.flake8
=> add houndci configuration and change flake8 config

pype/plugins/maya/publish/extract_camera_mayaAscii.py
We are now allowing export of non-baked cameras. Simply untick `bake to worldspace` and whole camera hierarchy will be exported as is.
=> PYPE-595: allow exports of non-baked cameras

pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/collect_render.py, pype/scripts/otio_burnin.py
This PR is adding ability of **Loader** to group renders from Maya with their AOV name.
=> PYPE 482 group aovs from maya render

pype/nuke/lib.py
create write node was not excepting with missing knobs on some nodes which should be created
=> PYPE-774 NUKE: better exception logic

.flake8
there was duplicated ignore option breaking flake8 linters who read this file.
=> fixing flake8 configuration

pype/nuke/lib.py, pype/plugins/nuke/publish/validate_script.py, pype/plugins/nukestudio/publish/collect_clips.py, pype/plugins/nukestudio/publish/collect_plates.py
- nks: collect plates better single or sequence collection
- nk: fps validator problem with fps
- nk: first build workfile was not getting jpeg sequences
=> client fixes requests

pype/plugins/global/publish/extract_burnin.py, pype/plugins/maya/create/create_yeti_cache.py, pype/plugins/maya/create/create_yeti_rig.py, pype/plugins/maya/load/load_look.py, pype/plugins/maya/load/load_reference.py, pype/plugins/maya/load/load_yeti_rig.py, pype/plugins/maya/publish/collect_look.py, pype/plugins/maya/publish/extract_yeti_rig.py, pype/plugins/nuke/publish/extract_thumbnail.py
Bundle of fixes, code changes should be self-explanatory.
=> bundle of fixes

pype/plugins/nuke/load/load_sequence.py
The file knob was referencing the existing containers file path and not updating to the new representation path.
=> Nuke file knob was not updating.

pype/nuke/__init__.py
This PR is dependent on https://github.com/pypeclub/avalon-core/pull/125
=> Check inventory versions on file open.

pype/services/adobe_communicator/lib/publish.py
- fixing the default host import to be from pype
=> some minor fixes for new premiere integration

pype/plugins/nukestudio/publish/collect_clips.py, pype/plugins/nukestudio/publish/collect_hierarchy_context.py
- check if hierarchy tag is not on two clips above each other
- check if two clips above each other are having the same name
=> fix(nks): duplicity in hierarchy tag and not matching names clips 

pype/plugins/global/publish/integrate_new.py
- also a bit of code cosmetics.
=> Enable additional metadata on representations

pype/plugins/nuke/create/create_backdrop.py, pype/plugins/nuke/create/create_gizmo.py
Before:
Notice the empty entry at the top of the list.
After:
=> Creator class exposed to the user.

pype/plugins/harmony/publish/extract_render.py
- Harmony always returns error code. Ignoring return code.
- Fix missing thumbnail.
=> Fix extract render

pype/plugins/harmony/publish/validate_instances.py
=> Validate instances

pype/hosts/harmony/__init__.py, pype/plugins/harmony/load/load_template_workfile.py, pype/plugins/harmony/publish/extract_save_scene.py, pype/plugins/harmony/publish/extract_template.py, pype/plugins/harmony/publish/extract_workfile.py
- Unified template export across workfile and templates.
- Fix scene saving per instance.
- Cleanup template loader.
=> Fix publishing workfile

pype/plugins/global/publish/validate_ffmpeg_installed.py
Ffmpeg validator is now a context plugin instead of instance.
=> Optimize processing

pype/plugins/standalonepublisher/publish/validate_shots.py
=> Validate shots

pype/plugins/standalonepublisher/publish/collect_shots.py
Shot names are collected from the editorial file instead of sequencial numbering.
=> Collect shots

pype/plugins/harmony/load/load_audio.py, pype/plugins/harmony/publish/extract_render.py
closes https://github.com/pypeclub/fourthwall-config/issues/18
=> Load audio

pype/hooks/photoshop/prelaunch.py
closes https://github.com/pypeclub/fourthwall-config/issues/14
Dependent PR: https://github.com/pypeclub/pype-config/pull/44
=> Install pywin requirement with prehook

pype/hooks/photoshop/prelaunch.py, pype/plugins/photoshop/publish/increment_workfile.py
and sneaky code cosmetic for Harmony.
=> Increment workfile

pype/plugins/global/publish/collect_avalon_entities.py
Only warn users about missing attributes.
=> Defaults for frameStart and frameEnd

pype/api.py, pype/lib.py, pype/modules/adobe_communicator/lib/io_nonsingleton.py, pype/modules/avalon_apps/rest_api.py, pype/modules/ftrack/ftrack_server/event_server_cli.py, pype/modules/ftrack/ftrack_server/lib.py, pype/modules/ftrack/ftrack_server/sub_event_storer.py, pype/modules/ftrack/lib/custom_db_connector.py, pype/modules/ftrack/lib/io_nonsingleton.py, pype/modules/logging/gui/models.py, pype/modules/logging/tray/logging_module.py, schema/session-2.0.json
There was a circular import when importing from pypeapp, which I couldnt resolve, so have copied the mongo url logic across.
=> Cloud Mongo

pype/hosts/harmony/__init__.py, pype/plugins/global/publish/integrate_new.py, pype/plugins/harmony/load/load_imagesequence.py, pype/plugins/harmony/load/load_palette.py, pype/plugins/harmony/publish/collect_palettes.py, pype/plugins/harmony/publish/extract_palette.py
depends on https://github.com/pypeclub/avalon-core/pull/159
=> Support palettes.

pype/plugins/standalonepublisher/publish/collect_shots.py
Currently the sequence start frame is hardcoded to 10:00:00:00, so can be expanded later to ask the user for this information. EDLs do not have any data about the sequence start frame.
=> Support publishing a subset of shots

pype/hosts/celaction/cli.py, pype/modules/adobe_communicator/lib/publish.py, pype/plugins/celaction/publish/collect_celaction_cli_kwargs.py, pype/plugins/celaction/publish/collect_celaction_instances.py, pype/plugins/celaction/publish/collect_render_path.py, pype/plugins/celaction/publish/submit_celaction_deadline.py, pype/plugins/global/publish/submit_publish_job.py
- conversion from pype to pype.hosts
dependent PR:
https://github.com/pypeclub/pype-config/pull/56
=> [draft] Celaction and Premiere workflow glithes

pype/hooks/premiere/prelaunch.py, pype/plugins/premiere/publish/collect_frameranges.py, pype/plugins/premiere/publish/collect_instance_representations.py, pype/plugins/premiere/publish/validate_auto_sync_off.py
- prelaunch is modifying registry now for extension to be working
- plugins reaorder
- repair function in validator didn't work
=> premiere workflow fixes

.gitignore
This adds only mac related stuff into `.gitignore`.
See pypeclub/pype-setup#48 and pypeclub/pype-config#67
=> Mac tweaks

pype/plugins/nuke/publish/submit_nuke_deadline.py
=> Use published workfile for rendering.

pype/plugins/celaction/publish/integrate_version_up.py
- not correct family and order
=> fix(celaction):  version up

pype/plugins/celaction/publish/collect_render_path.py, pype/plugins/global/publish/submit_publish_job.py
- path was pointing to wrong root folder
=> Celaction: metadata json folder fixes on path 

pype/plugins/celaction/publish/integrate_version_up.py
- it was not versioning up with clearing any additional comments or minor versions
=> CelAction - version up method taken fro pype.lib 

pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/submit_maya_deadline.py
This PR fix issue when only one frame was rendered. Submiting and publishing failed.
🌞 **Freshdesk Ticket ID** [#62](https://pype.freshdesk.com/a/tickets/62)
|---|
=> Maya: support for single frame renders

pype/api.py, pype/lib.py, pype/plugins/nuke/publish/collect_review.py
- also added get_latest_version method to library.
Resolves https://github.com/pypeclub/pype/issues/368
=> Adding "audioMain" to Nuke reviews.

pype/modules/ftrack/actions/action_delivery.py
- delivery action allows to enter delivery folder but that is not used in code so it doesn't work as expected
- entered path is replacing root key in filled path (multiroot included)
=> Delivery action can now work with entered path

pype/tools/tray/modules_imports.json
- added Websocket server to module imports
=> Websocket server added to module imports

pype/plugins/global/publish/extract_jpeg.py, pype/plugins/global/publish/extract_review.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/publish/collect_render.py
This enables a workflow where you can use DWAA compression while #382 is under way.
=> Optional skip review on renders.

pype/hooks/celaction/prelaunch.py
was not detecting last workfile version properly
dependency:
avalon-core: https://github.com/pypeclub/avalon-core/pull/180
=> celaction last workfile

pype/lib.py
This is for the work file builder code.
=> Get linked assets from "inputs".

pype/plugins/nukestudio/publish/collect_reviews.py
- The code logic resulted in the last track review in the context being the review file for all shots. Comparing shot naming as well to isolate to correct clip instance.
- Remove "- review" from label cause its already in subset.
=> Fix collect reviews

pype/plugins/maya/publish/submit_maya_deadline.py
**Draft Tile Assembler** needed more options in its configuration file. Also the way tiles are ordered seems to matter to Draft and so it needs to be changed to:
```
.---.---.---.
| 2 | 5 | 8 | 
+---+---+---+
| 1 | 4 | 7 |     Where 0 (x=0, y=0) and 8 (x=2, y=2)
+---+---+---+
| 0 | 3 | 6 |
.---.---.---.
```
=> Maya: Fix tile order for Draft Tile Assembler

pype/plugins/global/publish/extract_burnin.py
- adding the suffix `_[burnin profile name]` only in case there is more then one filtered burnin profiles
=> 388 Extract review a representation name with `*_burnin`

pype/plugins/global/publish/extract_burnin.py
=> Revert "388 Extract review a representation name with `*_burnin`"

pype/tools/settings/settings/widgets/item_types.py
- added few docstrings to important classes
=> Added doctrings settings

pype/tools/settings/settings/gui_schemas/system_schema/1_examples.json, pype/tools/settings/settings/widgets/item_types.py
- list item type can't be used as widget in other item types
- gave ability to list item be used as widget
=> List widget can be used as widget

pype/modules/ftrack/ftrack_server/lib.py
- this bug may happen when more than one Ftrack event storers are running
- when same event is more than once in mongo only one mongo document is marked as completed
- mark as completed is explicit about MongoID not event id
=> Avoid bugs when Ftrack event is duplicated in mongo

pype/lib.py
- launch of host from launcher tool also change Ftrack status and start Ftrack timer for the task
- this feature is quite "hardcoded" and should be moved to prelaunch hook when we'll implement them in a better way
=> Launcher tool launch hosts like from ftrack

pype/plugins/global/publish/extract_burnin.py
adding `_[burnin profile name]` as suffix to representation and file name only in case there is more filtered burnin profiles
=> Extract review a representation name with `*_burnin`

pype/tools/settings/settings/widgets/item_types.py, pype/tools/settings/settings/widgets/widgets.py
- `dict` item has checkbox before label, not after
=> Dict checkbox before label

pype/tools/settings/settings/style/style.css, pype/tools/settings/settings/widgets/item_types.py
- item `path-widget` should now work as expected at least what I was able to test
=> Path widget fix

pype/tools/pyblish_pype/model.py, pype/tools/pyblish_pype/window.py
- terminal items are much faster now
=> Pyblish gui faster Terminal

pype/modules/rest_api/rest_api.py
- rest api module is not using `QCore.QThread` for running but python's `threading.Thread`
- RestApi is not using PyQt at all now
=> RestApi module without Qt

pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py, pype/plugins/nukestudio/publish/extract_review_cutup_video.py
- space in path issue
- ftrack hierarchy had prints styles for p3
=> NKS small fixes

pype/modules/ftrack/__init__.py, pype/modules/ftrack/ftrack_server/__init__.py, pype/modules/ftrack/ftrack_server/custom_db_connector.py, pype/modules/ftrack/ftrack_server/lib.py, pype/modules/ftrack/ftrack_server/sub_event_storer.py, pype/modules/ftrack/lib/avalon_sync.py, pype/modules/ftrack/lib/ftrack_base_handler.py, pype/modules/ftrack/tray/login_dialog.py, pype/modules/ftrack/tray/login_tools.py
- this PR only prepare module to be able used more as pype module
- ftrack module is already separated
- modified imports - they are more explicit now
- fixed ftrack login thread
=> Ftrack module without Qt

pype/tools/settings/settings/widgets/item_types.py, pype/tools/settings/settings/widgets/widgets.py
- implemented nice looking checkbox (with animations)
=> Settings GUI has nice checkbox

pype/hosts/harmony/__init__.py, pype/plugins/harmony/create/create_render.py, pype/plugins/harmony/load/load_audio.py, pype/plugins/harmony/load/load_background.py, pype/plugins/harmony/load/load_imagesequence.py, pype/plugins/harmony/load/load_template_workfile.py, pype/plugins/harmony/publish/collect_current_file.py, pype/plugins/harmony/publish/collect_palettes.py, pype/plugins/harmony/publish/extract_palette.py, pype/plugins/harmony/publish/extract_render.py, pype/plugins/harmony/publish/extract_template.py, pype/plugins/harmony/publish/extract_workfile.py, pype/plugins/harmony/publish/validate_audio.py, pype/plugins/harmony/publish/validate_scene_settings.py
**UUID** prefixed function were incompatible with [ECMA](https://www.ecma-international.org/publications/standards/Ecma-262.htm). Dashes were replaced with underscores and prefixed with letter `f`.
Fixed unnecessary creation and deletion of `QApplication during` startup.
🏴 **Depends on:** pypeclub/avalon-core#202
|---|
=> Harmony: function signature

pype/tools/standalonepublish/__main__.py
- added application icon to standalone publisher tool
=> Standalone publisher now has icon

pype/plugins/harmony/publish/extract_render.py
- audio file is not added to `instance.data` if audio file was not created
=> Audio file existence check

pype/plugins/nukestudio/publish/collect_hierarchy_context.py, pype/plugins/nukestudio/publish/collect_plates.py, pype/plugins/nukestudio/publish/collect_reviews.py, pype/plugins/nukestudio/publish/extract_review_cutup_video.py
fix(nks): preview to review tag on representation 
order of hierarchy context was wrong
=> nks little bits

pype/plugins/global/publish/extract_review.py
- safer handle values getting (just to be sure)
- both start and end handle values must be set
- store information about valid handles values
- valid handle values means that they are both different than 0
- now we check of "no-handles" tag but if handles are set to 0 it is processing more in ffmpeg process without advantage
- do not set start offset if handle start is set to 0
- set video duration if input or output is sequence of images
- moved few lines to better spot
=> Extract review small enhancement

pype/plugins/hiero/publish/extract_review_cutup.py
=> 659 Hiero: Review video file adding one frame to the end

pype/lib.py
This orders the loading of representations as seen in the preset. For example:
```
{
"tasks": ["lighting"],
"current_context": [{
"families": ["camera", "animation"],
"repre_names": ["abc"],
"loaders": ["ReferenceLoader"]
},{
"families": ["pointcache"],
"repre_names": ["abc"],
"loaders": ["ReferenceLoader"]
},{
"families": ["render"],
"subset_name_filters": ["renderLightingPlate"],
"repre_names": ["exr"],
"loaders": ["ImagePlaneLoader"]
}]
}
```
- will load the current context camera before the current context animation, because its laid out as `["camera", "animation"]`.
- will load the current context camera and animation before the pointcache, because of the order of the presets.
This is useful when you need to predict a workflow. For example we needed to have the camera loaded in …
=> Order workfile build as presets.

pype/plugins/maya/load/load_image_plane.py
Instead of using the current selection, we ask the user about which non-default camera to use for the image plane. If no camera are selected we default back to asking about creating a new camera.
=> Ask user to select non-default camera from scene or create a new.

pype/lib/__init__.py, pype/lib/abstract_collect_render.py, pype/lib/abstract_expected_files.py, pype/lib/abstract_metaplugins.py, pype/lib/abstract_submit_deadline.py, pype/plugins/aftereffects/publish/collect_current_file.py, pype/plugins/aftereffects/publish/collect_instances.py, pype/plugins/aftereffects/publish/collect_render.py, pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
=> Feature #698 after effects publish to deadline

pype/tools/settings/settings/widgets/item_types.py
- settings item `modifiable-dict` can not have label
=> Modifiable dict without label

pype/settings/lib.py, pype/tools/settings/settings/widgets/base.py
- important changes modified only in develop but has huge effect in current development
- commits are cherry picked (not sure if that will make merge to develop clear?)
- fixed cleanup of widgts in Project settings window
=> Settings cherry pick develop changes to 2.x/develop

pype/lib/abstract_submit_deadline.py, pype/modules/websocket_server/stubs/aftereffects_server_stub.py, pype/plugins/aftereffects/publish/collect_audio.py, pype/plugins/aftereffects/publish/collect_render.py, pype/plugins/aftereffects/publish/extract_save_scene.py, pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py, pype/plugins/global/publish/submit_publish_job.py
Use extension configured in Render Queue.
If extension is not a sequence (mov, avi), only single rendering task is created.
Requires:
pypeclub/avalon-core#229
=> After Effects fixes

pype/tools/settings/settings/widgets/anatomy_types.py
- anatomy item can load dynamically other items than `templates`, `roots` and `imageio`
=> Anatomy with dynamic schemas

pype/settings/lib.py
- implemented `clear_metadata_from_settings` to remove metadata from loaded settings
=> Clear metadata from loaded settings

pype/settings/lib.py
- do not remove metadata from system settings on loading of environments
=> Loading of environments use system settings with metadata

pype/tools/settings/settings/style/style.css, pype/tools/settings/settings/widgets/base.py
Start of a style cleanup on settings gui as we're approaching the finish with this. Up to a discussion whether we should keep the same style as avalon tools, or divert a little bit to differentiate between pype exclusive tools and avalon core.
=> settings GUI styles

pype/plugins/ftrack/publish/validate_custom_ftrack_attributes.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/create/create_rendersetup.py, pype/plugins/maya/publish/extract_camera_mayaScene.py, pype/plugins/maya/publish/extract_maya_scene_raw.py, pype/plugins/maya/publish/extract_model.py, pype/plugins/maya/publish/extract_playblast.py, pype/plugins/maya/publish/extract_rig.py, pype/plugins/maya/publish/extract_thumbnail.py, pype/plugins/maya/publish/extract_yeti_rig.py, pype/plugins/maya/publish/submit_maya_muster.py, pype/plugins/maya/publish/validate_attributes.py, pype/plugins/maya/publish/validate_muster_connection.py, pype/settings/defaults/project_settings/ftrack.json, pype/settings/defaults/project_settings/global.json, pype/settings/defaults/project_settings/maya.json, pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json, pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_tools.json, pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_capture.json, pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_publish.json
all maya plugins are now independent of `context["presets"]`
=> Maya plugins use settings

pype/plugins/global/publish/extract_burnin.py
This PR removes the old way of creating burnins, considering it is back from v1.0 and is not use in production anymore
=> Remove legacy extract burnin script

pype/lib/applications.py, pype/plugins/global/publish/collect_anatomy_context_data.py
- used `ApplicationManager` in `CollectAnatomyContextData` to get key for `"app"` in templates
=> Use app manager in context collector

igniter/tools.py, pype.py
- if pype is executed with different cwd adding acre with relative path won't work
- add full path to acre module
=> Acre modul path bug

pype/hosts/harmony/js/PypeHarmony.js, pype/hosts/harmony/js/loaders/ImageSequenceLoader.js, pype/plugins/harmony/load/load_palette.py
This bugfix is for problems with *ImageSequenceLoader* and palette loader in Harmony. See #803 
🏴 **Related to:** pypeclub/avalon-core#251
|---|
closes #803
=> Harmony: fix palette and image sequence loader

pype/modules/__init__.py, pype/modules/base.py, pype/modules/settings_module.py, pype/settings/lib.py, pype/tools/settings/__main__.py, pype/tools/settings/settings/widgets/window.py
- added settings module to be able show settings gui from tray
- default settings are not cached (easier for development)
=> Settings in tray

pype/modules/ftrack/events/event_thumbnail_updates.py, pype/modules/ftrack/events/event_version_to_task_statuses.py, pype/modules/ftrack/ftrack_server/event_server_cli.py, pype/modules/ftrack/ftrack_server/ftrack_server.py, pype/modules/ftrack/lib/ftrack_base_handler.py, pype/pype_commands.py
- base of this PR is branch from PR https://github.com/pypeclub/pype/pull/821 which is not merged at the time of creation
- `ThumbnailEvents` handler use project settings in right way and faster
- event handler is also using new settings key `"levels"`
- task is not part of levels as task is not hierarchically connected to AssetVersion
=> Thumbnail event handler with settings

pype/pype_commands.py, pype/tools/settings/__init__.py, pype/tools/settings/__main__.py
- settings gui is not created from new subprocess when launched through pype's `cli`
=> Settings tool without subprocess

pype/modules/ftrack/events/event_task_to_parent_status.py, pype/settings/defaults/project_settings/ftrack.json, pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
- Task to parent status event handler was converted to use settings
=> Task to parent with settings

pype/modules/ftrack/actions/action_clean_hierarchical_attributes.py, pype/modules/ftrack/actions/action_create_cust_attrs.py, pype/modules/ftrack/actions/action_delete_asset.py, pype/modules/ftrack/actions/action_delete_old_versions.py, pype/modules/ftrack/actions/action_delivery.py, pype/modules/ftrack/actions/action_job_killer.py, pype/modules/ftrack/actions/action_prepare_project.py, pype/modules/ftrack/actions/action_seed.py, pype/modules/ftrack/actions/action_store_thumbnails_to_avalon.py, pype/modules/ftrack/actions/action_sync_to_avalon.py, pype/modules/ftrack/actions/action_thumbnail_to_childern.py, pype/modules/ftrack/events/event_task_to_parent_status.py, pype/modules/ftrack/events/event_task_to_version_status.py, pype/modules/ftrack/events/event_thumbnail_updates.py, pype/modules/ftrack/events/event_version_to_task_statuses.py, pype/modules/ftrack/lib/ftrack_action_handler.py, pype/modules/ftrack/lib/ftrack_base_handler.py, pype/modules/ftrack/lib/ftrack_event_handler.py, pype/settings/defaults/project_settings/ftrack.json
- ftrack actions are using settings to determine if should be enabled and for which user roles are available
=> Ftrack actions with settings

pype/lib/terminal.py
- Terminal's `_initialize` method set `_initialized` to `True` at the beginning but may not finish yet and there is small change that before it is really initialized other thread will try to access `log` method but initialization is still in progress
- `_initialized` is set to `True` only when is done with initialization
- added threading lock to Terminal to lock thread or wait until is lock is released to not do `_initialize` multipletime in one process
=> Thread safe Terminal

pype/modules/rest_api/rest_api.py
Finding free port is much faster now.
- finding free port is not done with trying to connect to socket (which is slow due to timeout) but trying to bind to it
=> Rest api faster find port

pype/tools/launcher/models.py, pype/tools/launcher/widgets.py, pype/tools/launcher/window.py
- apply fix actions discover in launcher tool from pype 2 PR
|---|---|
|pype|https://github.com/pypeclub/pype/pull/896/files|
=> Launcher fix actions discover

pype/hosts/tvpaint/plugins/load/load_sound.py
- implemented sound importer for TVpaint
|:black_flag:|Pype 2.x PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/893|
=> TVPaint audio/sound loader

pype/lib/anatomy.py
- applied `Anatomy` fix and feature PRs from pype-setup
- fix of `find_root_template_from_path` where empty roots are skipped 
- added methods to be able fill root with environment variable
|Related PRs in pype setup|
|---|
|https://github.com/pypeclub/pype-setup/pull/82|
|https://github.com/pypeclub/pype-setup/pull/84|
=> Anatomy updates from pype setup

pype/hosts/nuke/api/lib.py
pype3 version of https://github.com/pypeclub/pype/pull/909
=> nuke: bake writes colorspace

pype/modules/websocket_server/stubs/photoshop_server_stub.py
Version for Pype3
|---|---|
|pype|https://github.com/pypeclub/pype/pull/920
=> Photoshop fix - create called on single layer

pype/plugins/nuke/load/load_image.py
https://pypeclub.slack.com/archives/C01DQGA8CB0/p1611829903064400
=> nuke: missing `file` knob update 

pype/hosts/nuke/plugins/load/load_image.py
pype3 version of PR from https://github.com/pypeclub/pype/pull/933
=> nuke: missing `file` knob update

pype/hooks/photoshop/prelaunch.py
|---|---|
|pype|https://github.com/pypeclub/pype/pull/940
=> PS - safer handling of loading of workfile

pype/modules/ftrack/actions/action_djvview.py, pype/plugins/global/load/open_djv.py
- new version of DJV does not support same arguments
- removed unsused arguments for DJV
|---|---|
|pype|https://github.com/pypeclub/pype/pull/955|
=> DJV new version arguments

pype/plugins/global/publish/integrate_new.py
- subset document may not main family and may not be at first place
- instance family is added to subset families and is added as first
|---|---|
|pype|https://github.com/pypeclub/pype/pull/957|
=> Subset family is now stored in subset document

pype/modules/ftrack/lib/avalon_sync.py
- during sync to avalon are project's tasks compared to previous state of project and pass only changes between them to be updated but tasks must be updated as one key and is not possible to pass only changes
- due to this on each sync are task types chaning between 2 states
- modification of any task type is always resolved as all task types must be updated
|---|---|
|pype|https://github.com/pypeclub/pype/pull/972|
=> Fix update of project's tasks on Ftrack sync

pype/hosts/nuke/plugins/publish/extract_thumbnail.py
related to https://github.com/pypeclub/pype/pull/984
=> fix(nuke): missing preset's variable 

pype/hosts/maya/api/plugin.py
=> Maya: Alembic only set attributes that exists

pype/hosts/nuke/plugins/load/load_mov.py
related https://github.com/pypeclub/pype/pull/971
=> nuke: wrong frame offset in mov loader

pype/plugins/nuke/publish/submit_nuke_deadline.py
- adding `nuke` related env vars
- adding licensing env vars
=> Nuke: add nuke related env var to sumbission 

pype/plugins/nuke/publish/submit_nuke_deadline.py
- deadline submission parameters from presets (group and department)
=> Nuke deadline presets

pype/hosts/harmony/__init__.py, pype/hosts/harmony/js/PypeHarmony.js, pype/hosts/harmony/js/creators/CreateRender.js, pype/hosts/harmony/js/loaders/ImageSequenceLoader.js, pype/hosts/harmony/js/loaders/TemplateLoader.js, pype/hosts/harmony/js/publish/CollectCurrentFile.js, pype/hosts/harmony/js/publish/CollectFarmRender.js, pype/hosts/harmony/js/publish/CollectPalettes.js, pype/hosts/harmony/js/publish/ExtractPalette.js, pype/hosts/harmony/js/publish/ExtractTemplate.js, pype/lib/abstract_collect_render.py, pype/lib/avalon_context.py, pype/plugins/harmony/create/create_render.py, pype/plugins/harmony/load/load_imagesequence.py, pype/plugins/harmony/publish/collect_audio.py, pype/plugins/harmony/publish/collect_farm_render.py, pype/plugins/harmony/publish/collect_instances.py, pype/plugins/harmony/publish/collect_palettes.py, pype/plugins/harmony/publish/collect_scene.py, pype/plugins/harmony/publish/extract_render.py, pype/plugins/harmony/publish/submit_harmony_deadline..py, pype/plugins/harmony/publish/validate_scene_settings.py
Implemented handles.
Contain bunch of fixes found in pre-deploy of deadline implementation tests to FW
Requires:
pypeclub/avalon-core#279
=> Harmony: render local and handle fixes

pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
https://github.com/pypeclub/pype/pull/988
- adding `nuke` related env vars
- adding licensing env vars
=> fix(nuke): add nuke related env var to sumbission

pype/plugins/photoshop/publish/collect_instances.py, pype/plugins/photoshop/publish/collect_review.py
2.x PR:
https://github.com/pypeclub/pype/pull/1006/files
=> PS fix - removed unwanted functions from pywin32

pype/modules/ftrack/actions/action_clone_review_session.py
Important for context of what is being reviewed.
=> Clone description of review session objects.

pype/plugins/global/load/delete_old_versions.py
Final touches of PR https://github.com/pypeclub/pype/pull/445
- convert ftrack action to delete version into loader action
- renamed option keys: "version" -> "versions_to_keep" and "publish" -> "remove_publish_folder"
- subset is archived if all versions are deleted
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1012|
=> Delete version as loader action

pype/hosts/nuke/api/lib.py, pype/hosts/nuke/plugins/publish/precollect_instances.py, pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
=> Nuke small fixes

pype/hosts/maya/api/attributes.py, pype/hosts/maya/plugins/publish/collect_renderable_camera.py
=> Maya: Pype 3 implementation of #1053

pype/tools/settings/settings/widgets/item_widgets.py, pype/tools/settings/settings/widgets/multiselection_combobox.py
- mutliselection combobox does not work when item is clicked
- fixed order of code when combobox items are set as checkable
=> Multiselect combobox works

pype/tools/settings/settings/widgets/categories.py, pype/tools/settings/settings/widgets/widgets.py
- https://github.com/pypeclub/pype/pull/1075 caused some issues with AVALON_MONGO which was used in settings gui
- removed usage of the value from settings
=> Removed usage of AVALON_MONGO from settings

pype/hosts/photoshop/plugins/publish/collect_workfile.py, pype/hosts/photoshop/plugins/publish/increment_workfile.py
Requires:
pypeclub/avalon-core#291
2.x version:
pypeclub/pype#1078
=> PS - added .psb support

start.py
Fix of changes in PR https://github.com/pypeclub/pype/pull/1111
- global environments are parsed before merge
=> Parse global environments

pype/hosts/aftereffects/plugins/create/create_render.py, pype/hosts/aftereffects/plugins/load/load_background.py, pype/hosts/aftereffects/plugins/load/load_file.py
Fixes instance creation
Adds highlights for publishable or loaded instances
=> AE add subset manager

pype/hosts/nuke/menu.py
Adding feature to pype to be able to assign default pype menu item shortcuts
https://github.com/pypeclub/pype-config/pull/103
=> 1071 Nuke: shortcuts for Pype menu

pype/hosts/nuke/plugins/create/create_backdrop.py
Inheritance of creator plugin `CreateBackdrop` is broken since https://github.com/pypeclub/pype/pull/1068 .
- fixed inheritance of `CreateBackdrop`
=> Fix inheritance of CreateBackdrop creator

pype/__init__.py, pype/lib/__init__.py, pype/lib/avalon_context.py, pype/modules/timers_manager/rest_api.py, pype/modules/timers_manager/timers_manager.py
Used "taskChanged" signal to trigger change of all connected timers when task is changed in the context.
Closes #21
=> #21 - Change timers after task change

pype/hosts/nuke/api/menu.py, pype/settings/defaults/project_settings/nuke.json, pype/settings/entities/schemas/projects_schema/schema_project_nuke.json
pype3 impementation of https://github.com/pypeclub/pype/issues/1071
=> Nuke: shortcuts for Pype menu

pype/modules/ftrack/lib/avalon_sync.py
PR fix changes from https://github.com/pypeclub/pype/pull/1145
- changed used settings in sync to avalon
=> Temporary fix of short names from settings

pype/plugins/maya/publish/submit_maya_deadline.py
=> Maya: support for Deadline Group and Limit Groups - backport 2.x

pype/modules/deadline/plugins/publish/submit_maya_deadline.py, pype/settings/defaults/project_settings/deadline.json, pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
This adds ability to set Deadline Group and Limit Groups with settings for jobs submitted from Maya.
🎫 **Ticket:** [#574](https://support.pype.club/a/tickets/574)
=> Maya: support for Deadline Group and Limit Groups

pype/plugins/maya/publish/submit_maya_deadline.py
Fixing typo from previous merge of #1156 and pretending I didn't do it.
=> Maya: Submit to Deadline - fix typo in condition

pype/plugins/maya/publish/extract_playblast.py
Wrong method called "getName" > "name"
=> Fix getting the camera name.

pype/hooks/pre_python2_vendor.py, pype/lib/applications.py, pype/settings/defaults/system_settings/applications.json, pype/settings/entities/input_entities.py, pype/settings/entities/item_entities.py, pype/settings/entities/root_entities.py, pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json, pype/tools/settings/local_settings/apps_widget.py, pype/tools/settings/settings/widgets/item_widgets.py
- executables and arguments are stored separatelly in settings
- arguments are not stored per executable but are stored per platform
- for all executables of single platform are arguments the same
=> Application executables and arguments separated

pype/settings/defaults/project_settings/global.json, pype/settings/entities/input_entities.py, pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Settings schemas of opacity for ExtractBurnin plugin can be only integer but opacity is defined with value from 0 - 1
- number entities of opacity have 2 decimal places, minimum value 0 and maximum value 1
- `NumberEntity` can convert string to number if possible using regexes
=> Extract burnin settings fix

pype/settings/entities/enum_entity.py
- fix super call for python 2 compatibility
=> Enum super call fix

pype/settings/handlers.py
- fix check of attribute values in settings handler
=> Settings handler properties fix

pype/hosts/houdini/startup/MainMenuCommon.XML, pype/hosts/houdini/startup/scripts/123.py, pype/settings/defaults/system_settings/applications.json, pype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
houdini wasn't used for a while and it had wrong install call in the startup script
=> update houdini menu

pype/tools/pyblish_pype/model.py
- show error message in terminal item detail
|:black_flag: |Pype 3 PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1205|
=> Error message in pyblish UI

pype/modules/ftrack/lib/settings.py, pype/settings/defaults/system_settings/modules.json, pype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
- removed settings of mongo variables for ftrack event server
=> Remove ftrack mongo settings

pype/tools/settings/settings/widgets/categories.py
- catch exceptions and show a dialog with details if save of settings crashes
=> Catch exceptions on save in settings ui

pype/hosts/nuke/plugins/load/load_image.py, pype/hosts/nuke/plugins/load/load_mov.py, pype/hosts/nuke/plugins/load/load_sequence.py, pype/settings/defaults/project_settings/nuke.json, pype/settings/entities/schemas/projects_schema/schemas/template_loader_plugin.json
pype3 implementation of https://github.com/pypeclub/pype/pull/1146
=> Nuke: adding preset for a Read node name to all img and mov Loaders

pype/hosts/nuke/api/lib.py
implementation of https://github.com/pypeclub/pype/pull/1114/files
=> Nuke: AvalonTab as default for write node

igniter/tools.py, pype/settings/constants.py, pype/settings/defaults/system_settings/general.json, pype/settings/entities/schemas/system_schema/schema_general.json, pype/settings/handlers.py
- added new type of settings named `global_settings`
- `global_settings` are saved on each system settings save
- the values of global settings can't be modified directly
- changed how global settings are loaded in igniter
- `pype_path` should be loading as expected
- removed not used `load_environments` function from `igniter.tools`
=> Pype global settings

openpype/hosts/celaction/api/cli.py, openpype/tools/standalonepublish/widgets/widget_components.py
- removed usage of `AVALON_HIERARCHY` and `AVALON_PROJECTCODE` environment variables
=> Remove unused deprecated environment variables

README.md, website/docs/dev_build.md
Adding more info about Linux build environments using **pyenv** to readme.
=> Docs: Update Linux build environment

pype/plugins/aftereffects/publish/collect_render.py
2.x had a bit different structure, fixed, standardized across releases
=> AE remove orphaned instance from workfile - fix self.stub

openpype/settings/defaults/project_anatomy/attributes.json, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/defaults/project_settings/global.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/defaults/project_settings/standalonepublisher.json, openpype/settings/defaults/system_settings/applications.json
- applications in default anatomy is empty list
- intent in ftrack has filled template
- added missing `-gamma` argument in ffmpeg and fixed `gamma` to `-gamma`
- swap default resolution in maya (width <-> height)
- removed `CREATE_NEW_CONSOLE` from blender (is not used)
- added `QT_PREFERRED_BINDING` to blender
- fix maya's startup script in `PYTHONPATH`
=> Settings values cleanup

openpype/hosts/tvpaint/api/__init__.py, openpype/hosts/tvpaint/api/lib.py
This sets the TVP project settings when launching for the first time.
Pype 3 version of https://github.com/pypeclub/pype/pull/1299
Logic was changed to check existence of `AVALON_LAST_WORKFILE` on start as in Pype 3 are not templates yet.
||Pype 2 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1299|
=> Set initial project settings

openpype/settings/defaults/project_anatomy/attributes.json
- renamed applicaitons in default anatomy to match new app name convention
=> Fix default application names

openpype/hosts/maya/plugins/create/create_look.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
This is OpenPype 3 version of #1328
=> Maya: Make tx option configurable with presets - OpenPype 3

openpype/settings/defaults/project_settings/maya.json
- new schema of `CreateLook` plugin does not have saved default values
- saved defaults of new schemas
=> Fill default values of CreateLook

openpype/settings/defaults/project_anatomy/attributes.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/defaults/system_settings/applications.json, openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json, openpype/settings/entities/schemas/system_schema/schema_modules.json
this PR also tweaks some other minor defaults
Blender version to 2.91
Sync server labels to Site Sync
=> Add Maya 2022 and Nuke 13 for testing

openpype/tools/settings/settings/widgets/multiselection_combobox.py
- sometimes weird bug may happen in multiselection combobox (reason unknown) this may help
- fix items bigger than item's width
=> Mutliselection size calculation fix

pype/hosts/nuke/lib.py, pype/plugins/global/publish/submit_publish_job.py, pype/plugins/nuke/publish/collect_instances.py, pype/plugins/nuke/publish/collect_writes.py, pype/plugins/nuke/publish/validate_rendered_frames.py
- fixing prerender publishing workflow
- fixing viewer to be set to correct colorspace on start new script
- not opening control nuke panes when creating write node group
=> Nuke: freschdesk tickets

openpype/hosts/nuke/plugins/publish/precollect_instances.py, openpype/hosts/nuke/plugins/publish/precollect_writes.py, openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
implementing some commits form https://github.com/pypeclub/pype/pull/1308
following the PR for openpype3 https://github.com/pypeclub/pype/pull/1309
Also, it is improving code from merged https://github.com/pypeclub/pype/pull/1301
mainly:
- mishmash with families
- validator rendered frames were broken
=> Nuke: freschdesk ticket v2

openpype/modules/clockify/clockify_api.py
- do not create secure item on clockify api initialization
=> Clockify keyring usage fix

openpype/modules/idle_manager/idle_module.py
- idle manager is disabled for mac users
=> Temporary fix of Idle manager on MacOs

openpype/hosts/aftereffects/api/__init__.py, openpype/hosts/aftereffects/plugins/publish/collect_render.py, openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
2.x version:
https://github.com/pypeclub/pype/pull/1363
=> AE added scene duration validation

openpype/hosts/maya/plugins/publish/extract_redshift_proxy.py
Fixing sequence start frame for #1358
=> Maya: Redshift proxy - fix first frame for sequence

pype/plugins/global/publish/extract_review.py
- backward compatible with single float for config.
- support for pillar boxes.
- expose thickness of boxes to config.
- expose color of boxes to config.
Config of `letterbox` on the presets can be changed to a dictionary;
```
{
"state": "pillar",
"ratio": 1.777777,
"thickness": 3,
"color": "black"
}
```
||Pype 3 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1400|
=> Enhance review letterbox feature.

pype/plugins/nuke/publish/submit_nuke_deadline.py
implementation of https://github.com/pypeclub/OpenPype/pull/1394
=> Nuke: deadline submission with gpu

start.py
- validate loaded Mongo url even if is already set
- run igniter if can't connect to already defined mongo url
=> Validate MongoDB Url on start

pype/plugins/nuke/load/load_mov.py, pype/plugins/nuke/load/load_sequence.py
close https://github.com/pypeclub/client/issues/57
=> Nuke: fixing undo for loaded mov and sequence

pype/hosts/aftereffects/__init__.py
1001 to 1003 > duration 3 > 3 frames should be created
=> AE - validation for duration was 1 frame shorter

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/plugins/publish/collect_render.py, openpype/hosts/maya/startup/userSetup.py, openpype/modules/deadline/plugins/publish/submit_maya_deadline.py, vendor/deadline/custom/plugins/GlobalJobPreLoad.py
MayaPype plugin removed, replaced with injection of env vars by GlobalJobPreLoad.py (must be deployed to DL)
=> Bugfix Maya in deadline for OpenPype

openpype/tools/settings/settings/widgets/dict_mutable_widget.py
- made loading of modifiable dict item faster in settings UI
=> Faster settings UI loading

openpype/modules/ftrack/ftrack_module.py
- ftrack module raise error with more specific warning messages if save didn't go well
=> Ftrack specific settings save warning messages

openpype/plugins/publish/extract_burnin.py, openpype/scripts/otio_burnin.py
- ExtractBurnins can export sequence of files with burnins using clique collections and small modification of burnin script
- change should not affect single file export
=> Extract burnins with sequences

igniter/install_dialog.py
- buttons are enabled back only if something went wrong
=> Igniter buttons enable/disable fix

openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json, openpype/tools/settings/settings/widgets/item_widgets.py
- path entity may have defined placeholder for inputs
=> Path entity with placeholder

openpype/settings/entities/list_entity.py
Removing item from list entity does not mark list entity that has overrides which cause that it seems that entity has changes but are not stored to settings.
- list entity triggers `on_child_change` on add/remove of children outside item initialization
=> List entity catch add/remove item changes properly

openpype/hosts/resolve/api/lib.py, openpype/hosts/resolve/api/plugin.py, openpype/hosts/resolve/plugins/publish/precollect_instances.py, openpype/plugins/publish/collect_otio_review.py, openpype/settings/defaults/project_settings/global.json
- handles only to available source material
- review track get from instance
- create review track was duplicating to all markers
- code readability improvements
=> Resolve: additional fixes of publishing workflow

openpype/hosts/nuke/api/lib.py
implementation of https://github.com/pypeclub/OpenPype/pull/1494
=> nuke: space in node name breaking process

openpype/hosts/maya/plugins/publish/extract_thumbnail.py
=> Use instance frame start instead of timeline

tests/igniter/test_bootstrap_repos.py, tests/openpype/lib/test_user_settings.py, tools/run_tests.sh
This fix include fixes so all tests work again and pass.
=> Tests: fix pype -> openpype to make tests work again

pype/plugins/nuke/load/load_mov.py, pype/plugins/nuke/load/load_sequence.py
closing https://github.com/pypeclub/OpenPype/issues/1352
=> nuke: fixing start_at with option gui

openpype/hosts/nuke/plugins/load/load_mov.py, openpype/hosts/nuke/plugins/load/load_sequence.py
closed https://github.com/pypeclub/OpenPype/issues/1352
implementation of 2xDev PR: https://github.com/pypeclub/OpenPype/pull/1507
=> 3.0 | nuke: fixing start_at with option gui

tools/build.ps1, tools/build_dependencies.py
This is simplifying output of `copy_dependencies` part and adding progress bars to better see whats happening.
=> OpenPype: Build - Add progress bars

openpype/tools/mayalookassigner/app.py
This fixes broken look assignment for non vray proxy object.
=> Maya: fix look assignment

tools/build.ps1, tools/build.sh
`build.ps1|sh` now accept argument `--no-submodule-update` do disable automatic git submodule updates.
=> OpenPype: disable submodule update with `--no-submodule-update`

pype/lib/delivery.py, pype/plugins/global/load/delivery.py
2.x version of https://github.com/pypeclub/OpenPype/pull/1546
Closes pypeclub/client#68
Requires: https://github.com/pypeclub/avalon-core/pull/340
=> Feature Delivery in library loader

pype/hosts/celaction/cli.py, pype/plugins/celaction/publish/collect_celaction_instances.py
=> Celaction publishing

pype/plugins/maya/publish/extract_playblast.py
- Unrecognized `filepath` variable.
- Unused `input_path` variable.
- Formatting issues.
=> Fix Maya playblast.

openpype/plugins/publish/extract_otio_audio_tracks.py, openpype/plugins/publish/extract_otio_review.py
- ffmpeg path with space
- no need to add `ftrackreview` to tags
=> Hiero: publishing issues 

openpype/tools/workfiles/app.py
- workfiles tool has set current asset btn
||Related to PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/342|
Closes: https://github.com/pypeclub/OpenPype/issues/1448
Closes: https://github.com/pypeclub/OpenPype/issues/1603
=> Loader and Library loader enhancements

openpype/style/style.css, openpype/tools/launcher/actions.py, openpype/tools/launcher/widgets.py, openpype/tools/launcher/window.py
- added styles to launcher tool
- QPushButton has 1px wide border with transparent color (illusion of same height as combobox or line edit)
- few smaller changes in code - move, added delegate to combobox etc.
=> Launcher tool style

pype/modules/ftrack/events/action_push_frame_values_to_task.py
- don't query all entities from project but only entities related to selection
- this may be faster for smaller selection in hierarchy but slower on top
- added more safe change commits and data queries (in chunks)
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1627|
=> Faster hierarchical values push

openpype/style/style.css, openpype/tools/standalonepublish/app.py, openpype/tools/standalonepublish/widgets/widget_component_item.py, openpype/tools/standalonepublish/widgets/widget_components_list.py, openpype/tools/standalonepublish/widgets/widget_drop_empty.py, openpype/tools/standalonepublish/widgets/widget_family.py
- applied styles on Standalone publisher tool
=> Standalone style

openpype/modules/ftrack/plugins/publish/collect_ftrack_api.py
- removed duplicated line in collect ftrack api
=> Duplicated ftrack session in collector

setup.py
- added "dbm" module to install_requires
=> Fix missing dbm python module

openpype/tools/pyblish_pype/window.py
=> #1333 - added tooltip hints to Pyblish buttons

pype/plugins/aftereffects/create/create_render.py
In 2.x it is unstable, causes issues in Deadline rendering
=> Remove publish highlight icon in AE

openpype/modules/log_viewer/tray/app.py, openpype/modules/log_viewer/tray/widgets.py, openpype/style/style.css
- log viewer is using openpype styles
- modified QToolButton styles when has set menu
=> Log Viewer with OpenPype style

openpype/tools/tray/pype_info_widget.py
- scrolling of environments view start when you scroll to bottom of widget (scrolling of mouse wheel)
- environments view also change size to content widget so is always fully visible
Red should not scroll until green is not on bottom and green won't scroll until red has scroll on top.
=> Scrolling in OpenPype info widget

openpype/hosts/nuke/plugins/publish/precollect_instances.py
closes https://github.com/pypeclub/client/issues/109
- broken publishing of rendered frames
=> Nuke: broken publishing rendered frames

openpype/settings/defaults/project_anatomy/imageio.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
- settings were kept in large group but this could be problem in future
closes https://github.com/pypeclub/client/issues/66
=> Settings: Imageio improving granularity

pype/hosts/nuke/lib.py, pype/plugins/nuke/create/create_write_prerender.py, pype/plugins/nuke/publish/collect_instances.py, pype/plugins/nuke/publish/collect_writes.py, pype/plugins/nuke/publish/validate_rendered_frames.py
2x spin of https://github.com/pypeclub/OpenPype/pull/1699
- improving Validator of rendered frames
- improving linked knobs by moving them to lib and removing duplicity
- fixing families mishmush
=> 1698 Nuke: Prerender Frame Range by default

openpype/widgets/color_widgets/color_inputs.py, openpype/widgets/color_widgets/color_triangle.py
- cosmetic change to have smoother edges of color triangle in color dialog
- added smoothness to alpha slider too
=> Smoother edges of color triangle

poetry.lock
- update acre commit to fixed version of acre where existing value in variable is not duplicated which breaks all nonpath environments
=> Backend acre module commit update

pype/plugins/celaction/publish/collect_audio.py
- audio subset data was not found as the data structure had been changed
=> celaciton: audio subset changed data structure

pype/plugins/celaction/publish/collect_celaction_instances.py, pype/plugins/celaction/publish/submit_celaction_deadline.py
- subset name with family fix
- -16 submission parameter was fixed to -8
=> celaction fixes

openpype/hosts/tvpaint/plugins/publish/collect_instances.py, openpype/settings/defaults/project_settings/ftrack.json
- ftrack family is not collected in tvpaint plugins but is using ftrack collect ftrack family for that
=> TVPaint ftrack family

pype/plugins/global/publish/validate_version.py
For one customer configuration via presets didn't work
=> Added AE explicitly to ValidateVersion

openpype/tools/settings/settings/categories.py
- refresh button in settings ui is not available if not in dev mode which is not right
- keep refresh button available even if not in dev mode
- refresh button should be visible in settings ui even if not in dev mode
=> Settings UI with refresh button

pype/modules/ftrack/events/event_push_frame_values_to_task.py
- task parent changes are not handled with event handling with hierarchical value pushing from parent to task on attribute value change
- it is confusing for users that value set on (e.g.) Shot is not propagated to value on created task which is annoyng especially if task attribute is used in expression
- event handler also cares about change of task parent
- in that case is pushing of values more robust and a little bit slower as have to query hierarchical attribute values all the time
1. Run event server with this branch
2. Make sure you have custom attribute available for `Shot` and `Task` and is hierarchical at the same time (`frameStart` or `frameEnd`)
3. Make sure settings for this event have proper values (`ProjectSettings/Ftrack/Server Actions/Events/Sync Hierarchical and Entity …
=> Push hierarchical attributes care about task parent changes

pype/plugins/hiero/publish/collect_review.py
- collect review were having wrong frame for thumnail
=> Hiero: wrong frame number

pype/plugins/nuke/load/load_mov.py
https://stackoverflow.com/questions/1841565/valueerror-invalid-literal-for-int-with-base-10
=> Fix float being cast to int from string.

pype/modules/ftrack/actions/action_clone_review_session.py
Reverts pypeclub/OpenPype#1785
=> Revert "Invitee email can be None which break the Ftrack commit."

pype/modules/ftrack/actions/action_clone_review_session.py
fixing branch name and target for PR https://github.com/pypeclub/OpenPype/pull/1785
=> hotfixing: Invitee email can be None which break the Ftrack commit

openpype/hosts/houdini/plugins/publish/collect_instances.py
Instance collector use keys `startFrame` and `endFrame` which was changed to `frameStart` and `frameEnd`.
- fixed the keys
=> Houdini colector formatting keys fix

pype/plugins/nuke/create/create_write_prerender.py, pype/plugins/nuke/create/create_write_render.py
- deadlineChunkSize
- deadlinePriority
- render
=> Expose write attributes to config

pype/modules/ftrack/events/action_push_frame_values_to_task.py
Action to push attribute values may crash without description what happened.
- add traceback as text file component to crashed job
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1843|
=> Ftrack push attributes action adds traceback to job

openpype/plugins/publish/validate_editorial_asset_name.py
- wrong forming of db asset parents 
- open standalone publisher into editorial family
- make sure shots in publisher are already published before in the testing project, so they will have the same hierarchy as it is already in the project
- hit validate on the publisher and see it is going trough without error
=> standalone: validator asset parents

README.md, tools/create_env.ps1
This will check if Python version is set globally or locally when using pyenv.
Add Docker build info in readme.
=> Check for missing ✨ Python when using `pyenv`

openpype/lib/applications.py
- tool environments are added in alphabetical order
=> Environments: Tool environments in alphabetical order

openpype/modules/default_modules/ftrack/plugins/publish/collect_username.py
- fix attribute name from `host` to  `hosts`
=> Ftrack: Fix hosts attribute in collect ftrack username

.gitmodules
- change source url of arrow submodule from git to https
=> Ftrack: arrow submodule has https url source

openpype/lib/profiles_filtering.py, openpype/modules/default_modules/ftrack/plugins/publish/collect_ftrack_family.py
Warning method is unnecessary here, replaced with 'info'.
=> Replace warning method in profiles filtering

openpype/hosts/hiero/api/tags.py
fixing issue with None named tags
=> PYPE-1892_tag-fix

openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/style/style.css
- project list is disabled when "Modify defaults" is checked
- project list keep background color of selected project even after focus loose
=> Settings UI: Project view enhancements

openpype/hosts/maya/api/__init__.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/inventory/import_reference.py, openpype/hosts/nuke/plugins/publish/precollect_instances.py, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
=> Feature Maya import asset from scene inventory

openpype/modules/default_modules/sync_server/tray/app.py, openpype/modules/default_modules/sync_server/tray/models.py, openpype/modules/default_modules/sync_server/tray/widgets.py
Handles changes concurrently opened Settings and Sync Queue.
=> Fix Sync Queue when project disabled

openpype/plugins/publish/extract_burnin.py, openpype/plugins/publish/extract_review.py, openpype/scripts/otio_burnin.py
3.0 equivalent of https://github.com/pypeclub/OpenPype/pull/1965
=> Use CRF for burnin when available

pype/modules/ftrack/actions/action_multiple_notes.py
Grabbed code changes from `develop` branch.
=> Update Multiple Notes to latest.

openpype/lib/delivery.py
This fixes the file(s) exists check for file sequence delivery action.
fix #2067
=> Delivery Action Files Sequence fix

pype/lib/plugin_tools.py, pype/plugins/aftereffects/publish/collect_workfile.py, pype/plugins/harmony/publish/collect_workfile.py, pype/plugins/maya/publish/collect_scene.py, pype/plugins/nuke/publish/collect_workfile.py, pype/plugins/photoshop/publish/collect_workfile.py
- add host name to `get_subset_name` library method.
- get subset name from library method in AE, Harmony, Maya, Nuke and Photoshop.
=> Customizable subset name for workfiles.

openpype/hosts/maya/plugins/publish/validate_mesh_ngons.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Add a publish validator plugin for maya assuring no ngons exist on model
=> Maya : Validate mesh ngons

start.py
It seems that Mac OS doesn't have `subst`
=> Fix - different command used for Linux and Mac OS

openpype/hosts/maya/plugins/publish/validate_shape_zero.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Hi,
A validator to assure that shapes are frozen.
=> Maya : Validate shape zero

openpype/tools/loader/model.py
Choosing different version in Loader and load didn't work because of nonupdated signature of `_repre_per_version_pipeline`.
=> Loader load version issue

openpype/tools/mayalookassigner/app.py
- do not delete maya look assigned on close
- change how OpenMaya callback are registered
=> LookAssigner: Fix tool reopen

openpype/plugins/publish/validate_editorial_asset_name.py
addressing issue https://github.com/pypeclub/OpenPype/issues/2233
=> limiting validator to specific editorial hosts

openpype/hosts/houdini/startup/MainMenuCommon.xml
- added experimental tools action to houdini menu
=> Houdini: Add experimental tools action

pype/modules/ftrack/events/event_sync_to_avalon.py, pype/modules/ftrack/lib/__init__.py, pype/modules/ftrack/lib/avalon_sync.py, pype/modules/ftrack/lib/custom_attributes.py
This will sync incoming links in Ftrack to `inputs` on Mongo assets.
=> Ftrack: Sync incoming links to inputs.

openpype/hosts/hiero/api/menu.py
- added experimental tools action to hiero host
=> Hiero: Add experimental tools action

openpype/hosts/hiero/api/plugin.py
Solving the issue where if an user had put multiple templates in parent to be solved, we were not supporting it and only returned the last used fstring template result. So for example if `{episode}_{sequence}` was used then only {sequence} had been solved and identified as entityType. 
1. open Hiero in your testing sequence
2. remove all tags if there are any
3. select any clips from your main track
4. open Create Publishable clip tool
5. To Hierarchy template add {episode}/{episode}_{sequence}
6. in vertical rename identify as main track your `main` track
Confirm
7. publish and notice all went successful and you had created clip in correct hierarchy
=> Hiero: fixing multiple templates at a hierarchy parent

pype/plugins/ftrack/publish/integrate_ftrack_instances.py
If there are multiple review representations for Ftrack, this will create multiple asset versions. Each Ftrack asset name will be suffixed with the name of the review representation.
=> Support multiple Ftrack reviews.

openpype/hosts/maya/plugins/publish/collect_look.py, openpype/hosts/maya/plugins/publish/validate_model_content.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Provide configurable top level group model validation.
This is to be merged to `release/3.6.x`.
PR to develop #2321
=> Maya: configurable model top level validation

openpype/hooks/pre_foundry_apps.py
Host left here after debugging, causing issue in openpype_gui
=> Remove wrongly used host for hook

openpype/hooks/pre_non_python_host_launch.py, openpype/hosts/webpublisher/plugins/publish/validate_tvpaint_workfile_data.py
Was causing issues in starting in openpype_console or openpype_gui
Requires https://github.com/pypeclub/avalon-core/pull/396
=> Adobe products show issue

openpype/modules/default_modules/job_queue/module.py
=> JobQueue: Fix loading of settings

openpype/scripts/otio_burnin.py
- added support of OPAtom mxf into burnins
- add support of mxf format to be able recognize opatom mxf
=> Burnins: Be able recognize mxf OPAtom format

openpype/tools/loader/app.py, openpype/tools/project_manager/project_manager/widgets.py, openpype/tools/publisher/widgets/widgets.py, openpype/tools/publisher/window.py, openpype/tools/settings/local_settings/apps_widget.py, openpype/tools/settings/local_settings/general_widget.py, openpype/tools/settings/local_settings/mongo_widget.py, openpype/tools/settings/local_settings/projects_widget.py, openpype/tools/settings/settings/widgets.py, openpype/tools/standalonepublish/widgets/widget_asset.py, openpype/tools/subsetmanager/window.py, openpype/tools/utils/__init__.py, openpype/tools/workfiles/app.py
- placeholder color of active window is dark color in some PySide2 versions
- use PlaceholderLineEdit where placeholder is set
=> Tools: Placeholder color

openpype/settings/entities/enum_entity.py
- added `webpublihser` to hosts enum
=> Settings: Webpublisher in hosts enum

openpype/action.py
=> Fix #2473 Update "Repair Context" label to "Repair"

openpype/hosts/maya/plugins/load/load_look.py
=> Fix #2453 Refactor missing _get_reference_node method

openpype/modules/default_modules/sync_server/providers/dropbox.py
add feature to handle big size file ( 50mb ++ )
=> dropbox handle big file

.github/workflows/documentation.yml, website/docusaurus.config.js, website/yarn.lock
Update docusaurus to latest beta and fix build
=> Update docusaurus to latest version

openpype/tools/pyblish_pype/control.py
This fixes the [comments made here](https://github.com/pypeclub/OpenPype/pull/2708#issuecomment-1038371383) for PR #2708 
1. test whether the labels on Pyblish window make sense in the different states
=> Pyblish Pype: Improve labels with errors + fix end of validation stage

website/docs/artist_getting_started.md
another missing .md extension in link to different md file
=> Documentation: broken link fix

website/docs/admin_distribute.md
A short explanation of the versioning system in OpenPype.
=> Doc: OpenPype Versioning

openpype/hosts/resolve/api/utils.py
Fusion module in Resolve was not loading.
It was crashing loading of the menu inside of Resolve
=> resolve: fixing fusion module loading

openpype/tools/settings/settings/base.py
Apply from actions were using lambda callbacks created inside loop but it looks like lambda will keep using variable values from the scope in which was created so the last project name was always used.
- create custom class for action callbacks `_Callback` which stores function to call and arguments to be used
- replace `lambda` with `_Callback` object
1. Open project settings UI
2. Set some settings in one project and make sure they are different then all other projects
- don't do that on last project in list
3. Run Apply from -> "the project from step 2." action in other project and validate that values are the same
=> Settings UI: Fix "Apply from" action

openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.param, openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.py
During [this PR](https://github.com/pypeclub/OpenPype/pull/2789) was accidentally removed deadline events.
- added removed events to deadline repository files
1. Copy deadline plugin files into repository
2. OpenPype event should be visible in deadline `Configure Events`
=> Deadline: Added missing events folder

openpype/tools/publisher/widgets/create_dialog.py
Error dialog in new publisher does not inherit styles.
- use `ErrorMessageBox` implemented for Creator tool
- pass parent into `CreateErrorMessageBox`
1. Raise `CreatorError` in creator using new publisher
2. Message dialog should inherit styles
=> New Publisher: Error dialog got right styles

website/docs/artist_hosts_aftereffects.md, website/docs/artist_hosts_photoshop.md
Fix new plugins path in documentation.
=> Documentation: Change Photoshop & AfterEffects plugin path

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/load/load_reference.py, openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
This is adding additional fixes for #2837
=> Fixes for attaching loaded containers (#2837)

openpype/plugins/publish/extract_review.py
Gap was detect even there was none
=> Fixing gap detection in extract review

openpype/modules/slack/plugins/publish/integrate_slack_api.py
Added generic exception to handle all issues in Slack notification.
Slack doesn't wraps all exceptions, so generic Exception is added as a fail safe.
=> Slack: add generic exception

openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py, openpype/plugins/load/delete_old_versions.py
OpenPype 3 version of https://github.com/pypeclub/OpenPype/pull/1554/files PR.
Skip invalid data rather than crash when deleting old versions.
=> General: More fail safe delete old versions

poetry.lock
Solves issue in `tools/create_env.ps`
=> Added current commit of acre

openpype/hosts/flame/api/lib.py, openpype/hosts/flame/api/scripts/wiretap_com.py, openpype/hosts/flame/plugins/publish/collect_timeline_instances.py, openpype/hosts/flame/plugins/publish/collect_timeline_otio.py
Flame was behaving differently on centos
- Only collect selected segments once and pass it to context data
- head and tails could sometimes be string so condition is setting it to 0
- wiretap color policy is not file path but wiretap node path
=> Flame: centos related debugging

website/docs/module_site_sync.md
It pop ups from time to time on Discord
=> Documentation: Added mention of adding My Drive as a root

website/docs/dev_requirements.md
See https://discord.com/channels/517362899170230292/517382145552154634/961637910753472532
=> Documentation: Python requirements to 3.7.9

website/docs/artist_hosts_hiero.md, website/docs/artist_hosts_nuke_tut.md
Add YouTube videos to Nuke and Hiero pages
=> Nuke docs with videos

tests/lib/assert_classes.py, tests/lib/testing_classes.py
Minor fixes for integration tests
=> Testing fixes

openpype/hosts/photoshop/plugins/publish/collect_batch_data.py, openpype/hosts/photoshop/plugins/publish/collect_color_coded_instances.py, openpype/hosts/photoshop/plugins/publish/collect_instances.py, openpype/hosts/photoshop/plugins/publish/collect_review.py, openpype/hosts/webpublisher/plugins/publish/collect_batch_data.py, openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
Variant value wasn't propagated into subset name.
Created from `release/3.9.x` branch
1. Publish PS workifle via Webpublisher
2. compare resulting subset name of review
=> Webpublisher: Use variant value

openpype/hosts/standalonepublisher/plugins/publish/collect_context.py, openpype/settings/defaults/project_settings/standalonepublisher.json, openpype/tools/standalonepublish/widgets/widget_drop_frame.py, openpype/tools/standalonepublish/widgets/widget_family_desc.py
Adding support for standalone publisher to publish bgeo and vdb sequences.
This is adding just simple ability to publish bgeo and vdb as sequences (and adding vdbcache creator to standalone publisher).
=> Standalone publisher: add support for bgeo and vdb

openpype/modules/ftrack/event_handlers_user/action_create_folders.py, openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py
Create folders action use task as dictionary. (Variant for 3.9.x)
Changed how data for template collecting are prepared. Action used task as string instead of dictionary. Also made faster queries to get full hierarchy data.
1. Run the action
2. Check that work and publish folders are created
=> Ftrack: Update Create Folders action

openpype/hosts/maya/api/lib_renderproducts.py, openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/publish/validate_rendersettings.py, openpype/modules/deadline/plugins/publish/submit_maya_deadline.py, openpype/settings/defaults/system_settings/tools.json
Add fixed support for renderman as of #3006 to 3.9.x branch.
=> renderman support for 3.9.x

openpype/modules/base.py
Unified code for default and dynamically loaded OpenPype modules.
Removed duplicated code if modules import logic.
1. OP Modules and addons should load as they did
=> General: Simplified OP modules/addons import

openpype/pipeline/legacy_io.py, schema/session-3.0.json
Added new version of session schema without required `AVALON_CONFIG`.
Removed `AVALON_CONFIG` from required keys in session and reduced few more unused keys from the sesion.
1. Execute in any host script editor
```
from openpype.pipeline import legacy_io
legacy_io.install()
```
2. The execution should not error out
=> General: New Session schema

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
This is fix #3144 for 3.9.x branch.
=> Deadline output dir issue to 3.9x

openpype/hosts/unreal/api/rendering.py, openpype/hosts/unreal/plugins/load/load_animation.py, openpype/hosts/unreal/plugins/load/load_camera.py, openpype/hosts/unreal/plugins/load/load_layout.py, openpype/hosts/unreal/plugins/load/load_rig.py, openpype/hosts/unreal/plugins/publish/collect_render_instances.py
Rework for the `update` and `remove` functions for layout and camera assets.
- The `update` and `remove` functions for layout and camera assets have been changed to work after the changes for the rendering implementation.
- Loading the layout will load the assets in a separate folder. If another layout uses the same asset, this won't be loaded again. Before updating or removing a layout, we check if that assets is referenced by other layouts.
- Use anatomy for the render paths.
=> Unreal: Layout and Camera update and remove functions reimplemented and improvements

openpype/modules/deadline/plugins/publish/submit_publish_job.py
this is backport to 3.9.x of #3164
=> Backport of fix for attaching renders to subsets

openpype/modules/deadline/plugins/publish/submit_publish_job.py
this is backport of #3214 to 3.9.x
=> Deadline: instance data overwrite - backport #3214

openpype/hosts/unreal/plugins/load/load_animation.py, openpype/hosts/unreal/plugins/load/load_layout.py
The default sample rate seems to be stopping the animation to work properly when imported in UE5.
=> Unreal: Fixed Animation loading in UE5

openpype/settings/defaults/project_settings/maya.json
True was there only for testing, false is more sane default.
=> Chore: changed default

openpype/plugins/publish/extract_review_slate.py
Fixing color_matrix bt709 issue
Reported issue was showing problems with ffmpeg processing
- also found related issue with silent audio processing 
- at the moment audio is ignored and not added to the concatenated video file
=> Global: extract review slate issues

tools/create_env.ps1, tools/create_env.sh
updated poetry installation source
So we can get rid of the create_env message at the start
both .ps1 and .sh updated 
.\tools\create_env.ps1
=> updated poetry installation source

openpype/hosts/maya/plugins/publish/collect_look.py
This is adding fix from #3266 to 3.9.x branch.
=> Backport 3.9.x: Fix Maya look UDIMs (#3266)

openpype/hosts/maya/plugins/publish/collect_look.py
fixing typo in look collector.
=> Maya: look collector typo

openpype/modules/kitsu/kitsu_module.py, openpype/modules/kitsu/utils/update_op_with_zou.py
More consistent with a plural name.
=> Kitsu: renaming to plural func sync_all_projects

.gitignore
=> Add to gitignore `tools/run_eventserver.*`

openpype/settings/defaults/system_settings/applications.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json
Settings for Adobe applications and Harmony had slightly different schema options. Now Photoshop, After Effects, and Harmony have the same type.
=> Settings: Changes in schema settings for AE and Harmony

openpype/hosts/houdini/api/lib.py, openpype/hosts/houdini/api/usd.py, openpype/hosts/houdini/plugins/create/create_hda.py, openpype/hosts/houdini/plugins/publish/collect_usd_bootstrap.py, openpype/hosts/houdini/plugins/publish/extract_usd_layered.py, openpype/hosts/houdini/plugins/publish/validate_usd_shade_model_exists.py, openpype/hosts/houdini/vendor/husdoutputprocessors/avalon_uri_processor.py
Modified Houdini host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Houdini is using query functions from `openpype.client` to get full hierarchy. Modified avalon uri handler in vendorized module to use Anatomy.
=> Houdini: Use client query functions

openpype/modules/sync_server/tray/models.py
Null values were sorted as last, this keeps queued items together with last synched.
1. experiment with sorting by `Active site` (or `Remote site`)
2. queued items (without any value in column) should be sorted close to last updated
=> Sync Queue: Added far future value for null values for dates

openpype/modules/webserver/cors_middleware.py, openpype/modules/webserver/server.py, poetry.lock, pyproject.toml
Added CORS middleware into webserver application.
CORS needs to be implemented for React app could communicate with OP Tray webserver.
=> Webserver: Added CORS middleware

openpype/hosts/fusion/api/lib.py, openpype/hosts/fusion/plugins/load/load_sequence.py, openpype/hosts/fusion/scripts/fusion_switch_shot.py, openpype/hosts/fusion/utility_scripts/switch_ui.py
Modified Fusion host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Fusion is using query functions from `openpype.client` to get full hierarchy.
1. Switch UI in fusion should work with switching items
2. Update of loaded sequence should work (loaded using `FusionLoadSequence` loader)
=> Fusion: Use client query functions

openpype/hosts/fusion/plugins/load/load_sequence.py, openpype/hosts/resolve/plugins/load/load_clip.py
Modified Resolve host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Resolve is using query functions from `openpype.client` to get versions. Added `"plate"` family into load sequence loader.
1. Loader plugin `Load clip` should be able to load and update
=> Resolve: Use client query functions

openpype/settings/defaults/project_settings/harmony.json, openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
Currently to fix issue with reference representations with wrong names (png_mp4 instead of png), but it could be helpful regardless.
3.9.x version of https://github.com/pypeclub/OpenPype/pull/3449
=> Harmony: add loader settings

openpype/modules/kitsu/plugins/publish/collect_kitsu_entities.py, openpype/modules/kitsu/utils/sync_service.py, openpype/modules/kitsu/utils/update_op_with_zou.py
Fix several sync-service issues and publishing with Kitsu module.
- `sync-service` update projects and assets attributes properly.
- `sync-service` won't crash while update events are emitted but causing no changes.
- `CollectKitsuEntities` can collect shots.
- `zou` data attribute is set for asset tasks.
Resolve: #3472
Resolve: #3471
=> Kitsu: bugfix with sync-service ans publish plugins

openpype/modules/timers_manager/timers_manager.py
Timers manager is using query functions to get asset information.
Use query functions in timers manager and added few more data to information that can be used from triggered timer.
1. Enable some time tracking module (e.g. ftrack)
2. Start a timer or open application to start a timer
3. Check output for any errors
Optionally also stop timers using rest api:
Run in Tray > Admin > Console
```
import os
import requests
webserver_url = os.environ.get("OPENPYPE_WEBSERVER_URL")
rest_api_url = "{}/timers_manager/start_timer".format(webserver_url)
requests.post(rest_api_url)
```
=> TimersManager: Use query functions

openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/widgets.py
Added "Extract to file" action to be also shown on right click in project list.
1. Right click on a project in project settings
2. Extract to file action should be visible
3. Triggered action should work as expected
=> Settings UI: Add extract to file action on project view

openpype/hooks/pre_global_host_data.py, openpype/hosts/fusion/scripts/fusion_switch_shot.py, openpype/hosts/testhost/api/pipeline.py, openpype/hosts/testhost/plugins/create/auto_creator.py, openpype/pipeline/create/context.py, openpype/pipeline/thumbnail.py, openpype/scripts/fusion_switch_shot.py
Use query functions in general code of openpype.
Replace direct mongo calls with query functions in general places or forgotten places.
There are 2 duplicated fusion scripts and both seems to be unused.
1. Applications should launch
2. Thumbnails should be visible in loader (as they were)
3. Tray publisher can work
=> General: Use query functions in general code

openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
Newly created entities propagate hierarchical attribute values to non-hierarchical.
New created entities did not propagated defined attributes because they are not in category "changed" on creation. Because their value is "Not set" by default. Have to calculate attribute values on creation and change how values are created, updated or removed - before it was simplified but aparently that is not enough.
1. Make sure `project_settings/ftrack/events/sync_hier_entity_attributes/interest_entity_types` is enabled and filled for your project
2. Create new entity with type in settings (by default it is `Shot` or `Asset Build`)
3. Created entity should have synchronized hierarchical custom attributes to non hierarchical attributes (by default `frameStart` and `frameEnd`)
=> Ftrack: Sync hierarchical attributes can handle new created entities

openpype/plugins/publish/extract_otio_audio_tracks.py
Mix of audio using ffmpeg command should not cause error when ffmeg can't process too long command.
Modified command preparations for audio mix to be able store filters into a file and tell ffmpeg where to look for filters to process. Also was modified how a time for `dropout_transition` is defined from hardcoded `1000` calculate it using longest input audio in miliseconds.
1. Publish a timeline with at least 30 items containing audio (probably can be one very long audio item?)
2. It should not crash because of "too long command" in ffmpeg (or any other error in the `Extract OTIO Audio Tracks` plugin)
=> Editorial: Mix audio use side file for ffmpeg filters

openpype/hosts/maya/plugins/publish/collect_render.py
Committing the original bug fix by Big Roy  to collect full_exp_files
Link: https://github.com/BigRoy/OpenPype/commit/baaa98bed0e8aee85bbe6bb5b4255c0522f0a5a7
=> Collect full_exp_files instead of leaving it empty

openpype/plugins/publish/help/validate_containers.xml
Slightly change error message.
=> Docs: Refactored content of help, eg error message

openpype/hosts/tvpaint/__init__.py, openpype/hosts/tvpaint/api/__init__.py, openpype/hosts/tvpaint/api/pipeline.py, openpype/hosts/tvpaint/tvpaint_module.py
TVPaint is defined as OpenPype module.
1. TVPaint should launch
2. Open of last workfile should work if feature is enabled and there is any available
=> TVPaint: Defined as module

openpype/hosts/harmony/__init__.py, openpype/hosts/harmony/addon.py, openpype/hosts/harmony/api/pipeline.py, openpype/hosts/harmony/api/workio.py
Harmony host is addon.
Implemented `HarmonyAddon` for harmony host which gives public information about the host.
- Harmony can be launched and integration works (as before)
=> Harmony: Defined harmony as addon

openpype/hosts/resolve/utils.py
Change code which broke Python 2 DCCs.
Replaced f-string formatting with standard formatting.
=> Resolve: Addon import is Python 2 compatible

openpype/modules/kitsu/utils/update_op_with_zou.py, openpype/settings/defaults/project_settings/kitsu.json, openpype/settings/entities/schemas/projects_schema/schema_project_kitsu.json
Removed "entities root" setting to match with Kitsu's native behaviour without adding overhead in code, neither for admin.
Closes #3738
=> Kitsu|Change: Drop 'entities root' setting.

openpype/tools/tray/pype_tray.py
Enabled high pixmap scaling in tray application.
Enabling these flags enhance pixmap look in UIs a lot.
1. Compare look of UI images in this PR and in develop
=> General: Better pixmap scaling

.gitignore, README.md
Adding developer tools ignoring
all developer tools in /tools folder starting with prefix `dev_` will be ignored.
=> git: update gitignore

.github/ISSUE_TEMPLATE/bug_report.md
=> Github issues adding `running version` section

openpype/hosts/maya/plugins/publish/extract_look.py
Exception in Maketx wasn't printed anywhere. This PR makes logging better.
1. Publish look in Maya 
2. Publish look in Maya and try to trigger Maketx exception (not sure how - maybe just renaming vendorized oiio)
=> Maya: better logging in Maketx

openpype/pype_commands.py
Error would occur in Webpublisher only.
1. try basic publish (without Studio processing) in WP
=> WebPublisher: Fix import after refactor

openpype/lib/transcoding.py, openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
Added conversion for `float2` value type during oiio xml conversion.
Based on [discord conversation](https://discord.com/channels/517362899170230292/517382145552154634/1019572032008093706).
1. Try transcoding with `float2` type in attributes
=> General: Transcoding handle float2 attr type

openpype/hosts/flame/api/pipeline.py, openpype/hosts/flame/plugins/create/create_shot_clip.py, openpype/hosts/flame/plugins/publish/collect_timeline_instances.py, openpype/hosts/flame/plugins/publish/extract_subset_resources.py, openpype/plugins/publish/collect_otio_frame_ranges.py, openpype/settings/defaults/project_settings/flame.json, openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
Fixing retiming attributes
Retimed framerange and handles were not integrated in publishing. Settings were not created for Creator to control retimed attributes.
=> Flame: retimed attributes are integrated with settings

igniter/bootstrap_repos.py, igniter/install_thread.py
This PR is fixing logic of detection filtered version compatible with the currently installed build. It is also removing unnecessary and obsolete code.
**Note:** this already includes #3903 as it was needed for testing.
Same as with #3903 
Delete all versions from local app data. Be sure you have no newer version in update repository. Run Igniter and "install" OP. Everything should work.
=> Bug: Fixing version detection and filtering in Igniter

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
This is moving existing data classes to "new-style" as it seems that newer versions of attrs is complaining about it.
To test: submission to DL should work as expected.
=> Maya: new style dataclasses in maya deadline submitter plugin

openpype/hosts/resolve/api/pipeline.py, openpype/hosts/resolve/api/plugin.py
Fix wrong usage of lib functions in resolve host.
Change where from are lib functions used/imported.
1. Resolve creation should work
=> Resolve: Fix usage of functions from lib

.github/workflows/prerelease.yml, .github/workflows/release.yml, .gitignore, CHANGELOG.md, HISTORY.md
Updating Change log generator
- removing change log generator action from worlflows
- updating HISTORY.md
- updating CHANGELOG.md
=> Github workflows - Updating Change log generator

openpype/hosts/houdini/plugins/publish/validate_workfile_paths.py
Import `RepairAction` from new destination.
1. Validate workfile paths should work as did
=> Houdini: Change import of RepairAction

openpype/hosts/maya/plugins/create/create_render.py
Removed unused imports and change imports from `openpype.api` in create write plugin file.
1. Creator should be visible in maya
2. Creator should work
=> Maya: Removed unused imports

website/docs/dev_requirements.md
=> Documentation: Minor updates to dev_requirements.md

openpype/settings/defaults/system_settings/applications.json
Adding latest minor reliease of Nuke, Hiero, Nukex, NukeStudio
=> Nuke: add 13.2 variant

openpype/modules/kitsu/plugins/publish/collect_kitsu_username.py, openpype/plugins/publish/extract_burnin.py
Get kitsu login to fill username burnin. when session username is not right.
Get kitsu login to fill username burnin when session username is not the right username (like multiple artists working on the same session).
=> Get kitsu login to fill username burnin

openpype/modules/ftrack/scripts/sub_event_status.py
Ftrack event server statuser also shows information about where are versions stored for the process and where is looking for version repository.
1. Run ftrack event server 
2. Check status action which should show where is storing versions locally and where is looking for version in version repository
=> Ftrack: Event server status give more information about version locations

openpype/settings/defaults/project_settings/global.json
Move default values of online to legacy place of template resolving.
=> General: Move default settings for template name

openpype/plugins/publish/collect_anatomy_instance_data.py
Collect anatomy instance data is right variable to skip processing of instance.
=> General: Fix variable check in collect anatomy instance data

pyproject.toml
Implements properly update of Gazu.
Solves revert in https://github.com/pypeclub/OpenPype/pull/4207.
.lock already contains updated version.
=> Build: update to Gazu in toml

openpype/tools/settings/__init__.py, openpype/tools/settings/local_settings/apps_widget.py, openpype/tools/settings/local_settings/environments_widget.py, openpype/tools/settings/local_settings/experimental_widget.py, openpype/tools/settings/local_settings/general_widget.py, openpype/tools/settings/local_settings/mongo_widget.py, openpype/tools/settings/local_settings/projects_widget.py, openpype/tools/settings/local_settings/widgets.py, openpype/tools/settings/local_settings/window.py, openpype/tools/settings/settings/base.py, openpype/tools/settings/settings/breadcrumbs_widget.py, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/color_widget.py, openpype/tools/settings/settings/constants.py, openpype/tools/settings/settings/dialogs.py, openpype/tools/settings/settings/dict_conditional.py, openpype/tools/settings/settings/dict_mutable_widget.py, openpype/tools/settings/settings/images/__init__.py, openpype/tools/settings/settings/item_widgets.py, openpype/tools/settings/settings/lib.py, openpype/tools/settings/settings/list_item_widget.py, openpype/tools/settings/settings/list_strict_widget.py, openpype/tools/settings/settings/multiselection_combobox.py, openpype/tools/settings/settings/search_dialog.py, openpype/tools/settings/settings/tests.py, openpype/tools/settings/settings/widgets.py, openpype/tools/settings/settings/window.py, openpype/tools/settings/settings/wrapper_widgets.py
Settings UI is using `qtpy` instead of `Qt.py` module.
Settings tools should work on
=> General: Use qtpy in settings UI

openpype/hosts/blender/plugins/load/load_layout_blend.py
This PR fixes a problem occurring when trying to update a layout in Blender. It also relink the updated objects in animation instances, if they exist.
=> Blender: Fix Layout Family Versioning

openpype/hosts/traypublisher/plugins/create/create_online.py, openpype/hosts/traypublisher/plugins/publish/collect_online_file.py, openpype/hosts/traypublisher/plugins/publish/validate_online_file.py, openpype/plugins/publish/extract_thumbnail.py
This PR slightly improves online family functionality:
- adding posibility to publish image sequence (not only video files)
- review and thumbnail functionality
- optional validator fix for subset name
=> Tray Publisher: Improve Online family functionality

tools/run_documentation.ps1
=> Fix run_documentation.ps1

openpype/hosts/tvpaint/tvpaint_plugin/plugin_code/library.cpp
Plugin for TVPaint was modified to work in TVPaint 11.7.
TVPaint 11.7 is more sensitive about when the connection should be created and caused crashes. The connection is created in function defined by SDK where the init logic should happen.
1. Run TVPaint 11.7 (it will probably ask to copy plugin file)
2. All should work
Task: OP-4197
=> TVPaint: Fix plugin for TVPaint 11.7

openpype/hosts/traypublisher/batch_parsing.py, openpype/hosts/traypublisher/plugins/create/create_movie_batch.py
Just chore PR extracting parsing methods into separate reusable file. These functions should be refined further to make them more robust.
Use with https://github.com/ynput/OpenPype-premium/pull/30
=> TrayPublisher: Batch utils functions

openpype/hosts/celaction/plugins/publish/collect_celaction_cli_kwargs.py
CelAction is now publishing as expected
Collector CLI was failing as it could not correctly parse arguments send form CelAction. It should be working fine now.
=> CelAction: Collector CLI is now working as it should

openpype/pipeline/create/context.py
=> New Publisher: Fix Creator error typo

tests/integration/hosts/aftereffects/test_deadline_publish_in_aftereffects.py, tests/integration/hosts/aftereffects/test_deadline_publish_in_aftereffects_multicomposition.py, tests/integration/hosts/aftereffects/test_publish_in_aftereffects.py, tests/integration/hosts/aftereffects/test_publish_in_aftereffects_multiframe.py
'png' extension have 2 representations instead 1. (One is regular, one is from review, with name 'png_png'
=> Tests: fix AE 

pyproject.toml
Automatization injects wrong format
=> Chore: pyproject.toml version because of Poetry

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/menu.py, openpype/hosts/maya/plugins/publish/submit_maya_muster.py, openpype/hosts/maya/plugins/publish/validate_maya_units.py
Removing Maya library code that is redundant.
=> Maya: Clean up redundant lib code.

openpype/hosts/houdini/api/plugin.py
This is fixing bug introduced int #4374
=> Houdini: hotfix condition

pyproject.toml
Causes issue in create_env and new Poetry
=> Fix - remove minor part in toml

openpype/hosts/nuke/api/gizmo_menu.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_scriptsgizmo.json
Fix features for the Gizmo Menu project settings (shortcut for python type of usage and file type of usage functionality)
=> Fix features for gizmo menu

openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py, openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py, openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py, openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py, openpype/modules/deadline/plugins/publish/submit_maya_deadline.py, openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py, openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py
Only submit version when running from build.
When running from source code, we dont need a specific version of OP on the farm.
1. Run OP from source.
2. Submit a render to Deadline.
3. Validate no `OPENPYPE_VERSION` are in the jobs.
=> Deadline: Only submit version when running from build.

openpype/modules/slack/plugins/publish/integrate_slack_api.py
=> Slack: check existence only if not None

openpype/hosts/maya/api/lib.py
Fix broken lib.
This [commit](https://github.com/ynput/OpenPype/commit/3fa7610061298e4a3de96d176b74f5bd3ecca652) from this [PR](https://github.com/ynput/OpenPype/pull/4340) broke the Maya lib module.
1. Publish anything with Maya.
=> Maya: Fix broken lib.

openpype/modules/deadline/plugins/publish/submit_publish_job.py
Fix submit_publish_job
Resolves #4541
=> Deadline: fix submit_publish_job

openpype/cli.py, openpype/pype_commands.py, tests/conftest.py, tests/lib/testing_classes.py
Allows to download test zip, unzip and restore DB in preparation for new test.
=> Tests: Added setup_only to tests

openpype/hosts/maya/plugins/publish/collect_review.py, openpype/hosts/maya/plugins/publish/extract_playblast.py
=> Maya: Fix broken review publishing.

openpype/hosts/max/api/lib_renderproducts.py
fix the bug of failing publishing job in 3dsMax
OutputFilenames in Job Info are with explicit name, while RenderOutputFIle and RenderElementOutputFilename are with implicit names.
1. Launch 3dsMax via Openpype
2. Create Render Instance
3. Publish
=> bugfix for 3dsmax publishing error

openpype/plugins/publish/preintegrate_thumbnail_representation.py
Thumbnail representation might be missing tags field.
=> Global: add tags field to thumbnail representation

openpype/lib/applications.py
Use `app.full_name` for change done in #4682 
1. Launch Tray (from code or openpype_console)
2. Launch an application, read the console log
=> Improve logging of used app + tool envs on application launch (minor tweak)

openpype/hosts/maya/plugins/publish/extract_playblast.py
Paragraphs contain detailed information on the changes made to the product or service, providing an in-depth description of the updates and enhancements. They can be used to explain the reasoning behind the changes, or to highlight the importance of the new features. Paragraphs can often include links to further information or support documentation.
=> Refactor _capture

openpype/hooks/pre_foundry_apps.py, openpype/hosts/blender/api/ops.py, openpype/hosts/photoshop/api/launch_logic.py, openpype/hosts/tvpaint/api/communication_server.py, openpype/modules/example_addons/example_addon/addon.py, openpype/tools/utils/lib.py, website/docs/project_settings/settings_project_global.md, website/docs/pype2/admin_presets_plugins.md
Typo/grammar fixes in documentation.
1. Read the changes :)
=> Docs: Fix some minor grammar/typos

openpype/plugins/publish/extract_hierarchy_avalon.py, openpype/plugins/publish/extract_hierarchy_to_ayon.py
Implemented extract hierarchy to AYON plugin which created entities in AYON using ayon api.
I didn't test case when tasks should be created as I don't have testing data which would cause that. It was crashing because of missing OCIO configs for me now -> not fully related to this PR. I will try fix it later on.
1. Start editorial publishing which should create/update entities in project (e.g. Simple Editorial in TrayPublisher)
2. It should create entities in the project
=> AYON: Editorial hierarchy creation

openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
Change capture labels.
Think the labels for `project_settings/maya/publish/ExtractPlayblast/capture_preset/Codec/compression` and `project_settings/maya/publish/ExtractPlayblast/capture_preset/Codec/format` could be improved and become better parallels with what is in Maya's playblast options.
=> Maya: Suggestion to change capture labels.

ayon_start.py, openpype/vendor/python/ayon/ayon_api/__init__.py, openpype/vendor/python/ayon/ayon_api/_api.py, openpype/vendor/python/ayon/ayon_api/constants.py, openpype/vendor/python/ayon/ayon_api/entity_hub.py, openpype/vendor/python/ayon/ayon_api/events.py, openpype/vendor/python/ayon/ayon_api/exceptions.py, openpype/vendor/python/ayon/ayon_api/graphql.py, openpype/vendor/python/ayon/ayon_api/graphql_queries.py, openpype/vendor/python/ayon/ayon_api/operations.py, openpype/vendor/python/ayon/ayon_api/server_api.py, openpype/vendor/python/ayon/ayon_api/thumbnails.py, openpype/vendor/python/ayon/ayon_api/utils.py, openpype/vendor/python/ayon/ayon_api/version.py, poetry.lock, pyproject.toml
Vendorize ayon api into openpype vendor directory. The reason is that `ayon-python-api` is in live development and will fix/add features often in next few weeks/months, and because update of dependency requires new release -> new build, we want to avoid the need of doing that as it would affect OpenPype development.
Ayon api is now added into separated vendor folder which is added to `sys.path` and `PYTHONPATH` when `ayon_start.py` is used.
1. AYON mode should still work
=> AYON: Vendorize ayon api

website/docs/artist_concepts.md
Tweak some of the key concepts in the documentation.
Please review whether the terminology is right or should be improved.
This tries to resolve some of the issues with [undocumented terminology I mentioned here](https://community.ynput.io/t/subset-and-family-are-they-the-right-names/104/14?u=bigroy).
1. Read the glossary
=> Documentation: Add extra terminology to the key concepts glossary

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
Fixes tile rendering with Vray.
1. Setup tile render in Maya with Vray.
2. Publish and validate render is assembled correctly.
=> Maya: Fix tile rendering with Vray - OP-5566

openpype/hosts/maya/plugins/publish/collect_review.py
Fix nested model instance under review instance, where data collection was not including "Display Lights" and "Focal Length".
1. Setup nested model instance under a review instance.
2. Publish.
=> Maya: Fix nested model instances.

openpype/hosts/maya/startup/userSetup.py
Update branch `bugfix/maya_explicit_plugins_loading`.
=> Maya: Explicit Plugins Loading

openpype/settings/ayon_settings.py
Fix conversion of ftrack settings in AYON mode.
1. Ftrack server url should be available and filled with value from AYON settings
=> Ftrack: Fix AYON settings conversion

openpype/client/server/conversion_utils.py, openpype/client/server/entities.py, openpype/hosts/maya/api/lib.py, openpype/hosts/maya/startup/userSetup.py, openpype/settings/ayon_settings.py, openpype/vendor/python/common/ayon_api/entity_hub.py, openpype/vendor/python/common/ayon_api/graphql_queries.py, openpype/vendor/python/common/ayon_api/server_api.py, openpype/vendor/python/common/ayon_api/version.py
Few smaller fixes related to AYON connection. Some of fixes were taken from [this PR](https://github.com/ynput/OpenPype/pull/4959/files).
Fix of tools attribute conversion on project and asset. Fix representation fields conversion. Fix `get_last_version_by_subset_id` function. Convert maya load colors. Fix missing variable in maya lib function.
=> AYON: General fixes and updates

openpype/hosts/blender/plugins/load/load_abc.py
Fixed problem occurring when trying to load an Alembic model in Blender.
1. Open Blender.
2. Try loading any alembic model.
=> Blender: Fix Alembic loading

openpype/pipeline/publish/lib.py
Only project settings are passed to optional `apply_settings` method, if the method expects only one argument.
Previous implementation always passed project and system settings, but system settings are not used in 99.99% cases. Also is partially preparaion for AYON where system settings won't be a thing.
1. Make fake plugin with implemented classmethod `apply_settings`.
2. Make sure the plugin expects only one argument.
3. Only project settings should be passed to the method.
4. Change the arguments to expect both project and system settings.
5. Both should be passed to the method.
=> General: Publish plugin apply settings can expect only project settings

openpype/modules/ftrack/tray/login_dialog.py, openpype/modules/muster/muster.py, openpype/pipeline/publish/lib.py, openpype/tools/utils/lib.py, openpype/tools/utils/overlay_messages.py, tests/README.md
Small code cleanup and updates.
Removed unused import in ftrack login. Refactored code in muster. Removed `default` keyword argument from `get_publish_instance_label`. Overlay message always updates the style, to be able unset it. Updated mockup environment variables needed for custom scripts.
Go through changes and validate them. Everything should work as before.
=> General: Small code cleanups

openpype/hosts/blender/plugins/load/load_camera_abc.py
Implemented loading of Alembic cameras in Blender.
1. Open Blender
2. Try loading a camera published in abc format.
=> Blender: Implemented Loading of Alembic Camera

igniter/tools.py, openpype/client/mongo/mongo.py
Fix `ssl` and `tls` keys checks in mongo uri query string.
Origin PR https://github.com/ynput/OpenPype/pull/5028 -> changed source and destination of branch to next minor and removed dry change as it would break bootstraping.
Validate the code logic.
Optional: Try collect to mongo with tls in query keys.
Resolves https://github.com/ynput/OpenPype/issues/5027
=> General: Fix mongo secure connection

openpype/hosts/hiero/plugins/load/load_clip.py
Changed `apply_settings` to classmethod which fixes the issue with settings.
1. Load Clip should work in hiero
=> Hiero: Fix apply settings Clip Load

openpype/plugins/publish/collect_frames_fix.py
Previous implementation https://github.com/ynput/OpenPype/pull/5036 was broken this is fixing the issue where attribute is found in instance data although the settings were disabled for the plugin.
Hard to test this. It is only code review
=> Global: collect_frame_fix plugin fix and cleanup

openpype/hosts/blender/hooks/pre_add_run_python_script_arg.py, website/docs/dev_blender.md, website/sidebars.js
Hook to allow hooks to add path to a python script that will be executed when Blender starts.
1. Follow the documentation added in the PR
=> Feature: Blender hook to execute python scripts at launch

igniter/__init__.py
Function `_get_qt_app` actually creates new `QApplication` if was not created yet.
1. Turn off your local mongo
2. Start OpenPype
3. Igniter UI should show
=> Igniter: QApplication is created

openpype/hosts/maya/plugins/load/load_reference.py
Fix bug introduced with https://github.com/ynput/OpenPype/pull/4751 where `cmds.ls` returns a list.
1. Publish a maya scene with a camera.
2. Load maya scene.
3. Publish a new version of the maya scene.
4. Update the maya scene container while viewing through the camera.
=> Maya: Fix Load Reference.

openpype/hosts/houdini/plugins/publish/collect_frames.py, openpype/hosts/houdini/plugins/publish/collect_instances.py, openpype/hosts/houdini/plugins/publish/collect_rop_frame_range.py
Fix missing frame range for pointcache and camera exports on published version.
Resolves #5019 
1. Publish pointcache and camera instance
2. Loader should show start + end frame for it
3. Also publish other instances, e.g. workfile, vdbcache or alike - they should work as before.
=> Houdini: Fix missing frame range for pointcache and camera exports

openpype/hosts/standalonepublisher/plugins/publish/collect_context.py, openpype/hosts/traypublisher/api/plugin.py, openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py, openpype/hosts/traypublisher/plugins/publish/help/validate_existing_version.xml, openpype/hosts/traypublisher/plugins/publish/validate_existing_version.py, openpype/pipeline/create/context.py, openpype/plugins/publish/collect_from_create_context.py, openpype/settings/defaults/project_settings/traypublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json, openpype/tools/standalonepublish/widgets/widget_family.py
Simple creators in TrayPublisher can affect which version will be integrated. Standalone publisher respects the version change from UI.
Standalone publisher is considered as deprecated so TrayPublisher changes will be explained more. Simple creators allow to control integrated version by added bool ("Use next version") and number ("Version to use") inputs where user can enable if custom version is used abd define what version it will be. There is a setting to enable this option per creator. Added optional validator that makes sure if the version does not already exists to avoid possible conflicts with existing versions.
The next version on instance is prefilled on each publisher refresh, so it reflect what is the expected version to integrate. The version cannot be prefilled in create …
=> TrayPublisher & StandalonePublisher: Specify version

openpype/hosts/maya/plugins/publish/collect_arnold_scene_source.py
Suggestion for simpler solution for #5150
=> Simplify bug fix.

openpype/hosts/maya/plugins/publish/collect_instances.py
=> Convert frame handles to int.

openpype/hosts/maya/api/lib.py
=> Maya: Fix set_attribute for enum attributes

openpype/modules/slack/plugins/publish/integrate_slack_api.py
Covered issues found in production on customer site. SlackAPI exception doesn't need to have 'error', covered uncaught exception.
=> Slack - enhanced logging and protection against failure

openpype/settings/defaults/project_settings/harmony.json, openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
It shouldn't be configurable, it is internal logic. By adding additional extension it wouldn't start to work magically.
Matching OP state to Ayon where it was removed previously.
=> Harmony:Removed loader settings for Harmony

openpype/client/server/conversion_utils.py
Workfile update conversion util function have right expected arguments.
=> AYON: Fix args for workfile conversion util

openpype/modules/deadline/plugins/publish/collect_pools.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py
=> Deadline: missing context argument

openpype/hosts/maya/plugins/publish/validate_instance_in_context.py
Missing new publisher error so the repair action shows up.
1. Open a workfile with instances setup.
2. Save as a different asset/shot.
3. Publish and repair the failing validations.
=> Maya: Validate Instance In Context

website/docs/admin_hosts_resolve.md
Missing information about compatible Resolve version and latest docs from https://github.com/ynput/OpenPype/tree/develop/openpype/hosts/resolve
=> Resolve: Update with compatible resolve version and latest docs

openpype/hosts/aftereffects/plugins/publish/extract_local_render.py
Removed unused import from extract local render plugin file.
=> AfterEffects: Removed unused imports

openpype/hosts/houdini/api/plugin.py, openpype/hosts/houdini/plugins/create/create_arnold_ass.py, openpype/hosts/houdini/plugins/publish/validate_workfile_paths.py
I made this PR to solve the issue with hard-coded settings in houdini
Change project settings and check if 
1. "Arnold ASS" changes accordingly 
2. ~~Workfile~~ it's automated for validators, check this [comment](https://github.com/ynput/OpenPype/pull/5400#discussion_r1283008864)
=> Bugfix: houdini hard coded project settings

openpype/client/mongo/__init__.py
Added `load_json_file`, `replace_project_documents` and `store_project_documents` to mongo init.
1. Command `unpack-project` should work again
=> Unpack project: Fix import issue

openpype/plugins/publish/collect_anatomy_instance_data.py
Fixed issues caused by my fault. Filled right version value to anatomy data.
Bug caused here https://github.com/ynput/OpenPype/pull/5262 . Also added `folder` to anatomy fill data.
=> Chore: Versions post fixes

openpype/plugins/actions/open_file_explorer.py
Adds an action in launcher to open the directory of the asset.
1. Open the launcher and navigate to an asset.
2. Select *Open in File Browser*
=> General: Navigation to Folder from Launcher

openpype/client/server/conversion_utils.py
Fixed updates of attribs in AYON mode.
Integrate version attribute plugin should integrate version attributes correctly.
=> AYON: Fix version attributes update

openpype/plugins/publish/extract_burnin.py
This PR fixes missing burnins in reviewables when rendering from UE.
=> added UE to extract burnins families

openpype/pipeline/farm/pyblish_functions.py
- avoiding potential situation where missing Tag key could raise error
1. all should work normally
=> General: missing tag could raise error

openpype/hosts/unreal/plugins/publish/validate_sequence_frames.py, tests/unit/openpype/hosts/unreal/plugins/publish/test_validate_sequence_frames.py, tests/unit/openpype/lib/test_delivery.py, tests/unit/openpype/modules/sync_server/test_site_operations.py
Fixed failing tests.
Updated Unreal's validator to match removed general one which had a couple of issues fixed.
=> Tests: fix unit tests

README.md, tools/docker_build.ps1
Added PowerShell script to run docker build.
1. Run `./tools/docker_build` (with possible variant `centos7` or `debian`)
2. Build should be in `./build` once finished
=> Chore: PowerShell script for docker build

openpype/hosts/houdini/plugins/create/create_vbd_cache.py
Improves VDB selection 
if selection is `SopNode`: 
return the selected sop node
if selection is `ObjNode`: 
get the output node with the minimum 'outputidx' or the node with display flag
It's the same as pointcache (ABC) selection
Try create an instance while selecting:
1. empty `ObjNode` 
2. `ObjNode` with many sop nodes inside it
3. `SopNode`
=> Houdini: Improve VDB Selection

README.md
Fixed github url in README.md.
=> Chore: Use correct git url

openpype/hosts/nuke/plugins/publish/validate_write_nodes.py
Knob values can now be validated against multiple values, so you can allow write nodes to be `exr` and `png`, or `16-bit` and `32-bit`.
1. Add `datatype` of `32 bit float` in `project_settings/nuke/imageio/nodes/requiredNodes/0/knobs/1/type`.
2. Create `render` instance in Nuke and modify the write node inside the output node, to use a different datatype.
3. Publish.
=> Nuke: Allow for knob values to be validated against multiple values.

openpype/hosts/harmony/plugins/publish/collect_farm_render.py, openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py, openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.param, openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.py
- Added support in Deadline Plug-in for new versions of Harmony, in particular version 21 and 22.
- Remove review=False flag on render instance
- Add farm=True flag on render instance
- Fix is_in_tests function call in Harmony Deadline submission plugin
- Force HarmonyOpenPype.py Deadline Python plug-in to py3
- Fix cosmetics/hound in HarmonyOpenPype.py Deadline Python plug-in
=> Harmony: refresh code for current Deadline

tests/integration/hosts/maya/test_deadline_publish_in_maya.py
DL picks up jobs quite slow, so bump up delay.
=> Increase timout for deadline test

openpype/hosts/max/api/plugin.py
Fix the bug shown when clicking "Delete Items from Container" and selecting nothing and press ok.
Please create the new instance instead
1. Launch Max 
2. Create Instance
3. Add items to the container
4. Click "Delete Item From Container"
5. Select Nothing
6. Press Ok
=> Max: bug fix delete items from container

openpype/hosts/max/plugins/publish/extract_pointcloud.py, openpype/hosts/max/plugins/publish/validate_pointcloud.py
Bug fix on the settings being errored out in validate point cloud(see links:https://github.com/ynput/OpenPype/pull/5759#pullrequestreview-1676681705) and passibly in point cloud extractor.
n/a
1. Launch Max via launcher
2. Create Point Cloud Instance 
3. Publish
=> Max: bug fix on the settings in pointcloud family

openpype/hosts/blender/api/capture.py
Include Grease Pencil in review and thumbnails.
1. Publish a model that includes Grease Pencil and a Review.
2. Check that the review and the thumbnails include the grease pencil.
=> Blender: Include Grease Pencil in review and thumbnails

openpype/modules/base.py, openpype/settings/ayon_settings.py
Fixed access to bundles data in settings to define correct develop variant.
=> AYON: Fix bundles access in settings

openpype/hosts/maya/plugins/publish/extract_redshift_proxy.py
Bug fix redshift proxy family not being successfully published due to the error found in integrate.py
n/a
1. Create Redshift Proxy with/without enabling Animation options
2. Publish
=> Maya: Bug fix Redshift Proxy not being successfully published

openpype/hosts/resolve/api/menu.py, openpype/hosts/resolve/utility_scripts/AYON__Menu.py, openpype/hosts/resolve/utils.py
Resolve in Ayon is now having aligned name.
1. open Resolve withing AYON
2. Open menu and notice the name change
=> Resolve: renaming menu to AYON

openpype/hosts/blender/plugins/publish/extract_layout.py, server_addon/blender/server/settings/publish_plugins.py
Changed the labels for Blender's Layout JSON Extractor.
=> Blender: Changed the labels for Layout JSON Extractor

tests/integration/hosts/maya/test_deadline_publish_in_maya/input/workfile/test_project_test_asset_test_task_v001.ma
Skip license check when rendering for testing.
```
openpype_console runtests C:\Users\tokejepsen\OpenPype\tests\integration\hosts\maya\test_deadline_publish_in_maya.py --mongo_url "mongodb://localhost:2707/"
```
=> Testing: Skip Arnold license for test rendering.

openpype/modules/deadline/plugins/publish/submit_houdini_cache_deadline.py
`hou` module should be within the class code else we'll get pyblish errors from needing to skip the plugin.
1. Submit Deadline render from Houdini.
2. Validate the renders are successfull.
=> Testing: hou module should be within class code.

openpype/vendor/python/common/ayon_api/_api.py, openpype/vendor/python/common/ayon_api/constants.py, openpype/vendor/python/common/ayon_api/entity_hub.py, openpype/vendor/python/common/ayon_api/graphql.py, openpype/vendor/python/common/ayon_api/graphql_queries.py, openpype/vendor/python/common/ayon_api/server_api.py, openpype/vendor/python/common/ayon_api/utils.py, openpype/vendor/python/common/ayon_api/version.py
Updated ayon-python-api to '1.0.0-rc.1'.
The new version is adding few important changes, like fix of `get_latest_versions` and added ability to define default settings variant with environment variable.
NOTE: This change can be recognized only if not in AYON launcher process (in DCCs).
- All tools and publishing should work.
=> AYON: Update ayon python api

openpype/modules/python_console_interpreter/window/widgets.py, openpype/tools/experimental_tools/dialog.py, openpype/tools/publisher/control.py, openpype/tools/publisher/window.py, openpype/tools/tray/pype_info_widget.py
Replaced OpenPype with AYON in AYON mode and added bundle nam to information.
1. Check changed tools if are showing correct labels.
2. Report more places if there are any.
=> AYON: Use AYON label in ayon mode

openpype/modules/deadline/abstract_submit_deadline.py
This quickly fixes bug introduced by #5420
Deadline submission from non-houdini host should work
=> Bugfix: handle missing key in Deadline

openpype/hosts/aftereffects/plugins/create/create_render.py
Removing of `render` instance caused renaming of composition to `dummyComp` which caused issue in publishing in next attempt.
This PR stores original composition name(cleaned up for product name creation) and uses it if instance needs to be removed.
1.create instance in AE in Publisher
2. remove it, check name of composition
=> OP-7535 - Fix renaming composition in AE

openpype/plugins/publish/extract_thumbnail.py
Minor code change for optimisation of thumbnail workflow.
The code change modifies the `ExtractThumbnail` class in `extract_thumbnail.py`. It updates the loop that iterates over representations to handle cases where the "representations" key is missing from the instance data. This change ensures that cleanup occurs for representations with both "delete" and "need_thumbnail" tags.
=> Refactor code to handle missing "representations" key in instance data

openpype/vendor/python/common/ayon_api/__init__.py, openpype/vendor/python/common/ayon_api/_api.py, openpype/vendor/python/common/ayon_api/entity_hub.py, openpype/vendor/python/common/ayon_api/server_api.py, openpype/vendor/python/common/ayon_api/version.py
Updated ayon python api to 1.0.0-rc.3.
This verison contains fix when connecting to server `1.x`.
=> AYON: Update ayon api to 1.0.0-rc.3

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/plugins/publish/extract_playblast.py, openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Proposing some code cleanup for existing PR #5942
@moonyuet
=> Code cleanup

openpype/hosts/traypublisher/plugins/publish/validate_filepaths.py
Use correct label for Validate filepaths.
=> Traypublisher: Correct validator label

openpype/modules/ftrack/event_handlers_user/action_djvview.py
Fix bugs in DJV  ftrack action.
Fixed misspelled variable name, convert executable to string, and access event values from correct variable. Changed formatting to use double quotes.
1. Launch OpenPype with enabled ftrack.
2. Make sure you have djv in applications with valid path.
3. Show actions for asset version in ftrack, published from OpenPype.
4. Choose DJV action.
5. It should start DJV.
=> Ftrack: DJV action fixes

openpype/tools/ayon_workfiles/models/workfiles.py
Fix parenthesis typo with arrow local timezone function.
=> AYON Workfiles tool: Fix arrow to timezone typo

openpype/modules/ftrack/launch_hooks/post_ftrack_changes.py
Fix lowerin of values in status mapping.
1. Post launch hook should not crash on application launch
=> Ftrack: Post-launch hook fix value lowering

openpype/tools/publisher/control.py
This PR targets to fix issue #6234.
1. Make an action fail on purpose. 
2. "Action Failed" window should appear and display information properly.
=> Bugfix - Fix "Action Failed" window not showing

openpype/modules/deadline/plugins/publish/submit_max_deadline.py
Improvement on https://github.com/ynput/OpenPype/pull/6231
=> Tests: Fix failing maya automatic test
