openpype/hooks/pre_non_python_host_launch.py
openpype/hosts/tvpaint/hooks/pre_launch_args.py
openpype/lib/__init__.py
openpype/lib/execute.py
openpype/lib/pype_info.py
openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py
openpype/modules/default_modules/ftrack/ftrack_server/socket_thread.py
openpype/modules/standalonepublish_action.py
openpype/plugins/publish/extract_burnin.py
openpype/tools/standalonepublish/widgets/widget_components.py
openpype/tools/tray/pype_tray.py

Environment PYTHONPATH may break dependencies of OpenPype.
This issue was found due to missing implementation of `distutils.spawn` which is overriden with Python 2 vendor (e.g. from Nuke). This is almost imposible to catch on OpenPype start as importing of defaukt Python module may be also modified with PYTHONPATH.
- implemented `clean_envs_for_openpype_process` which modify envs so OpenPype subrpocess won't be affected by current env values (currently only removes PYTHONPATH env)
- implemented `run_openpype_process` which use `clean_envs_for_openpype_process` and prepend openpype executable args
- use `run_openpype_process` in `ExtractBurnin` plugin
- renamed `get_pype_execute_args` -> `get_openpype_execute_args`

General: PYTHONPATH may break OpenPype dependencies

---

openpype/hosts/maya/api/lib.py

The Maya validators *Validate Mesh Non Zero Edge* and *Validate Mesh NGONs* rely on using Maya's poly selection constraints to quickly retrieve the relevant components. However, since these rely on Maya selection of actual vertices/edges there are UI edges cases that can make this query very slow for high-res meshes.
The issue is basically that it is extremely slow when the user is NOT currently in the Select tool context. As if other manipulators do some extra processing during this step that introduces a huge performance drop. Previously it could literally take **MINUTES** for a very a bunch of very high res meshes to be processed.
This PR implements an optimization by ensuring the tool context is currently set to the the Select tool and not e.g. the Translate, Rotate, Scale or other …

Improve lib.polyConstraint performance when Select tool is not the active tool context

---

openpype/hosts/houdini/plugins/load/load_alembic.py
openpype/hosts/houdini/plugins/load/load_camera.py

This removes the unique name counter in some Houdini loaders and resolves #2449.
However, it requires a change in `avalon.houdini.pipeline` as well.
In particular [this line](https://github.com/pypeclub/avalon-core/blob/ffe9e910f1f382e222d457d8e4a8426c41ed43ae/avalon/houdini/pipeline.py#L148) should be changed to:
```python
container.setName(container_name, unique_name=True)
```
With this change the [`children_as_string` method can also be removed from `avalon.houdini.lib`](https://github.com/pypeclub/avalon-core/blob/ffe9e910f1f382e222d457d8e4a8426c41ed43ae/avalon/houdini/lib.py#L7-L8) since it's only used throughout the code base for these two loaders.

Houdini: Remove broken unique name counter

---

openpype/plugins/publish/integrate_new.py

Previously expression didn't trigger as `repre.get("frameStart")` returned 0 which translated into False
This resulted in using frame value in source padding which might had been different from final, correct value.
In AE it manifested when artist manually updated frame pattern in Render Queue, used more `#` than is in final pattern from Anatomy (which is `####`).  AE rendered locally files with `00000` temporarily, `integrate_new` used correct padding for publishing, but `representation.context.frame` stayed with wrong value (`00000` instead of `0000`).
This might have happened in another hosts too.
1. add new Render Queue in AE, choose "PNG" as destination format
2. modify name there to contain more or less # than 4
3. render locally
4. check published files, they will be correct
5. …

Fix published frame content for sequence starting with 0

---

openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json

As [per request of Dillon Sindon (Lucan) on Discord](https://discord.com/channels/517362899170230292/563751989075378201/930864370756497469) here's a PR to expose the enabled status for the Maya Look Shading Engine Naming Validator.
The first step was to add it to the project settings definition in: `openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json`
By using the [validator's class name: `ValidateShadingEngine`](https://github.com/pypeclub/OpenPype/blob/f5c0c6453383c7a64e5ce3340c7227e11720c8e8/openpype/hosts/maya/plugins/publish/validate_look_shading_group.py#L8)
```json
{
"type": "schema_template",
"name": "template_publish_plugin",
"template_data": [
{
"key": "ValidateShadingEngine",
"label": "Validate Look Shading Engine Naming"
}
]
},
```
After that we …

Expose toggle publish plug-in settings for Maya Look Shading Engine Naming

---

openpype/hosts/maya/api/lib.py

This PR implements a fix for #2497

Fix #2497: reset empty string attributes correctly to "" instead of "None"

---

igniter/bootstrap_repos.py
tools/create_zip.py

this is fixing wrong type passed when using **create_zip** tool with `--path` argument.
Close #2451

Fix create zip tool - path argument

---

openpype/modules/slack/plugins/publish/integrate_slack_api.py
openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
website/docs/module_slack.md

Currently only thumbnail is present, it was required to add link to review.
There are two options now how to add review to Slack notification message. 
- upload file - burnin version is preferred if present
- use {review_link} placeholder in content of message
Uploading of review must be though through as in case of large sizes of reviews publish might be too slow and one will be hitting on Slack limits pretty soon.
Contained in #2499, use #2499 to test both.
1. Use configuration like: ![Screenshot 2022-01-07 121535](https://user-images.githubusercontent.com/4457962/148536219-4c3bd988-28b0-48e5-8cff-9cd081a93438.png)  (full bot key in Keeper under 'Slack bot token')
2. Publish any `render` family
3. Check `test_integration` channel

Slack: Add review to notification message

---

openpype/hosts/houdini/plugins/publish/collect_frames.py

Houdini's collect_frames plugin has a bug in frame range check.
It's fairly minor issue. 
We assume the 'endframe' is the last frame *to be included*. 
Thus, the current condition works for all cases, except a frame range of 2 frames, e.g. [1001-1002] , in this case it'll incorrectly consider it to be single frame publish. This isn't affecting almost all realistic use cases.. we simply spotted this during some testing. 
Technical artist spotted this, so I surfaced his commit from our internal git system.

Fixed bug: Minor inaccuracy in multi-frame calculation

---

openpype/hosts/maya/plugins/publish/validate_shape_zero.py

Previously when performing repair on the Validate Shape Zero plug-in the last processed mesh would remain highlighted for all its individual vertices. This fixes that issue.

Maya: Validate Shape Zero do not keep fixed geometry vertices selected/active after repair

---

website/docs/module_slack.md

There was left one occurrence of old variable name in documentation.

Renamed to proper name

---

igniter/bootstrap_repos.py
igniter/install_thread.py

InstallThread in igniter is using not existing method `get_local_live_version`.
- replaced `get_local_live_version` with `OpenPypeVersion.get_installed_version_str`
1. Turn off mongo server
2. Run openpype
3. Turn on mongo server
4. Press start
5. Process should not stuck
1. Remove mongo url from keyring (Credentials on windows)
2. Run openpype
3. Enter valid mongo url
4. Process should not stuck

General: Fix install thread in igniter

---

openpype/settings/entities/input_entities.py

PathInput makes sure there are no whitesymbols at the start/end of value.
- strip value of PathInput on set and on loading of settings values
1. Try to pass any path starting/ending with space

Settings: PathInput strip passed string

---

openpype/modules/default_modules/ftrack/event_handlers_user/action_djvview.py

Current DJV action is looking for DJV path into env variable `DJV_PATH` but we have DJV in system settings.
- DJV action is using ApplicationManager to get path to DJV
- action will offer to choose from available djv versions if there are more
1. Set path to DJV in settings
2. Try to run the action it on Asset Version that has components with full path

Ftrack: Use ApplicationManager to get DJV path

---

.github/workflows/test_build.yml
openpype/lib/__init__.py
openpype/tools/tray/pype_tray.py

Current check of updates does not expect that version check is not available for current openpype build.
- skip version validation if build does not store `OpenPypeVersion` to `sys.modules`.
1. Run OpenPype zip from this branch in older OpenPype build

General: Do not validate version if build does not support it

---

openpype/hosts/fusion/hooks/pre_fusion_setup.py

This is related to #2500 
Improve FusionPreLaunch hook error readability + make it a pop-up from the launcher.
- I've removed the usage of ` in the string as they would convert into special characters in the pop-up. So those are changed to '.
- Also fixed mention of `environments/resolve.json` to `environments/fusion.json`.

Improve FusionPreLaunch hook errors

---

openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_asset.py

Ftrack delete action crashes if entity that has children was deleted using ftrack api.
- find all children of entities to delete and delete them from bottom to the selection
- modified message which will popup when selected ftrack entities does not have avalon equivalent
- message text: "Didn't found entities in avalon. You can use Ftrack's Delete button fot this selection."
1. Run delete asset/subset on ftrack entity that has avalon asset and published subsets with asset versions in ftrack
2. Confirm deletion
3. No error should be shown

Ftrack: Delete action revision

---

openpype/lib/remote_publish.py

Previously fail message was at the end of log, which was a lot of scrolling.
Moved error message to the beginning of log. Separate by line of '-' for potential parsing
1. Run webpublish that would fail (maybe some validation error)
2. Check front end for failed log

Webpublisher: Moved error at the beginning of the log

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
openpype/modules/default_modules/ftrack/plugins/publish/collect_username.py
openpype/pype_commands.py

Ftrack username wasn't collected for 'studio' processing webpublishes (eg. workfile sent for rendering).
Added storing user  email into environment variable. This value is used first, only if not present, `user_email` on instances is checked.
1. Run webpublish from PS
2. Check Ftrack

Webpublisher: ftrack shows incorrect user names

---

openpype/hosts/maya/plugins/load/load_ass.py

Fix get_reference_node call as it was out of date because of API changes

Fix Maya AssProxyLoader version switch

---

openpype/hosts/maya/api/customize.py

This PR relates to #2539 and avoids Maya Look Assigner getting initialized on Maya launch. The code change is basically a full removal of checking whether Maya Look Assigner exists on startup since the code for it is embedded directly within OpenPype and [always gets added to `sys.path`](https://github.com/pypeclub/OpenPype/blob/7a2164cf4f941ed0ac313ea9add5aa6436c1bff8/openpype/hosts/maya/__init__.py#L10). **_It would be good to know if there are any expected issues with this check being fully removed._**
This PR also removes the background color flag on the icons - because it didn't seem to make any difference when I removed it.
---
Note: Changes to this code will conflict on merge with changes in #2445 but merging them should be trivial since they don't influence the exact same lines of …

Maya: Remove Maya Look Assigner check on startup

---

openpype/hosts/maya/plugins/load/load_reference.py

(cherry picked from commit f1b7aed767b76bced648b785dc3d40a68b36db7b)
Very simple fix which actually avoids the error. It's not necessarily a full cleanup as to the root of the problem and why it could fail in the first place. It's a hotfix for #2528 
Later we can look into more accurate ways to retrieve the root group of a reference without issue. (Hint: Maya actually creates a connection from the reference node to the root group, we can abuse that!)

Maya: ReferenceLoader fix not unique group name error for attach to root

---

openpype/hosts/maya/api/lib.py

Small fix for where `openpype.hosts.maya.api.lib.namespaced` context manager wouldn't go back to original state when started from inside a namespace.
**To reproduce**
```python
cmds.file(new=True, force=True) # clear scene
cmds.namespace(add=":aap")
cmds.namespace(add=":aap:foo")
cmds.namespace(set=":aap")
before = cmds.namespaceInfo(currentNamespace=True, absoluteName=True)
print("Before -> %s" % before)
with lib.namespaced(":aap:foo", new=False):
during = cmds.namespaceInfo(currentNamespace=True, absoluteName=True)
print("During -> %s" % during)
after = cmds.namespaceInfo(currentNamespace=True, absoluteName=True)
print("After  -> %s" % after)
assert before == after
```
That should work fine and print out:
```
Before -> :aap
During -> :aap:foo
After  -> :aap
```
But before this PR it …

Maya: namespaced context go back to original namespace when started from inside a namespace

---

openpype/hosts/maya/plugins/publish/extract_look.py

This fixes #2055.
With this changed the source and destination filepath is now escaped with `"` quotes in the call to subprocess when a space is in the path. We're also doing this for the `sourceHash` argument since that uses the filename as part of the hash and had the same issue.
1. Publish a look that uses a texture with a space in filename.
2. Assign the look
I've tested the publishing plus look assignment. It looks solid on my end. 👍

Maya: Fix Extract Look with space in names

---

openpype/hosts/houdini/plugins/publish/collect_instances.py
openpype/hosts/houdini/plugins/publish/extract_vdb_cache.py
openpype/plugins/publish/validate_version.py

This PR fixes a bug with VDB publishes from Houdini so that it actually preserves its original frame numbers (otherwise would always get remapped to start at frame 0 by the integrator - even though the loader would still show frameStart and frameEnd as the non-remapped range.)
- The [Integrator requires `frameStart` data to be present on the `representations` to preserve the frame numbers upon integrating](https://github.com/pypeclub/OpenPype/blob/7d016ab82ca7d68695926b7ff49d6ef500218603/openpype/plugins/publish/integrate_new.py#L455) - I've added `frameEnd` too just to be consistent.
- [We had to include `families` data otherwise the integrator would error here](https://discord.com/channels/517362899170230292/563751989075378201/931579623593087027)
Publishing frame range 1000-1015 …

Houdini: vdbcache family preserve frame numbers on publish integration + enable validate version for Houdini

---

openpype/hosts/maya/plugins/load/load_vdb_to_vray.py

(cherry picked from commit d53db6cd2b02a9b4ac251c70d600b47cc5e2493c)
This fixes the VDB Loader for V-Ray render engine. 
There are some annoying bugs in V-Ray for which I tried to document the code as much as possible. But working around those particular issues is why this code is relatively lengthy.
Tested in Maya 2022.1 with V-Ray 5 for Maya, update 2.1 (v5.20.01 from Dec 16 2021)
Tested using a `.vdb` publish from Houdini.

Maya: Fix Load VDB to V-Ray

---

openpype/hosts/maya/api/lib.py
openpype/hosts/maya/plugins/create/create_review.py

Here's a draft implementation for #2443 where it remains exposed on the Review family but is removed from the others. It's still up for discussion whether it's even relevant for the Review family too. I'm not entirely sure that attribute actually influences the output of the created review since I couldn't easily trace that in the code.

Maya: Collect 'fps' animation data only for "review" instances

---

openpype/hosts/maya/plugins/load/load_vrayproxy.py

Add option to load alembic files published using `model` family with V-ray proxy loader.
1. load alembic model from OP loader with `Import VRay Proxy (abc)`.

Maya : V-Ray Proxy - load all ABC files via proxy

---

openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
openpype/tools/utils/lib.py

This implements #2516 
It adds an extra boolean checkbox in Admin Settings for Family Filters to decide whether the filtering is to "include" what you've selected or to "exclude" what you've selected.
Like the label describes in settings it works like this:
- Include: **show** selected families by default. Hides others by default.
- Exclude: **hide** selected families by default. Shows others by default.
So on Exclude always all families will be enabled except for those selected in the filter. On Include, it behaves like before, only the families you select in settings are enabled by default in the Loader.
This is how it looks in Settings:
👍 I tested it in Maya 2020 on both include and exclude mode and it worked as intended.

Loader: Allow to toggle default family filters between "include" or "exclude" filtering

---

openpype/plugins/publish/collect_otio_review.py

Collect OTIO review fix on track names.
Track names were picked by mistake and no clips were found in them to publish as review.

global: track name was failing if duplicated root word in name

---

openpype/hosts/maya/plugins/create/create_vrayscene.py
openpype/hosts/maya/plugins/publish/collect_vrayscene.py

This is fixing obsolete use of API to determine Deadline URL that was causing creator crash.
⚠️ *WARNING:* extracting vrscene will pass even it you don't have valid vray license (for example using demo license). It will than fail on integration step.

`vrscene` creator Deadline webservice URL handling

---

openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py

Subset name for color coded layer that should be published needs to use task name, not task type.
1. Use Webpublish for studio processing for Photoshop
2. Check published subset name for color coded layers, it should contain task name, not tasky type

Webpublisher: Fix - subset names from processed .psd used wrong value for task

---

poetry.lock
pyproject.toml

This is fixing openpype private repository used in poetry to be considered as *secondary* so it will not override default [pypi,org](https://pypi.org/). Also updated [speedcopy](https://pypi.org/project/speedcopy/) so it includes bug fixes.

Fix poetry index and speedcopy update

---

tools/build_dependencies.py

`./tools/build_dependencies.py` was using `distutils.util.get_platform()` to determine folder where openpype is built. As distutils are now [deprecated](https://docs.python.org/3/whatsnew/3.10.html#distutils), this is switching `get_platform()` to **sysconfig** module with similar functionality.
This is also fixing rare cases where platform was reported differently by distutils and sysconfig (`win32` vs. `win-amd64`).

switch distutils to sysconfig for `get_platform()`

---

pype/plugins/tvpaint/publish/extract_sequence_exr.py

**Goal**
Support EXR (DWAA) in TVPaint.
**Motivation**
We are battling large data transfers when using the built image formats. EXR (DWAA) has a very small data footprint compared to TVPaint native image formats.
**Implementation**
This extractor will convert all output (representations) to EXR (DWAA). Its disabled by default but can be enabled with a config:
```
{
"ExtractSequenceEXR": {
"active": true
}
}
```
This would be good to convert to 3.0 when merged, as its just needs a setting under TVPaint.

TVPaint: EXR Extractor

---

openpype/hosts/webpublisher/plugins/publish/extract_thumbnail.py

Current thumbnail extractor in global is based on specific workflow which should work in different way in webpublisher so easier way is to create webpublisher specific plugin for thumbnail extraction.
- removed `webpublisher` from global plugin `ExtractJpegExr`
- created new thumbnail extractor in webpublisher host
I've added `image` and `render` families there but if any others should be added there then do it (@kalisp or @64qam).

Webpublisher: Thumbnail extractor

---

openpype/plugins/publish/collect_scene_version.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
tests/integration/README.md

Added `CollectSceneVersion` to Settings. Added option to configure skipping it for headless publishing.
One might want to skip collecting/validating presence of version number in published workfile (in case of studio processing).
In that case, integrator will use next version number automatically.
Currently applicable only for Photoshop triggered by webpublisher with studio processing.
1. Try to publish PS workfile without version number via Webpublisher (should fail)
2. Apply this PR
3. Add 'photoshop' into `Skip for host if headless publish` in `project_settings/global/publish/CollectSceneVersion`
4. Publish it again

Webpublisher: Skip version collect

---

openpype/tools/sceneinventory/switch_dialog.py

Detected a typo in the code for the Switch Dialog. I'm not sure what actual issues this might have caused for the code. I'm just here to refactor the actual faulty code.
Seems like it could have caused issues when both *asset* and *subset* were selected where available *representations* would not get queried correctly.

Scene Inventory: Fix type name for 'representation' in switch logic

---

openpype/settings/defaults/project_settings/photoshop.json
openpype/settings/entities/enum_entity.py

Resolve issue when enum stores empty string instead of selected item.
- make sure enum has set `_current_value` to valid key
Resolves: https://github.com/pypeclub/OpenPype/issues/2614

Settings: Enum does not store empty string if has single item to select

---

openpype/hosts/maya/api/__init__.py
openpype/pipeline/lib/__init__.py
openpype/pipeline/lib/events.py
openpype/tools/workfiles/app.py

Workfiles tool does not know how to work when workfiles directory does not match workdir path which cause issues in maya where workspace.mel is created and when extra folders should be created.
- in Workfiles tool renamed `root` to `_workfiles_root` and added attribute `_workdir_path` which may not be the same
- added base of objected events where only one argument (object of the event) is passed to callback
- this approach gives more abilities for backwards compatibility when we need to tweak arguments for callbacks
- use objected events to pass workfile path with workdir path into callback
- maya callback is looking for workfile directory instead of directory where workfile is
Expected that we're testing in Maya
1. Set `AVALON_SCENEDIR` environment in maya and set it to `"scene"`
2. Add …

Workfiles Tool can handle when workfile is not created directly in workdir path

---

openpype/lib/vendor_bin_utils.py

`get_oiio_tools_path()` didn't take into account extension on windows. So trying to get path for `maketx` - returned path like `C:\foo\bar\oiio\bin\maketx` that is invalid on Windows because it should be `C:\foo\bar\oiio\bin\maketx.exe`. This PR is providing simple fix to add `.exe` on windows if it is missing. Note that it will not work for other executable files on windows, like shell scripts, and so on, but because this is strictly **OIIO tool** specific I don't see problem with it.
Without this fix, extracting looks from maya on windows will fail.

hotfix: OIIO tool path - add extension on windows

---

openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py

Task name and asset name pulled from batch manifest file
1. Run Webpublish with studio reprocessing for PS

Fix - safer pulling of task name for webpublishing from PS

---

openpype/hosts/photoshop/plugins/create/create_image.py

Photoshop Creator Behavior:
- if `use selection`:
- if you create a subset group for the whole selection, the subset takes the name of the interface.
- if several objects are selected, the subset takes the name of the interface + the group
- if not `use selection`, create an empty group subset in top level with the name of the interface subset

Photoshop: Fix subset name match creator if use selection

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/startup/clear_rendered.py

User can use `Clear Rendered` on write node.
In case users need to remove all content of rendering folder, they can use clear button. 
1. open your testing workfile
2. in case render node is already created then remove it
3. create render/prerender node and notice `Clear Rendered` button
4. if in case you are sure some content in rendering folder exists then use the button and see that all will disapear.

nuke: adding clear button to write nodes

---

openpype/hosts/tvpaint/plugins/load/load_image.py
openpype/hosts/tvpaint/plugins/load/load_reference_image.py

It is not possible to import/load review family in TVPaint.
- image import and reference loaders can load `review` families

TVPaint: Image loaders also work on review family

---

openpype/cli.py
openpype/lib/project_backpack.py
openpype/pype_commands.py

Create and load packages of project with all files and mongo documents for development and testing purposes.
Be able to create a package of project with all documents and files related to project can be usefull for development or testing purposes. Implementation is not meant for production purposes (at least not at this stage) and has few requirements to be able do that.
Created package is a zip containing json with metadata about package and json with mongo documents and folder with project files from root level.
Unpacking project will replace all mongo documents if there were any and rename project folder if there is existing one.
- project must have only one root
- all project template paths must start with `{root[...]}/{project[name]}`
- created `project_backpack.py` in openpype lib …

General: Project backup tools

---

openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py
openpype/hosts/photoshop/plugins/publish/validate_unique_subsets.py
openpype/lib/remote_publish.py
openpype/pype_commands.py

In rare cases of existing created subset in the workfile validation of subset uniqueness could fail.
Added skip condition if subset was already created.
1. Prepare workfile that contains created instance in metadata with subset name that would be created after `CollectRemoteInstances`
2. Publish it through WP

WebPublisher: fix instance duplicates

---

Dockerfile
Dockerfile.centos7
tools/docker_build.sh

This is fixing pyenv initialization in dockerfile for ubuntu, where `.bashrc` wasn't for some reason sourced even when it was done explicitely. It's initialization was moved to another script file. Changed base image from debian to Ubuntu 20.04 Focal LTS to meet various dependency issues between versions of available glibc and ncurses.
Added additional metadata to image about build date and openpype version.

Docker: enhance dockerfiles with metadata, fix pyenv initialization

---

openpype/hosts/photoshop/api/lib.py

Fixed AVALON_PHOTOSHOP_WORKFILES_ON_LAUNCH environment variable not being retrieved correctly.

Fix open workfile on launch in photoshop

---

openpype/hosts/houdini/api/__init__.py
openpype/hosts/houdini/api/lib.py
openpype/hosts/houdini/api/pipeline.py
openpype/hosts/houdini/api/plugin.py
openpype/hosts/houdini/api/workio.py
openpype/hosts/houdini/plugins/create/create_hda.py
openpype/hosts/houdini/plugins/load/load_alembic.py
openpype/hosts/houdini/plugins/load/load_camera.py
openpype/hosts/houdini/plugins/load/load_hda.py
openpype/hosts/houdini/plugins/load/load_image.py
openpype/hosts/houdini/plugins/load/load_usd_layer.py
openpype/hosts/houdini/plugins/load/load_usd_reference.py
openpype/hosts/houdini/plugins/load/load_vdb.py
openpype/hosts/houdini/plugins/publish/collect_instances.py
openpype/hosts/houdini/plugins/publish/collect_instances_usd_layered.py
openpype/hosts/houdini/plugins/publish/collect_remote_publish.py
openpype/hosts/houdini/startup/MainMenuCommon.xml
openpype/hosts/houdini/startup/scripts/123.py
openpype/hosts/houdini/startup/scripts/houdinicore.py

Moved Houdini implementation into OpenPype.
- moved houdini from avalon into openpype repository
1. Houdini should work as before
Related to https://github.com/pypeclub/avalon-core/pull/420

Houdini: Moved to OpenPype

---

openpype/hosts/aftereffects/plugins/publish/collect_render.py
openpype/hosts/harmony/plugins/publish/collect_farm_render.py
openpype/lib/abstract_collect_render.py
openpype/modules/default_modules/deadline/plugins/publish/collect_default_deadline_server.py
openpype/modules/default_modules/deadline/plugins/publish/submit_aftereffects_deadline.py
openpype/modules/default_modules/deadline/plugins/publish/submit_harmony_deadline.py
openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_remote_publish.py
openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_render_deadline.py
openpype/modules/default_modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/modules/default_modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
openpype/settings/defaults/project_settings/deadline.json
openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json

Add option to pass mongo url to deadline job.
- added attributes `pass_mongo_url` to `CollectDefaultDeadlineServer` plugin which is used in submitters to define if `OPENPYPE_MONGO` environment is passed to job environments
1. Trigger deadline publishing
2. The job (worker) should not need to have set mongo url in keyring or in global environments

Deadline: Be able to pass Mongo url to job

---

Dockerfile.centos7

Add path to fix this problem:
```
Downloading Python-3.7.12.tar.xz...
-> https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tar.xz
Installing Python-3.7.12...
/root/.pyenv/plugins/python-build/bin/python-build: line 1638: patch: command not found
BUILD FAILED (CentOS Linux 7 using python-build 20180424)
```

Fix python install in docker for centos7

---

openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
openpype/modules/default_modules/ftrack/lib/avalon_sync.py

Sync description key from ftrack entities to assets in avalon db.
- sync action will also sync `"description"`
- sync event cares about changes of description
1. Run Sync to avalon
2. description should be synced
1. Run eventserver
2. turn on auto sync on project
3. change description on asset
4. description should be changed

Ftrack: Sync description to assets

---

openpype/tools/project_manager/project_manager/delegates.py
openpype/tools/project_manager/project_manager/widgets.py

Implements #2677 
1. Open Project Manager with some assets in a test project
2. Test whether scrolling over float and integer fields changes values - it shouldn't.
3. No click inside the float/integer field to give it focus, confirm it now does allow you to change value with scroll wheel.

Project Manager: Only allow scroll wheel edits when spinbox is active

---

openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json

It could be potentially dangerous to have CleanUpFarm plugin enabled by default https://github.com/pypeclub/OpenPype/pull/2390#issuecomment-1032811166.
- added settings for `CleanUpFarm` plugin and disable the plugin by default

General: Add settings for CleanUpFarm and disable the plugin by default

---

openpype/tools/launcher/models.py
openpype/tools/launcher/widgets.py

Changing of attribute `data` breaks other than application actions because they don't have `data` attribute.
- Change of data happens only on `ApplicationAction` classes

Launcher: Fix access to 'data' attribute on actions

---

openpype/lib/transcoding.py

Conversion for ffmpeg is also checking length of string stored in exr attributes because ffmpeg has limit up to 8196 characters.
- information about input file from oiiotool are loaded using xml format
- this gives more and more precise information about input
- all attributes with string values longer than 8196 are removed from exr to be able pass it to ffmpeg
- few smaller tweaks of oiiotool conversion
- oiiotool loads only channels that are used for output so works a little bit faster with reducing memory leak issues
- function for converting does not require frame start/env arguments 
1. Try publish exrs with string attributes which have value longer than 8196 characters (e.g. cryptomatte stores whole manifest)
2. It should be able to create review and thumbnail just fine

General: FFmpeg conversion also check attribute string length

---

openpype/hosts/hiero/plugins/publish/collect_clip_effects.py

the order was wrong and therefore name has to change to collector only
`Collect OTIO Frame Range` had to precede this plugin otherwise `startFrame` attribute was missing in `instance.data` of effect instance.
1. open any of your testing project with a softeffect on a publishable clip
2. see that `Collect Clip Effects Instances` is shown after `Collect OTIO Frame Ranges`

hiero: fix effect collector name and order

---

openpype/hosts/webpublisher/plugins/publish/collect_batch_data.py
openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
openpype/settings/defaults/project_settings/webpublisher.json
openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json

Changed settings to list instead of dictionary to allow single frame and multiframe sequences into same family
Former implementation was dictionary, so single family couldn't be assigned to sequences (pngs) or single file (mp4).
1. Update `project_settings/webpublisher/publish/CollectPublishedFiles/task_type_to_family`
2. Publish single file or sequence

WebPublisher: Updated Settings

---

openpype/modules/default_modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py
openpype/modules/default_modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py
openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
openpype/modules/default_modules/ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
openpype/modules/default_modules/ftrack/event_handlers_user/action_create_cust_attrs.py
openpype/modules/default_modules/ftrack/ftrack_module.py
openpype/modules/default_modules/ftrack/lib/avalon_sync.py
openpype/modules/default_modules/ftrack/lib/custom_attributes.py

It was discovered that `ContextCustomAttributeValue` does return default value of custom attribute if entity does not have set value explicitly which is an issue for querying of hierarchical attribute values.
- 'query_custom_attributes' has ability to return only explicitly set values or all values with defaults
- added new argument `only_set_values` to define if `CustomAttributeValue` or `ContextCustomAttributeValue` table is used to get values
- almost all places that query custom attributes are using 'query_custom_attributes'
- Create new project with some structure
- Find one hierarchical custom attribute (e.g. `fps`) and set default value to something
1. Set different then defaut value on project
2. Run sync to avalon
3. Check attribute values on assets (e.g. in project manager) they …

Ftrack: Hierarchical attributes are queried properly

---

openpype/hosts/maya/api/lib_renderproducts.py
openpype/hosts/maya/plugins/create/create_render.py
openpype/hosts/maya/plugins/publish/validate_rendersettings.py

this is fixing various issues there were for Redshift support (#2446, #1825), invalid default image prefix and ignoring AOV character separator option.
Close #2446
Close #1825

Maya Redshift fixes

---

openpype/hosts/maya/plugins/publish/validate_maya_units.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json

this is adding configurable options for Maya Units validator.
Most of the options should be set later in different place - by something like scene defaults settings.
🗒️ There is also issue #2620 with fps decimal rounding that needs to be investigated between supported maya versions and ftrack.

Maya configurable unit validator

---

openpype/hosts/houdini/plugins/publish/collect_frames.py

(cherry picked from commit 0f82a753560e362be731d0d14177c4f3edbf1db0)
There was a bug in Houdini that whenever you do have a frame range set of just a single frame, e.g. `1001-1001` then `collect_frames` would actually eval the filename on the current frame instead of that start frame. Thus if you're writing to a file with `$F` the file would be named different than what the ROP node would actually output
Here's an example error that could happen. The integrator here fails to copy the file becuase the ROP node actually rendered another file than was "collected" as expected resulting filename from the ROP node.
```
Instance: 
vdbcachesmoke_room (160) [1001.0 - 1001.0]
Message: 
[WinError -2147024894] The system cannot find the file specified
Line: 
933
Traceback: 
Traceback (most recent …
```

Houdini Explicitly collect correct frame name even in case of single frame render when `frameStart` is provided

---

openpype/hosts/houdini/api/lib.py
openpype/hosts/houdini/plugins/create/create_arnold_ass.py
openpype/hosts/houdini/plugins/publish/collect_frames.py
openpype/hosts/houdini/plugins/publish/extract_ass.py
openpype/settings/defaults/project_settings/houdini.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_houdini_create.json

This implements the creation and publishing of Arnold proxies (`.ass` or `.ass.gz`) from Houdini.
Currently defaults to ~`.ass.gz`~ (changed with https://github.com/pypeclub/OpenPype/pull/2603/commits/dd92fe1e4ee9a195b85d7aa6b4234fba2829dec4) `.ass`
Detecting whether a filename ends with a multidot extension like `.ass.gz` isn't fool proof. It's hard to know whether something is just an extra dot in a filename or actually is part of the extension. As such I've opted for logic that explicitly says that it allows `.ass.gz` as extension.
It does mean some hardcoded logic for that - but will definitely reduce false positives. If anyone knows a better way I'd be happy to hear it.
No matter whether you publish `.ass` or `.ass.gz` extensions the resulting representation name is `ass`. This just …

Houdini: Implement Arnold .ass standin extraction from Houdini (also support .ass.gz)

---

openpype/hosts/houdini/plugins/load/load_ass.py

Implement an `.ass` Arnold Procedural Loader for Houdini
- Requires `htoa` (Houdini to Arnold) to be installed for Houdini.
- Tested in Houdini 19.0.455 with `htoa-6.0.2.0_r0ad447a_houdini-19.0.455.py3` with published output from #2603 ✅

Houdini: Load Arnold .ass procedurals into Houdini

---

igniter/bootstrap_repos.py
igniter/install_dialog.py
igniter/tools.py
start.py

This is a draft PR to implement some changes to optimize some pieces from the OpenPype startup and is related to #2592 to allow less overhead when initializing to the environment.
I've gone ahead and started some minor tweaks. Some are just optimizations I figured could work glancing over the code (e.g. restructuring validate dir/zip logic) which only would make it faster in certain cases (for that particular case only when files would be missing).
The bigger improvement is to keep `global settings` around during startup and re-use it. With our network database [that ` get_openpype_global_settings` query alone](https://github.com/pypeclub/OpenPype/blob/1964e30246480bd33f4ebf9464130bba7bc14416/igniter/tools.py#L131-L161) takes 2+ seconds. So every time we avoid calling that would already …

Global: Optimize OpenPype startup

---

openpype/tools/mayalookassigner/models.py
openpype/tools/mayalookassigner/vray_proxies.py
openpype/tools/mayalookassigner/widgets.py

Some imports from avalon are invalid now when code was moved to OpenPype.
- changed import of maya lib function to be imported from openpype maya
- changed import of tools models to be imported from openpype
1. Try look manager functions in Maya

LookAssigner: Fix imports after moving code to OpenPype repository

---

openpype/tools/pyblish_pype/control.py
openpype/tools/pyblish_pype/settings.py
openpype/tools/pyblish_pype/window.py

There was an issue with the recent speed ups for pyblish with UI not drawing correctly.
- This now defaults to having "animations" disabled with `OPENPYPE_PYBLISH_ANIMATED` in settings. With the small timeout that was introduced recently with #2464 which sped up the publishing by tons it did mean animations didn't really visually show anyway. So disabling them doesn't make much of a difference, except for that the UI correctly updates to the latest state.
- There was some odd "on", "off', "on", "fade out" steps on the Log text bottom left of the UI. Not sure why, but that definitely didn't look good with the shorter intervals. Just having it "on", stay around for a while, and "fade out" looks much smoother and also avoids the text being drawn only half as if it's still updating the …

Pyblish Pype: Improve UI updates during processing

---

openpype/hosts/blender/api/ops.py
openpype/hosts/flame/api/menu.py
openpype/hosts/fusion/api/menu.py
openpype/hosts/hiero/api/menu.py
openpype/hosts/houdini/startup/MainMenuCommon.xml
openpype/hosts/nuke/api/pipeline.py
openpype/hosts/resolve/api/menu.py

Some hosts were missing Library loader menu item
This will allow to use Library loader across most of supported DCC
Triple dot stile `Library...` was unified to keep one style only without space between word
1. open your host
2. see there is available `Library...` under `Manage...`
3. It should open Library Loader
4. Also check the triple dots are not having space between word

Multiple hosts: unify menu style across hosts

---

openpype/hosts/nuke/plugins/create/create_write_prerender.py
openpype/modules/default_modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schema_project_nuke.json

Adding re-viewable option to prerender instance.
This will allow to publish reviewable components to Ftrack for example.
1. make sure the settings `project_settings/nuke/create/CreateWritePrerender/reviewable` is set to ON
2. make sure there are no project overrides on `project_settings/ftrack/publish/CollectFtrackFamily/profiles/6/families/2` and `prerender` family is available there
3. also make sure `project_settings/ftrack/publish/IntegrateFtrackInstance/family_mapping` is not having project overides and `prerender` key is available in mappings.
4. open your nuke testing workfile and create a prerender. 
5. review toggle should be set on and set for example some frame range constrain in rendering attribures on the prerender node.
6. publish and notice new version in ftrack with the …

Nuke: prerender with review knob

---

openpype/settings/handlers.py

Querying of studio project anatomy is not using right key to get data document.
- fix keys which are used to get studio anatomy settings
1. Change and save values in studio default project anatomy
2. Restart process and look if the values are loaded

Settings: Studio Project anatomy is queried using right keys

---

openpype/tools/settings/local_settings/apps_widget.py
openpype/tools/settings/local_settings/window.py

Additional applications break local settings UI because does not handle properly labels of dynamic entities.
- fix how labels are defined in local settings
1. Add new additional application to system settings (with variant)
2. Open local settings which should work and containt the application

Local Settings: Additional applications don't break UI

---

openpype/plugins/publish/collect_scene_loaded_versions.py

Plugin `CollectSceneLoadedVersions` expect that object returned using `ls` will return dictionary with key `objectName` which is available only in few hosts and is not required (and used). Was found out in TVPaint where reference was loaded.
- do not store and use `objectName`

General: Don't use 'objectName' from loaded references

---

openpype/hosts/tvpaint/api/pipeline.py

Fill `objectName` when calling `ls` in TVPaint.
TVPaint does not match container schema and does not return `objectName` key in returned container discovered during quick fix https://github.com/pypeclub/OpenPype/pull/2715 .
- function `ls` in tvpaint fills `objectName` with joined `members`

TVPaint: Set objectName with members

---

openpype/tools/project_manager/project_manager/window.py

The Project manager had the add task, add asset and save button when just launched and no project was active. This was confusing as was [reported on dicord](https://discord.com/channels/517362899170230292/563751989075378201/943059891969482772).
**Before**:
This PR disables the buttons until you're in a project.
**After**:
1. open project manager
2. confirm it still works as intended

Project Manager: Disable add task, add asset and save button when not in a project

---

openpype/hosts/flame/api/pipeline.py
openpype/hosts/fusion/api/pipeline.py
openpype/hosts/hiero/api/pipeline.py
openpype/hosts/houdini/api/pipeline.py
openpype/hosts/maya/api/pipeline.py
openpype/hosts/nuke/api/pipeline.py
openpype/hosts/resolve/api/pipeline.py

This removes the Avalon data being set for `familiesStateToggled` and `familiesStateDefault` from the `install()` logic for hosts. 
Specifically:
- `avalon.api.data["familiesStateToggled"]`
- `avalon.api.data["familiesStateDefault"]` 
This can be removed since the code does nothing within OpenPype due to overriding this behavior with the admin settings with `project_settings/global/tools/loader/family_filter_profiles`
Even though it currently did nothing within OpenPype - would we like to save default settings with OpenPype that match what this code did originally. The [current OpenPype default settings define **no** filtering whatsoever](https://github.com/pypeclub/OpenPype/blob/3d1ad1258161e2bba15746b1c0f41271b5755bcf/openpype/settings/defaults/project_settings/global.json#L327-L336). …

Loader: Remove default family states for hosts from code

---

openpype/hosts/houdini/plugins/create/create_arnold_ass.py

https://github.com/pypeclub/OpenPype/pull/2603 implemented creation of Arnold ass files for Houdini. However, upon merging the refactor of Houdini host to OpenPype was missed. This fixes that.

Houdini: Fix refactor of Houdini host move for CreateArnoldAss

---

openpype/lib/transcoding.py

Class `ElementTree` in xml parser don't know how to handle all escaped values which cause parse error.
Not sure what is proper fix. Propably would be to modify xml parser which is more complicated or define all possible espace values (e.g. from this [source](https://www.obkb.com/dcljr/charstxt.html)). It currently breaks loading of data for some exr.
- replace `&` in some unused xml ampresand characters with `&amp;` so `ElementTree` can parse it

General: Fix loading of unused chars in xml format

---

openpype/settings/defaults/system_settings/modules.json

This disables the Ftrack module by default for any new OpenPype users.
One of the first questions that tend to come up on Discord from new users is "How do I disable Ftrack?" or "I get this Ftrack error/warning. What to do?"
Since you first have to actually set an Ftrack Server URL for it to work for which you need to go into Admin Settings anyway it makes sense to just disable the module by default. If anyone wants to use Ftrack, they go to settings, enable the module **and** directly set the right Ftrack URL for their studio.
1. start a fresh openpype install/database
2. make sure things work as expected with the ftrack module disabled

Ftrack: Disable ftrack module by default

---

openpype/tools/libraryloader/app.py
openpype/tools/loader/app.py
openpype/tools/loader/lib.py
openpype/tools/loader/model.py
openpype/tools/loader/widgets.py
openpype/tools/utils/assets_widget.py

Loader errors when it is clicked on a group with merge group in it and underline colors in assets widget are not cleared.
Code does not expect that group can have children item that is another group but expects it has version document which cause not updating of version info widget on click. Also underline color are not cleared at all righ now.
- implemented missing part of clearing of underline colors in assets widget
- looping through group item expect that can have another group as children
- it is possible to show loaders on group items
1. Click on group with merged subsets in loader (multi asset selection with same subsets in same group is required)
2. Nothing should crash and should be possible to run loaders on the group
3. Underline colors should be cleared when clicked on …

Loader UI: Multiple asset selection and underline colors fixed

---

openpype/plugins/publish/extract_review.py
tests/README.md
tests/unit/openpype/plugins/publish/test_extract_review.py

Batch names containing `-af` or `-vf` were triggering failure of `ExtractReview` with 
```At least one output file must be specified```
There is logic which handles presence of audio/video filters in output arguments for ffmpeg to yank them into proper position. They were just simple presence filters which hit on an issue that output arguments for files coming from WP contain batch name with `-` characters. 
In specific cases batch name could contain `-af` which broke parsing and produces command like 
```
"C:\Program Files (x86)\OpenPype\vendor\bin\ffmpeg\windows\bin\ffmpeg" -apply_trc gamma22 -i W:\4c9c1954-d342-44f6-962d-af347c59c83b\be9709f0-b370-47c5-bbde-f973c48464bb\wsb_sh060_2d_rough_b_v001.mp4 -filter:a "W:\4c9c1954-d342-44f6-962d347c59c83b\be9709f0-b370-47c5-bbde-f973c48464bb\wsb …
```

WebPublisher: Fix for proper parsing of ffmpeg output arguments

---

openpype/lib/path_tools.py

When publishing in Maya with a workfile enabled the current workfile will increment its version - however upon doing so the filename will not preserve its subversion comment string that I user might have set.
The previous logic was to strip anything after the version label. This PR implements new logic that will preserve anything after the version string as it was.
**Before:**
```
my_file_v001_test.ma
my_file_v002.ma
```
**After**
```
my_file_v001_test.ma
my_file_v002_test.ma
```
If there are existing files in the folder, the logic is the same as before to skip existing files:
```
my_file_v001_test.ma # <--- version up on this file
my_file_v002.ma
my_file_v003_other.ma
my_file_v004_test.ma
my_file_v005.ma
my_file_v006_test.ma # <--- will version up to here - skipping any matches up to the …
```

Version Up: Preserve parts of filename after version number (like subversion) on version_up

---

openpype/modules/default_modules/deadline/plugins/publish/submit_maya_deadline.py

When submitting from Maya to deadline with Work file publish enabled Deadline will render using the published work file. The deadline batch and job name were set using that filename.
The problem however was that a user could have a work file name `shot_v001_{subversion}` like `shot_v001_testfile` as current workfile. On submitting to deadline the Deadline job would however read as batch name and job name `shot_v001` which made it harder for artists to trace back their render to their work file and track e.g. some test subversions they submitted.
This change should always force the usage of the original work file name for Job + Batch name.
1. test a deadline submission from workfile with subversion string with Use Published enabled + workfile publishing enabled as well
2. test same …

Maya: set Deadline job/batch name to original source workfile name instead of published workfile

---

openpype/hosts/flame/plugins/publish/validate_source_clip.py

Checking if source clip is present in reels.
Due to Flame API limits we have to have available source clips for timeline segments in Reels as they are then used for rendering rather then render all segments in timeline.

Flame: adding validator source clip

---

openpype/tools/workfiles/app.py

This is an implementation for #2626 where clicking on Save in the Work Files tool the subversion field will be prefilled with what is assumed to be the current 'comment' in the filename. 
It uses regex so is always prone to error I suppose. Howevr this case should be a pretty accurate detection against the filename template because all other "data" of the current context is formatted like also used for making a new save version- then only the {comment} and {version} are parsed against the current filename.
If the regex cannot detect any comment or current filename can't be matched against the template then nothing changes. Comment field will remain empty.
1. try and break the logic
2. test against some unique filename templates used by OP teams

Work Files: Preserve subversion comment of current filename by default

---

openpype/modules/default_modules/deadline/plugins/publish/submit_harmony_deadline.py

DL used `c:/Users/SUBMITTER` folder to render files, which didn't work on different machine than submitter.
Because work folder in Harmony is local, it must be replaced with folder where workfile will be finally published. In some cases naming convention of expected files didn't match correct value, which resulted in not updating the path.
This explicitly replaces dir name of expected file with staging folder where renders will be created on a DL machine.

Harmony: Rendering in Deadline didn't work in other machines than submitter

---

openpype/tools/loader/model.py
openpype/tools/loader/widgets.py

[This PR](https://github.com/pypeclub/OpenPype/pull/2731) broke right click of representation widget. It also used ItemRole which would not work with older python + PySide.
Don't use `ItemRole` in loader since it won't pass right object in older Python + PySide combination because proxy model will convert it to known python oject which cause lost of methods/attributes.
- use item id in representations widget
Site sync module must be enabled
1. Open loader in host
2. Right click on representation in representation widget

Loader UI: Fix right click in representation widget

---

openpype/hooks/pre_add_last_workfile_arg.py
openpype/hooks/pre_copy_template_workfile.py

Fix typo in name `afftereffects` -> `aftereffects` as came up in the comments [here](https://github.com/pypeclub/OpenPype/issues/2714#issuecomment-1044673592)
Note: this being a typo is an assumption on my end - so correct me if I'm wrong. :)
1. test whether open last workfile on launch worked before (I assume it didn't) and whether it works now. 
2. test whether `pre_copy_template_workfile` does what it was intended to do for After Effects

After Effects: Fix typo in name `afftereffects` -> `aftereffects`

---

openpype/plugins/publish/integrate_new.py

Texture batch publishing renamed texture udim indexes like they were image sequence indexes. This fixes that, leaving udim indexes untouched.

Avoid renaming udim indexes

---

openpype/hosts/houdini/api/lib.py
openpype/hosts/houdini/api/pipeline.py
openpype/hosts/houdini/startup/MainMenuCommon.xml

Implement **Reset Frame Range** for Houdini as per issue #2740 
- Adds menu entry that allows user to reset at any time
- On Houdini open or new scene it will now default to asset frame range.
It seems that whenever I do new scene the frame range is set correctly, but the start frame just doesn't want to go to the right start frame. It stays at 1 in the playbar. On Houdini launch however it seems fine, also with clicking the entry in the menu bar it also seems fine.
1. launch houdini, check whether frame range is correct
2. click CTRL+N (new scene), check whether frame range is correct
2. set your frame range incorrectly, click _reset frame range_ in OpenPype menu, check whether frame range is correct

Houdini: Implement Reset Frame Range

---

openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py
openpype/modules/slack/plugins/publish/collect_slack_family.py
openpype/settings/defaults/project_settings/slack.json
openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
website/docs/module_slack.md

Subset name filtering could be used to limit notification to Slack only for specific AOVs
1. configure subset name in `project_settings/slack/publish/CollectSlackFamilies/profiles`
2. run publish

Slack: Added regex for filtering on subset names

---

openpype/tools/workfiles/app.py

This makes the save prompt messagebox an actual child to the parent Qt UI element. 
This fixes the save prompt appearing behind the workfiles UI in Fusion.
Setting the windowFlags without the original messagebox.windowFlags() was the culprit as to why the messagebox previously wouldn't show when parented. Likely because then it's missing the Dialog window flag and thus would try to embed itself into the parent UI, which you then cannot exec()
(cherry picked from commit 290e2b601d0e20f4aaba356d4f053bf733de406b)
1. Test whether save prompt (when current scene has modifications and you are **opening** a file through Work Files) works as expected
2. Please test Blender integration, since original code mentioned "crashes" in Blender. ⚠️ 
I tested in Fusion 17 and Maya 2020 - those worked fine. …

Work Files: Fix parenting of save prompt QMessageBox

---

openpype/settings/defaults/system_settings/applications.json

Default value of flame settings contains invalid character `.`.
- changed flame name from `"2021.1"` to `"2021_1"`

Flame: Fix version string in default settings

---

openpype/lib/terminal.py

If I'm not mistaken the logic for `OPENPYPE_LOG_NO_COLORS` was incorrectly setting `use_colors` to True when `OPENPYPE_LOG_NO_COLORS` was set to True.
I believe this would fix that - and thus would avoid this printed output when the value is enabled for hosts that don't support `blessed`:
> Module `blessed` failed on import or terminal creation. Pype terminal won't use colors.
1. Make sure I'm not misreading the logic. 😄 
2. Test it for hosts that have `OPENPYPE_LOG_NO_COLORS` set.

Fix `OPENPYPE_LOG_NO_COLORS` being True actually resulting in `use_colors` being False

---

openpype/tools/pyblish_pype/app.py
openpype/tools/pyblish_pype/control.py
openpype/tools/pyblish_pype/window.py

Draft implementation for #2786 where the typed comment is preserved on reset.
Of course this has the side effect that if you were to keep the pyblish window open after publishing, go into another asset, then reset that your old comment would still be there. Not sure if that'd be an issue for anyone? If so, we might want to just "clear" the comment after a full publish. (e.g. Publish finished without errors)?
Not sure if this is the cleanest/best implementation. Let me know if you feel there's something off with this approach.
1. start pyblish, type a comment, reset. Your comment should be preserved
2. ensure the actual pyblish plug-ins are picking up the preserved comment on the publish

Pyblish Pype: Preserve comment on reset

---

openpype/hooks/pre_global_host_data.py
openpype/lib/__init__.py
openpype/lib/applications.py

Other applications don't have set context environments.
- set context environments on non host application start
- set `AVALON_APP` only is application has host implementation
1. Add custom applications in system settings (set executable to app where you can check environments)
2. Add the application to some project
3. Run the application through launcher
4. Check if environments contain `AVALON_PROJECT` `AVALON_ASSET` and `AVALON_TASK`

General: Set context environments for non host applications

---

openpype/tools/settings/settings/categories.py
openpype/tools/settings/settings/search_dialog.py

Search in settings is not case sensitive.
Case sensitivity is not welcommed as searching of `jpeg` won't find `JPEG`.
- regex is case insensitive
- fixed filter text change timer to be singleshot
- fixed issue with missing entity on reset which can happen if schema is invalid or there was an issue with creation
2. Open search dialog (CTRL + f)
3. Find something with wrong case sensitivity

Settings UI: Search case sensitivity

---

openpype/hosts/houdini/api/__init__.py
openpype/hosts/houdini/api/lib.py

Similar to what #2709 does for Maya this tries to remove unused code from the Houdini lib.
---
Houdini also has `set_id` and `get_id` functions similar to Maya that, as far as I know, are unused outside the fact they do seem to "generate" on save callback. Are those used anywhere? Do we ever intend to use them? If not, we might want to drop that logic too. The issue #2723 might shed more light on that but guessing based on how Houdini works the current implemenation of setting the ids isn't that useful anyway.
Thoughts?
1. launch houdini, make sure things work as expected.

Houdini: Remove unused code

---

openpype/widgets/color_widgets/color_inputs.py
openpype/widgets/color_widgets/color_triangle.py

Smaller tweaks of color dialog.
- alpha slider handler never fully goes to right side and sometimes does not draw tiled checker right way on hover
- thickness of circles in triangle widget are too thick in some cases
- fixed alpha slider 
- thickness of circles is calculated using `ceil` instead of `floor`
1. Try show color dialog and validate changes (e.g. `project_settings/global/publish/ExtractReview/profiles/0/outputs/h264/bg_color`)

General: Color dialog UI fixes

---

openpype/settings/handlers.py
openpype/tools/settings/settings/base.py

Settings in some cases expect that a versioned document already exists and does not handle it.
- Make sure that function returning versioned doc makes sure that result is dictionary and not None
- Side change: Replaced `_Callback` with `functools.partial` ( [related discussion](https://github.com/pypeclub/OpenPype/pull/2820#discussion_r816644392) )
1. On fresh mongo start OpenPype with specified version that is not build version - start should not crash

Settings: Missing document with OP versions may break start of OpenPype

---

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py

DL with enabled concurrent tasks fails with an error of nonexistent json. It probably gets deleted by different task.
1. enable concurrent tasks in DL
2. publish something that triggers multiple tasks in DL

Deadline: more detailed temp file name for environment json

---

openpype/lib/avalon_context.py

Build workfile was not returning presets from settings
This issue was effecting all hosts supporting Build workfile feature.

General: Host name was formed from obsolete code

---

openpype/hosts/blender/api/pipeline.py
openpype/hosts/harmony/api/lib.py
openpype/hosts/maya/api/commands.py
openpype/hosts/maya/api/menu.py
openpype/tools/mayalookassigner/widgets.py
openpype/tools/sceneinventory/model.py
openpype/tools/sceneinventory/view.py
openpype/tools/standalonepublish/publish.py
openpype/tools/utils/__init__.py
openpype/tools/utils/host_tools.py
openpype/tools/workfiles/model.py

Planned movement of code requires to cleanup code in openpype first. One change is that 
Changed imports to not use lib functions and models from `avalon.tools` but from `openpype.tools.utils`.
- changed imports
- moved pyblish gui discover logic into openpype
Nothing should change. Affected places:
- Standalone publishing should show publish tool
- Scene inventory should display versions correctly
- Maya should have pyblish icon in menu
- mayalookassigner should work before
- workfiles tool should work as before

Tools: Don't use avalon tools code

---

openpype/hosts/nuke/api/lib.py

Templates fill in nuke is using deprecated or complicated way how to fill `"app"` key for templates formatting.
Deprecated way is using `which_app` that can't work because we dropped .toml files since OP3. Complicated way is getting host name from application full name which can work but using `AVALON_APP` is much simpler.
- use `AVALON_APP` to fill `"app"` key for templates formatting in nuke lib functions
1. Add `{app}` to some template used in nuke
2. Create write node which should fill `{app}` with `nuke`

Nuke: Use AVALON_APP to get value for "app" key

---

openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
openpype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
openpype/modules/ftrack/lib/__init__.py
openpype/modules/ftrack/lib/avalon_sync.py
openpype/modules/ftrack/lib/constants.py

2 decimal places of fps may not be enough for some productions but ftrack numeric custom attributes have limitations into 2 decimal places.
Added option to store fps as string in ftrack custom attributes. The value can be set with multiple ways.
```
"1000"
"1000.05"
"1000,05"
",05"
".05"
"1000,"
"1000."
"1000/1000"
"1000.05/1000"
"1000/1000.05"
"1000,05/1000"
"1000/1000,05"
"1000.05/1000.05"
"1000,05/1000,05"
"1000,05/1000.05"
```
The FPS custom attribute can still be numeric so this feature is optional.
- added function which converts fps string into float
- sync to avalon is using the function to convert fps value
- custom attribute key must be available in `FPS_KEYS` variable
- right now the variable containts `"fps"` and `"fps_string"` (for development and testing purposes)
- create …

Ftrack: Can sync fps as string

---

openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py

Previously only specific keys (`channel, subset, color_space, shader` were used for template formatting for subsets for texture and workfiles, this allows use any configured group name
1. configure `project_settings/standalonepublisher/publish/CollectTextures` and incorporate there group name outside of previously hard-coded values (see higher), for example `material`
3. use Standalone Publisher and publish textures matching configured format

StandalonePublisher: use dynamic groups in subset names

---

openpype/plugins/publish/extract_jpeg_exr.py

This is fixing an issue where cryptomattes were still used for generation review videos even if they shouldn't. This then caused crash with ffmpeg during publishing because it cannot handle data stored in exrs.
---
Publish render from Maya with cryptomattes enabled in any AOV.
🗒️ This is really just quick fix and proper solution is needed. Currently we are looking for `crypto` string in subset name but this is too broad definition.

Maya: Stop creation of reviews for Cryptomattes

---

openpype/hosts/fusion/scripts/fusion_switch_shot.py
openpype/hosts/fusion/utility_scripts/switch_ui.py
openpype/lib/avalon_context.py
openpype/scripts/fusion_switch_shot.py
openpype/tools/assetcreator/app.py
openpype/tools/workfiles/app.py

Context change related functions moved from avalon into openpype.
These functions recalculate session changes and change of workdir used primarily in workfiles tool.
- moved functions into `openpype/lib/avalon_context.py` - at this moment there is not a better place
- changed how fusion is getting wordir path
- use functions in workfiles tool
1. Workfiles tool should work as before
- changes context on save
- calculate proper workdir and uses right template
2. Fusion scripts handling workdir should work - not sure if it did work before?

General: Move change context functions

---

openpype/pipeline/create/context.py

Class `CreatedInstance` will always add `"version"` key into data but it does not make sense and breaks publishing.
- remove autoadded `"version"` key in instance data

New Publisher: Don't set instance version if is not available

---

openpype/hosts/blender/plugins/publish/extract_camera.py

Fixed parameters for the export of FBX camera from Blender.
Blender changed the FBX exporter plugin with version 2.93. The camera extractor has been updated to include some parameters to make the camera working as before these changes.

Blender: Fixed parameters for FBX export of the camera

---

openpype/hosts/maya/plugins/publish/extract_look.py
openpype/lib/__init__.py
openpype/lib/applications.py
openpype/lib/execute.py
openpype/lib/vendor_bin_utils.py

We're using `find_executable` from distutils but it seems that they'll get deprecated soon and may not work as expected also some older hosts have issues with using distutils too.
Added custom `find_executable` which should return full path to an executable file.
- implemented `find_executable` in `openpype/lib`
- use the function in places where it is needed
- `maketx` in extract look does not add `".exe"`
- try run applications
- oiio and ffmpeg functions returning path should work and return full path to file

General: Custom function for find executable

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
openpype/lib/vendor_bin_utils.py
openpype/scripts/otio_burnin.py

Wrong value 0-1 was hardcoded, now `ffprobe` is used to try get frame count from a file
In the case of any weird video format, fallback to values stored in DB (Ftrack) is used.
1. Publish any video file as a 'render' family via WebPublisher
2. Compare number of frames in the file and in published record (shoul be visible in Loader or when Loaded to Nuke)

WebPublisher: Fix wrong number of frames for video file

---

openpype/modules/ftrack/plugins/publish/collect_username.py

Burnin name, version.author and representation.username is set to same value
1. Publish something with WP
2. Check burnin left bottom corner
3. Check version author value in Loader

WebPublisher: Fix username stored in DB

---

openpype/style/style.css
openpype/tools/traypublisher/window.py

It was not clear what to do on tray publisher open.
Make widget showing to choose a project more clear for artist with adding background under all widgets that are importatnt for the selection and make the selection widget wider.
1. Open TrayPublisher and check look

TrayPublisher: Choose project widget is more clear

---

openpype/modules/base.py

Calling `getattr` on dynamic modules in openpype (`openpype_modules` and `openpype_interfaces`) does not behave as expected because is raising `ImportError` instead of `AttributeError`.
- dynamic module has `__name__` attribute (where is stored it's name)
- `__getattr__` method raises `AttributeError` instead of `ImportError`
Run script in python interpreter console
```
import openpype_modules
getattr(openpype_modules, "missing_module", None)
```

General: Fix getattr clalback on dynamic modules

---

openpype/hosts/testhost/plugins/publish/collect_context.py
openpype/hosts/testhost/plugins/publish/collect_instance_1.py
openpype/pipeline/create/context.py
openpype/plugins/publish/integrate_new.py
openpype/tools/publisher/control.py
openpype/tools/publisher/widgets/create_dialog.py
openpype/tools/publisher/widgets/list_view_widgets.py
openpype/tools/publisher/widgets/tasks_widget.py
openpype/tools/publisher/widgets/widgets.py

Change of task on publishing instance does not fix invalid instance and it is not possible to have instance without set task which may be needed in some cases of publishing.
- changed `Submit` label to `Confirm`
- instance does not need to have set task but can have empty task (stored as `None`)
- change of invalid task on existing instance is propagated to instance properly
- invalid task doesn't mean invalid asset
- it is captured `TaskNotSetError` in both creator dialog and publisher
- publish plugin `IntegrateNew` does not require task in anatomy data
- change of checkbox states using keys (space, backspace, enter) will also trigger change state of group checkbox
- tasks in combobox are sorted
- plugin is added to report after checks if should stop/pause publishing
Try change subset …

NewPublisher: Changing task on publishing instance

---

openpype/lib/path_tools.py

[This PR](https://github.com/pypeclub/OpenPype/pull/2848) implemented `create_hard_link` which has special condition for windows but when is successfull it continues right into raise of exception.
- added `return` for windows specific condition
1. Run `create_hard_link` on windows in host with Python 2

General: Fix hardlink for windows

---

openpype/hosts/nuke/plugins/publish/precollect_instances.py
openpype/hosts/nuke/plugins/publish/validate_write_legacy.py

Precollect checks Nuke groups for having "write" in families. Publishing Group as OP Gizmo fails.
1. create group of nodes in Nuke
2. Create OP Gizmo from selected group
3. Publish

Nuke: gizmo precollect fix

---

openpype/hosts/nuke/plugins/publish/validate_write_legacy.py

Fix Still Image publishing
Publishing StillImage from Nuke fails on family check. 
1. Go to Nuke
2. Create StillImageFrame, set it to local render
3. Publish
4. Check that publish didn't fail on "Not correct family"

Nuke: Fix family test in validate_write_legacy to work with stillImage

---

openpype/lib/transcoding.py
openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
openpype/settings/defaults/project_settings/deadline.json
openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json

Deadline tile assembler plugin is called `OpenPypeTileAssembler` but in settings is available only `oiio` so the jobs are crashing.
- changed `oiio` name to `OpenPypeTileAssembler`
- fix getting info about input files
It seems that the tile assembler is compositing tiles vertically in oposite order.
1. Set in settings to use `Open Image IO` for tiles (`project_settings/deadline/publish/MayaSubmitDeadline/tile_assembler_plugin`)
2. Submit to deadline tile job
3. Job should load

Deadline: Fix plugin name for tile assemble

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py

Duration was saved into frameEnd which resulted in one too may frame issue
1. Publish video file with WP
2. Check published file duration and frame range in Loader

WebPublisher: Video file was published with one too many frame

---

openpype/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json

Add filtering of output definitions in `ExtractReview` plugin by subset name using regex strings.
- added settings for subset names in additional filtering of `ExtractReview`
- added filtering logic in `ExtractReview` using the settings
1. Add subset name filter
2. Run publishing matching or not matching the regex

General: Subset name filtering in ExtractReview outpus

---

openpype/hosts/harmony/plugins/publish/collect_farm_render.py
openpype/hosts/maya/plugins/publish/collect_render.py
openpype/hosts/maya/plugins/publish/collect_vrayscene.py
openpype/lib/__init__.py
openpype/lib/abstract_collect_render.py
openpype/lib/config.py
openpype/plugins/publish/collect_time.py

During [this PR](https://github.com/pypeclub/avalon-core/pull/425) was removed function `time` which is used at few places.
- added function `get_formatted_current_time` in openpype lib
- replaced usage of `avalon.lib.time` with the function 
1. Try publishing with latest avalon main

General: Missing time function

---

openpype/hosts/aftereffects/api/launch_logic.py
openpype/hosts/aftereffects/api/ws_stub.py
openpype/hosts/photoshop/api/launch_logic.py
openpype/hosts/photoshop/api/ws_stub.py
openpype/tools/adobe_webserver/app.py
openpype/tools/adobe_webserver/readme.txt

Part of incorporating of avalon-core repo into openpype.
Webserver moved to `adobe_webserver` as both AE and PS should use same logic.
0. Requires https://github.com/pypeclub/avalon-core/pull/428
1. Start AE
2. Menu should work (open Workfiles tool or any other)

Refactor: move webserver tool to openpype

---

openpype/__init__.py

Import of `LegacyCreator` cause circular import in `openpype/__init__.py`.
- moved import to `install` function
1. OpenPype should install in hosts (Blender had an issue)

General: Avoid circular import

---

openpype/lib/avalon_context.py

There was one forgotten place where `Creator` plugin is not replaced with `LegacyCreator` not moved in [this PR](https://github.com/pypeclub/OpenPype/pull/2854).
- replace `avalon.api.Creator` with `LegacyCreator` in `get_creator_by_name`
1. Call `get_creator_by_name` in any host

General: Remove forgotten use of avalon Creator

---

openpype/hosts/harmony/api/TB_sceneOpened.js

Creator failed with `'str' object does not support item assignment`
Missed replacement of old avalon emit to new callback method.
1. Open Harmony
2. Use Create tool

Harmony - fixed creator issue

---

openpype/pipeline/__init__.py
openpype/tools/sceneinventory/window.py

Function `get_repres_contexts` is not available in `openpype.pipeline` so switch dialog crashes on initialization.
- added `get_repres_contexts` function to `openpype.pipeline.__init__.py`
- fixed tooltips of refresh and update to latest buttons
1. Open scene inventory tool
2. Try switch version
3. Validate tooltips of buttons

SceneInventory: Fix import of load function

---

openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py
openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
openpype/lib/__init__.py
openpype/lib/transcoding.py
openpype/lib/vendor_bin_utils.py
openpype/plugins/publish/extract_review.py
openpype/plugins/publish/extract_review_slate.py
openpype/scripts/otio_burnin.py
openpype/tests/test_lib_restructuralization.py

Plugin `ExtractReviewSlate` don't know how to reuse data from ffprobe to recreate almost same output as needed.
But we have a base of that logic in burnins so it is a good idea to move it to transcoding functions and share it across code. Also some functions from vendor lib can be moved to transcoding too.
- function `ffprobe_streams` is split into 2 function `get_ffprobe_data` and `get_ffprobe_streams` and is moved to `transcoding`
- changed related code to use this function
- moved function related to "recreate as close as possible" stream using ffmpeg from burnins into `transcoding`
- changed related code to use it
- renamed function `get_fps` into `convert_ffprobe_fps_value` and moved to `transcoding`
1. Burnins should work as they did
2. ExtractReviewSlate should be able to create …

Nuke: ExtractReviewSlate can handle more codes and profiles

---

openpype/tools/pyblish_pype/control.py

This fixes #2834 
Ensures "Extraction" and "Integrating" is actually shown correctly whilst those orders are currently processing. Previously it kept saying "Validating" during those steps.
1. publish with a slow extractor and integrator
2. the bottom left labels on the Pyblish UI should always state the correct current 'state'

Pyblish Pype - ensure current state is correct when entering new group order

---

openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json

Adding new ocio aces config version
1. In imageio nuke on your project set aces_1.2 ocio config version
2. open Nuke > 13.1 on your project
3. see the ocio config was set to the version

nuke: imageio adding ocio config version 1.2

---

openpype/pipeline/load/utils.py

Get representation path used `roots_obj` from Anatomy instead of `roots`.
- use `roots` attribute from Anatomy object instead of `roots_obj` when different project roots should be used
1. Try copy path from loader launched from tray

General: Fix use of Anatomy roots

---

openpype/cli.py
openpype/lib/log.py

Env variable `OPENPYPE_DEBUG` must be set to 2 or higher number to enable debugging which is unexpected for most of cases.
- `OPENPYPE_DEBUG` can be set to any number higher than `0` to start emit debug log
- all changes of `OPENPYPE_DEBUG` setting the value has been changed to set it to `0`
1. Run any command with env variable `OPENPYPE_DEBUG` set to `"1"`

General: Change how OPENPYPE_DEBUG value is handled

---

openpype/settings/entities/base_entity.py
openpype/settings/entities/schemas/README.md
openpype/tools/settings/settings/base.py

Add ability to set `"tooltip"` in schemas which is then shown in UI on hover.
- each entity may have `"tooltip"` in schemas
- each widget has set tooltip if it's entity has set it
1. Set tooltip on entity in schema
2. Open settings UI
3. Hover over the entity's widget

Settings UI: Add simple tooltips for settings entities

---

openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
openpype/tools/workfiles/app.py

Calculate work filename for tasks and fill the value into custom attribute in ftrack.
The workfile name is filled with version `1`, extension is kept as `{ext}` and possible host name is kept as `{app}`. The action is disabled by default. It is required to define which custom attribute should be filled. The custom attribute must be a `text` type attribute for `Task` entity type.
- added ftrack acion into user actions that will fill workfile string into custom attribute
- workfiles tool is using `get_workdir_data` from `openpype.lib`
- maybe the action should be server action?
1. Create any text custom attribute for Task entity type (e.g. with key `workfile`)
2. Enable the action is project settings and set the custom attribute key to `workfile`
3. Run the action on any project (`OpenPype …

Ftrack: Fill workfile in custom attribute

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py

Deadling jobs don't use `--headless` argument at all when running OpenPype and `OPENPYPE_HEADLESS` may not get to publish job.
- added `--headless` when running OpenPype executable on deadline
- this change requires update of deadline repository plugin - see [Admin Docs -> Deadline Module](https://openpype.io/docs/module_deadline/)
1. Submit publish job to deadline
2. Pause the job before publishing
3. Add newer version of OpenPype into version repository so opening of OpenPype requires update
4. Continue with publish job
5. Publishing should success

Deadline: Add headless argument

---

tools/ci_tools.py

This PR changes the logic of CI action that determines the next OpenPype version with each nightly and production release. 
Untill now, any PR that was labeled with `type: Feature` triggered upping of the minor version, however because of that it became quite hard to tell when we need to re-deploy re-built executables, and when it's enough to use automated system with zips. 
With this change we're making this a lot more transparent. 
If a pull request requires a new build of the binaries, due to changes in the igniter, pyproject.toml or similar major changes, it is the responsibility of the Author and the Reviewer to make sure the PR is labeled as `Bump Minor`.
CI will pick this up and make sure that minor version is updated next time this PR makes it to a release. The main upside being …

CI: change the version bump logic

---

openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py
openpype/hosts/tvpaint/plugins/load/load_workfile.py
openpype/lib/__init__.py
openpype/lib/applications.py
openpype/lib/avalon_context.py
openpype/lib/delivery.py
openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
openpype/pipeline/load/utils.py
openpype/plugins/publish/integrate_new.py
openpype/tools/workfiles/app.py

Move functions from avalon that are related to calculation of last workfile path and optional template formatting.
Usage of `format_template_with_optional_keys` function is replaced with `StringTemplate`.
Functions `last_workfile_with_version` renamed to `get_last_workfile_with_version` and `last_workfile` renamed to `get_last_workfile` and both moved to `openpype/lib/avalon_context.py`.
1. Workfiles tool should be able to find last workfile version and use next available (when save as is clicked)
2. Last workfile should be launched on host start (if the feature is enabled!)
3. Modified string formatting should work as did
Related to PR https://github.com/pypeclub/avalon-core/pull/434

General: Move formatting and workfile functions

---

openpype/hosts/hiero/api/events.py

Function `register_event_callback` is imported from `openpype.hosts.hiero.api.lib` instead of `openpype.lib`.
- changed import to point into `openpype.lib`
1. Open hiero/nukestudio from OpenPype
2. Implementation should work

Hiero: Fix import of 'register_event_callback'

---

openpype/lib/log.py

It seems that crashed log emit in `openpype_gui` (windows) can sometimes raise an OSError on stream write which fallbacks to exception handling that tried do the same using `print` so crashes again.
- don't print record if OSError is raised during writing
It would be good to find out real reason. This was discovered in Ftrack action server subprocess.
1. Run tray using `openpype_gui.exe` with enabled Ftrack module
2. Run `Prepare Project` on any project
3. A form with inputs should be shown

General: Don't print log record on OSError

---

openpype/tools/settings/settings/wrapper_widgets.py

When `collapsible-wrap` has set `collapsed` in schemas it does in UI the opposite of what it should.
- fix usage of collapsed value in CollapsibleWrapper
1. Add `collapsible-wrap` item into settings schema and set it's `collapsed` to `True`
2. Open settings UI where should the item be collapsed

Settings UI: Collapsed of collapsible wrapper works as expected

---

openpype/pipeline/actions.py
openpype/tools/sceneinventory/switch_dialog.py

Remained usage of `loaders_from_repre_context` from avalon repository cause crashes in scene inventory tool. Bug since [this PR](https://github.com/pypeclub/OpenPype/pull/2886).
Fixed import of function used from `avalon.pipeline`.
1. Open SceneInventory tool
2. Call switch asset on any referenced item and dialog shoud show

SceneInventory: Fix imports in UI

---

openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py

Code was too complex to read
1. configure `project_settings/nuke/publish/ExtractReviewDataMov/outputs` to have multiple presets with use of filters
2. open your testing nuke script
3. publish render write node

Nuke: improving readability

---

openpype/modules/log_viewer/tray/app.py
openpype/modules/log_viewer/tray/widgets.py

Logs are refreshed on initialization of log viewer window which slows down tray application launch.
Refresh of logs is triggered on first show of the window instead of on initialization.
1. LogViewer module must be enabled
2. Start of tray should be a little bit faster
3. Log viewer should still show logs on showing the window

LogViewer: Don't refresh on initialization

---

openpype/settings/entities/schemas/projects_schema/schemas/schema_representation_tags.json

Allow skipping audio for reviews.
Some reviews can't have audio. This tag allows to flag reviews to be mute.
Ffmpeg can fail adding audio to files that cant' have any, like OpAtom MXFs
1. Add no-audio flag in extractReview profile
2. Publish shot with audio available (from Nuke)
3. Check that review is mute

Nuke: Add no-audio Tag

---

openpype/lib/avalon_context.py

Fixing data consistency
All anatomy data should have `short` used as key for task code.

General: anatomy data with correct task short key

---

openpype/hosts/maya/api/lib.py

This fixes support for Maya 2018
Older versions of Maya do not allow `set` type to be passed to Maya commands and will result in e.g. "RuntimeError: # Syntax error: unexpected end ( at position 4 while parsing"
E.g. error as [reported on discord](https://discord.com/channels/517362899170230292/563751989075378201/955419340826628157):
```
: set([u'Props_lookMain_01_RN'])
```
This fixes loaded version updating, shader assignments and more areas that relied on `get_container_members`. 
1. start maya versions
2. ensure updating versions of loaded content continues to work, and lookdev shader assignments still work

Maya: Do not pass `set` to maya commands (fixes support for older maya versions)

---

openpype/pipeline/__init__.py
openpype/pipeline/publish/__init__.py
openpype/pipeline/publish/publish_plugins.py

Optional plugins must be set to active/inactive in new publisher UI somehow. The way is to implement `get_attribute_definitions` in `OpenPypePyblishPluginMixin`.
Implemented `OptionalPyblishPluginMixin` which will check optional attribute and will care about attributes for the plugin. Publish plugin must inherit from the mixin to be able use it. Should be backwards compatible with current publisher.
1. Add plugin which inherit from `OptionalPyblishPluginMixin`
2. Make the validator optional
3. Open new publisher in context where the plugin should be visible and check publish attributes

NewPublisher: Prepared implementation of optional pyblish plugin

---

openpype/hosts/maya/plugins/create/create_review.py
openpype/hosts/maya/plugins/publish/extract_playblast.py

Transparency configuration was missing from `CreateReview`
1. Create camera in Maya scene and Create Review family
2. check created review group, there should be new item to select transparency
3. publish and check that selected transparency was applied

Maya - added transparency into review creator

---

openpype/settings/entities/base_entity.py
openpype/settings/entities/dict_conditional.py
openpype/settings/entities/dict_immutable_keys_entity.py
openpype/settings/entities/dict_mutable_keys_entity.py
openpype/settings/entities/input_entities.py
openpype/settings/entities/item_entities.py
openpype/settings/entities/list_entity.py

Conditional dictionary which has children with same key but different types does not cause warning logs when loading settings anymore.
Added option to not log invalid value type on loading of settings which is by default enabled but (currently only) dict-conditional may disable it if is updating values of children which may have different type which is not importatnt.
- added argument to `update_default_values`, `update_studio_values` and `update_project_values` which will define if invalid value type is logged out
- when this argument is passed and value has invalid type it is not logged out
- conditional dictionary changes the enabled logging based on enum value from the values
1. Run settings UI
2. Check logs in console if there are any warnings

Settings: Conditional dictionary avoid invalid logs

---

openpype/hosts/nuke/plugins/load/load_effects.py
openpype/hosts/nuke/plugins/load/load_effects_ip.py
openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
openpype/hosts/nuke/plugins/publish/validate_write_deadline_tab.py

`iteritems` is python2 function and python3 was crashing.

nuke: python3 compatibility issue with `iteritems`

---

openpype/settings/defaults/project_settings/slack.json

Previously added `review_upload_limit` was missing in Setting's default which resulted in labeling Slack collector in Settings having changes incorrectly.
1. Open Settings
2. Project without any configuration for `CollectSlackFamilies` shouldn't have highlighted section of `CollectSlackFamilies` blue.

Slack: Added default for review_upload_limit for Slack

---

openpype/settings/constants.py

Potential micro-optimization by changing `METADATA_KEYS` into an immutable set (`frozenset`) because the keys are often used for a `if x in METADATA_KEYS` look up.
1. test settings - in particular dict conditionals seem to use the keys

General: `METADATA_KEYS` constant as `frozenset` for optimal immutable lookup

---

openpype/hosts/traypublisher/plugins/create/create_workfile.py
openpype/hosts/traypublisher/plugins/publish/validate_workfile.py
openpype/modules/ftrack/lib/avalon_sync.py
openpype/modules/log_viewer/tray/app.py
openpype/tools/publisher/widgets/create_dialog.py
openpype/tools/utils/lib.py
openpype/widgets/attribute_defs/files_widget.py

Fix of few smaller issues.
Fixed import of attribute definitions in tray publisher plugin. Fixed typo of attribute `_first_show`. Log information about not find icon and also log that passed icon name is not exact match of used icon name (prefix from qtawesome was added). Changed `Name:` label to `Variant:` in creator dialog window.
- Tray publisher should show workfiles creator
- log viewer should not crash
- icons should be visible in tools
- creator dialog in new publisher should show `Variant:` instead of `Name:`

General: Smaller fixes and typos

---

openpype/lib/transcoding.py

Sequences now convert input into one output file so there are missing file and first frame contains last frame.
The bug is that output filepath uses filename of input without frame indexing (`%04d`) so oiio will output to same file. This was changed and filename is created like `tmp.%04d.exr`.
- add filename with frame indexing when converting sequence for ffmpeg
1. Run publish which produce sequence that must be converted for ffmpeg
2. Publish should finish successfully (or not crash due to missing frames)
Resolves https://github.com/pypeclub/OpenPype/issues/2957

General: OIIO conversion for ffmeg can handle sequences

---

openpype/lib/applications.py
openpype/settings/defaults/system_settings/tools.json
openpype/settings/entities/schemas/system_schema/schema_tools.json
openpype/settings/lib.py

Tools can be filtered for specific host or application.
Right now are all tools environments applied to all applications which may break then and it is not possible to have different versions for different versions of application. It was added a hosts and application variants filter for each tool variant. Both filters must be matched. Missing filters mean that the tool will be used at all cases. The filtering using host will probably be used in most of cases but for more granular filtering was also added a application variant filter.
This change require to change how tools are stored so a "hasckish" backwards compatible conversion in settings was added when studio settings overrides are loaded so old environment values are not lost. But changes are still showed in settings.
Application …

General: Tools with host filters

---

openpype/hosts/aftereffects/api/workio.py

Occured when no scene was opened and Workfile wanted to open existing workfile
1. open context where no workfile is existing
2. use Workfile tool to open exisiting workfile from different context

AEL: fix opening existing workfile if no scene opened

---

openpype/hosts/nuke/api/plugin.py
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json

Adding Read Raw bool attribute.
This way we can bake unmanaged color space into bake mov files. 
1. open your testing nuke workfile
2. create/modify output profile and activate `project_settings/nuke/publish/ExtractReviewDataMov/outputs/baking/read_raw` 
3. publish render instance with `review` on
4. check rendered review video and see the gamma is linear.

Nuke: ReviewDataMov Read RAW attribute

---

openpype/tools/settings/settings/widgets.py

Fix version input in settings which end in infinite loop of focus changes on some linux dist.
Some linux distributions cause that showing completer take focus from the text input which is then changed back to input and so on. It is forced to show completer inactive. Also was changed logic how completer is hidden by adding timer. On timer's callback is checked if line edit or completer have focus and will hide completer if both don't have it.
PreReq:
- be on centos machine
- have some versions in version repository
2. Click in System settings into `general/production_version`
3. Focus should be in version input but popup should show
4. Test the same on Windows
Resolves https://github.com/pypeclub/OpenPype/issues/2977

Settings UI: Fix version completer on linux

---

setup.py
tools/build.ps1
tools/build.sh

With updated [setuptools](https://github.com/pypa/setuptools) new behaviour emerged that is not backwards compatible,
introducing non-backwards compatible breaking changes.
Setting packages to an empty list will disable autodiscovery and should permit build to run as before.
Described here pypa/setuptools#3197

Fix: Disable setuptools auto discovery

---

openpype/hosts/photoshop/plugins/publish/validate_naming.py
openpype/settings/defaults/project_settings/photoshop.json

Validator Repair method used layer name as a subset name.
1. create multiple layers with broken names (layer name containing `/`, or `;` ...)
2. create for all of them instances (in single Creator, 'Use Selection')
3. use `Repair` action when `Validate Naming` fails
4. compare published file names format with unbroken layer names

PS: fix renaming subset incorrectly in PS

---

openpype/hosts/photoshop/plugins/publish/collect_review.py
openpype/hosts/photoshop/plugins/publish/collect_workfile.py

Use existing `get_subset_name` function to get subset name for workfile and review.
- prepare specific tempate for workfile in PS in `project_settings/global/tools/creator/subset_name_profiles`
- try to publish and compare name of published workfile with template
- (without this it was always `workfileMytaskname`)

Photoshop: Fix creation of subset names in PS review and workfile

---

openpype/hosts/tvpaint/plugins/publish/extract_convert_to_exr.py
openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
openpype/plugins/publish/collect_cleanup_keys.py
openpype/settings/defaults/project_settings/tvpaint.json
openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json

TVPaint extractor is creating PNG sequences but it may be better to store them as exr files.
Since the TVPaint extraction is based on compositing in python we can't extract EXRs directly from TVPaint. Extractor is using oiiotool to convert pngs into exr. Plugin is disabled by default. Has ability to choose output exr compression and if should replace input pngs or keep them. If pngs are replaced then their files are removed during cleanup.
Source [PR from Pype 2](https://github.com/pypeclub/OpenPype/pull/2048).
Right now there are hardcoded color conversions `--colorconvert sRGB linear`. Not sure if we should do it or if we should add some kind of settings for this? If yes, what kind of settings?
1. Enable the plugin in project settings
2. Publish from TVPaint

TVPaint: Extractor to convert PNG into EXR

---

openpype/lib/avalon_context.py

Newly created workfile contained 2 dots before extension

Fix - remove doubled dot in workfile created from template

---

openpype/hosts/photoshop/plugins/publish/collect_instances.py
openpype/hosts/photoshop/plugins/publish/extract_image.py
openpype/hosts/photoshop/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/photoshop.json
openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
website/docs/artist_hosts_photoshop.md

Publish creates flatten image with configurable subset name if no image instances present in workfile
This is special use case requested by customer making publish process easier for artist. It checks if no image instances are present AND `project_settings/photoshop/publish/CollectInstances/flatten_subset_template` is filled.
1. fill `project_settings/photoshop/publish/CollectInstances/flatten_subset_template` with template 
2. try to publish workfile without explicitly Creating image instances

Photoshop: create image without instance

---

openpype/hosts/nuke/plugins/publish/extract_review_data.py
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json

Added support for review without baking
Since someone can set workfow rendering to png with sRGB so screenspace already baked into image sequence, they can skip baking because only purpose of it is to bake screen space into reviewable files. 
1. go to settings on your project and disable `project_settings/nuke/publish/ExtractReviewDataMov`
2. go to settings on your project and enable `project_settings/nuke/publish/ExtractReviewData`
3. go to settings `project_anatomy/imageio/nuke/nodes/requiredNodes` and set `CreateWriteRender` to be png `file_type`, remove [`compression`, `cropped`], set `datatype` to "16 bit" and `colorspace` to "sRGB" or "Output - sRGB" (if you are in ACES)
4. Render locally, on farm, from rendered files
5. all should look the same and produce reviewable version on …

nuke: bypass baking

---

openpype/hosts/blender/__init__.py
openpype/hosts/hiero/__init__.py
openpype/hosts/houdini/__init__.py
openpype/hosts/maya/__init__.py
openpype/hosts/nuke/__init__.py

Function `add_implementation_envs` should not remove not existing paths because they may be not yet resolved environment value.
Resolving of environment variable values is finished after collection of all environments. Last step is that host implementation may modify environments value in `add_implementation_envs` function. But in some cases are also verifying existence of paths that may still have unfilled values of other environments. This should not happen at all, it is better to keep the invalid value then  remove it completely which cause confusion.
- host's implementation of `add_implementation_envs` does not remove not existing paths from env values
1. Hosts should still work
2. It should be possible to use env keys in variables that are modified in host implementation
Resolves …

Hosts: Remove path existence checks in 'add_implementation_envs'

---

pyproject.toml

Limiting Pyright in projects.toml
It is speeding up indexing of source files within project.
python language servers are usually looking into all source files within workspace or project and it was taking too long at indexing phase. 
It is tested only on vscode.

General: adding limitations for pyright

---

openpype/hosts/nuke/plugins/load/load_effects.py
openpype/hosts/nuke/plugins/load/load_effects_ip.py
openpype/hosts/nuke/plugins/load/load_gizmo_ip.py

Fixing unicode type detection in effect loaders
1. open testing nuke workfile in nuke12
2. Load Effect family subset to scene either as Input process or as nodes

Nuke: fixing unicode type detection in effect loaders

---

openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

No need to publish sequence with review if baked profiles are used. 
This was happenning due wild card regex match but since we are adding `bakingNukeScripts` atribute to instance data, it is quite clear we don't need to review also .exr image sequence.
We had also not very nice way of Ftrack asset naming in case multiple reviewable representations were processed. I had hopefully preserved backward compatibility for single reviewable, but it needs to be tested. The feature was made optional and can be activated in settings `project_settings/ftrack/publish/IntegrateFtrackInstance/nicer_asset_name`
Ideal test scenarios are following:
- activate `project_settings/ftrack/publish/IntegrateFtrackInstance/nicer_asset_name` on your project
- nuke single baking preset - ftrack component asset name …

Nuke: removing redundant Ftrack asset when farm publishing

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/plugins/publish/precollect_writes.py
openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/settings/defaults/project_settings/deadline.json
openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json

Adding support for `ConcurrentTask` Deadline Job attibute.
Some productions might want to use Deadline feature for concurrent tasks on one Worker. This will allow to either set this in settings for Nuke submission or even let user to decide how many concurrent task he wants to use on Rendering node Deadline Tab.
1. Make sure you are having Deadline Worker with at least some Concurrent task defined > Super user needs to be ON and RMB click on worker and go to Worker Settings/Concurrent Tasks. If zero is in it it will detect your maximum available threads and use it. 
2. Open Settings and save on your project override. To to `project_settings/deadline/publish/NukeSubmitDeadline/concurrent_tasks` and define it to _5_.
2. Open your favorite Nuke workfile.
3. Test 1 render publish with already …

Nuke: add concurrency attr to deadline job

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

Names were not correctly distributing
Previous PR https://github.com/pypeclub/OpenPype/pull/2996 was merged with broken logic and didn't distribute correctly extended names. 
1. Nuke Single baking preset with `project_settings/ftrack/publish/IntegrateFtrackInstance/keep_first_subset_name_for_review` ON should create ftrack asset name equal to `{subset_name}`
2. Nuke Single baking preset with `project_settings/ftrack/publish/IntegrateFtrackInstance/keep_first_subset_name_for_review` OFF should create ftrack asset name equal to `{subset_name}`
3. Nuke Multiple baking preset with `project_settings/ftrack/publish/IntegrateFtrackInstance/keep_first_subset_name_for_review` ON should create ftrack asset name equal to `{subset_name}_{repre_name}` but __first__ asset name should equal to …

Ftrack: multiple  reviewable componets

---

openpype/hosts/traypublisher/api/pipeline.py
openpype/hosts/traypublisher/plugins/publish/validate_workfile.py

Register of tray publisher creators does not work after [this PR](https://github.com/pypeclub/OpenPype/pull/2935).
Changed how creators are registered in traypublisher host. And added few more information into validator exceptions.
1. Run tray publisher (enabled experimental **New Standalone Publisher** in local settings first)
2. Workfiles creator should be visible

Tray publisher: Fixes after code movement

---

openpype/hosts/maya/api/pipeline.py

Maya implementation imported `find_submodule` from avalon which is no longer available.
Removed the `find_submodule` import and it's usage which looked into avalon's config (OpenPype) for specific function name, which is not used and needed.
1. Maya should start and install with latest `main` of avalon-core repository

Maya: Remove missing import

---

openpype/settings/defaults/project_settings/global.json
tests/lib/assert_classes.py

Added default template for subset workfile to '{family}{Task}'. (eg. for TestTask subset would be `workfileTestTask`)
Standard method `get_subset_name` might not be used for workfiles on all places (it should), but it seems when it will be used, 
it should translate into workfileTaskname format.

General: default workfile subset name for workfile

---

openpype/modules/python_console_interpreter/window/widgets.py

Use stored splitter sizes as relative ratio rather then absolute size.
Restored sizes are now set explicitly on initialization but the size of window is not yet known so the bottom part is squeezed and when sizes would be set as absolute size of first show it may cause issues when machine has more displays with different resolution. The best solution seems to be se restore size of window before first show and change splitter sizes after showing up.
1. Open tray > Admin > Console
2. Change sizes of window and splitter parts
3. Restart tray
4. Open tray > Admin > Console again
5. Size of window and splitter parts should be the same, or more close then were before this PR

Console Interpreter: Changed how console splitter size are reused on show

---

openpype/modules/base.py
openpype/modules/ftrack/event_handlers_user/action_create_folders.py

Example addons folder is not auto-loaded because is not in ignored filenames variable.
Added `example_addons` and `default_modules` folders into ignored folders. Also added condition to ignore all openpype module folders that don't have `__init__.py` files in. Side change is removement of imports in ftrack action `action_create_folders.py` which were accidentally added back during merge resolving.
1. OpenPype modules should be loaded.
2. Example addons must not be added automatically unless their path is explicitly added in settings.
3. Folders of OpenPype modules containing only pycache files should be skipped.

General: Add example addons to ignored

---

openpype/hosts/harmony/plugins/publish/collect_workfile.py

Subset name (folder and subset part of published workfile) was previously hardcoded as `workfileTASKNAME`.
Now it uses template in `project_settings/global/tools/creator/subset_name_profiles` -
1. modify template in `project_settings/global/tools/creator/subset_name_profiles`
2. publish workfile in Harmony, check name of published folder and name of published workfile if it matches to template

Harmony: Added creating subset name for workfile from template

---

openpype/hosts/aftereffects/plugins/publish/collect_workfile.py

Subset name (folder and subset part of published workfile) was previously hardcoded as `workfileTASKNAME`.
Now it uses template in `project_settings/global/tools/creator/subset_name_profiles` -
1. modify template in `project_settings/global/tools/creator/subset_name_profiles`
2. publish workfile in AE, check name of published folder and name of published workfile if it matches to template

AfterEffects: Added creating subset name for workfile from template

---

openpype/hosts/maya/plugins/publish/validate_camera_contents.py

Fixes #3026
1. create camera instance with just an empty group in it
2. pyblish -> right click -> select invalid -- should select the contents

Maya: Allow to select invalid camera contents if no cameras found

---

openpype/plugins/publish/validate_asset_docs.py

Fix **Validate asset docs** plug-in filename and class name which was invalid [as reported on Discord](https://discord.com/channels/517362899170230292/517382145552154634/961312392711667773).
Plus some minor typos/grammar changes.
This should also avoid a class name conflict with [Validate Containers](https://github.com/pypeclub/OpenPype/blob/2207d3a279a7974d187a43d404861cd68f06c05c/openpype/plugins/publish/validate_containers.py#L17).
1. Check whether the plug-in shows up and runs as expected.

General: Fix validate asset docs plug-in filename and class name

---

openpype/hosts/standalonepublisher/plugins/publish/collect_app_name.py
openpype/hosts/traypublisher/plugins/publish/collect_app_name.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
openpype/plugins/publish/collect_host_name.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

Added option to fill published files and host name in note during integration of ftrack note.
Reorganized integrate ftrack api plugin to be more readable. Integrate Ftrack Api now does not collect only used asset versions but also component data that were used to create them which gives ability to get published paths.
Integrate ftrack note does not require comment from artist to be able add the note, because the note may consist only from published paths and intent, but empty notes are not created. Added 4 new possible keys into note template `{host_name}`, `{app_name}`, `{app_label}` and `{published_paths}` which adds all published paths.
Extended host name collector to collect app name and app label into context.
Changed key in settings because note template was extended.
From: …

Ftrack: Add more options for note text of integrate ftrack note

---

openpype/tools/settings/settings/categories.py

Wrapper around settings content is splitter so projects view can be resized.
The version column did not show full version string and it was not possible to easily resize the column so it is visible. In that in mind the content of settings UI is wrapped by QSplitter so it is possible to resize them on demand.
1. Open settings UI and go to project settings
2. Change sizes of widgets using handle between projects view and settings

Settings UI: Version column can be extended so version are visible

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

The default value of `useSequenceForReview` was not used because the key was always available with value `None`.
Moved default value to place where the key is assigned to instance data. Issue caused by [this PR](https://github.com/pypeclub/OpenPype/pull/3015).
1. Publish using deadline
2. The review should be created in all matching aov cases

Deadline: Fixed default value of use sequence for review

---

openpype/modules/sync_server/providers/gdrive.py

Allow resolving a path with an environment variable in gdrive credentials.
For example:
if OpenPype is installed in `path/to/OP` and setting `project_settings/global/sync_server/sites/gdrive/credentials_url` is `{OPENPYPE_ROOT}/path/to/cred_file.json` will give `/path/to/OP/path/to/cred_file.json`

Resolve environment variable in google drive credential path 

---

openpype/hosts/unreal/api/pipeline.py
openpype/hosts/unreal/plugins/create/create_camera.py
openpype/hosts/unreal/plugins/create/create_layout.py
openpype/hosts/unreal/plugins/create/create_look.py
openpype/hosts/unreal/plugins/create/create_staticmeshfbx.py

Creators in unreal are using function from avalon which are not avaialbe anymore and were importing `Creator` directly which caused that the base of Unreal Creator was visible in Creator tool.
Change imports to use function from OpenPype and base `Creator` plugin is not part in globals of plugin files.
1. Open unreal using openpype
2. All should work
3. Creator tool should show all 4 current creators and not should default one

Unreal: Creator import fixes

---

openpype/modules/sync_server/providers/dropbox.py
openpype/modules/sync_server/providers/gdrive.py

GDrive site was checking presence of credentials even if it was disabled on a project.
This caused uncaught exceptions which prevented of synching of totally unrelated sites, which were configured correctly.
Same behavior noticed in Dropbox, SFTP checked also (without this issue).
1. Add Gdrive site in System Settings
2. disable it on project settings
3. restart Tray (without this fix, it would complain in the log that Gdrive credentials are missing)

SiteSync: Providers ignore that site is disabled

---

openpype/modules/sync_server/sync_server_module.py
openpype/plugins/publish/integrate_new.py

Based on specific use case for a customer where separate site is used for specific project.
'studio2' site was created to separate synchronization for specific project, previous implementation didn't handle setting this site as an alternative site to `studio`.
1. this PR will be tested by customer on their specific configuration
2. It should be tested on regular configuration if it didn't break anything (just pulled and start OP and try to publish something if it behaves same way as before)

SiteSync: fix transitive alternate sites, fix dropdown in Local Settings

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py

Fixed wrong looping over dictionary object.
Loop over dictionary did not use `items` method. Bug was added with [this PR](https://github.com/pypeclub/OpenPype/pull/3025).
1. Run any publish which will trigger integrate ftrack api and will cause that new asset type will be created
- asset type name can be defined in `project_settings/ftrack/publish/IntegrateFtrackInstance/family_mapping`

Ftrack: Integrate ftrack api fix

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py

Removed forgotten hardcoded family
1. Publish psd or tvp via Webpublisher
2. shouldn't create render family

Webpublisher - removed wrong hardcoded family

---

openpype/hosts/houdini/api/pipeline.py

This PR fixes #2946 by avoiding import of `hdefereval` when no UI is available.
Run this from Houdini
```python
import subprocess
subprocess.Popen("hbatch")
```
Before this PR an error is raised as per the issue. Now it doesn't. 👍

Houdini: Avoid ImportError on `hdefereval` when Houdini runs without UI

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py

TVP workfile was parsed by ffprobe
1. Publish TVP workfile via Webpublisher

Webpublisher: fix processing of workfile

---

openpype/tools/utils/lib.py

Family filter now query asset from current project instead of project selected in library loader.
Library loader queried asset document which defines family filters from the project defined in library loader instead of from current project which caused missing asset document bug.
1. You have to have at least one library project
2. Open host in other project
3. Open Library loader in the host
4. Select a library project
5. Tool should not crash due to missing asset document
```
```

LibraryLoader: Use current project for asset query in families filter

---

openpype/lib/applications.py
openpype/settings/defaults/system_settings/general.json
openpype/settings/entities/schemas/system_schema/schema_general.json
openpype/settings/lib.py
openpype/tools/settings/local_settings/constants.py
openpype/tools/settings/local_settings/environments_widget.py
openpype/tools/settings/local_settings/window.py

Give ability to define white list of environment variables that can be changed per machine.
In `system_settings/general` was added new key `local_env_white_list` where is possible to define environment variable keys that can be changed per machine. Values of the environment variable keys can be set in Local settings UI. Values are applied on application launch and only if launch environments contain the keys.
These environment variable changes are not applied on OpenPype launch but only on application launch.
1. Not sure about the placement of the env white list in the `system_settings/general/local_env_white_list`, it could be maybe added under applications as it's related to them?
TODO modify documentation based on answer of question 1
1. Add a env key into …

General: Local overrides for environment variables

---

openpype/lib/transcoding.py
openpype/plugins/publish/extract_review.py

Extract review prepare input exrs with invalid characters for ffmpeg.
FFmpeg can't read exr input if it's metadata attributes contain invalid characters, from that moment ffmpeg can't read any information about input (like width, height, ...) and will crash on using it as source. Added check for invalid characters (similar to string length check) which can cause that attribute is removed before ffmpeg processing. Right now the invalid chars contain only `"` but will be probably extended over time. Another issue was when data from input could not be read by ffmpeg the temporary staging dir was not set back to previous directory so integration failed because could not find source exrs.
1. Publish something that will produce exrs with `"` in attributes (e.g. cryptomatte adds json string)
2. …

General: Extract Review handle invalid characters for ffmpeg

---

openpype/hosts/aftereffects/plugins/publish/collect_render.py
openpype/hosts/maya/plugins/create/create_render.py
openpype/hosts/maya/plugins/create/create_vrayscene.py
openpype/hosts/maya/plugins/publish/collect_render.py
openpype/hosts/maya/plugins/publish/submit_maya_muster.py
openpype/hosts/maya/plugins/publish/validate_muster_connection.py
openpype/lib/__init__.py
openpype/lib/connections.py
openpype/modules/deadline/deadline_module.py
openpype/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py
openpype/modules/deadline/plugins/publish/collect_default_deadline_server.py
openpype/modules/deadline/plugins/publish/collect_pools.py
openpype/modules/deadline/plugins/publish/help/validate_deadline_pools.xml
openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/deadline/plugins/publish/validate_deadline_pools.py
openpype/settings/defaults/project_settings/deadline.json
openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json

Previous solution was nonconsistent, expected values for pools in multiple places in Setting.
New collector and validator was introduced. Collector adds pool names from Setting (merged and removed separate pool settings in hosts sections) if not already present on a instance (as Maya has it, potentially others with New Publisher).
Validator checks if name of pools on the instances matches to current values on DL (does a query of DL).
Refactored `_requests_get` and `requests_post` wrappers into `openpype.lib.connections` - name up for commenting/changing.
1. configure `project_settings/deadline/publish/CollectDeadlinePools`
1.a - insert non existent values
1.b - insert values matching situation on DL
3. publish on DL and check pools

Deadline: reworked pools assignment

---

openpype/hosts/nuke/plugins/inventory/select_containers.py
openpype/hosts/nuke/plugins/load/load_backdrop.py

Import of `openpype.hosts.nuke.api.command` has typos in 2 plugins loader `LoadBackdropNodes` and inventory action `SelectContainers`.
Fixed the imports from `openpype.hosts.nuke.api.commands` to `openpype.hosts.nuke.api.command`.
1. Load backdrop and Select containers should work

Nuke: Typos in imports from Nuke implementation

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

Updated github workflow action.
Due to fix of [security issue](https://github.blog/2022-04-12-git-security-vulnerability-announced/) workflow action, pushing to protected branch `main`, stopped to work. The action was [recently fixed](https://github.com/CasperWA/push-protected/pull/115) so the action version which should be used was changed.

GitHub: Updated push-protected action in github workflow

---

openpype/lib/profiles_filtering.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py

Previously filtering used only for collections and 'render' family.
This should allow more control when to add 'review' tag to representation.
1. Create `prerender` write node in Nuke
2. configure `project_settings/deadline/publish/ProcessSubmittedJobOnFarm/aov_filter`
2a. configure that pattern matches created subset name
2b. configure that pattern doesn't match created subset name
4. publish
5. check Ftrack

Nuke: Add aov matching even for remainder and prerender

---

openpype/tools/standalonepublish/publish.py

Install openpype plugins properly. Bug caused by [PR](https://github.com/pypeclub/OpenPype/pull/3009).
Changed deprecated `openpype.install()` to `install_openpype_plugins()`.
1. Open standalone publisher
2. Run publish

Standalone publisher: Fix plugins install

---

openpype/tools/project_manager/project_manager/model.py

Existing asset documents are not updated if nothing has changed.
Keys `parent` and `data.parents` are always resolved as changed on existing asset items. That is because queried asset documents do not contain them at all. Added `parent` and `data.parents` to query projection so they can be compared. Source issue and [PR](https://github.com/pypeclub/OpenPype/pull/3082).
Best way how to validate this is working is by modifying code in `openpype/tools/project_manager/project_manager/model.py` on line (approximately line 1412 where condition `if bulk_writes:` is) add log/print of `bulk_writes`. Bulk writes contain all updates that happened which should be empty if nothing has changed.
Visually nothing changes.
1. Open Project manager
2. Choose any project
3. Hit "Save"
4. Terminal log should …

Project Manager: Avoid unnecessary updates of asset documents

---

openpype/modules/royalrender/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
openpype/pype_commands.py

Submission from RoyalRender Control application must set `AVALON_APP_NAME` even if it is not used down the line. This is fixing it by calling necessary functions only if this variable is set.

RoyalRender Control Submission - AVALON_APP_NAME default

---

openpype/cli.py
openpype/lib/log.py
openpype/modules/ftrack/ftrack_server/lib.py
openpype/pype_commands.py
openpype/settings/defaults/system_settings/general.json
openpype/settings/entities/schemas/system_schema/schema_general.json
openpype/settings/handlers.py
start.py
website/docs/admin_openpype_commands.md
website/docs/admin_use.md

Added ability to turn on/off mongo logging and handle global arguments for verbose and debug.
Logging to mongo can be tuend on/off in system settings, change is propagated after restart. Added `--verbose` argument expecting verbose level int [0-50] or string matching python log level enum, value is stored in env variable `OPENPYPE_LOG_LEVEL`. With verbose argument seems `--debug` argument deprecated but there are usages for it so it was also added global flag argument `--debug` which affects `OPENPYPE_DEBUG` value.
This is partially fix and partially enhancement. Current usage of `--debug` argument is not propagated in current process because is handled too late.
- change logging to mongo in settings and check if is propagated
- use all new global arguments
- verbose
- debug
Resolves …

General: Add global log verbose arguments

---

igniter/bootstrap_repos.py
setup.py
start.py
tests/unit/igniter/test_bootstrap_repos.py

Remove logic related to repos directory in OpenPype which is removed in [PR](https://github.com/pypeclub/OpenPype/pull/3066).
Repos directory related logic was removed and few places based on repos directory path was modified. Repos directory is not handled at all from this moment. Zip files copied from version repository are removed.
PR is extending [this PR](https://github.com/pypeclub/OpenPype/pull/3066). This change may affect how OpenPype works so it was separated to this PR to see changes better.
- Test if OpenPype from code works
- Zip can be created from code
- Build can be created from code
- Build can load zip from openpype repository
- zip copied to Local App data should be removed when extracted

General: Remove repos related logic

---

openpype/hosts/maya/plugins/publish/collect_render.py

This fixes the bug mentioned [here](https://github.com/pypeclub/OpenPype/pull/3055#issuecomment-1106235644)
With this fix a simple renderlayer with a single camera without <camera> in the render tokens now has render cameras checked correctly. 
1. Open a lighting scene without `<camera>` render token and check if you can collect `CreateRender` correctly

Maya: Collect Render fix any render cameras check

---

openpype/hosts/maya/api/lib_renderproducts.py
openpype/hosts/maya/plugins/create/create_render.py
openpype/hosts/maya/plugins/publish/validate_rendersettings.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/settings/defaults/system_settings/tools.json

This is restoring basic support for Renderman in Maya and OpenPype. It is still very basic and has no support for more advanced features like light groups, and so on.
Install Renderman for Maya, create simple scene, create render instance, submit to farm.

Fix support for Renderman in Maya

---

openpype/lib/path_templates.py

It is possible to create copy of `TemplateResult` object.
Creating copy of `TemplateResult` crashes because is using `str` implementation of calling `__new__` which does not pass all arguments. Implemeneted `copy` method with `__copy__` and `__deepcopy__` magic methods.
1. Get template result using `format` on `openpype.lib.StringTemplate`
2. Create copy of the result
```
import copy
from openpype.lib import StringTemplate
result = StringTemplate.format_template("{key}", {"key": "value"})
result_copy = copy.deepcopy(result)
```

General: TemplateResult can be copied

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

Give ability to set status of AssetVersion on publish.
Added new settings `project_settings/ftrack/publish/IntegrateFtrackInstance/asset_versions_status_profiles` where is possible to define which status will have asset version on publish. By default is empty.
1. Add new profile in the settings
2. Set to the result of profile different then default status from ftrack
3. Publish
4. Check if AssetVersion in ftrack has the status

Ftrack: AssetVersion status on publish

---

openpype/lib/avalon_context.py

Get last versions in queries works for Py3 hosts.
There is an issue that dictionary in Py3 returns `dict_keys` when `.keys()` is called which causes crash in mongod queries, so we're making sure that result of `keys()` is converted to list.
1. Run build workfile in Python 3 host
Older release variant of [PR](https://github.com/pypeclub/OpenPype/pull/3112).

General: Python 3 compatibility in queries

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/api/pipeline.py
openpype/hosts/nuke/api/plugin.py
openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
openpype/settings/defaults/project_anatomy/imageio.json
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json

Adding ability to override Anatomy imagio required nodes with subset filtering.
Some studios were requesting overriding per subset name regex filtering. This will allow to have different colorspace on subset `renderCompMain` then on `renderCompMask` for example. Overrides and also adding missing knob values if they are not found in the original Required Plugin nodes. 
- if override knob is having the same name but different value, value is overriten
- if override knob is not having its equivalent in original knobs, it is added
- if override knob is having matching equivalent in original knobs and having empty value, it is removed from original knobs.
1. Start testing workfile in nuke
2. go to Studio settings `project_anatomy/imageio/nuke/nodes/overrideNodes` at your project
3. configure …

Nuke: render instance with subset name filtered overrides

---

openpype/hosts/tvpaint/plugins/create/create_render_layer.py
openpype/hosts/tvpaint/plugins/create/create_render_pass.py
openpype/hosts/tvpaint/plugins/publish/collect_instances.py
openpype/hosts/tvpaint/plugins/publish/collect_scene_render.py
openpype/settings/defaults/project_settings/global.json

Render layer key in TVPaint implementation is without underscode (`render_layer` -> `renderlayer`).
Add 'renderlayer' to instance.data for TVPaint render instances. Render passes had `render_layer` which was changed to `renderlayer` and layers pass their `variant` as value. This is to match Maya specifically. There is a secondary reason to do so, to match subset group name filtering. Also usage of `render_pass` was modified to use `renderpass` to keep consistency.
For some time there must be bost ways how are keys stored. Release variant of [PR](https://github.com/pypeclub/OpenPype/pull/3110).
- New files
1. Open new TVpaint file
2. Create some render layers/passes
3. Publish
4. All should work and if subset group profile is matching, it should be grouped
- Old files
1. Open TVPaint file …

TVPaint: Match renderlayer key with other hosts

---

openpype/settings/defaults/project_settings/nuke.json

Default settings are set to the new `LoadClip` plugin
Settings were holding obsolete plugins
1. start nuke in testing task workfile
2. make sure no project overrides are in `project_settings/nuke/workfile_builder/profiles/0/current_context/0/loaders`
3. go to nuke menu Openpype/Build Workfile
4. It should load available subset version.

Nuke: fixing default settings for workfile builder loaders

---

openpype/modules/base.py

Fixes minor typo in logged message, `contan` -> `contain`.
Before:
```
- { ModulesLoader }: [  Module directory does not contan __init__.py file /path/to/module
```
After:
```
- { ModulesLoader }: [  Module directory does not contain __init__.py file /path/to/module
```

Cosmetics: Minor typo fix in ModulesLoader

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/api/pipeline.py
openpype/hosts/nuke/api/plugin.py
openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
openpype/settings/defaults/project_anatomy/imageio.json
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json

Adding ability to override Anatomy imagio required nodes with subset filtering.
Some studios were requesting overriding per subset name regex filtering. This will allow to have different colorspace on subset `renderCompMain` then on `renderCompMask` for example. Overrides and also adding missing knob values if they are not found in the original Required Plugin nodes. 
- if override knob is having the same name but different value, value is overriten
- if override knob is not having its equivalent in original knobs, it is added
- if override knob is having matching equivalent in original knobs and having empty value, it is removed from original knobs.
1. Start testing workfile in nuke
2. go to Studio settings `project_anatomy/imageio/nuke/nodes/overrideNodes` at your project
3. configure …

Nuke: render instance with subset name filtered overrides (3.9.x)

---

openpype/hosts/tvpaint/lib.py

Layers are composited in reversed order.
Layer were composited from top to bottom layer which is oposite then it should be.
1. Publish renderLayer with multiple layers
2. Output images should be in right order
Release variant of [PR](https://github.com/pypeclub/OpenPype/pull/3135)

TVPaint: Composite layers in reversed order

---

openpype/hosts/houdini/plugins/load/load_alembic_archive.py

Adds a Houdini loader for Alembic files through the `alembicarchive` node.
_Requested by one of our artists_.
The original Alembic loader would load alembic geometry directly into SOPs with an `alembic` node. The downside to that is that not all nodes/hierarchies can be accurately represented in SOPs since it's only geometry data. Thus empty transforms, or locators or parents in the hierarchies can't be correctly represented in SOPs only.
This Loader instead does allow to rebuild the full Alembic Hierarchy as a Houdini Hierarchy in the Network Editors.
- Logic is loosely based on the Camera Loader which already was using the `alembicarchive` node.
- Any local changes made INSIDE the Alembic Archive in the Houdini are lost upon updating since the contents are "Rebuild".
1. Test whether …

Houdini: Add loader for alembic through Alembic Archive node

---

openpype/lib/terminal.py

This tweaks the regex for colorizing in the terminal to change how the TrayModulesManager logs the enabled states' colors.
**Before:**
**After:**
I'm not too knowledgeable about this area of the code base so please double check the change.
1. Check whether logging messages are colored as intended and messages come out ok.

Terminal: Tweak coloring of TrayModuleManager logging enabled states

---

openpype/settings/defaults/project_anatomy/imageio.json

Regex example is correct.
This redex is in default settings just to inspire users for their own definition, but since it was wrong it was misleading.

Nuke: fix anatomy imageio regex default

---

start.py

Added missing variable in start.py.
Usage of missing OP version in headless mode did not crash properly. It crashed because of missing 'openpype_versions' variable. Moved logic of validate versions and print versions from `boot` into separated functions.
1. Start of OpenPype should work as did
2. When version which is not available should be used, it should crash properly in headless mode
- run e.g. `openpype_console --headless --use-version="4.4.4"` or `start.py --headless --use-version="4.4.4"`
```
Requested version "3.11.0" was not found.
File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\start.py", line 1050, in boot
version_path = _bootstrap_from_code(use_version, use_staging)
File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\start.py", line 830, …
```

General: Missing version on headless mode crash properly

---

setup.py

Python module 'dataclasses' was added to required module in build.
The module is Python builtin module which is not copied to build because is not used in OP but can be used in addons.
1. Only difference is that build will contain dataclasses module

General: Add 'dataclasses' to required python modules

---

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py

This is fixing bug introduced with renderman support changing output directory in deadline, Because renderman has different prefix for file and folder.
This is quick fix, but I still vote for optimizing the code to have as little as possible of hardcoded renderer specific code.

Deadline: fix the output directory

---

openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py

Fixed formatting of representation path with frames.
Arguments for `StringTemplate` were swapped which caused a crash.
1. Run the action from Ftrack on representation with frames
2. Action should delete files without any issues
```
==============================
<StringTemplate> argument must be a string, not <class 'dict'>.
==============================
File "/some_root/openpype/modules/ftrack/lib/ftrack_base_handler.py", line 137, in wrapper_launch
return func(*args, **kwargs)
File "/some_root/openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py", line 310, in launch
file_path, seq_path = self.path_from_represenation(repre, anatomy)
File "/some_root/openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py", line …
```

Ftrack: Action delete old versions formatting works

---

openpype/hosts/houdini/plugins/load/load_bgeo.py
openpype/tools/standalonepublish/widgets/widget_drop_frame.py

This PR is adding support for standalone publisher to publish `.bgeosc` and `.bgeogz` (compressed bgeo sequences/files). It is also adding basic loader for Houdini for `bgeo*`
Related to #3098

Compressed bgeo publishing in SAP and Houdini loader

---

openpype/hosts/photoshop/api/ws_stub.py
openpype/hosts/photoshop/plugins/publish/collect_color_coded_instances.py
openpype/hosts/photoshop/plugins/publish/validate_naming.py

Invalid character(s) (as a undercore) triggered error in ValidateNaming.
Plugin which creates instances from color coded layers uses `ValidateNaming` Settings to clean subset and layer name
Version for 3.9.x branch.
1. Prepare .pds with names like "Layer 1" or "Layer ;/ 1" with proper color coding by configured values in `project_settings/photoshop/publish/CollectColorCodedInstances`
2. Publish via Webpublisher and studio processing
3. It shouldn't fail

Webpublisher: replace space by underscore in subset names

---

openpype/hosts/harmony/plugins/publish/collect_farm_render.py

Render instance was missing filled task
1.Try to publish from Harmony to Deadline

Harmony: fixed missing task name in render instance

---

openpype/hosts/fusion/plugins/load/actions.py
openpype/hosts/houdini/plugins/load/actions.py
openpype/hosts/houdini/plugins/load/load_alembic.py
openpype/hosts/houdini/plugins/load/load_camera.py
openpype/hosts/houdini/plugins/load/load_image.py
openpype/hosts/houdini/plugins/load/load_vdb.py
openpype/hosts/maya/plugins/load/_load_animation.py
openpype/hosts/maya/plugins/load/actions.py
openpype/hosts/maya/plugins/load/load_ass.py
openpype/hosts/maya/plugins/load/load_gpucache.py
openpype/hosts/maya/plugins/load/load_reference.py
openpype/hosts/maya/plugins/load/load_vdb_to_vray.py
openpype/hosts/nuke/plugins/load/actions.py

Purely cosmetics (except for one!) change to fix some loader docstrings to be more accurate.
I believe these are also used as tooltip or status tip for the Loaders in the loader context menu so artists might actually see this information too.
It might still be worth looking into doing a more thorough cleanup and unifying of how Loaders are described across all hosts.

General: Cleanup some Loader docstrings

---

openpype/lib/transcoding.py

Fix check for invalid characters in oiio conversion.
Check for invalid characters never happened because of invalid condition before.
1. Create renders with `"` in some metadata attribute but shorted then 8196 characters
2. Make it go through ExtractReview plugin
3. It should not crash on ffmpeg conversion

General: Oiio conversion for ffmpeg checks for invalid characters

---

openpype/plugins/publish/extract_jpeg_exr.py

Extract jpeg exr does not create multiple representation names with "thumbnail" name but skip others after first.
There is no way how to define which representation will be source but that is for future PRs.
1. Publish on farm instance with more outputs from which thumbnail can be created (I don't know how)
2. It should not crash during integration

General: Avoid creating multiple thumbnails

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

Ftrack "prepare" integrator queries location entities which can cause issues if the component item is deep copied as different component for different usage.
The preparation integrator set only location name. Locations are then queried in the "real" integrator. Kept backwards compatibility.
1. Integration to ftrack should still work as did.
2. Integration of multiple thumbnails should be working as is implemented.

Ftrack: Locations deepcopy issue

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

Don't create `ftrackreview-image` component if there are mp4 reviews.
When there are both `ftrackreview-image` and `ftrackreview-mp4` it is not 100% sure that video is used as review source.
1. Publish something with review video and thumbnail
2. Only `ftrackreview-mp4` should be created

Ftrack: Review image only if there are no mp4 reviews

---

.github/workflows/prerelease.yml

Since 3.10 Avalon repo is no longer needed.

Avalon repo removed from Jobs workflow

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

This is fixing issue when renders couldn't be attached as a review to published subsets.
- Create look
- Create Render
- Drag Look instance under render layer set in Render instance
- Set your render settings as needed
- Publish
Look will be published just fine, job will be submited to farm and when complete, render will be published as render. It will be shown on ftrack as render asset type and you won't find it in Maya Loader.
This is fixing it, render should attach correctly and look subset should be found along others in Loader as usual.
Close #2753

Fix for attaching render to subset

---

openpype/hosts/traypublisher/api/plugin.py
openpype/modules/base.py
openpype/modules/interfaces.py
openpype/pipeline/context_tools.py
openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py

Addons can register creator plugin paths and Creators can have host name filter.
Creator plugins have host name filtering so e.g. tray publisher creators won't appear in other hosts. Addon can implement new method which return creator plugin paths for specific host name. Default implementation is using `get_plugin_paths` for backwards compatibility. Installation of openpype plugins will also register creators from modules. Creator plugin has also ability to define host name filter.
We wanted to have filtering ability of creator plugins on both addon and creator side so creator plugin has `host_name` attribute which can define on which host is working. This is for backwards compatibility not abstract. But it is a question if it should be required? In most of cases it is only matter of …

General: Creator plugins from addons can be registered

---

openpype/modules/sync_server/sync_server_module.py
openpype/tools/loader/model.py

A little bit enhanced loader UI speec when sync server is enabled.
Cache sync server related information for some time to avoid refresh of sync server on each selection change.
Loader was refreshing sync server module, it's setting for all projects on each change of context in loader UI which is also happening separatelly for subset widget and representation widget.
This is a "quick" change, full fix would require to modify some logic in sync server and partially rewrite how loader UI logic works.
Loader didn't change but should be faster when sync server is enabled.

Loader UI: Speed issues of loader with sync server

---

openpype/hosts/hiero/api/otio/hiero_export.py

Effect object uses update rather then __setter__ method
1. open hiero (13 <) script with timeline with animated timewarp on clip
2. publish
3. all should look fine

hiero: otio p3 compatibility issue - metadata on effect use update 

---

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
openpype/tools/standalonepublish/widgets/widget_components.py

Standalone publisher thumbnail extractor create new representation for thumbnail even if source file has `jpg` extension.
The missing representation caused few issues the major is that ftrack did not integrate the published path of the source image. Also temp files from standalone publisher are cleaned up when publishing finish.
1. Publish jpg file marked as thumbnail, using standalone publisher (and using ftrack module)
2. Check if ftrack AssetVersion contains both `thumbnail` and `jpg` components where `jpg` component contains published path

Standalone Publisher: Always create new representation for thumbnail

---

openpype/pipeline/context_tools.py
start.py

Module's publish plugin paths are registered during installation of OpenPype plugins.
Changed how module plugin paths are registered. Instead of using environment variables are plugin paths registered during installation of OpenPype plugins which is more suitable and possible dynamic.
This approach gives more dynamic approach of registering publish plugins (e.g. does not require restart of tray when module change state). Can be extended in future to install plugin paths per project and more dynamically, which is not as easy now because modules' plugin paths are there from moment when openpype starts.
PR is based on https://github.com/pypeclub/OpenPype/pull/3179 where creator plugins are installed same way. I wanted to separate the PRs as this change should be fully tested.
1. All modules …

General: OpenPype modules publish plugins are registered in host

---

openpype/hosts/hiero/api/otio/hiero_export.py
openpype/hosts/hiero/plugins/publish/precollect_instances.py
openpype/lib/editorial.py

Improving clip duration calculation
Frame duration should not be excluding one frame as it is disturbing other hosts. Better to fix it in global then hack particular dcc (flame)
1. open your testing hiero script
2. publish a clip
3. all should look as expected

General/Hiero: better clip duration calculation

---

openpype/hosts/nuke/api/plugin.py
openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
openpype/hosts/nuke/plugins/publish/extract_thumbnail.py
openpype/hosts/nuke/plugins/publish/precollect_writes.py

Publishing UX are less distracting 
Once additional publishing nodes created on flight are created inside rendering group node. Publishing seems to be less distracting
1. open nuke test script
2. publish render write node
3. notice that during publishing no nodes are created in top tree view.

nuke: generate publishing nodes inside render group node 

---

openpype/hosts/maya/plugins/load/actions.py

By selecting this option all occurrences of cbId of imported nodes will be removed.
Usable for sharing assets between projects.
1. Load model via `Import` loader - set `Clean import` option (rectangle after Import label)
2.`cbId` in `Extra Attributes` should be removed (also check log for 'Removing ..' in Script Editor)

Maya: added clean_import option to Import loader

---

openpype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py

Push hierarchical attributes action had swapped arguments sent to 'query_custom_attributes'.
Swapped attributes where `query_custom_attributes` is called to fix query of hierarchical attributes.
1. Run the action on some hierarchy where hiearchical attributes have different value then non-hierarchical
2. When job finishes the values should be same as were hierarchical

Ftrack: Push hierarchical attributes action works

---

openpype/tools/project_manager/project_manager/model.py
openpype/tools/project_manager/project_manager/view.py
openpype/tools/project_manager/project_manager/window.py

Speed of project loading was enhanced by ignoring signals during initial project item creation.
Blocking of signals during that time cause that filtering and repaint of view is not triggered which makes everything much smoother. Also refresh button forces to refresh current project.
1. Open project manager
2. Select project
3. Load of project entities should be 3x faster

Project manager: Sped up project load

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

submission of publishing job to deadline had a serious bug for some quite time: It is creating new instances based on stuff that is being rendered. For this it is using some skeleton data that are part of every newly created instance.
When the instance was being created, it `copy()` the skeleton data but that is only shallow copy. Anything that was modifying data on newly created instance edited them in skeleton data too, influencing all other newly created instances.
```python
from copy import copy
skeleton = {
"name": "A",
"families": []
}
new_instance_names = ["B", "C", "D"]
new_instances = []
for new_name in new_instance_names:
new_instance = copy(skeleton)
new_instance["name"] = new_name
if new_name == "C":
new_instance["families"].append("FOO")
new_instances.append(new_instance)
for …
```

Deadline: instance data overwrite fix

---

openpype/hosts/maya/plugins/load/load_image_plane.py

Only mov, exr, preview and png were present, jpg should work too.

Maya: added jpg to filter for Image Plane Loader

---

openpype/tools/project_manager/project_manager/model.py
openpype/tools/project_manager/project_manager/view.py
openpype/tools/project_manager/project_manager/window.py

Open persistent editors on project change/refresh in Project manager. Issue caused by [PR](https://github.com/pypeclub/OpenPype/pull/3216).
Insert signals are ignored on initial items fill on project refresh which cause that persistent editors are not opened. Opening of persistent editors is "faked" after project refresh. This change make it a little bit slower.
1. Open project manager
2. Select a project
3. All editors should be visible on all items and their values should match
4. The same should work on project change or on save

Project Manager: Fix persistent editors on project change

---

openpype/tools/project_manager/project_manager/model.py
openpype/tools/project_manager/project_manager/view.py

You can now paste Tasks from the clipboard onto multiple assets at once instead of having to paste into only the 'currentIndex' and thus having to paste per asset individually
1. Select some Tasks
2. CTRL + C
3. Select some Tasks/Assets
4. Paste
It should consistenly copy things across and feel logical as to what it does in the end.

Project Manager: Allow to paste Tasks into multiple assets at the same time

---

openpype/hosts/tvpaint/api/lib.py

Loop over more layer groups then initial 12.
TVPaint can have more then 12 groups but we've always looking only for 12 groups. This has changed to look over 100 groups which is also not perfect but there is not much safe way how to find out how many groups there is.
1. Create RenderLayer in TVPaint file with more then 12 groups
2. It should not crash
3. Publish should pass and render correct output

TVPaint: Look for more groups than 12

---

openpype/modules/ftrack/lib/credentials.py

Validation of ftrack credentials also check if the username exists on ftrack.
Ftrack connection is primarilly available by using ftrack api key and invalid username may not be discovered on session creation but can cause few issues when timer listener is launched in Tray. Due to these issues a validation of ftrack username existensce was added.
1. Open OpenPype tray
2. Login in OpenPype ftrack module
3. Close OpenPype tray
4. Change username in ftrack
5. Open OpenPype tray and ftrack loin popup should show

Ftrack: Validate that the user exists on ftrack

---

openpype/hosts/maya/api/lib_renderproducts.py

This changes allows skipping processing of display type of Renderman that doesn't produce any file output. It should fix publishing renders on farm where validator was expecting produced files from those unsupported display types.
1) Open Maya with Renderman
2) Load / Create scene for testing rendering
3) Create Rendering instance
4) Configure some render channels / displays
Running this should list all your displays currently present:
```python
from rfm2.api.displays import get_displays
displays = get_displays()["displays"]
for name, display in displays.items():
print(f"{name}: {display['driverNode']['type']}")
```
you should get bunch of `d_openexr` (per number of displays you've created)
5) Open Renderman IPR
6) After it did some work, run the above code again. You should get the same …

Maya: renderman displays needs to be filtered

---

openpype/modules/ftrack/lib/avalon_sync.py

Make sure chunk size is at least 1 when chunks are created.
The issue happens in rare ocassions where a lot of entities from ftrack are queried at once.
1. There must be a very large project on ftrack (5000 entities at least)
2. Run sync to avalon
3. It should not crash

Ftrack: Chunk sizes for queries has minimal condition

---

openpype/hosts/harmony/api/TB_sceneOpened.js

Harmony 21.1 changed Qt Javascript API from 4 to 6 which resulted in issue with missing QDataStream.
Different approach of getting QtTextCodec implemented.
1. start Harmony 21.1.
2. Openpype menu should show up and work

Harmony: 21.1 fix

---

openpype/hosts/unreal/plugins/load/load_camera.py

The function to import a camera from FBX is different from UE 4.27 onwards.

Unreal: Fixed Camera loading in UE5

---

openpype/hosts/maya/plugins/publish/collect_fbx_camera.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json

This is adding support for publishing camera from Maya as FBX. This is disabled by default
You can enable it in the Settings here `project_settings/maya/publish/CollectFbxCamera` by enabling **Collect Camera for FBX export**. When you publish your camera, fbx representation will be made.

Maya: FBX camera export

---

openpype/tools/project_manager/project_manager/view.py

Do not create persistent editors but create then on demand.
Creation of persistent editors is making the UI initialization slow but at the same time it's easy to see what can be modified. This change cause that editors are not visible so it's unclear what can be modified but it's really fast on initialization. All other functionality should stay the same. Also the columns are not resized to editor's size hint because are not known at the moment.
1. Run project manager
2. Select project
3. Loading of project should be fast
4. Change any value on items

Project manager: Speed up but without persistent editors

---

openpype/hosts/harmony/api/TB_sceneOpened.js
openpype/hosts/harmony/api/server.py

Additional fix for message length.
Harmony 21.1 doesn't have QDataStream anymore.
This means we aren't able to write bytes into QByteArray so we had
modify how content length sent do the server.
Content length is sent as string of 8 char convertible into integer
(instead of 0x00000001[4 bytes] > "000000001"[8 bytes])

Harmony: message length in 21.1

---

openpype/hosts/unreal/plugins/load/load_camera.py

Fixes a problem when loading a camera asset when the layout is missing.
When loading a camera, the loader checks for the master level. If no layout has been loaded, the master level is missing. Now when loading the camera, if there's no master level, it is created similarly to the master level sequence.

Unreal: Fix Camera Loading if Layout is missing

---

openpype/hosts/nuke/api/plugin.py

Bake stream reformat knob settings improvements
Knob type from settings was not allowing unicode to be set as value.
1. in settings on any bake output preset activate reformat and set some knob values
2. Open nuke workfile and render some render family node
3. all should work as expected

Nuke: bake reformat was failing on string type

---

openpype/lib/editorial.py

Fixing editorial data, resolving
Editorial in Hiero was not correctly resolving frame range - it was making them one frame longer. Following plugins were crashing because they could not find the redundant frame.
Editorial library function was not correctly looking at framerange.

General: editorial collection one frame longer

---

openpype/plugins/publish/extract_review_slate.py

Allows Nuke slate with audio
Slate is concatenated with review using ffmpeg concat. Concatenation requires same number, type and layout of streams in concatenated files. Adding silence to the slate before concatenation allows to keep the audio in the review.
- Some review files do not support audio. Make sure you use Do not add audio tag to avoid encoding fail.
- It seems that some file formats produce small audio offsets. That might be a limitation of concat.
1. make sure you have an audio available
2. setup a review with Add Slate Frame tag
3. Publish from Nuke, with slate
4. Check that review file has slate and audio

add silent audio to slate

---

pyproject.toml

Changed url to new version (2.3.10) of OpenImageIO tools.
1. Fetch 3rd party libs
2. Run any publishing which is using oiio or try run the oiio manually

General: Updated windows oiio tool

---

openpype/hosts/maya/api/plugin.py
openpype/hosts/maya/plugins/load/_load_animation.py
openpype/hosts/maya/plugins/load/load_ass.py
openpype/hosts/maya/plugins/load/load_look.py
openpype/hosts/maya/plugins/load/load_reference.py
openpype/hosts/maya/plugins/load/load_yeti_rig.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schema_project_maya.json

All reference loaders in Maya now could instead of real published folder use environment variable placholder. This would allow to use this workfile in different locations (remote artist computer, studio etc.)
`OPENPYPE_PROJECT_ROOT_WORK` is calculated for values in Anatomy or overridden values from Local Setting.
This placeholder is physically stored in workfile, each value is resolved when workfile is opened. 
This allows remote artists to reference assets in a workfile and publish it. Same workfile will then work everywhere (studio, different artist) if they have Anatomy or Local Setting configured to existing folder on their machine.
This limits opening workfiles without Openpype, this could be remedied by adding used environment variable to artist environment. (By adding to theirs mel …

Maya: reference loaders could store placeholder in referenced url

---

openpype/hosts/webpublisher/webserver_service/webpublish_routes.py

Previously even archived projects were shown in Webpublisher front end
3.9.x version of https://github.com/pypeclub/OpenPype/pull/3281
1. Check FE if only active projects are visible

Webpublisher: return only active projects in ProjectsEndpoint

---

openpype/hosts/unreal/plugins/load/load_rig.py
openpype/hosts/unreal/plugins/load/load_staticmeshfbx.py

This small PR is just adding support for `skeletalMesh` and `staticMesh` to Unreal loaders.
Just publish skeletal mesh and static mesh in Maya and load it in Unreal

Unreal: add support for skeletalMesh and staticMesh to loaders

---

openpype/lib/vendor_bin_utils.py

Fix path to oiio tool on linux.
It seems that oiiotool was not used on linux at all. This is a quick fix before resolving issue https://github.com/pypeclub/OpenPype/issues/3276.
1. It should be possible to use oiiotool on linux machines
- e.g. by running script on tray admin console
```
from openpype.lib.transcoding import get_oiio_info_for_input
some_path_to_image = ""
print(get_oiio_info_for_input(some_path_to_image))
```

General: Fix Oiio tool path resolving

---

openpype/hosts/maya/api/lib.py
openpype/tools/utils/host_tools.py

Originally-authored-by: @icyvapor 
follow up on #3208
Look assigner now handles RuntimeError and continues with material assignment; also some UI usability improvements for host tools.
Add a bit error handling so LookAssigner doesn't abort when there's any single RuntimeError.
Also we noticed LookAssigner is not docked as a sub-window of the main Maya window, and once it's opened, clicking the menu item(or icon) wouldn't bring up the UI to the default size. So I added showNormal() call. Did the same for couple of other UI tools.

Maya: Look assigner UI improvements

---

website/docs/admin_settings_project_anatomy.md

I added the app key which was missing in the documentation on the list of existing keys in the templates.

Documentation: Add app key to template documentation

---

openpype/hosts/maya/plugins/publish/collect_render.py

Reviews from Maya had swaped width and height collected from scene.
1. Publish from maya with some review in scene

Maya: Fix swaped width and height in reviews

---

openpype/modules/ftrack/event_handlers_user/action_delivery.py

Added ability to run Delivery action on review session objects.
Action works the same way but if review session is selected it will first query it's asset versions and from that point the logic is same.
Enhanced speed with prequerying data that are used at multiple places.
1. Make sure you have at least on (valid) delivery template in project's anatomy templates
- one key in delivery templates is one path (full path)
2. Run delivery action of Review Session in ftrack
3. Check output in delivery folder

Ftrack: Delivery action can work on ReviewSessions

---

openpype/hosts/maya/api/pipeline.py
openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
openpype/pipeline/context_tools.py
openpype/plugin.py

By default when host is started, it should register targets to 'local', only if specific env var is set (OPENPYPE_REMOTE_PUBLISH) it should be 'remote'. This means
farm is using host to collect/validate/extract and publish on behalf of artist.
Without this extractors weren't triggered in other host than Maya (which is explicitly setting targets to local because of implementation of remote pointcache publishing).
This PR sets 'targetst = ["local"]' to any host not started on a farm.
1. Retry Maya ABC pointcache farm publishing
2. Try publish locally in Nuke

Fix - added local targets to install host

---

openpype/hosts/tvpaint/api/pipeline.py
openpype/hosts/tvpaint/plugins/publish/extract_sequence.py

Extractor does not change rendered frame range based on frame start/end on instance but uses mark in/out.
Extractor forced to use frame start/end stored on instance data, which is ignoring what is set to be rendered. So even if validation of mark in/out is turned off it is not possible to render different range of images from TVPaint. With this change is used only frame start as "offset" for filename frame and frame end is calculated using frame start and marks range.
1. Open TVPaint
2. Change Mark in or Mark out so the range does not match frame range on asset
3. Run publish
4. Disable validation of mark in/out
5. Hit publish
6. Extraction should work and render the range defined by mark in/out
3.9.x variant of [PR](https://github.com/pypeclub/OpenPype/pull/3309).

TVPaint: Extractor use mark in/out range to render

---

openpype/hosts/maya/plugins/load/load_gpucache.py

This simple PR is adding `pointcache` family to GPU loader so alembic published as pointcaches can be loaded with it.
Try to load pointcache alembic as GPU cache in Maya
Close #3313

Maya: add pointcache family to gpu cache loader

---

openpype/tools/project_manager/project_manager/delegates.py

(cherry picked from commit fbdd225c8b0cc579a022d69c179a5f90fc6a387d)
Show Tools of an asset even when not currently editing in Project Manager
Before:
After:
1. Open Project Manager in a project that has custom tools assigned per asset
2. Confirm they are visible when directly going into the project (even when not editing)

Project Manager: fix tools not being visible until when editable

---

openpype/tools/project_manager/project_manager/view.py
openpype/tools/project_manager/project_manager/window.py

(cherry picked from commit 96ca15b565b952d4e17c2010e8846ca18272d681)
This makes the "Task" button create a directly editable task for name/type like when doing right click -> Add Task.
Otherwise it makes a task for which it's unclear what to do next.
Before:
After:
~I know this is not the way to fix it because it calls a private method. However, I'm opening this to start the discussion and approach a better solution. Maybe make that method not private?~ Made public with https://github.com/pypeclub/OpenPype/pull/3325/commits/cbc6fb8b330abc88c0e8c64c57a966cd09fd8077
1. Open Project Manager
2. Select an asset
3. Click on the "Task" button in the top left
4. The task should now directly be clearly editable and have a default type.

Project Manager: Directly make task editable when clicking on the add Task button

---

openpype/modules/ftrack/event_handlers_server/action_create_review_session.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

Added server action to create daily review session with ability to auto-create dailies each day.
Action creates review session with name based on template defined in settings. If there is review session with same name then rest of logic is skipped. If there is not review session with same name and then is review session from "previous day" which does not contain any reviewables then that is just renamed otherwise new review session object is created. Action does daily cycles during which checks if project has enabled "daily creation" of review sessions and create them automatically for all enabled so the action does not have to be executed manually.
If template does not contain day formatting key it probably won't be "daily" so it can be used for e.g. weeklies too. Default template is …

Ftrack: Action to easily create daily review session

---

openpype/hosts/hiero/api/otio/hiero_export.py

Effect object uses update rather then __setter__ method
1. open hiero (13 <) script with timeline with animated timewarp on clip
2. publish
3. all should look fine
https://github.com/pypeclub/OpenPype/pull/3194

hiero: otio p3 compatibility issue - metadata on effect use update 3.11

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/plugins/create/create_write_still.py

Temporarily fixing anatomy backward compatibility
Anatomy had changed bit in the way it is configuring node knobs. Backward compatibility had to be maintained on projects which are locked on production.
- changes are annotated as `HACK` and needs to be removed as soon as they will not be needed
1. open nuke on project with anatomy versioned back to 3.9
2. open Creator and see Still image plugin is missing (if it is not available in `project_anatomy/imageio/nuke/nodes/requiredNodes`)
3. create Render, Prerender nodes and see those are created fine.

Nuke: anatomy compatibility issue hacks

---

openpype/tools/settings/settings/base.py
openpype/tools/settings/settings/categories.py
openpype/tools/settings/settings/constants.py

Added option to extract current values into json file.
Extraction takes current values and extract them to a json file. It takes all values no matter if are overriden or not. Values are stored under keys with double underscores to be able differentiate what is value and what are metadata. Also added option to paste values from clipboard that are copied from different source or when whole file is copied.
Didn't add option to "open json file" because it would be hard to find out what user want's to do with it. This is not meant as backup of Project settings as it does not save only overrides but all values.
2. Right click on any item in settings and hit `Extract to file`
3. Select output file and hit Save
4. Check output
2. Copy file in file explorer …

Settings: Settings can be extracted from UI

---

openpype/hosts/maya/plugins/publish/collect_look.py

This is fixing look collector so it will skip empty filename attributes. Useful mainly on nodes that defines file attribute but can accept also input from other nodes.
Create look with shader network, connecting **PxrTexture** to **PxrBump** for example in renderman (leaving filename attribute in **PxrBump** empty. Publishing and loading of the look should be successfull

Maya look: skip empty file attributes

---

openpype/hosts/blender/api/pipeline.py
openpype/hosts/blender/plugins/publish/extract_layout.py

Blender is using query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288) instead of direct use of mongo queries.
Blender uses query functions from `openpype.client`.
1. Run blender
2. Frame start/end should be set to asset's resolution
3. Publish layout
PR waits for merge of [PR](https://github.com/pypeclub/OpenPype/pull/3288)

Blender: Use client query functions

---

openpype/plugins/publish/integrate_new.py

Handle cases when instance contain `"source"` key but is empty during integration.
Missing `"source"` key causes crashes because of invalid type in version document. Changed in a way that empty source value on instance is ignored and in that case is used source as current file from context.
Not sure?
1. Happened during publishing in hiero
3.9.x variant of [PR](https://github.com/pypeclub/OpenPype/pull/3342)

General: Handle empty source key on instance

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

Submit job has filter of allowed environment values, it missed OPENPYPE_MONGO.
This issue will probably manifest only if deadline publish machine doesn't have set OPENPYPE_MONGO itself.

Deadline: added OPENPYPE_MONGO to filter

---

openpype/client/entities.py

Function `get_last_verisons` does not crash if `fields` are passed and do not contain `"parent"` key.
Missing `"parent"` key was not added to required fields properly.
Bug was spotted in standalone publisher where in specific cases is called this function.
It is possible to test in Tray > Admin > Console
```
from openpype.client import get_last_versions, get_subsets
project_name = "some project name"
any_subset = None
for subset in get_subsets(project_name):
any_subset = subset
break
versions = get_last_versions(project_name, [any_subset["_id"]], fields=["name"])
```

General: Fix last version function

---

openpype/hosts/maya/plugins/create/create_yeti_cache.py
openpype/hosts/maya/plugins/load/load_yeti_cache.py
openpype/hosts/maya/plugins/publish/collect_yeti_rig.py
openpype/hosts/maya/plugins/publish/extract_yeti_cache.py
openpype/hosts/maya/plugins/publish/extract_yeti_rig.py

I was unable to create a Yeti rig publish and load it correctly so I started working on fixing the implementation.
**This is still a draft WIP - not fully tested.**
Current status:
-  [x] Creators work
-  [x] Extractors work
-  [x] Loaders work
Currently the Yeti Rig publish will also try to create a single frame Yeti Cache alongside the rig publish - which as far as I know isn't required for a Yeti Rig to work. Would it make sense to remove that logic and if one would ever want both a "rig" and a "cache" from that same file they would just create two publish instances, one `yetiRig` family and one `yetiCache` family.
---
The way it's currently broken it seems like this has hardly ever been tested - or maybe has seen numerous changes in other areas of OpenPype but hasn't been tested in …

Maya: Fix Yeti errors on Create, Publish and Load

---

openpype/plugins/publish/extract_jpeg_exr.py

Fixed unexisting variable and only one thumbnail is created for an instance.
Extract thumbnail plugin did not check if any thumbnail was created or if was created more than one thumbnail. In case when more thumbnails was created was used only the last one, and plugin crashes if none was created.
1. Trigger farm publish which won't have representation that would be used as thumbnail source.
2. It should not crash if none thumbnail was created.
Don't know how to achieve that.

General: Create only one thumbnail per instance

---

openpype/modules/kitsu/utils/update_op_with_zou.py

Add a `None` to `pop(...)` to avoid process abortion at early stage of production

Kitsu: Prevent crash on missing frames information

---

openpype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
openpype/settings/defaults/system_settings/modules.json
website/docs/module_ftrack.md

Ftrack settings don't have `pypeclub` role for custom attributes creation in defaults.
Create/Update of custom attributes does not require `pypeclub` role by default. Changed label of action to `Create/Update Custom Attributes`.
1. Remove `pypeclub` role from ftrack (if is there)
2. Run action to Create/Update Avalon attributes which should not fail if the role is not in ftrack

Ftrack: Removed requirement of pypeclub role from default settings

---

openpype/api.py
openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/pipeline/create/context.py
openpype/plugin.py

This caused missing extractors that should be running on a farm (Slate extractor for Nuke...).
Explicitly set all plugins creating jobs on DL to be triggered only on local.
1. Try publish Nuke job that renders and publish Slates.
2. Try publishing Maya job

Deadline: removed wrong targets on Extractor

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

fixing wrong `review` attribute distribution
1. start your host supporting farm publishing
2. set your farm instance and set it to `review` **on** and publish
2.1. it should be reviewable on ftrack
3. set your farm instance and set it to `review` **off** and publish
3.1. it should not be reveiwable on ftrack

deadline: fixing misidentification of revieables

---

openpype/hosts/nuke/plugins/publish/precollect_writes.py

Always create variable representation in precollect writes.
Representation variable was created only if "representations" key was not in instance.data.
1. Create instance of write in nuke
2. Run publish
3. Collecting should not crash

Nuke: Fix precollect writes

---

openpype/hosts/aftereffects/plugins/publish/collect_render.py

Fix -ValidateSceneSettings was failing for legacy instances
Fix - renderLocal is published to 'render' folder same as render farm
1. Publish local render on AE
2. it should trigger `ValidateSceneSettings`
3. it should publish into 'render' folder instead of 'renderLocal'

AE- fix validate_scene_settings and renderLocal

---

openpype/hosts/nuke/plugins/publish/extract_thumbnail.py

Fixed missing variables in nuke's extract thumbnail at specific cases.
There were missing variables `previous_node` and `fhead` if `use_rendered` was disabled.
1. Disable use rendered in settings
2. Open nuke
3. Create something to create thumbnail (Render)
4. Publish
5. Should not crash on extract thumbnail

Nuke: Fix missing variable in extract thumbnail

---

openpype/hosts/harmony/plugins/publish/validate_audio.py

Wrong condition stayed after change from asset to raise (it should be negated).
1. add some audio file into Harmony
2. validator shouldnt trigger

Harmony: audio validator has wrong logic

---

openpype/hosts/maya/plugins/publish/collect_instances.py

Maya 2019 support was broken in collectors. This was reported to me by Petr Kalis on Discord.
Explanation in comment [here](https://github.com/pypeclub/OpenPype/commit/122536675fb043fda7d62710149c65cfd089d674#commitcomment-76327122)
`__iter__` is only implemented in Maya 2020+ for Maya Python 2.0 iterators.
1. Use Maya 2019
2. Publish an instance

Maya: Fix collector Maya 2019 support

---

openpype/hosts/standalonepublisher/plugins/publish/collect_bulk_mov_instances.py
openpype/hosts/standalonepublisher/plugins/publish/collect_hierarchy.py
openpype/hosts/standalonepublisher/plugins/publish/collect_matching_asset.py
openpype/hosts/standalonepublisher/plugins/publish/validate_task_existence.py

Modified standalone publisher plugins to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Standalone publisher plugins are using query functions from `openpype.client`.
1. Run publishing in standalone publisher using one of modified plugins
- editorial publishing
- bulk mov publishing
2. Publishing should work as expected

Standalone Publisher: Use client query functions

---

openpype/lib/avalon_context.py
openpype/plugins/publish/collect_current_pype_user.py
website/docs/admin_settings_project_anatomy.md

Use `get_openpype_username` to receive value for `user` key in template data collection.
This function is in openpype for a long time but was not fully used. It just gives ability to change username for templates instead of usign user name from machine by changing it in local settings.
Added `"user"` key to available template keys.
1. Change username in local settings UI
2. Add `"{user}"` to any template (e.g. publish)
3. Do something in a way that template is filled (e.g. run publish)
4. Check the create filepath if contains changed username from local settings

General: Add ability to change user value for templates

---

openpype/lib/avalon_context.py
openpype/modules/base.py
openpype/modules/timers_manager/timers_manager.py
openpype/pipeline/context_tools.py
openpype/tools/workfiles/files_widget.py

Modules are acknowledged on host installation that host was installed so they can register their specific callbacks. Workfiles tool also trigger events on workfile open. Moved start timer callback on task change to timers manager.
Modules have method `on_host_install` which is called when `install_host` is called, these modules are kept in memory (they're not refreshed for rest of process) that is because modules would be garbage collected and their callbacks would not work. Workfiles tool is triggering `workfile.open.before` and `workfile.open.after`. All events triggered from workfiles tool also contain context information (host name, project name, asset name and task name) so it's not just blind information. Task changed topic has human readable keys. Logic related to start timer on …

Hosts: More options for in-host callbacks

---

openpype/hosts/maya/plugins/publish/extract_playblast.py
openpype/plugins/publish/extract_review.py

Before clique.assemble returns empty collections
Closes #2561
1. create single frame review in Maya
2. `ExtractPlayblast` nor `ExtractReview` should fail

Maya - added support for single frame playblast review

---

openpype/hosts/photoshop/plugins/create/workfile_creator.py

Modified Photoshop host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Photoshop is using query functions from `openpype.client` to get assets.
1. Run legacy workfile creator

Photoshop: Use client query functions

---

openpype/hosts/harmony/api/README.md
openpype/hosts/harmony/api/pipeline.py

Modified Harmony host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Harmony is using query functions from `openpype.client` to get representations when checking outdated containers.
1. Load "not last version" of representation to some workfile.
2. Open the workfile to trigger check of outdated containers.

Harmony: Use client query functions

---

openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py

`Submit to Deadline` failed with some workfiles.
Extracting too large url resulted in 'File not found' issue (side effect was that files in offending directory were skipped).
UNC path seems to help.

Harmony: added unc path to zifile command in Harmony

---

openpype/hosts/aftereffects/api/pipeline.py
openpype/hosts/aftereffects/plugins/create/workfile_creator.py
openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py

Modified AfterEffects host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
AfterEffects is using query functions from `openpype.client` to get assets. Function `get_asset_settings` expects asset document to be passed.
Function `get_asset_settings` is used only in plugin `ValidateSceneSettings` which always used asset from current context to get expected data which does not seem to make much sense? Shouldn't that plugin be context plugins instead of instance plugin? Or should it pass asset document from context data instead of instance data? Not sure if is possible to have multiple instances for different assets in afters...
1. Run legacy workfile creator
1. Run publishing (ideally with more complex scene with multiple instances)
2. Validate scene settings …

AfterEffects: Use client query functions

---

openpype/hosts/maya/api/lib.py

Vray has a different attribute name for device aspect ratio from other renderers.
(.aspectRatio instead of .deviceAspectRatio)
- open/create a maya scene with vray renderer set
- run OpenPype -> Set Resolution
resolution should be set without an error message about nonexistent vray attribute

Maya: vray device aspect ratio fix

---

openpype/hosts/maya/plugins/publish/extract_camera_alembic.py
openpype/hosts/maya/plugins/publish/extract_camera_mayaScene.py
openpype/hosts/maya/plugins/publish/validate_camera_contents.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json

This PR is releasing restrictions in camera extractors to allow more data to be published along with the camera. There is still validator that validates camera content and by default allows only camera to be passed down the line, but it can be set to allow more data. Usefull for proxy geometry / locators / pointcloud to be published with the camera.
in the Settings, there are new options for **Validate Camera Content** - `project_settings/maya/publish/ValidateCameraContents`. It can be disabled, it can be set as optional and also you can disable validating presence of shapes - in another words, disabling this option will allow more then cameras to pass this validator.
* Create camera instance and put for example box and camera under it
* Publish it with `Validate presence of shapes` …

Maya: Allow more data to be published along camera 🎥 

---

openpype/hosts/tvpaint/api/communication_server.py

Server process for TVPaint is not exiting properly and crashed on invalid return code sent to QApplication.
Make sure the exit code is set to not `None` on calling `_exit` in communicator.
1. Run openpype with console
2. Launch TVPaint - this should show console and TVPaint
3. Close TVPaint
4. The console should shut down

TVPaint: Make sure exit code is set to not None

---

openpype/hosts/maya/api/action.py
openpype/hosts/maya/api/commands.py
openpype/hosts/maya/api/lib.py
openpype/hosts/maya/api/setdress.py
openpype/hosts/maya/plugins/inventory/import_modelrender.py
openpype/hosts/maya/plugins/load/load_audio.py
openpype/hosts/maya/plugins/load/load_image_plane.py
openpype/hosts/maya/plugins/load/load_look.py
openpype/hosts/maya/plugins/load/load_vrayproxy.py
openpype/hosts/maya/plugins/publish/collect_review.py
openpype/hosts/maya/plugins/publish/validate_node_ids_in_database.py
openpype/hosts/maya/plugins/publish/validate_node_ids_related.py
openpype/hosts/maya/plugins/publish/validate_renderlayer_aovs.py

Modified Maya host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288). Also small tweaks in code related to using the functions which in some cases can make the process faster.
Use query functions from `openpype.client`. Some functions were modified to be able match to functions abilities or were enhanced by reducing queries. Most of places used during publishing are using `assetEntity` instead of querying it again by name.

Maya: Use client query functions

---

openpype/hosts/hiero/api/lib.py
openpype/hosts/hiero/api/tags.py
openpype/hosts/hiero/plugins/load/load_clip.py
openpype/hosts/hiero/plugins/publish_old_workflow/collect_assetbuilds.py

Modified Hiero host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Hiero is using query functions from `openpype.client` to get full hierarchy. Added some smaller tweaks to code.

Hiero: Use client query functions

---

openpype/plugins/publish/integrate_new.py

Representations filtering in `IntegrateAssetNew` happens as first step.
Representations were validated after subset and version creation and is not handled case when instance contains only representations that should not be integrated. Integration still fails if instance don't have any representations, but won't crash if none of those representations should not be integrated. Reset of `"transfers"` key on instance was moved to end of representations loop instead of at the start -> make sure that transfers end up with same values after each representation process.
Related to testing notes in [PR](https://github.com/pypeclub/OpenPype/pull/3355/files)
1. Publish instance which does not integrate any representation (e.g. review instance with only review representation)
2. IntegrateAssetNew …

General: Filter representations before integration start

---

pyproject.toml
website/docs/dev_requirements.md

This PR is linking newer version of OIIO for linux that is more self-contained.
It still needs **boost** (`sudo yum install boost-1.53.0` on centos 7) and **LibRaw** (`sudo yum install LibRaw`).

Linux: update OIIO package

---

openpype/hosts/nuke/plugins/load/load_model.py

Fix Nuke model loader to select all geo nodes in the hierarchy for loading by default
The current implementation only selects top level geo nodes form the hierarchy, this fixes it by always selecting all geo nodes
Nuke pops up the Hierarchy window during Alembic loading to show which geo nodes are selected for loading. To avoid this popup, you have to set the following in preferences:
```python
preferencesNode = nuke.toNode('preferences')
preferencesNode.knob('DfltAbcAlwaysCreateAllInOne').setValue(True)
```
We put this into Nuke's `init.py` in our pipeline, we didn't want to hardcode it in here.  Without it loading/version switching especially on multiple geo nodes is really annoying.  Maybe there's a more streamlined solution to avoid this window?

Nuke: Load full model hierarchy by default

---

openpype/hosts/nuke/plugins/publish/extract_render_local.py
openpype/hosts/nuke/plugins/publish/precollect_writes.py

Collect output frames based on Write node file input field instead of guessing based on files in output directory.
Using previous approach expected that output folder contains only output from current state of the write node but didn't handle previous renders with different frame range or different output extensions. New approach is using nuke api to collect all possible output files from write node based on it's current state by evaluating path with each possible frame.
This change fixed bug/removed feature - it is NOT possible that more frames is integrated then Write node has defined with frame start and frame end.
Example: Write node would render 1001-1010, but I could manually hit `Render Local` and render 999-1020. In that case were integrated frames 999-1020, that is not possible …

Nuke: Collect representation files based on Write

---

openpype/hosts/nuke/api/lib.py

Fixed keyword argument `repre_ids` -> `representation_ids`.
1. Open Nuke in some context
2. Create workfile (if is not created)
3. Load something into the scene
4. Open the file again so check if versions happens
5. It should not crash

Nuke: Fix keyword argument in query function

---

openpype/lib/path_tools.py
openpype/settings/defaults/project_settings/global.json

While keeping the previous operation of create_starting_folder, the project[name], project[code] and root[work..] keys can be used in project folder structure, for example:
```
{
"{root[work]}": {
"project[code]": {
"template": {}
}
}
```

Add root keys and project keys to create starting folder

---

website/docs/dev_build.md

Fixes `pyenv` typo that doesn't allow `$SHELL` to run
When following the install steps for macOS, 3rd step is to install `PyEnv`, on the second line, `echo 'eval "$(pypenv init -)"' >> ~/.zshrc` there's an extra 'p' in `pypenv init` that should be `pyenv init`.
This is a simple typo fix.

Fix typo in documentation: pyenv on mac

---

openpype/lib/path_tools.py

This little PR is fixing invalid avalon import in the code, preventing launch of Maya (and probably others)

Bug: fix invalid avalon import

---

openpype/client/entities.py
openpype/hosts/unreal/plugins/create/create_render.py
openpype/hosts/unreal/plugins/load/load_camera.py
openpype/hosts/unreal/plugins/load/load_layout.py
openpype/hosts/unreal/plugins/publish/extract_layout.py

Modified Unreal host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).
Unreal is using query functions from `openpype.client` to get versions.
1. Load Camera - try load camera
2. Load Layout - try load layout
3. Extract layout should work

Unreal: Use client query functions

---

openpype/hosts/blender/api/pipeline.py

Fix event callback on new/open to set fps and frame range properly.
See issue: `Blender 3.1+ don't set frame range and fps on open` -> https://github.com/pypeclub/OpenPype/issues/3424
- Just open a shot task with setted frameStar, frameEnd and fps in a Blender 3.1+ host.

Blender: Bugfix - Set fps properly on open

---

openpype/modules/log_viewer/tray/widgets.py

Messages with html tags are not shown as expected.
Escape html characters in log message so `<MyObject...>` is shown in UI.
1. Log to mogno must be enabled
2. Log something using OpenPype logger
- e.g. in Tray>Admin>Console
```
from openpype.lib.anatomy import log
log.info("<div>")
```
2. Open log viewer UI, find process where this log happened and check output which should show `"<div>"`.

LogViewer: Escape html characters in log message

---

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py

Hashing function used for tile rendering doesn't work in Python 3.
Use Maya with python 3 and publish tile job for rendering. It should submit to deadline ok.

Maya: fix hashing in Python 3 for tile rendering

---

openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
openpype/hosts/nuke/plugins/publish/precollect_writes.py

Slate frame is missing in representation files. It is primarilly caused by https://github.com/pypeclub/OpenPype/pull/3407 but the same issue could happen even before.
Add slate filename to representation files in Extract Slate.
I've used input with different frame range then write node frame range which caused that slate was not rendered at all (file was rendered but without slate content). Maybe we should force duplicated netflix gizmo to use frame we define as slate frame (e.g. prepend FrameRange/Retime node)?
1. Create render in Nuke
2. Add Netflix before the write node
3. Hit publish
+ Farm publishing (I didn't test it)

Nuke: Slate frame is integrated

---

openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
openpype/plugins/publish/extract_jpeg_exr.py

Prerender reviewable is functioning well
Prerender reviewable workflow was broken.
- `prerender.farm` had to be added to condition in extract review mov plugin.\
- thumbnail extractor on farm were not activated for  `prerender` family
1. make sure you have toggled ON `project_settings/nuke/create/CreateWritePrerender/reviewable` at your testing project.
2. create prerender node in your nuke testing node - Make sure prerender node is above of Slate node if you have any in the testing scene.
3. Test Review ON on the node with On farm rendering.

Nuke: prerender reviewable fails

---

openpype/hooks/pre_global_host_data.py
openpype/hosts/hiero/api/lib.py
openpype/hosts/houdini/vendor/husdoutputprocessors/avalon_uri_processor.py
openpype/hosts/maya/api/plugin.py
openpype/hosts/nuke/api/lib.py
openpype/hosts/tvpaint/plugins/load/load_workfile.py
openpype/hosts/unreal/api/rendering.py
openpype/hosts/unreal/plugins/publish/collect_render_instances.py
openpype/lib/applications.py
openpype/lib/avalon_context.py
openpype/lib/path_tools.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/ftrack/event_handlers_server/event_user_assigment.py
openpype/modules/ftrack/event_handlers_user/action_create_folders.py
openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
openpype/modules/ftrack/event_handlers_user/action_delivery.py
openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
openpype/modules/ftrack/event_handlers_user/action_rv.py
openpype/modules/ftrack/event_handlers_user/action_store_thumbnails_to_avalon.py
openpype/modules/sync_server/providers/local_drive.py
openpype/modules/sync_server/sync_server_module.py
openpype/pipeline/context_tools.py
openpype/pipeline/load/utils.py
openpype/plugins/load/delete_old_versions.py
openpype/plugins/load/delivery.py
openpype/plugins/publish/collect_anatomy_object.py
openpype/tools/loader/widgets.py
openpype/tools/texture_copy/app.py
openpype/tools/workfiles/files_widget.py

Changed imports of Anatomy to use `openpype.pipeline.anatomy.Anatomy` instead of `openpype.lib.anatomy.Anatomy`.
Import anatomy from `openpype.pipeline` at all current places to avoid deprecated warnings after [PR](https://github.com/pypeclub/OpenPype/pull/3435) (destination of this PR).

General: Use Anatomy after move to pipeline

---

openpype/modules/avalon_apps/rest_api.py

Rest api calls in avalon module use query functions instead of `AvalonMongoDB`.
Not sure if are the rest points used anywhere? Maybe we could removed them.
It should be possible to receive project documents using rest api points. Try access `http://localhost:8079/avalon/projects` when tray is running.

General: Use query functions in rest api calls

---

openpype/hosts/maya/plugins/load/load_vdb_to_redshift.py

Improves Redshift Volume VDB loader to actually support updating and removing + also support single file or multiple frames in a sequence
The Loader still loads the volume **without!** a material assigned by default. I was thinking of potentially auto-assigning a simple Volume Material but wasn't sure whether we wanted that in the same namespace + actually auto-remove that material when removing the volume as well.
For now you'll need to just manually assign the shader you'll want to render it with after loading the volume.
1. Load a VDB volume into Maya
---
Tested with Maya 2022 + Redshift 3.0.67

Maya: Redshift Volume Loader Implement update, remove, switch + fix vdb sequence support

---

openpype/plugins/load/delete_old_versions.py

The [Delete Old Versions](https://github.com/pypeclub/OpenPype/blob/a4b440d080a8a392aa26bf9e333baec20f735c9b/openpype/plugins/load/delete_old_versions.py#L375-L405) should use openpype.settings to get if **ftrack** module is enable and proceed ftrack logic only if needed.
see issue : Delete Old Versions relies on Ftrack session - #2801
1. Disable Ftrack in the OpenPYPE Studio settings
2. Use Loader tool to action **Delete Old Versions**
Resolves: https://github.com/pypeclub/OpenPype/issues/2801

General: Delete old versions is safer when ftrack is disabled

---

openpype/plugins/publish/extract_thumbnail.py

The extractor is bypassed to ffmpeg if oiiotool is failing
Oiiotool was failing on some version of CentOS that seems to not handle oiiotool correctly, so as a fallback we now use ffmpeg when oiiotool fails to do its conversion.
- also containing: https://github.com/pypeclub/OpenPype/pull/3455

General: thumbnail extractor fix

---

openpype/client/__init__.py
openpype/client/entities.py
openpype/plugins/load/delete_old_versions.py
openpype/plugins/load/delivery.py
openpype/plugins/publish/collect_anatomy_instance_data.py
openpype/plugins/publish/collect_avalon_entities.py
openpype/plugins/publish/collect_scene_loaded_versions.py
openpype/plugins/publish/extract_hierarchy_avalon.py
openpype/plugins/publish/integrate_hero_version.py
openpype/plugins/publish/integrate_new.py
openpype/plugins/publish/integrate_thumbnail.py
openpype/plugins/publish/validate_editorial_asset_name.py

Global plugins are using query functions.
Query from mongo is using get functions from `openpype.client`. Subsets can be queried on combination of asset id and subset names and added special function to query only archived representations. Finding of last version does not do double query if only `_id`, `name` or `parent` are requested. Fixed typo in client `artchived_representations` -> `artchived_representation`.
- Editorial

General: Use query functions in global plugins

---

openpype/hosts/aftereffects/plugins/create/create_render.py
openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py

Change order of creator init arguments to have most used project settings as first to less important arguments as last.
In most of cases when creator want to override initialization it's because of using project settings thus it's better to have it as first argument, then system settings and then what is probably not used in custom init just to be passed to super init.
Breaks backwards compatibility. So this should be done now before new publisher is used in all hosts.
Order was change from most used to less used arguments.
```
def __init__(self, create_context, system_settings, project_settings, headless=False):
def __init__(self, project_settings, system_settings, create_context, headless=False):
def __init__(self, create_context, system_settings, project_settings, *args, **kwargs): …
```

General: Better arguments order in creator init

---

openpype/hosts/resolve/api/lib.py
openpype/hosts/resolve/api/plugin.py
openpype/hosts/resolve/plugins/create/create_shot_clip.py
openpype/hosts/resolve/plugins/load/load_clip.py
openpype/hosts/resolve/plugins/publish/precollect_workfile.py

Buggs were blocking publishing and creating.
- precollect workfile needed to add families attribute to instance.data
- clearing code
- loading was not working for mov files

Resolve: removed few bugs

---

openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py

Creator plugins in new creation have access to project name.
In same cases need access to project name during creation which is not possible right now. Project name is traversed from CreateContext which initialized plugin objects.

General: Creator Plugins have access to project

---

openpype/tools/publisher/widgets/create_dialog.py

It is possible to hit create for creators which do not require context selection.
Creator plugins could define if want to allow context selection but UI did not support to hit Create button if it's so. In that case asset name, task name and subset name are set to `None` because context which would be used to fill subset name are not enabled.
This kind of creation make sense only for bulk creators which have to get asset, task and subset name from elsewhere during creation. Added sorting of create plugins based on label. Converted few attributes to be private.
1. Add plugin that define to disable context selection on creation
2. Create button should be enabled in that case

New Publisher: Disabled context change allows creation

---

openpype/pipeline/create/context.py
openpype/tools/publisher/widgets/card_view_widgets.py
openpype/tools/publisher/widgets/list_view_widgets.py

Instance can have defined label in it's data which is shown in instances view.
Previously instance used only subset name of instance which makes it complicated when instances are created in bulk for multiple different contexts so each has same name. If label is not available then subset name is used as fallback.
To use label just pass `"label"` to instance data of `CreatedInstance`.
1. Create instance which has `"label"` key in data
2. Label should be visible in create UI

NewPublisher: Added ability to use label of instance

---

openpype/tools/publisher/widgets/widgets.py

Align attribute definition widgets from top to bottom instead of keeping them in center.
Change alignment on main layout in attributes defininition widget.
1. Create an instanace in new publisher (for which creator define attribute definitions or has some values)
2. Select created instance in instances view
3. Check if creator attribute are alignet from top to bottom

NewPublisher: Align creator attributes from top to bottom

---

openpype/plugins/publish/extract_review.py

Fixed issue when output frame start does not match input frame range when sequence is used as input.
We tell ffmpeg which is the first frame of an input sequence but we used output frame start to define it. But output frame start could be different. Thus first frame of an sequence is used. There may be caviads when handles should be used. I've tried to "guess" it but not sure if it will cover all usages.
This was discovered with AfterEffects which store frame start/end from scene into instance data `frameStart` and `frameEnd`. I'm not sure if we should store scene data there, but the keys probably don't have any defined usage.
Trigger publishing which creates sequences that should be processed by extract review.
- I know about AfterEffects, TVPaint, Maya on farm and standalone publisher

General: Extract review use first frame of input sequence

---

openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py
openpype/tools/publisher/widgets/card_view_widgets.py
openpype/tools/publisher/widgets/list_view_widgets.py

Grouping of instances has much more abilities. Instances can have their own group defined in data and creator plugin can define it's group label. This is just UI purpose change.
Group label is defined by this order (if value is empty then next value is used):
- key `"group"` in created instance data
- attribute `group_label` on creator plugin
- attribute `label` on creator plugin
- attribute `identifier` on creator plugin
Identifier must be available on creator plugin so it is end point. Default implementation returns creator's `family` which can be considered as last source.
Creators group label
1. Define `group_label` on creator plugin and create it's instances
2. They should be grouped under that label
Instance group label
1. Create an instance with some string in `"group"` key in it's …

TrayPublisher: Added more options for grouping of instances

---

openpype/lib/applications.py

Use `plist.load` instead of `plist.readPlist` which seems to be deprecated.
Kept both access for cases when `load` function is not available (bust should be always).
1. Launch application on MacOs
2. Application should be launched

General: Fix Plist loading for application launch

---

openpype/settings/defaults/project_settings/traypublisher.json

This move all the families that don't require a custom collector from standalone publisher to the new Tray publisher GUI. This is a first step in getting rid of the old standalone publisher.
Testing should be as easy as running the tray publisher from the OpenPype tray menu and trying to publish some families that are available by default. 
This is really just a change in the default settings, to have some reasonable defaults.

Migrate basic families to the new Tray Publisher

---

openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py

Trigger custom ftrack topic with project name in event data on triggering or create project structure action.
Topic triggered on finish is `openpype.project.structure.created` which can be listened to and trigger custom callback when finishes. This may have usage for example for customuzation of permissions on first folder structure creation.
This change require to have custom code implemented.
```
import ftrack_api
def my_callback(event):
print("Project structure was created on project {}".format(
event["data"]["project_name"]))
if __name__ == "__main__":
ftrack_url = "https://<your domain>.ftrackapp.com"
ftrack_api_key = "<ftrack api key>"
ftrack_username = "<ftrack username>"
session = ftrack_api.Session(
ftrack_url,
ftrack_api_key,
ftrack_username,
auto_connect_event_hub=True
) …
```

Ftrack: Trigger custom ftrack topic of project structure creation

---

openpype/hosts/traypublisher/api/__init__.py
openpype/hosts/traypublisher/api/pipeline.py
openpype/hosts/traypublisher/api/plugin.py
openpype/pipeline/create/creator_plugins.py
openpype/tools/traypublisher/window.py

Converted Tray Publisher to host inheriting from HostBase which makes sure `AVALON_APP` is filled.
Make sure `AVALON_APP` is filled in both environment and legacy io session. Tray publisher is using `HostBase` as source for implementation. Traypublisher creator has helper method to store new instance. Creators have access to host.
1. AVALON_APP should be available in both environments and legacy_io.Session during publishing
Resovles https://github.com/pypeclub/OpenPype/issues/3500

TrayPublisher: Make sure host name is filled

---

openpype/pipeline/create/context.py
openpype/tools/publisher/control.py
openpype/tools/publisher/publish_report_viewer/report_items.py

Add plugins that don't have matching targets to publish report so we have available all loaded plugins.
Filtered plugins are marked as skipped so they are visible in the report view. The main reason is confusion that plugin is not visible in view and is not in crashed plugin paths.
1. Run validation in new publisher
2. Go to report view
3. Unhide skipped plugins
4. You should see plugins that were skipped because if mismatched targets

NewPublisher: Keep plugins with mismatch target in report

---

openpype/hosts/nuke/plugins/load/load_clip.py
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_load.json

Loading of options can be set in settings.
In case production needs to set loading options for all retimed plates to ignore retime settings, this can be now done from settings.
1. open nuke workfile
2. make sure you are having some retimed plate to load - ideally more that one version.
3. Load first older version with option set to add_retime to False
4. Update to latest version
5. It should load first read node without retime node connected to it, and then during update it should just update the read node without retime nodes.

Nuke: load clip with options from settings

---

pyproject.toml

Fixed hash of centos oiio archive.
1. Fetch 3rd party libraries on centos

General: Fix hash of centos oiio archive

---

openpype/modules/ftrack/event_handlers_server/action_create_review_session.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

It is possible to define in which time automated creation of daily review session happens.
The time definition is in project settings but can't be set per project and the change of time in settings take effect on next day or on restart of event server.
1. Enable `project_settings/ftrack/events/create_daily_review_session/cycle_enabled`
2. Change `project_settings/ftrack/events/create_daily_review_session/cycle_hour_start` to trigger automated creation at your time (would recommend +5 minutes from current tim)
3. Run ftrack event server
4. Wait until that time
5. Daily review session should be created

Ftrack: Automatic daily review session creation can define trigger hour

---

openpype/vendor/python/common/capture.py

Logs and captures exception when attribute is not possible to set (when locked).
Next paragraf is more elaborate text with more info. This will be displayed for example in collapsed form under the first sentence in a changelog.
This is temporary hotfix, in the future decorator should be implemented, which will try to store old value, unlock attribute, set new, reset old one back and lock again. In that case new wrapper method could be as a base of decorator.
1. create Review subset in Maya
2. lock some attribute on Camera shape (I tried `Depth of Field`)
3. Thumbnail nor Extract Playblast should fail

Maya: Added wrapper around cmds.setAttr

---

openpype/plugins/publish/extract_thumbnail.py

Used global plugin for thumbnail extraction even in Traypublisher
Added check if thumbnail representation is not present, created by different plugin by any chance.
ExtractThumbnailSP should be removed when SP is removed, no need to copy and have 2 plugins.
1. try publish render with TrayPublisher
2. it should create thumbnail in publish folder

Traypublisher: added thumbnail extract 

---

.gitmodules
tools/build.ps1
tools/build_win_installer.ps1
tools/create_env.ps1
tools/create_zip.ps1
tools/fetch_thirdparty_libs.ps1
tools/make_docs.ps1
tools/run_mongo.ps1
tools/run_project_manager.ps1
tools/run_settings.ps1
tools/run_tests.ps1
tools/run_tray.ps1

This is moving powershell modules to tools so it is not pulled to build. It is also silencing exception put there by BurnToast when run on system (CI) where toasts cannot be displayed.

Additional fixes for powershell scripts

---

openpype/cli.py
openpype/pype_commands.py
website/docs/admin_openpype_commands.md

Added ability to run interactive console through OpenPype cli.
Added new cli command `interactive` which will launch OpenPype and start interactive session like when python executable does. This may be helpful for development or debuging purposes.
This does not work on windows when `openpype_gui.exe` executable is used. That's because the executable disable stdin, stdout and stderr so there is no way how it could start in "interactive" mode.
1. Run `./openpype_console interactive` (from code: `poetry run python "./start.py" interactive`)
2. Try to write some code like in python interpreter

General: Interactive console in cli

---

openpype/hosts/maya/api/lib_renderproducts.py

Imagine you have two displays in a scene - `beauty` and let say `mattes`. In the `beauty`, there are channels `Z`, `Env`, `id` (and of course `Ci` and `a`) and in the `mattes` there are `foo`, `bar`, `baz`:
```
beauty
|- Z
|- Env
\- id
mattes
|- foo
|- bar
\- baz
```
publishing **without** prior IPR render will result correctly in two displays (and two expected sequences) for example `Layer_beauty.####.exr` and `Layer_mattes.####.exr`. 
But when you do the IPR before publishing, Renderman will breakout existing displays (`beauty` and `mattes`) into `beauty_Z`, `beauty_Env`, `beauty__id` and similar with mattes - `mattes_foo`, `mattes_bar`, `mattes_baz`.
is to force rfm to output only displays for render destination (not all - viewport/it/driver). This PR is doing exactly this, plus adding …

Maya: Renderman display output fix

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/api/pipeline.py
openpype/tools/utils/host_tools.py
openpype/tools/workfiles/window.py

Change is related to showing workfiles tool on launch in Nuke. On some linux distributions is workfiles tool hidden under main nuke window and has issues with reshowing it correctly.
Workfiles tool has ability to change `AlwaysOnTop` window flag on show. This has some other issues but all are less affecting then hidden workfiles tool. Workfiles tool is not also `QMainWindow` but `QWidget` with `Window` flag and nuke does not pass parent widget to initialization of workfiles tool. This cause that workfiles tool is showed as separate window from nuke window and at the same time is fixing bugs related to re-opening the tool.
Change of window flags is not always supported so on some OS distribution it can cause that the workfiles tool window will stay always on top. That will happen only if …

Workfiles tool: Show of tool and it's flags

---

openpype/modules/kitsu/utils/update_op_with_zou.py

All assets are put under an `AssetType` folder in the tree for a better readability in classification.

Change: Asset is put under an AssetType folder

---

openpype/modules/kitsu/utils/update_op_with_zou.py

shot name with parents hierarchy `({episode}_){sequence}_{shot}` to avoid duplicate name issue

Fix: shot duplicate name using shot's hierarchy (ep, seq)

---

openpype/modules/base.py

OpenPype interfaces are raising `AttributeError` instead of `ImportError` when some attribute is missing.
Import error should be raised by Python interpreter when attribute is not available which we're by passing. 
```
import openpype_interfaces
some = getattr(openpype_interfaces, "something")
missing = getattr(openpype_interfaces, "missing", None)
```
This code snipped should not crash but print "None"
```
import openpype_interfaces
result = getattr(openpype_interfaces, "missing", None)
print(result)
```
At the same time this should cause `ImportError`
```
from openpype_interfaces import missing
```
Resolves https://github.com/pypeclub/OpenPype/issues/3541

Module interfaces: Fix import error

---

openpype/settings/defaults/system_settings/general.json

Removed unused metadata values from default environments settings.
Default values of environments settings contain metadata values that are not used anymore.
1. Nothing should change really

Settings: Clean default values of environments

---

openpype/hosts/maya/plugins/publish/validate_review_subset_uniqueness.py
openpype/hosts/maya/plugins/publish/validate_setdress_root.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json

With this PR all Maya validators that are more or less safe to disable/enable are added to the Settings.
It is difficult to test, but the state of the validators should be the same as before. They show up in the Settings, where they can be configured (enabled/optional/active)

Maya: add additional validators to Settings

---

openpype/hosts/harmony/api/pipeline.py
openpype/hosts/harmony/plugins/publish/validate_scene_settings.py
openpype/hosts/hiero/api/plugin.py
openpype/hosts/houdini/api/lib.py
openpype/hosts/maya/api/lib.py
openpype/hosts/maya/plugins/create/create_render.py
openpype/hosts/maya/plugins/publish/validate_maya_units.py
openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/plugins/publish/validate_script.py
openpype/hosts/resolve/api/plugin.py
openpype/hosts/standalonepublisher/plugins/publish/collect_editorial.py
openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py
openpype/hosts/unreal/plugins/load/load_animation.py
openpype/hosts/unreal/plugins/load/load_layout.py
openpype/lib/avalon_context.py
openpype/pipeline/context_tools.py

Moved function `get_asset` from `openpype.lib.avalon_context` into `openpype.pipeline.context_tools` and renamed to `get_current_project_asset`. Also was added function `get_current_project` to receive current project document.
Function in `openpype.lib` was marked as deprecated and internally is calling the new function in context tools. New function has extended arguments with ability to pass asset id and define fields that will be returned.
At some places there is possibility to use different source for asset documents, e.g. during publishing should be asset documents already available on instance or context (marked with TODO).
Hosts should work as before:
- validation of scene settings (workfile publishing)
- clip loader
- fps should be set correctly based on asset data
- scene …

General: Get current context document functions

---

openpype/plugins/publish/integrate.py
openpype/plugins/publish/integrate_legacy.py

Removed hosts filters from integrator plugins.
Integrators accidentaly kept hosts filters that should not be there.
1. Integration should work in all hosts

General: Remove hosts filter on integrator plugins

---

openpype/hosts/nuke/plugins/publish/precollect_instances.py
openpype/plugins/publish/integrate.py

Removing exclude family filter
New integrator doesn't need exclude family filter anymore. 
In nuke we had to add `farm` key collector to instance data - this is for Integrator to exclude it from its processing.
Test in Nuke by submitting render family subset to farm. It should work normally

General: Integrator exclude farm removal

---

openpype/hosts/maya/plugins/publish/extract_playblast.py
openpype/hosts/maya/plugins/publish/extract_thumbnail.py

This little PR is fixing situation when ative pane is lost during applying capturing presets in Maya, resulting in crash of `extract_playblast` and `extract_thumbnail` plugins.
Publishing of review playblast from Maya should work as expected.

Maya: fix active pane loss

---

openpype/tools/publisher/publish_report_viewer/model.py
openpype/tools/publisher/widgets/card_view_widgets.py
openpype/tools/publisher/widgets/list_view_widgets.py
openpype/tools/utils/lib.py

Escape of html syntax symbols is implemented in openpype instead of using Python 3 module.
We've used Python 3 module `html` for escaping of html symbols which is not available in Python 2 hosts. Thus we needed to add that option for them too. The basic escaping is easy to implement and does not need special python module for that so a function was added.
1. Open NewPublisher in host with Python 2
2. UI should show their labels and not crash
Resolves https://github.com/pypeclub/OpenPype/issues/3558

NewPublisher: Python 2 compatible html escape

---

openpype/client/__init__.py
openpype/client/entities.py
openpype/client/mongo.py
openpype/hosts/maya/api/shader_definition_editor.py
openpype/hosts/maya/plugins/publish/validate_model_name.py
openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
openpype/hosts/webpublisher/webserver_service/webserver_cli.py
openpype/lib/local_settings.py
openpype/lib/log.py
openpype/lib/mongo.py
openpype/lib/remote_publish.py
openpype/modules/ftrack/ftrack_server/event_server_cli.py
openpype/modules/ftrack/ftrack_server/lib.py
openpype/modules/ftrack/scripts/sub_event_storer.py
openpype/modules/slack/plugins/publish/integrate_slack_api.py
openpype/pipeline/mongodb.py
openpype/settings/handlers.py

Moved core of Mongo connection `OpenPypeMongoConnection` from `openpype.lib` into `openpype.client`. This change makes `openpype.client` independent from openpype lib functions and can be considered as self contained.
Changed parts of code using `OpenPypeMongoConnection` to use new source and marked lib functions as deprecated. That is unfortunatelly not possible for classes located there too.

General: Mongo core connection moved to client

---

openpype/plugins/publish/extract_thumbnail.py

It seems that only adding `traypublisher` to global thumbnail extractor is not enough. There are few issues related to the plugin which was not prepared to be used elsewhere then on farm.
Added or modified preflight checks. First check is if instance have representations and skip when not. Instance check for review and already existing thumbnail were moved earlier. Thumbnail representation has staging in temp rather then reuse source staging, that is because if input is `.jpg` it is just replaced so source is "replaced" (happend to my jpg sequence - not fun in production). Limited creation of thumbnail into 2 conditions and the creation of thumbnail is tried on all representations that can be used for that (if first crashes it will try create it from next). Added few logs.
- We could …

General: Global thumbnail extractor is ready for more cases

---

openpype/plugins/publish/integrate.py

New integrator plugin is using query functions from `openpype.client`.
Integrator PR was created before query functions were available (legacy integrator is already using them).
1. New integrator should work as did before but is using query functions

General: Use query functions in integrator

---

openpype/settings/defaults/system_settings/modules.json
start.py

Use new imports and names of classes in `start.py` and fixed missing default settings.
Use `get_default_components` from `openpype.client.mongo` instead of `openpype.lib.mongo` and try to use class `Logger` instead of `PypeLogger`.
1. Start of OpenPype should not crash and there should not be deprecated warnings
2. Missing default settings should not popup

General: Update imports in start script

---

openpype/hosts/nuke/api/plugin.py
openpype/hosts/nuke/plugins/publish/collect_slate_node.py
openpype/hosts/nuke/plugins/publish/extract_render_local.py
openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py

Range is correct when published slate from existing frames
The miscalculation was removed.
1. open nuke workfile with slate workflow
2. publish from existing frames
3. notice that frame range is correct and not frame shorter

Nuke: publish existing frames with slate with correct range

---

openpype/hosts/nuke/plugins/publish/extract_render_local.py
openpype/hosts/nuke/plugins/publish/precollect_instances.py
openpype/hosts/nuke/plugins/publish/precollect_writes.py

Families are integrating to the same family from any render target.
Any chosen render target should now produce the same result in published folder.
Integrator is using `anatomyData` keys for filling up templates and choosing what template to use from Anatomy. So family has to be correct.
1. Nuke render local, farm, existing frames from render and prerender node
2. published versions should be the same family
closes https://github.com/pypeclub/OpenPype/issues/3568

Nuke: render family integration consistency 

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

Ftrack integrator can handle if `published_path` is not filled on representation.
Ftrack integrator expected that `published_path` is always filled on representation for review and thumbnail upload, but in some very specifici cases they may not be integrated with `IntegrateAsset` thus they don't have filled the key at all. But in that cases can be used their source path.
Before this PR it crashed with `KeyError`.
```
File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
runner(*args)
File "C:\Program Files (x86)\OpenPype\openpype\modules\ftrack\plugins\publish\integrate_ftrack_instances.py", line 273, in process
KeyError: 'published_path'
```
Not sure how it is possible to make reviewable that is not …

Ftrack: Handle missing published path in integrator

---

openpype/plugins/publish/integrate.py

Fixed few smaller issues in integrator and cleaned up code and comments.
Minimum frame padding is defined by last frame of sequence instead of first frame (999 vs. 1000). Frame padding fom anatomy template is always considered when `frame` should be filled. Replaced `AssertionError`s with `KnownPublishError`. Added `"output"` to representation context keys and removed explicit set of it at the end. Make sure that representation context has filled first frame during sequence processing. Removed comments marking logic as backwards compatibility which is still fully required and does not have any replacement.
- Integration should work
- Integrated representation filenames should at all costs have filled frame with padding from anatomy templates or lenght of last frame (in case anatomy …

General: New Integrator small fixes

---

openpype/modules/ftrack/ftrack_server/lib.py
poetry.lock
pyproject.toml

Update python ftrack api to 2.3.3.
Updated to newer version. This change required few small changes in code to work as did. It should work with both newer and older version. Also updated certifi.
1. Ftrack publishing should work
2. Ftrack event server should run ok (both server and user side)

Ftrack: Update ftrack api to 2.3.3

---

openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
openpype/hosts/hiero/plugins/publish/precollect_instances.py
openpype/hosts/resolve/plugins/publish/precollect_instances.py
openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
openpype/plugins/publish/extract_hierarchy_avalon.py
openpype/plugins/publish/integrate.py
openpype/plugins/publish/validate_asset_docs.py

Editorial instances are not failing due missing assetEntity
Editorial workflow was missing instance data flag telling validator and integrators they should be treated with missing asset entity, since this is created during publishing and is not available at the time of collecting phase.
global, flame, hiero, resolve, sp: implementing `newAssetPublishing`

Editorial publishing workflow improvements

---

poetry.lock
pyproject.toml

Appdirs should work in any python build.
Appdirs module is in release using `pywin32` module but that may crash if is compiled for different python which is not handled properly in the module. That is not in `release` branch but not in `master` which should work the same way even wihout `pywin32`.
1. Update from version repository should work
2. Local machine name should be loaded
3. ..all other logic using appdirs should work too

General: Python module appdirs from git

---

openpype/modules/kitsu/utils/update_op_with_zou.py

Every time the sync is processed, the name of `Shot` and `Sequence` assets is prefixed by the parent's name, which make the name longer and longer...

Kitsu: Shot&Sequence name with prefix over appends

---

start.py

Fix how variables are resolved in general settings. This will now allow to define new variables and resolve them in one pass.
For example:
```
{
"FOO": "something",
"BAR": ["{FOO}", "else"]
}
```
will now resolve correctly. This was crashing OpenPype on start.
Resolves #3585

Fix general settings environment variables resolution

---

.gitmodules
openpype/hosts/maya/plugins/publish/extract_look.py

`maketx` executable requires an `OCIO` config file path appended when using the `--colorconfig` flag.  This resolves #3584 and prepares for preventing `maketx` from crashing when publishing OpenPype `Look` instances.
Adding OCIO as a submodule and adding functionality to grab the OCIO config file path based on a profile folder parameter as the function argument.
Testing: 
1. Create some geo and OP model instance.
2. Publish it.
3. load model instance in.
4. Create shader, apply a test base color texture (that's in sRGB).
5. publish it. 
The publishing should produce a `.tx` file that's optimized for `MtoA`. (Make sure create .tx is enabled in the look creator)

Bugfix: Add OCIO as submodule to prepare for handling `maketx` color space conversion.

---

openpype/hosts/maya/plugins/create/create_animation.py
openpype/hosts/maya/plugins/create/create_pointcache.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json

Add the switching on/off option for write color sets in Create Cache in Openpype settings
Add the switching on/off option for write color sets in Create Cache in Openpype settings, which overrides the write color sets attributes in maya when creating point cache instance for the geometry. 
It is implemented for being consistent regarding to the same implementation of switching on/off options in Create Animation for maya.

Enable write color sets on animation publish automatically

---

openpype/modules/kitsu/plugins/publish/collect_kitsu_entities.py

Fix #3552
Some Python3 syntax was added in the `collect_kitsu_entities.py` file, leading Python2 softwares to fail.

Kitsu|Fix: Collect entities error cause of Python2

---

openpype/hosts/blender/api/ops.py

Bring back the Workfile Dialog in Blender Host since this commit: https://github.com/pypeclub/OpenPype/commit/55ff302d21a49b13281972129a944adcb998bf89 
see issue : https://github.com/pypeclub/OpenPype/issues/3592
1. Start with a task in Blender.
2. Open the workfiles dialog -> should now appear.

Blender: bugfix blender.api.ops for workfiles dialog

---

openpype/hosts/traypublisher/api/plugin.py
openpype/hosts/traypublisher/plugins/create/create_editorial.py

Tray publisher creator is missing `_store_new_instance` which was appended after new `HiddenCreator`.
Added `_store_new_instance` into tray publisher creator. Use `_store_new_instance` in editorial creators -> removed usage of `HostContext`.
1. Simple creators should work
2. Editorial should work

TrayPublisher: Fix wrong conflict merge

---

openpype/plugins/publish/integrate.py

Creation of collection in new integrator does not require to have frame starting with dot.
It is not forced to use determined frame pattern in clique assemble. It seems to be added to support single file sequence which is not supported across multiple plugins so it's pointless and breaks a lot of current extractors output (or publish templates). Output sequence is created using anatomy format for each frame/udim.
It was discovered in TVPaint but it is also issue for AfterEffects.
Resolves https://github.com/pypeclub/OpenPype/issues/3608

Integrator: Don't force to have dot before frame

---

openpype/lib/__init__.py
openpype/lib/transcoding.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/plugins/publish/extract_review.py

Add more metadata to ftrack components even for those which are not for review.
Add fps, width, height to components that can potentially be able to use it in CineCync. To achieve that I'm using ffprobe to read information about published path. If ffprobe crashes the component won't have any metadata otherwise fps (or `frameRate` is added.
Fixed issue when there are both `ftrackreview-mp4` and `ftrackreview-image` which could cause the thumbnail is showed in play instead of video. When both are available the `ftrackreview-image` is renamed to thumbnail.
We have no information about representation, is it an image or video with width, height and fps and sometimes when the information is there it is sometimes copied from source representation which changed so the data are not relevant.
1. …

Ftrack: Add more metadata to ftrack components

---

openpype/plugins/publish/help/validate_containers.xml
openpype/plugins/publish/validate_containers.py

`Validate Containers` could now be used in New Publisher as a optional plugin.
First sentence is brief description.
AE could be already using NP.
1. Try to publish in AE with New Publisher in the scene with obsolete loaded containers.

Core: translated validate_containers.py into New publisher style

---

openpype/hosts/maya/plugins/publish/collect_look.py
openpype/hosts/maya/plugins/publish/validate_look_contents.py

Solving the failure of validating look data contents when custom attributes are set up on group
Set up the condition to tell the relative validating scripts to exclude the nodes with custom attributes from the invalid list, when the system is checking if the attributes are on nodes with IDs.

Maya look data contents fails with custom attribute on group

---

openpype/modules/kitsu/utils/update_op_with_zou.py

In Kitsu, you can assign task types to a Project. If none are assigned, the project takes all existing tasks as default. 
In OP, it doesn't behaves like that, it could assign an empty tasks list, which is not correct.
This fixes it.

Kitsu: Project with no dedicated task types use defaults

---

openpype/lib/path_templates.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
openpype/settings/defaults/system_settings/modules.json
openpype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
openpype/tools/pyblish_pype/model.py
openpype/tools/pyblish_pype/window.py

Reduced empty notes and descriptions during publishing when integrating to ftrack, intent can be nullable and `StringTemplate` support to keep less/greater symbols if don't contain any formatting `<...>` (`<br/>` is kept unchanged).
The main issue is that templates in most of cases consist from `{intent}: {comment}` which cause that result is `{-: }`. One reason is that intent can't be empty at this moment so it's filled with other symbol (e.g. `"-"`) and we're unable to know which part should be skipped if value is missing.
Intent can have nullable option so studio can tell that empty intent is possible and we can handle it in some way during publishing.
`StringTemplate` support to keep less/greater symbols if they do not contain any formatting. That is important for ftrack integrate …

Ftrack: Comment template can contain optional keys

---

igniter/bootstrap_repos.py
igniter/tools.py
openpype/cli.py
openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py
openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.param
openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.py
setup.py
start.py
tools/build.sh
tools/create_zip.py

This PR is adding support for multiple installed versions (builds) on the same system. It will allow easy rollback and testing on farms and without disrupting existing running sessions.
On Deadline, it is now passing OpenPype version as `OPENPYPE_VERSION` to the job. If this environment variable is found on the job, Deadline will try to find compatible version build to use for launching that version of OpenPype. So if job was submitted from OpenPype version `3.12.2` Deadline will try to find any build that matches `3.12` and will use the latest available. Deadline will try to find it in directories specified in `OpenPypeInstallationDirs` configuration option.
It relies on functionality implemented here #3445.
Since #3445 you can have multiple versions of OpenPype installed on Windows. …

Support for mutliple installed versions - 3.13

---

openpype/lib/remote_publish.py
openpype/pype_commands.py
openpype/settings/defaults/project_settings/webpublisher.json
openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json

Introduced configurable timeout for PS studio processing jobs.
Sometimes publishing job could get stuck on Photoshop side because some dialog requiring user interaction. This should limit that and kill the process.
In the code 1 hour limit is hardcoded if no configuration is found.
1. Configure some small timeout in `project_settings/webpublisher/timeout_profiles`
2. Run studio processing job in PS that triggers user dialog

Webpublisher: timeout for PS studio processing

---

openpype/settings/defaults/project_settings/maya.json
openpype/settings/defaults/project_settings/traypublisher.json

Default settings for maya RenderSettings use list instead of dictionary which is defined in settings schemas.
Resaved default settings using settings UI which reorganized formatting of few lines in default settings and fixed wrong types.
I hope nothing should change.

Maya: Fix types of default settings

---

tools/build_dependencies.py

This is fixing build issues on mac with multiple versions feature introduced by #3605. It is adding properly version string to mac specific paths.

Fix for multi-version build on Mac

---

openpype/plugins/publish/extract_review.py

Ratio scaling calculations happens in ffmpeg instead of our python code.
It happened that `1080` after python float calculations becomes `1081` which cause a lot of troubles. The main reason why we did that was to keep aspect ratio but ffmpeg scale has `force_original_aspect_ratio` option which keep ration by decreasin or increasing (in our case decreasing) and calculate padding difference in ffmpeg too.
This is huge change and should be tested properly. Changes affect cases when scale is needed and when input and output have different aspect ratio (scale is needed).
Force extract review to output a video which has different aspect ratio (visible with an eye) then converted input. The output should have right resolution and should be padded the right way.

General: Extract review aspect ratio scale is calculated by ffmpeg

---

openpype/lib/plugin_tools.py
openpype/pipeline/context_tools.py
openpype/pipeline/create/creator_plugins.py
openpype/pipeline/create/legacy_create.py
openpype/pipeline/load/plugins.py
openpype/pipeline/publish/lib.py
openpype/tools/loader/widgets.py

Loader and creator settings are handled by plugins.
`LoaderPlugin` and `LegacyCreator` have new classmethod `apply_settings` which by default contains logic from `openpype.lib.set_plugin_attributes_from_settings`. 
Function `filter_pyblish_plugins` which apply settings for pyblish plugins was moved to `openpype.pipeline.publish.lib`. For pyblish plugins was added ability to implement classmethod `def apply_settings(cls, project_settings, system_settings)` too. Can customize how settings are applied on a plugin. This is optional. If method is not implemented the "automated" approach is used as before - this option was added to be able handle some cases when path location of plugin does not exactly match settings path. Functions in lib were marked as deprecated.
1. Settings on loader …

General: Plugin settings handled by plugins

---

openpype/hosts/maya/api/lib_renderproducts.py
openpype/hosts/maya/plugins/publish/collect_render.py

Getting AOV separator for Redshift breaks render layer collection. This is fixing it, using the same default logic even for Redshift.

Maya:  fix aov separator in Redshift

---

openpype/client/entities.py

This fixes `get_output_link_versions` query.
Now it search for `data.inputLinks.id` instead of `data.inputLinks.input`
With this change the Outputs in the Loader are now also correctly shown:
Note: The old logic is likely due to how the ids were stored previously. So we might want to add backwards compatibility similar to [how the SimpleLinkView does for inputs here](https://github.com/pypeclub/OpenPype/blob/a04840eadfc7e0be3d69e7a0c2dd13bd9109393b/openpype/tools/assetlinks/widgets.py#L64-L68).
Or if that "old style" is **ancient legacy** we can also remove the backwards compatibility there and only consider entries with `id` data present for inputs.
---
This will be a useful fix once #3629 is merged as well. It'll allow you to trace easily from a specific version in what publishes it's …

Refactor `get_output_link_versions` to query id instead of input

---

openpype/modules/kitsu/utils/update_op_with_zou.py

1. Movie Kitsu project types (Short and Film) crash because `Sequence` type has no parent for these types and sync expect them too (based on TV Show system) -> Had to make sure parent is not None.
Fix #3635
1. Shots and Sequences names are not built with parents hierarchy names at very first loop. -> Had to update the name of the item in the in-memory stored doc.

Kitsu|Fix: Movie project type fails & first loop children names

---

openpype/hosts/maya/api/plugin.py

Fixes a problem with Maya for which it is impossible to set hero version for Unreal Static Meshes.
It happens because Unreal Static Meshes are FBXs, and the FBX format was unsupported in the update function of the Reference Loader.
1. Publish a model as Unreal Static Mesh with hero version enabled for the `staticMesh` family.
2. Load the model as hero version *or* change to hero version for a loaded Static Mesh.

Maya: FBX support for update in reference loader

---

openpype/plugins/publish/integrate_hero_version.py

Add all keys from anatomy data to representation context even if it's already there.
Integrate hero versions skipped reusing of anatomy data values in repre context if the key was already there but e.g. for `project` or `task` the key can be there but not all subkeys were used. Was found out because project name was filled but project code was missing in representation context.
1. Publish hero version which does not use project code in templates
2. Check DB if representations contain project code in `context`

General: Hero version representations have full context

---

openpype/tools/sceneinventory/view.py

Scene Inventory actions allows to change the selection in the UI. That functionality however was broken and is fixed with this PR.
To test, here's an example Action that selects all containers of which the subsets belong to subset group `Deprecated`:
```python
from collections import defaultdict
from bson.objectid import ObjectId
from openpype.pipeline import InventoryAction, legacy_io
from openpype.client import get_representations, get_versions, get_subsets
def _by_id(docs):
return {str(doc["_id"]): doc for doc in docs}
class CheckDeprecated(InventoryAction):
"""Select all containers that are 'Deprecated'
Whenever a subset is added to a group named 'Deprecated' then this will
identify those containers in the Scene Inventory and select them.
"""
label = "Select deprecated"
icon = …
```

Scene Inventory: Fix allow actions to change selection

---

openpype/hosts/nuke/api/lib.py

Getting correct settings for write node was not working.
Key name in avalon data was defined as `family` but in reality in settings and in publishing plugins we are using `families`.
1. open nuke workfile and create render write node.
2. open settings and go to `project_anatomy/imageio/nuke/nodes/requiredNodes/0/knobs/6/value` and set to different colorspace setting.
3. Save settings and then go back to nuke and in openpype menu chose `Apply all`
4. colorspace on write node should change (this can only be seen inside the write node group)

Nuke: color settings for render write node is working now

---

openpype/hosts/maya/plugins/publish/extract_look.py

When the user added a texture with AiImage with UDIMs format and assign the look instance to the mesh with the texture, it will result to the KeyError when publishing the look.
the system cannot find the texture path when passing through the if-condition code: `if files_metadata[source]["color_space"] == "Raw"`. This error contributes to the Maya File Path Editor, which maya cannot resolve the udim path in AiImage.
~~Introduce exception handling to tell the system to reference the color_space attribute of the AiImage node itself to set up the color_space to raw specifically for the AiImage case.~~ 
UPDATE: Get the resolved files from `resource.get("source")` and tell the system to do the condition of `file_metadata[source]["color_space"] == "Raw"` to set color_space if the files are …

fix the bug of failing to extract look when UDIMs format used in AiImage

---

openpype/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json

This [PR](https://github.com/pypeclub/OpenPype/pull/3620) removed ability to scale source using pixel aspect ratio which is fixed here.
Next paragraf is more elaborate text with more info. This will be displayed for example in collapsed form under the first sentence in a changelog.
1. Make sure `project_settings/global/publish/ExtractReview/profiles/0/outputs/h264/scale_pixel_aspect` is set to true
2. Publish something with pixel aspect ratio different then 1
- from what I know it's possible from nuke or editorial
- e.g. anamorphic image (pixel aspect is 2 so 100x100 should have resolution 200x100)
3. Check output which should be scaled as expected
Resolves …

General: Extract Review can scale with pixel aspect ratio

---

openpype/modules/sync_server/providers/abstract_provider.py
openpype/modules/sync_server/providers/dropbox.py
openpype/modules/sync_server/providers/gdrive.py
openpype/modules/sync_server/providers/local_drive.py
openpype/modules/sync_server/providers/sftp.py
openpype/modules/sync_server/sync_server.py
openpype/modules/sync_server/sync_server_module.py
openpype/modules/sync_server/tray/models.py
openpype/tools/loader/model.py

Preparation for v4 transition.
Replaced regular `find` functions with `get_representations` query whenever possible.
There is a couple of places where appropriate query doesn't exist in entities. 
There is also quite a few MongoDB dependent aggregates, piece meal updates of representation documents. It doesn't make sense to prepare intermediate step for these, they will need to be updated when transition to v4 will be imminent.
1. Enable SiteSync module, everything should work as before

SyncServer: use query functions

---

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py

OpenPype deadline global plugin is not Pype 2 compatible anymore.
Because of pype 2 compatibility the deadline prelaunch hook is always triggered which cause issues with jobs that are not for OpenPype because in that case Pype 2 logic starts.
Side change is to make the plugin Python 2 compatible.
1. Copy the plugin to deadline repository
2. Try submit a job without openpype
3. It should not crash
Resolves https://github.com/pypeclub/OpenPype/issues/3664

Deadline: Global job pre load is not Pype 2 compatible

---

openpype/hosts/maya/api/lib_rendersettings.py
openpype/hosts/maya/plugins/publish/collect_render.py
openpype/hosts/maya/plugins/publish/validate_render_image_rule.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/settings/defaults/project_settings/maya.json

This is a draft untested PR to fix #3642 
Please test publishing from Maya with up-to-date saved settings.
1. Ensure render images file rule works as expected.
2. Ensure aov separator works as expected

Maya: Refactor moved usage of CreateRender settings

---

openpype/tools/loader/widgets.py

Fix logic that reports whether a representation was found for the versions or not.
Noticed an odd if statement which looked like a bug:
```python
if version_id not in version_ids:
version_ids.remove(version_id)
```
Which in the end resulted in all loaders to always log this:
> Subsets "subset" don't have representation 'representation'
So ended up investigating and refactoring the code.
1. Loaders should work as expected and report when representation isn't found.

Loader: Fix representation check per version logic

---

igniter/bootstrap_repos.py
igniter/install_thread.py
openpype/tools/tray/pype_tray.py
openpype/version.py
start.py

There was a bug that affected finding of last OP version. This resulted in invalid behaviour mainly in headless mode, where it tries to reinstall already installed version.

General: Fix finding of last version

---

openpype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
openpype/settings/defaults/project_settings/ftrack.json
openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json

Have ability to set task status on creation during integrate hierarchy (editorial publishing).
Added profiles using task name and task type to be able tell what status should be set on new created task during integrate hierarchy.
1. Add a profile which define some status name for specific task type (`project_settings/ftrack/publish/IntegrateHierarchyToFtrack/create_task_status_profiles`)
2. Publish editorial which creates new tasks
3. Check if statuses of new tasks are right

Ftrack: Set task status on task creation in integrate hierarchy

---

openpype/modules/kitsu/utils/update_zou_with_op.py
openpype/modules/sync_server/sync_server_module.py
openpype/tools/launcher/models.py
openpype/tools/libraryloader/app.py
openpype/tools/project_manager/project_manager/model.py
openpype/tools/sceneinventory/window.py
openpype/tools/settings/settings/widgets.py
openpype/tools/standalonepublish/widgets/widget_asset.py
openpype/tools/utils/lib.py
openpype/tools/utils/models.py

Use `get_projects` from `openpype.client` instead of `projects` method from `AvalonMongoDB`.
Use `get_projects` function in code to query projects.
I didn't notice this method during query getter refactor.
Inactive projects should be hiddedn as expected

General: Use client projects getter

---

openpype/host/host.py
openpype/hosts/maya/__init__.py
openpype/hosts/maya/api/workio.py
openpype/hosts/maya/module.py
openpype/lib/applications.py
openpype/modules/base.py
openpype/modules/interfaces.py

Hosts are OpenPype modules so they have more abilities and more defined structure.
First step to be able define hosts as OpenPype modules which can make them self contained parts. Added interface `IHostModule` which marks a module as host module so it can handle host related logic before a DCC or process, where host is integrated, is running. Host module must have set which host it represents with it name (`host_name`). Can define it's workfile extensions out of integration so it's available before DCC is running. As module it can handle some logic more dynamically without predetermined paths. For example can define path to launch hooks using `get_launch_hook_paths` or handle launch environments implementing `add_implementation_envs` as module method.
Changed how paths to prelaunch hooks …

Maya: Hosts as modules

---

openpype/client/entities.py
openpype/hosts/nuke/plugins/load/load_clip.py
openpype/pipeline/load/utils.py
openpype/tools/loader/widgets.py

Fix switch from hero version functionaly in scene manager tool.
Bug was not related to scene manager tool but to client function `get_representation_parents` where were not handled hero versions thus it didn't find parents and crashed.
Side fixes related to loading of hero version in loader and in nuke's LoadClip. If loader crashed on loading of hero version it caused another crash when tried to show message with error becaue hero versions don't have name key in it. LoadClip crashed from same reason when added to scene "information" data.
1. Load Hero version to scene
2. Open scene manager tool
3. Run "Switch to version" which should work (if loader support it)
Resolves https://github.com/pypeclub/OpenPype/issues/3689

General: Switch from hero version to versioned works

---

openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py

More information in logs when autosync is turned on/off.
Log information than auto sync was turned off and added infromation about username who triggered it.
1. Start ftrack event server
2. Change auto sync on a project
3. A log describing who turned on/off auto sync on which project should appear in process of ftrack event server

Ftrack: More logs related to auto sync value change

---

openpype/plugins/publish/extract_review.py
openpype/plugins/publish/integrate_subset_group.py

Not setting `AVALON_APP_NAME` to proper configured host name resulted in crashes in  `extract_review` and `integrate_subset_gorups` that relied on `app` resp. `hostName` to be set in context.
This is not directly related to RoyalRender, only that RoyalRender publisher doesn't set this as it is oblivious about host name to be used.

RoyalRender: handle host name that is not set

---

openpype/modules/deadline/abstract_submit_deadline.py

It seems that DL webservice can return broken json payload even if `response.ok`. Safer and saner report.
Without it error message is a bit vague:
Not sure how to test it properly. I would just try to send regular DL submission from AE (or Harmony).

Deadline: better logging for DL webservice failures

---

openpype/hosts/photoshop/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/photoshop.json
openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json

Ffmpeg cannot handle pictures higher than 16384x16384. 
Used PIL to resize to max size(with aspect ratio).
Implemented as a 'hotfix' to unblock customers production.
In the future this plugin should be refactored (to use general ExtractThumbnail and ExtractReview). That is currently blocked by not having oiio on all platforms.
1. publish workfile with larger resolution than 16384x16384 in PS

Photoshop: resize saved images in ExtractReview for ffmpeg

---

openpype/settings/handlers.py
openpype/settings/lib.py
openpype/tools/settings/settings/categories.py
openpype/tools/settings/settings/dialogs.py
openpype/tools/settings/settings/window.py

Handle opened sessions of settings UI and last saved settings, to avoid unwanted loss of settings values when multiple people are modifying setting at the same time.
First who opens settings will create lock in mongo (OP version specific lock). From that moment anyone who will open settings UI will see message saying that other session of settings is opened with information about username and machine where it's happening. The dialog give options to open settings in view only mode or take control over the settings. In view mode is save disabled and when control is taken the lock is changed to the user who did it. From that moment the previous locked user can't save with only option to reset settings, is shown with dialog and information about person who took the control.
Also was added one …

Settings: Lock settings UI session

---

openpype/tools/workfiles/model.py

Published workfiles are again visible in workfiles tool.
Workfiles tool used wrong filtering for queries of published workfiles which caused that published workfiles are not visible in workfiles tool.
1. Open any host
2. Publish any workfile
3. Open workfiles tool
4. Check "Published" so published workfiles are visible
5. Your workfile should be visible there

Workfiles tool: Fix published workfile filtering

---

openpype/hosts/aftereffects/plugins/create/workfile_creator.py
openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
openpype/hosts/photoshop/plugins/create/workfile_creator.py
openpype/hosts/photoshop/plugins/publish/collect_workfile.py

Variant was omitted which resulted in trailing underscore if subset name was in format of `{family}_{Task}_{Variant}` (which is a case for one customer.)
Default value 'Main' hardcoded. 
Will only propagate in workfile subset (and final published name of workfile) if {variant} is used in subset name template. (By default it isn't.)
It could be potentially added to Settings if anyone requires. Currently not implemented to limit polluting Settings with unnecessary values.
This particular issue occurred only on one specific customer.
1. configure subset name template to `{family}_{Task}_{Variant}` in `project_settings/global/tools/creator/subset_name_profiles`
2. publish workfile
3. compare resulting workfile name in `publish` folder, it should contain `Main` value

PS, AE: Provide default variant value for workfile subset

---

openpype/cli.py
openpype/hosts/traypublisher/__init__.py
openpype/hosts/traypublisher/module.py

Traypublisher host is now working as module.
Moved content of `traypublisher_action.py` into traypublisher host which can now behave as module. The module now also inherit from `IHostModule` and has custom cli commands. With new cli commands in the module was removed global cli command for traypublisher.
1. TrayPublisher action should still be visible in tray menu (if enabled in experimental tools)
2. TrayPublisher should launch when the action is triggered

TrayPublisher: Define TrayPublisher as module

---

openpype/settings/handlers.py

Fix broken save of project overrides.
There was wrong mongo operation when project overrides were saved to already existing overrides. This change is fixing it.
1. Save settings on a project
2. Save the settings again and it should not crash

Settings: Fix project overrides save

---

openpype/client/notes.md
openpype/client/operations.py
openpype/tools/loader/model.py
openpype/tools/loader/widgets.py
openpype/tools/utils/lib.py

Use client opeartions to change subset group on subset documents.
1. Open any host on project where you have something published
2. Open loader tool in the host
3. Select subset/s
4. Hit Ctrl + G
5. Change group of subset
6. Group change should be propagated

Loader: Subset groups using client operations

---

openpype/lib/avalon_context.py
openpype/pipeline/context_tools.py
openpype/tools/workfiles/files_widget.py

Functions related to change of current context were moved to context tools.
Moved `compute_session_changes` and `update_current_task` into `openpype.pipeline.context_tools`. Function `update_current_task` was also renamed to `change_current_context`. Both functions don't expect host name as argument and expect only asset document instead of asset name.
Marked functions in `avalon_context` as deprecated and updated few deprecated categories in the file (changed removement version caused by quick release of 3.14).
1. Context change should work as expected (context can be changed using workfiles tool)

General: Move context specific functions to context tools

---

openpype/hosts/maya/plugins/load/_load_animation.py
openpype/hosts/maya/plugins/load/load_ass.py
openpype/hosts/maya/plugins/load/load_look.py
openpype/hosts/maya/plugins/load/load_reference.py
openpype/hosts/maya/plugins/load/load_yeti_rig.py

Use project name for root preparation instead of project code.
Using project code can cause that anatomy won't be created for right project so root values will be invalid.
1. Loading in Maya should work

Maya: Use project name instead of project code

---

openpype/modules/base.py

Added helper methods to ModulesManager to access modules by name.
Added dictionary like access to module by their names and special method to get module by name which also checks if is module enabled.
New methods on created object of `ModulesManager` in different cases (e.g. in Tray > Admin > Console).
```
from openpype.modules import ModulesManager
manager = ModulesManager()
print(manager["project_manager"])
print(manager.get("project_manager"))
print(manager.get_enabled_module("project_manager"))
```

General: Added helper getters to modules manager

---

openpype/client/operations.py
openpype/lib/avalon_context.py
openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
openpype/modules/ftrack/lib/avalon_sync.py
openpype/tools/project_manager/project_manager/model.py
openpype/tools/project_manager/project_manager/widgets.py

Moved entity specific constants to client code or reuse those which are already there.
These constants are related to creation of new entities. Some of them were already available there. 
Hard to tell to which degree these constants are "constants" and should be defined at one place? They're connected to schema validations but schema validation is in pipeline part. I would say that logic related to validation of project entities should be moved to client side and rest should stay in pipeline. I would like to avoid changing it and discussing it in this PR as this is refactor PR.
Variable `PROJECT_NAME_ALLOWED_SYMBOLS` is not used in `avalon_context.py` but is imported from there in `__init__.py`. I would like to keep it until the backwards compatibility is removed.
Technically logic didn't …

General: Move constants from lib to client

---

openpype/settings/handlers.py

It is possible to save changes in studio default anatomy.
Add information about last save into studio default project anatomy. Right now it's crashing because the last save information is missing on cache.
The last save information is not used from cache but it is probably good idea to store that information too.
2. Go to Project tab
3. Keep default project and change anything in Anatomy category
4. Hit save
5. Save should work fine

Settings: Fix studio default anatomy save

---

openpype/modules/settings_action.py
openpype/tools/settings/settings/dialogs.py

Remove settings lock on tray exit.
On tray exit is closed settings UI which should cause that settings lock is removed. This won't solve situations when tray crashes or is shut down by task manager but will solve most of possible issues connected to shutting down tray.
Also make sure that `None` value in machine information won't cause crashes.
1. Run OpenPype tray
2. In tray open studio settings (Tray > Admin > Studio Settings) - let them load
3. Close tray (Tray > Exit)
4. Open settings UI again (through tray or direct settings command) and no dialog should show
Resolves https://github.com/pypeclub/OpenPype/issues/3718

Settings: Remove settings lock on tray exit

---

openpype/hosts/blender/plugins/load/load_layout_blend.py
openpype/hosts/blender/plugins/load/load_layout_json.py
openpype/hosts/blender/plugins/load/load_rig.py
openpype/hosts/maya/plugins/load/load_reference.py
openpype/lib/avalon_context.py
openpype/pipeline/create/__init__.py
openpype/pipeline/create/creator_plugins.py

Moved `get_creator_by_name` function into `openpype.pipeline.create.creator_plugins` and renamed to `get_legacy_creator_by_name`.
Creation during loading in Blender and Maya should work as before.

General: Move creators plugin getter

---

openpype/hosts/aftereffects/__init__.py
openpype/hosts/aftereffects/api/workio.py
openpype/hosts/aftereffects/module.py

AfterEffects host is module.
Implemented `AfterEffectsModule` for resolve host which gives public information about the host.
- AE can be launched and is connected to side process (integration works)
- Last workfile is launched (not sure if it was possible?)

AfterEffects: Define AfterEffects as module

---

openpype/hosts/blender/__init__.py
openpype/hosts/blender/api/workio.py
openpype/hosts/blender/module.py

Blender host is OpenPype module.
Implemented `BlenderModule` for blender host which gives public information about the host.
- Blender can be launched
- Integration works
- PySide2 is auto install when missing
- Other addons are registered too
- Last workfile is launched if available and feature is enabled

Blender: Define blender as module

---

openpype/pype_commands.py

Safer check for presence of "context" data in batch manifest.
Currently is somehow possible to upload batch without context data. This results in uncaught fail and batch keeps in "in_progress".
1. provide batch with manifest with empty context ({})
2. run WP

Webpublisher: added check for empty context

---

openpype/hosts/photoshop/__init__.py
openpype/hosts/photoshop/addon.py
openpype/hosts/photoshop/api/pipeline.py
openpype/hosts/photoshop/api/workio.py

Photoshop host is addon.
Implemented `PhotoshopAddon` for photoshop host which gives public information about the host.
- Photoshop can be launched and integration works (as before)

Photoshop: Defined photoshop as addon

---

openpype/hosts/nuke/api/lib.py

Setting settings from Anatomy is working
Nuke menu item `Set Colorspace` was not working properly and render write nodes were not fixed in case any change in Settings were made. 
1. open workfile with test node graph containing render family node
2. change anything in `project_anatomy/imageio/nuke/nodes/requiredNodes` knobs values (make sure there is no legacy set in types!)
3. in nuke openpype menu Set colorspace
4. it should change acordingly to settings (`CTRL+Enter` on selected group node, to get inside to look at write node)

Nuke: color-space settings from anatomy is working

---

openpype/hosts/blender/api/lib.py
openpype/hosts/blender/api/ops.py
openpype/hosts/blender/blender_addon/startup/init.py

Blender host ops module enhancements : manager refresh after process events
- Manager (scene inventory) is refreshed after process events.
- _process_app_events registered once (before, this was multiple registered, each time OP dialogs was opened)
- TIMER_INTERVAL more longer to avoid lag with MacOs.
- OP Blender startup add-on fixed with required function register/unregister.
1. Open a task with out-to-date OP container asset.
2. Open the Manager dialog and update the asset.
3. Should get the Manager refreshed after the update.

Blender: ops refresh manager after process events

---

openpype/lib/applications.py
openpype/modules/__init__.py
openpype/modules/base.py
openpype/modules/ftrack/ftrack_module.py
openpype/modules/interfaces.py
openpype/modules/shotgrid/shotgrid_module.py
openpype/modules/slack/slack_module.py
openpype/modules/timers_manager/timers_manager.py

Cleanup of openpype interfaces related to openpype modules.
Moved `OpenPypeInterface` into interfaces file as don't propagate it to `openpype.modules` api. Reduced usage of `ILaunchHookPaths` from modules as the interface is not needed anymore -> marked as deprecated. Function for collecting of launch hooks was moved to applications logic. Use direct import of interfaces -> replaced `from openpype_interfaces import ...` with `from openpype.modules.interfaces import ...`.
1. All modules should be imported and loaded
2. All launch hooks should be working as expected (e.g. slack should work in python 2 hosts)

General: Module interfaces cleanup

---

openpype/hosts/photoshop/plugins/publish/collect_color_coded_instances.py
openpype/settings/defaults/project_settings/photoshop.json
openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json

`CollectColorCodedInstances` allows publish only flattened subset of 'image' family.
Previously it was possible to set in Settings to create flatten subset of 'image' family from published subsets. But separate layers marked by publishable colors were published also.
This PR brings more granularity, now it is possible to:
- create flattened 'image' subset of all publishable layers + create 'image' subset per publishable layer
- create ONLY flattened 'image' subset of all publishable layers
- not create flattened 'image' subset at all, only separate subsets per marked layer.
1. set `project_settings/photoshop/publish/CollectColorCodedInstances/flatten_subset_template`
2. 
3. mark some top layers in PS to be published
4. check that …

Webpublisher:change create flatten image into tri state

---

openpype/modules/sync_server/providers/abstract_provider.py
openpype/modules/sync_server/providers/dropbox.py
openpype/modules/sync_server/providers/gdrive.py
openpype/modules/sync_server/providers/sftp.py
openpype/modules/timers_manager/rest_api.py
openpype/modules/webserver/webserver_module.py

Fix logger issue in timers manager and modify logs in sync server.
Timers manager rest api codebase is using wront attribute name during initialization for logger. Sync server provides have their own loggers so they don't have to use loggers in global scope.
1. TimersManager can register webserver callbacks
- can start/stop timer from host (e.g. on task change in workfiles tool)
2. Sync server provides should not crash and still can log

General: Logger tweaks

---

openpype/plugins/publish/collect_context_label.py
openpype/tools/publisher/publish_report_viewer/report_items.py
openpype/tools/publisher/widgets/publish_widget.py
openpype/tools/pyblish_pype/control.py
openpype/tools/pyblish_pype/model.py

Context label collector is more benevolent to available data.
Collector does not require `currentFile` to be filled and use just host name in that case. If context data contains `contextLabel` the plugin just set it as label of context and skip rest of logic, this was added to have ability define custom context label and skip the plugin logic. Result is that standalone publisher and tray publisher don't have to be explicitly named in the plugin.
Pyblish pype does not force to have `"label"` in `instance.data` and `context.data`.
1. Context label should be collected as did

General: Benevolent context label collector

---

openpype/pipeline/workfile/path_resolving.py

Allow env vars to be parsed in workfile template path resolving
The current workfile template path resolving matches either an absolute path or just the anatomy context.
This extends the anatomy context used by the parser to also contain all the os.environ vars
using dict.update (so there's no conflict with keys)
Priority would be in environ then, which makes this flexible.
1. put an env var in the workfiles template path
2. seems to work!

General: Custom workfile template use env keys to fill path

---

openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py

Multiple Deadline job dependencies are linked.
If Nuke multiple baking stream jobs are created, those are added as job dependency to the last python publishing job.
1. open nuke workfile in project with multiple baking stream configuration
2. publish render family instance to farm
3. Open Deadline Monitor and switch to Superuser mode
4. double click to `Publish - *` python job in submitted group of jobs
5. go to Dependencies and see there are multiple jobs.

Nuke: missing job dependency if multiple bake streams

---

openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
openpype/pipeline/create/creator_plugins.py

Fixed imports in collect ftrack api and new publisher creators.
Collect ftrack api used import of `filter_profiles` from different file (reimported imported function...). Creator plugins for new publisher used deprecated function to get subset name.
1. Publishing to Ftrack works
2. Creator plugins in tray publisher won't cause deprecation warning

General: Smaller fixes of imports

---

openpype/lib/__init__.py
openpype/lib/delivery.py
openpype/lib/path_tools.py
openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
openpype/modules/ftrack/event_handlers_user/action_delivery.py
openpype/pipeline/delivery.py
openpype/pipeline/load/__init__.py
openpype/pipeline/load/utils.py
openpype/pipeline/template_data.py
openpype/plugins/load/delete_old_versions.py
openpype/plugins/load/delivery.py

Moved delivery logic into `pipeline.delivery`.
Few functions were kept in lib but changed place or were renamed. Function `sizeof_fmt` was renamed to `format_file_size` and with `collect_frames` was moved to `path_tools`. Collect frames is not used only in delivery and can be considered as lib function. Function `path_from_representation` was added to load utils as `get_representation_path_with_anatomy`. Rest of delivery logic was moved to `openpype.pipeline.delivery` and function in lib were marked as deprecated.
1. Delivery action from loader works
2. Delivery action from ftrack works

General: Move delivery logic to pipeline

---

openpype/client/operations.py
openpype/pipeline/thumbnail.py
openpype/plugins/publish/integrate_thumbnail.py

It is not required to have filled `AVALON_THUMBNAIL_ROOT` to integrate thumbnail. The root can be replaced with project roots from anatomy.
The key `AVALON_THUMBNAIL_ROOT` is optional for thumbnail integration and thumbnail resolver. It is possible to use anatomy roots in thumbnail template as replacement. Anatomy roots are "loaded" only if template is using them - load of Anatomy could make loading slower.
Thumbnails integration is using client operations.
It would be good idea to make wrapper around thumbnail resolvers to reuse initilized objects instead of initialize them on use -> anatomy could be loaded only once.
1. Thumbnail integration works as before
- integrate thumbnail happens and don't crash
- the thumbnails are visible in loader
2. Usage of `{root[work]}` in thumbnail …

General: Thumbnail can use project roots

---

openpype/hosts/maya/plugins/publish/extract_playblast.py
openpype/hosts/maya/plugins/publish/extract_thumbnail.py

This should fix #3752
Test against what's mentioned in the issue.

Maya: Fix typo in getPanel argument `with_focus` -> `withFocus`

---

openpype/plugins/load/open_file.py

This should fix #3760 or at least a part of it. This should fix "Open file" not being able to open some of the representations.
For image sequences this should open the same first file as before.
1. Test the **Open** action

General: Fix Open File action to use main file of representation

---

openpype/settings/defaults/project_settings/ftrack.json

there is a typo in the default status name in settings prgoress -> progress
check the value was fixed in settings under `project_settings/ftrack/events/next_task_update`

Ftrack status fix typo prgoress -> progress

---

openpype/modules/sync_server/sync_server_module.py
openpype/pype_commands.py

Addon has defined `syncservice` cli command.
Goal is to move cli commands from global commands to module specific commands. The previous implementation is kept so transition from one to other is smooth.
1. Running `~/openpype_console module sync_server syncservice -a <site name>` should work and do same thing as `~/openpype_console syncserver -a <site name>`

SyncServer: Added cli commands for sync server

---

openpype/client/__init__.py
openpype/client/operations.py
openpype/lib/avalon_context.py
openpype/modules/ftrack/event_handlers_server/action_prepare_project.py
openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
openpype/modules/kitsu/utils/update_op_with_zou.py
openpype/tools/project_manager/project_manager/widgets.py

Function `create_project` was moved to `openpype.client.operations`.
Project creations is very specific operations which deserve special function. Function in lib was marked as deprecated with warning to new location. All existing usages in current codebase were replaced with new import location.
Creation of projects should work (e.g. from Ftrack or from Project Manager tool).

General: Create project function moved to client code

---

openpype/pipeline/publish/__init__.py
openpype/pipeline/publish/publish_plugins.py
openpype/plugin.py
openpype/plugins/publish/extract_burnin.py
openpype/plugins/publish/extract_otio_file.py
openpype/plugins/publish/extract_otio_review.py
openpype/plugins/publish/extract_otio_trimming_video.py
openpype/plugins/publish/extract_review_slate.py
openpype/plugins/publish/extract_trim_video_audio.py

Copied `Extractor` from `openpype.plugin` to `openpype.pipeline.publish`.
This is first step to move `Extractor` class to different location. The plugin is used in almost each hosts and it will be safer and faster to do PRs for each of them to test them. In this PR were changed imports in global plugins.

General: Copied 'Extractor' plugin to publish pipeline

---

openpype/tools/standalonepublish/widgets/model_asset.py

Match how other models ignore empty asset labels and then still show asset name.
We have some custom logic that can set custom labels on Assets - but it sets just an empty string when not set to anything - which didn't look pretty in Standalone Publisher. Other tools didn't have the issue.
1. Add a `asset["data"]["label"] = ""` to an asset
2. Show the asset in Standalone Publisher - should still look good.

Standalone Publisher: Ignore empty labels, then still use name like other asset models

---

openpype/client/entities.py

This fixes Settings reading and saving for inactive projects.
**:warning: NOTE: This makes `openpype.client.get_project` argument `inactive` default to True.**
_And `openpype.client.get_projects` argument `inactive` still defaults to False like before._
I felt that was a much more logical default value for a function whose sole function is to get a single project by name - it should just return it if found by default. Having this filtered by default would also break a lot of other code too if you would be working inside the DCC and the project would be set to inactive.
The Project Settings did not read the project settings (anatomy data) for an inactive project and thus the UI would just show the default values.
Saving the settings for an inactive project would error:
```python
Traceback …
```

Settings: Fix settings for inactive projects 

---

openpype/modules/kitsu/utils/credentials.py

Added an event triggered when user connects to kitsu.
Thanks to this addition, other modules and addons can be notified when the user successfully connects to Kitsu via Kitsu module, and get data at the same time (Currently, only Kitsu login, but it's possible to pass more data if need be).
Listeners should subscribe to the event in tray_init using register_event_callback.
This method return value can be stored in a class level variable, which will be useful to unsubscribe to the event on tray_exit by calling the deregister method.
1. Create the on_kitsu_login(self, event) method in the class that should listen to the event. This method will be called when kitsu module calls the event.
2. Create a class level variable in which …

Added an event triggered when user connects to kitsu

---

igniter/bootstrap_repos.py
tools/create_zip.ps1

This is fixing edge case where if version of OP is "pure" - ie. `3.14.1`  then `OpenPypeVersion.version_in_str()` will fail (it will return None). This mainly affects `create_zip` script and probably finding versions.
This is change in Igniter, so in theory it should go to new minor release but because it has low impact and is useful for subsequent patch releases, let's put it to develop.

Fix version resolution

---

openpype/hosts/maya/api/pipeline.py

Maya host `containerise` was the only implementation that skipped imprinting values if the value was empty/None/zero (`if not value`). Instead of ever allowing to do so this now forces the required attributes to actually be generated on containerise.
Since all values should be string anyway I've also simplifies the logic that adds and sets the attributes.
I was investigating an issue where some loaded containers were missing `loader` and `representation` attributes and I'm unsure how that happened. However, this part of the code could have potentially done so without warnings/errors if `loader` or `representation` values were ever considered null.
1. Load containers into Maya
2. Everything should load as usual and be visible in the Scene Inventory, etc.

Maya: `containerise` dont skip empty values

---

openpype/hosts/maya/api/menu.py

[This PR added a new menu entry to **Set render settings**](https://github.com/pypeclub/OpenPype/pull/3097/files#diff-6776f55e08129abce6069879cab8e37160877468ca9276bbaabc631f28c1d3d8R102-R108) but our team felt it was in an odd location in the menu. Plus it messed with the muscle memory for the "Work files" menu entry they tend to click a lot.
Here's the change made by this PR:
**Before**
**After**
Also [mentioned on discord here](https://discord.com/channels/517362899170230292/517382145552154634/1008732362491838576)

Maya: move set render settings menu entry

---

openpype/hosts/nuke/plugins/publish/validate_write_nodes.py

Nuke was failing due wrong type detection.
Settings Anatomy had introduced from version 3.11 new type of Gui color knob value. Validator was not refactored for the new value yet. 
1. Open any nuke workfile with created render node
2. open publisher and validate
3. Validate write nodes should not fail on Error (Traceback: wrong type)

nuke: validate write node is not failing due wrong type

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

[Remove `instance._log` legacy code that has no use anymore](https://github.com/pypeclub/OpenPype/commit/d00eb29ca1bd8fcda97a40a14f8ae03d171c4853)
Came up on [Discord here](https://discord.com/channels/517362899170230292/517382145552154634/1016662712614404147).
Original commit that added the code is [here](https://github.com/pypeclub/OpenPype/commit/5bceb794413381d7c1a1378de87cb9efaade4041).
Likely was related to [old logic in the Submit Publish Job](https://github.com/pypeclub/OpenPype/blame/b55dbc2bc29b040dedaad01adcbcba4d3ec54ee2/pype/plugins/global/publish/submit_publish_job.py#L438-L447) which is since long gone.
1. Publishing to Deadline with publish jobs
2. Publish jobs should behave as expected

Deadline: Submit publish job remove instance._log that has no use anymore

---

openpype/hosts/blender/plugins/publish/collect_current_file.py

Like `collect_workfile` behavior from Maya host, Blender should ba able to publish workfiles.
- I have updated `collect_current_file.py` with the code from maya plugin `collect_workfile` to be able to publish workfile representation.
- Action are available to save file if needed.

Blender: Publisher collect workfile representation

---

openpype/hosts/photoshop/api/lib.py
openpype/hosts/photoshop/api/ws_stub.py
openpype/hosts/photoshop/plugins/publish/extract_image.py

If workfile has a large number of layers (hundreds or thousands), ExtractImage wasn't too efficient. It was hiding/showing layers too many times.
Current logic is to hide all, show only publishable layers of instance, save to image, hide them again.
get_layers replaced by argument if possible.
1. open workfile with large number of publishable instances and layers
2. measure if it is faster with this PR (results should be same)

Photoshop: attempt to speed up ExtractImage

---

openpype/modules/ftrack/plugins/publish/collect_username.py
openpype/modules/slack/plugins/publish/integrate_slack_api.py
openpype/plugins/publish/extract_burnin.py
openpype/plugins/publish/integrate.py
openpype/plugins/publish/integrate_hero_version.py
openpype/plugins/publish/integrate_legacy.py

There is some bizzare usage mix of `"user"` and `"username"` keys during publishing. This change few places where it could cause issues.
In most of places is used `"user"` during publishing. This PR does not unify the mix of user and username but adds both options to places where only `"username"` was used. Renamed `CollectUsername` to `CollectUsernameForWebpublish`. Use query limits to get user. `WEBPUBLISH_OPENPYPE_USERNAME` is not set as user is already changed on context.
1. Webpublisher should still be able to fill user
2. Integrate slack can use `{user}` in template

General: User keys during publishing

---

openpype/hosts/hiero/plugins/publish/precollect_instances.py

Retimed clips for lest then 100% is working now.
Publishing is working as expected.
Precollect instances was falsely detecting timeline range for otio clip data.
1. open Hiero with testing project
2. create clip with retime for about 80% speed
3. Create publishable clip from the 2.
4. publish and see that Precollect intances will not fail

Hiero: retimed clip publishing is working

---

openpype/tools/sceneinventory/model.py
openpype/tools/sceneinventory/window.py

This adds a `subsetGroup` column to the Scene Inventory / Manager.
We tend to group publishes in the Loader (shortcut: `ctrl + g`) to sometimes label things as "extras" or even group them to be "deprecated".
By showing the column in the Manager this is now also much easier to trace to that information.
Code might be a bit messy - so please double check. 
The "icon" for the group is the default group icon. Originally in Avalon groups could be configured on the project to allow custom icons per groups, etc. but that's currently not supported in OpenPype as far as I know. Thus I had chosen for now to just hardcode the icon.
This would be extra useful as soon as better UX for filtering is added to tools - then we could also filter by subset group, etc.
1. Load some content with and without …

Scene Inventory: Add subsetGroup column

---

igniter/install_dialog.py

Fix unhandled cases when `status` is set to `None` when installation did not happen.
Fixed issue when install thread has status set to `None` because the version is already installed. That can happen in some cases.
This is reaction to happened traceback. I'm not sure how this happened so this is more or less quick fix. We should maybe find out where is the source of the issue?
```
*** No DB connection string specified.
--- launching setup UI ...
File "C:\Users\petr.dvorak\Downloads\openpype-3.14.2-nightly.2-windows\openpype-3.14.2-nightly.2-windows\igniter\install_thread.py", line 150, in run
bs.install_version(openpype_version)
File "C:\Users\petr.dvorak\Downloads\openpype-3.14.2-nightly.2-windows\openpype-3.14.2-nightly.2-windows\igniter\bootstrap_repos …
```

Igniter: Fix status handling when version is already installed

---

openpype/client/entities.py

Client code does not crash on python distributions where is not available `re.Pattern`.
Replace `re.Pattern` with custom variable `PatternType` by getting type of compiled string.

General: Fix Pattern access in client code

---

openpype/tools/launcher/models.py
openpype/tools/launcher/widgets.py

Fixed "Skip opening last workfile" for grouped applications.
The option to skip last workfile was not working if there was more then one variant of application group. In that case `"start_last_workfile"` was not set on action data and the cache of applications stored the cache only for first application.
1. Make sure you have at least 2 variants of application enabled on project
2. Open launcher on some task
3. Change state "Skip opening last workfile" with right click on the application
4. Launch the application
5. Last workfile should not be opened
Resolves https://github.com/pypeclub/OpenPype/issues/3533 and https://github.com/pypeclub/OpenPype/issues/2788

Launcher: Skip opening last work file works for groups

---

openpype/hosts/maya/api/pipeline.py

#3790 added redundant duplicated code. This removes that.
1. Maya launch

Maya: Remove getting project name and settings twice on install

---

openpype/tools/utils/host_tools.py

Added new publisher to host tools. Code copied from https://github.com/pypeclub/OpenPype/pull/3046 which is in draft and the code is already needed for other PRs.
Added new publisher to host tools to be able easily open the tool from hosts.
1. Calling `show_publisher` in host tools should work
```
from openpype.tools.utils.host_tools import show_publisher
show_publisher()
```

Publisher: Add new publisher to host tools

---

openpype/modules/ftrack/__init__.py
openpype/modules/ftrack/ftrack_module.py
openpype/modules/ftrack/ftrack_server/__init__.py
openpype/modules/ftrack/ftrack_server/event_server_cli.py
openpype/modules/ftrack/ftrack_server/lib.py
openpype/modules/ftrack/lib/avalon_sync.py
openpype/modules/ftrack/tray/ftrack_tray.py

Self deployed ftrack server does not have to end with `.ftrackapp.com` which is now possible to handle in OpenPype.
The validation does 2 validations of server connection, one with `ftrackapp.com` and one without. This way it is backwards compatible but works when url does not end with `.ftrackapp.com`. Function `check_ftrack_url` was moved to module level.
To get ftrack url it is required to connect to ftrack server which can slow down tray launch. That is because environment variable `FTRACK_SERVER` is set on launch. We should maybe not set the environment variable on start but get it from module when needed - has high potential to break ftrack code (created [issue](https://github.com/pypeclub/OpenPype/issues/3835)).
1. Set ftrack url to self deployed server without `ftrackapp.com` at …

Ftrack: Url validation does not require ftrackapp

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/settings/defaults/project_settings/ftrack.json

Fix typo in legacy family name `mayaascii` -> `mayaAscii`.
Not sure how relevant this tweak is because I think this is the legacy family name for `mayaScene` family. Correct?
[Mentioned on discord](https://discord.com/channels/517362899170230292/517382145552154634/1017751095734452264)
1. Not sure where to test this best. Publish a Maya scene and check with Ftrack?

Maya+Ftrack: Change typo in family name `mayaascii` -> `mayaAscii`

---

openpype/hosts/fusion/plugins/publish/collect_inputs.py
openpype/hosts/houdini/plugins/publish/collect_inputs.py
openpype/hosts/maya/api/lib_rendersetup.py
openpype/hosts/maya/plugins/publish/collect_inputs.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/plugins/publish/collect_input_representations_to_versions.py

This is a (currently **DRAFT**) pull request to implement specific input links used in the generation of a specific publish.
This basically implements the following code mentioned in [this comment](https://github.com/pypeclub/OpenPype/issues/2092#issuecomment-1113324596):
> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/collect_inputs.py
> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/houdini/publish/collect_inputs.py
> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/fusion/publish/collect_inputs.py
Note that the [Houdini code actually already exists in the OpenPype code base](https://github.com/pypeclub/OpenPype/blob/e93558f961c32615b36177f0e2a212ed59f22e24/openpype/hosts/houdini/plugins …

General: Collect (generative) input links

---

openpype/lib/transcoding.py
openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py

Logic did `divisor == 3` instead of `divisor = 3`. 
Variable `divisor` wasn't defined.
This felt like a bug - not entirely sure it was a typo. Was it?
1. Try transcoding with matrix3 type (3x3 = 9 values)?

Transcoding: Fix typo in logic for matrix type

---

openpype/plugins/publish/extract_otio_file.py

This is quick fix for publishing workfile with tray publisher, skipping **Extract OTIO File** if data is missing on instance.
It should be fixed more thoroughly but I hadn't time to dig deeper as how this OTIO stuff works with workfilles and this is needed by client.

Tray Publisher: skip plugin if otioTimeline is missing

---

openpype/hosts/maya/api/lib.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json

Adds a `displayTextures` setting that actually does what you expect it to do - toggle display of textures.
The old `textures` setting is preserved, but now labelized that it is actually about Texture Placements.
I've also labelized all settings to match the Show menu in Maya to avoid confusion.
- This **fixes** "textures" by adding the new but correct `displayTextures` key-value for settings to toggle Display Textures.
- This **fixes** the toggle for HUD / Heads Up Display from #3850 
- This **labelizes** all Viewport Show Options and Camera Options to match more with Maya
<details>
<summary>Click to expand and see screenshots</summary>
New settings in OpenPype:
Display Textures is added higher:
Reference: Maya **Show** menu in viewport:
</details>
1. Playblast away with nice settings
- …

Maya: Extract Playblast fix textures + labelize viewport show settings

---

openpype/tools/publisher/window.py

Main window of publisher is slighly bigger.
The publisher window can be bigger then is now to add more space for attributes and create dialog is smaller then the window and is clearly visible it is not the same window - it blended before.
1. Open Publisher in a host which has creators (e.g. tray publisher)

Publisher: Increase size of main window

---

openpype/tools/workfiles/files_widget.py

Use function `copyfile` instead of `copy` in which cause some issues on linux distribution.
Function `copy` also tries to change permissions of file but most of artist users don't have the permissions to change permissions so whole operation crashes after the file is copied.
1. Open workfile in a host in linux dist
2. Run `Copy & Open` on some published file
3. File should be copied and opened as expected

General: Copy of workfile does not use 'copy' function but 'copyfile'

---

openpype/settings/defaults/project_settings/blender.json
openpype/settings/defaults/project_settings/houdini.json

Added missing default settings for houdini shelf. Blender settings are saved in different order.
1. Houdini settings should not be blue on settings open

Settings: Add missing default settings

---

openpype/hosts/maya/plugins/publish/save_scene.py

During publish, the lockfile isn't removed currently for the maya scene when incrementing and saving the scene.\
Adding the remove_lockfile function in `save_scene.py`

Remove lockfile during publish

---

openpype/settings/defaults/project_settings/maya.json

Set default image format for V-Ray+Redshift to `exr` instead of `png` and `iff` in OP settings.
1. Test setting default rendersettings with V-Ray and Redshfit.

Maya: RenderSettings set default image format for V-Ray+Redshift to exr

---

tools/get_python_packages_info.py

This is adding simple script that will crawl over python packages installed by Poetry and printing them out along with the version information and license type in Markdown table. This could be then used to update [documentation](https://openpype.io/docs/dev_requirements/#python-modules-we-use-and-their-licenses).
```sh
./.poetry/bin/poetry run python ./tools/get_python_packages_info.py
```

General: Simple script for getting license information about used packages

---

openpype/hosts/maya/api/lib_rendersettings.py

I'm noticing a lot of "duplicated" code and logic that contradicts itself in separate areas regarding Maya + Render Settings. Specifically:
- Sometimes checking the project settings and sometimes using a hardcoded default
- `lib_rendersettings` is totally decoupled from the validating of the rendersettings. This should be unified where possible.
The issue is relatively widespread so I'm not sure how to best clean this without going into a big refactor of logic. As such, I'll try to make tiny PRs for each individual problem where I can first.
Remove double setting of additional attributes for Arnold renderer.
1. Create render settings for arnold (with the "set render settings" enabled in settings)

Maya: Render Settings remove double setting of additional attributes for Arnold

---

openpype/plugins/publish/integrate_hero_version.py

Disk must be NTFS format or it will throw "[WinError 1", which matches to EINVAL. Still raise different errors.
Occured on disk formatted by `exFAT`.
1. publish Hero version

Fix - hardlink issue in integrate Hero

---

openpype/hosts/flame/hooks/pre_flame_setup.py

Flame projects are migratable after they are created.
It was reported that when project is created by `user01` at `machine01`, Flame is creating its own unmanaged project data which are locked to 722 and therefore they are not migratable to other machines. This is workaround. The process will open immediately all those files after the project is crated.

Flame: make migratable projects after creation

---

openpype/widgets/nice_checkbox.py

NiceCheckbox widget should work in Python 2 environment.
NiceCheckbox is expecting auto-conversions to float which does not happen in Python 2 so it's width is `0` and the checker does not move. By converting numbers to float at all places where it's expected should be the issue resolved.
I don't have any Python 2 application available so let me know if something does not work.
1. Open Publisher in DCC with Python 2 (e.g. Houdini 18.5)
2. Checkboxes should be visible and should behave right way on changing check state
Resolves https://github.com/pypeclub/OpenPype/issues/3782

Publisher: Nice checkbox visible in Python 2

---

openpype/hosts/tvpaint/lib.py

Change return value of 'rename_filepaths_by_frame_start' when frame start is same as mark in.
1. Set frame start of an asset to `0`
2. Start tvpaint on the asset's task
3. Create some render layers to render
4. Run publish
5. Publishing should not crash during extraction

TVPaint: Fix renaming of rendered files

---

openpype/hosts/photoshop/plugins/publish/collect_review.py
openpype/settings/defaults/project_settings/photoshop.json
openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json

Creating review in Photoshop is configurable by settings
Some studio might want to skip creating and publishing review by default. Now it could be configured in 
`project_settings/photoshop/publish/CollectReview/publish`.
Artist might always override by clicking on a square icon next to review.
1. Disable publishing of review in `project_settings/photoshop/publish/CollectReview/publish`
2. Publish in PS - Extract REview, Extract Burnins should be skipped
3.

Photoshop: review can be turned off

---

openpype/pipeline/load/utils.py

Fixes typo. Good to refactor now since it's pretty much unused.
1. Run some `filter_containers` and make sure there is one that's not found.

Fix typo in ContainersFilterResult namedtuple `not_foud` -> `not_found`

---

openpype/hosts/hiero/api/lib.py

Hiero inventory check is working again by using right kwarg in function.
~Fixed kwargs `repre_ids` -> `representation_ids` in `get_representations`.~ Refactored `check_inventory_versions` to use `filter_containers` from load utils which reduced the code and fixed the source issue.
1. Load "not last version" to hiero workfile
2. Reopen hiero
3. Scene inventory should show

Hiero: Fix inventory check on launch

---

openpype/hosts/maya/plugins/publish/validate_rendersettings.py

This fixes #3410 
The file format check for AOVs is skipped for Cryptomatte AOVs because Redshift always write it as "Cryptomatte (EXR)" format.
1. Set up scene with Redshift + Cryptomatte AOV and others
2. Ensure validation works as expected for file format (extension)

Maya: Redshift Skip aov file format check for Cryptomatte

---

openpype/style/data.json
openpype/tools/publisher/widgets/widgets.py

Fix PublishIconButton drawing disabled icon with the color specified.
Previously the color to draw in the `paint_image` logic was ignored when button was disabled because default color was applied to the disabled state. As such the disabled image always had a default "gray" state which QPushButtons generate.
Before:
(Only "reset" button is actually enabled here!)
After:
Note that the disabled color is a bit hardcoded like this and randomly chosen. I picked the direct color from `openpype/style/data.json` for `font-disabled` which was `#99A3B2` but that just didn't show well enough.
1. Check in different platforms, Python and Qt versions

Publisher: Fix PublishIconButton drawing disabled icon with the color specified

---

openpype/host/__init__.py
openpype/host/interfaces.py
openpype/hosts/traypublisher/api/pipeline.py
openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py
openpype/plugins/publish/collect_from_create_context.py

Proposing possible enhancements related to new publisher.
Instance object has `lifetime_data` where can creator add objects from scene or other objects not related to instance data, during publishing can be accessed using `lifetimeData` on instance. Renamed `INewPublisher` to `IHostPublish` -> match other interfaces and get rid of "new publisher" (`INewPublisher` kept for backwards compatibility, but we could remove it now?). Creators have method `apply_settings` to simplify initialization.
The `lifetime_data` were requested from Fusion implementation where node name is not enough to be able identify the node. I would say it's reasonable enough to provide this option too.

Publisher: Enhancement proposals

---

openpype/style/color_defs.py

Fix variable name `sat` -> `sat_str`
`sat` is actually undefined in the else statemen
This actually not being found earlier is due to the fact that saturation for `hsl` and `hsla` was never used without a percentage sign in the saturation value in the style `data.json`
1. Usage of these color definitions (e.g. run different UIs)

General - Color definitions - Fix variable name `sat` -> `sat_str`

---

openpype/modules/kitsu/utils/update_op_with_zou.py

In the case where the resolution of the project has been removed by a soft user that the resolution does not contain x, the update of openpype by zou crashes.
In case the character 'x' is not in the resolution of kitsu, this information is not updated.

Fix kitsu openpype sync without project resolution

---

openpype/tools/sceneinventory/window.py

Remove "saveWindowPref" property.
This should fix #3921 
Now Maya will not restore/remember the previous Scene Inventory position.
The UI will now behave similar to other hosts.
1. Start Scene Inventory - move it off-screen off to the side.
2. Close it down, close maya, save maya preferences, etc.
3. Restart Maya. 
Previously before this PR Maya would have reopened Scene Inventory in position where it was last time, now it doesn't.

Maya: Fix Scene Inventory possibly starting off-screen due to maya preferences

---

openpype/style/__init__.py
openpype/tools/publisher/widgets/border_label_widget.py
openpype/tools/publisher/widgets/list_view_widgets.py
openpype/tools/settings/settings/widgets.py
openpype/tools/tray/pype_tray.py
openpype/tools/utils/assets_widget.py
openpype/tools/utils/lib.py
openpype/tools/utils/overlay_messages.py
openpype/tools/utils/widgets.py
openpype/widgets/nice_checkbox.py

The `get_objected_colors` function is called very often - e.g. over 1500 times when opening the Settings UI - and did a full read of the style's color `data.json` and converted it to the color objects with an average of 0.0009s per call on my machine.
See original discussion in the comments [here](https://github.com/pypeclub/OpenPype/pull/3910#issuecomment-1257727856) where I've elaborated on the usage of the function in the Settings UI.
Do we want to return a deep copy to ensure any usage of the data doesn't influence the cache? - It does seem that with a deep copy the time taken for the function returns almost to the same as without the caching. (However that is only if the data.json is read from my local SSD of course)
1. Test whether colors are still correct in the UIs.

Style: Cache `get_objected_colors` function

---

openpype/hosts/maya/plugins/publish/validate_render_single_camera.py

Fixed import of `RenderSettings` in Maya validator.
Found out this issue after merge of [this PR](https://github.com/pypeclub/OpenPype/pull/3925) (The PR didn't cause it).
1. Validator "Render Single Camera" should work

Maya: Fix Render single camera validator

---

openpype/hosts/houdini/api/shelves.py
openpype/settings/defaults/project_settings/houdini.json

I was unable to start **Houdini Core 19.5.303 Py 3.7** on Windows due to the Shelf Set Manager implemented with #3652 
It would just hang on Houdini splash screen without continuing. What causes it exactly I'm not sure - but I had no shelves set or defined but the shelves still tried to create and or set shelves which apparently broken my Houdini start.
With the changes implemented here the default is now correctly fully empty to avoid warnings, it'll now also not try `get_or_create_shelf_set` if the shelf definition for that shelf is empty (like previous default value in settings).
Also instead of returning it'll now continue on entries that are invalid in settings.
I'd still like to figure out what exactly stops my Houdini from continuing past the splash screen - still investigating …

Houdini: Tweak Shelves set manager to ignore invalids

---

openpype/widgets/attribute_defs/files_widget.py

Cleanup code of files widgets used in publisher.
Handle moving around of items in files widget. Stack widgets in files widget to handle their size hints. Proper showing of empty widget on moving items around. Hide Drag'n'Drop label if user can't drop any.
Files widget changed a look when have no items in. The view is painted underneath so the beackground is dark grey.
1. Open TrayPublisher where files widget is available
2. Try to play with it to validate if reported issues that should be resolved do not happen.
Resolves https://github.com/pypeclub/OpenPype/issues/3837
Resolves https://github.com/pypeclub/OpenPype/issues/3836

Publisher: Files Drag n Drop cleanup

---

igniter/bootstrap_repos.py

In case of clean installation where there are not update zips available, OP tries to create the zip from the build and fails moving it to local app data folder if directory of the version doesn't exists. This PR is fixing it.
Delete all versions from local app data. Be sure you have no newer version in update repository. Run Igniter and "install" OP. Everything should work.

Bug: Create missing version dir

---

openpype/hosts/maya/plugins/publish/collect_render.py

This is a fix for #3812 
This fixes the reported error and the node added incorrectly into the set is now logged with a warning. However, what the user originally tried in #3812 might still be unclear on how to solve correctly.
They should have done this: 🟢 
Instead of this: 🔴 
Note how the `lookMain` that was intended to be attached to the layer is not a member of `_renderingMain:Main` (which represents the Main layer) and instead `lookMain` is a member of the `renderingMain` instance directly.
We might want improve the logging or workflow to ensure the User is more aware of what they did wrong, because this is what is logged as warning now:
In the current stage it DOES allow the user to continue and publish - but it won't attach the render to `lookMain`.
1. Add `lookMain` into …

Maya: Warn correctly about nodes in render instance with unexpected names

---

openpype/lib/applications.py

Root environments can be used in enviornments of applications now.
We set them after host launch so they were not available at the moment when system settings environment variables were resolved.
1. Use `OPENPYPE_ROOT_WORK` in DCC environments
- e.g. `{"MY_ENV": "{OPENPYPE_ROOT_WORK}"}`
2. Launch the DCC
3. Check if the env is filled

General: Set root environments before DCC launch

---

openpype/hosts/photoshop/plugins/publish/collect_version.py

If Collect Version is enabled, everything published (`image`, `review`, even `workfile`) from workfile should carry its version number.
1. check that you have `project_settings/photoshop/publish/CollectVersion` enabled
2. publish workfile from PS, check all published images, reviews and workfile version

Photoshop: missed sync published version of workfile with workfile

---

openpype/hosts/photoshop/plugins/publish/extract_review.py
openpype/hosts/traypublisher/api/plugin.py
openpype/lib/transcoding.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
openpype/settings/defaults/project_settings/photoshop.json

Previously PS was creating .mov even for single frame review. This PR allows to create and upload single image instead.
Next paragraf is more elaborate text with more info. This will be displayed for example in collapsed form under the first sentence in a changelog.
Still in progress as Play button under Versions metadata is finicky, Play button on thumbnail in version list seems to work fine.
1. Double check jpg options for Photoshop ExtractReview in Setting
2. Publish workfile that has single or no `image` instance.
3. Check that `publish/review` folder contains high res review
4. Check in Ftrack by clicking on Thumbnail in Versions list that high res image pops up

Photoshop: create single frame image in Ftrack as review

---

openpype/widgets/attribute_defs/files_widget.py

Widget for `FileAttrDef` can handle multivalue so multiselection in publisher don't crash on attributes creation.
This is a fast fix to have it "not crashing" we could maybe (in future) find better way how to handle multiselection in this widget.
2. Create at least 2 instances using same simple creator (enter files there)
3. Multiselect instances in UI
4. Files widget should not cause crash and be disabled

AttributeDefs: Fix crashing multivalue of files widget

---

openpype/hosts/traypublisher/api/plugin.py
openpype/pipeline/create/context.py

Give ability to mark instance object as stored to clear changes.
New created instance have all attributes marked as changed (because there were none data before) but in most of cases are also stored to scene during creation so they should be marked as stored. Implemented method `mark_stored` to "clear changes" and from that moment instance object behave like has no changes.
Method `mark_as_stored` must be called explicitly in creator. I didn't find a good place how to automate it with being sure that the instance was actually stored. Traypublisher does it.
Testing requires some code changes. Easiest is probably using prints in tray publisher:
1. In `~/openpype/hosts/traypublisher/api/pipeline.py` add print of `update_list` variable in `update_instances`
2. Open TrayPublisher
3. Create an …

Publisher: Instances can be marked as stored

---

openpype/tools/tray/pype_tray.py

Set `AA_EnableHighDpiScaling` before QApplication is initialized.
1. Launch of tray should not cause warning `"Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created."`

Tray: Change order of attribute changes

---

openpype/hosts/houdini/plugins/publish/validate_workfile_paths.py

Fix error on `param=None` for HDA file references
Previous error:
1. Publish workfile from Houdini with HDAs loaded

Houdini: Fix validate workfile paths for non-parm file references

---

openpype/hosts/maya/plugins/publish/extract_playblast.py

When there is a version string in subset name, like foo_bar_v004  and that subset name is used for review, clique  has trouble collecting playblasted sequences for it because it tries to parse version string as a frame number, resulting in multiple collections.
Defines the pattern of the filename in `clique.assemble()`
Instead of 
```
collections, remainder = clique.assemble(collected_files,
minimum_items=1)
```
Uses
```
pattern_frame = [r'\.(?P<index>(?P<padding>0*)\d+)\.\D+\d?$']
collections, remainder = clique.assemble(collected_files,
minimum_items=1,
patterns=pattern_frame)
```

General: version string in subset name break file sequence collection in review

---

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py

During refactoring of Maya Deadline submitter, we've accidentaly dropped Renderman specific hacks. This is returning back one of them. 
Renderman integration in Deadline relies on plugin info `OutputFilePath` to be set differently than in other renderes. I has to point directly to the file output, unlike with other renderers where this can be further expanded by `OutputFilePrefix`
Renderman renders should render and publish correctly

Maya: Deadline OutputFilePath hack regression for Renderman

---

openpype/hosts/fusion/api/lib.py
openpype/hosts/fusion/api/menu.py
openpype/hosts/fusion/api/pipeline.py
openpype/hosts/fusion/api/pulse.py

Implements "save", "open" and "new" OpenPype events based on Fusion notifications of certain events.
Note that the Fusion events may not be 100% reliable. It could still be that a 'different action' might need to be listened to - but these events implemented now seemed reliable enough.
This adds a background QThread with the OpenPype menu which will listen to the Fusion events for comp open, save and new comp. This has the downside that IF you were to ever open the OpenPype menu twice (or more times) that the Events will be heard multiple time and each running instance of the menu would then trigger the callbacks to happen.
As such - a next step likely would be to figure out a way for the menu to just get raised instead of re-requested to open if it was already opened for the current …

Fusion: Implement callbacks to Fusion's event system thread

---

openpype/plugins/publish/validate_version.py

PS and AE allow synchronization of workfile version (version number from work workfile) as a version of all published items.
This could result in unwanted overwrites of existing version, this Validator protects from this.
1. enbale sync workfile version in photohop
2. try in PS publish workfile with a version number that is already published

General: Added Photoshop and Aftereffects into ValidateVersion

---

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
openpype/settings/defaults/project_settings/maya.json

`RenderSetupIncludeLights` must be either set to 1 or 0 or not at all. This PR is adding default value for edge cases where this is not handled. Without it, DL is crashing.

Maya: Set default value for RenderSetupIncludeLights option

---

openpype/hosts/maya/api/customize.py
openpype/hosts/nuke/api/utils.py
openpype/tools/launcher/actions.py
openpype/tools/launcher/lib.py
openpype/tools/launcher/window.py
openpype/tools/standalonepublish/app.py
openpype/tools/tray/pype_info_widget.py

Import `resources` directly instead of through api.

General: Use direct import of resources

---

openpype/hosts/houdini/plugins/load/load_image.py
openpype/hosts/houdini/plugins/load/load_usd_layer.py
openpype/hosts/houdini/plugins/load/load_usd_reference.py

Refactor container schema key value `avalon-core:container-2.0` -> `openpype:container-2.0`
These were the only remainders using the old schema value
Not sure how relevant still with #3046 in progress. But just noticed this was the only usage of the old schema value.
1. Load + update Houdini containers for image and USD.

Houdini: Refactor container `schema` value

---

openpype/plugins/publish/integrate_thumbnail.py
openpype/plugins/publish/preintegrate_thumbnail_representation.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json

Thumbnail representations are needed for Ftrack integration to show something in Versions. This provides more explicit configuration if they should be integrated, eg. stored in DB.
This PR provides setting up explicit profiles (host, task name, task type, subset, family) to enable/disable integration (eg storing in DB AND storing thumbnail in 'publish' folder)
Storing in publish folder might be sometimes confusing for artists.
This adds explicit step, if no profile gets added, state as is still remains.
In most cases thumbnail representations shouldn't be integrated. There is no standardization right now if the thumbnail repre gets  stored or not. 
After customer issue it was decided that more control could be beneficial, It could be approached that configuration gets added to each host, …

General: Control Thumbnail integration via explicit configuration profiles

---

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
openpype/settings/defaults/project_settings/webpublisher.json
openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json

With this PR it is possible to keep same version for all published items via WP (without studio processing).
Artist is uploading `.psd` and `.png`, it should look for highest published of `workfile (.psd)` or `image (.png)`, increase this by 1 and use this version number for BOTH workfile and image instances.
It looks for max version number, from both subsets, eg. if more `image` than `workfile` is published , workfile version number will follow image one.
1. set `Sync next publish version `project_settings/webpublisher/publish/CollectPublishedFiles`
3. publish only .psd (maybe couple of times)
4. publish both .psd and .png >> resulting version for .png should match to .psd (eg. there will be gaps in images versions)

Webpublisher: use max next published version number  for all items in batch

---

openpype/pipeline/context_tools.py

This is wrong function for what it is supposed to do. It raises an error because a string is tested like a class during the process, which is not the correct behaviour.

Fix: Inventory action path wrong functions leads to errors

---

openpype/plugins/publish/integrate.py

Preserve existing subset group if instance does not set it for new version
[Came up on discord](https://discord.com/channels/517362899170230292/517382145552154634/1029755458069729412)
1. Publish e.g. a new `pointcacheMain` version that was previously manually added in Loader to a subsetGroup. 
2. Group should now be preserved after publish.

Integrate: Preserve existing subset group if instance does not set it for new version

---

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py

Older Maya (Python2) doesn't like declaration of attr.s without (object)
This handles issue when `Submit Render to Deadline` doesn't show up in Publish and when manually imported in Maya console it throws 
```
```
Maybe this is not needed as new Maya's (with Python3) might not have an issue with it, but it just happened to me on Maya 2019 and on same day someone from community on Discord reported it too.
https://discord.com/channels/517362899170230292/517382145552154634/1029628902701805609
I don't see it to be too offensive to have object as an argument there for now.
1. Publish from Maya to DL
2. `Submit Render to Deadline` should be visible during

Maya: add object to attr.s declaration

---

openpype/hosts/maya/plugins/publish/extract_layout.py
openpype/hosts/unreal/plugins/load/load_alembic_staticmesh.py
openpype/hosts/unreal/plugins/load/load_layout_existing.py
openpype/pipeline/workfile/path_resolving.py
openpype/settings/defaults/project_settings/unreal.json
openpype/settings/entities/schemas/projects_schema/schema_project_unreal.json

Loader for layouts from Maya for existing scenes in Unreal.
This layout loader will:
- Match assets in the scene and create the containers for all of them.
- Loads assets that are in the layout, but currently not in the scene.
- Removes from the scene the assets that are not in the layout.
1. Manually import some assets in the unreal project (the assets should be imported from published FBXs or ABCs).
2. Instantiate those assets in a level.
3. Load the layout.

Unreal: Layout Loader from Maya for Existing Scenes

---

inno_setup.iss

This little fix is adding verison string to the shortcut name created on Windows when installed to differentiate between multiple installed versions.

Add version to shortcut name

---

openpype/hosts/blender/plugins/publish/validate_camera_zero_keyframe.py
openpype/hosts/blender/plugins/publish/validate_mesh_has_uv.py
openpype/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py
openpype/hosts/blender/plugins/publish/validate_no_colons_in_name.py
openpype/hosts/blender/plugins/publish/validate_transform_zero.py

Removed and replaced `openpype.api` imports in blender.
1. All validators should load and work

Blender: Remove openpype api imports

---

openpype/modules/ftrack/python2_vendor/ftrack-python-api/source/ftrack_api/session.py

Python 2 ftrack_api is caching server schema to user's directory so there are not issues with permissions on linux.
1. There should not be issues with caching server schema on linux machines

Ftrack: Fix schema cache for Python 2

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

"tags" might be missing on representation, this fixes direct approach
Solves:
1. publish review in Maya, shouldn't fail in `integrate_ftrack_component`

Fix - tags might be missing on representation

---

openpype/pipeline/create/legacy_create.py

Fixed import of 'get_subset_name' function in `LegacyCreator`.
Function `get_subset_name` was moved from `openpype.lib` to `openpype.pipeline.create` and modified arguments. This PR is using new function location and is handling different arguments.
```
PluginToolsDeprecatedWarning: Call to deprecated function 'get_subset_name'
Function was moved or removed. Please check content of deprecated function to figure out possible replacement.
```
1. Deprecation warning should not be printed when `LegacyCreator` is used to create instance in scene

General: Fix deprecated warning in legacy creator

---

openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py

Collect `originalBasename` data to be used in templates in Tray Publisher. 
This is useful for retaining original file name and it's use in publishing templates.

Tray Publisher: add `originalBasename` data to simple creators

---

openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py

Don't crash in collection when files are not filled with `IndexError`.
This is "UX" change to not crash in collector of simple instances when files are not filled but let it on validator. If files are not filled `originalBasename` key is not filled.
Crashed is happening after [this PR](https://github.com/pypeclub/OpenPype/pull/3988). I thought it could maybe cause known publish error but that would not show a nice UI error with list of crashed instances...
2. Create an instance without filled filepaths
3. Publishing should crash with validation error instance of IndexError

TrayPublisher: Original Basename cause crash too early

---

openpype/modules/kitsu/utils/update_op_with_zou.py

- Retrieve `nb_frames` from item instead of data.
- `Shot` type error at updating.
- Some black formatting.

Kitsu: 2 fixes, nb_frames and Shot type error

---

openpype/hosts/flame/api/workio.py
openpype/hosts/flame/hooks/pre_flame_setup.py

Use direct import of lib functionality in flame.
1. Flame should be integrated and workfiles functionlity should work

Flame: Import lib functions from lib

---

openpype/hosts/traypublisher/plugins/create/create_movie_batch.py

Batch mov creator does not support sequences anymore as it's redundant for mov files.
It is confusing to be able pass sequences of mov files into the input when movie files just can't support sequences.
2. Go to create page
3. Select `Batch Movies` creator
4. If multiple files are dropped to file input, they should never be grouped as sequence
- e.g. `asset_sh0010.mov` and `asset_sh0020.mov` should not be grouped as one item

TrayPublisher: Disable sequences in batch mov creator

---

openpype/lib/vendor_bin_utils.py
website/docs/admin_settings_system.md

Added mechanism to define custom paths to ffmpeg and oiio tools and more detailed validation of them.
Right now we're missing vendorized oiio tool for MacOs and don't have mechanism to be able allow different paths for them. Also we have issues on some linux distributions that executables we support are compatible with them. It is possible to define `OPENPYPE_FFMPEG_PATHS` and `OPENPYPE_OIIO_PATHS` which lead to custom paths where tool can be found. These tools are checked as before using executables from OpenPype build. Added one more layer of executable validation to check if they can be executed by executing them. FFmpeg tools are validated with executing `{tool} -version` arguments and oiio tools are validated executing `{tool} --help`. In both cases the return code should be `0` …

General: Custom paths to ffmpeg and OpenImageIO tools

---

openpype/hosts/maya/api/lib_renderproducts.py
openpype/modules/deadline/plugins/publish/submit_maya_deadline.py

This is fixing image prefixes for Vray and Redshift to not add `<aov>` token for outputs that are multipart (merged aovs).
Submit render to Deadline with merged AOVs from vray or redshift.
Close #3956

Maya: remove invalid prefix token for non-multipart outputs

---

openpype/hosts/maya/plugins/create/create_animation.py
openpype/hosts/maya/plugins/create/create_model.py
openpype/hosts/maya/plugins/create/create_pointcache.py
openpype/hosts/maya/plugins/create/create_rig.py
openpype/settings/defaults/project_settings/maya.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json

Adding the on/off option of write color sets attributes in _create_rig.py_
Adding swtiching on/off clickbox to override the boolean option of write_color_sets_arttirbute in _create_model.py_ and  _create_rig.py_

Maya: write color sets in  create_model

---

openpype/hosts/unreal/integration/UE_5.0/Source/OpenPype/Private/OpenPypeStyle.cpp

Little bug in order of includes in Unreal 5 OpenPype integration plugin.
Fixing error happening during the build:

Unreal: fix order of includes

---

openpype/hosts/unreal/hooks/pre_workfile_preparation.py

Change import of 'get_workfile_template_key' in unreal prelaunch hook.
1. Launch of unreal should not cause deprecation warning on creation of new workfile

Unreal: Fix import of moved function

---

openpype/lib/vendor_bin_utils.py

[This PR](https://github.com/pypeclub/OpenPype/pull/3982) broke python 2 compatibility of ffmpeg and oiio tool discovery.
Fixed missing `DEVNULL` constant in `subprocess` module for python 2. It is replaced with fake devnull file handler.
1. Try to get ffmpeg or oiio tools in Python 2 DCC

General: Fix python 2 compatibility of ffmpeg and oiio tools discovery

---

openpype/hosts/unreal/api/__init__.py
openpype/hosts/unreal/api/plugin.py
openpype/hosts/unreal/plugins/create/create_camera.py
openpype/hosts/unreal/plugins/create/create_layout.py
openpype/hosts/unreal/plugins/create/create_look.py
openpype/hosts/unreal/plugins/create/create_render.py
openpype/hosts/unreal/plugins/create/create_staticmeshfbx.py

This is simplifying code for Creator plugins in Unreal and dealing with issue that Creator stub was for some reason shown in Creator dialog as empty item.

Unreal: Remove redundant Creator stub

---

openpype/hosts/hiero/api/pipeline.py
openpype/hosts/hiero/plugins/publish/integrate_version_up_workfile.py
openpype/hosts/nuke/api/pipeline.py
openpype/hosts/nuke/plugins/publish/precollect_workfile.py

Replaced `openpype.api` imports with explicit imports in foundry hosts.

Nuke/Hiero: Refactor openpype.api imports

---

openpype/hosts/nuke/api/lib.py
openpype/hosts/nuke/api/plugin.py
openpype/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/defaults/project_settings/nuke.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json

Representation can be filtered by custom tagging in extract review
Extract review was filtering only on the publishing instance level and not able to aim directly at particular representation. We have to implement filtering method to be able to activate output preset only to particular representation.
- adding `custom_tag` as optional key to representation
- adding `custom_tags` to nuke extract review data movie plugin
- improving nuke's way of handling viewerProcess to include also display selector which is now pars-able from a string. The syntax is as follows:
- add string input to `project_settings/nuke/publish/ExtractReviewDataMov/outputs/baking/viewer_process_override` in case you want to add bake stream overide of `project_settings/nuke/imageio/baking/viewerProcess` (notice we hade …

Nuke | Global: adding custom tags representation filtering

---

openpype/plugins/publish/extract_review.py

Avoid crashes in extract review with older settings overrides.
[This PR](https://github.com/pypeclub/OpenPype/pull/4009) caused that extract review would crash with older settings overrides where `custom_tags` key is not available on output definitions so iteration over `None` is invalid operation. The tags validation also happened in all cases even if the valid state was already known. Removed unnecessary log messages.
1. Use extract review with older settings overrides on project and it should not crash.

General: Extract review does not crash with old settings overrides

---

openpype/pipeline/create/context.py
openpype/tools/publisher/control.py
openpype/tools/publisher/widgets/create_widget.py
openpype/tools/publisher/widgets/overview_widget.py
openpype/tools/publisher/widgets/publish_frame.py
openpype/tools/publisher/window.py
openpype/tools/utils/__init__.py
openpype/tools/utils/error_dialog.py
openpype/tools/utils/widgets.py

Handle failed operations of creator plugins in Publihser UI to safe-guard failed state.
If creator failed during one of their operations the UI could stuck without any way how to rollback and user have no idea that something went wrong. For this purposes all oprations on create context raise special exceptions. Exception hold information about each failed creator with error message and optionally traceback. This can be showed in UI as a dialog. The dialog shows a tabs per each creator which failed. Exceptions are handled on collect, update, remove and create. Create widget does not handle exceptions on it's own because it would not be possible in remotelly controllerd UI instead a controller trigger events when dialog should be shown.
Reset of controller does not trigger save …

Publisher: Catch creator errors

---

openpype/scripts/otio_burnin.py

Raise more specific error in burnins script when input does not have streams before otio ffprobe is called.
It would crash anyway but with cryptic error that subprocess failed to run in otio adapters. This can happen when input does not have any streams (invalid movie file).
Not sure how the movie file can be invalid (seems like `skip-handles` tag on single frame can cause it?). Issue created https://github.com/pypeclub/OpenPype/issues/4028
1. Invalid input movie file in burnins should cause error with more specific information.

General: More specific error in burnins script

---

.github/workflows/milestone_assign.yml
.github/workflows/milestone_create.yml

Milestones on Github used in workflows
All PR will be now labelled by milestone according to its target:
- target to `develop` will be milestone `next-patch`
- target to `release/**` will be milestone `next-minor`
In case of later renaming of milestone to release number, new set of  default milestones will be created, so they will be always available.
- for this to work properly, we will need to merge this PR to `main`, latest `release/` and `develop` branches.

workflows: adding milestone creator and assigner

---

openpype/pipeline/create/context.py
openpype/pipeline/create/creator_plugins.py
openpype/style/data.json
openpype/style/style.css
openpype/tools/publisher/constants.py
openpype/tools/publisher/control.py
openpype/tools/publisher/widgets/card_view_widgets.py
openpype/tools/publisher/widgets/list_view_widgets.py
openpype/tools/publisher/widgets/overview_widget.py
openpype/tools/publisher/widgets/widgets.py
openpype/tools/publisher/window.py

Give ability to have convertor plugins for conversion from legacy instances to new creators.
Added Convertor plugins which can collect `ConvertorItem` into `CreateContext`. These items are shown in UI next to instances with a label that the convertor plugin defines. Convertor collect items after Creator's collection so there should not be a clash if any creator would convert something automatically and also has access to shared data. Has 2 methods `find_instances` and `convert` both without any arguments. Plugin must be in files next to creators (can be in file with creator). In UI is conversion button always before creator attributes. So multiple conversion plugins can be selected and UI does not break when instances are selected too.
Create fake convertor in TrayPublisher e.g. …

Publisher: Convertors for legacy instances

---

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py

Thumbnail is not integrated as reviewable component and thumbnail to ftrack because of missing `"thumbnail"` key on representation.
1. Thumbnails from standalone publisher should be integrated to ftrack as thumbnails

StandalonePublisher: Fix thumbnail publishing

---

openpype/tools/experimental_tools/tools_def.py

Experimental tools can't import publisher at the moment because the import source has changed.
Import `PublisherWindow` directly from `openpype.tools.publisher.window`.
1. New Publisher callback in experimental tools should show

Experimental Tools: Fix publisher import

---

igniter/bootstrap_repos.py

Fixing bug where if on vanilla machine you install completely new version and you enter correct mongo into Igniter dialog, installation will fail because it was not checking for presence of `{major}.{minor}` folder. If that folder was missing, move renamed the zip file to its name and everything crashed.
- Delete every localised version in `%LOCALAPPDATA%`.
- Delete mongodb record from Credentials Manager/Keyring.
- Build OpenPype
- Run `openpype_console`
- Enter correct mongodb
- **Everything should work as expected**

Igniter: handle missing directory

---

openpype/hosts/maya/plugins/publish/extract_playblast.py
openpype/vendor/python/common/capture.py

This is partially solving issues with capture presets when incompatible flags broke publishing process of reviews. It will only print warning when capute couldn't apply the whole present, but it won't stop publishing.
Might close #4033

Maya: Soft fail when applying capture preset

---

website/docs/admin_settings.md
website/docs/admin_settings_system.md

Made some adjustments to the documentation. They mainly consist of changes to spelling, grammar, and punctuation along with wording to make aspects a bit more clear.
Some examples are adding bullet points when listing multiple parts of a specific item in a topic. Also adding emphasis in areas to reinforce ideas. Added some code formatting to words in the documentation that refer to specifically named areas in the OpenPype UI.
There will be further edits to the documentation from me, though I will be asking for some clarity on specific parts. Would it be more advantageous for me to work on the documentation for OpenPypev4?

Formatting and wording changes for grammar, spelling, and clarity.

---

openpype/hosts/houdini/plugins/load/load_ass.py

ASS loader was filling in only file name, not the whole path. This is fixing the problem.
Load ASS file with OpenPype in Houdini, everything should work as expected.

Houdini: fix wrong path in ASS loader

---

openpype/tools/publisher/publish_report_viewer/window.py

Publish report viewer tool is not storing paths to files which had been loaded but the creates a copy of the file so they're still available.
Publish report viewer keep last opened files in the view and with this PR the last opened reports are stored to specific directory so they're loaded automatically and because are not pointing to source file it is possible to add custom data (like label).
1. Open Publish report viewer tool
2. Load a report there
3. Change a label of the report
4. Close the tool
5. Open it again
6. The report should be there with the label

Publish Report Viewer: Store reports locally on machine

---

openpype/hosts/hiero/plugins/publish/precollect_instances.py

Collecting effect is working properly
Collecting effects is collecting all timeline effects on all layers.
1. open hiero testing scene
2. add clip which is created to be published
3. create track above it and add any effect
4. publish and see that effect instance is crated

Hiero - effect collection fixes

---

openpype/hosts/maya/api/lib.py

If you load content with many instances inside of it - you'll want this fix for `get_container_members`.
Previously the short (non-unique) names would be returned per instance from `cmds.referenceQuery` and then the call to `cmds.ls` afterwards would take each of these instances and for those return all instances.
It would turn 7000 instances into 7000*7000 = 49.000.000 long paths to be returned - and that's slow and basically just duplicates. Now it just returns the 7000 long paths.
For our scene this was a difference between 16 seconds for the call to 0.17 seconds.
I noticed this was slightly faster:
```python
reference_members = cmds.referenceQuery(ref, nodes=True)
reference_members = list(set(reference_members))
reference_members = cmds.ls(reference_members,
long=True, …
```

Maya: Fix very slow `get_container_members` calls for instances

---

openpype/tools/loader/widgets.py

Fix the comparison of representation names to match stored representation names in found combinations.
1. Make sure you have 2 or more subsets with representation that has at least one capital character in name
- e.g. "someRepre"
2. Open loader in DCC where you have available Loader plugin that can load the representation
3. Select group of subsets in loader view a right-click to shown context menu
4. The loader should be visible there

Loader: Fix comparison of repre name

---

openpype/tools/publisher/window.py

Reset of publisher controller happens defered so the UI has time to change sizes based on window size.
Because the reset happens too early on show the UI is not painted correctly. UI needs at least 3 event loops to propagate show, resize and repaint events properly. When all of that is done the reset can start and UI is not "stretched" to minim sizes.
1. Show Publisher in a DCC and see the difference on first show

Publisher: Better reset defer

---

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py

Fix occational issue on Deadline where `subprocess.check_output` is crashing.
We expect deadline has modified some functionality in `check_output` which cause crashes. Changed to use deadline process utils to run the process instead of subprocess.
1. Copy the plugin to deadline plugins
2. Run publishing
Resolves https://github.com/pypeclub/OpenPype/issues/3998

Deadline: Extract environment subprocess failure

---

openpype/tools/settings/settings/categories.py
openpype/tools/settings/settings/widgets.py

Avoid to show unsaved changes dialog if settings are in view only mode.
Even if settings UI is in view only mode change of project may trigger unsaved changes dialog which can allow to save settings. This PR makes sure the dialog is not showed.
2. Open second settings UI -> should ask to view only mode -> accept view only mode
3. Do some changes in project settings
4. Go to different project
5. No dialog should appear

Settings UI: Locked setting can't bypass lock

---

openpype/tools/publisher/control.py

Asset docs cache may store generator instead of list of asset documents.
This is future proof change that makes sure the output of `get_assets` is converted to list if is generator.
1. Nothing should change visually
2. Assets should be loaded in publisher UI

Publisher: Fix cache of asset docs

---

openpype/plugins/publish/extract_review.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
website/docs/project_settings/settings_project_global.md

Extract review have different outputs when input is single frame.
The goal is to avoid creating of single frame movie files but also give ability to create different review output and define it's resolution and tags. We've added one more additional filtering to output defintinions. It is possible to tell that the output will be created always (no matter how many frames input has), when input has 1 frame image or when input has 2+ images (or is movie).
Added default output definition to create HD png output if input is single frame and h264 is created only if input is video or has multiple frames.
Your current settings should work as they did before (nothing should break with older settings).
To test the feature: Change your settings to create an output definition on single frame, another …

General: Extract review single frame output

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

remove unnecessary underscore from subset name when rendering without AOVs
When publishing the render with the empty AOV name, it will create subset name with underscore at the end. (See the screenshot below)
This PR will fix the issue of adding extra underscore at the end when publishing the render.
This is only tested in maya Host.
1. Launch Maya in Openpype
2.  Create Render Main
3. In Render Setting, add an AOV and empties the AOV name
4. Save and Publish the scene.

remove underscore from subset name

---

openpype/hosts/hiero/api/plugin.py

Fixing wrong value in ui set from settings
Settings value was not correctly transferred onto creator ui. 
1. Open Hiero workfile
2. select a clip and hit OP Creator
3. Look to down to workfile start frame and it should be 1001

hiero: creator from settings with set maximum

---

openpype/hosts/flame/api/menu.py
openpype/hosts/flame/plugins/load/load_clip_batch.py
openpype/settings/defaults/project_settings/flame.json

Loading to multiple batches within a project is supported.
Using name of active Batch it is loading into, as part of name of loaded clip. 
Known issue is, there is no way it would load, multiply into one Batch.
1. Activate a Batch and then RMB click at Project manager, OpenPype/Load
2. Find a subset you want to load and RMB click select `Load to active batch`
3. Activate other Batch and repeate 2. on the same subset with the same representation. 
4. Notice it is loading with name of Batch in clip name.

Flame/Flare: Loading to multiple batches

---

openpype/hosts/nuke/plugins/load/load_clip.py

Resolving path to image sequence with hashes only at frame token.
Solving issue with resolving name to hashes even in other parts of name.
1. Open your testing workfile in Nuke
2. Open Loader and load image sequence, and some video file
3. It should load as excepted

Nuke: resolve hashes in file name only for frame token

---

openpype/tools/publisher/publish_report_viewer/widgets.py
openpype/tools/publisher/publish_report_viewer/window.py

Small fixes in publish report viewer.
Fix delete button position on row insert. The button was offset on first item insert because of outdate viewport size. Fix issue when all report items are removed. In that case it set report as `None` which was not checked.
- adding first report item should not offset remove button
- removing last remaining item from report tool should not cause crash

Publish Report Viewer: Fix small bugs

---

openpype/tools/publisher/window.py

Don't close publisher window on press of escape button.
1. Open publisher in host or open tray publisher
2. Hit escape on keyboard
3. Nothing should happen

Publisher: Ignore escape button

---

igniter/bootstrap_repos.py

This should fix the case where multiple hyphens were used in staging version pre-release part.
`foo-v3.14.6-nightly.2-x-y-x+staging` were not matched properly and so the staging status of the version couldn't be determined.
This happened with `--list-versions --use-staging` and when staging version was not set in the Settings (so the latest compatible with the build should be used)
Create multiple versions in update repository like
```
foo-3.14.6+staging
goo-3.14.6-something.1+staging
hoo-3.14.6-something-else.1+staging.boo
```
then
```sh
openpype-console --list-versions --use-staging
```
should list them all
> **Note**
> This will be probably obsolete in 3.15 where staging logic will be dropped. See #3979

Igniter: fix regex to match semver better

---

openpype/hosts/tvpaint/plugins/publish/collect_instance_frames.py
openpype/hosts/tvpaint/plugins/publish/validate_marks.py
openpype/hosts/webpublisher/plugins/publish/validate_tvpaint_workfile_data.py
openpype/plugins/publish/collect_anatomy_context_data.py
openpype/plugins/publish/collect_context_entities.py

Renamed collector `CollectAvalonEntities` to `CollectContextEntities` and changed how asset and task names are received.
Renamed the plugin and asset/task name is taken from `context.data` instead of `legacy_io.Session`.
We should change all remaining publish plugins to use context from `instance.data` (or `context.data` if is context based) instead of using `legacy_io.Session`.
In theory nothing should change or break. I'm not worried about local publishing, issues could come on farm or webpublisher. Please check if integration is going to right context (asset and task) in:

General: Collect entities plugin minor changes

---

openpype/lib/attribute_definitions.py
openpype/tools/attribute_defs/files_widget.py

Files widget is not case sensitive about dropped files.
Files widget validation of dropped files use extension as one of filters, but extensions dropped files were not lowered so the validation didn't allow to enter e.g. `.PNG` files.
1. Prepare e.g. png file with upper case extensions
2. Open TrayPublisher
3. Select `Image` family and tray drop the file to file input
4. It should allow you to drop it and publishing should finish successfully

Files Widget: Ignore case sensitivity of extensions

---

openpype/hosts/maya/plugins/load/load_yeti_cache.py

We hit this issue when the code was trying to create a group node that by pure luck had a node name that matched exactly with a name that was also in the namespace - thus maya would auto-rename the created group node.
As such `group_name != group_node` and the `.setOutlinerColor` failed to do its job correctly.
This fixes it by actually using the node name returned by maya.
Might be hard to test the specific edge case since I'm not entirely sure how we got the exact name match. But just testing a Yeti publish + load to begin with should be a good test.
1. Load a Yeti Cache.

Maya + Yeti: Fix yeti cache load using wrong name in edge case

---

openpype/hosts/maya/plugins/load/load_abc_to_standin.py

Adding Alembic Loader as Arnold Standin function as the Openpype Plugin
The user can load the published workfileswith abc format as Arnold Standin if the pusblished workfiles belong to model and pointcache family.
Doesn't have any for the current stage
1. Start maya in Openpype
2. Click "Load" from Openpype in maya
3. Right-click the workfiles which belongs to either model or pointcache family
4. Click Import Alembic as Standin
5. It will load the abc file as an arnold standin

Alembic Loader as Arnold Standin

---

openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json
openpype/tools/project_manager/project_manager/view.py
openpype/tools/settings/settings/constants.py

Define max number of frame start/end and clip in/out to 9 digits number in anatomy settings and project manager tool.
- Open project manager and change some frame or clip value to really high number.
- Open settings, go to a project anatomy and change some frame or clip value to really high number

General: Allow higher numbers in frames and clips

---

openpype/hosts/flame/api/plugin.py
openpype/hosts/flame/plugins/load/load_clip.py
openpype/hosts/flame/plugins/load/load_clip_batch.py

Flame is loading clips with correct colorspace mapping
Mapping can be added at Studio settings/Project tab: `project_settings/flame/imageio/profilesMapping`. 
1. Make sure mapping is set in `project_settings/flame/imageio/profilesMapping`
2. Load any published subset version 
3. See the colorspace is correctly set

Flame: Loading clip with native colorspace resolved from mapping

---

openpype/client/entities.py
openpype/hosts/traypublisher/plugins/create/create_online.py
openpype/hosts/traypublisher/plugins/publish/collect_online_file.py
openpype/hosts/traypublisher/plugins/publish/validate_online_file.py
openpype/pipeline/create/creator_plugins.py
openpype/plugins/publish/integrate.py
openpype/settings/defaults/project_anatomy/templates.json
openpype/settings/defaults/project_settings/global.json

This PR is adding new creator/workflow for Tray Publisher called **Online** - it is using specific template to retain original file name of the published file - it is designed for video files. That original file name is also used for subset name. By default it will prevent publishing if file already exists, but there is optional validator that can be disabled if necessary.
> **Note**
> This is very workflow specific file that can be useful but should be in v4 probably moved out from the code base to custom repository.

Online family for Tray Publisher

---

openpype/hosts/nuke/api/pipeline.py
openpype/hosts/nuke/plugins/load/load_camera_abc.py
openpype/hosts/nuke/plugins/load/load_clip.py
openpype/hosts/nuke/plugins/load/load_effects.py
openpype/hosts/nuke/plugins/load/load_effects_ip.py
openpype/hosts/nuke/plugins/load/load_image.py
openpype/hosts/nuke/plugins/load/load_model.py
openpype/hosts/nuke/plugins/load/load_script_precomp.py

Loaded nodes are opening to first tab
OpenPype tab was not important to see and user always needed to switch back to native first tab.
Also every created node was also opening property panel in bin and users were mentioning it would be improvement ux if we had closed them.
1. start testing script in nuke
2. Open loader and load anything
3. notice property bin is closed
4. also open created node and notice first tab is opening.

Nuke: loaded nodes set to first tab

---

openpype/hosts/nuke/plugins/load/load_image.py

Nuke load image is setting correctly first frame
Start frame is taken from script first frame.
1. Open testing script in Nuke
2. open loader and point to subset with image sequence
3. chose Load Image and do not set anything in options
4. notice it loads first script frame and sets it to first/last frame

Nuke: load image first frame

---

openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
openpype/modules/kitsu/plugins/publish/integrate_kitsu_review.py
openpype/settings/defaults/project_settings/tvpaint.json
openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json

When publishing, upload only the review file on kitsu.
We realized that when publishing exports from TvPaint, all the files are uploaded to Kitsu (all reviews for renderLayers and renderPasses) but the only one we really need is the main review. Is our logic correct or are all the files are necessary for Kitsu to work properly ?

TvPaint: Upload only main review file on kitsu from TvPaint

---

openpype/hosts/maya/api/lib_renderproducts.py
openpype/hosts/maya/api/lib_rendersettings.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py

fixing the bug for the regex filter not excluding the aov in RedShift
See(https://github.com/pypeclub/OpenPype/issues/4057)
Multipart boolean option of the renderers (RedShift and Arnold) is broken in lib_renderproduct.py, which submits a wrong information to collect_render.py(i.e. multipart is always True even when it is being turned off..), This cause the review option not working with regex filters, which depends on whether multipart is on /off.
For this fix, 
if “force combine beauty and AOVs into single file” or “multipart EXR” in Redshift Render Setting is off, it will filter out the renderpass according to the regex filter set in the Openpype Setting. (I set .*([Bb]eauty).* as filter)
If either one is on, it will show both beauty and Cryptomatte pass.
If mergeAOVs or multipart in …

Maya: aov filtering

---

openpype/modules/slack/plugins/publish/collect_slack_family.py
openpype/modules/slack/plugins/publish/integrate_slack_api.py

This handles issue with missing 'published_path' key caused by not publishing thumbnail.
It also handles task better, it takes task info from instance first, handles legacy case when task data is only string and not dict as expected.
1. Enable Slack module
2. Prepare `project_settings/slack/publish/CollectSlackFamilies/profiles/0/channel_messages/0/channels/0`
3. Make sure that thumbnail won't get published in `project_settings/global/publish/PreIntegrateThumbnails`
4. Publish

Slack: notification fail in new tray publisher

---

openpype/lib/attribute_definitions.py
openpype/tools/attribute_defs/widgets.py
openpype/tools/publisher/widgets/widgets.py

Hide unknown publish plugin values to avoid user's confusion.
We showed unknown attributes stored on instance to user which could easily cause confusion because the showed key would not tell user (or us) almost nothing. But it make sense to show the unknown attribute on instances thus there were kept untouched. Mostly visible after changing optional validators as required.
Added option to define attribute definition as "hidden" or "disabled" (both only for UI purposes). Also was added option to define hidden attribute definition that hold any value defined by code.
1. Set validator supported by Publisher tool as optional
2. Open a host which support Publisher tool and create an instance where the validator would show
3. Close the host and change settings of the validator to be required
4. …

Publisher: Hide unknown publish values

---

openpype/tools/publisher/widgets/card_view_widgets.py
openpype/tools/publisher/widgets/list_view_widgets.py
openpype/tools/publisher/widgets/overview_widget.py
openpype/tools/publisher/widgets/tabs_widget.py
openpype/tools/publisher/widgets/widgets.py
openpype/tools/publisher/window.py
openpype/tools/utils/host_tools.py

Publisher has option to be opened on specific tab when showed.
It is possible to show publisher window on specific tab. Added option to open publisher on create/publish tab on first restart when there is at least one instance. Tasks combobox is extended to full width.
1. Pass `tab` keyword argument with value `"create"` or `"publish"` when opening publisher.
2. Check if the tab is set to what was passed

Publisher: Open on specific tab

---

openpype/hosts/photoshop/plugins/create/create_legacy_image.py

In photoshop on Windows when we select multiple layers to create an instance, there's a pop-up window that appears behind the Instance Creator window, but we can't select this window.
The pop-up asks the users if they want to create one instance per layer or not, but we can't select what to do since it's not the active window (the Instance Creator window is). So the solution seems to make the Creator Instance window the parent of the pop-up window.
With the pop-up stuck behind the Instance Creator window:
With the Instance Creator window as parent of the pop-up:

Photoshop: bug with pop-up window on Instance Creator

---

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py

Deadline prelaunch plugin have more sofisticated build version resolving to be used.
Before this PR deadline global pre launch plugin always used last openpype build it found (without comparing prerelease part of version string) which cause issues if the requested version from job lead to older build version.
This is fixing edge case usages and development testing. Before this PR the deadline could find for example 3 build versions `3.14.5`, `3.14.6-nightly.5` and `3.14.6` from that point both builds `3.14.6-nightly.5` and `3.14.6` were considered as same versions and if job requested version `3.14.5` the environments injection would fail because build `3.14.6` could not find the zip for `3.14.5`.
1. Prepare multiple build with different versions for deadline plugin
2. Submit multiple …

Deadline: Build version resolving

---

openpype/hosts/maya/plugins/publish/extract_look.py

Fix validation of maketx executable in maya.
Extract look validated if executable returned from `get_oiio_tools_path` exists which did not on windows because of missing extension but that should not cause issues.
We should fix the source issue in `get_oiio_tools_path` but that would require more time.
1. ExtractLook in Maya should work on windows

General: Maketx executable issue

---

openpype/hosts/maya/plugins/publish/collect_look.py

If file node was connected not using its "primary data" plug, look collector was ignoring it - for example file node driving only with `Alpha Out` something down the line was missed by collector.
This is adding `allConnection` or `ac` flag to `cmds.listHistory` to get even those.
Create shader with texture using `Alpha Out` to drive something in the material. Look collector should pick it up correctly.

Maya: Looks - add all connections

---

openpype/lib/vendor_bin_utils.py

Enhance how executables are found when `find_executable` is called which cause that oiiotools return full path to executable.
Modified function `find_executable` which can now also fill extension to path to executable if is missing. With this change oiiotools return full path to executable with extension.
Proper fix of previous issue from PR https://github.com/pypeclub/OpenPype/pull/4136 .
Open `Tray > Admin > Console` and run this script:
```
from openpype.lib import get_oiio_tools_path
print(get_oiio_tools_path("oiiotool"))
print(get_oiio_tools_path("maketx"))
```
Output on windows should return full path to executabls with extensions. It should also still work on linux and mac (if the executables are available there).

General: Find executable enhancement

---

openpype/tools/standalonepublish/widgets/widget_drop_frame.py

Dropped directories in the Standalone Publish tool are not handled.
When dropping a directory in the Standalone Publish tool, the content of the directory is not expanded.
The publish then crashes during the integration (in the "integrate_new" plugin) with an "Access Denied" error.
The fix is however already present, but not used (call to the ```_get_all_paths``` function).
The error is due to the ```copyfile``` function being called with a directory as the ```src``` parameter (though a file is expected).
The code already contains the fix to expand the directories:
```
paths = self._get_all_paths(in_paths)
```
However, the newly created list ```paths``` is not used in the following ```for``` loop:
```
for path in in_paths:
...
```
1. Open the Standalone Publish tool.
2. Select a project, …

Fix: Standalone Publish Directories

---

openpype/modules/ftrack/lib/avalon_sync.py

Fix issue when asset has doubled last parent.
The issue happens when mongo id is not filled in ftrack but entity exists in mongo. Source of issue is because of loggins path of entity which adds parent's name to parens to log it's path but did not create copy of parents list.
The issue happened in most of cases during editorial publishing where both ftrack and mongo entities are created and ftrack did not fill mongo id in custom attributes.
1. Sync a project from ftrack
2. Remove Avalon Mongo ID value from entities in ftrack
3. Remove `ftrackId` from assets data in mongo
4. Sync project again
5. Check mongo values where should be all parents right
NOTE: Second sync form ftrack would fix the issue so make sure you sync only once after values removement.

Ftrack: Fix occational double parents issue

---

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py

~Integrate ftrack api is reseting ftrack api session on integration.~ Integrate ftrack api is re-configuring ftrack api locations on integration.
~Reset session before each instance is processed to trigger recache of locations which should help to fix the issue.~
Reset of session caused loose of local cache data which would require to requery all information again and again.
First fix was to create new session for each processed instance and close it afterwards but the closing of session cause closing of all sessions in process.
Since I wasn't able to reproduce source issue I cannot describe testing notes for source issue.
- Ftrack integration should work at least the same way as did

Ftrack: Reset session before instance processing

---

openpype/hosts/blender/plugins/publish/extract_abc_animation.py

Implemented extractor for Alembic Animations in Blender.

Blender: Extract Alembic Animations

---

openpype/plugins/publish/extract_review.py

Extract review can handle handles offset if input is sequence.
Source of the issue comes when extract review has set tag `no-handles` and input is sequence of images in that case are combined arguments `-start_number` and `-ss` and it seems that `-ss` should not be used with sequence but is better to change `-start_number` value instead.
Validate if output of extract review is ok. Prepare asset with handles and settings with same output but one have `no-handles` tag

General: Extract review handle start offset of sequences

---

tools/run_mongo.ps1

If mongo database directory was missing, the tool would exit without description.
1. Ensure mongo database does not exist.
2. Run `tools/run_mongo.ps1`.

Ensure Mongo database directory exists in Windows.

---

openpype/hosts/maya/api/lib.py
openpype/hosts/maya/plugins/create/create_pointcache.py
openpype/hosts/maya/plugins/publish/extract_pointcache.py

Optional viewport refresh on pointcache extraction.
Sometimes you need the viewport to refresh for example when dealing with the bullet plugin.
1. Create pointcache.
2. Enabled refresh.
3. See the viewport update as extraction is done.

Maya: Optional viewport refresh on pointcache extraction

---

openpype/hosts/maya/plugins/publish/extract_playblast.py
openpype/hosts/maya/plugins/publish/extract_thumbnail.py

Disable viewport Pan/Zoom on playblast extraction.
1. Create camera with Pan/Zoom enabled in Maya.
2. Create review.
3. Publish and check Pan/Zoom was disabled in review.

Maya: Disable viewport Pan/Zoom on playblast extraction.

---

openpype/hosts/unreal/integration/UE_4.7/Source/OpenPype/Private/OpenPypePublishInstance.cpp
openpype/hosts/unreal/integration/UE_4.7/Source/OpenPype/Private/OpenPypePublishInstanceFactory.cpp
openpype/hosts/unreal/integration/UE_4.7/Source/OpenPype/Public/OpenPypePublishInstance.h
openpype/hosts/unreal/integration/UE_4.7/Source/OpenPype/Public/OpenPypePublishInstanceFactory.h
openpype/hosts/unreal/integration/UE_5.0/Source/OpenPype/Private/OpenPypePublishInstance.cpp
openpype/hosts/unreal/integration/UE_5.0/Source/OpenPype/Private/OpenPypePublishInstanceFactory.cpp
openpype/hosts/unreal/integration/UE_5.0/Source/OpenPype/Public/OpenPypePublishInstance.h
openpype/hosts/unreal/integration/UE_5.0/Source/OpenPype/Public/OpenPypePublishInstanceFactory.h

The UOpenPypePublishInstance now uses the UDataAsset to store references to saved assets.
- UOpenPypePublishInstance derives from the UPrimaryDataAsset.
- Assets are now either Internal (UOpenPypePublishInstance monitors it's own directory and subdirectories for changes) or external (Assets which can be added in from other locations).
- Created new functions to get external, internal or all assets combined.
- AssetData variables use TSets to ensure there are no duplicate assets being added. A check is also implemented between the external and internal TSets which also monitor, if a user isn't trying to add an duplicate asset to external container, if it already exists in the internal one.
- There is also a check to make sure the user doesn't include the UOpenPypePublishInstance itself.
To …

Changed the UOpenPypePublishInstance to use the UDataAsset class

---

openpype/hosts/flame/api/plugin.py

Creator is detecting properly vertical alignment
Shots above each other with the same name are now properly detected and only hero track defined in Creator is used for metadata collection during publishing.

Flame: vertical alignment of layers

---

openpype/hosts/hiero/addon.py
openpype/hosts/nuke/addon.py

Nuke/Hiero started from Builded OpenPype on Windows does not have issues with unicode by removing `TCL_LIBRARY` and `TK_LIBRARY` environment variables before start of Nuke and Hiero.
Issue is described in https://github.com/pypeclub/OpenPype/issues/4170 . The environments are forced to be removed before application start.
Follow steps from the issue.
Resolves https://github.com/pypeclub/OpenPype/issues/4170

Nuke/Hiero: Remove tkinter library paths before launch

---

openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
openpype/modules/deadline/plugins/publish/submit_celaction_deadline.py
openpype/modules/deadline/plugins/publish/submit_publish_job.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py
openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
openpype/pipeline/publish/publish_plugins.py
openpype/plugins/publish/collect_comment.py
openpype/plugins/publish/extract_burnin.py
openpype/plugins/publish/integrate.py
openpype/plugins/publish/integrate_legacy.py
openpype/settings/defaults/project_settings/global.json
openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json

Instances in publisher can have ability to set comment per instance.
Collect comment plugin also store comment to each instance in context (so all plugins using it can access it directly). Added plugin which define "comment" attribute per instance and have settings for which families is available. By default is disabled and for none families.
The same should work when instance is sent to farm. Comment should stay on instances (didn't test).
Modified instance data sent to farm to contain comment per instance to persist comment from UI.
1. Enable the `Collect Comment per instance` in settings and fill families by your choice (`project_settings/global/publish/collect_comment_per_instance`)
2. Run host which use new Publisher tool (e.g. TrayPublisher)
3. Create instance with family from …

General: Comment per instance in Publisher

---

openpype/plugins/publish/extract_thumbnail_from_source.py
openpype/plugins/publish/integrate_thumbnail.py

Integrate thumbnail can look to more places where thumbnail for instance could be found.
Before this PR was thumbnail found only on published representations or from context thumbnail. There are 2 missing sources: First is at key `"thumbnailPath"` on instance data and second is on not integrated representations. Added these 2 options.
1. Look for published representation with name `"thumbnail"`
2. Look for not published representation with name `"thumbnail"`
3. Look into instance data for key `"thumbnailPath"`
If any step has available value but the path is not valid then go to next step until hit end.
1. Thumbnails are integrated even if it's representation is not

General: Integrate thumbnail looks for thumbnail to multiple places

---

openpype/lib/file_transaction.py
openpype/plugins/publish/integrate.py

File transaction object can handle when source and destination path are the same.
Class `FileTransactions` does handle cases when source and destination are the same which means they don't need to be copied or backuped.
1. Run publishing where source files are the same as output files

File transactions: Source path is destination path

---

openpype/lib/transcoding.py

Don't define input channels if input is multipart exr.
When converting multipart exr for ffmpeg it can't handle definition of channels on input because there are multiple subimages which cause crash if oiiotool.
Extended few types in xml info result parsing and added ability to receive information about every subimage in exr.
The output has all subimages (which can be big exr) that is because ffmpeg then created transparent image without any content. Not sure why but it's an issue. Also if any subimage in the exr has attributes with invalid characters or too long value it would cause issues in ffmpeg too -> future enhancements.
1. It should be possible to convert multipart exr for ffmpeg (e.g. in extract review)

General: Oiio conversion multipart fix

---

openpype/hosts/nuke/api/lib.py

Regex pattern is now correctly detecting viewer
In case of Aces name convention if Rec.709 was used - regex pattern was falsely detecting Viewer as Rec only. It was causing wrong colorspace settings on OCIODisplay node.
1. Go to Nuke ImageIO settings and set `Rec.709 (ACES)` at your ACES project.
2. Publish and stop process during `Exctract Review Data Mov`. Look to OCIODisplay node and see there is Rec.709 set to Viewer.

Nuke: correct detection of viewer and display

---

openpype/lib/path_templates.py
openpype/pipeline/load/utils.py

When a representation is published from windows, the `data.template` is filled with backslashs (`{root[main]}\_OpenPype\PUBLISH\{hierarchy}\{asset}\{family}\{subset}\v…`). When trying to open this file on Linux, the root is resolved with forward slashes and if in case your local root ends with a forward slash (`/my/root/path/`), `os.path.normpath` returns `/my/root/path/\\_OpenPype\\PUBLISH...`, which is not a valid path.
This fix ensures this case doesn't happen by replacing all backslashes with forward slashes.

Fix: Template path wrong normpath for cross platform

---

openpype/modules/kitsu/utils/sync_service.py
pyproject.toml
website/docs/module_kitsu.md

gazu API connection token expires after a week. It is refreshed every week.
1. Run sync service: `.poetry/bin/poetry run python start.py module kitsu sync-service -l <login> -p <pwd>`
2. It never stops synchronizing

Feature: API token refreshed every week

---

openpype/modules/ftrack/event_handlers_server/event_first_version_status.py
openpype/settings/defaults/project_settings/maya.json
openpype/tools/standalonepublish/widgets/widget_family.py

* [Warning log with missing parenthesis.](https://github.com/pypeclub/OpenPype/commit/7772ac7ea9125e2d06d5e31cf5771bb7e2211ca1)
* String ```format``` applied to ```log.warning``` function instead of its string content.
* Standalone Publish ```widget_family```
* [Duplicate command to get the plugin from the selected item.](https://github.com/pypeclub/OpenPype/commit/605432cc5db24201a124a4bf220200f672f502bf)
* [Asset selection check.](https://github.com/pypeclub/OpenPype/commit/ba149de263a5edef4468e9822ee6e44b2f557789)
* Check if the ```asset_name``` is not empty, but should also check if not equal to  ```NOT_SELECTED```.
* Steps to reproduce:
* Without anything selected in asset browser, select a family in the list.
* The following message is displayed in the logs:
```
Asset '< Nothing is …
```

Various minor bugfixes

---

openpype/tools/settings/__init__.py

Settings tool does not crash if igniter is showed first.
Settings tool always created new QApplication in main function which caused crashes if any QApplication was create before that point (e.g. in igniter). It is first check if application was created.
1. Make sure that igniter will show (e.g. by temporary closing mongo server) when openpype is started with settings argument
2. After filling mongo url should the settings UI show without any issues
Resolves https://github.com/pypeclub/OpenPype/issues/4155

Settings UI: Don't create QApplication if already exists

---

openpype/hosts/maya/api/lib.py
openpype/hosts/maya/plugins/publish/extract_pointcache.py

This is a fix for `cmds.refresh` not being queryable. See https://github.com/pypeclub/OpenPype/pull/4144
Gone with the `cmds.ogs` route but slightly confusing that its a toggle.

Maya: pointcache

---

openpype/hosts/maya/plugins/publish/extract_thumbnail.py

Enable thumbnail transparency on extraction.
Missing transparency feature from playblast extraction.

Maya: Enable thumbnail transparency on extraction.

---

openpype/cli.py

Print help instead of running `tray` by default if headless mode is enabled and no command is entered.
The only reason is that trying to launch tray when `headless` is explicitly defined is "not right".
The command won't do anything if `openpype_gui` executable is used on windows (there is no right command to run in that case).
1. Start openpype executable with only `--headless` argument

General: Default command for headless mode is interactive

---

openpype/hosts/houdini/api/pipeline.py

Changed import and usage of `INewPublisher` to `IPublishHost` in houdini.
1. Houdini should work as did before

Houdini: Use new interface class name for publish host

---

openpype/modules/deadline/plugins/publish/submit_publish_job.py

Better way of passing environments.
In some occasions there was need for having default keys in job, even those were not yet used in previous dependency job so they could not be passed with list of filtered keys. 
The procedure is working now following way.
1. default set of environment variables are compiled
2. next class attribute `enviro_keys` is iterated and found keys are included or overridden from 1. step
3. last step is taking class attribute  `environ_job_filter` is iterated and available keys in previous job are included or overridden from 2. step
1. publish to farm to your favourite host
2. all should work as before

Deadline: improve environment processing

---

openpype/hosts/maya/plugins/create/create_layout.py
openpype/hosts/maya/plugins/publish/extract_layout.py

fix the assertion error shown in` extract_layout.py `when publishing layout.
fix the assertion error shown in` extract_layout.py `when publishing layout.
If the user creates instance for the content which is not loaded from the workfile loader, it will have an assertion error to warn the user to use the loaded content. Unlike the previous version, it wont show an asset with more than one containers as the assertion error.
N/A
1. load the content from any families
2. rename the content
3. create layout instance for the loaded content(s)
4. publish it
5. uses the loader to load the layout content.
1. create a new geometry or load a scene with geometry
2. create layout instance for the new geometry
3. publish it
4. it will trigger the assertion issue to tell you to use the loaded content

layout publish more than one container issue

---

openpype/lib/events.py

It seems that event callbacks were broken for all Python 2 hosts because of wrong check of function signature when a method was used.
To find out if arguments should be passed is tried to bound argumets to callback instead of checking the function specs on own. Also added option to pass event as kwarg to callback function (positional arguments have priority).
This PR was made because of issues in Publisher tool when combined with Nuke 12.* [in PR](https://github.com/pypeclub/OpenPype/pull/4006).
1. Try event callbacks in Python 2 host where are used for method bounding

General: Event callbacks pass event to callbacks as expected

---

openpype/hosts/nuke/api/lib.py

Subset filter works even mixture of letter sizes in subset name.
Once mixture of sizes was used (ex. `_this_ButThat`), subset filter was not able to detect correctly node override from imageio nodes preset.
1. Create new preset in `project_settings/nuke/imageio/nodes/overrideNodes`, which would override the **CreateWriteRender** plugin, with Node Node Class to `Write` from `project_settings/nuke/imageio/nodes/requiredNodes`
2. add subset name filter to `_bla_BlaBla`
3. add the `_bla_BlaBla` also to `project_settings/nuke/create/CreateWriteRender/defaults`
4. Open nuke, select a node, Create Render node and set Variant to _bla_BlaBla
5. created node should be pink

Nuke: fixed imageio node overrides subset filter

---

igniter/__init__.py
igniter/__main__.py
igniter/install_dialog.py
igniter/install_thread.py
igniter/message_dialog.py
igniter/nice_progress_bar.py
igniter/update_thread.py
igniter/update_window.py
setup.py

Replaced usage of `Qt.py` module with `qtpy` in igniter.
Igniter tools should work as usually.

Igniter: Use qtpy modules instead of Qt

---

openpype/hosts/blender/plugins/load/import_workfile.py

Implemented the importer for other blend workfiles.
The workfile importer will import everything from another blend file, but it will not create any container for it. It will just merge the content in the current blend file.

Blender: Workfile Loader

---

openpype/hosts/nuke/api/lib.py

Use `qtpy` in nuke host implementation instead of `Qt.py`.
Nuke UIs should work as did before (even in older then 13.*).

Nuke: Use qtpy in Nuke

---

openpype/hosts/flame/api/plugin.py
openpype/hosts/flame/plugins/load/load_clip.py
openpype/hosts/flame/plugins/load/load_clip_batch.py
openpype/settings/defaults/project_settings/flame.json
openpype/settings/entities/schemas/projects_schema/schema_project_flame.json

Layers can be renamed dynamically during loading to batch
Folowing settings were created for layer template and layer rename patterns:
- `project_settings/flame/load/LoadClipBatch/layer_rename_template`
- `project_settings/flame/load/LoadClipBatch/layer_rename_patterns`
Regular expression patterns could be used for detecting name patterns in loaded layers and if any match is found, then the layer is renamed to use of version context data and additional formatting keys found if the context of loading file and its layer. For example layer with name `rgba` and layer uid `BEAUTY:MasterBeauty` can be now renamed with template `{asset}_{subset} [{layerUID}]` to new name `shot01_renderMain [BEAUTY:MasterBeauty]`. 
This had been requested by a client who is using Flame for metadata slates. The …

Flame - loading multilayer with controlled layer names

---

openpype/hosts/hiero/api/launchforhiero.py
openpype/hosts/hiero/api/lib.py
openpype/hosts/hiero/api/menu.py
openpype/hosts/hiero/api/plugin.py
openpype/hosts/hiero/plugins/publish/precollect_workfile.py

Use `qtpy` in hiero host implementation instead of `Qt.py`.
Hiero UIs should work as did before (even in older then 13.*).

Hiero: Use qtpy in Hiero

---

openpype/hosts/flame/api/menu.py
openpype/hosts/flame/api/plugin.py
openpype/hosts/flame/startup/openpype_babypublisher/modules/panel_app.py
openpype/hosts/flame/startup/openpype_babypublisher/modules/uiwidgets.py
openpype/hosts/flame/startup/openpype_in_flame.py

Use `qtpy` in flame host implementation instead of `Qt.py`.
Flame UIs should work as did before.

Flame: Use qtpy in flame

---

openpype/settings/defaults/project_settings/global.json

Fill default values of new location of publish template settings. This PR breaks backwards compatibility of legacy settings.
From this PR settings in `project_settings/global/publish/IntegrateAssetNew/template_name_profiles` and `project_settings/global/publish/IntegrateHeroVersion/template_name_profiles` won't be used. They're still kept as "back doors" for those who forget or updated from older versions.
It is still possible to rollback by removing values in the new location to empty list. In that case the legacy values are used but it is not recommended as the schema will be removed in one of patch release completely.
Publishing should work as before and should publish to right place.

General: Fill default values of new publish template profiles

---

openpype/modules/base.py
openpype/modules/interfaces.py
openpype/pipeline/context_tools.py

Extended abilities of `IPluginPaths` to have methods for load, create and publish plugin paths. Use new methods to register plugins from addons.
Added more methods to collect paths to load, create and publish plugin paths. These methods are called on OpenPype plugins installation (was used only for create plugins before).
Renamed `collect_creator_plugin_paths` -> `collect_create_plugin_paths` on `ModulesManager` and `get_creator_plugin_paths` -> `get_create_plugin_paths` (added backwards compatibility and warning).
1. Loader plugins can be registered by addons
Resolves https://github.com/pypeclub/OpenPype/issues/4194

General: Extend 'IPluginPaths' to have more available methods

---

poetry.lock

Fix issue with incompatible gazu version in poetry lock and pyproject toml files.
Current creation of venv is crashing because of incompatible gazu versions.
```
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
SolverProblemError
Because openpype depends on gazu (^0.8.34) which doesn't match any versions, version solving failed.
at .poetry\venv\lib\site-packages\poetry\puzzle\solver.py:241 in _solve
237│             packages = result.packages
238│         except OverrideNeeded as e:
239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
240│         except SolveFailure as e:
→ 241│             raise SolverProblemError(e)
242│
243│         results = …
```

General: Update gazu in poetry lock

---

openpype/tools/publisher/control.py

Implement `__ne__` method in `CreatorType` for `!=` comparison in Python 2 DCCs.
It seems that the method must be explicitly implemented for Python 2 otherwise default implementation is used instead of negation of `__eq__`.
Create plugins should be visible in Publisher in any Python 2 DCC.

Publisher: Fix 'CreatorType' not equal for Python 2 DCCs
