ynput/OpenPype

openpype/widgets/nice_checkbox.py
Positoining of checker in `NiceCheckbox` is calculated properly in all Python 2 DCC.
Some values did not change type to float and kept their value as integer which cause insonsistency where the checker should be drawn. The issue was discovered in Nuke 12.*
Checker should move in Python 2 hosts as expected.
=> NiceCheckbox: Fix checker positioning in Python 2

openpype/hosts/maya/api/commands.py, openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/menu.py, openpype/hosts/maya/api/pipeline.py, openpype/hosts/maya/api/shader_definition_editor.py, openpype/hosts/maya/plugins/load/actions.py, openpype/hosts/maya/plugins/load/load_image_plane.py, openpype/hosts/maya/plugins/load/load_look.py, openpype/hosts/maya/plugins/publish/validate_assembly_transforms.py
Use `qtpy` in maya host implementation instead of `Qt.py`.
Maya UIs should work as did before (even in Maya 2020).
=> Maya: Use qtpy in Maya

openpype/hosts/max/api/menu.py
Use `qtpy` in max host implementation instead of `Qt.py`.
Max UIs should work as did before.
=> Max: Use qtpy in Max

openpype/hosts/houdini/api/usd.py
Use `qtpy` in houdini host implementation instead of `Qt.py`.
Houdini UIs should work as did before.
=> Houdini: Use qtpy in Houdini

openpype/hosts/hiero/api/plugin.py
Hiero creator gui is number input with improved min and max.
The number input for handles start/end is now allowing `0` input and workfile start is able to define `1001`. 
1. open Heiro
2. select a clip
3. go to OpenPype Create
4. go to bottom and notice the workfile is set to `1001`, before it only allowed to set it to `99`
5. also set Handle Start to `0` and it will stay at `0`
6. if all that works this PR is success!
=> hiero: creator gui with min max 

openpype/modules/slack/plugins/publish/integrate_slack_api.py
Unpublished review could caused an issues.
Added also better handling of missing keys in message. Previously if key was missing, message didn't get sent.
Now missing key is double escaped ({{}}) to update message or fix collection.
1. Put dummy key in message in `project_settings/slack/publish/CollectSlackFamilies/profiles/0/channel_messages/0/message` (for example `{missing_key}`)
2. Disable integration of review and publish something that produces review
=> Slack: notification fails because of missing published path

openpype/widgets/message_window.py
Fix access to width of geometry in `ScrollMessageBox`.
The `ScrollMessageBox` tried to access width of desktop by accessing `width` attribute but it is a method so comparison failed. 
Also renamed variable `max_len` to `message_len`.
We should maybe rewrite the whole dialog as the logic of size definition is not readable much. The dialog also contains "Copy to clipboard" button which is on right side next to OK and Cancel which is not very intuitive. Dialog does not have enabled close.
1. Use the dialog (Currently used only in Maya look loader)
Resolves https://github.com/pypeclub/OpenPype/issues/4243#event-8068289765
=> Scene Manager: Fix variable name

openpype/settings/defaults/project_settings/deadline.json
This PR is changing default value for mongo url collector to pass by default mongo url to Deadline jobs. Because of #4182 changed (fixed) passing of `OPENPYPE_MONGO` environment variable, it broke renders submitted to deadline to linux headless workers.
Resolves #4273
=> Deadline: fix default value for passing mongo url

openpype/modules/sync_server/providers/dropbox.py, openpype/modules/sync_server/providers/gdrive.py, openpype/modules/sync_server/sync_server.py
Fix check if site is active, eg. correctly configured to be used, only for active and remote site actually set on a project.
Previously it went through all configured sites, even if they weren't used.
Site might be configured as possible target, but artist might not use it. They are in studio and not using SiteSync at all etc.
Closes https://github.com/ynput/OpenPype/issues/4125
- Enable Site Sync module, create a SFTP(or Gdrive without any values filled)  site with wrong credentials and enable it for your production.
- Change your local settings to local and studio (not to the sftp site).
- Restart Tray, and look to the logs, it tries to connect when it shouldn't because the user settings don't ask for it.
=> SiteSync: sftp connection failing when shouldnt be tested

openpype/hosts/maya/api/workfile_template_builder.py, openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/pipeline.py, openpype/hosts/nuke/api/workfile_template_builder.py, openpype/hosts/nuke/plugins/load/load_backdrop.py, openpype/pipeline/create/creator_plugins.py, openpype/pipeline/workfile/workfile_template_builder.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_templated_workfile_build.json
Adding Creator Placeholder plugin implementation
New placeholders for creators are now available. Templates can be now build included publishable instances.
Several global abstractions at parent workfile building classes had to be altered. Creator plugin abstraction can now be implemented also into other hosts. 
1. Test in `\OP02_VFX_demo` ideally on **sh020**  because the template is expecting data from this project. Project can be deployed with `/tools/unpack_project.ps1` (follow instructions inside of the .ps1 file), [here](https://drive.google.com/file/d/1LQkF8r-6q-aD1iSELuHa68JEnAx8MVjb) is where you can download it from.
2. Download [following zip](https://drive.google.com/file/d/1cJCKO8AJzO9Nm7i5-zMMu8D0p2EtDo8Z/view?usp=sharing) and unpack it in project structure as follows.
3. …
=> Global | Nuke: Creator placeholders in workfile template builder

openpype/modules/ftrack/event_handlers_user/action_where_run_ask.py, openpype/modules/ftrack/ftrack_server/event_server_cli.py, openpype/modules/ftrack/ftrack_server/lib.py, openpype/modules/ftrack/scripts/sub_event_status.py
Fix issue with getting host IP address on MacOs machines.
There are 2 ways how host IP is tried to receive. If both fail `N/A` is used instead.
1. Start ftrack event server on MacOs machine -> report if other issues with appear
=> Ftrack: Fix receive of host ip on MacOs

openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/publish/collect_instances.py, openpype/hosts/maya/plugins/publish/validate_frame_range.py
This fixes:
- #4272 - Now handles are set as expected if `handleStart` and `handleEnd` attribute exists on the instance
- #3302 - Render Layer frame ranges are now also repaired - also works with explicit render layer overrides on a layer
- Create Render globals not working (errors) when Deadline module is disabled
1. Test Create Render with Deadline module disabled and with it enabled in a scene that **does not yet** have a `renderingMain` globals.
2. Check with different start+end frame + handles settings for an asset on renderlayers, but also on other instances like pointcaches and cameras.
=> Maya: Fix validate frame range repair + fix create render with deadline disabled

openpype/hosts/traypublisher/api/editorial.py, openpype/hosts/traypublisher/plugins/create/create_editorial.py, openpype/hosts/traypublisher/plugins/publish/collect_shot_instances.py
Traypublisher simple editorial supports multiple sequence files.
Multilayer edl files are now supported.
1. add multilayer edl files to sequence representations
2. add reviewable media
3. hit create and see nothing is broken
=> Traypublisher: simple editorial multiple edl

openpype/hosts/resolve/api/menu.py, openpype/hosts/resolve/api/plugin.py
Use `qtpy` in resolve host implementation instead of `Qt.py`.
Resolve UIs should work as did before.
=> Resolve: Use qtpy in Resolve

openpype/hosts/unreal/api/__init__.py, openpype/hosts/unreal/api/pipeline.py
This is quick fix for missing call to `maintained_selection`. This functionality isn't available in Unreal (yet), but it is still called in legacy creator code.
=> Unreal: fix missing `maintained_selection` call

openpype/host/host.py
Added `install` method to `HostBase` class with docstrings. The method is not abstract as is not required at least not at this moment.
The method was added so developers can see what methods should be implemented in host implementation for what cases.
Validate grammar and content of the docstring.
Resolves https://github.com/ynput/OpenPype/issues/4054
=> General: Added install method with docstring to HostBase

tools/create_env.ps1, tools/create_env.sh
This PR is getting rid of version restrain on Poetry version.
=> General: Unbind poetry version

openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py, openpype/plugins/publish/collect_comment.py
Comment might have not been collected when inserted only after collection phase which resulted in not sending comment to Ftrack.
Clean-up of comment and using only comments on instances is good step, but as far as we are still using old Pyblish, context comment should be kept as a fallback (comment might be filled after collection phase, in this case it is present only on context level. Eg. artists knows/sees that it is filled, but integrator prints it is not there. Another approach would be to disable comments  field after publish is started, but I didn't want to mess with Pyblish.)
Comment field in Publisher is controlled by `project_settings/global/publish/collect_comment_per_instance`. To show comment field this should be set:
1. publish anything in Standalone Publisher, fill comment …
=> General: missing comment on standalone and tray publisher

openpype/plugins/publish/extract_review.py
Adds `-vn` tag in ExtractReview.
This tag ignores any graphic data from secondary audio input. This solves an issue where audio stream should be used from mp4/mov. Without it ffmpeg uses graphical data from this input too.
1. add layer containing audio in mp4 into composition
2. publish from AE to DL
3. Publish to DL with layer containing only .wav
=> AfterEffects: Fix for audio from mp4 layer

openpype/hosts/maya/plugins/publish/extract_multiverse_usd.py
Fix for when animation was published from rig, `Extract Multiverse USD` was triggered even if no usd extraction was required.
Publish animation from rig.
=> Maya: Bug - Multiverse extractor executed on plain animation family

openpype/plugins/publish/collect_from_create_context.py
Removed line breaking Python 2 compatibility in collector for new publishing.
1. Instances should be collected in new publisher during pyblish process
=> General: Python 2 compatibility of instance collector

openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Fixing typos causing rollback failures in ftract sync.
=> Ftrack: fix typos causing bugs in sync

openpype/modules/slack/plugins/publish/integrate_slack_api.py
Query user and group information only if necessary.
When message contains '@' character, translation between users and Slack user id is necessar. This operation might hit rate limit and slows down publish process.
Trigger this querying only if absolutely necessary.
1. publish something that should trigger Slack notification
2. compare messages with and without @ character
=> Slack: user groups speedup

openpype/pipeline/create/legacy_create.py, openpype/pipeline/load/plugins.py, openpype/pipeline/workfile/build_workfile.py, openpype/pipeline/workfile/workfile_template_builder.py, openpype/tools/creator/model.py, openpype/tools/loader/widgets.py
Loader and Creator plugins can be disabled.
Added `enabled` attribute to `LoaderPlugin` and `LegacyCreator` plugins. Check the value in Loader tool and in Creator tool.
1. Set `enabled` to `False` on any Loader plugin
2. From that moment should not appear in loader tool
1. Set `enabled` to `False` on any Creator plugin
2. From that moment should not appear in creator tool
=> General: Loader and Creator plugins can be disabled

openpype/plugins/publish/extract_otio_review.py
Quality is improved when jpeg to jpeg review extracting
FFMPEG was reducing quality due increasing of compression in cases where jpeg sequence was used at reviewable clip sources. 
1. open our testing hiero project
2. add any jpeg sequence with nice clip
3. create two clips above each other at different layers
4. name one layer `review` and other `main`
5. select both clips and then OpenPype/Create > publishable clip
6. Define reviewable layer as `review`  and hit create
7. publish
8. look to created h264 mp4 reviewable and notice the quality is comparable
=> Exctract OTIO review has improved quality

openpype/modules/sync_server/providers/gdrive.py, openpype/modules/sync_server/sync_server.py, openpype/modules/sync_server/sync_server_module.py
Fix that (un)pausing a representation works only using the sync queue UI.
Fix #4311
- Added the `paused` condition to `get_sync_representations` aggregation.
- Refactored `is_representation_paused` to check into the database and unified with `is_representation_on_site`.
- Cleaned useless `_paused_representations`.
1. Add this integrator to your pipeline and play with pausing blocks
```py
import pyblish.api
from openpype.modules.base import ModulesManager
from openpype.pipeline import legacy_io
class IntegratePauseRepre(pyblish.api.InstancePlugin):
label = "Integrate Pause Representation"
order = pyblish.api.IntegratorOrder + 0.1
optional = True
hosts = ["blender"]
def process(self, instance):
manager = ModulesManager()
sync_server_module = manager.modules_by_name["sync_server"] …
```
=> Fix: (un)pause_representation doesn't work programmatically.

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/create/create_backdrop.py, openpype/hosts/nuke/plugins/create/create_camera.py, openpype/hosts/nuke/plugins/create/create_gizmo.py, openpype/hosts/nuke/plugins/create/create_model.py, openpype/hosts/nuke/plugins/create/create_source.py, openpype/hosts/nuke/plugins/create/create_write_image.py, openpype/hosts/nuke/plugins/create/create_write_prerender.py, openpype/hosts/nuke/plugins/create/create_write_render.py, openpype/hosts/nuke/plugins/publish/extract_render_local.py, openpype/hosts/nuke/plugins/publish/validate_output_resolution.py, openpype/plugins/publish/collect_from_create_context.py
New creators correctly checking nodes in scene for existing subset.
Latest publisher creator plugins are now correctly detecting if nodes in workfile node tree is having a node with the same subset name user wants to create. This way unique subset name is secured.
Error messages were having typos in all creators
1. open nuke in your testing workfile already converted with new publisher.
2. open Create from OpenPype menu and set family and variant matching any already created instance node. 
3. Error message should popup with clear message.
=> Nuke: new creators fixes

openpype/hosts/traypublisher/plugins/create/create_editorial.py, openpype/lib/attribute_definitions.py, openpype/pipeline/workfile/workfile_template_builder.py, openpype/tools/attribute_defs/widgets.py
Atrribute definition `EnumDef` has more specifically defined value and label.
The previous implementation expected dictionary where key is value and value is label which is unintuitive. This logic was kept for backwards compatibility (at least for time there are opened PRs which use `EnumDef` that way. Added option to pass list where each item is dicrionary with `"value"` and `"label"` to make it more explicit.
Changed items in currently used `EnumDef` to use explicit items.
1. Create editorial should show correct enum items
2. Workfile builder should show corrent enum items
=> General: Enhanced enum def items

openpype/hosts/maya/plugins/publish/validate_assembly_transforms.py, openpype/tools/project_manager/project_manager/window.py, openpype/tools/workfiles/files_widget.py
PR fixing usage of constants with QMessageBox with combination with PySide6 (where constants are not available on objects).
1. Use workfiles tool where is save changes prompt that crashed
2. This dialog is shown if there are unsaved changes in host
3. The dialog should show and should be possible to select what should happen
Missed that bug in https://github.com/ynput/OpenPype/pull/4255 . There still can be more wrong usage of constants in the code, any reports welcomed.
=> General: Use class constants of QMessageBox

openpype/hosts/photoshop/api/workio.py
When opening a png (or other non psd file) in photoshop, the save-as in workfile interface save with png extension intead of psd if we don't touch the select extension dropdown.
Set default extension to psd if file is not psd or psb.
=> Fix photoshop workfile save-as

openpype/hosts/houdini/plugins/publish/collect_inputs.py, openpype/hosts/houdini/plugins/publish/validate_alembic_input_node.py, openpype/plugins/publish/cleanup_explicit.py, openpype/plugins/publish/collect_anatomy_instance_data.py, openpype/plugins/publish/integrate_hero_version.py, openpype/plugins/publish/validate_containers.py, openpype/plugins/publish/validate_version.py, openpype/settings/lib.py, openpype/tools/publisher/widgets/assets_widget.py
A small collection of minor tweaks to plugins to improve usage in new publisher.
- Fix typo (missing space) in houdini plug-in
- Change "Validate Containers" label to "Validate Outdated Containers" so the Options appear more understandable.
- Refactor error for Validate Versions to KnownPublishError for nicer error report. Changes here are also focused on keeping it readable in the old publisher since it's a global plug-in.
1. Test the validations! :)
=> New publisher: Some validation plugin tweaks

.pre-commit-config.yaml
This PR is removing [black](https://github.com/psf/black) from pre-commit hooks.
Black was making automatic unintended changes in the code that were sometimes incompatible with the Houd rules. This can be configured, but lets remove it for now.
=> Pre-commit: Remove black

openpype/tools/creator/model.py
In the Create menu, sort the families by alphabetical order for better readability.
=> Sort families by alphabetical order in the Create plugin

tools/docker_build.sh
Along with switching to Python 3.9 a folder name of the docker build must be renamed accordingly.
=> change 3.7 to 3.9 in folder name

openpype/pipeline/anatomy.py, openpype/tools/push_to_project/control_integrate.py, openpype/tools/push_to_project/window.py
Fix removement of assets from root hierarchy level on project change in push to project tool.
Asses from previous project were not removed from root item so they stayed in hierarchy view.
Make sure you have at least 2 library projects
1. Run Push To Project action
2. Select 1st project
3. Select 2nd project
4. Assets from 1st project should not be visible in 2nd
=> PushToProject: Fix hierarchy of project change

openpype/hosts/unreal/plugins/load/load_layout_existing.py
Unreal load plugin `ExistingLayoutLoader` used direct mongo calls using `legacy_io.find_one` and imported from `openpype.api`. Both should not be used anymore.
Use `get_representations` function to get representations instead of direct queries. Replaced querying of representations one by one into 2 chunks. Added class attribute `delete_unmatched_assets` which stores value of `"delete_unmatched_assets"` from unreal settings (overriden classmethod `apply_settings`) -> removed import from `openpype.api`.
1. Loader should work as did before this PR (maybe faster)
=> Unreal: Don't use mongo queries in 'ExistingLayoutLoader'

openpype/plugins/publish/collect_otio_subset_resources.py, openpype/plugins/publish/integrate.py
Editorial now support in-place publishing
In-place publishing was missing some data to stream source file metadata. Now we are collecting metadata so downstream plugins are publishing it correctly
Exception in Integrate plugin needed to be added for renumbering destination files.
1. follow Settings setup from https://github.com/ynput/OpenPype/pull/4157
2. go to `project_settings/global/tools/publish/template_name_profiles` and make sure you have following input 
3. Add some image seqence to your testing project. My where `<project>/source/plates/shot01/v001/<name_of_file>.<number>.<ext>`
4. add the sequence to your testing editorial project in `hiero` or `resolve`
5. Add the clip to fresh timeline and create publishable clip on it
6. publish it
7. check the published file by loading it …
=> Global: fixing in-place source publishing for editorial

openpype/settings/defaults/project_settings/blender.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_blender_publish.json
Added for Blender host : Validator **No colons In Name** in project settings schemas and defaults.
=> Blender: added project settings for validator no colons in name

openpype/pipeline/load/__init__.py
This fixes the issue mentioned [here](https://github.com/ynput/OpenPype/pull/4284#issuecomment-1403745577) that got introduced with that PR.
That PR has broken the Loader tool in Houdini:
```
File "<stdin>", line 5, in <module>
File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 419, in show_loader
"loader", parent, use_context=use_context
File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 394, in show_tool_by_name
cls.helper.show_tool_by_name(tool_name, parent, *args, **kwargs)
File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 345, in show_tool_by_name
self.show_loader(parent, *args, **kwargs)
File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 89, in show_loader
loader_tool = …
```
=> Houdini: Fix loader not working in Houdini

pyproject.toml, tools/fetch_thirdparty_libs.py
Since we are not able to provide OpenImageIO tools binaries for macos, we should remove the item from th `pyproject.toml`. This PR is taking care of it.
It is also changing the way `fetch_thirdparty_libs` script works in that it doesn't crash when lib cannot be processed, it only issue warning.
Resolves #3858
=> Remove OIIO build for macos

openpype/hosts/maya/plugins/publish/validate_plugin_path_attributes.py
PR #4271 has broken publishing in Maya.
See [my comment here](https://github.com/ynput/OpenPype/pull/4271/files#r1088472107)
This PR solves that issue.
1. Publish a workfile.
2. Should now work fine.
=> Maya: Fix validate plugin path attributes

openpype/hosts/houdini/api/plugin.py
This is cosmetics only - the previous code to me felt quite unreadable due to the lengthy strings being used.
Code should do roughly the same, but just be reformatted.
1. Houdini publisher should still work as expected.
=> Houdini: New publisher code tweak

openpype/hosts/houdini/api/pipeline.py
Using the new publisher UI would generate a visible 'null' locator at the origin. It's confusing to the user since it's supposed to be 'hidden'.
Before this PR the user would see a locator/null at the origin which was the 'hidden' `/obj/OpenPypeContext` node. This null would suddenly appear if the user would've ever opened the Publisher UI once.
After this PR it will not show:
Nice and tidy.
This does NOT change it for existing scenes that already had the OpenPypeContext generated with it visual. It'll only change it for new scenes where it's generated the first time.
1. Open Houdini
2. Use new publisher
=> Houdini: Do not visualize the hidden OpenPypeContext node

openpype/pipeline/colorspace.py, openpype/pipeline/publish/publish_plugins.py
Extract colorspace data is fixed
Plugin is not failing due missing config data. 
Order in `openpype\pipeline\publish\publish_plugins.py` had to be prioritised to first check supported file extension before a imageio settings should be equired. Also the host config settings are now optional since some older projects might have imageio group setting override with missing config and rules. 
1. open Maya and publish pointcache
2. all should be published without hiccups ;)
=> Global: extract colorspace is not failing

website/docs/module_kitsu.md
To keep memory of this discussion: https://discord.com/channels/517362899170230292/563751989075378201/1068112668491255818
=> Docs: Question about renaming in Kitsu

openpype/hosts/max/api/menu.py, openpype/hosts/max/api/pipeline.py, openpype/hosts/max/plugins/load/load_pointcache.py
This PR is adding update/switch ability to pointcache/alembic loader in 3dsmax and fixing wrong tool shown when clicking on "Manage" item on OpenPype menu, that is now correctly Scene Inventory (but was Subset Manager).
Alembic update has still one caveat - it doesn't cope with changed number of object inside alembic, since loading alembic in max involves creating all those objects as first class nodes. So it will keep the objects in scene, just update path to alembic file on them.
=> 3dsmax: enhance alembic loader update function

openpype/hosts/maya/plugins/publish/validate_attributes.py
Code was broken. So either plug-in was unused or it had gone unnoticed.
Looking at the commit history of the plug-in itself it seems this might have been broken somewhere between two to three years. I think it's broken since two years since [this commit](https://github.com/BigRoy/OpenPype/commit/4a300e0b087fb40e044a99f3a0d0d5c3835f0a19#diff-805f60be6c0433010b43f2495f96f7901397109d588b9b030dff36ccd24911aa).
Should this plug-in be removed completely?
@tokejepsen Is there still a use case where we should have this plug-in? (You created the original one)
1. Validate Attributes in maya, yay!
=> Maya: Fix Validate Attributes plugin

openpype/hosts/blender/plugins/publish/validate_camera_zero_keyframe.py, openpype/hosts/blender/plugins/publish/validate_mesh_has_uv.py, openpype/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py, openpype/hosts/blender/plugins/publish/validate_no_colons_in_name.py, openpype/hosts/blender/plugins/publish/validate_transform_zero.py, openpype/hosts/maya/plugins/publish/collect_maya_workspace.py, openpype/hosts/maya/plugins/publish/validate_color_sets.py, openpype/hosts/maya/plugins/publish/validate_mesh_arnold_attributes.py, openpype/hosts/maya/plugins/publish/validate_mesh_has_uv.py, openpype/hosts/maya/plugins/publish/validate_mesh_lamina_faces.py, openpype/hosts/maya/plugins/publish/validate_mesh_non_zero_edge.py, openpype/hosts/maya/plugins/publish/validate_mesh_normals_unlocked.py, openpype/hosts/maya/plugins/publish/validate_mesh_overlapping_uvs.py, openpype/hosts/maya/plugins/publish/validate_mesh_single_uv_set.py, openpype/hosts/maya/plugins/publish/validate_mesh_vertices_have_edges.py, openpype/hosts/maya/plugins/publish/validate_no_default_camera.py, openpype/hosts/maya/plugins/publish/validate_no_namespace.py, openpype/hosts/maya/plugins/publish/validate_no_null_transforms.py, openpype/hosts/maya/plugins/publish/validate_rig_joints_hidden.py, openpype/hosts/maya/plugins/publish/validate_scene_set_workspace.py, openpype/hosts/maya/plugins/publish/validate_shape_default_names.py, openpype/hosts/maya/plugins/publish/validate_transform_naming_suffix.py, openpype/hosts/maya/plugins/publish/validate_transform_zero.py, openpype/hosts/maya/plugins/publish/validate_unreal_mesh_triangulated.py
Once upon a time in a land far far away there lived a few plug-ins who felt like they didn't belong in generic boxes and felt they needed to be versioned well above others. They tried, but with no success.
Even though they now lived in a universe with elaborate `version` and `category` attributes embedded into their tiny little plug-in DNA this particular deviation has been greatly unused. There is nothing special about the version, nothing special about the category.
It does nothing.
Having these attributes on these plug-ins just meant other developers would join in thinking _"hell yeah baby!"_ producing their own special plug-in babies with `category` and `version` attributes of their own. Well, they were fooled.
Their time spent on adding these precious attributes meant more lines of …
=> Maya + Blender: Pyblish plugins removed unused `version` and `category` attributes

openpype/host/host.py, openpype/pipeline/__init__.py, openpype/pipeline/context_tools.py
Defined more functions to receive current context information and added the methods to host integration so host can affect the result.
This is one of steps to reduce usage of `legacy_io.Session`. This change define how to receive current context information -> call functions instead of accessing `legacy_io.Session` or `os.environ` directly. Plus, direct access on session or environments is unfortunatelly not enough for some DCCs where multiple workfiles can be opened at one time which can heavily affect the context but host integration sometimes can't affect that at all.
`HostBase` already had implemented `get_current_context`, that was enhanced by adding more specific methods `get_current_project_name`, `get_current_asset_name` and `get_current_task_name`. The same functions were added …
=> General: Functions for current context

openpype/pipeline/colorspace.py
Colorspace settings (imageio) are now optional
Settings might not be supported on some hosts and api was expecting it an all. 
API is now getting as fallback global imageio settings.
=> Global: colorspace host settings are now optional

openpype/hosts/maya/api/pipeline.py
Skip workfile lock check if current scene is 'Untitled'.
1. If Maya is opened in Untitled scene it should not crash on lock workfile check
=> Maya: Ignore workfile lock in Untitled scene

openpype/hosts/max/addon.py, openpype/hosts/max/startup/startup.py
This is fixing various issues that can occur on some of the 3dsmax versions.
On displays with +4K resolution UI was broken, some 3dsmax versions couldn't process `PYTHONPATH` correctly. This PR is forcing `sys.path` and disabling `QT_AUTO_SCREEN_SCALE_FACTOR`
1. 3dsmax with OpenPype should start as expected
2. No UI issues on high resolution displays
=> 3dsmax: startup fixes

openpype/host/host.py
Fix bug created in https://github.com/ynput/OpenPype/pull/4324 where for current task name is used `AVALON_ASSET` instead of `AVALON_TASK`.
Use `AVALON_TASK` instead of `AVALON_ASSET` in `get_current_task_name`.
=> General: Use right environment variable for current task name

openpype/modules/ftrack/ftrack_module.py, openpype/modules/ftrack/tray/login_dialog.py
Auto-fill of ftrack url don't break custom urls. Custom urls couldn't be used as `ftrackapp.com` is added if is not in the url.
The code was changed in a way that auto-fill is still supported but before `ftrackapp` is added it will try to use url as is. If the connection works as is it is used.
Can't test it as I wasn't able run ftrack server locally and couldn't run redirect proxy either.
1. Have ftrack server without `ftrackapp` in url
2. Set it in settings to be connected there
3. Run Tray and log in
4. Publish at least from one DCC
=> Ftrack: Don't force ftrackapp endpoint

openpype/hosts/maya/plugins/load/load_vrayproxy.py, openpype/hosts/maya/plugins/publish/validate_vray.py
Updating the Vray proxy would fail.
Also added validator to ensure vray plugin is enabled since publishing could go past validation without needing vray and fail at extraction.
1. Create Vray Proxy in Maya.
2. Publish.
3. Load into Maya.
4. Publish a new version and update.
=> Maya: V-Ray Proxy - Update to latest fails - OP-2008

openpype/hosts/houdini/api/shelves.py
Fix Houdini shelf tools.
Use `label` as mandatory key instead of `name`. Changed how shelves are created. If the script is empty it is gracefully skipping it instead of crashing.
1. Shelves creation should work
PR is replacement of stale PR https://github.com/ynput/OpenPype/pull/4062
=> Houdini: Houdini shelf tools fixes

openpype/modules/slack/manifest.yml
Added missed additional scopes for Slack bot
Must be added with Slack admin for a organization. Slack app must be restarted (but token stays the same).
Slack user notificaton was added here https://github.com/ynput/OpenPype/pull/4265
=> Slack: added missed scopes for Slack bot

openpype/modules/ftrack/ftrack_server/event_server_cli.py, openpype/modules/ftrack/tray/login_dialog.py
Use `is_alive` method instead of `isAlive` which is not compatible with Python 3.9.*.
1. Ftrack statuser on ftrack event server should work
=> Ftrack: Fix methods called on thread objects

openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/publish/collect_render.py, openpype/modules/deadline/plugins/publish/submit_maya_deadline.py, openpype/settings/defaults/project_settings/deadline.json, openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
DL by default has Strict error checking, but some errors are not fatal. 
This allows to set profile based on Task and Subset values to temporarily disable Strict Error Checks.
Subset and task names should support regular expressions. (not wildcard notation though).
1. Configure Settings in `project_settings/deadline/publish/MayaSubmitDeadline/strict_error_checking` - set to false
3. create new render instance, publish from Maya to DL, check `MayaBatch Settings` of job properties
=> Deadline: Allow disabling strict error check in Maya submissions

openpype/host/dirmap.py
Fixed issue in dirmap in Maya and Nuke
Loads of error were thrown in Nuke console about dictionary value.
`AttributeError: 'dict' object has no attribute 'lower'`
`remote_site_dir` started to return platform dict instead of str value
1. enable SiteSync on a project,
2. set local site to local, remote to Studio
3. start Nuke or Maya - observe console
=> SiteSync: fix dirmap

openpype/pipeline/load/plugins.py, openpype/pipeline/load/utils.py
This is "idea", how to give loaders more power to decide if can be shown in UI by adding `is_compatible` method on it.
Add `is_compatible` class method to loader plugin which by default does what `is_compatible` function did but loader can override the method and be more precise in the decision.
There are also SubsetLoaders which didn't use `is_compatible` at all but probably should have that option too. In future we could add objects that would represent items in loader menu so loader does not have to calculate that on it's own. That is missing few more things (like unique identifier of loader plugins, etc.) -> doable, but more complicated.
I didn't test it...
1. Loader plugins should be filtered as they were before in Loader and LibraryLoader
=> General: Loader plugin define its own compatibility

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py, openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.py
This works if DL Openpype plugin Installation Directories is set to level of app bundle (eg. '/Applications/OpenPype 3.15.0.app')
=> Fix: DL on MacOS

openpype/tools/attribute_defs/widgets.py, openpype/tools/utils/__init__.py, openpype/tools/utils/widgets.py
Scroll of mouse wheel should not affect number inputs unless thay are clicked in. Label widgets of attribute definitions also have tooltips.
1. Labels should have same tooltips as input fields
2. Make sure you have NumberDef in UI
3. Make sure the widget of NumberDef is not active (click elsewhere)
4. Scroll mouse over number input
5. Value should not change
6. Make the widget active (click in)
7. Scroll mouse over number input
8. Value should change
=> AttrDefs: Enhancements of AttrDefs widgets

openpype/pipeline/anatomy.py
Added attribute `project_code` to `Anatomy` object.
Anatomy already have access to almost all attributes from project anatomy except project code. This PR changing it. Technically `Anatomy` is everything what would be needed to get fill data of project.
```
{
"project": {
"name": anatomy.project_name,
"code": anatomy.project_code
}
}
```
Nothing has changed for user.
=> General: Add project code to anatomy

openpype/hosts/maya/plugins/publish/validate_ass_relative_paths.py
When validating/repairing we previously required users to open render settings to create the Arnold options. This is done through code now.
1. Launch Maya and setup lighting scene without opening render settings.
2. Publish.
=> Maya: Create Arnold options on repair.

openpype/hosts/harmony/plugins/publish/extract_render.py, openpype/lib/execute.py, openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py, openpype/scripts/otio_burnin.py
Ignore decode errors and replace invalid character (byte) with escaped byte character.
Calling of `run_subprocess` may cause crashes if output contains some unicode character which (for example Polish name of encoder handler).
Issue was discovered by a client so testing notes are related to the case.
2. Select family (e.g. Render)
3. Drop video from client to both (source and reveiw) input fields
4. Publish
5. Publishing should went smoothly without issues in ExtractReview plugin
=> General: Ignore decode error of stdout/stderr in run_subprocess

openpype/client/entity_links.py, openpype/plugins/load/add_site.py, openpype/plugins/load/remove_site.py, openpype/tools/loader/widgets.py
If adding site to representation presence of hero version is checked, if found hero version is marked to be donwloaded too.
Replacing https://github.com/ynput/OpenPype/pull/4191
1. locate subset which has some hero version in Loader
2.use latest version of said subset and `Download` representation (in right bottom)
3. check that both latest and hero version representation were downloaded
=> Fix - addSite loader handles hero version

openpype/plugins/publish/integrate.py
Treat `{originalBasename}` in different way then standard files processing. In case template should use `{originalBasename}` the transfers will use them as they are without any changes or handling of frames.
Frames handling is problematic with original basename because their padding can't be defined to match padding in source filenames. Also it limits the usage of functionality to "must have frame at end of fiename". This is proposal how that could be solved by simply ignoring frame handling and using filenames as are on representation. First frame is still stored to representation context but is not used in formatting part. This way we don't have to care about padding of frames at all.
This is a proposal, I could miss some other issues related to the feature.
1. Add templates to use …
=> General: Fix original basename frame issues

openpype/hosts/blender/plugins/load/import_workfile.py
Having this feature related to workfile available for any family is absurd.
=> Blender: fix import workfile all families

openpype/plugins/publish/integrate_hero_version.py
Keep previously synchronized sites up-to-date by comparing old and new sites and adding old sites if missing in new ones.
Fix #4331
1. Publish a version from a site A
2. Using the loader, download the hero version
3. Publish the same subset from site B
4. It's being synchronized in site A
=> Feature: Keep synced hero representations up-to-date.

openpype/hosts/maya/plugins/publish/collect_render.py
Provide default of strict error checking for instances created prior to PR.
1. Create a render instance.
2. Delete the strict error checking attribute to simulate having an instance from before the PR was made.
3. Publish.
=> Strict Error Checking Default

openpype/pipeline/load/utils.py
Replaced forgotten usage of `dbcon.parenthood` with function `get_representation_parents`.
Don't know if there is a way how to test this change. Technically it should never get to that point if the files from representation are available on the machine.
=> General: Don't use mongo call in load utils

openpype/tools/publisher/window.py
A little bit less confusing automated tab changes in Publisher tool.
First reset of publisher won't trigger change of tab to anything else than 'Create' tab. Reset of publisher will change tab only if user is on Report tab -> Won't change tab if is on 'Details' tab.
Stay at `Create` tab on open
1. Open publisher in scene where is something already created
2. Publisher should stay at `Create` tab
Don't change tab on reset
1. Run publishing
2. When stopped hit reset
3. Only if you're on `Report` tab it should change tab to `Publish` but not in any other case
=> Publisher: Less confusing tab changes

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/hosts/aftereffects/plugins/create/workfile_creator.py, openpype/hosts/photoshop/plugins/create/create_image.py, openpype/hosts/photoshop/plugins/create/workfile_creator.py
`legacy_io` import was removed, but usage stayed. 
Usage of `legacy_io` should be eradicated, in creators it should be replaced by `self.create_context.get_current_project_name/asset_name/task_name`.
Source issue for this was found in automatic tests, it might be complicated to replicate it as it occurs in legacy instances without proper task.
It should be enough to try publishing to make sure it doesn't break regular process. (Automatic test will be fixed by this PR.)
1. Try to publish workflow - create new instance, publish in PS
1. Try to publish workflow - create new instance, publish in AE
=> Photoshop: fix missing legacy io for legacy instances

openpype/tools/publisher/widgets/widgets.py
Fix `QAction` for older version of Qt bindings where QAction requires a parent on initialization.
This bug was discovered in Nuke 11. Fixed by creating QAction when QMenu is already available and can be used as parent.
1. Open Publisher in Nuke 11
2. Should not crash
=> Publisher: Fix compatibility of QAction in Publisher

openpype/pipeline/tempdir.py
Fixing python2 incompatibility
Python 3 only compatible code had slipped into codebase.
Resolves https://github.com/ynput/OpenPype/issues/4475
=> Global: fixing python2 incompatibility 

openpype/tools/publisher/window.py
Use right name of constant 'ActiveWindow' -> 'WindowActive'.
1. Start a host with Publisher
2. Open Publisher
3. Keep it opened and try open it again
4. Nothing should crash
Crash is described in https://github.com/ynput/OpenPype/issues/4462
Resolves https://github.com/ynput/OpenPype/issues/4462
=> Publisher: Fix reopen bug

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py, openpype/modules/shotgrid/plugins/publish/integrate_shotgrid_publish.py, openpype/modules/shotgrid/plugins/publish/integrate_shotgrid_version.py, openpype/modules/slack/plugins/publish/integrate_slack_api.py, openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py, openpype/plugins/publish/integrate.py
Representation instances don't have a "published_path" attribute when submitting remotely so the Shotgrid integrator plugins were failing expecting it. This PR abstracts the function that the ftrack integrator plugins used into a common module and uses it on the Shotgrid plugins to fix the bug.
Rendering remotely in the farm we were hitting this bug where "published_data" attribute didn't exist on the representation instances:
```
INFO: Create Shotgrid version: {'id': 290916, 'project': {'id': 2917, 'name': 'zzz', 'type': 'Project'}, 'sg_task': None, 'entity': {'id': 53397, 'name': 'cloud1_10_10', 'type': 'Shot'}, 'code': 'zzz_Shots_cloud1_10_10_DummyTask_v045', 'type': 'Version'}
File "/usr/openpype/exe.linux-x86_64-3.9/dependencies/pyblish/plugin.py", …
```
=> Shotgrid: Fix how representation paths are received during publishing

openpype/pipeline/create/context.py, openpype/pipeline/create/creator_plugins.py, openpype/pipeline/plugin_discover.py, openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py, openpype/tools/publisher/control.py, openpype/tools/publisher/widgets/create_widget.py
Added crashes of creators and convertos discovery (lazy solution).
Report in Publisher also contains information about crashed files caused during creator plugin discovery and convertor plugin discovery. They're not separated into categroies and there is no other information in the report about them, but this helps a lot during development. This change does not need to change format/schema of the report nor UI logic.
1. Cause a crash in Creator plugin on import (e.g. add `import foobar` to file)
2. Open Publisher
3. Go to 'Report' tab
4. Go to crashed plugins information
5. The crashed file with creator should be there
=> Publisher: Report also crashed creators and convertors

openpype/hosts/maya/api/workfile_template_builder.py
When we build a template with Maya Template Builder, it will update the asset field of the sets (creator instances) that are imported from the template. 
When building a template, we also want to define the publishable content in advance: create an instance of a model, or look, etc., to speed up the workflow and reduce the number of questions we are asked. After building a work file from a saved template that contains pre-created instances, the template builder should update the asset field to the current asset.
As an aside, for some instances that contain CbId, I didn't know if we should update the ID or not. 
1. Create a template base on the documentation.
2. Make sure that your template contains a creator instance. 
3. In a new asset, build workfile from template.
4. You should see …
=> Update Asset field of creator Instances in Maya Template Builder

start.py
Drive paths for windows are fixing possibly missing slash at the end of destination path.
Windows `subst` command require to have destination path with slash if it's a drive (it should be `G:\` not `G:`).
1. Set mapping e.g. `C:/` -> `D:/` in general settings for windows
2. Run tray
3. The mapping should happen
=> Start script: Fix possible issues with destination drive path

openpype/tools/workfiles/files_widget.py
Browse button works with PySide 6 binding too.
Added one more option to choose which kwargs is filled for QFileDialog.
1. Build OpenPype with PySide6
2. Launch a host DCC which is using OpenPype process for UIs (AE, Photoshop, Harmony, TVPaint,...)
3. Open workfiles tool
4. Click on `Browse`
5. A dilog should pop up
=> Workfiles tool: Add PySide 6 support

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Ftrack can integrate reviewables with original filenames.
As ftrack have restrictions about names of components the only way how to achieve the result was to upload the same file twice, one with required name and one with origin name.
~~We could try "reuse" the same container id from the required file so the file does not have to uploaded twice.~~ I couldn't figura out how it could be possible.
Make sure you have enabled ftrack
1. Go to `project_settings/ftrack/publish/IntegrateFtrackInstance/upload_reviewable_with_origin_name` and enable it
2. Publish something with reviewable (e.g. trough tray publisher)
3. Check ftrack where should be on version `ftrackreview-mp4` component and component with original filename prepared to be downloaded
=> Ftrack: Upload reviewables with original name

openpype/hosts/maya/plugins/publish/extract_playblast.py, openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Error when extracting playblast with no model panel.
If `project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options` were off and publishing without showing any model panel, the extraction would fail.
1. Turn off `project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options`
2. Launch Maya and setup a review.
3. Dont show any model panels by choosing Outliner or similar.
4. Publish review.
Resolves #3754
Resolves #4104
=> Maya: extract Thumbnail "No active model panel found" - OP-3849

openpype/settings/defaults/project_settings/ftrack.json
With default settings, renderlayers in Maya were not being tagged with the Ftrack family leading to confusion when doing reviews.
1. Start a new pipeline/project with default settings.
2. Create render in Maya and Publish.
=> Default Ftrack Family on RenderLayer

openpype/hosts/maya/api/commands.py, openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/lib_rendersettings.py, openpype/hosts/maya/api/menu.py
Location in commands caused cyclic import
Failure occurred in automatic testing in Maya 2020.
1.open Maya (2020)
=> Maya: Fix changed location of reset_frame_range

openpype/hosts/harmony/api/pipeline.py
Frame range gets set from DB everytime scene is opened.
Added also check for not up-to-date loaded containers.
1. open scene in Harmony and check if frame duration matches to DB (Harmony starts from 1, so only duration is set
2. load older version of published asset
=> Harmony: missing set of frame range when opening scene

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/plugins/publish/validate_maya_units.py
Returned value of float fps on integer values would return float.
This PR fixes the case when switching between integer fps values for example 24 > 25. Issue was when setting the scene fps, the original float value was used which makes it unpredictable whether the value is float or integer when mapping the fps values.
1. Set `project_anatomy/attributes/fps` to 24.
2. Launch Maya and save the workfile as 24 fps.
3. Set `project_anatomy/attributes/fps` to 25.
4. Publish or relaunch the workfile, and fix the fps validation.
=> Maya: Fix setting scene fps with float input

openpype/hosts/fusion/api/lib.py, openpype/hosts/fusion/hooks/pre_fusion_setup.py, openpype/hosts/fusion/plugins/publish/collect_instances.py, openpype/hosts/fusion/plugins/publish/render_local.py
Fixed Fusion review-representation and small bug-fixes
This fixes the problem with review-file generation that stopped the publishing on second publish before the fix.
The problem was that Fusion simply looked at all the files in the render-folder instead of only gathering the needed frames for the review.
Also includes a fix to get the handle start/end that before throw an error if the data didn't exist (like from a kitsu sync).
=> Fusion: Fix files collection and small bug-fixes

openpype/hosts/nuke/plugins/load/load_clip.py, openpype/plugins/publish/collect_otio_subset_resources.py
Publishing and loading `originalBasename` is working as expected
Frame-ranges on version document is now correctly defined to fit original media frame range which is published. It means loading is now correctly identifying frame start and end on clip loader in Nuke.  
Loading is only fixed for Nuke but other DCC's should also be treated. Perhaps some abstracted implementation in wider scale should be done.
1. Set to use the template for your use case. `plate` family with `source` template.
2. Open Hiero and add a clip, create to publishable and publish 
3. Open Nuke Load published clip and all should play as it suppose to
=> Hiero/Nuke: originalBasename editorial publishing and loading

openpype/pipeline/create/context.py
Disabled creators are ignored in CreateContext.
All creator plugins that have set `enabled` attribute to `False` on initialization are not added to creator attributes but to `disabled_creators` so they're not available on collect/create and not shown in UI.
1. Disable a creator plugin
2. Open UI and check if is visible there
=> General: Ignore disabled creators in create context

openpype/hosts/max/plugins/load/load_camera_fbx.py, openpype/hosts/max/plugins/load/load_max_scene.py, openpype/hosts/max/plugins/load/load_pointcache.py
Fix the bug of being unable to delete loaded asset in the Scene Inventory
Fix the bug of being unable to delete loaded asset in the Scene Inventory
1. launch 3dsmax through Openpype
2. go to Openpype -> load
3. load the assets from any families
4. go to Openpype -> Manage
5.  RMB -> Removeitems
=> 3dsmax unable to delete loaded asset in the scene inventory

openpype/hosts/tvpaint/plugins/create/create_render.py, openpype/hosts/tvpaint/plugins/publish/collect_render_instances.py, openpype/hosts/tvpaint/plugins/publish/extract_sequence.py, openpype/settings/defaults/project_settings/tvpaint.json, openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
It is possible to ignore layers transparency during Render Pass extraction.
Render pass extraction does not respect opacity of TVPaint layers set in scene during extraction. It can be enabled/disabled in settings.
I found out that `opacity` received using `tv_layerinfo` is always `0` which caused a troubles but `tv_layerdensity` does return previous value on change so I've used that option to change it to `100` and then back to previous value.
1. Enable `project_settings/tvpaint/publish/CollectRenderInstances/ignore_render_pass_transparency`
2. Open TVPaint scene
3. Create Render Layer
4. Create Render Pass on TVPaint layer
5. Change opacity of the layer (e.g. to 50%)
6. Publish
7. Output of Render Pass should have 100%
=> TVPaint: Ignore transparency in Render Pass

openpype/hosts/nuke/api/__init__.py, openpype/hosts/nuke/api/pipeline.py
Template placeholder creation was erroring out in Nuke due to the Workfile template builder not being able to find any of the plugins for the Nuke host.
Move `get_workfile_build_placeholder_plugins` function to NukeHost class as workfile template builder expects.
1. Start Nuke
2. Create a Placeholder from the template builder
=> Nuke: Fix workfile template placeholder creation

start.py
Change exit code from `1` to `0` when versions  are printed or when version is validated.
Return code `1` is indicating error but there didn't happen any error.
1. Run and check return code when you run `openpype_console --list-versions`
=> Start script: Change returncode on validate or list versions

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/plugin.py, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Added support for multiple reformat nodes in baking profiles.
Old settings for single reformat node is supported and prioritised just in case studios are using it and backward compatibility is needed. Warnings in Nuke terminal are notifying users to switch settings to new workflow. Settings are also explaining the migration way. 
1. Go to settings at your testing project
2. Go to settings `project_settings/nuke/publish/ExtractReviewDataMov/outputs/baking/reformat_node_add` and disable
3. Go to settings `project_settings/nuke/publish/ExtractReviewDataMov/outputs/baking/reformat_nodes_config/enabled` and disable
4. Go to `project_settings/nuke/publish/ExtractReviewDataMov/outputs/baking/reformat_nodes_config/reposition_nodes` copy contenst of .zip file and paste it to `reposition_nodes` …
=> Nuke: multiple reformat in baking review profiles

openpype/hosts/nuke/addon.py, openpype/hosts/nuke/api/__init__.py, openpype/hosts/nuke/api/constants.py, openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/pipeline.py, openpype/hosts/nuke/api/utils.py, openpype/hosts/nuke/hooks/pre_nukeassist_setup.py, openpype/settings/defaults/system_settings/applications.json, openpype/settings/entities/schemas/system_schema/schema_applications.json
Adding support for NukeAssist
For support of NukeAssist we had to limit some Nuke features since NukeAssist itself Nuke with limitations. We do not support Creator and Publisher. User can only Load versions with version control. User can also set Framerange and Colorspace.
1. Set NukeAssist to your project
2. Open NukeAssist on task and see the OpenPype menu items have are redefined.
=> Nuke: adding nukeassist 

openpype/settings/handlers.py, openpype/settings/lib.py
This logs all changes in Settings to separate collection ('setting_log') to help debug/trace changes. This functionality is pretty basic as it will be replaced by Ayon implementation in the future.
It saves only 'changes' (like diffs) not old values as resolution of that could get tricky (in complex dictionaries). 
No UI implemented, accessible only through Compass or other IDE.
It produces documents like this:
Changes to system/anatomy/project settings could be filtered by value in `settings_type`.
It would be theoretically possible to apply list of these changes on barebone Settings to create state at specific point in time. Not sure if we want to investigate this for v3 though.
1. Try to change something in settings, save, check `settings_log`
=> Settings - first implementation of saving settings changes to DB

openpype/tools/publisher/control.py, openpype/tools/publisher/widgets/widgets.py
UI attribute definitions are working for publish plugins in Publisher tool.
UI attributes were treated as value holding attributes which caused crashes on load and none attributes were visible in UI nor were stored values on instance.
1. Add `UILabelDef` or `UISeparatorDef` to attribute definitions of publish plugin
2. Open Publisher tool where the plugin will be shown
3. The attributes should be there
=> Publisher: Fix Attr UI definitions for publish plugins

openpype/tools/publisher/widgets/overview_widget.py, openpype/tools/publisher/window.py
Prevent access to create tab after publish start.
Disable create button in instance view on publish start and enable it again on reset. Even with that make sure that it is not possible to go to create tab if the tab is disabled.
1. Open Publisher tool
2. Hit validate (you must have at least 1 created instance to be able do that)
3. Go to Publish tab
4. Minimize bottom overlay
5. `+` button in instance view should be disabled
Resolves https://github.com/ynput/OpenPype/issues/4316
=> Publisher: Prevent access to create tab after publish start

openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Private/AssetContainer.cpp, openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Private/AssetContainerFactory.cpp, openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Public/AssetContainer.h, openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Public/AssetContainerFactory.h
Fixing Unreal loaders, where changes in OpenPype Unreal integration plugin deleted AssetContainer.
`AssetContainer` and `AssetContainerFactory` are still used to mark loaded instances. Because of optimizations in Integration plugin we've accidentally removed them but that broke loader.
1. Start Unreal with OP
2. try to load something
> **Note**
> you need to force engine to rebuild the plugin - delete `C:\Program Files\Epic Games\UE_5.1\Engine\Plugins\Marketplace\OpenPype` (or analogous)
=> Unreal: fix loaders because of missing AssetContainer

tools/create_env.ps1, tools/create_env.sh
New 1.4.0 breaks `sphinxcontrib-applehelp`. Change in `poetry.lock` would need new minor version.
`poetry.lock` will be redone for next release, so that should fix it for newer version of Poetry
This will help new users to build OP, I encountered issue with failures of `atomicwrites`.
The solution was to purge poetry pypi cache. I used in OP root:
```
poetry cache clear pypi --all
``` 
Or you could manually delete `c:\Users\YOUR_USER\AppData\Local\pypoetry\`
=> General: hardcode Poetry to 1.3.2 temporarily

openpype/plugins/publish/extract_color_transcode.py
When transcoding into new colorspace, representation must carry this information instead original color space.
1. publish workfile where color transcoding should happen
2. check final transcoded representation in DB if it contains colorspace which should be transcoded into
=> Color Transcoding: store target_colorspace as new colorspace

openpype/hosts/maya/plugins/create/create_vrayproxy.py, openpype/hosts/maya/plugins/publish/collect_vrayproxy.py, openpype/hosts/maya/plugins/publish/extract_pointcache.py, openpype/hosts/maya/plugins/publish/extract_vrayproxy.py, openpype/hosts/maya/plugins/publish/validate_vrayproxy.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
Options for output of VrayProxy.
Client requested more granular control of output from VrayProxy instance. Exposed options on the instance and settings for vrmesh and alembic.
1. Create VrayProxy in Maya.
2. Enable/Disable attributes `vrmesh` and `alembic`, on the instance.
3. Enable/Disable `project_settings/maya/create/CreateVrayProxy/vrmesh` and/or `project_settings/maya/create/CreateVrayProxy/alembic` and create VrayProxy instance to validate settings are propagated to instance.
=> Maya: Options for VrayProxy output - OP-2010

openpype/hosts/maya/plugins/publish/collect_instances.py, openpype/hosts/maya/plugins/publish/validate_instance_attributes.py
Validate missing instance attributes.
New attributes can be introduced as new features come in. Old instances will need to be updated with these attributes for the documentation to make sense, and users do not have to recreate the instances.
1. Make an instance in Maya.
2. Delete an attribute from the instance's objectset.
3. Publish.
=> Maya: Validate missing instance attributes

openpype/hosts/hiero/plugins/publish/collect_clip_effects.py
Collected effect name after renaming is saving correct class name.
1. Go to a Hiero timeline.
2. Drag in a clip and create soft effects. Tested with `OCIOCDLTransform`.
3. Rename soft effects with something other than default node name.
4. Publsih clip with its effects.
5. Check published effects json, it will have wrong class name.
Resolves https://github.com/ynput/OpenPype/issues/4326
=> hiero: fix effect item node class

openpype/hosts/maya/plugins/publish/validate_model_name.py
Validate model name issues.
Couple of issues with validate model name;
- missing platform extraction from settings
- map function should be list comprehension
- code cosmetics
1. Setup `simple_shader_list.txt` with:
```
fabricCotton
fabricCorduroy
fabricGeneric
rubberGeneric
IDorganicSkin
```
2. Setup settings:
- enable `project_settings/maya/publish/ValidateModelName`.
- disable `project_settings/maya/publish/ValidateModelName/database`
- `project_settings/maya/publish/ValidateModelName/regex` > `(.*)_ID(?P<shader>.*)_(GEO)`
- `project_settings/maya/publish/ValidateModelName/material_file/windows` > point to created `simple_shader_list.txt`.
3. Setup Maya scene with two meshes named `balloon_IDrubberGeneric_GEO` and `string_IDfabricGeneric_GEO`.
4. Publish.
=> Maya: Validate model name - OP-4983

openpype/plugins/publish/extract_hierarchy_avalon.py
Tasks won't disappear on editorial publish.
Editorial publishing which create tasks was always removing all other tasks if the asset already had some. With this PR, the other tasks kept.
1. Publish some editorial which creates assets and some tasks
2. Add any other task to a asset which was created using the publishing
3. Run the same editorial publishing again
4. The task from 2. should stay untouched
=> Editorial: Fix tasks removal

openpype/hosts/nuke/plugins/publish/collect_writes.py, openpype/hosts/nuke/plugins/publish/extract_render_local.py, openpype/pipeline/colorspace.py, openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/publish_plugins.py, openpype/plugins/publish/extract_colorspace_data.py
Colormanaged extractor had changed to Mixin class so it can be added to any stage of publishing rather then just to Exctracting. 
Nuke is no collecting colorspaceData to representation collected on already rendered images.
Mixin class can no be used as secondary  parent in publishing plugins.
1. open Nuke testing workfile
2. publish aready rendered images
3. all should be publish as usuall -additionally colorspaceData are added to representation db doc into data
=> Nuke | Global: colormanaged plugin in collection

openpype/hosts/maya/api/workfile_template_builder.py, openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/create/create_write_image.py, openpype/hosts/nuke/plugins/create/create_write_prerender.py, openpype/hosts/nuke/plugins/create/create_write_render.py, openpype/pipeline/workfile/workfile_template_builder.py
Nuke workfile template builder can use new creators instead of legacy creators.
Modified workfile template builder to have option to say if legacy creators should be used or new creators. Legacy creators are disabled by default, so Maya has changed the value.
=> Nuke: Add option to use new creating system in workfile template builder

openpype/hosts/fusion/plugins/load/load_sequence.py
[Resolves issue mentioned on discord](https://discord.com/channels/517362899170230292/563751989075378201/1082272423212224593) by @movalex:
> I launch openpype menu, choose Load - plateMain - right click - load sequence (mov) and instead of the plate the thumbnail file appears in the created loader. 
> there's two files in the publish folder.
> One is the plate, second is the thumbnail.
The loader was incorrectly trying to find the file in the publish folder which resulted in just picking 'any first file'.
This gets the filepath from representation instead of taking the first file from listing files from publish folder.
1. Load an image sequence (or video file)
2. Make sure to test a case where the publish folder also contains other files than the image sequence (or video file), like e.g. …
=> Fusion: Load sequence fix filepath resolving from representation

openpype/hosts/fusion/plugins/publish/collect_inputs.py, openpype/hosts/houdini/plugins/publish/collect_inputs.py, openpype/hosts/maya/plugins/publish/collect_inputs.py, openpype/plugins/publish/collect_input_representations_to_versions.py
Don't use `ObjectId` as representation ids during publishing.
Representation ids are kept as strings during publishing instead of converting them to `ObjectId`. This change is pre-requirement for AYON connection.
Inputs are used for integration of links and for farm publishing (or at least it looks like).
1. Load (Reference) something into scene (fusion, houdini, maya)
2. Publish the scene
3. There should be integrated links in workfile version
1. Load (Reference) something into scene (fusion, houdini, maya)
2. Create a farm job
3. Input versions should be filled as expected
=> General: Input representation ids are not ObjectIds

openpype/tools/attribute_defs/widgets.py
Use right type in signal emit for value change of attribute definitions.
Changed `UUID` type to `str`. This is not an issue with PySide2 but it is with PySide6.
1. Run some UI using AttrDefs (e.g. Publisher) in process using PySide6
2. Change value of the attribute
3. The change should not cause crash
=> AttrDefs: Fix type for PySide6

openpype/modules/kitsu/utils/update_op_with_zou.py
From the last PR (https://github.com/ynput/OpenPype/pull/4425) a comment-commit last second messed up the code and resulted in two lines being the same, crashing the script. This PR fixes that.
=> Kitsu: Fix task itteration in update-op-with-zou

openpype/widgets/popup.py
This fixes an error for applications showing the "Scene has outdated content" pop-ups which use PySide6+ 
This is currently noticable only in Fusion as far as I know since it's the only application using the pop-up widget which allows a custom Python version with a PySide version of your choice.
Note that the pop-up widget is used in Houdini, Maya and Fusion so it's likely good to test across the different applications to ensure it still works as expected.
This is the reported error:
> [after clicking _Repair_ I've got an AttributeError (reported by @movalex on Discord)](https://discord.com/channels/517362899170230292/517382145552154634/1081869316074516560):
1. [x] Test pop-up in Fusion (tested in Fusion 18, Py3.7, PySide6
1. [x] Test pop-up in Maya (tested in Maya 2022.1, Py3.7.7, …
=> Fusion: Avoid error in "Scene has outdated content" pop-up in PySide6+

openpype/hosts/maya/plugins/load/load_reference.py
In Maya, fix the SkeletalMesh family not loadable as reference.
1. Have a rig published as SkeletalMesh.
2. Load that rig in the scene as reference.
=> Maya: SkeletalMesh family loadable as reference

openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json, openpype/tools/project_manager/project_manager/delegates.py, openpype/tools/project_manager/project_manager/view.py
Allows input 23.976 to the FPS settings both in Project Manager and the Project Anatomy.
Adds `setSingleStep` to the DoubleSpinBox editor with decimals.
Makes the FPS column in the Project Manager adjustable.
Based on this issue: https://github.com/ynput/OpenPype/issues/4479
* Go to Project Manager
* Click on asset
* Try to set fps to 23,976 with `,` as decimals separator.
* Select FPS cell and scroll the mouse, the value will be adjusted with 1 frame precision.
* Select Pixel Aspect cell and scroll the mouse, the value will be adjusted with 0.01 precision.
* Open Studio settings and check Project -> Anatomy -> Attributes. The Frame Rate field now have three decimals precision.
=> add up to 3 decimals precision to the frame rate settings

openpype/hosts/nuke/plugins/load/load_clip.py
Nuke is loading correctly clip  from image sequence created without "{originalBasename}" token in anatomy template.
1. Open any testing workfile in Nuke
2. load any image sequence subset 
3. It should load without hiccups
resolves https://github.com/ynput/OpenPype/issues/4553
=> Nuke: fix clip sequence loading

openpype/hosts/unreal/plugins/load/load_layout.py
Use 'get_representations' instead of 'legacy_io' query in layout loader.
This is removing usage of `find_one` called on `legacy_io` and use rather client functions as preparation for AYON connection. Also all representations are queried at once instead of one by one.
1. Open Unreal
2. Load a layout
3. Nothing should crash and layout should be loaded
=> Unreal: Use client functions in Layout loader 

openpype/hosts/fusion/plugins/publish/collect_comp_frame_range.py, openpype/hosts/fusion/plugins/publish/collect_instances.py
Fix the burnin start and end frame for reviews. Without this the asset document's start and end handle would've been added to the _burnin_ frame range even though that would've been incorrect since the handles are based on the comp saver's render range instead.
[Mentioned on discord](https://discord.com/channels/517362899170230292/517382145552154634/1082747784492494958)
It does feel a bit odd that I'm required to ALSO set this explicitly like this because otherwise global plug-ins start messing with the data. There seems to be something fishy in logic elsewhere:
1. Create an asset with start + end handles of say 10
2. Create a comp with in/out points on 1001-1010. (including its global in/global out, so no handles)
3. Render with review burnin
Without this PR the burnin would say …
=> Fusion: Fix review burnin start and end frame

openpype/hosts/unreal/hooks/pre_workfile_preparation.py, openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Private/AssetContainer.cpp, openpype/hosts/unreal/lib.py, openpype/hosts/unreal/ue_workers.py, openpype/widgets/README.md, openpype/widgets/splash_screen.py
Implemented a new splash screen widget to reflect a process running in the background. This widget can be used for other tasks than UE. **Also fixed the compilation error of the AssetContainer.cpp when trying to build the plugin in UE 5.0**
The proper usage of the splash screen is documented in the `openpype/widgets/README.md` file
1. Create a new project in OpenPype.
2. Launch the newly created project through the Launcher
3. The splash screen should appear
The splash screen should start a newly created thread and execute its code.
If no plugin is installed (You can do it just by deleting the OpenPype dir in `UE_X.X/Engine/Plugins/Marketplace` path), it should be building the plugin, logging and updating its progress.
After that if there is no project created, it should move to …
=> Implementation of a new splash screen

openpype/hosts/maya/api/lib_rendersettings.py
Resolves #4565
Set V-Ray Image Format using settings.
1. apply different image format in settings
2. apply render settings for v-ray in maya
=> Maya: V-Ray Set Image Format from settings

openpype/host/dirmap.py, openpype/hosts/nuke/api/lib.py, openpype/modules/sync_server/sync_server_module.py, openpype/tools/settings/local_settings/projects_widget.py
If artists uses SiteSync with real remote (gdrive, dropbox, sftp) drive, Local Settings were throwing error `string indices must be integers`.
Logic was reworked to provide only `local_drive` values to be overrriden by Local Settings. If remote site is `gdrive` etc. mapping to `studio` is provided as it is expected that workfiles will have imported from `studio` location and not from `gdrive` folder.
Also Nuke dirmap was reworked to be less verbose and much faster.
This should be gone from Nuke logs:
1. Set SiteSync to be enabled on project
2. Set gdrive/dropbox/sftp remote site in Local Settings (might not be actually working)
3. Check in LS that no error is throwns
4. Download some Maya or Nuke workile from remote site, open it and check if dirmap doesn't fail.
=> SiteSync: host dirmap is not working properly

openpype/tools/loader/widgets.py, openpype/tools/sceneinventory/model.py, openpype/tools/sceneinventory/window.py, openpype/tools/settings/settings/search_dialog.py, openpype/tools/standalonepublish/widgets/model_filter_proxy_recursive_sort.py, openpype/tools/utils/models.py
Fix recursive filtering which is broken since PySide6 support was added.
Change order of available methods to check for legacy ones first to fix PySide2 support. Assets filtering if using Qt recursive filtering if is available.
The most changes can be visible in Loader, Scene Inventory and Settings tool.
1. Open Loader
2. Try filter assets by nested asset name
3. The parents should stay visible
4. The same for Subsets
1. Open settings
2. Press CTRL+F (or find shortcut of your OS)
3. Type some settings key nested in the search dialog
4. The filtering should not hide parents if they don't match the name but their children does
Enhanced [PR](https://github.com/ynput/OpenPype/pull/4595) which solved only one issue.
=> Tools: Fix recursive filtering

openpype/hosts/houdini/startup/MainMenuCommon.xml
During a talk with @maxpareschi he mentioned that the new publisher in Houdini felt super confusing due to "Create" going to the older creator but now being completely empty and the publish button directly went to the publish tab.
This resolves that by fixing the Create button to now open the new publisher but on the Create tab.
Also made publish button enforce going to the "publish" tab for consistency in usage.
@antirotor I think [changing the Create button's callback was just missed in this commit](https://github.com/BigRoy/OpenPype/commit/f2a1a11bec47855f1409b6620c618fa3bd89c550) or was there a specific reason to not change that around yet?
1. Start Houdini
2. Create should go to new publisher Create tab.
3. Publish should go to new publisher Publish tab.
=> Houdini: Create button open new publisher's "create" tab

openpype/client/server/conversion_utils.py, openpype/client/server/operations.py, openpype/plugins/publish/integrate_hero_version.py
Hero versions integration is more specific about data integrated to ayon. The change was added to reduce time spent in requerying already known data. In AYON is hero version fully usable version without reference to source version entity (other than negative value of version).
During this process were discovered few bugs on server and python api. Some of bugfixes are in progress to be merged and released so it is possible that this PR won't work because of outdated versions (make sure you have run 'create_env' script).
1. Enabled Integrate Hero version on ayon server
2. Publish something (family must be in enabled families in settings)
3. Integration of hero version should be successful
=> AYON: Integrate Hero version is more specific about data

openpype/hosts/maya/plugins/load/load_arnold_standin.py
Fix an error on right clicking in the Loader when `mtoa` is not a loaded plug-in.
Additionally if `mtoa` isn't loaded the loader will now load the plug-in before trying to create the arnold standin.
The error:
```python
// Warning: openpype.lib.python_module_tools : Failed to load path: "S:\openpype\OpenPype\openpype\hosts\maya\plugins\load\load_arnold_standin.py"
File "S:\openpype\OpenPype\openpype\lib\python_module_tools.py", line 92, in modules_from_path
module = import_filepath(full_path, mod_name)
File "S:\openpype\OpenPype\openpype\lib\python_module_tools.py", line 38, in import_filepath
module_loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in …
```
=> Maya: Avoid error on right click in Loader if `mtoa` is not loaded

openpype/hosts/maya/plugins/inventory/connect_geometry.py, openpype/hosts/maya/plugins/inventory/connect_xgen.py, openpype/hosts/maya/plugins/load/load_xgen.py
Replace last usage of `Qt` module with `qtpy`. This change is needed for `PySide6` support. All changes happened in Maya loader plugins.
1. Open Maya
2. Open Loader
3. Use `Load XGen`
4. Open Scene Inventory
5. Use `Connect Geometry` action
6. Use `Connect XGen` action
Resolves https://github.com/ynput/OpenPype/issues/3987
=> Maya: Replace last usages of Qt module

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
In the GlobalJobPreLoad plugin, we propose to replace the SpawnProcess by a sub-process and to pass the environment variables in the parameters, since the SpawnProcess under Centos Linux does not pass the environment variables.
In the GlobalJobPreLoad plugin, the Deadline SpawnProcess is used to start the OpenPype process. The problem is that the SpawnProcess does not pass environment variables, including OPENPYPE_MONGO, to the process when it is under Centos7 linux, and the process gets stuck. We propose to replace it by a subprocess and to pass the variable in the parameters.
Please note that I have not tested it on Windows. 
1. Run a deadline Job, under Linux, Centos 7, Deadline 10.1
2. Check if OPENPYPE_MONGO is in the os environment. 
3. Check if the spawned process can see the …
=> Resolve missing OPENPYPE_MONGO in deadline global job preload 

openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
Ftrack family collector makes sure the subset family is also in instance families for additional families filtering.
When additional filtering would look for combination of `"render"` and `"review"` families on instance it would not work when the `"render"` would be subset family.
1. Define additional filtering of families with `"plate"` and `"review"` for Collect Ftrack Familiy in `traypublisher` (in a way that you can validate it works)
2. Open Tray Publisher
3. Create Plate with review representation
4. Hit validate (you don't need to publish to validate the collector works)
5. The instance should have/not have `"ftrack"` family based on your settings
=> Ftrack: Ftrack additional families filtering

openpype/hooks/pre_add_last_workfile_arg.py
Supports opening last saved workfile in 3dsmax host.
1. Launch 3dsMax via Openpype
2. If you saved workfile in 3dsmax before, it automatically opens the last saved workfile after launch
=> 3dsmax: opening last workfile

tests/unit/openpype/pipeline/publish/test_publish_plugins.py, website/docs/dev_colorspace.md
Refactor `ExtractorColormanaged` to `ColormanagedPyblishPluginMixin` in tests and documentation.
The PR https://github.com/ynput/OpenPype/pull/4556 refactored  `ExtractorColormanaged` to `ColormanagedPyblishPluginMixin` but the tests and documentation still referred to the old name.
1. Run tests
=> Update tests and documentation for  `ColormanagedPyblishPluginMixin`

openpype/lib/vendor_bin_utils.py
Use ffmpeg exec validation for ffmpeg executables instead of oiio exec validation. The validation is used as last possible source of ffmpeg from `PATH` environment variables, which is an edge case but can cause issues.
1. Remove ffmpeg from vendor bin
2. Make sure `"OPENPYPE_FFMPEG_PATHS"` env is not set
3. Add ffmpeg executable to `"PATH"` env variable
4. Open OpenPype and try to get ffmpeg path
=> General: Use right validation for ffmpeg executable

openpype/plugins/publish/collect_comment.py
Collect Comment plugin is instance plugin so should inherit from `InstancePlugin` instead of `ContextPlugin`.
Pyblish will resolve the plugin as instance plugin because of `instance` argument in `process` method, but it can be confusing for developer who does not know that.
=> General: Use right plugin class for Collect Comment

openpype/hosts/maya/plugins/create/create_animation.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
Add an option in Project Settings > Maya > Creator Plugins > Create Animation to include (or not) parent hierarchy. This is to avoid artists to check manually the option for all create animation.
=> Maya: Add "Include Parent Hierarchy" option in animation creator plugin

openpype/hosts/maya/plugins/publish/extract_look.py
Fix the logic which guesses the colorspace using `arnold` python library.
- Previously it'd error if `mtoa` was not available on path so it still required `mtoa` to be available.
- The guessing colorspace logic doesn't actually require `mtoa` to be loaded, but just the `arnold` python library to be available. This changes the logic so it doesn't require the `mtoa` plugin to get loaded to guess the colorspace.
- The if/else branch was likely not doing what was intended `cmds.loadPlugin("mtoa", quiet=True)` returns None if the plug-in was already loaded. So this would only ever be true if it ends up loading the `mtoa` plugin the first time.
```python
print(cmds.loadPlugin("mtoa", quiet=True))
print(cmds.loadPlugin("mtoa", quiet=True))
```
Originally implemented in PR …
=> Maya: Fix extract look colorspace detection

openpype/tools/sceneinventory/model.py, openpype/tools/sceneinventory/view.py, openpype/tools/utils/delegates.py
Whenever a "NOT FOUND" entry is present a lot of errors happened in the Scene Inventory:
- It started spamming a lot of errors for the VersionDelegate since it had no numeric version (no version at all). 
[Error reported on Discord](https://discord.com/channels/517362899170230292/563751989075378201/1082727536523489341):
```python
File "C:\Users\videopro\Documents\github\OpenPype\openpype\tools\utils\delegates.py", line 65, in paint
text = self.displayText(
File "C:\Users\videopro\Documents\github\OpenPype\openpype\tools\utils\delegates.py", line 33, in displayText
assert isinstance(value, numbers.Integral), (
AssertionError: Version is not integer. "None" <class 'NoneType'>
```
- Right click menu would error on NOT FOUND entries, and thus not show. With …
=> Scene inventory: Fix code errors when "not found" entries are found

openpype/hosts/nuke/plugins/publish/extract_review_data.py, openpype/hosts/nuke/plugins/publish/extract_review_data_lut.py, openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py, openpype/hosts/nuke/plugins/publish/extract_thumbnail.py, openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py, openpype/modules/deadline/plugins/publish/validate_deadline_pools.py, tests/integration/hosts/nuke/test_deadline_publish_in_nuke.py, tests/integration/hosts/nuke/test_publish_in_nuke.py
After Nuke had adopted new publisher with new creators new issues were introduced. Those issues were addressed with this PR. Those are for example broken reviewable video files publishing if published via farm. Also fixed local publishing. 
Global plugins had to be addressed too so please test also other DCCs if those are still working - talking of AfterEffects, Maya mainly.
1. Open Nuke workfile and publish render family node to farm.
2. Ideally test also included slate workflow (you might need to add slate tag to your ExctractReview output preset)
3. After the publish is done check Ftrack if reviewable video (with slate) was published.
=> Global | Nuke: fixing farm publishing workflow

openpype/lib/file_transaction.py, openpype/plugins/publish/integrate.py
Fix #4656 by enforcing unique destination transfers in the Integrator. It's now disallowed to a destination in the file transaction queue with a new source path during the publish.
Note that this is per instance - it doesn't validate cross-instance destinations in the context
1. Try integrating e.g. the example in #4656
=> Integrator: Enforce unique destination transfers, disallow overwrites in queued transfers

openpype/settings/defaults/project_settings/global.json, start.py
Define environment variable which lead to root of builtin ocio configs to be able change the root without changing settings. For the path in settings was used `"{OPENPYPE_ROOT}/vendor/bin/ocioconfig/OpenColorIOConfig"` which disallow to change the root somewhere else. That will be needed in AYON where configs won't be part of desktop application but downloaded from server.
1. Extraction with OCIO configs should work as did
=> General: Environment variable for default OCIO configs

openpype/hosts/hiero/api/plugin.py
Creator was showing 99 in workfile input for long time, even if users set default value to 1001 in studio settings. This has been fixed now.
1. open Hiero workfile project
2. select any clip in timeline and open Creator
3. Select clip creator and hit Create
4. Notice that Workfile start number is set to 1001. It used to show 99.
=> Hiero: Creator with correct workfile numeric padding input

openpype/modules/ftrack/event_handlers_user/action_applications.py, openpype/settings/defaults/project_settings/applications.json, openpype/settings/entities/schemas/projects_schema/schema_main.json, openpype/settings/entities/schemas/projects_schema/schema_project_applications.json, openpype/tools/launcher/models.py
Added option to filter applications that don't have valid executable available in settings in launcher and ftrack actions. This option can be disabled in new settings category `Applications`. The filtering is by default disabled.
1. Enable `project_settings/applications/only_available`
2. Make sure there is application which have set paths that don't lead to executable available on your machine
3. Add the application to a project
4. Open launcher and go to a task in project / Open actions on task in ftrack
5. The application should not be there
=> General: Filter available applications

openpype/lib/execute.py, openpype/lib/vendor_bin_utils.py, openpype/plugins/publish/extract_burnin.py, openpype/scripts/otio_burnin.py
Reduce the command line pop-ups that show on Windows during publishing.
This PR can be considered a continuation of PR #4481 
Also mentioned on discord [here](https://discord.com/channels/517362899170230292/517382145552154634/1087768816529985576)
Examples of the pop-ups can be found in the comments [here](https://github.com/ynput/OpenPype/pull/4481#issuecomment-1478126460):
https://user-images.githubusercontent.com/49758407/226671061-7a5b578d-5975-4344-827f-2f993bcf3337.mp4
---
The pop-ups:
I'm not entirely sure how to resolve the last two. It shows both when running from source and also when running from a `openpype_gui.exe` in a build.
1. Publish away with reviews and the (new?) publisher
=> Publisher: Windows reduce command window pop-ups during Publishing

openpype/lib/applications.py
Improve logging of what apps + tool environments got loaded for an application launch.
Before unordered (due to `set`) and unclear what belonged to what:
```
- { GlobalHostDataHook }: [  Will add environments for apps and tools: mtoa, 2023, 3-2, 3-1, maya  ]
```
After order is preserved and app name / tool names match:
```
- { GlobalHostDataHook }: [  Will add environments for apps and tools: maya/2023, mtoa/3-1, mtoa/3-2  ]
```
Additional benefit is that now you can also see/debug in what order the environments were build - so that if one env var ended up overriding one of another tool this might help to debug what could've overwitten what.
_Ignore the fact that for this test case in the screenshots/examples I added both mtoa 3.1 and 3.2 into a single asset_
1. Launch Tray (from code or …
=> Improve logging of used app + tool envs on application launch

openpype/hosts/celaction/hooks/pre_celaction_setup.py, openpype/hosts/celaction/plugins/publish/collect_celaction_cli_kwargs.py, openpype/modules/deadline/plugins/publish/submit_celaction_deadline.py, openpype/settings/defaults/project_settings/celaction.json, openpype/settings/entities/schemas/projects_schema/schema_project_celaction.json
Since some productions were requesting excluding some workfile parameters from publishing submission, we needed to move them to settings so those could be altered per project.
1. Open Studio settings at CelAction host and remove one of Workfile parameters.
2. Start Celaction on task and go to Submit render > Dialogue window will popup
3. Notice that parameters are not showing up. 
4. hit Submit and after publisher will open and Collect hit Publish
5. all should publish as usual
=> CelAction: conditional workfile parameters from settings

openpype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py, openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
Sync between hierarchical and non-hierarchical attributes should be fixed and work as expected. Action should sync the values as expected and event handler should do it too and only on newly created entities.
Action did not use proper table to get and change attribute values (user `ContextCustomAttributeValue` instead of `CustomAttributeValue`), so the received values were not right and changes were not propagated as expected. At the same time action had few bugs in way how values were pushed to ftrack. Event handler which should sync values automatically was based on task changes so it really never did changes as expected until a task was created/changed/moved/removed.
Both handlers are pushing the value to task (which was original purpose of the handlers) but the logic should be …
=> Ftrack: Hierarchical <> Non-Hierarchical attributes sync fix

openpype/hosts/nuke/plugins/load/load_backdrop.py, openpype/hosts/nuke/plugins/publish/collect_backdrop.py
No need to add frame range data into `nukenodes` (backdrop) family publishes - since those are timeless.
1. Open your favorite testing workfile in Nuke
2. Create randomly some nodes and select them all
3. Create Backdrop publishable instance with selection enabled
4. publish
5. Open Loader and see there are no frame range data 
6. Load nukenodes family node and see nothing is broken
7. ideally update it from older to newer version if you are having loaded nukenodes from previouse publishes.
https://github.com/ynput/OpenPype/pull/4383
=> Nuke: Nukenodes family instance without frame range

openpype/hosts/maya/plugins/publish/collect_review.py
Fix for attaching review to subset with pan/zoom option.
Recent changes allowed publishing of reviews with pan/zoom enabled, but introduced bug in case review is attached to subset. This is providing fix
1. Create review attached to something (model)
2. Publish
Publish should proceed normally.
=> Maya: bug fix for passing zoom settings if review is attached to subset

openpype/hosts/hiero/api/lib.py
Colors on loaded containers are now correctly identifying real state of version. `Red` for out of date and `green` for up to date.
1. open hiero testing workfile
2. load into current timeline deliberately older version of plate
3. Save with CTRL+S (clip should be shown as RED)
4. Open Inventory manager and Update version to latest
5. Save with CTRL+S (clip should be shown as GREEN)
=> Hiero: correct container colors if UpToDate

openpype/tools/project_manager/project_manager/view.py
Project manager can have frame start/end set to `0`.
1. Open project manager
2. Change frame start/end on asset to `0`
=> Project Manager: Change minimum frame start/end to '0'

openpype/settings/defaults/system_settings/applications.json
Fixing reliability of OpenPype startup in 3dsmax.
Unfortunately using `ADSK_3DSMAX_STARTUPSCRIPTS_ADDON_DIR` environment variable to specify location of OpenPype startup script isn't very reliable, because of clash with other plugins, some strange race condition happening during the startup of max, or for whatever obscure reason. This fix is forcing max to execute OpenPype startup script via command line argument. Caveat is that it might be harder to connect it to existing pipeline if this functionality is already used.
Try to launch 3dsmax with OpenPype integration - it should always work.
=> 3dsmax: make sure that startup script executes

openpype/hosts/maya/api/lib.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
Add Display Gradient Background toggle in settings to fix support for setting flat background color for reviews.
This fixes #4693.
New setting is `project_settings/maya/publish/ExtractPlayblast/capture_preset/Display Options/displayGradient`
1. Tweak the settings `project_settings/maya/publish/ExtractPlayblast/capture_preset/Display Options/displayGradient`
2. Set some diverse colors for background, backgroundTop and backgroundBottom.
3. Make a playblast for both case with gradient enabled and disabled.
=> Maya: Extract Review settings add Use Background Gradient

pyproject.toml
New version of PySide6 does not have issues with settings UI. It is still breaking UI stylesheets so it is not changed for other plaforms but it is enhancement from previous state.
Re-fetch third part libraries on MacOs
1. Run OpenPype on MacOs
2. Settings should work without any major issues
=> General: Update PySide 6 for MacOs

openpype/plugins/publish/collect_custom_staging_dir.py
Improve speed of Collect Custom Staging Directory.
Collect Custom Staging Directory made publishing with many instances very slow, this resolve that issue.
- No requerying of project settings in `get_custom_staging_dir_info`
- Only deepcopy anatomy data once we need to edit and use it.
1. Publish with and without a custom staging dir
=> Global: Improve speed of Collect Custom Staging Directory

openpype/tools/workfiles/files_widget.py, openpype/tools/workfiles/save_as_dialog.py
Browse might make sense even if there are no workfiles present, actually in that case it makes the most sense (eg. I want to locate workfile from outside - from Desktop for example).
1. Browse button in Workfiles should be enabled even in new tasks where no workfiles are present
=> Workfiles: keep Browse always enabled

website/docs/artist_hosts_aftereffects.md
Move publisher related tips for After Effects artist documentation to the correct position.
Before these notes would display under the "Load" block which was very confusing.
1. Read the docs.
=> Documentation: Move publisher related tips to publisher area

openpype/modules/deadline/plugins/publish/submit_publish_job.py
Generating config templates was hardcoded to `root[work]`. This PR fixes that.
1. Setup colour management in Maya with a config from a root directory.
2. Publish to Deadline.
3. Check the json generated has the correct template in `instances > representations > colorspaceData > config > template`.
=> Deadline: Submit publish job fails due root work hardcode - OP-5528

openpype/pipeline/create/context.py
Added option to remove attributes with UnkownAttrDef on instances. Pop of key will also remove the attribute definition from attribute values, so they're not recreated again.
This can be used for fix of instance data during collection after adding to context. The changes will be marked as changes for save but not yet saved to scene. The pop won't remove keys that have valid attribute definitions.
1. Create instance with unknown data in creator attributes
2. Remove the key when `CreatedInstance` object is created using `pop`
```python
instance_data["creator_attributes"]["new_key"] = "value"
instance = CreatedInstance(instance_data, self)
instance["creator_attributes"].pop("new_key")
```
=> CreateContext: Added option to remove Unknown attributes

openpype/plugins/publish/collect_otio_review.py
Collect OTIO review plugin is not crashing if `label` key is missing in instance data.
Label key is conditional. 
1. publish from Resolve clip which is having counterpart in reviewable layer
2. all should be published as expected
=> Global: label key in instance data is optional

openpype/tools/loader/model.py
There is missing variable `handles` in loader tool after https://github.com/ynput/OpenPype/pull/4746. The variable was renamed to `handles_label` and is initialized to `None` if handles are not available.
1. Make sure there is a version without handles information.
2. Open loader
3. The version should work and be shown in UI
=> Loader: Fix missing variable

openpype/lib/path_templates.py, openpype/pipeline/anatomy.py
Added option to format only single template from anatomy instead of formatting all of them all the time. Formatting of all templates is causing slowdowns e.g. during publishing of hundreds of instances.
- Anatomy formatting should work as before
- It should be possible to format single template in anatomy
```python
from openpype.lib import Anatomy
from openpype.pipeline.template_data import get_template_data_with_names
project_name = "*fill*"
asset_name = "*fill*"
task_name = "*fill*"
anatomy = Anatomy(project_name)
fill_data = get_template_data_with_names(
project_name,
asset_name,
task_name)
folder_template = anatomy.templates_obj["work"]["folder"]
folder_path = folder_template.format(fill_data)
print(folder_path)
```
=> General: Anatomy templates formatting

openpype/hosts/harmony/api/lib.py
External Harmony zip files might contain one additional level with scene name.
Without this zip files would fail with not really helpful `error: cannot determine scene file`.
Zip files like this might come from external artists as they are used to zip scene folder, not only select everything under scene folder
1. try to open this workfile zip in Harmony
[my_uploaded_scene.zip](https://github.com/ynput/OpenPype/files/11158094/my_uploaded_scene.zip)
=> Harmony: Handle zip files with deeper structure

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/workfile_template_builder.py
Popup window after Nuke start is not showing. Knobs with X/Y coordination on nodes where were converted from placeholders are not added if `keepPlaceholders` is witched off.
=> Nuke: Workfile Template builder fixes

openpype/hosts/maya/plugins/publish/extract_look.py
Fix Extract Look supporting python 2.7 for Maya 2020.
`attr` dataclass must be new style class.
1. Publish look from Maya 2020.
=> Maya: Fix Look Maya 2020 Py2 support for Extract Look

openpype/tools/settings/settings/widgets.py
Version completer popup have issues on some platforms, this should fix those edge cases. Also fixed issue when completer stayed shown fater reset (save).
Most important is that it does not make it worse for windows.
Windows & Linux & MacOs:
1. Open settings on windows
2. In System settings go to general in version selector
3. Click into input
4. The popup show up and should not cause a change of focus (infinite focus change from input to popup)
5. Reset settings UI when focus is in the input field
=> Settings: Version settings popup fix

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement_request.yml
Tweak some of the grammar in the issue form templates.
I also made the title `bug: ` and `enhancement: ` to be uppercase just so it's more in line with how issues currently look:
---
Also, it would be great if the "checkboxes" for _I added the labels and searched the issues_ would not come into the final issue report - just so that they don't show as "tasks" for the issue plus it just looks weird when reading the issue report too. As an example see this issue report: https://github.com/ynput/OpenPype/issues/4812
1. Read the differences
=> Github: Grammar tweaks + uppercase issue title

openpype/hosts/maya/api/lib.py
The `view_transform` returns a different format in Maya 2020. Fixes #4540 (hopefully).
Error message in current `develop`:
```
File "C:\Users\tokejepsen\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
runner(*args)
File "C:\Users\tokejepsen\OpenPype\openpype\hosts\maya\plugins\publish\collect_render.py", line 162, in process
File "C:\Users\tokejepsen\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 183, in get
return renderer(layer, render_instance)
File "C:\Users\tokejepsen\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 205, in __init__
self.layer_data.products = self.get_render_products()
File "C:\Users\tokejepsen\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 707, in …
```
=> Maya: Fix getting view and display in Maya 2020 - OP-5035

openpype/settings/defaults/project_settings/hiero.json, openpype/settings/entities/schemas/projects_schema/schema_project_hiero.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_imageio.json
New versions of Hiero were introduced with new colorspace property for Monitor Out. It have been added into project settings. Also added new config names into settings enumerator option.
I had also included Nuke config names update.
1. download file and copy paste content to `project_settings/hiero/imageio/workfile`
[imageio_workfile_settings.txt](https://github.com/ynput/OpenPype/files/11211367/imageio_workfile_settings.txt)
2. make sure `project_settings/hiero/imageio/workfile/monitorOutLut` is having set `ACES/Rec.709` and save settings
3. Open hiero at any task in your testing project (the same project where you configured the colorspace)
4. In Hiero OpenPype menu use `Apply Colorspace` 
5. then look into Project settings 
6. Look to Colorspace tab and see that all settings are …
=> Hiero/Nuke: adding monitorOut key to settings

openpype/settings/ayon_settings.py
Updated conversion script of AYON settings to v3 settings. PR is related to changes in addons repository https://github.com/ynput/ayon-addons/pull/6 . Changed how the conversion happens -> conversion output does not start with openpype defaults but as empty dictionary.
Instead of using OpenPype defaults as base is used empty dictionary. This revealed few missing conversions on the way as defaults were used instead so it look like nothing is wrong.
Shotgrid settings are not converted when different than OpenPype shotgrid module settings data are received (Forwads compatibility for new shotgrid addon).
1. Update addons on server with addons repository
2. Settings should load and work as expected
=> AYON: Update settings conversion

openpype/hosts/traypublisher/plugins/create/create_movie_batch.py, openpype/settings/defaults/project_settings/traypublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
Moved settings for `BatchMoviewCreator` into subcategory `create` in settings. Changes are made to match other hosts settings chema and structure.
Simple creators have separated category because they're not used the same way. Changed how settings are applied to creator plugin.
1. Create plugin should still work as did.
=> TrayPublisher: Move 'BatchMovieCreator' settings to 'create' subcategory

openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
Add `"review"` tag to output of extract sequence if instance is marked for review. At this moment only instances with family `"review"` were able to define input for `ExtractReview` plugin which is not right.
The request is to be able ignore review creator and use just scene render creator for `render` output which also creates reviewable. That is not possible now.
1. Open TVPaint
2. Enable Scene Render instance
3. Enable Review on the instance
4. Hit Publish
5. A reviewable should be created
=> TVPaint: Review can be made from any instance

openpype/client/entities.py, openpype/hosts/maya/api/workfile_template_builder.py, openpype/pipeline/workfile/workfile_template_builder.py
Problem
All the assets of the ftrack project are loaded and not those linked to the shot
How get error
Open maya in the context of shot, then build a new scene with the "Build Workfile from template" button in "OpenPype" menu.
=> Maya template builder load all assets linked to the shot

openpype/hosts/maya/tools/mayalookassigner/app.py
MayaLookAssigner erroring when MTOA is not loaded:
```
```
1. Unload `mtoa.mll`.
2. Assign a Vray look.
=> Maya: local variable 'arnold_standins' referenced before assignment - OP-5542

openpype/hosts/maya/plugins/publish/validate_single_assembly.py
Rig groups may now be parented to others groups when `includeParentHierarchy` attribute on the instance is "off".
This additionally means that it is technically possible now to export geometry that is not all part of a single hierarchy in the outliner. However, the chances are very slim since they are based on the `out_SET` of a rig which DOES have that validated. At the same time there isn't actually a direct issue with if there were potentially multiple top level nodes in the export, especially since `includeParentHierarchy=False` would be able to produce that too even if the rig instance itself was a top level group.
Based on Discord discussion [here](https://discord.com/channels/517362899170230292/1096006848664059944) with @friquette, @tokejepsen and @mkolar 
1. Publish an animation …
=> Maya: Remove single assembly validation for animation instances

openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
Sometimes when publishing with AE (we only saw this error on AE 2023), we got a KeyError for the handles in the "Collect Workfile" step. So I did get the handles from the context if ther's no handles in the asset entity.
=> After Effects: fix handles KeyError

openpype/hosts/max/hooks/force_startup_script.py, openpype/settings/defaults/system_settings/applications.json
Startup script for OpenPype was interfering with Open Last Workfile feature. Moving this loggic from simple command line argument in the Settings to pre-launch hook is solving the order of command line arguments and making both features work.
3dsmax has inconsistent behaviour about running custom startup script. The most reliable of them is passing `-U` command line argument with path to script file. But this argument can have multiple values so having it as the last one can make it work with specifying workfile.
1. Make sure there is no `-U ...` argument in Setting for 3dsmax.
2. Delete `ADSK_3DSMAX_STARTUPSCRIPTS_ADDON_DIR` env variable if present, it shouldn't be needed anymore
3. Run 3dsmax on task with already existing workfile
You should see OpenPype menu and the last workfile …
=> 3dsmax: move startup script logic to hook

openpype/hosts/maya/api/lib.py
Don't change time slider ranges in `get_frame_range`
The bug was introduced [here](https://github.com/ynput/OpenPype/pull/4664/files#r1170416917).
It shouldn't have made much difference since `get_frame_range` appears to ONLY be used in `reset_frame_range` but at least this now is consistent with the function's name.
1. Launch Maya
2. Reset frame range should work fine for the different profile support implemented with https://github.com/ynput/OpenPype/pull/4664
=> Maya: Don't change time slider ranges in `get_frame_range`

Dockerfile.centos7
For Centos dockerfile it is necessary to lock the patchelf version to the older, otherwise the build process fails.
=> Patchelf version locked

openpype/client/server/entities.py, openpype/client/server/entity_links.py, openpype/plugins/publish/integrate_inputlinks.py, openpype/plugins/publish/integrate_inputlinks_ayon.py, openpype/vendor/python/common/ayon_api/server_api.py, openpype/vendor/python/common/ayon_api/version.py
Implemented entity links get/create functions. Added new integrator which replaces v3 integrator for links.
Based on changes in https://github.com/ynput/OpenPype/pull/4841 . Modified ayon api with bugfix from develop.
**Publishing -> links integration**
1. Run publishing in a host with workfile instance
2. That should create links to the workfile
**Loader -> links getters**
1. Open Loader tool (e.g. from tray)
2. Go to asset with published subsets that were published with workfile (with links)
3. Select workfile subset
4. Change tab on right side of loader to `Dependency`
5. You should see dependent subsets there
=> AYON: Implement integrate links publish plugin

openpype/hosts/maya/tools/mayalookassigner/alembic.py, openpype/hosts/maya/tools/mayalookassigner/arnold_standin.py, openpype/hosts/maya/tools/mayalookassigner/vray_proxies.py
If `.abc` file is loaded into arnold standin support look assignment through the `cbId` attributes in the alembic file.
This is an enhancement after feature https://github.com/ynput/OpenPype/pull/4460 to allow Alembic files to also get looks assigned in arnold proxies as was requested on discord [here](https://discord.com/channels/517362899170230292/563751989075378201/1097828501924610068).
This re-uses the alembic functionality that was already there for vray proxies.
1. Load a `.abc` file in arnold standin
2. Assign a look
=> Maya: Support .abc files directly for Arnold standin look assignment

openpype/settings/defaults/project_settings/maya.json
Namespaces of loaded references are now _by default_ back to what they were before #4511 
I originally [mentioned it on the PR that the last `_` had to be there](https://github.com/ynput/OpenPype/pull/4511#discussion_r1160707262) but it seems to have been "resolved" at some point and then missed that it wasn't when it merged.
This also influences animation instances. Before #4511 the animation instances were `asset1_rigMain_01_1` in the outliner and subsets were `asset1_rigMain_01_`, after that PR the outliner instances became e.g. `asset1_rigMain_02` (due to name conflict with the namespace and thus the number increasing) and the subsets became `asset1_rigMain_01`. I'm not saying the trailing `_` for the subset names is nice. But at least with this PR the default settings is compatible …
=> Maya: Make default namespace naming backwards compatible

openpype/hosts/houdini/plugins/load/load_alembic.py, openpype/hosts/houdini/plugins/load/load_alembic_archive.py, openpype/hosts/houdini/plugins/load/load_bgeo.py, openpype/hosts/houdini/plugins/load/load_camera.py, openpype/hosts/houdini/plugins/load/load_image.py, openpype/hosts/houdini/plugins/load/load_usd_layer.py, openpype/hosts/houdini/plugins/load/load_usd_reference.py, openpype/hosts/houdini/plugins/load/load_vdb.py
Implement `switch` method on loaders
Fixes #4865 
- Houdini ass loader is skipped: it already had it implemented.
- Houdini hda loader is skipped: I wasn't too sure whether it'd be safe to implement it for the HDA loader.
- _Note that I believe technically the switching allows to switch "loaders" as well instead of only asset, subset or representation and that the `update` method should check for that I believe. However, I haven't seen any implementation as of yet that actually does so._
1. Load using the changes loaders.
2. Test switching to another asset (or representation), etc.
=> Houdini: Implement `switch` method on loaders

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/plugins/create/convert_legacy.py
Nuke legacy convertor was triggering deprecated function which is causing a lot of logs which slows down whole process. Changed the convertor to skip all nodes without `AVALON_TAB` to avoid the warnings.
1. Legacy convertor should not trigger deprecation warnings if there are not any deprecated nodes in the scene
2. Legacy convertor should discover legacy nodes if they are there
=> Nuke: Legacy convertor skips deprecation warnings

openpype/tools/publisher/window.py
Clear comment text field on successful publish and on window close.
Resolves #4867
1. Open new publisher
2. Write a comment in field at bottom
3. On window close + reopen the comment should be removed
4. Write a comment in field at bottom
5. On successful publish the comment should be removed
=> Publisher: Clear comment on successful publish and on window close

openpype/hosts/houdini/plugins/publish/collect_review_data.py
fix the bug of failing to publish extract review in Houdini
Original error:
```python
File "OpenPype\build\exe.win-amd64-3.9\openpype\plugins\publish\extract_review.py", line 516, in prepare_temp_data
"fps": float(instance.data["fps"]),
KeyError: 'fps'
```
1. Launch Houdini
2. Create Review Instance
3. Publish
=> Add fps as instance.data in collect review in Houdini.

openpype/hosts/traypublisher/plugins/publish/collect_review_frames.py
Fill required data to instance in traypublisher if instance has review family. The data are required by ExtractReview and it would be complicated to do proper fix at this moment! The collector does for review instances what did https://github.com/ynput/OpenPype/pull/4383
Ideally we should fill frame start/end from ranges of passed files, and use frame start from asset -> calculate frame end based on range from files. There is a lot of issues connected to this approach that may break other suff. We should also collect frame ranges for image frame sequences which are not right too (e.g. in burnins).
**Simple creators**
2. Select a creator (e.g. `render`)
3. Pass files to source file input and to review input
4. Publish
5. ExtractReview should not fail on missing data …
=> TrayPublisher: Fill missing data for instances with review

openpype/hosts/maya/plugins/publish/extract_look.py
Texture hash is calculated for textures used in published look and it is used as key in dictionary. In recent changes, this hash is not calculated for TX files, resulting in `None` value as key in dictionary, crashing publishing. This PR is adding texture hash for TX files to solve that issue.
In case of existing TX files the hash should be taken from TX file itself? Also, this needs to be changed anyway for AYON as we can't store hash information on version the same way we are doing it in OpenPype.
1. In Maya, create look that is using already existing TX files
2. Publish the look, it should be published ok.
=> Maya: Looks - calculate hash for tx texture

openpype/plugins/publish/validate_sequence_frames.py, tests/unit/openpype/plugins/publish/test_validate_sequence_frames.py
Slate workflow is now working as expected and Validate Sequence Frames is not raising the once slate frame is included.
Also testing routine is provided. 
1. `poetry run python .\start.py runtests <abs path>\OpenPype\tests\unit\openpype\plugins\publish\test_validate_sequence_frames.py`
=> Nuke: fixed broken slate workflow once published on deadline

openpype/tools/sceneinventory/model.py, openpype/tools/sceneinventory/window.py
Fix cherry pick issue in scene inventory.
As described in [source issue](https://github.com/ynput/OpenPype/issues/4593), the functionality is implemented only in blender. I didn't find out what it actually does?
```
File "S:\openpype\OpenPype\openpype\tools\sceneinventory\window.py", line 156, in refresh
self._model.refresh(**kwargs)
File "S:\openpype\OpenPype\openpype\tools\sceneinventory\model.py", line 211, in refresh
if not hasattr(host.pipeline, "update_hierarchy"):
AttributeError: 'FusionHost' object has no attribute 'pipeline'
```
1. Open scene inventory
2. Cherry pick an item there
=> Scene inventory: Model refresh fix with cherry picking

openpype/hosts/nuke/plugins/publish/collect_writes.py
If instance created in nuke was missing `review` flag, collector crashed.
1. try publishing prerender in nuke
=> Nuke: Pre-render and missing review flag on instance causing crash

openpype/hosts/fusion/plugins/create/create_saver.py, openpype/hosts/fusion/plugins/create/create_workfile.py
Simplify code for setting the icons for the Fusion creators
Icons look like before:
There was no need to reimplement `get_icon` methods.
1. Open Publisher in Fusion
2. Icons should still look beautiful for the instances
=> Fusion: Simplify creator icons code

openpype/tools/loader/model.py, openpype/tools/publisher/widgets/list_view_widgets.py
Fixes PySide 6.5 support in Loader.
There's a bug in PySide 6.5 it seems with multiple inheritance:
- https://bugreports.qt.io/browse/PYSIDE-2294
- https://bugreports.qt.io/browse/PYSIDE-2304
- https://forum.qt.io/topic/144262/typeerror-with-pyside-6-5-0-for-multiple-inheritance-of-mainwindow/7?_=1682360495905&lang=nl
In [this USD PR the inheritance order is reversed](https://github.com/PixarAnimationStudios/USD/pull/2392) to solve the issue, which also works in our case.
---
This PR also fixes an issue with the Publisher when switching list view mode when having a single instance selected - which is an issue I believe from PySide6+ not PySide6.5.
1. Launch Loader in PySide 6.5
2. Toggle list view mode in new publisher with a single instance selected.
=> Enhancement: Fix PySide 6.5 support for loader

openpype/pipeline/publish/publish_plugins.py, openpype/style/data.json, openpype/style/style.css, openpype/tools/attribute_defs/widgets.py, openpype/tools/publisher/constants.py, openpype/tools/publisher/control.py, openpype/tools/publisher/widgets/card_view_widgets.py, openpype/tools/publisher/widgets/create_widget.py, openpype/tools/publisher/widgets/list_view_widgets.py, openpype/tools/publisher/widgets/precreate_widget.py, openpype/tools/publisher/widgets/widgets.py, openpype/tools/publisher/window.py, openpype/tools/utils/__init__.py, openpype/tools/utils/widgets.py
Small changes in styles and form of publisher UI.
- Attribute definitions have smaller spacing and padding, their labels are aligned to right.
- Cards in card view are a little bit smaller (6px).
- Icons on cards should have unified size -> pixmaps are not sometimes resized correctly but card size is unified.
- Change of active states on card view works the same as in list view.
- Renamed `Options` to `Context`.
- Border radius on inputs is a little bit smaller.
- Scroll area have explicitly set borders to none -> in Houdini were black.
- Implemente combobox which ignores mouse wheel event until has active focus (avoid accidental change of values)
1. Open Publisher in different DCCs
2. Validate it is not broken
=> Publisher: Small style changes

openpype/cli.py, openpype/client/mongo.py, openpype/lib/project_backpack.py, openpype/pype_commands.py
Pack project functionality have option to zip only project database without project files. Unpack project can skip project copy if the folder is not found.
Added helper functions to `openpype.client.mongo` that can be also used for tests as replacement of mongo dump.
1. Run `openpype_console pack-project --project YourProjectName --dbonly`
2. Look to project root folder where should be a zip file with only `metadata.json` and `database.json`
3. Now try to reverse the project using `openpype_console unpack-project --zipfile C:/path/to/your/file.zip`
4. Project should be recreated in mongo
=> Project packager: Backup and restore can store only database

openpype/hosts/maya/plugins/publish/extract_playblast.py
When pan/zoom enabled attribute on camera is locked, playblasting with pan/zoom fails because it is trying to restore it. This is fixing it by skipping over with warning.
1. Create camera, lock pan/zoom attribute
2. Publish review from it
3. Publishing shouldn't fail
=> Maya: soft-fail when pan/zoom locked on camera when playblasting

openpype/hosts/maya/plugins/load/load_reference.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_load.json
When we load a reference in Maya using OpenPype loader, display handle is checked by default and prevent us to select easily the object in the viewport. 
I understand that some productions like to keep this option, so I propose to add display handle to the reference loader settings. 
1. Using Openpype loader in Maya, load an asset as reference. 
2. Verify that Display Handle is following the settings.
=> Maya Load References - Add Display Handle Setting

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/hosts/aftereffects/plugins/publish/collect_render.py, openpype/hosts/aftereffects/plugins/publish/collect_review.py, openpype/hosts/aftereffects/plugins/publish/extract_local_render.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py, openpype/pipeline/publish/abstract_collect_render.py, openpype/settings/defaults/project_settings/aftereffects.json, openpype/settings/defaults/project_settings/deadline.json, openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json, tests/integration/hosts/aftereffects/test_deadline_publish_in_aftereffects_multicomposition.py
Adds `mark_for_review` flag to the Creator to allow artists to disable review if necessary.
Exposed this flag in Settings, by default set to True (eg. same behavior as previously).
Not sure if `CollectReview` should be separate plugin and exposed in Settings. I matched state from Photoshop to be the same.
Adding 'review' family from `creator_attributes` could be easily moved to `collect_render.py` and whole `collect_review.py` removed.
1. toggle `Review` flag in created `render` instance in AE 
2. publish locally
3. publish on Deadline
=> AfterEffects: add review flag to each instance

openpype/pipeline/publish/lib.py
remote publishing was missing import of `remote_publish`. This is adding it back.
This was affecting publishing on farm, like pointcache.
1. Try to publish pointcache on farm from Maya
2. Everything should work
=> Bug: add missing `pyblish.util` import

openpype/hosts/unreal/plugins/load/load_animation.py, openpype/hosts/unreal/plugins/load/load_layout.py
Epic removed the `object_path` property from `AssetData`. This PR fixes usages of that property.
Fixes #4936 
1. In Unreal, load a layout.
2. Try changing version of the layout.
=> Unreal: Fix missing 'object_path' property

openpype/hosts/maya/api/workfile_template_builder.py
When we build an asset workfile with build workfile from template inside Maya, we load our turntable camera. But then we end up with 2 renderables camera : **persp** the one imported from the template.
We need to remove the **persp** camera (or any other default camera) from renderable cameras when building the work file.
1. In Maya, build a scene from the template.
2. Check the render settings so that there is no persp camera in the list renderble cameras.
=> Maya Template Builder - Remove default cameras from renderable cameras

poetry.lock, pyproject.toml
This updates Gazu to 0.9.3 to make sure Gazu works with Kitsu and Zou 0.16.x+
Currently users running Gazu 0.8.x won't be able to communicate with Kitsu 0.16.x+
```
Hello all, we did a lot of Kitsu Python dependencies upgrades. Most of them doesn't support old versions of Python. So our next release, the 0.16.0 (Zou and Kitsu) 0.9.0 for Gazu will come with some breaking changes:
- Gazu (the python client for our API) will no longer support Python versions below 3.6.
- Zou (the Kitsu API)  will no longer support Python versions below 3.8.
We upgraded the python-socketio package in both Gazu and Zou which use the Socket.IO protocol in version 5.
So, to keep realtime features working between Kitsu (the frontend) and Zou (the API) we also need to use the same Socket.IO protocol, so we also …
```
=> Bugfix - Update gazu to 0.9.3

openpype/hosts/maya/api/workfile_template_builder.py
When building a template with Maya template builder, we import the template and also the references inside the template file. This causes some problems:
- We cannot use the references to version assets imported by the template.
- When we import the file, the internal reference files are also imported. As a side effect, Maya complains about a reference that no longer exists. 
`// Error: file: /xxx/maya/2023.3/linux/scripts/AETemplates/AEtransformRelated.mel line 58: Reference node 'turntable_mayaSceneMain_01_RN' is not associated with a reference file.`
1. Create a template containing some references.
2. Build the workfile with template builder from openpype menu
=> Maya template builder - preserve all references when importing a template

openpype/hosts/unreal/plugins/load/load_camera.py
Fix the frame range of the level sequence for the Camera in Unreal.
1. Load a camera in Unreal.
2. Open the level sequence that has been created.
3. Check if the frame range of the sequence is the one set in the project manager.
=> Unreal: Fix camera frame range

openpype/hosts/houdini/api/pipeline.py
Shelf generation during Houdini startup would add an insane amount of delay for the Houdini UI to launch correctly. By deferring the shelf generation this takes away the 5+ minutes of delay for the Houdini UI to launch.
The Houdini 'bug' was also described in Shotgrid's houdini toolkit [here](https://github.com/shotgunsoftware/tk-houdini/blob/af194f38b316384726a5555e8851060e95e9afaa/engine.py#L201-L220). (They seem to poll with a Qt timer, but `hdefereval.executeDeferred` seems to work just fine. I also described the problem in [this comment](https://github.com/ynput/OpenPype/issues/4061#issuecomment-1503985901).
1. Configure a custom shelf in OP project settings `project_settings/houdini/shelves`
=> Houdini: Fix slow Houdini launch due to shelves generation

openpype/hosts/unreal/addon.py
Removed Python 3.8 syntax from addon.
Causing crashes in older pythons inside DCCs.
=> Unreal: Remove Python 3.8 syntax from addon

poetry.lock, pyproject.toml
Remove AYON python api from pyproject.toml and poetry.lock again.
Was already removed in https://github.com/ynput/OpenPype/pull/4753 and somehow got back.
1. AYON mode should work as before
=> General: Remove ayon api from poetry lock

openpype/vendor/python/common/scriptsmenu/scriptsmenu.py
Add the possibility to associate a shorcut for an entry in the script menu definition with the key "shortcut"
Example of an entry with a shortcut:
=> Add "shortcut" to Scripts Menu Definition

.gitignore, openpype/addons/README.md, openpype/modules/base.py
This adds a directory for Addons, for easier distribution of studio specific code.
Discussion about how to distribute and maintain studio specific code is going on the forums; https://community.ynput.io/t/studio-specific-code/182/11
1. Add an addon to the `openpype/addons` directory.
2. Create a build, zip and installer.
3. Validate the addon files are included with the build, zip and installer.
=> Addons directory

openpype/modules/kitsu/plugins/publish/integrate_kitsu_note.py, openpype/modules/kitsu/plugins/publish/integrate_kitsu_review.py, openpype/settings/defaults/project_settings/global.json
This PR adds "image", "online" and "plate" to the review families so they also can be uploaded to Kitsu.
It also adds the `Add review to Kitsu` tag to the default png review. Without it the user would manually need to add it for single image uploads to Kitsu and might confuse users (it confused me first for a while as movies did work).
1. Publish an image, video or image sequence as an image, online or plate and watch the review be uploaded to Kitsu
=> Kitsu - Add "image", "online" and "plate" to review families

openpype/hosts/maya/plugins/publish/validate_shader_name.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Running the plugin would error with:
```
// TypeError: 'str' object cannot be interpreted as an integer
```
Fixed and added setting `active`.
1. Enable `project_settings/maya/publish/ValidateShaderName`
2. Launch Maya, create a look and publish.
3. Validation should fail with information about naming of shader.
=> Maya: Validate shader name - OP-5903

openpype/hosts/unreal/plugins/load/load_layout_existing.py
Fixed transform when loading layout to match existing assets.
Changed the way the transform is applied to match the one for the regular layout loading.
1. In Unreal, load assets that have been published in a layout.
2. Add the assets to a level and save it.
3. Open the loader, select the layout, and select **Load Layout on Existing Scene**.
4. The transform for the assets should be correct.
=> Unreal: Fix transform when loading layout to match existing assets

pyproject.toml, tools/fetch_thirdparty_libs.py
So that DCCs don't conflict with their own.
See https://github.com/ynput/OpenPype/pull/4267#issuecomment-1537153263 for the issue with Gaffer.
I'm not sure if this is the correct approach, but I assume PySide/Shiboken is under `vendor/python` for this reason as well...
=> Global: Move PyOpenColorIO to vendor/python 

openpype/hosts/aftereffects/api/pipeline.py
Allows to use Workfile app to Save first empty workfile.
1. Open task without any workfile in AE
2. Use Save As to create first workfile
=> AfterEffects: allow returning stub with not saved workfile

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/load/load_reference.py, website/docs/admin_hosts_maya.md
We are using the template builder to build an animation scene. All the rig placeholders are imported correctly, but the automatically created animation instances retain the rig family in their names and subsets. In our example, we need animationMain instead of rigMain, because this name will be used in the following steps like lighting.
Here is the result we need. 
I checked, and it's not a template builder problem, because even if I load a rig as a reference, the result is the same. For me, since we are in the animation instance, it makes more sense to have animation instead of rig in the name. The naming is just fine if we use create from the Openpype menu.
1. In Maya, in the animation task, use the template builder to build a template that contains rig placeholders. 
2. The created …
=> Load Rig References - Change Rig to Animation in Animation instance

openpype/modules/sync_server/sync_server.py
Some optimization condition is messing with the feature: if the published workfile is not already downloaded, it won't download it...
1. Clear all local cache in full remote configuration
2. Try to launch any file
=> Fix: Download last workfile doesn't work if not already downloaded

openpype/client/server/conversion_utils.py, openpype/client/server/operations.py
Fix integration of files into representation in server database.
The `files` were not integrated correctly. They were added to representation data instead of representation itself and the structure of files data were not right. Fixed the structure and fixed missing sites that were already handled, but not correctly. Also fixed update of hero version, where `"version_id"` change is skipped.
1. Integration in AYON mode should work and representations on server should have files
2. Update of representations should work
3. Update of hero version should work
NOTE: To test hero version enable the plugin in settings and add family you want to test to families filter in settings.
=> AYON: Missing files on representations

openpype/hosts/unreal/addon.py, openpype/hosts/unreal/lib.py
Fixed Python 2 compatibility of unreal addon.
Current addon implementation causes SyntaxError in Python 2 DCCs. Which is very scary for artists.
1. Unreal addon should not cause any crashes when ModulesManager is initialized in Python 2 DCC
=> Unreal: Addon Py2 compatibility

openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py, website/docs/dev_publishing.md
Added plugins option to define settings category where to look for settings of a plugin and added public helper functions to apply settings `get_plugin_settings` and `apply_plugin_settings_automatically`.
Plugin has no way how to tell automated settings apply function where to look for it's settings. We allow 2 options, one is to look for settings into current host (we should maybe remove that completelly?), second is to use 3rd parent folder name from plugin file -> we're lucky it somehow worked.
We already have option to implement `apply_settings` class method, but then developer looses the option to automatically apply the settings -> that's why those functions were made as public, so it is at least possible to reuse them.
In most of cases all we need to define is the first level of …
=> Publish: Enhance automated publish plugin settings

openpype/hosts/unreal/plugins/load/load_camera.py
The keyframes of the camera, when loaded, were not using the correct frame range.
1. Load camera in Unreal.
2. Check in the sequencer if the frame range is right and the keyframes are in the right range.
=> Unreal: Fix the frame range when loading camera

openpype/plugins/publish/integrate_version_attrs.py
Implemented unified integrate plugin to update version attributes after all integrations for AYON. The goal is to be able update attribute values in a unified way to a version when all addon integrators are done, so e.g. ftrack can add ftrack id to matching version in AYON server etc.
The can be stored under `"versionAttributes"` key.
Since nothing is yet implementing `versionAttributes` the testing is hard.
=> General: Version attributes integration

openpype/hosts/nuke/plugins/publish/collect_writes.py
Issue with missing keys once rendering target set to existing frames is fixed. Instance has to be evaluated in validation for missing files.
1. Open nuke workfile and create new Render family instance on any selected node. 
2. Do not render any frames and set instance's render target to Existing frames
3. hit Publish button and notice that Validate Rendered frames is popping up. 
4. This is correct behaviour.
=> Nuke: fixed missing files key in representation

openpype/hosts/unreal/plugins/load/load_animation.py, openpype/hosts/unreal/plugins/load/load_camera.py, openpype/hosts/unreal/plugins/load/load_layout.py
This PR changes all the occurrences of `get_full_path` functions to alternatives to get the path of the objects.
`get_full_path()` returns a string that includes the name of the class of the objects. This was preventing the change of the level in most of the loaders, and to save some of the assets.
This function has been included to fix another error in PR #4938.
The function was not causing evident errors. But there were some messages in the output log that it was impossible to change level because the path was malformed.
One of the most evident problems was that updating a layout placed the new asset in the wrong level, so to test if the PR is working, try updating a layout and check if the assets are in the correct level.
=> Unreal: Fix usage of 'get_full_path' function

openpype/settings/entities/lib.py
It is possible to nest settings templates in another templates.
Not sure if this is a bugfix or enhancement? I think it did work in past, but not really sure.
1. Nest template inside another template and use it in settings.
```
[
{"type": "boolean", "key": "test_bool"}
]
[
{"type": "template", "name": "template_1"}
]
```
2. UI Should not crash.
=> Settings: Added option to nest settings templates

openpype/hosts/unreal/plugins/publish/validate_sequence_frames.py
Fix sequence frames validator to use clipIn and clipOut data instead of frameStart and frameEnd.
1. In Unreal, create a Render instance.
2. Render the sequence.
3. Try publishing. The validator should pass if data is correct in the Project Manager.
=> Unreal: Fix sequence frames validator to use correct data

openpype/hosts/unreal/plugins/publish/collect_render_instances.py
Fix render instances collection to use `frameStart` and `frameEnd` from the Project Manager, instead of the sequence's ones.
1. In Unreal, create a Render instance and render it.
2. Publish the render.
3. Check in the published render files if the name uses the right frame range.
=> Unreal: Fix render instances collection to use correct data

openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/integrate_thumbnail.py, openpype/tools/publisher/control.py
Publisher UI does not crash if instance don't have filled 'label' key in instance data.
Issue was added with publish instances view in [this PR](https://github.com/ynput/OpenPype/pull/4915). Reported in UE where are instances without filled `"label"` key. Implemented helper function 'get_publish_instance_label' in publish lib, to get label from pyblish instance.
1. Make sure you have publish instance without label filled
2. Use publisher UI to publish
3. Wait for successfull publishing, or stop publishing in middle
4. On left side should be instances view without any major issues
=> Publisher: UI works with instances without label

openpype/modules/ftrack/ftrack_server/lib.py
Limit the amount of ftrack events received from mongo at once to 100.
We hit a limit of message length when there is a heap of events to process, which should be avoided by limiting the documents returned from mongo.
Not sure how to test? Somehow make more than 100 events at a time and validate they are processed in correct order.
=> Ftrack: Limit number of ftrack events to query at once

openpype/hosts/nuke/api/pipeline.py
Nuke was slowed down on processing due this callback. Since it is disabled by default it made sense to add it only on demand. 
It is very difficult to measure the difference in performance. It could be noticeable in multitude of image sequence Readers with higher resolution merged together into one viewer and played. The framerate during loading could identify the difference. Good benchmark is to compare it with Nuke session started from OpenPype and then the same nuke script opened with Nuke without OpenPype.
1. you shell enable or disable it from here `project_settings/nuke/nuke-dirmap/enabled`
2. See the difference in cashing and playback performance.
=> nuke: callback for dirmapping is on demand

openpype/tools/publisher/window.py
It is not possible to go to Create tab during publishing from OpenPype menu.
Public method `set_current_tab` does not use directly `_set_current_tab` but one of prepared methods. There are two ways how to handle this. One is this, the other is to move the condition from `_go_to_create_tab` to `_set_current_tab`. I don't have preference.
1. Make sure you're in host where `Create` action in OpenPype menu opens publisher on Create tab
1. Open publisher
2. Start publishing
3. Pause publishing (or just validate)
4. Click on the `Create` action in menu
5. The UI should not change to `Create` tab
=> Publisher: Call explicitly prepared tab methods

openpype/hosts/maya/plugins/publish/validate_instance_has_members.py
When publishing a `rendersetup`, the objectset is and should be empty.
1. Create `rendersetup` in Maya.
2. Publish.
=> Maya: Skipping rendersetup for members.

openpype/modules/deadline/plugins/publish/submit_publish_job.py
If the publish path on Deadline job contains spaces or other characters, command was failing because the path wasn't properly escaped. This is fixing it.
1. Try to submit publish job with space in the path
2. Everything should work as expected
=> Deadline: escape rootless path in publish job

openpype/hosts/blender/api/pipeline.py, openpype/settings/defaults/project_settings/blender.json, openpype/settings/entities/schemas/projects_schema/schema_project_blender.json
A setting for the base unit scale has been added for Blender.
The unit scale is automatically applied when opening a file or creating a new one.
1. Set a default unit scale in Studio Settings: `project_settings/blender/base_file_unit_scale`.
2. Open any task with Blender.
3. Check if the unit scale has been applied:
=> Blender: Added setting for base unit scale

openpype/modules/ftrack/lib/ftrack_action_handler.py, openpype/modules/ftrack/scripts/sub_event_status.py
Event server status action is not case sensitive for role names of user.
1. Change role name of `pypeclub` to e.g. `PyPeCLuB` in ftrack
2. Run event server
3. Status action should be visible in actions list
=> Ftrack: Role names are not case sensitive in ftrack event server status action

poetry.lock, pyproject.toml
I changed Click to version 8.0 instead of 7.1.2 to solve this error:
```
2023-05-30 16:16:51:  0: STDOUT: Traceback (most recent call last):
2023-05-30 16:16:51:  0: STDOUT:   File "start.py", line 1126, in boot
2023-05-30 16:16:51:  0: STDOUT:   File "/prod/softprod/apps/openpype/LINUX/3.15/dependencies/click/core.py", line 829, in __call__
2023-05-30 16:16:51:  0: STDOUT:     return self.main(*args, **kwargs)
2023-05-30 16:16:51:  0: STDOUT:   File "/prod/softprod/apps/openpype/LINUX/3.15/dependencies/click/core.py", line 760, in main
2023-05-30 16:16:51:  0: STDOUT:     _verify_python3_env()
2023-05-30 16:16:51:  0: STDOUT:   File "/prod/softprod/apps/openpype/LINUX/3.15/dependencies/click/_unicodefun.py", line 126, in _verify_python3_env
2023-05-30 16:16:51:  0: STDOUT:     raise …
```
=> RuntimeError with Click on deadline publish

openpype/tools/publisher/widgets/border_label_widget.py
Fixed border lines in Publisher UI to be painted correctly with correct indentation and size.
If this did not happen to you before this PR, you're can't validate the change much.
1. Open Publisher
2. Check the painted borders visible in Create and Publish pages
=> Publisher: Fix border widget

openpype/hosts/maya/plugins/publish/validate_rig_output_ids.py
Absolute names of node were not used, so plugin did not fetch the nodes properly.
Also missed pymel command.
1. Load model.
2. Setup rig with duplicate of model.
3. Validation should fail on the plugin.
4. Repair and publish.
=> Maya: Validate Rig Output IDs

website/docs/project_settings/settings_project_global.md
Wrong image display in `https://openpype.io/docs/project_settings/settings_project_global#extract-oiio-transcode`.
=> Docs: Display wrong image in ExtractOIIOTranscode

openpype/hosts/unreal/ue_workers.py, openpype/settings/defaults/project_settings/unreal.json
Fix problem when creating an Unreal Project when Commandlet Project is in a protected location. 
The Commandlet project is now first copied to a temporary directory.
Fixes #5060 
1. These changes need to be added to the installed version of OpenPype.
2. Try creating a new Unreal Project in any task.
=> Unreal: Fix Commandlet Project and Permissions

openpype/hosts/unreal/addon.py
The Unreal app name is used to determine the Unreal version folder, so it is necessary that if follows the format `x-x`, where `x` is any integer. This PR adds a verification that the app name follows that format.
Fixes #5062
1. Add a new version of Unreal in OpenPype System Settings, and add as key any string that does not respect the format.
2. Add that version to `project_anatomy/attributes/applications`.
3. Try creating a new Unreal project opening a task with that new Unreal version you added. It should show an error.
=> Unreal: Added verification for Unreal app name format

openpype/hosts/resolve/utils.py
Make sure the scripts directory exists before looping over it's content.
The issue appeared to me on first launch.
1. Remove utils script dir on your workstation
2. Launch Resolve -> That should not crash
=> Resolve: Make sure scripts dir exists

openpype/settings/ayon_settings.py
Fixed settings for AYON variant of sync server.
1. Addon ayon-sitesync should work in AYON mode.
2. Sync server should work in OpenPype mode.
=> AYON: Fix site sync settings

igniter/tools.py, openpype/client/mongo/mongo.py
Use argument `tlsCAFile` instead of `ssl_ca_certs` to avoid deprecation warnings.
Argument `ssl_ca_certs` is marked as deprecated by `pymongo` module.
1. Connection to secure mongo server should work (e.g. cloud mongo)
=> General: Replace deprecated keyword argument in PyMongo

openpype/tools/tray/pype_tray.py
Fix arguments on restart.
First argument in `sys.argv` is always removed. When running from code, it contains `start.py` script path and when running from build it contains path to openpype executable. The argument of executable can be what was passed to terminal so it could be `./openpype_console` (on linux).
Update and restart from tray should work. To replicate
1. Make sure you have at least one version in update repository
2. Choose the latest version in update repository and make sure it is not available in your local versions in local app data
3. Run openpype with different version using `--use-version={lower version}` (this version must have changes from this PR)
4. It should ask to update and restart -> condifm to update and restart
5. OpenPype should start when update finished
=> Tray: Fix restart arguments on update

poetry.lock, pyproject.toml
Use older version of Unidecode module to support Python 2.
The version definition `^1.2` does not specify that the version should be `1.2.*` so latest (`1.3.6`) version was used.
1. OpenPype should run in Python 2 DCCs
=> General: Lower unidecode version

openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/publish/collect_render.py, openpype/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py, openpype/modules/deadline/plugins/publish/collect_default_deadline_server.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py
Fix working with multiple Deadline servers in Maya.
- Pools (primary and secondary) attributes were not recreated correctly.
- Order of collector plugins were wrong, so collected data was not injected into render instances.
- Server attribute was not converted to string so comparing with settings was incorrect.
- Improve debug logging for where the webservice url is getting fetched from.
1. Add multiple webservices to `modules/deadline/deadline_urls`.
2. Setup render and use non-default webservice in Maya.
3. Publish.
4. Test enabling/disabling webservices in `project_settings/deadline/deadline_servers`.
=> Maya: Deadline servers

openpype/lib/project_backpack.py
Single roots validation is skipped if only documents are extracted.
1. Create/Change project to have more than 1 root
2. Run `pack-project` command with `--dbonly` flag
3. Output should be exported without any issues
4. The same file should be possible to unpack using `unpack-project`
=> Project pack: Documents only skips roots validation

openpype/tools/publisher/window.py
The default windowFlags is making the publisher window (in Linux at least) only show the close button and it's frustrating as many times you just want to minimize the window and get back to the validation after. Removing that line I get what I'd expect.
**Before:**
**After:**
1. Open publisher window
=> General: Remove default windowFlags from publisher

openpype/hosts/maya/plugins/publish/validate_arnold_scene_source_cbid.py
Fix the bug of not being able to use repair action  in Arnold Scene Source CBID Validator
n/a
1. Launch Maya via OP
2. Create Arnold Scene Source Instance with Content mesh and proxy mesh.
3. Run the publisher
4. If it triggers the Arnold Scene Source CBID Validator, right-click to repair it.
5. Run the publisher again
6. It will pass the validation.
=> Maya: bug fix on repair action in Arnold Scene Source CBID Validator

openpype/hosts/maya/plugins/publish/collect_arnold_scene_source.py
When collecting cameras for `ass` family, this improves the error message when no cameras are renderable.
1. Setup `ass` instance in Maya.
2. Ensure no cameras are renderable.
3. Publish and validate collection error message.
=> Maya: Improve error feedback when no renderable cameras exist for ASS family.

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/pipeline.py, openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/create/create_backdrop.py, openpype/hosts/nuke/plugins/create/create_camera.py, openpype/hosts/nuke/plugins/create/create_gizmo.py, openpype/hosts/nuke/plugins/create/create_model.py, openpype/hosts/nuke/plugins/create/create_source.py, openpype/hosts/nuke/plugins/create/create_write_image.py, openpype/hosts/nuke/plugins/create/create_write_prerender.py, openpype/hosts/nuke/plugins/create/create_write_render.py
- removing instance node if removed via publisher
- removing info knob since it is not needed any more (was there only for the transition phase)
1. nuke should create instance nodes without info message
2. Nuke should remove node once is bin icon used in Publisher on particular instance
=> removing info knob from nuke creators

openpype/tools/launcher/models.py
The launcher actions weren't being sorted by its label but its name (which on the case of the apps it's the version number) and thus the order wasn't consistent and we kept getting a different order on every launch. From my debugging session, this was the result of what the `actions` variable held after the `filter_compatible_actions` function before these changes:
```
(Pdb) for p in actions: print(p.order, p.name)
0 14-02
0 14-02
0 14-02
0 14-02
0 14-02
0 19-5-493
0 2023
0 3-41
0 6-01
```
This caused already a couple bugs from our artists thinking they had launched Nuke X and instead launched Nuke and telling us their Nuke was missing nodes
**Before:**
**After:**
1. Start the launcher and check the order of the apps
=> General: Sort launcher actions alphabetically

poetry.lock, pyproject.toml
Lower cryptography to 39.0.0 to avoid breaking of DCCs like Maya and Nuke.
1. Run create_env script in tools
2. Run tray
3. Launch Nuke 13 (or lower) or Maya 2022 (or lower)
=> General: Lower cryptography to 39.0.0

openpype/client/server/entities.py
Added support for `active` argument to hide versions with active set to False in Loader UI when in AYON mode.
This PR is adding implementation required by [this PR](https://github.com/ynput/OpenPype/pull/5100).
=> Loader: Hide inactive versions in UI - Next release

openpype/modules/deadline/plugins/publish/submit_publish_job.py
Prerender wasn't correctly recognized and was replaced with just 'render' family.
In Nuke it is correctly `prerender.farm` in families, which wasn't handled here. It resulted into using `render` in templates even if `render` and `prerender` templates were split.
Eventually this query should be simplified only to `prerender.farm`, but this way it is safer for now.
1. Publish `prerender` in Nuke via Deadline
2. check metadata.json in `work` folder, families need to contain `prerender`
=> Deadline: make prerender check safer

openpype/hosts/maya/plugins/publish/validate_rendersettings.py
Validator was flagging that `<RenderPass>` was in the image prefix, but did not repair the issue.
1. Setup render in Maya with `Merge AOV` enabled.
2. Ensure `<RenderPass>` token is in image prefix.
3. Publish and repair.
=> Maya: Repair RenderPass token when merging AOVs.

openpype/settings/ayon_settings.py
Seems that when converting ayon settings to OP settings the `environments` setting is put under the `environments` key in `general` however when populating the environment the `environment` key gets picked up, which does not contain the environment variables from the `core/environments` setting
=> AYON: Global environments key fix

openpype/cli.py
Added `addon` alias for `module` in OpenPype cli commands.
1. Choose addon cli command of your will e.g. traypublisher
2. Replace `module` with `addon` in the command e.g. `openpype_console addon traypublisher launch`
3. It should work
=> General: CLI addon command

openpype/client/entities.py, openpype/tools/loader/model.py, openpype/tools/utils/delegates.py
Hide versions with `active` set to `False` in Loader UI.
This required changes in next-minor release too.
There is not a function to change or set active of version in our codebase.
1. Open Loader UI
2. Choose a subset with version
3. Find the version in Mongo
4. Set it's `data.active` to `False`
5. Refresh loader UI
6. The version should disappear from UI
=> Loader: Hide inactive versions in UI

openpype/hosts/max/api/pipeline.py
`INewPublisher` interface is deprecated, this PR is changing the use to `IPublishHost` instead.
This shouldn't affect functionality and it should allow to remove `INewPublisher` from code as 3dsmax integration was its last use.
1. open 3dsmax
2. try to publish something
=> 3dsmax: Move from deprecated interface

openpype/hosts/traypublisher/plugins/create/create_editorial.py
Editorial create plugin in traypublisher does not expect that first stream in input is video.
The first stream is usually audio if there is any and video is available later on.
1. Prepare edl with video that has available audio
2. Pass the edl and video with audio in traypublisher on Editorial create plugin
3. Hit create
4. There should not be issue about reading fps from the input
=> TrayPublisher: Editorial video stream discovery

openpype/hosts/maya/plugins/publish/validate_rendersettings.py
When validating render settings attributes, support same attribute names on different node types.
1. Add the following settings to `project_settings/maya/publish/ValidateRenderSettings/arnold_render_attributes`:
- aiAOVDriver.exrCompression = 8
- renderGlobals.exrCompression = 2
2. Setup render in Maya with Arnold and Publish.
=> Maya: Support same attribute names on different node types.

tools/build.sh
Set `LSUIElement` to `1` in the `Info.plist` to hide OP icon from the macos dock by default.
https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement
=> hide macos dock icon on build

openpype/tools/publisher/widgets/create_widget.py
Whenever a person is creating a subset to publish, the "creator" widget resets (where you choose the variant, product, etc.) so if the person is publishing several images of the a variant which is not the default one, they have to keep selecting the correct one after every "create".
This commit resets the original variant upon successful creation of a subset for publishing.
Demo:
[Screencast from 2023-06-08 10-46-40.webm](https://github.com/ynput/OpenPype/assets/1800151/ca1c91d4-b8f3-43d2-a7b7-35987f5b6a3f)
1. Launch AYON/OP
2. Launch the publisher (select a project, shot, etc.)
3. Crete a publish type (any works)
4. Choose a variant for the publish that is not the default
5. "Create >>"
The Variant fields should still have the variant you choose.
=> Keep `publisher.create_widget` variant when creating subsets

openpype/tools/creator/model.py
I added the possibility to filter the `family smart select` with the label in addition to the family.
The family smart select does not work with the default settings and it is not intuitive for users to have to know the family instead of the family label.
With the default settings (to test this new add):
1. open a light task in maya
2. open the creator interface
3. if it works Render is selected
To test the legacy code change the family smart select option from `render` to `rendering`:
1. open a light task in maya
2. open the creator interface
3. if it works Render is selected
=> add label to matching family

openpype/lib/project_backpack.py, openpype/pype_commands.py
Pack project crashes with relevant message when destination directory is not set.
It did crash with cryptic error when the logic tries to create a directory from `None`.
1. Run `pack-project --project {project name} --dbonly`
2. It should crash with more specific information what to do
=> Pack project: Raise exception with reasonable message

openpype/tools/publisher/window.py
Save shortcut should work for both PySide2 and PySide6.
Event key sequence match returns differnet type in PySide2 and PySide6. For PySide2 returns boolean whereas for PySide6 it is enum item (type of match).
Save in publisher using Ctrl + S should work in PySide2 and PySide6.
=> Publisher: Fix save shortcut

openpype/modules/README.md, openpype/modules/base.py, openpype/modules/interfaces.py, openpype/pipeline/context_tools.py
Adds "inventory" as a possible key to the plugin paths to be returned from a module.
Attempts to resolve #5121
It's untested :)
See steps to reproduce in  #5121 - it should now work
=> Allow "inventory" actions to be supplied by a Module/Addon.

openpype/lib/project_backpack.py
Packing of project with files does work again.
Fixed variable value when checking for multiple roots.
1. Run pack project command on single root project
=> Pack Project: Fix files packing

openpype/hosts/maya/plugins/publish/collect_xgen.py, openpype/hosts/maya/plugins/publish/extract_xgen.py, openpype/hosts/maya/plugins/publish/validate_xgen.py
When having multiple descriptions on the same geometry, the extraction would produce redundant duplicate geometries.
1. Setup Maya Xgen scene with multiple descriptions on the same geometry. See below for outliner example.
2. Publish.
3. Load in Xgen into a new scene and validate no duplicate geometries are present.
=> Maya: Xgen multiple descriptions on single shape - OP-6039

openpype/hosts/maya/plugins/publish/extract_workfile_xgen.py, openpype/hosts/maya/plugins/publish/extract_xgen.py
Shading assignments was missing duplicating the setup for Xgen publishing and the exporting of patches was getting the end frame incorrectly.
1. Setup Xgen with material assignments.
3. Publish.
4. Load Xgen and animation and connect geometry.
5. Create render instance.
6. Publish.
=> Maya: Xgen export of Abc's during Render Publishing - OP-6206

openpype/plugins/publish/extract_color_transcode.py
When there is only 1 file, the datamember `files` on the representation should be a string.
1. Setup a profile for Maya in `project_settings/global/publish/ExtractOIIOTranscode/profiles`.
2. Setup a `render` in Maya and publish.
=> OCIO: Support working with single frame renders

openpype/hosts/maya/plugins/load/load_xgen.py
Xgen was not updating correctly when for example adding or removing descriptions. This resolve the issue by overwritting the workspace xgen file.
1. Publish Xgen v1 with 1 description.
2. Load in a new Maya scene and save the workfile.
3. Make any changes on the description.
4. Publish Xgen v2 with 2 descriptions.
5. Update Xgen and validate both descriptions are present plus any changes.
=> Maya: Xgen version mismatch after publish - OP-6204

openpype/hosts/nuke/api/lib.py, openpype/pipeline/colorspace.py
Old project settings overrides are now fully backward compatible. The issue with host config paths overrides were solved and now once a project used to be set to ocio_config **enabled** with found filepaths - this is now considered as activated host ocio_config paths overrides.
Nuke is having an popup dialogue which is letting know to a user that settings for config path were changed. 
We are having issue in hosts using prelaunch hook for OCIO environment hosts and also having Set colorspace in OpenPype menu. In case were production will change ocio config path and users are having opened hosts - they will not know about the change since we are not able to flush environment variable under running instance of host. In Nuke I was able to at least let know to artists with the popup, but we …
=> Colorspace: host config path backward compatibility

openpype/hosts/max/api/plugin.py, openpype/hosts/max/plugins/create/create_render.py, openpype/hosts/max/plugins/publish/validate_camera_contents.py, openpype/hosts/max/plugins/publish/validate_model_contents.py, openpype/hosts/max/plugins/publish/validate_pointcloud.py
Python 3.7 in 3dsmax 2022 is not supporting walrus operator. This is removing it from the code for the sake of compatibility
3dsmax functionality should work the same in 2022 and 2023
=> 3dsmax: make code compatible with 3dsmax 2022

openpype/hosts/blender/api/lib.py, openpype/hosts/blender/api/pipeline.py
This PR adds support for a custom [App Templates](https://docs.blender.org/manual/en/dev/advanced/app_templates.html) path in Blender by setting the `BLENDER_USER_SCRIPTS` environment variable to the path specified in `OPENPYPE_APP_TEMPLATES_PATH`. This allows users to use their own custom app templates in Blender.
1. Set the `OPENPYPE_APP_TEMPLATES_PATH` environment variable to a directory containing custom app templates.
2. Launch Blender and check that the custom app templates are available in the "New" menu.
=> Blender: Add support for custom path for app templates

openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
`subprocess.call` was blocking, which resulted in UI non responsiveness as it was waiting for publish to finish.
=> Webpublisher - headless publish shouldn't be blocking operation

openpype/hosts/maya/plugins/load/actions.py, openpype/pipeline/load/plugins.py
Missing `workfile` family to import.
1. Publish a workfile.
2. Import the workfile through the Loader.
=> Maya: import workfile missing - OP-6233

openpype/hosts/maya/plugins/load/load_arnold_standin.py
The changes are the following. We started by updating the the is_sequence(files) function allowing it to return True for a list of files which has only one file, since our animation in this provides just one alembic file. For the correct FPS number, we got the fps from the published ass/abc from the version data.
Load the animation with abc format with Maya
=> Enhancement:animation family loaded as standing (abc) uses "use file sequence"

openpype/hosts/unreal/hooks/pre_workfile_preparation.py, openpype/hosts/unreal/lib.py, openpype/hosts/unreal/ue_workers.py
There was a bug where Unreal project name was used to query project settings. But Unreal project name can differ from the "real" one because of naming convention rules set by Unreal. This is fixing it by asking for current project settings.
Creatiing new Unreal project via AYON with different name from the main project should work as expected
=> Unreal: get current project settings not using unreal project name

openpype/hosts/maya/api/workfile_template_builder.py, openpype/hosts/nuke/api/workfile_template_builder.py, openpype/tools/workfile_template_build/window.py
Workfile Templates Builder:
1. Create dialog is not a modal dialog
2. Create dialog remains open after create, so you can directly create a new placeholder with similar settings 
3. In Maya allow to create root level placeholders (no selection during create) - **this felt more like a bugfix than anything else.**
Minor tweaks to workfile template creation.
1. Test creating and using of workfile templates (in particular in Maya and Nuke)
=> Workfile Builder UI: Workfile builder window is not modal

openpype/tools/publisher/control.py
Pyblish plugin actions are visible as expected.
Action may not be visible in validation UI if the same action class was reused in multiple publish plugins. Store action ids by plugin ids to make sure they are stored in a different manner and store all action ids per plugin even if would already be in actions mapping.
The source issue came from Maya new publisher refactor where multiple pyblish plugins were using `RepairAction` but only one of them showed up in UI.
1. Have more than one validation plugin that is using `RepairAction`
2. Make both crash with validation error
3. Both should show Repair action in UI
=> Publisher: Fix disappearing actions

openpype/hosts/maya/api/lib.py
Render range was missing the handles.
1. Setup shot with handles.
2. Enable `project_settings/maya/include_handles/include_handles_default`.
3. Set frame range in Maya and validate it includes handles.
=> Maya: Include handles - OP-6236

openpype/lib/profiles_filtering.py
Tweak profiles logging to debug level since they aren't artist facing logs.
Before:
After:
1. Publish from some hosts using the new publisher
2. Artist facing logs should now be much clearer (less clutter)
=> Tweak profiles logging to debug level

openpype/pipeline/workfile/workfile_template_builder.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_templated_workfile_build.json
Now platformity is still handed by usage of `work[root]` (or any other root that is accessible across platforms.) 
Previous change would broke backward compatibility as Settings are re-saving string value to dict and losing existing values.
In the case of customer request it needs to be reworked for proper multiplatformity.
=> General: Revert backward incompatible change of path to template to multiplatform

openpype/settings/defaults/project_settings/aftereffects.json, openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
Adds check if scene contains only latest version of loaded containers.
1. Disable `Validate Containers` in AE section and try to publish
=> AfterEffects - add container check validator to AE settings

openpype/scripts/otio_burnin.py
Burnins are working for inputs with audio.
Filters defined in file are also applied to audio streams if there is no specifier in `-filter_script`.
1. Try to make review from video with audio
2. Burnins should be added without crash
=> Burnins: Filter script is defined only for video streams

openpype/hosts/max/api/lib.py
Resolve #5181 
also resolve the timeline issue at #5001 
1. Launch Max via OP
2. Openpype... -> Set Frame Range
3. Should be setting up the right timeline regarding to the DB
=> Fix the reset frame range not setting up the right timeline in Max

openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py, openpype/modules/ftrack/plugins/publish/integrate_ftrack_status.py, openpype/plugins/publish/cleanup.py
Got this from one of our artists' reports - figured some of these logs were definitely not for the artist, reduced those logs to debug level.
1. Read the changes
2. Test publish in new publisher hosts
=> Enhancement: Reduce more visual clutter for artists in new publisher reports

openpype/pipeline/publish/publish_plugins.py
- Add icon to RepairContextAction
- logs to debug level
- also add attempt repair for RepairAction for consistency
- fix RepairContextAction docstring to mention correct argument name
We should not forget to remove this ["deprecated" actions.py file](https://github.com/ynput/OpenPype/blob/3501d0d23a78fbaef106da2fffe946cb49bef855/openpype/action.py) in 3.16 (next-minor)
1. Run some fabulous repairs!
=> Cosmetics: Tweak pyblish repair actions (icon, logs, docstring)

openpype/hosts/maya/api/pipeline.py
fixing the bug of register_event_callback not being able to collect action of "workfile_save_after" for lock file action
n/a
1. launch maya via OP
2. enable lockfile profile for maya
3. open a file(called workfile A) via Maya
4. save a new file(called workfile B)
5. launch maya via OP
6. open workfile A
7. Should show the lock widget
=> Maya: fix the register_event_callback correctly collecting workfile save after

openpype/hosts/houdini/plugins/create/create_redshift_rop.py
Problem : 
"RS_outputFileFormat" parm value was missing 
and there were more "image_format" than redshift rop supports 
Fix: 
1)  removed unnecessary formats from `image_format_enum`
2) add the selected format value to `RS_outputFileFormat`
=> Houdini: Redshift ROP image format bug

openpype/pipeline/colorspace.py
Fix python version comparison.
Resolves #5211
**Note** that this is just fixing what the code seemed to intend to do - whether the colorspace logic actually works in e.g. 3.10+ or hosts like Maya, Nuke, Fusion, Houdini, etc. with more recent Python versions I'm not sure as I'm not sure whether those actually all have access to the `PyOpenColorIO` package. As such this might need testing across all hosts also whether `import PyOpenColorIO` actually works.
Run:
```python
import sys
from openpype.pipeline import colorspace 
print(sys.version)
print(sys.version_info)
print(colorspace.compatible_python())
```
Any python 3.9+ should return True on the last print.
**NOTE** We might also want to test across different DCCs whether the check is actually accurate, e.g.:
```python
try:
import …
```
=> Colorspace lib fix compatible python version comparison

openpype/pipeline/colorspace.py
Fixing previously merged PR (https://github.com/ynput/OpenPype/pull/5212) And applying better way to check compatibility with PyOpenColorIO python api.
- implementing suggestion from https://github.com/ynput/OpenPype/pull/5212#issuecomment-1614651292
1. Colorspace features should now work again in any host
=> Colorspace: check PyOpenColorIO rather then python version

openpype/hosts/maya/api/pipeline.py, openpype/scripts/otio_burnin.py
This PR manages the Xgen files when switching context in the Workfiles app.
1. Setup Xgen in Maya.
2. Switch context and validate xgen files are copied to new location.
3. Repeat steps 1-2 and validate overwrite dialog appears.
4. Load in Xgen in Maya.
5. Switch context and validate xgen still works after relaunch of Maya.
=> Bug: Maya - xgen sidecar files arent moved when saving workfile as an new asset workfile changing context - OP-6222

openpype/pipeline/load/__init__.py, openpype/pipeline/load/utils.py, openpype/tools/sceneinventory/switch_dialog.py
Tweak raised errors and error messages for loader errors.
Intends to solve #4870 
1. Try and hit the loader error cases, make sure the error message is clear.
- perform switch asset on a loader that does not have `switch` implemented
- change the 'loader' name on a maya container (e.g. change the attribute value to 'foobar') to something non-existent, loader messages should be clear when trying to interact with it.
=> Enhancement: More descriptive error messages for Loaders

openpype/hosts/maya/api/workfile_template_builder.py
I add an assertion management in case the container does not have a represention in outliner.
If a template contains a placeholder without outliner representation it will produce this warning:
```bash
```
1. Add a placeholder without ouliner representation in your template (like maya render settings)
2. Build workfile from template
3. See this error in the script editor
=> Bug: Template builder fails when loading data without outliner representation

openpype/hosts/houdini/plugins/publish/validate_abc_primitive_to_detail.py, openpype/hosts/houdini/plugins/publish/validate_primitive_hierarchy_paths.py
When `sop_path`  on ABC ROP node points to a  non `SopNode`, these validators `validate_abc_primitive_to_detail.py`, `validate_primitive_hierarchy_paths.py` will error and crash when this line is executed 
`geo = output_node.geometryAtFrame(frame)`
=>  Houdini: Add geometry check for pointcache family

openpype/hosts/houdini/plugins/publish/validate_vdb_output_node.py
When `sop_path` on Geometry ROP node points to a non SopNode, this validator `validate_vdb_output_node.py` will error and crash when this line is executed
`sop_node.geometryAtFrame(frame)`
The bug addressed here is the same as in this [PR](https://github.com/ynput/OpenPype/pull/5230)
=> Houdini: Add geometry check for VDB family

openpype/settings/defaults/project_settings/maya.json
Maya colorspace setttings defaults are set the way they align our distributed ACES 1.2 config file set in global colorspace configs.
Workfile category is disabled by default since we don't want to damage any productions which were having configured their settings already.
The issue was mentioned here https://github.com/ynput/OpenPype/pull/5225
=> Maya: aligning default settings to distributed aces 1.2 config

openpype/hosts/substancepainter/plugins/create/create_textures.py, openpype/hosts/substancepainter/plugins/publish/collect_textureset_images.py
Instead of having two settings in both create and publish tab, there is solely one setting in the publish tab for users to set up the parameters.
Resolve #5172
n/a
1. Launch SP via OP
2. Open project file
3. Create Texture Set
4. Go to Publish Tab -> Click TextureSetMain
5. It would show all the settings
=> Substance Painter: Include the setting only in publish tab

openpype/hosts/max/api/plugin.py
No duplicates for node references in Max when users trying to select nodes before publishing 
n/a
1. Launch Max via Openpype
2. Create Instance
3. Click "Add to Container" in OP Parameter in the created container
4. Add Items
5. And add the same items as 4
6.  The node references won't show the duplicated items anymore.
=> node references to check for duplicates in Max

poetry.lock, pyproject.toml, tools/fetch_thirdparty_libs.py
Defined runtime dependencies in pyproject toml. Moved python ocio and otio modules there.
This change makes sure that both modules won't be in PYTHONPATH thus not propagated to launched DCCs, which should fix possible issues e.g. in NukeStudio/Hiero.
1. Delete `./.venv` if you have any in repository
2. Run `./tools/create_env`
3. Run `./tools/fetch_thirdparty_libs`
Resolves https://github.com/ynput/OpenPype/issues/5138
=> General: Runtime dependencies

openpype/modules/deadline/plugins/publish/submit_publish_job.py
When running from source the environment variable `OPENPYPE_VERSION` should not be added. This is a bugfix for the feature #4489
1. Run OP from source.
2. Setup render in Maya.
3. Submit to Deadline and verify there is no `OPENPYPE_VERSION` environment variable on the publish job.
=> Deadline: OPENPYPE_VERSION should only be added when running from build

openpype/hosts/houdini/api/lib.py
Fix the issue described [here](https://github.com/ynput/OpenPype/pull/4825#discussion_r1217793100) where the logic for retrieving the current OCIO display and view was incorrectly trying to apply a regex to it.
1. Publish renders from Houdini with different OCIO configs - preferably with colorspace prefs set to something without a `-` in the colorspace name.
=> Houdini: Fix `get_color_management_preferences`

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/pipeline.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/api/render_setup_tools.py, openpype/hosts/maya/plugins/publish/extract_obj.py, openpype/hosts/maya/tools/mayalookassigner/app.py, openpype/pipeline/create/legacy_create.py
Some small cleanup and refactoring of logic. Removing old comments, unused imports and some minor optimization. Also removed the prints of the loader names of each container the scene in `fix_incompatible_containers` + optimizing by using `set` and defining only once. Moved some UI related code/tweaks to run `on_init` only if not in headless mode. Removed an empty `obj.py` file.
Each commit message kind of describes why the change was made.
Even though these are mostly cosmetic changes they might introduce subtle bugs (of course). So do a quick test run please.
1. Maya Look assigner should still open
2. Maya Creator UI should still work
3. Render Setup observers should still work, create a render instance - ensure it correctly catches adding new renderlayers or removing old ones and test …
=> Maya: Minor refactoring and code cleanup

openpype/pipeline/create/__init__.py, openpype/pipeline/create/context.py, openpype/pipeline/create/creator_plugins.py, openpype/pipeline/create/utils.py
Implemented helper functions to get next available versions for create instances.
The helper functions are doing what they can do with available data on instances to find next possible available version for an instance. I would be scared to use the value for publishing as publishing may have different requirements in different cases so it should be always optional. This is a quick PR to unblock [custom staging directory PR](https://github.com/ynput/OpenPype/pull/5207).
Other possible usages need more brainstorm. About how to use it, before using it everywhere. e.g. to show the version in UI (and possibly change it?) would mean that the value must be in instance data.
Since the code is not used, it must be faked.
1. Add a creator that would call `self.get_next_versions_for_instances` on …
=> CreatePlugin: Get next version helper

openpype/plugins/load/delivery.py
- disable delivery button if no representations checked
- fix macos combobox layout
- add error message if no delivery templates found
Addressed #5162
1. Open Loader
2. Select sequence and right+click launch Deliver Versions
3. Leave it as it is. Deliver button will not be activated
4. Delete all delivery templates in `project_anatomy` and open delivery dialogue. Error message will be shown in the `text_area` with corresponding error log message.
=> Validate delivery action representations status

openpype/hosts/houdini/api/pipeline.py, openpype/hosts/houdini/plugins/publish/save_scene.py
Fix no prompt for "unsaved changes" showing when opening workfile in Houdini.
@iLLiCiTiT It seems there has been some refactoring of `host.has_unsaved_changes` to `host.workfile_has_unsaved_changes` but the **refactoring actually wasn't done in a backwards compatible way**. It seems the new default does this:
```python
def workfile_has_unsaved_changes(self):
"""Currently opened scene is saved.
Not all hosts can know if current scene is saved because the API of
DCC does not support it.
Returns:
bool: True if scene is saved and False if has unsaved
modifications.
None: Can't tell if workfiles has modifications.
"""
return None
def has_unsaved_changes(self):
"""Deprecated variant of 'workfile_has_unsaved_changes'.
Todo:
Remove when all usages are replaced.
"""
return …
```
=> Fix no prompt for "unsaved changes" showing when opening workfile in Houdini

openpype/hosts/substancepainter/api/pipeline.py, openpype/hosts/substancepainter/plugins/publish/save_workfile.py
Fix no prompt for "unsaved changes" showing when opening workfile in Substance Painter.
Equivalent of fix https://github.com/ynput/OpenPype/pull/5246 but for Substance Painter
1. Make some changes in your scene in Houdini
2. Open another file with work files tool - a "save prompt" should be shown.
=> Fix no prompt for "unsaved changes" showing when opening workfile in Substance Painter

openpype/action.py, openpype/hosts/blender/api/action.py, openpype/hosts/fusion/api/action.py, openpype/hosts/houdini/api/action.py, openpype/hosts/maya/api/action.py, openpype/hosts/nuke/api/actions.py, openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py, openpype/hosts/resolve/api/action.py, openpype/pipeline/publish/lib.py, openpype/pipeline/publish/publish_plugins.py
RepairAction and SelectInvalidAction actually filter to instances that failed on the exact plugin - not on "any failure"
This [comment](https://github.com/ynput/OpenPype/pull/5231#discussion_r1251954530) showcased that actually the repair and select actions were running on ANY plugin that errored, not necessarily the ones that errored on the plugin we're running the action on.
I haven't tried this code - so please test. But it showcases what I think could be a solution.
I've removed the `pyblish.api.instances_by_plugin(errored_instances, plugin)` filtering because whenever an error occurred for the instance for this particular plug-in then of course the instance was related to that plugin - at least that's what I assumed.
Likely this hasn't been spotted much earlier because MOST …
=> RepairAction and SelectInvalidAction filter instances failed on the exact plugin

common/ayon_common/distribution/data_structures.py
Package returned from server has `filename` instead of `name`.
=> Ayon: server returns different key

openpype/hosts/houdini/api/action.py, openpype/hosts/houdini/plugins/publish/validate_sop_output_node.py
This PR adds `SelectROPAction` action to `houdini\api\action.py`
and it's used in `Validate Output Node` 
`SelectROPAction` is used to select the associated ROPs with the errored instances.
Testing this PR requires merging these [PR](https://github.com/ynput/OpenPype/pull/5230) and [PR](https://github.com/ynput/OpenPype/pull/5232)
Alternatively, you can add these lines before `geo = output_node.geometryAtFrame(frame)`
```
if not hasattr(output_node, "geometry"):
cls.log.warning("No geometry output node found, skipping check..")
return
```
=> Houdini: add select invalid action for ValidateSopOutputNode

openpype/hosts/max/api/lib.py, openpype/hosts/max/api/plugin.py
Resolve #5183, general maxscript conversion issue to python (e.g. bool conversion, true in maxscript while True in Python)
(Also resolve the ValueError when you change the subset to publish into list view menu)
n/a
1. Launch Max via OP
2. Openpype -> Publish...
3. Create Instance
4. Disable it
5. Close and re-open the publisher
6. It should show the instance disabled instead of enabled
=> Max: Publisher instances dont hold its enabled disabled states when Publisher reopened again

openpype/hosts/maya/api/lib_renderproducts.py
When no prefix is specified in render settings, the renderlayer collector would error.
1. Setup `render` in Maya.
2. Ensure no prefix is specified in render settings.
3. Publish and verify no errors occur at the collection stage.
=> Maya: Fix collecting arnold prefix when none

openpype/pipeline/delivery.py
If the delivery template has a new line symbol at the end, say it was copied from the text editor, the delivery process will fail with `OSError` due to incorrect destination path. To avoid that I added `rstrip()` to the `delivery_path` processing.
1. Create a delivery template with a newline at the end (copy the template string from the text editor including the newline)
2. Delivery now will not fail.
=> Remove new lines from the delivery template string

openpype/tools/sceneinventory/view.py
When selecting many items in the scene inventory to update versions and one of the items would error out the updating stops. However, before this PR the scene inventory would also NOT refresh making you think it did nothing.
Also implemented as method to allow some code deduplication.
We might want to change the `AssertionError` to show a popup to something more generic too to show ANY error as a dialog popup - but to remain consistent with old behavior I haven't done that. However, doing that might at least make it clearer to end user that something actually failed.
Starts updating and switching versions:
2. Update versioned containers randomly
3. Update versioned containers to explicit version (using Set version dialog)
4. Update containers to latest using top right update button
5. …
=> Update scene inventory even if any errors occurred during update

openpype/hosts/houdini/plugins/create/create_pointcache.py
Houdini  allows `ObjNode` path as `sop_path` in the `ROP` unlike OP/ Ayon require `sop_path` to be set to a sop node path explicitly 
In this code, better selection is used to filter out invalid selections from OP/ Ayon  point of view
Valid selections are 
- `SopNode` that has parent of type `geo` or `subnet`
- `ObjNode` of type `geo` that has 
-  `SopNode` of type `output` 
- `SopNode` with render flag `on` (if no `Sopnode` of type `output`)
this effectively  filter 
- empty `ObjNode` 
- `ObjNode`(s) of other types like `cam` and `dopnet` 
-  `SopNode`(s) that thier parents of other types like `cam` and `sop solver` 
This PR is one of several PRs made for this [issue](https://github.com/ynput/OpenPype/issues/3431)
Create `pointcache` instance while selecting:
Case    ->    Result 
1. …
=> Houdini: better selection on pointcache creation 

openpype/hosts/unreal/addon.py
Importing `Window` creates errors in headless mode.
```
*** WRN: >>> { ModulesLoader }: [  FAILED to import host folder unreal  ]
=============================
No Qt bindings could be found
=============================
File "C:\Users\tokejepsen\OpenPype\.venv\lib\site-packages\qtpy\__init__.py", line 252, in <module>
from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundERROR: No module named 'PySide6'
During handling of the above exception, another exception occurred:
File "C:\Users\tokejepsen\OpenPype\openpype\modules\base.py", line 385, in _load_modules
default_module = __import__(
File "C:\Users\tokejepsen\OpenPype\openpype\hosts\unreal\__init__.py", line 1, in <module>
from .addon …
```
=> Unreal: Move Qt imports away from module init

openpype/hosts/maya/plugins/load/load_look.py
Fixes a bug where updating attributes on nodes with assigned shader if shape name existed more than once in the scene due to `cmds.listRelatives` call not being done with the `fullPath=True` flag.
Original error:
```python
```
Also optimized the query a bit by doing a single `listRelatives` query.
1. Update looks in Maya
=> Maya: Bugfix look update nodes by id with non-unique shape names (query with `fullPath`)

openpype/settings/defaults/project_settings/substancepainter.json
The default settings for color management for Substance Painter were invalid, it was set to override the global config by default but specified no valid config paths of its own - and thus errored that the paths were not correct.
This sets the defaults correctly to match other hosts.
_I quickly checked - this seems to be the only host with the wrong default settings_
Resolves #5241
1. Enable global color management in settings `project_settings/global/imageio/activate_global_color_management`
2. Launch Substance Painter
For sake of testing it would also be good to confirm the OCIO config works in Substance Painter and that publishing also works as expected with it.
=> Substance Painter: Fix default color management settings

openpype/hosts/nuke/plugins/load/load_clip.py
Windows path in container data are reformatted. Previously it was reported that Nuke was rising `utf8 0xc0` error if backward slashes were in data values.
1. Load any image or video version into Nuke and all should work as before.
=> Nuke: fixing container data if windows path in value

openpype/pype_commands.py
Unit testing logging was crashing on more then one nested layers of inherited loggers.
- Also muting Deprecated warnings. 
- adding printing during testing rather then waiting for the test results
1. run any of your favourite tests in terminal to see the difference
=> Testing: improving logging during testing

openpype/hosts/substancepainter/plugins/publish/collect_textureset_images.py
Fix `copy.deepcopy` of `instance.data`.
Resolves https://github.com/ynput/OpenPype/issues/5171 and issue reported on forum https://community.ynput.io/t/substance-painter-error-in-op-3-15-11/443/2
1. Start Substance Painter
2. Publish a texture set
=> Substance Painter: Fix Collect Texture Set Images unable to copy.deepcopy due to QMenu

openpype/hosts/nuke/api/plugin.py
Removing deprecated settings for baking with reformat. This option was only for single reformat node and it had been substituted with multiple reposition nodes.
https://github.com/ynput/ayon-addons-settings/pull/18
=> Nuke: removing deprecated settings in baking

openpype/hosts/houdini/plugins/publish/collect_arnold_rop.py
Fixing a typo error in `collect_arnold_rop.py`
Reference: [#5280](https://github.com/ynput/OpenPype/issues/5280)
=> Houdini: fix typo error in collect arnold rop

openpype/tests/lib.py
This import resulted in adding additional logging handler which lead to duplication of logs in hosts with plugins containing `is_in_tests` method. Import is unnecessary for testing functionality.
=> Maya: Removed unnecessary import of pyblish.cli

common/ayon_common/utils.py, openpype/lib/local_settings.py, openpype/modules/base.py, openpype/vendor/python/common/ayon_api/thumbnails.py
Appdirs for AYON are case sensitive for linux and mac so we needed to change them to match ayon launcher. Changed 'ayon' to 'AYON' and 'ynput' to 'Ynput'.
Since windows is not case sensitive I didn't think about as an issue but it is an issue...
=> AYON: Make appdirs case sensitive

openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py, openpype/modules/deadline/plugins/publish/submit_max_deadline.py
Removing deprecated method of adding OPENPYPE_VERSION to job environment. It was leftover and other hosts have already been cleared.
1. all should work as before
=> Deadline: removing OPENPYPE_VERSION from some host submitters

openpype/hosts/nuke/api/workfile_template_builder.py
Adding auto run of Apply All Settings after template is builder is finishing its process. This will apply Frame-range, Image size, Colorspace found in context of a task shot.
1. Run Template build and see that your workfile will be set to correct
=> Nuke: auto apply all settings after template build

igniter/bootstrap_repos.py
Support long paths for version extract on Windows.
Use case is when having long paths in for example an addon. You can install to the C drive but because the zip files are extracted in the local users folder, it'll add additional sub directories to the paths and quickly get too long paths for Windows to handle the zip updates.
1. Setup a long path in for example `addons` folder with multiple subfolders.
2. Create zip and try to update with the zip.
=> Windows: Support long paths on zip updates.

Dockerfile.centos7
Move to python 3.9 has added need to use openssl 1.1.x - but it is not by default available on centos 7 image. This is fixing it.
`./tools/docker_build.sh centos7` should work now.
=> Docker: handle openssl 1.1.1 for centos 7 docker build

openpype/hosts/houdini/plugins/publish/collect_pointcache_type.py
FIxing a bug in publishing alembics, were invalid creator identifier caused missing family association.
Publishing of BGEO and pointCache (alembics) should work as expected
1. Open Houdini
2. create some testing geo
3. create PointCache instance
4. publishing should work with all almebics related validations, etc.
5. create BGEO instance
6. publishing should still work as expected.
=> Houdini: fix wrong creator identifier in pointCache workflow

openpype/hosts/fusion/api/action.py
When you run the action to select a node, this PR makes the node-flow show the selected node + you'll see the nodes controls in the inspector.
1. With a Fusion project open, open OP and open Manage
2. Move the node flow away from any nodes
3. Right click a loader in the Manage window
4. Go to Actions -> Select Containers
5. The node flow should shift to show the selected node and you should see the controls in the inspector.
=> Fusion - Set selected tool to active

openpype/hosts/maya/api/plugin.py, openpype/pipeline/__init__.py, openpype/pipeline/create/context.py
Prepared base classes for each creator type in Maya. Extended `MayaCreatorBase` to have default implementations of common logic with instances which is used in each type of plugin.
This way the default instance logic is at single place and does not need to be implemented multiple times.
Idea for this PR came from this PR https://github.com/ynput/OpenPype/pull/5297
=> Maya: All base create plugins

openpype/hosts/blender/plugins/publish/collect_review.py, openpype/plugins/publish/extract_burnin.py
This PR adds support for ExtractBurnin for Blender, when publishing a Review.
1. In Project Settings, `project_settings/global/publish/ExtractBurnin/profiles`, be sure to have a profile for the `review` family and add Blender to the host names.
2. In Blender, create a Review. (You need to select a camera when creating it).
3. Publish the Review.
4. Check if the published review has the burnins.
=> Blender: Support for ExtractBurnin

openpype/hosts/blender/api/ops.py, openpype/hosts/blender/api/pipeline.py, openpype/settings/defaults/project_settings/blender.json, openpype/settings/entities/schemas/projects_schema/schema_project_blender.json
This PR adds `set_resolution_startup `and `set_frames_startup` settings. They automatically set respectively the resolution and start/end frames and FPS in Blender when opening a file or creating a new one.
1. Change default settings in the Project Manager for resolution, start/end frames and FPS.
2. Disable the new settings and check when opening Blender if those settings have changed. You can check from the *Property panel*, in the *Output properties* tab.
3. Now enable the settings and try opening Blender again, and check if those settings have changed.
=> Blender: Added setting to set resolution and start/end frames at startup

openpype/hosts/blender/plugins/publish/extract_abc.py, openpype/hosts/blender/plugins/publish/extract_camera_abc.py, openpype/hosts/blender/plugins/publish/extract_camera_fbx.py, openpype/settings/defaults/project_settings/blender.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_blender_publish.json
Added support to extract Alembic Cameras in Blender.
1. Check that `project_settings/blender/publish/ExtractCameraABC` is enabled.
2. Try publishing a camera from Blender (be sure that the *Extract Camera (ABC)* extractor is enabled).
3. Try loading the published camera.
=> Blender: Extract Camera as Alembic

openpype/pipeline/colorspace.py
for some reason a user may have `PyOpenColorIO` installed to his machine,  _in my case it came with renderman._
it can trick the compatibility check as `import PyOpenColorIO` won't raise an error 
however it may be an old version _like my case_ 
Before
compatibility check was true and It used wrapper directly 
After Fix 
It will use wrapper via subprocess instead
=> Fix colorspace compatibility check

openpype/modules/ftrack/event_handlers_server/action_sync_to_avalon.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Added roles settings for sync to avalon action.
The action didn't have settings for roles and nobody noticed for a long time. Also the settings were there but used. The only key it had was `statuses_name_change` which is not used anywhere.
1. Open openpype settings
2. change Sync to Avalon (in Server actions) roles to one of roles you don't have
3. Start ftrack event server
4. Open ftrack in browser
5. Discover actions on a ftrack project
6. You should not see sync to avalon action
7. Change the settings to contain role you have
8. Wait 10 seconds (settings cache time)
9. Again discover actions on ftrack project
10. Now you should see the action
=> Ftrack: Sync to avalon settings

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/create/create_arnold_scene_source.py
Project settings were not applied to the creators.
1. Make a change from the default settings on any of the Maya creators; `project_settings/maya/create`
2. In Maya create the modified creator.
3. Verify the settings from the project settings are applied.
=> Maya: Apply project settings to creators

openpype/hosts/houdini/plugins/create/create_arnold_rop.py, openpype/hosts/houdini/plugins/create/create_karma_rop.py, openpype/hosts/houdini/plugins/create/create_mantra_rop.py, openpype/hosts/houdini/plugins/create/create_redshift_rop.py, openpype/hosts/houdini/plugins/create/create_vray_rop.py
Deadline Farm publishing and Rendering for Houdini was possible with this PR #4825 
farm publishing is enabled by default some ROP nodes which may surprise new users (like me).
I think adding a toggle (on by default) on creation UI is better so that users will be aware that there's a farm option for this publish instance.
ROPs Modified : 
I'm using the same toggle here #4903
=> Houdini: Add farm toggle on creation menu

openpype/hosts/maya/plugins/create/create_rig.py, openpype/hosts/maya/plugins/publish/validate_rig_output_ids.py
In case of multiple subset rig in the maya scene, there is an error on the plugin `rig output ids`
I change endswith method by startswith method because the set are automacaly name out_SET, out_SET1, out_SET2 ...
1. Open maya
2. Add multiple rig instance with different subset
3. Publish and see the error
=> Bug: Error on multiple instance rig with maya

openpype/pipeline/schema/__init__.py, openpype/pipeline/schema/application-1.0.json, openpype/pipeline/schema/asset-1.0.json, openpype/pipeline/schema/asset-2.0.json, openpype/pipeline/schema/asset-3.0.json, openpype/pipeline/schema/config-1.0.json, openpype/pipeline/schema/config-1.1.json, openpype/pipeline/schema/config-2.0.json, openpype/pipeline/schema/container-1.0.json, openpype/pipeline/schema/container-2.0.json, openpype/pipeline/schema/hero_version-1.0.json, openpype/pipeline/schema/inventory-1.0.json, openpype/pipeline/schema/inventory-1.1.json, openpype/pipeline/schema/project-2.0.json, openpype/pipeline/schema/project-2.1.json, openpype/pipeline/schema/project-3.0.json, openpype/pipeline/schema/representation-1.0.json, openpype/pipeline/schema/representation-2.0.json, openpype/pipeline/schema/session-1.0.json, openpype/pipeline/schema/session-2.0.json, openpype/pipeline/schema/session-3.0.json, openpype/pipeline/schema/shaders-1.0.json, openpype/pipeline/schema/subset-1.0.json, openpype/pipeline/schema/subset-2.0.json, openpype/pipeline/schema/subset-3.0.json, openpype/pipeline/schema/thumbnail-1.0.json, openpype/pipeline/schema/version-1.0.json, openpype/pipeline/schema/version-2.0.json, openpype/pipeline/schema/version-3.0.json, openpype/pipeline/schema/workfile-1.0.json
Moved/copied schemas from repository root inside openpype/pipeline.
The movement is necessary because of AYON addon conversion. Since ayon-launcher does not contain the schemas and openpype neither there is not way how it can be accessed. The easiest solution is to move schemas inside openpype codebase.
Most of the schemas are very outdated and should be probably removed, but that is not purpose of this PR.
I've kept the schema directory in the root of repository and will create different [PR in next-minor branch](https://github.com/ynput/OpenPype/pull/5355) that will remove them.
There should not be any issues with schema validation.
When does schema validation happen? e.g. on host install (open of DCC) or integration.
When used openpype as an addon via ayon-launcher should not cause any …
=> Chore: Schemas inside OpenPype

openpype/hosts/unreal/addon.py
Automatically set `UE_PYTHONPATH` as `PYTHONPATH` when launching Unreal.
UE 5 has a default settings that isolate the Python interpreter environment, so the standard environment variables (such as `PYTHONPATH`) are ignored. Instead, UE5 uses `UE_PYTHONPATH`. This PR automatically sets `UE_PYTHONPATH` as `PYTHONPATH` when launching Unreal, so it isn't necessary anymore to set it explicitly in the settings.
1. Remove `UE_PYTHONPATH` from `applications/unreal/environment` (or any environment for a specific version of Unreal), if you have it.
2. Run Unreal, and check if Ayon works (you should be able to open the menu and open any window, such as Loader or Publisher).
=> Unreal: Python Environment Improvements

openpype/hosts/maya/plugins/publish/collect_review.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Fixes situation where frame range validator can't be turned off on models if they are attached to reviewable camera in Maya. 
1. Create model publish instance in maya
2. create review publish instance in maya 
3. parent model maya set under the review maya set based on this **https://ayon.ynput.io/docs/artist_hosts_maya#publishing-model-with-review**
4. turn off `validate frame range` on the review in the publisher GUI. 
5. Everything should go through correctly and you should end up with review attached to the model Product.
=> Maya: fix validate frame range on review attached to other instances

openpype/hosts/maya/plugins/publish/validate_model_content.py
`assemblies` in `cmds.ls` does not seem to work;
```python
from maya import cmds
content_instance = ['|group2|pSphere1_GEO', '|group2|pSphere1_GEO|pSphere1_GEOShape', '|group1|pSphere1_GEO', '|group1|pSphere1_GEO|pSphere1_GEOShape']
assemblies = cmds.ls(content_instance, assemblies=True, long=True)
print(assemblies)
```
Fixing with string splitting instead.
1. Setup model instance with geometry from two different top level parents.
2. Publish and verify validation fails.
=> Maya: Validate Model Content

openpype/hosts/unreal/hooks/pre_workfile_preparation.py, openpype/hosts/unreal/ui/__init__.py, openpype/hosts/unreal/ui/splash_screen.py
Moved splash screen code to unreal integration and removed import from Igniter.
The `NiceProgress` is not nice if igniters stylesheest are not used. The changes in progress bar don't add any visual value.
=> Unreal: Move unreal splash screen to unreal

openpype/pipeline/farm/pyblish_functions.py, tests/integration/hosts/nuke/test_deadline_publish_in_nuke_prerender.py
`prerender` family was using wrong subset, same as `render` which should be different.
Added new test class added which covers default settings for `prererender`:
- default subset name template (without task)
- no reviews
1. create `prerender` instance in Nuke
2. publish via Deadline
3. it should create `prerender` folder in `publish` (without it it would create `render` folder, eg. subset/product)
=> Nuke: farm rendering of prerender ignore roots in nuke

openpype/cli.py, openpype/lib/__init__.py, openpype/lib/applications.py, openpype/lib/execute.py, openpype/lib/openpype_version.py, server_addon/create_ayon_addons.py
Prepare code for ayon-launcher compatibility. Fix ayon launcher subprocess calls, added more checks for `AYON_SERVER_ENABLED`, use ayon launcher suitable environment variables in AYON mode and changed outputs of some functions. Replaced usages of `OPENPYPE_REPOS_ROOT` environment variable with `PACKAGE_DIR` variable -> correct paths are used.
AYON mode with ayon-launcher is not fully compatible now at some points. It tries to launch `ayon_start.py` when running from code instead of `start.py` which is there from time when OpenPype had ayon executables.
**Publishing**
1. Make sure a script with subprocess is executed (for example burnins extraction)
2. Run publishing in host of your choice
3. Publishing should not crash
**Info in tray**
1. Open info window in tray.
2. Check the information …
=> AYON: Environment variables and functions

openpype/hosts/houdini/api/plugin.py
When creating many product types (families) one after another without refreshing the creator window manually 
if you toggled `Use selection` once, all the later product types will use selection even if it was toggled off
Here's Before 
it will keep use selection even if it was toggled off, unless you refresh window manually 
https://github.com/ynput/OpenPype/assets/20871534/8b890122-5b53-4c6b-897d-6a2f3aa3388a
Here's After 
it works as expected
https://github.com/ynput/OpenPype/assets/20871534/6b1db990-de1b-428e-8828-04ab59a44e28
create publishes one after another with different `Use selection` on and off
=> Bugfix: Houdini Creator use selection even if it was toggled off

openpype/hosts/maya/api/plugin.py, openpype/vendor/python/python_2/click/__init__.py, openpype/vendor/python/python_2/click/_bashcomplete.py, openpype/vendor/python/python_2/click/_compat.py, openpype/vendor/python/python_2/click/_termui_impl.py, openpype/vendor/python/python_2/click/_textwrap.py, openpype/vendor/python/python_2/click/_unicodefun.py, openpype/vendor/python/python_2/click/_winconsole.py, openpype/vendor/python/python_2/click/core.py, openpype/vendor/python/python_2/click/decorators.py, openpype/vendor/python/python_2/click/exceptions.py, openpype/vendor/python/python_2/click/formatting.py, openpype/vendor/python/python_2/click/globals.py, openpype/vendor/python/python_2/click/parser.py, openpype/vendor/python/python_2/click/termui.py, openpype/vendor/python/python_2/click/testing.py, openpype/vendor/python/python_2/click/types.py, openpype/vendor/python/python_2/click/utils.py
Fix Python 2 support by adding `click` into python 2 dependencies and removing f-string from maya.
This PR is fixing Python 2 but does not fix support for Python 3.6 and lower versions which might be another problem.
The `click` issue started with this PR https://github.com/ynput/OpenPype/pull/5065 which is a valid PR.
1. Launch older Maya, Nuke, Houdini, etc. that have Python 2
2. Everything should work as expected
=> Chore: Python 2 support fix

openpype/hosts/nuke/plugins/publish/collect_writes.py, openpype/pipeline/farm/pyblish_functions.py, openpype/pipeline/publish/lib.py
Previous PR enabled explicit cleanup of `renders` folder after farm publishing. This is not matching customer's workflows. Customer wants to have access to files in `renders` folder and potentially redo some frames for long frame sequences.
This PR extends logic of marking rendered files for deletion only if instance doesn't have `stagingDir_persistent`.
For backwards compatibility all Nuke instances have `stagingDir_persistent` set to True, eg. `renders` folder won't be cleaned after farm publish.
Whenever Custom staging directories are fully implemented in Nuke, this hardcoded value could be removed and behavior should be more controllable by profiles in `project_settings/global/tools/publish/custom_staging_dir_profiles`. No additional Settings were added/modified as Custom Staging …
=> Nuke: returned not cleaning of renders folder on the farm

openpype/hosts/unreal/ue_workers.py
Implemented a new `UEWorker` base class to handle exception during the execution of UE Workers.
The existing workers `UEProjectGenerationWorker` and `UEPluginInstallWorker` now inherit from `UEWorker` and have been modified to override the `execute` method instead of the `run` method. The `run` method calls `execute`, and it should catch any exception during the Worker execution.
1. Change the UE plugin code to fail the build.
2. Try running Unreal from the launcher. It should fail and the traceback should be printed in the log window.
=> Unreal: Better handling of Exceptions in UE Worker threads

openpype/hosts/nuke/plugins/load/load_clip.py
Loading image sequences was broken after the latest release, version 3.16. However, I am pleased to inform you that it is now functioning as expected.
1. open Nuke in your testing project
2. load any image sequence product version
3. read node should be working well with #### for sequence
=> Nuke: loading sequences is working

openpype/hosts/houdini/plugins/create/create_bgeo.py, openpype/hosts/houdini/plugins/create/create_pointcache.py
To me it's logical to find pointcaches types listed one after another, but they were named differently 
So, I made this PR to update their labels 
1. open OP creator window 
2. check families names
=> Enhancement: Houdini Update pointcache labels

openpype/client/mongo/entity_links.py
Remove condition that avoids downloading dependency without `inputLinks`. 
This PR is to open discussion about this condition I don't know the original purpose of and about which I'd be glad to have @kalisp 's opinion.
As far as I understand the issue, audio published versions don't have `inputLinks`, which makes the fetch process avoid them from being downloaded when they are not hero versions. In fact I cannot figure why this is like that, and if my proposal is wrong, I'd be glad to learn a bit about it.
1. Open Blender
2. Load an audio into a workfile
3. Publish
4. Remove the local workfile (not the published one)
5. Using the Sync Queue, remove from local the audio
6. Launch the same task to process the `copy last published workfile` process
7. The audio isn't fetched
=> Bugfix: Dependency without 'inputLinks' not downloaded

openpype/hosts/nuke/api/pipeline.py, openpype/hosts/nuke/api/plugin.py
Nuke now allows users to duplicate publishing instances, making the workflow easier. By duplicating a node and changing its name, users can set the product (subset) name in the publishing context.
Users now have the ability to change the variant name in Publisher, which will automatically rename the associated instance node.
We are temporarily implementing order sorting, but once [this issue #5391]( https://github.com/ynput/OpenPype/issues/5391) is addressed, we will remove it.
1. Open the testing nuke script.
2. Create a write render product node.
3. Duplicate the node multiple times.
4. Refresh the Publisher and observe that those nodes are included in the instances stack.
5. Rename the Variant attribute in any instance and confirm the changes. Also, save the publisher context.
6. …
=> Nuke: node name influence product (subset) name

openpype/hooks/pre_add_last_workfile_arg.py, openpype/hosts/max/hooks/force_startup_script.py, openpype/hosts/max/hooks/inject_python.py, openpype/settings/ayon_settings.py
Keep `adsk_3dsmax` group in applications settings.
Because 3dsmax group in AYON is `adsk_3dsmax` but we're converting it to `3dsmax` it does not match and find available application in `ApplicationManage`. Because the group changed it was required to add `adsk_3dsmax` to launch hooks which had `3dsmax`.
1. 3dsMax can be launched in AYON
2. The prelaunch hooks are executed in both AYON and OpenPype modes
=> AYON: 3dsMax settings

openpype/hosts/nuke/api/lib.py, openpype/settings/entities/schemas/projects_schema/schemas/template_nuke_knob_inputs.json
Nuke knob types in settings having new `Box` type for reposition nodes like Crop or Reformat.
Also found some typos so fixed them too
1. all should work as it was but new knob type is added
2. Open Studio Settings on any project at `project_settings/nuke/create/CreateWriteRender/prenodes/Reformat01/knobs`
3. Try to add new knob and set the type to box
4. you should see this
=> Nuke: adding BBox knob type to settings

openpype/hooks/pre_ocio_hook.py, openpype/pipeline/colorspace.py
Fixed bug in GitHub PR where the OCIO config template was not properly formatting environment variables from System Settings `general/environment`.
1. make sure `general/environmnet` is configured for multiplatform path
2. use the defined environenment key in config path input
3. open nuke task and see it is correctly adding OCIO env var and setting config path to running process
=> Colorspace: including environments from launcher process

openpype/hosts/houdini/plugins/publish/validate_primitive_hierarchy_paths.py
When ABC path validator fails, it prints node objects not node paths or names
This bug happened because of updating `get_invalid` method to return nodes instead of node paths 
Before
After 
`get_invalid` method should return a list of nodes objects because this is what `get invalid action` expects. 
1. create a geo without path attr
1. create alembic pointcache instance
2. check error message
=> Bugfix: Houdini abc validator error message

openpype/hosts/houdini/plugins/create/create_arnold_ass.py, openpype/hosts/houdini/plugins/create/create_arnold_rop.py, openpype/hosts/houdini/plugins/create/create_karma_rop.py, openpype/hosts/houdini/plugins/create/create_mantra_rop.py, openpype/hosts/houdini/plugins/create/create_redshift_rop.py, openpype/hosts/houdini/plugins/create/create_vray_rop.py
So, something was forgotten while moving out from `LegacyCreator` to `NewCreator`  
`LegacyCreator` used `defaults` to list suggested subset names 
which was changed into `default_variants` in the the `NewCreator`
and setting `defaults` to any values has no effect! 
This update affects: 
I have removed  `default_variants` which effectively set variants to `"Main"` as default, so no need to setting it explicitly.
This bug is the same as #5368
1. open creator and check `Variants` menu
=> Bugfix: Houdini update defaults variable

openpype/client/server/conversion_utils.py, openpype/hosts/maya/api/plugin.py, openpype/lib/usdlib.py, openpype/pipeline/template_data.py, openpype/settings/ayon_settings.py
Added `folder` to template data, so `{folder[name]}` can be used in templates.
The folder has only `name` at this moment for which is used asset name. Can be also used in OpenPype. As far as I'm aware there are no other places where data for templates are prepared at this moment.
1. Make openpype addon, upload to AYON, set in bundle
2. Make sure you're using `{folder[name]}` in anatomy templates
3. Run OpenPype
- Last workfile should be found on startup
- Last workfile should be found in workfiles tool
- Save in workfiles tool should work correctly
- Save as in workfiles tool should work correctly
1. Publish from host of your choice
2. Publishing should went smoothly
=> AYON: Add folder to template data

openpype/cli.py, openpype/host/dirmap.py, openpype/hosts/nuke/api/lib.py, openpype/modules/sync_server/sync_server_module.py, openpype/modules/sync_server/utils.py, openpype/plugins/publish/integrate.py, openpype/pype_commands.py, openpype/tools/libraryloader/app.py, openpype/tools/loader/model.py, openpype/tools/sceneinventory/lib.py, openpype/tools/sceneinventory/model.py, openpype/tools/sceneinventory/view.py, openpype/tools/settings/local_settings/projects_widget.py, openpype/tools/utils/lib.py, server_addon/create_ayon_addons.py
Existence of SyncServer module is optional and not required. Added `sync_server` module back to ignored modules when openpype addon is created for AYON. Command `syncserver` is marked as deprecated and redirected to sync server cli.
Use safe access to module and check if is set to `None` before checking for `enabled` attribute. The most possibly breaking change is in integrate plugin where sites are calculated on own if sync server is not available. PR is preparation for AYON.
Nothing should change in OpenPype!
1. Create openpype addon
2. Upload addon to AYON server
3. Add the version to new bundle
4. In AYON mode should work all tools in hosts
5. Publishing should go through integration without complications
=> SyncServer: Existence of module is optional

openpype/tools/sceneinventory/view.py
Fix accesss to `sync_server` attribute in scene inventory.
Bug caused by https://github.com/ynput/OpenPype/pull/5413.
1. Open Scene inventory
2. Should work as usual
=> Scene Inventory: Fix issue with 'sync_server'

openpype/hosts/nuke/api/workfile_template_builder.py, openpype/pipeline/workfile/workfile_template_builder.py
Some bunch of small bugs needed to be fixed 
- implemented **delete_placeholder** abstraction
1. create some testing template and set the template in a nuke template builder profelse
2. create the template inside Nuke and all should be working as expecting. Placeholders should be removed after the template is applied if the preset is having desabled `Keep placeholders`
=> Nuke: workfile template fixes

openpype/pipeline/context_tools.py
Without it plugins with 'automated' targets won't be triggered (eg `CloseAE` etc.)
1. Trigger `runtests` for AE or PS, tests should finish successfully
=> Tests: Add automated targets for tests

openpype/hosts/tvpaint/api/lib.py, openpype/hosts/tvpaint/lib.py
Calculation of frames for repeat behavior is working correctly.
It did work only if layer started from frame `0`, now it should be able to handle any range.
1. Create asset with frame range 12 frames (1001 - 10013) - and task
2. Open workfile on task under the asset
3. Set mark in to 0 and mark out to 12
4. Make a layer that does start on frame 5
5. Make 4 frames in layer (with visibly different content)
6. Set pre and post behavior of the layer to repeat (loop)
7. Create -> Publish the layer
8. Check integrated frames and validate if the image content does match the content from workfile (the order of frames is correct)
=> TVPaint: Fix 'repeat' behavior

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/load/_load_animation.py, openpype/hosts/maya/plugins/load/actions.py, openpype/hosts/maya/plugins/load/load_reference.py, openpype/hosts/maya/plugins/load/load_yeti_rig.py, openpype/settings/ayon_settings.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_load.json, server_addon/maya/server/settings/loaders.py, server_addon/maya/server/version.py
This PR enhances previous one. All ReferenceLoaders could not wrap imported products into explicit group.
Also `Import` Loaders have same options. Control for this is separate in Settings, eg. Reference might wrap loaded items in group, `Import` might not.
1. Remove `_GRP` in `project_settings/maya/load/import_loader`
2. Try to `Import` anything into Maya
3. Try import `abc` representation of `animation`
=> Maya: allow not creation of group for Import loaders

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/settings/ayon_settings.py, openpype/settings/defaults/project_settings/aftereffects.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
Settings of custom addons are available in converted settings.
Settings of addons that are not in prepared conversion utils were not available in output ('ftrack', 'slack' 'shotgrid' addons).
=> AYON: Apply unknown ayon settings first

openpype/tools/settings/local_settings/projects_widget.py
Yes I have
Not yet
@FadyFS
3.15.11-nightly.3
Linux / Centos
the previous behavior (bug) : 
Happened only once in a particular configuration
open settings with 3.14.7 
1. Run openpype on the 3.15.11-nightly.3 version 
2. Open settings in 3.14.7 version
_No response_
_No response_
=> Bug: Local settings don't open on 3.14.7 

openpype/pipeline/farm/pyblish_functions.py
Handles are now set correctly on farm published product version if asymmetric were set to shot attributes.
1. set asymmetric handles to any of your testing shot
2. open any host app and set framerange to it from shot
3. publish on farm
4. notice in loader that product is having correct handles
=> Farm publishing: asymmetric handles fixed

openpype/tools/sceneinventory/model.py
Fix how provider icons are accessed in scene inventory.
Call `get_site_icons` on sync sever module instead of calling it on self.
1. Enabled sync server module
2. Open scene inventory in any host
3. It should not crash
Resolves https://github.com/ynput/OpenPype/issues/5449
=> Scene Inventory: Provider icons fix

openpype/hosts/nuke/plugins/load/load_image.py
Bug fixing of the read node's name not being updated correctly when setting version or switching asset.
n/a
1. Go to OP Setting `project_settings/nuke/load/LoadImage/node_name_template`
2. Set node_name template with the varying data by version/asset, such as `{class_name}_{id}_{ext}`
3. Launch Nuke with Launcher/OP
4. Access "Load.." via AYON/OP Menu
5. Load image with the families such as plateMain, reviewMain etc...
6. Access "Manage.." via AYON/OP Menu
7. Right click to set version or switch asset
8. The name should be changed as expected
=> Nuke: Name of the Read Node should be updated correctly when switching versions or assets.

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/create/convert_legacy.py, openpype/pipeline/farm/pyblish_functions.py
New Publisher is creating different subset names than previously which resulted in duplication of `render` string in final subset name of `render` family published on Deadline.
This PR solves that, it also fixes issues with legacy instances from old publisher, it matches the subset name as was before.
This solves same issue in Max implementation.
`renderModelingMain_beauty` in old publisher >> `renderModelingRenderingMain_beauty`
1. create new render instance, publish to deadline, check subset name (folder name)
2. use old workfile with instances created in old publisher, use `Convert legacy` to re-create instance, check subset names
=> Maya: Fix wrong subset name of render family in deadline

openpype/hosts/maya/plugins/publish/collect_current_file.py
`Maya Current File` collector was tied to `workfile` unnecessary. It should run even if `workile` instance is not being published.
1. Disable `workfile` instance and publish
2. `Collect Scene Version` shouldnt fail
=> Maya: Context plugin shouldn't be tied to family

openpype/modules/deadline/plugins/publish/submit_publish_job.py
This PR hopefully fixes this issue #5440  
This solution was a dumb test that worked! 
I don't know if it covers all the cases (e.g. Muster)
1. enable kitsu module
2. submit a deadline job
=> Add kitsu credentials to deadline publish job 

openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
Fix publishing version 0 to Ftrack.
Error:
```
File "C:\Users\tokejepsen\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
runner(*args)
File "C:\Users\tokejepsen\OpenPype\openpype\modules\ftrack\plugins\publish\integrate_ftrack_api.py", line 57, in process
File "C:\Users\tokejepsen\OpenPype\openpype\modules\ftrack\plugins\publish\integrate_ftrack_api.py", line 149, in integrate_to_ftrack
TypeError: 'NoneType' object has no attribute '__getitem__'
```
1. Setup version 0 for any or all hosts.
2. Publish version 0 to Ftrack from the configured host.
=> Ftrack: Fix version 0 when integrating to Ftrack - OP-6595

openpype/plugins/publish/extract_thumbnail_from_source.py
Avoids the following warning from `ExtractThumbnailFromSource`:
```
// pyblish.ExtractThumbnailFromSource : oiiotool WARNING: -o : Can't save 4 channels to jpeg... saving only R,G,B
```
Added argument `--ch R,G,B`.
This is fine because the output thumbnail is currently always `.jpg` and doesn't support alpha.
[Mentioned on Ynput Discord here](https://discord.com/channels/517362899170230292/517382145552154634/1144627806844752002).
1. Use a screenshot in the new publisher, e.g. take one from screenshot tool or paste from clipboard (or browse)
2. Publish
It'd be good to also test if publishing thumbnail using 'browse' works fine if the source itself isn't a `.jpg` or `.png` but potentially a file format more complex than that.
=> Publisher: Avoid warnings on thumbnails if source image also has alpha channel

openpype/modules/deadline/plugins/publish/submit_max_deadline.py
Fix the bug of falling back to use workfile for Arnold 
n/a
1. Launch Max via launcher
2. Create Render Instance with Arnold or some renderers
3. Publish
=> Max: Fixing the bug of falling back to use workfile for Arnold or any renderers except Redshift

openpype/pipeline/publish/lib.py
Fix logged message for settings automatically applied to plugin attributes
Before:
```
```
After:
```
```
1. Open the publisher
2. Check the logs
=> Publisher: Tweak log message to provide plugin name after "Plugin"

openpype/settings/defaults/project_settings/traypublisher.json
Adding Audio product type into default presets so anybody can publish audio to their shots.
1. Open publisher and se there is new product / family available on top Audio.
2. Set context and drop any wav into representation field and publish.
3. All should be publish as expected.
=> TrayPublisher: adding audio product type into default presets

openpype/plugins/publish/validate_publish_dir.py
Nonsensical "family" key was used instead of real value (as 'render' etc.) which would result in wrong translation of intermediate family names.
Updated docstring.
=> General: Fix Validate Publish Dir Validator

openpype/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py, openpype/modules/deadline/plugins/publish/help/validate_deadline_pools.xml, openpype/modules/deadline/plugins/publish/validate_deadline_connection.py, openpype/modules/deadline/plugins/publish/validate_deadline_pools.py
- Fix optional support of validate deadline pools
- Query deadline webservice only once per URL for verification, and once for available deadline pools instead of for every instance
- Use `deadlineUrl` in `instance.data` when validating pools if it is set.
- Code cleanup: Re-use existing `requests_get` implementation
Example report of Validate Deadline Pools:
1. Publish to Deadline from supported hosts, e.g. maya, fusion, nuke, etc.
=> Enhancement: Deadline plugins optimize, cleanup and fix optional support for validate deadline pools

openpype/plugins/publish/validate_version.py
Fix double spaces in message.
Example output **after** the PR:
1. Publish from a lower workfile version than the latest publish with "Use workfile version" setting enabled.
2. Check the validation message in the publisher.
=> Enhancement: Cosmetics for Higher version of publish already exists validation error

openpype/lib/events.py, tests/unit/openpype/lib/test_event_system.py
Implemented event system with more expected behavior of event system. If an event is triggered during other event callback, it is not processed immediately but waits until all callbacks of previous events are done. The event system also allows to not trigger events directly once `emit_event` is called which gives option to process events in custom loops.
The event system is not used anywhere, I need it for refactor of workfiles tool, where order of events matter. The changes can be added as part of that PR, but I thought it would be easier to do a review in smaller PR.
=> Chore: Queued event system

openpype/hosts/houdini/startup/MainMenuCommon.xml
This PR adds two updates:
1. dynamic main menu 
2. dynamic asset name and task
1. Check main menu name in AYON and OpenPype
2. Switch among assets, check asset name and task
<table>
<tr>
<td><img src="https://github.com/ynput/OpenPype/assets/20871534/60a2a711-47c1-4c95-a77b-b7cb2e0bdc60"></td>
<td><img src="https://github.com/ynput/OpenPype/assets/20871534/761fba8f-fb64-40af-8bf6-fcae3a7a809e"></td>
<td><img src="https://github.com/ynput/OpenPype/assets/20871534/96584dd1-1d85-4d00-8b51-52a82d82b661"></td>
</tr>
</table>
=> Enhancement: Update houdini main menu

openpype/modules/base.py
When using a custom AYON_ADDONS_DIR environment variable that variable is used in the launcher correctly and downloads and extracts addons to there, however when running Ayon does not respect this environment variable
1. set custom `$AYON_ADDONS_DIR`
2. start ayon-launcher
3. It should fetch the addons to the specified `$AYON_ADDONS_DIR`
4. When it then runs it uses the addons from there (instead of the dir under the users home folder)
=> have the addons loading respect a custom AYON_ADDONS_DIR

openpype/modules/deadline/repository/custom/plugins/Ayon/Ayon.py, openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Expande `~` paths in executables list.
This gives option to set executable to `~/.local/share/AYON/app/{version}/ayon` (or `~/AppData/local/Ynput/AYON/app/{version}/ayon.exe` for windows) without defining all usernames.
1. Fill path to AYON in deadline plugin with `~`
2. Install AYON there
3. Submit job
4. All should work as expected
=> AYON: Deadline expand userpaths in executables list

openpype/hosts/houdini/api/lib.py, openpype/hosts/houdini/api/pipeline.py
*Similar to Maya,* Make `Set Frame Range` resets FPS, issue https://github.com/ynput/OpenPype/issues/5516
There are couple of callbacks that validates FPS (e.g.  `before_save`)
> If you think This PR is not necessary, I can close it! 
1. open new houdini session 
2. try setting fps to different values
3. click `Set Frame Range`
=> Houdini: Reset FPS when clicking Set Frame Range

openpype/hosts/webpublisher/publish_functions.py, openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
Targets could be a list, original implementation pushed it as a separate items, it must be added as `--targets webpulish --targets filepublish`.
`wepublish_routes` handles triggering from UI, changes in `publish_functions` handle triggering from cmd (for tests, api access).
=> Webpublisher: better encode list values for click

openpype/plugins/publish/extract_hierarchy_to_ayon.py
Fill entities and update template data on instances during extract AYON hierarchy.
I think we need to change the fill of `anatomyData`, they should be prefilled in collection phase -> Future feature.
1. Run editorial publishing in AYON
2. Make sure the publishing would create new folders and tasks in project
3. The publishing should work as expected and get over integration
- Validate the hierarchy is correct, the subsets are under correct folders and files are at correct places
=> AYON: Fill entities during editorial

openpype/hooks/pre_ocio_hook.py, openpype/hosts/nuke/api/lib.py
Hiero and Nuke is not supporting windows unc path formatting in OCIO environment variable.
1. Add ocio config with unc path
2. open nuke and check that the unc path is added into custom config.
=> OCIO: windows unc path support in Nuke and Hiero

openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
Nuke is now correctly repairing render target after the existing frames validator finds missing frames and repair action is used.
1. open test scene in nuke and make sure no rendered frames are available on created Render Write node. 
2. Open Publisher and set render target to existing frames publishing.
3. Validator should fail and use repair buttons on Top either to Local or Farm
4. Refresh publishing context and notice the Render Target was set according to your selection. 
Closes https://github.com/ynput/OpenPype/issues/4997
=> Nuke: existing frames validator is repairing render target

openpype/pipeline/publish/lib.py
Publishing folder can be flagged as persistent at representation level.
1.all should work as usually. This only is not removing files after publish if the representation is having persistancy flag in representation data.
=> Global: avoiding cleanup of flagged representation

openpype/hosts/maya/plugins/publish/validate_shape_zero.py
Refactor to PublishValidationError to allow the RepairAction to work + provide informational report message
Fixes #5456
Example report:
1. Make sure to enable the plug-in in settings: `project_settings/maya/publish/ValidateShapeZero/enabled`
2. Publish a model family with geometry with component tweaks, e.g.
- Create a cube
- Delete history
- Move one vertex in edit mode (this is now a component tweak)
=> Maya: Validate Shape Zero fix repair action + provide informational artist-facing report

openpype/hosts/maya/plugins/publish/validate_plugin_path_attributes.py
- Optimize query (use `cmds.ls` once)
- Add Select Invalid action
- Improve validation report
- Avoid "Unknown object type" errors
Example report output after this PR:
1. Set some invalid filepaths on node types that are checked by the plug-in's settings.
=> Maya: Optimize validate plug-in path attributes

openpype/hosts/maya/plugins/publish/validate_instance_in_context.py
- Chore/Refactor: Re-use existing select invalid and repair actions
- Enhancement: provide more elaborate PublishValidationError report
- Bugfix: fix "optional" support by using `OptionalPyblishPluginMixin` base class.
1. Create an instance that publishes into a different asset than your current asset.
2. Publish (make sure the validator catches it, the report is nice and clear.
3. Make sure the "optional" checkbox works for the validator.
=> Maya: Refactor/tweak Validate Instance In same Context plug-in

openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
Further logic expects that single item files will be only 'string' not 'list' (eg. repre["files"] = "abc.exr" not repre["files"] = ["abc.exr"].
This would cause an issue in ExtractReview later.
This could happen if DL rendered single frame file with different frame value.
=> Deadline: files on representation cannot be single item list

openpype/hosts/unreal/hooks/pre_workfile_preparation.py
Create Unreal project in local temporary folder and when done, move it to final destination.
Project creation in Unreal requires directory to be clean without any content whatsoever. But in some storage scenarios, metadata files are created and thus will project creation fail. Solution is to create it locally in temporary folder and move it to final destination only when it is done.
1. Create new Unreal project
2. It should be created as expected and copied to the final destination specified by project templates.
=> Unreal: Create project in temp location and move to final when done

igniter/bootstrap_repos.py
Do not add `schema` folder to zip file. This fixes issue cause by https://github.com/ynput/OpenPype/pull/5355 .
Schema folder was moved inside openpype codebase.
```
File "C:\Users\qam\code\OpenPype\igniter\install_thread.py", line 166, in run
local_openpype = bs.create_version_from_live_code()
File "C:\Users\qam\code\OpenPype\igniter\bootstrap_repos.py", line 697, in create_version_from_live_code
self._create_openpype_zip(temp_zip, repo_dir)
File "C:\Users\qam\code\OpenPype\igniter\bootstrap_repos.py", line 867, in _create_openpype_zip
sha256sum(sanitize_long_path(file.as_posix())),
File "C:\Users\qam\code\OpenPype\igniter\bootstrap_repos.py", line 74, in sha256sum
with open(filename, 'rb', buffering=0) as f:
FileNotFoundError: [Errno 2] No such file or …
```
=> Chore: Do not try to add schema to zip files

openpype/tools/utils/lib.py
Do not force `PassThrough` rounding policy if different policy is defined via env variable.
On some virtual machines is `PassThrough` rounding policy causing issues with calculated widget rectangle and paint rectangle. Painted rectangle has expected rectangle, but handling of events happens in smaller and offset rectangle. Probably caused by some bug in Qt. Widgets on top left are closer to expected behavior, bottom right is worse.
You must have some scaling set (e.g. 125% on windows).
1. Set environment variable `QT_SCALE_FACTOR_ROUNDING_POLICY` to e.g. `"Floor"`
2. Launch OpenPype
3. UIs should be resized by the rounding policy
NOTE: This does not affect when Igniter starts first. Changes in igniter are in separated PR https://github.com/ynput/OpenPype/pull/5554
=> Chore: Allow custom Qt scale factor rounding policy

igniter/__init__.py
Do not force `PassThrough` rounding policy if different policy is defined via env variable.
On some virtual machines is `PassThrough` rounding policy causing issues with calculated widget rectangle and paint rectangle. Painted rectangle has expected rectangle, but handling of events happens in smaller and offset rectangle. Probably caused by some bug in Qt. Widgets on top left are closer to expected behavior, bottom right is worse.
You must have some scaling set (e.g. 125% on windows).
1. Set environment variable `QT_SCALE_FACTOR_ROUNDING_POLICY` to e.g. `"Floor"`
2. Launch OpenPype so igniter is shown
3. The size of igniter should be rounded by the policy you set to env variable
=> Igniter: Allow custom Qt scale factor rounding policy

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/hosts/fusion/plugins/create/create_saver.py, openpype/hosts/houdini/api/plugin.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/create/create_animation.py, openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/create/create_unreal_skeletalmesh.py, openpype/hosts/maya/plugins/create/create_unreal_staticmesh.py, openpype/hosts/maya/plugins/create/create_vrayscene.py, openpype/hosts/nuke/api/plugin.py, openpype/hosts/photoshop/plugins/create/create_flatten_image.py, openpype/hosts/photoshop/plugins/create/create_image.py, openpype/hosts/photoshop/plugins/create/create_review.py, openpype/hosts/photoshop/plugins/create/create_workfile.py, openpype/hosts/traypublisher/plugins/create/create_movie_batch.py, openpype/hosts/tvpaint/plugins/create/create_render.py, openpype/hosts/tvpaint/plugins/create/create_review.py, openpype/hosts/tvpaint/plugins/create/create_workfile.py, openpype/lib/python_module_tools.py, openpype/pipeline/create/context.py, openpype/pipeline/create/creator_plugins.py
System settings are not passed to initialization of create plugin initialization (and `apply_settings`).
Reasons: The system settings are not used anywhere, and since AYON there won't be 2 types of settings.
We need validation of all Create plugins: They should not use `system_settings` in `apply_settings` method and they should not override `__init__` method.
To make this PR safer the system settings can still be passed to creator initialization, but eventually it will be removed in future PR anyway, so it would be just temporary backwards compatibility.
This PR must be updated with latest develop and revalidated changes before merge.
1. Technically run all available creators in Publisher
=> Chore: Create plugin does not expect system settings

openpype/pipeline/create/creator_plugins.py
Create plugins do not log warning messages about each create plugin because of wrong `__init__` method check.
Use `__init__` check for each base class of create plugin. Issue caused by https://github.com/ynput/OpenPype/pull/5553 .
1. Open publisher.
2. There should not be any logged warnings if create plugin does not override `__init__` or expect system settings in `apply_settings`.
=> Create Plugins: Better check of overriden '__init__' method

openpype/hosts/houdini/api/pipeline.py
Fix Houdini not showing outdated containers pop-up on scene open when launching with last workfile argument
1. Launch Houdini into an asset that has an existing workfile with outdated containers
2. On launch (with launch last workfile) this should now popup the dialog that scene contains outdated containers
=> Houdini: Fix outdated containers pop-up on opening last workfile on launch

openpype/hosts/maya/plugins/create/create_yeti_cache.py
Fix attribute definitions for `CreateYetiCache`
`__init__` was overridden instead of using `get_instance_attr_defs`. Previously the attribute definitions should not have worked.
Note that even with this PR [the issue here](https://github.com/ynput/OpenPype/issues/5468#issuecomment-1706070618) might still be present.
1. Create yeti cache instance
2. Publish it
=> Maya: Fix attribute definitions for `CreateYetiCache`

openpype/hosts/maya/plugins/load/load_yeti_cache.py, openpype/hosts/maya/plugins/publish/collect_yeti_cache.py
When publishing and loading yeti caches persist the display output and preview colors + settings to ensure consistency in the view
1. Publish yeti cache in Maya with some tweaked preview settings (e.g. viewport preview color, etc)
2. Load in yeti cache, settings should be preserved.
=> Maya: Yeti Cache Include viewport preview settings from source

openpype/hosts/blender/plugins/load/load_blend.py, openpype/pipeline/load/plugins.py, openpype/pipeline/load/utils.py
Since https://github.com/ynput/OpenPype/pull/4602 the `fname` attribute on the `LoaderPlugin` should've been deprecated and set for removal over time. However, no deprecation warning was logged whatsoever and thus one usage appears to have sneaked in (fixed with this PR) and a new one tried to sneak in with [a recent PR](https://github.com/ynput/OpenPype/pull/5584#discussion_r1317740936) 
1. Add usage of `self.fname` in a loader plugin
2. Ensure the deprecation warning is logged
3. Ensure also that loaders work fine without usage of `self.fname`
=> Chore: Loader log deprecation warning for 'fname' attribute

openpype/client/server/conversion_utils.py
Do not fix `"folder"` key in representation context until it is needed.
The folder is already filled during publishing so it is not necessary to convert template and change value.
1. Published representations could be loaded
=> AYON: Fix representation context conversion

openpype/hosts/traypublisher/plugins/publish/collect_missing_frame_range_asset_entity.py, openpype/hosts/traypublisher/plugins/publish/validate_frame_ranges.py, openpype/plugins/publish/collect_sequence_frame_data.py
We are inheriting  default frame handles and fps data either from project or setting them to 0. This is just for case a production will decide not to injest the sequential representations with asset based metadata.
1. Open TrayPublisher on a context
2. drop some imagesequence data to Plate family.
3. Disable instance attribute for `Collect Sequence Frame Data`
4. Publish and see that all had been published as expected.
5. look into Loader and find the published product and see that the frame-range defined on the version is the same as the original frame-range and is not the same as it is defined on asset parent.
=> TrayPublisher: set default frame values to sequential data

openpype/tools/publisher/widgets/screenshot_widget.py
Fix opacity value.
Current value of animation until it starts is `None`.
```
File "C:\Users\<user>\AppData\Local\Ynput\AYON\addons\openpype_3.16.5-nightly.1\openpype\tools\publisher\widgets\screenshot_widget.py", line 74, in paintEvent
painter.setBrush(QtGui.QColor(0, 0, 0, self._opacity))
TypeError: 'PySide2.QtGui.QColor' called with wrong argument types:
PySide2.QtGui.QColor(int, int, int, NoneType)
Supported signatures:
PySide2.QtGui.QColor()
PySide2.QtGui.QColor(typing.Any)
PySide2.QtGui.QColor(PySide2.QtCore.Qt.GlobalColor)
PySide2.QtGui.QColor(PySide2.QtGui.QColor)
PySide2.QtGui.QColor(str)
PySide2.QtGui.QColor(int, int, int, int = 255)
PySide2.QtGui.QColor(int)
```
1. Open Publisher tool
2. Take screenshot in thumbnails widget
=> Publisher: Screenshot opacity value fix

openpype/lib/transcoding.py, openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py, openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py, openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py, openpype/modules/kitsu/plugins/publish/integrate_kitsu_note.py
- Reduce artist-facing logs for component integration for Ftrack 
- Avoid "Comment is not set" log in artist facing report for Kitsu and Ftrack
- Remove info log about `ffprobe` inspecting a file (changed to debug log)
- interesting to see however that it ffprobes the same jpeg twice - but maybe once for thumbnail?
Here's an example how it was before:
1. See the code changes (likely easiest)
=> Ftrack: Less verbose logs for Ftrack integration in artist facing logs

openpype/hosts/maya/plugins/publish/collect_rig_sets.py, openpype/hosts/maya/plugins/publish/validate_rig_contents.py, openpype/hosts/maya/plugins/publish/validate_rig_controllers.py, openpype/hosts/maya/plugins/publish/validate_rig_controllers_arnold_attributes.py, openpype/hosts/maya/plugins/publish/validate_rig_out_set_node_ids.py, openpype/hosts/maya/plugins/publish/validate_rig_output_ids.py
Fix usage of `out_SET` and `controls_SET` since #5310 because they can now be prefixed by the subset name.
- Collect the rig sets only once (I've ordered it before Collect History so that the instance still contains less node, as an optimization)
- Also fixes a hard error when `out_SET` is not found, instead now only relevant `PublishValidationError` are raised to generate a nice report
_Note that quite a few validators for the rig can be disabled and are disabled by default - so you might need to enable them to validate they work correctly._
1. Enable all the rig validators
2. Create a new rig instance
3. Validate the rig publish
=> Maya: Fix rig validators for new out_SET and controls_SET names 

openpype/hosts/maya/tools/mayalookassigner/commands.py
Fix Maya Look assigner failing to show any content if it finds an invalid container for which it can't find the asset in the current project. (This can happen when e.g. loading something from a library project).
There was logic already to avoid this but there was a bug where it used variable `_id` which did not exist and likely had to be `asset_id`. 
I've fixed that and improved the logged message a bit, e.g.:
```
// Warning: openpype.hosts.maya.tools.mayalookassigner.commands : Id found on 22 nodes for which no asset is found database, skipping '641d78ec85c3c5b102e836b0'
```
Example not found representation in Loader:
The issue isn't necessarily related to NOT FOUND representations but in essence boils down to finding nodes with asset ids that do not exist in the current project which …
=> Maya: Fix look assigner showing no asset if 'not found' representations are present

openpype/hosts/aftereffects/plugins/load/load_file.py
#4602 broke imports of image sequences. 
1. try to load image sequence with multiple frames into AE
3. shouldn't fail
=> AfterEffects: fix imports of image sequences

openpype/hosts/blender/plugins/publish/collect_review.py
Fixes hardcoded subset name for Reviews in Blender.
1. Create a review instance and publish it.
2. Check if it is published with the right subset name.
=> Blender: Remove Hardcoded Subset Name for Reviews

openpype/hosts/tvpaint/api/communication_server.py
Do not wait for callback to finish.
Initialization and showing of tools can trigger request sent to a TVPaint which will block both processes as both are waiting for response.
1. Open tools in TVPaint
2. They should not cause stucked process
=> TVPaint: Fix tool callbacks

openpype/hosts/tvpaint/tvpaint_plugin/plugin_code/library.cpp
TVPaint plugin can be reopened.
When TVPaint plugin window was closed and reopened, the new opened window did not contain menu items.
1. Start TVPaint
2. Open OpenPype plugin
3. Close the window
4. Open the plugin again
5. Menu items should be visible
=> TVPaint: Plugin can be reopened

openpype/lib/transcoding.py, openpype/plugins/publish/extract_review.py
Extract review is specifying layer name when exr is multilayer.
This issue was discovered with renders from blender where output exr had channels `['Main.AOV.R', 'Main.AOV.G', 'Main.AOV.B', 'Main.AOV.A', 'Main.Combined.R', 'Main.Combined.G', 'Main.Combined.B', 'Main.Combined.A', 'Main.Normal.X', 'Main.Normal.Y', 'Main.Normal.Z', 'Main.Test.X']` which failed in ffmpeg.
1. First of all, any other current exr processing should still work (e.g. multipart exrs from maya)
2. Render from blender (testing for @simonebarbieri )
=> Extract Review: Multilayer specification for ffmpeg

openpype/hosts/photoshop/plugins/publish/extract_review.py
ExtractReview caused issue on `auto_image` instance without alpha channel, this fixes it.
1. add visible layer with any background color
2. publish - ExtractReview shouldn't fail
=> Photoshop: auto_images without alpha will not fail

openpype/client/server/entities.py
Just 'id' is not returned because value in fields. Caused KeyError.
=> Fix - _id key used instead of id in get_last_version_by_subset_name

server_addon/maya/server/settings/imageio.py
Added deprecated info to docstrings of maya colormanagement settings.
Resolves: https://github.com/ynput/OpenPype/issues/5556
=> AYON: Mark deprecated settings in Maya

poetry.lock, pyproject.toml
Lower click version to support older versions of python.
The newest version is only for python >=3.7 which cause issues with addons that have defined their cli methods.
1. Run create env
2. Run older DCC via OpenPype (ideally with Python 2.x)
3. Test publishing with addons that use click for cli commands (e.g. ftrack)
=> Chore: Lower click dependency version

openpype/hosts/maya/plugins/publish/extract_active_view_thumbnail.py
This sets the Maya instance's thumbnail to the current active view if no thumbnail was set yet.
It's currently set to only the workfile family for which it makes most sense - but I think it could even be nice for other families as at least a visual hint?
1. Make sure thumbnails are enabled for your studio
- Ensure you have `AVALON_THUMBNAIL_ROOT` set in OpenPype settings
3. Open Maya
4. Publish a workfile
5. Published workfile subset should now have a thumbnail
=> Maya: Extract active view as thumbnail when no thumbnail set

openpype/hosts/maya/plugins/create/create_multiverse_usd_over.py
Fix Creator for Multiverse USD Override by inheriting from correct new style creator class type
1. Open Create tab in Publisher
2. Multivere USD Override should now be listed and be creatable.
=> Maya: Multiverse USD Override inherit from correct new style creator

openpype/hosts/max/plugins/publish/extract_model_obj.py, openpype/hosts/max/plugins/publish/validate_usd_plugin.py
There migh be situation where OBJ Extractor passes without failure, but no obj file is produced. This is adding simple check directly into the extractor to catch it earlier then in the integration phase. Also switched `Validate USD Plugin` to optional, because it was always run no matter if the Extract USD was enabled or not, hindering testing (and publishing).
Apart of simple check for the file, this is modifying seemingly unrelated Validate USD Plugin. This was really needed without actually installing it into the max because of the above mentioned reason. I think we should look into #5602 to amend that properly.
Publishing model from Max should work as before when `Extract obj` is switched on. The validator for USD Plugin should be optional too.
=> 3ds max: small tweaks to obj extractor and model publishing flow

Dockerfile.centos7
Docker build was missing `libssl.1.1.so` and `libcrypto.1.1.so` symlinks needed by the executable itself, because Python is now explicitly built with OpenSSL 1.1.1
This just creating symlinks, but to already copied libraries, but it should be probably handled more gracefuly.
1. Build Centos 7 variant
2. Run it on vanilla Centos 7 system
=> Bugfix: create symlinks for ssl libs on Centos 7

openpype/modules/base.py
Do not load already separated modules from default directory.
The modules are not in client code when created using `create_ayon_addon.py` script, but for testing of PRs is usually copied whole openpype into local app data which causes troubles when these modules are loaded.
1. All ignored addons should be loaded in OpenPype (ftrack, shotgrid, slack, sync_server)
2. The same addons should not be loaded in AYON mode from OpenPype
=> AYON: Ignore separated modules

inno_setup.iss
In OP Installer `Create a desktop icon` is checked by default.
=> General: Create a desktop icon is checked

setup.cfg
Add default configuration for [isort tool](https://pycqa.github.io/isort/)
This shouldn't affect any functionality of OpenPype/AYON
=> Chore: add default isort config

openpype/hosts/tvpaint/plugins/publish/extract_sequence.py, openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py
Extractor marks representation of review instance with review tag.
1. Open TVPaint
2. Review auto-creator should create an instance
3. Enable the instance
4. Publish
5. Extract review should catch the representation and create review (based on settings)
=> TVPaint: Fix review family extraction

openpype/settings/ayon_settings.py, server_addon/core/server/settings/publish_plugins.py
Output definitions of Extract OIIO transcode have name to match OpenPype settings, and the settings are converted to dictionary in settings conversion.
Added partial fix of older AYON settings.
1. Extract OIIO transcode plugin should work with filled profiles
=> AYON settings: Extract OIIO transcode settings

openpype/client/server/conversion_utils.py, openpype/tools/ayon_workfiles/abstract.py, openpype/tools/ayon_workfiles/control.py, openpype/tools/ayon_workfiles/models/hierarchy.py, openpype/tools/ayon_workfiles/models/workfiles.py
Convert AYON task type short name for OpenPype correctly.
AYON has short name stored under `shortName` whereas in OpenPype is expected `short_name`.
1. Use `{task[short]}` in template (e.g. in workfile template)
2. Use the template so it is filled
=> AYON: Fix task type short name conversion

openpype/hosts/maya/plugins/publish/validate_color_sets.py
Fix `validate_color_sets` for the new publisher.
In current `develop` the repair option does not appear due to wrong error raising.
1. Setup multiple colorsets on a mesh in Maya with `Modeling > Mesh Display > Color Sets Editor`
2. Publish and repair through publisher.
=> Maya: Support new publisher for colorsets validation.

openpype/hosts/maya/plugins/create/create_unreal_yeticache.py, openpype/hosts/maya/plugins/publish/collect_yeti_cache.py, openpype/hosts/maya/plugins/publish/extract_unreal_yeticache.py, openpype/hosts/unreal/plugins/load/load_yeticache.py, openpype/plugins/publish/collect_resources_path.py, openpype/plugins/publish/integrate.py
Implemented Yeti support for Unreal.
A new family has been implemented, `ue_yeticache`, to differentiate from the existing `yeticache`. Yeti has different exporter to be compatible with the Unreal built-in Groom system, so it needs a different extractor.
1. In Maya, import or create a Yeti Node
2. Create a new instance of family Unreal Yeti Cache and publish.
3. In Unreal, load the published asset.
=> Unreal: Yeti support

openpype/hosts/nuke/api/lib.py
Colorspace is set correctly to any write node created from publisher. 
1. create any write node via publisher in nodes
2. open group node of render write node with CTRL+Enter 
3. Open Write node in property bin and change colorspace knob to some value
4. Use Menu OpenPype Set Colorspace 
5. see that the value had been set to settings configuration
=> Nuke: fix set colorspace on writes

openpype/hosts/photoshop/lib.py, openpype/hosts/photoshop/plugins/create/create_flatten_image.py, openpype/hosts/photoshop/plugins/create/create_image.py, tests/unit/openpype/hosts/photoshop/test_lib.py
If {layer} placeholder is at the end of subset name template and not used (for example in `auto_image` where separating it by layer doesn't make any sense) trailing '_' was kept. This updates cleaning logic and extracts it as it might be similar in regular `image` instance.
1.Configure `project_settings/global/tools/creator/subset_name_profiles` set something like `{family}_{Task}_{Variant}_{layer}`
2. try to publish from fresh new workfile
=> Photoshop: remove trailing underscore in subset name

openpype/tools/ayon_workfiles/models/workfiles.py
Fix save as button in workfiles tool.
(It is mystery why this stopped to work??)
1. Start AYON
2. Launch DCC from launcher (your choice)
3. Open workfiles tool
4. Save workfile
5. Happy end
=> AYON: Workfiles tool save button works

openpype/hosts/traypublisher/plugins/publish/collect_frame_data_from_asset_entity.py, openpype/hosts/traypublisher/plugins/publish/collect_sequence_frame_data.py, openpype/plugins/publish/collect_sequence_frame_data.py, openpype/settings/defaults/project_settings/traypublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
Issue with missing `assetEnity` key in context data is not problem anymore. 
1. Try to publish plate imagesequence in traypublisher
2. enable `Collect Original Sequence Frame Data` toggle on instance and publish
3. Open Tray Loader and check the framerange is inherited form original sequence and handles are set to 0
4. reload the tray publishing context
5. desable`Collect Original Sequence Frame Data` toggle on instance and publish
6. publish again 
7. Open Tray Loader and check the framerange is inherited form asset frame range including handles
=> traypublisher: missing `assetEntity` in context data

openpype/tools/publisher/control.py
Fixes a memory leak where resetting publisher does not clear the stored plugins for the Publish Report Maker.
Also changes the stored plugins to a `set` to optimize the lookup speeds.
Reported the bug on discord [here](https://discord.com/channels/517362899170230292/517382145552154634/1158139604831059968)
> I think I've found a **'memory leak' in the new publisher.**
> 
> Shouldn't `reset` on the Publisher's Report maker controller also clear the `_stored_plugins` here: https://github.com/ynput/OpenPype/blob/6e69d3a87f3c8ec6168c59bbf7e7d7fdadd58b61/openpype/tools/publisher/control.py#L187
> 
> The only reason why currently *this* https://github.com/ynput/OpenPype/blob/6e69d3a87f3c8ec6168c59bbf7e7d7fdadd58b61/openpype/tools/publisher/control.py#L225-L231 isn't occuring on refreshes/resets …
=> Publisher: Fix report maker memory leak + optimize lookups using set

openpype/hosts/nuke/plugins/publish/collect_nuke_instance_data.py
Settings for synchronizing workfile version to published products is fixed.
- settings were broken by renaming plugin name to `CollectNukeInstanceData` here https://github.com/ynput/OpenPype/pull/5409
1. publish new render instance and make sure current workfile version is set to more than first version.
2. notice that the published version of render is aligned with workfile version.
Closed #5661
=> Nuke: workfile version synchronization settings fixed

openpype/hosts/blender/plugins/load/load_blend.py
Fixes an error that occurs when removing or updating an asset in a new layout instance.
When updating or removing the assets, it looks for `members` in the parent container, which doesn't exist (it exists in loaded layouts, not in instances).
1. Create a new layout instance in Blender.
2. Try updating or removing one of the assets in the layout.
=> Blender: Fix remove/update in new layout instance

openpype/hosts/maya/plugins/publish/validate_plugin_path_attributes.py
Overwriting list with string is causing `TypeError: string indices must be integers` in subsequent iterations, crashing the validator plugin.
1. Plugin should work as expected
=> Maya: Bug in validate Plug-in Path Attribute

openpype/cli.py, openpype/pype_commands.py, tests/conftest.py, tests/lib/testing_classes.py
Instead of changing the environment, this command flag allows for changing the database.
1. Run test suite with command flag `--openpype_mongo [URI]`.
=> Add openpype_mongo command flag for testing.

openpype/modules/deadline/repository/custom/plugins/Ayon/Ayon.py
This commit enhances the path resolution mechanism in the RenderExecutable function of the Ayon plugin. Previously, the function only considered paths starting with a tilde (~), ignoring other valid paths listed in exe_list. This limitation led to an empty expanded_paths list when none of the paths in exe_list started with a tilde, causing the function to fail in finding the Ayon executable.
With this fix, the RenderExecutable function now correctly processes and includes all valid paths from exe_list, improving its reliability and preventing unnecessary errors related to Ayon executable location.
Resolves: #5675
=> Deadline: handle all valid paths in RenderExecutable

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/plugin.py
Code and docstring tweaks on https://github.com/ynput/OpenPype/pull/5623
n/a
1. add `png` to the settings `project_settings/nuke/publish/ExtractReviewDataBakingStreams/outputs/baking/extension`
2. publish review from nuke
=> Nuke: minor docstring and code tweaks for ExtractReviewMov

openpype/hosts/maya/api/menu.py, openpype/hosts/maya/api/pipeline.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/publish/validate_unreal_staticmesh_naming.py, openpype/modules/muster/plugins/publish/submit_maya_muster.py
Re-use system settings / project settings where we can instead of requerying.
Note: Moved the Muster-specific submitter for maya into the muster module
1. Maya should launch ok
2. Maya menu should install ok
3. Muster submissions should still work from maya
4. Custom naming for import and reference loaders should this be configurable in `project_settings/maya/load/import_loader` and `project_settings/maya/load/reference_loader` and should still work as intended.
=> Chore: Maya reduce get project settings calls

openpype/plugins/actions/open_file_explorer.py
Explore here action does not crash when task is not selected, and change error message a little.
1. Run explore here action when only asset is selected
2. If there is some relevant folder it should open explorer.
=> Chore: Explore here action can work without task

openpype/hosts/nuke/plugins/publish/extract_review_intermediates.py, openpype/settings/ayon_settings.py, server_addon/applications/server/applications.json
Small changes/fixes related to AYON settings. All foundry apps variant `13-0` has label `13.0`. Key `"ExtractReviewIntermediates"` is not mandatory in settings.
The label for `13-0` was missing for all variants (probably copy>paste issue). New settings `"ExtractReviewIntermediates"` does not work in backwards compatible way and always expects the key which breaks when new version of openpype addon is used with older nuke addon.
1. Check the labels in applications.
2. `"ExtractReviewIntermediates"` should not cause crashes of OpenPype addon with older version of nuke addon.
=> AYON: Small settings fixes

start.py
Make sure that source disk ends with `\` instead of destination disk.
Destination disk should be just `<letter>:` but we were adding `\` to the end which does not work. That should be forced for source path where it must be `C:\`.
Make sure that you build OpenPype, or run it from code for testing of this PR.
1. Change settings to map e.g. `C:\` to `T:\`
2. Start OpenPype
3. Validate the mapping happened 
NOTE: To remove the new disk open powershell and pass in `subst T: /d` (replace T with your disk letter).
=> Chore: Fix subst paths handling

openpype/tools/ayon_launcher/abstract.py, openpype/tools/ayon_launcher/control.py, openpype/tools/ayon_launcher/models/actions.py, openpype/tools/ayon_launcher/ui/actions_widget.py
Skip last workfile boolean works as expected.
The value was reversed, so it skipped last workfile when should use it and vica versa.
1. Open host and task of your choice and make sure it has a workfile.
2. Close it.
3. Make sure `Skip last workfile` is not checked in launcher tool.
4. Launch it again, it should open host with last workfile.
5. Close it.
6. Make sure `Skip last workfile` is checked in launcher tool.
7. Launch it again, it should not open a workfile.
=> AYON Launcher tool: Fix skip last workfile boolean

openpype/pype_commands.py
Env var will be filled in `env_var` fixture, here it is too early to check
=> Tests: Remove checks for env var

openpype/tools/ayon_launcher/abstract.py, openpype/tools/ayon_launcher/control.py, openpype/tools/ayon_launcher/ui/actions_widget.py, openpype/tools/ayon_launcher/ui/hierarchy_page.py, openpype/tools/ayon_launcher/ui/projects_widget.py, openpype/tools/ayon_launcher/ui/window.py, openpype/tools/ayon_utils/models/hierarchy.py, openpype/tools/ayon_utils/widgets/folders_widget.py, openpype/tools/ayon_utils/widgets/tasks_widget.py
Refresh button does propagate refreshed content properly. Folders and tasks are cached for 60 seconds instead of 10 seconds. Auto-refresh in launcher will refresh only actions and related data which is project and project settings.
Refresh button did trigger refresh in controller but if project/asset/task did not change, the other widgets did not update their data.
1. Open launcher tools
2. Go to a project in launcher tool
3. Open the same project in AYON web UI
4. Go to Edit tab and add few folders/tasks
5. Go back to launcher tool
6. It should update new folders/tasks when you click on refresh
NOTE: There is auto-refresh in launcher each 10 seconds so you may not need to click on refresh button at all.
Resolves https://github.com/ynput/OpenPype/issues/5681
=> AYON Launcher tool: Fix refresh btn

openpype/hosts/blender/hooks/pre_pyside_install.py
Change version regex to support blender 4 subfolder.
1. Install brand new blender 4
2. Open Blender 4 via launcher
3. A PySide2 should be automatically installed
=> Blender: Add support to auto-install PySide2 in blender 4

openpype/hosts/blender/plugins/load/load_abc.py
Implemented loading Alembic Animations in Blender.
The Alembic loader has been extended to support the `animation` family. A few issues with the collections where the assets were linked to have been fixed.
1. Publish an animation in Alembic format in any DCC.
2. Try loading it in Blender.
=> Blender: Alembic Animation loader

openpype/modules/sync_server/launch_hooks/pre_copy_last_published_workfile.py
Fixing these two issues:
- Hardcoded main site -> Replaced by `anatomy.fill_root`.
- Workfiles can sometimes be copied while they shouldn't.
- Download a workfile by using the `Pre Copy Last Workfile` launch hook.
- You should get a `resources` folder in your local workdir containing all `resources` listed in the workfile data, except the workfile itself.
Note: If the asset you're testing this on is already downloaded, you can rename its task folder (for instance by appending `_old`) to force openpype to redownload it, or use the [Force download last workfile feature](https://github.com/ynput/OpenPype/pull/5660) if it's available.
=> Fix: Hardcoded main site and wrongly copied workfile

openpype/pipeline/farm/pyblish_functions.py
There's a bug on the `pyblish_functions.get_time_data_from_instance_or_context` where if `handleStart` or `handleEnd` on the instance are set to value 0 it's falling back to grabbing the handles from the instance context. Instead, the logic should be that it only falls back to the `instance.context` if the key doesn't exist.
This change was only affecting me on the `handleStart`/`handleEnd` and it's unlikely it could cause issues on `frameStart`, `frameEnd` or `fps` but regardless, the `get` logic is wrong.
1. Assign handleStart/handleEnd value to 0 on the instance and some other value on the context data
2. Run a publish to the farm and check that the handleStart/handleEnd are set to 0
=> General: Avoid fallback if value is 0 for handle start/end

openpype/client/server/operations.py
Fix ServerDeleteOperation asset -> folder conversion typo
Pretty sure this was a bug.
Also took along two typos in docstring in the same file.
Not sure what this influences - so not sure what to test.
=> Bugfix: ServerDeleteOperation asset -> folder conversion typo

openpype/hosts/nuke/plugins/load/actions.py, openpype/hosts/nuke/plugins/load/load_backdrop.py, openpype/hosts/nuke/plugins/load/load_camera_abc.py, openpype/hosts/nuke/plugins/load/load_effects.py, openpype/hosts/nuke/plugins/load/load_effects_ip.py, openpype/hosts/nuke/plugins/load/load_gizmo.py, openpype/hosts/nuke/plugins/load/load_gizmo_ip.py, openpype/hosts/nuke/plugins/load/load_matchmove.py, openpype/hosts/nuke/plugins/load/load_model.py, openpype/hosts/nuke/plugins/load/load_script_precomp.py
Variable name for filtering by extensions were not correct - it suppose to be plural. It is fixed now and filtering is working as suppose to.
1. loaders should be now correctly offered on extensions
=> Nuke: loaders are filtering correctly

openpype/settings/ayon_settings.py
The `output` dictionary that gets passed into `ayon_settings._convert_global_project_settings` gets replaced when converting the settings for `ExtractOIIOTranscode`. This results in `global` not being in the output dictionary and thus the defaults being used and not the project overrides.
=> AYON Settings: Fix global overrides

openpype/client/server/entities.py
Fixed how `archived` argument is handled in get subsets/assets function.
The logic was not matching to implementation of mongo api function. If `archive` is set to `True` it does mean that both active and inactive should be queried instead of only non-active.
The `archive=True` is used in scene inventory so there is a chance that scene inventory does not work in AYON mode at all.
1. Open Switch asset dialog in Scene Manager tool
2. It should fill the values as expected
=> Chore: AYON query functions arguments

openpype/hosts/blender/api/pipeline.py
Remove `update_hierarchy` function which is causing crashes in scene inventory tool.
The function can change view of scene inventory hierarchy in Scene manager when user use cherry-pick on set of containers. But the implementation does crashes with `unhashable type: dict` (code: `all_containers = set(ls())`). The code probably never worked.
1. Open blender.
2. Make sure you have something loaded in.
3. Open scene manager.
4. Right click on loaded container and trigger `Cherry-pick` action.
5. It should cherry pick it and the view should show only cherry picked containers (before it crashed).
=> Blender: Remove 'update_hierarchy'

openpype/hosts/nuke/api/__init__.py, openpype/hosts/nuke/api/actions.py, openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/plugins/publish/validate_asset_context.py
Refactor `SelectInvalidAction` to behave like other action for other host, create `SelectInstanceNodeAction` as dedicated action to select the instance node for a failed plugin.
- Note: Selecting Instance Node will still select the instance node even if the user has currently 'fixed' the problem.
Implement comment as per [here](https://github.com/ynput/OpenPype/pull/5749/files#r1358090182)
This also makes sure there's backwards compatibility to before this PR  #5749 for studios that might have used the `SelectInvalidAction` of Nuke host for any validators they had rolled out themselves. (Currently in native OpenPype no nuke validator is currently using it)
1. validate asset context - action should still work
2. select invalid action is currently unused so might be hard to test - but at …
=> Enhancement: Nuke refactor `SelectInvalidAction`

openpype/hosts/nuke/plugins/publish/collect_backdrop.py, openpype/hosts/nuke/plugins/publish/collect_context_data.py, openpype/hosts/nuke/plugins/publish/collect_gizmo.py, openpype/hosts/nuke/plugins/publish/collect_model.py, openpype/hosts/nuke/plugins/publish/collect_slate_node.py, openpype/hosts/nuke/plugins/publish/collect_workfile.py, openpype/hosts/nuke/plugins/publish/extract_backdrop.py, openpype/hosts/nuke/plugins/publish/extract_camera.py, openpype/hosts/nuke/plugins/publish/extract_gizmo.py, openpype/hosts/nuke/plugins/publish/extract_model.py, openpype/hosts/nuke/plugins/publish/extract_ouput_node.py, openpype/hosts/nuke/plugins/publish/extract_render_local.py, openpype/hosts/nuke/plugins/publish/extract_review_data_lut.py, openpype/hosts/nuke/plugins/publish/extract_review_intermediates.py, openpype/hosts/nuke/plugins/publish/extract_script_save.py, openpype/hosts/nuke/plugins/publish/extract_slate_frame.py, openpype/hosts/nuke/plugins/publish/extract_thumbnail.py, openpype/hosts/nuke/plugins/publish/validate_backdrop.py, openpype/hosts/nuke/plugins/publish/validate_output_resolution.py, openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py, openpype/hosts/nuke/plugins/publish/validate_write_nodes.py
Tweak logs that are not artist-facing to debug level + in some cases clarify what the logged value is.
Note that I don't use Nuke, so someone else would need to test how well the reports now end up in Nuke.
1. Publish lots of different stuff from Nuke, like models, renders, cameras, etc.
The Publish Reports should not contain technical logs - but should be limited only to information an artist cares about after a publish.
=> Enhancement: Tweak logging for Nuke for artist facing reports

openpype/hosts/maya/api/lib.py
`cmds.ogs()` is a call that will crash if Maya is running in headless mode (mayabatch, mayapy). This is handling that case.
This command is used only in `suspended_refresh` context manager, but that one is used on many places. This is fixing it perhaps in a little dirty way directly inside that context manager to lower impact on other code.
This is hard to test - current workflows in UI based Maya should work the same, like publishing pointcaches. But publishing them from mayapy or mayabatch shouldn't crash.
=> Maya: don't call `cmds.ogs()` in headless mode

openpype/settings/defaults/system_settings/applications.json, server_addon/applications/server/applications.json
Adding Maya 2024 as default application variant.
Removing Maya 2020 and older, as these are not supported anymore.
1. Launch settings with a new database and validate only Maya 2024-2022 is present.
Split from https://github.com/ynput/OpenPype/pull/5644
=> Maya: Add Maya 2024 and remove pre 2022.

openpype/modules/deadline/plugins/publish/submit_fusion_deadline.py
Fusion submission to Deadline was missing OPENPYPE_VERSION env var when submitting from build (not source code directly). This missing env var might break rendering on DL if path to OP executable (openpype_console.exe) is not set explicitly and might cause an issue when different versions of OP are deployed.
This PR adds this environment variable.
1. build OP
2. start publish from build and Fusion
3. check that render job `Environments` contain OPENPYPE_VERSION
4. remove explicit path to `openpype_console.exe` (and keep only dir there?)
5. try to republish again
=> Fusion: added missing OPENPYPE_VERSION

tests/integration/hosts/maya/input/startup/userSetup.py, tests/integration/hosts/maya/lib.py
Suggesting to ingest `userSetup.py` startup script for easier collaboration and transparency of testing.
1. Run Maya testing `.\tools\openpype_console.bat runtests C:\Users\tokejepsen\OpenPype\tests\integration\hosts\maya\test_publish_in_maya.py`
2. Comment out `tests\integration\hosts\maya\lib.py` line 42 and validate Maya only launches.
Split from https://github.com/ynput/OpenPype/pull/5644
=> Testing: Ingest Maya userSetup

openpype/modules/ftrack/plugins/publish/collect_ftrack_api.py
Skip tasks when looking for asset equivalent entity.
If there is a `wasp` folder and `wasp` task in ftrack project, which is valid, it is possible that `wasp` task would be used for `"ftrackEntity"` instead of the folder.
I don't know how to test this.
=> Ftrack: Skip tasks when looking for asset equivalent entity

openpype/plugins/publish/extract_thumbnail.py
Fixing issue with the order of the `ExtractOIIOTranscode` and `ExtractThumbnail` plugins. The problem was that the `ExtractThumbnail` plugin was processed before the `ExtractOIIOTranscode` plugin. As a result, the `ExtractThumbnail` plugin did not inherit the `review` tag into the representation data. This caused the `ExtractThumbnail` plugin to fail in processing and creating thumbnails.
1. We need to test mainly Maya, Houdini and ideally local and farm publishing
2. Test it with ExtractOIIOTrancode multiple presets. Here is an example 
3. In combination with Ftrack it should create two AssetVersions and each with own Thumbnail.
=> General: thumbnail extractor as last extractor

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/plugins/load/load_gizmo.py, openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
Gizmo product is not offered in Loader as plugin. It is also updating as expected.
Nuke api lib is having new context function for swapping nodes with maintained linked dependencies.
1. Load any Gizmo product into scene which is having more then one version. (publish some in advance if you are having none. Two versions are enough)
2. Load the Gizmo into the script and connect it to graph so you are having input and output dependencies.
3. Open Manager of inventory and change version of the loaded gizmo
4. all should work as expected.
5. Use bot loaders > `Load Gizmo - Input Process` and `Load Gizmo`
closes https://github.com/ynput/OpenPype/issues/5501
=> Nuke: loading gizmos fixes

openpype/hosts/nuke/api/lib.py
UNC paths were broken on windows for custom OCIO path and this is solving the issue with removed double slash at start of path 
1. add UNC path to second anatomy root ("resources") >> on windows just go to folder properties and switch to `share` tab. Then copy past the unc path to the Anatomy windows field. My looks like this 
2. add new ocio path to first position on a project `project_settings/global/imageio/ocio_config` and use `{root[resources]}` as part of path >> my looks like this
3. save and open Nuke. All should work as expected and the ocio path should be added to the nuke workfile properties looking like this > 
4. No warning message about `using previouse ocio config...`
=> Nuke: fixing UNC support for OCIO path

server_addon/applications/server/applications.json
In PR #5705 `maya` was wrongly used instead of `mayapy`, breaking AYON defaults in AYON Application Addon.
Unchanged defaults in Application Addon in AYON should show correct maya executables
=> Bug: fix key in application json

openpype/tools/publisher/widgets/card_view_widgets.py
Change of instance by clicking on enabled checkbox will actually update attributes on right side to match the selection.
Trigger 'selection_changed' signal to propagate selection change.
1. Open publisher
2. Create 2 instances
3. Change any visible attribute on one of the instances so there are visible change when changing their selection
4. Select only one if the instances
5. Click on enabled checkbox of the second instance
6. It should change the state, the instance should be selected and the attributes on right side should be related to selected instance
Resolves https://github.com/ynput/OpenPype/issues/5789
=> Publisher: Selection change by enabled checkbox on instance update attributes

openpype/hosts/houdini/plugins/load/show_usdview.py
Fix the "Show in USD View" loader to show up in Houdini
Previous loader would never show since family does not exist within OpenPype.
1. Launch Houdini
2. In loader use "Show in USD View" action (also works with alembic files)
=> Houdini: Fix Show in usdview loader action

server_addon/core/server/settings/main.py
Added disk mapping settings to core addon settings.
The settings are used in ayon-launcher since this PR https://github.com/ynput/ayon-launcher/pull/61.
=> AYON Settings: Disk mapping

openpype/hosts/houdini/api/lib.py, openpype/hosts/houdini/api/plugin.py
Revert a recent change made in #5621 due to this [comment](https://github.com/ynput/OpenPype/pull/5621#discussion_r1355611105). However the change is faulty as can be seen [mentioned here](https://github.com/ynput/OpenPype/pull/5698#pullrequestreview-1685448609)
This is how I tested - if I open the publisher and "reset" in the publisher the instances also match the states set in this code, e.g. all on or all off depending on how I ran it.
```python
from openpype.pipeline import registered_host
from openpype.pipeline.create import CreateContext
host = registered_host()
context = CreateContext(host, reset=True)
for instance in context.instances:
instance.data["active"] = False
context.save_changes()
context = CreateContext(host, reset=True)
assert all(instance.data["active"] == False for …
```
=> Houdini: Remove `setParms` call since it's responsibility of `self.imprint` to set the values

openpype/tools/ayon_loader/models/actions.py
Fix SubsetLoader plugin processing in AYON loader tool.
Version contexts supposed to be stored by their id, but were stored by product id which lead to invalid contexts on load.
1. Open loader in tray
2. Use on of SubsetLoader actions (e.g. Calculate old versions)
3. The action should work as expected (in case of Calulcate old versions the size should not be `0.0 b`)
=> AYON loader: Fix SubsetLoader functionality

openpype/tools/attribute_defs/widgets.py
Attribute definition widget 'NumberAttrWidget' shows `< Multiselection >`  label on multiselection.
I've tried multiple different approaches and after few fails when overriding `paintEvent`, changing `QLineEdit` in spinboxes and some others, I found out the easiest is to show different QLineEdit which is clickable.
1. Create 2 instances with number inputs
2. Change value of first to different value from second instance
3. Select both
4. Label `< Multiselection >` should show and if you click on it it should show one of the values there
Resolves https://github.com/ynput/OpenPype/issues/5790
=> 'NumberAttrWidget' shows 'Multiselection' label on multiselection

server_addon/openpype/client/pyproject.toml
Removed `shotgun_api3` dependency from openpype dependencies for AYON launcher. The dependency is already defined in shotgrid addon and change of version causes clashes.
=> AYON: Remove 'shotgun_api3' from dependencies

openpype/pipeline/create/context.py
Fix issue with unrespected change propagation in `CreateContext`. All successfully saved instances are marked as saved so they have no changes. Origin data of an instance are explicitly not handled directly by the object but by the attribute wrappers.
The issue was described here https://github.com/ynput/OpenPype/pull/5698#discussion_r1368665597 .
This cannot be tested without coding.
This is my example I've used in Nuke and I've used random instance with random plugin...
```python
from openpype.pipeline import registered_host
from openpype.pipeline.create import CreateContext
create_context = CreateContext(registered_host())
create_context.reset()
created_instance = None
for instance in create_context.instances:
created_instance = instance
break
print(created_instance.changes().changed) …
```
=> Chore: Create context respects instance changes

openpype/hosts/blender/api/ops.py
Skip logic in `before_window_show` in blender when in AYON mode. Most of the stuff called there happes on show automatically.
1. Run AYON with openpype addon from this PR
2. Launch blender
3. Try to use tools (workfiles, sceneinventory, loader) in blender
4. They shoud work
=> Blender: Fix tools handling in AYON mode

openpype/pipeline/publish/abstract_collect_render.py
Removed unused `_asset` variable from `RenderInstance`.
I didn't find any usage of the variable anywhere, and because it was using `legacy_io` it looked like a good candidate to be removed. As far as I know each instance should have the the asset so it should not be really used anywhere.
1. Validate the variable is not used
=> Chore: Removed unused variable from `AbstractCollectRender`

openpype/tools/ayon_workfiles/widgets/files_widget_workarea.py
Fix double click on workfiles in workfiles tool to open the file.
Use `open_current_requested` signal instead of missing `save_as_requested`.
1. Open AYON with this PR in openpype addon
2. Launch a DCC
3. Open workfiles tool
4. Double click on a workfile
5. That should open the workfile
=> Workfiles tool AYON: Fix double click of workfile

openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
If it throws exception, `no_of_frames` value  wont be available, so it doesn't make sense to log it.
This approach is used to limit need to decide if published file is image or video-like. Hopefully exception is fast enough and would be still necessary for rare cases of weird video-likes files.
1. setup in WP Settings family 'pointcache' and appropriate non video-like extension (could be .zip)
2. publish file with that extension, it shouldn't fail in `CollectPublishedFiles`
=> Webpublisher: removal of usage of no_of_frames in error message

openpype/hosts/unreal/plugins/publish/validate_sequence_frames.py
Improved error reporting for Sequence Frame Validator.
This validator was using only `asserts` to report errors, and those were missing essential information about the offending files that were causing the validation to fail.
1. Prepare a render to publish.
2. Remove some of the files, and add another sequence from another render.
3. Test that the validator fails, and check that the reports inform clearly on what the problem is.
=> Unreal: Improved error reporting for Sequence Frame Validator

openpype/tools/attribute_defs/widgets.py
Fixed default look of `NumberAttrWidget` by hiding its multiselection widget.
=> Attribute Defs: Hide multivalue widget in Number by default

openpype/hosts/unreal/api/pipeline.py, openpype/hosts/unreal/plugins/inventory/delete_unused_assets.py, openpype/hosts/unreal/plugins/inventory/update_actors.py, openpype/hosts/unreal/plugins/load/load_alembic_animation.py, openpype/hosts/unreal/plugins/load/load_geometrycache_abc.py, openpype/hosts/unreal/plugins/load/load_skeletalmesh_abc.py, openpype/hosts/unreal/plugins/load/load_skeletalmesh_fbx.py, openpype/hosts/unreal/plugins/load/load_staticmesh_abc.py, openpype/hosts/unreal/plugins/load/load_staticmesh_fbx.py, openpype/hosts/unreal/plugins/load/load_uasset.py, openpype/hosts/unreal/plugins/load/load_yeticache.py
Changed how assets are updated in Unreal.
When updating assets in Unreal, instead of completely replacing the old version, the new version is loaded in a different folder (it is checked beforehand if it was already loaded), and replaces the asset in the current level. Then, we check if the old asset is used in any other level. If it isn't we remove the previous version.
Updated:
- Static Meshes (FBX and ABC).
- Skeletal Meshes (FBX and ABC).
- Geometry Caches.
1. Load an asset.
2. Add it to a level and save it.
3. Try changing the version of the asset.
=> Unreal: Changed behaviour for updating assets

openpype/hosts/nuke/plugins/load/load_image.py
When updating `Image` containers the code is trying to set the name of the node. This results in a warning message from Nuke shown below;
Suggesting to not change the node name when updating.
1. Update an `image` container in Nuke with an existing node already called `LoadImage_png`.
=> Nuke: Dont update node name on update

server_addon/create_ayon_addons.py
Adding developers environment options.
- adding argparse module
- adding `output` for targeting to specfic folder (ayon-docker/addons)
- adding `clear-output-dir` to explicitly clearing already created folders and versions in addons
- adding `addon` arg for creating package only for particualr addons
1. in cmd of choice go to `./server_addon` folder
2. use similarly following cmd 
```
python .\create_ayon_addons.py --skip-zip --output="[path to docker repo folder]\ayon-docker\addons"  
```
3. this should add addons to your addon folder and not to remove any previously created addons.
=> Chore: updating create ayon addon script

openpype/hosts/nuke/api/lib.py
Remove unused function `get_render_path` from nuke integration.
Randomly found a function without usage.
Validate the function is not used and the content is not important.
=> Nuke: Remove unused 'get_render_path' function

openpype/modules/base.py, server_addon/create_ayon_addons.py
Create AYON packages is skipping kitsu module in creation of modules/addons and kitsu module is not loaded from modules on start. The addon already has it's repository https://github.com/ynput/ayon-kitsu.
=> AYON: Skip kitsu module when creating ayon addons

openpype/lib/attribute_definitions.py
`UILabelDef` have implemented comparison and uniqueness.
Label of the attribute definition is considered when comparing the objects and it is possible to define a key of label to be able differentiate between different objects.
I didn't test the `key`, but it should work.
1. Use something like this in create plugin
```python
def get_instance_attr_defs(self):
return [
UILabelDef("<b>Header 1</b>"),
BoolDef("Bool1", label="Boolean 1"),
UILabelDef("<b>Header 2</b>"),
BoolDef("Bool2", label="Boolean 2"),
]
```
2. Open publisher
3. See the labels in attributes list after creation
Resolves https://github.com/ynput/OpenPype/issues/5797
=> UIDefLabel can be unique

openpype/plugins/publish/collect_rendered_files.py
Collect all instances from the metadata file - don't return on first instance iteration.
Came up on discord [here](https://discord.com/channels/517362899170230292/517382145552154634/1168569214429311067)
Without this fix e.g. only the first AOV would be integrated for non-multilayer EXRs.
1. Publish a Maya render with multiple AOVs that are **not** multilayer (e.g. generate multiple instances)
=> Bugfix: Collect Rendered Files only collecting first instance

openpype/modules/launcher_action.py
Fix typo `actions_dir` -> `path` to fix register launcher actions fromm OpenPypeModule
[Issue reported on discord](https://discord.com/channels/517362899170230292/517382145552154634/1168917035355471953)
1. Register launcher action from a module with `IPluginPaths` interface in `get_plugin_paths` returning `"actions"` key.
2. Actions should be visible in launcher.
Example registering:
```python
import os
from openpype.modules import OpenPypeAddOn
from openpype.modules.interfaces import IPluginPaths
class MyModule(OpenPypeAddOn, IPluginPaths):
name = "my_module"
def get_plugin_paths(self):
"""Implementation of IPluginPaths to get plugin paths."""
current_dir = os.path.dirname(os.path.abspath(__file__))
return {
"actions": [os.path.join(current_dir, "launcher_actions")]
}
```
Or see …
=> Fix registering launcher actions from OpenPypeModules

openpype/hosts/houdini/api/lib.py, openpype/hosts/houdini/api/shelves.py, openpype/pipeline/context_tools.py
Current implementation of `get_current_context_template_data` does return the same values as base template data function `get_template_data`.
The previous implementation added few more data that are different from the base, which makes the function "unique" > hard to maintain, especially now with AYON compatibility. Implemented the same functionality in houdini to not break current usage. We can think about adding some of the functionality in the base function, but in separated PR.
1. Houdini context change should still update environment variables and shelves correctly.
=> Chore: Limit current context template data function

openpype/lib/local_settings.py, openpype/plugins/publish/collect_current_pype_user.py
Use ayon username for template data in AYON mode.
1. Use `{user}` in one of anatomy templates
2. Publish
3. The username should be filled in the final path
=> AYON: Use AYON username for user in template data

openpype/hosts/blender/plugins/publish/collect_review.py
Fix Grease Pencil missing in review when isolating objects.
When isolating objects for review, the grease pencils objects were excluded. This was supposed to be solved in #5812, but it was missing the case of isolating objects.
1. Try creating a review and add an object that include grease pencil to the instance (they must be linked to the review instance collection).
2. Publish the review. The Grease Pencil should be visible.
=> Blender: Fix missing Grease Pencils in review

openpype/hosts/houdini/plugins/publish/validate_frame_range.py
I faced a bug when publishing HDA instance as it has no `trange` parameter. 
As this PR title says : skip  frame_range_validator  if node has no 'trange' parameter
1. publish hda from Houdini, publisher shouldn't complain about frame range.
=> Bigfix: Houdini skip frame_range_validator if node has no 'trange' parameter

openpype/hosts/blender/plugins/load/load_blend.py
Fix a problem with loading blend layouts.
There was a missing condition when loading blend layout to find the asset group in the published blend file. For this reason, the wrong object was picked up as the asset group, and the rest of the layout wasn't loaded properly.
1. Publish a layout that includes loaded assets.
2. Load it, it should be loaded properly.
=> Blender: Fix loading of blend layouts

openpype/settings/defaults/system_settings/applications.json
Found I needed Nuke 11.0 in the default settings to help with unit testing.
1. Only install Nuke 11.0v4 on the machine.
2. Run testing suite.
=> Nuke: Add Nuke 11.0 as default setting

openpype/hosts/houdini/plugins/create/create_composite.py
Quick bug fix for created composite ROP, set its frame range to the frame range of the playbar.
1. Create Composite ROP 
2. Its frame range should be same as playbar
=> Houdini: set frame range for the created composite ROP

openpype/hosts/nuke/api/pipeline.py, openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/load/load_backdrop.py, openpype/hosts/nuke/plugins/load/load_camera_abc.py, openpype/hosts/nuke/plugins/load/load_clip.py, openpype/hosts/nuke/plugins/load/load_effects.py, openpype/hosts/nuke/plugins/load/load_effects_ip.py, openpype/hosts/nuke/plugins/load/load_gizmo.py, openpype/hosts/nuke/plugins/load/load_gizmo_ip.py, openpype/hosts/nuke/plugins/load/load_image.py, openpype/hosts/nuke/plugins/load/load_model.py, openpype/hosts/nuke/plugins/load/load_ociolook.py, openpype/hosts/nuke/plugins/load/load_script_precomp.py
Nuke loaded containers are updating correctly even they have been duplicating of originally loaded nodes. This had previously been removed duplicated nodes.
- containers are now having `node` key
- container `objectName` is now full path so there is not mistake in nested nodes with the same name
- all loaders had to be updated to access `node` rather then `objectName`
1. Nuke leaders' needs to be tested with Loading of all possible product types and also updating to newer versions. 
2. Ideally, test to duplicate node in the graph and update them too.
=> Nuke: loaders' containers updating as nodes

openpype/hosts/houdini/api/pipeline.py, openpype/hosts/houdini/plugins/publish/collect_instances_usd_layered.py
Remove on instance toggled callback which isn't relevant to the new publisher
As far as I know this does nothing in the new publisher.
1. Use publisher
2. Toggling instances should still work as intended
=> Houdini: Remove on instance toggled callback

server_addon/core/server/settings/tools.py
Fix the wrong key words for the tycache workfile template settings in AYON
(i.e. Instead of families, product_types should be used)
n/a
1. Build the server-addon with this branch
2. Update the addon to your ayon server
3. Update your ayon bundle
4. Launch AYON(If you have the app data built, please delete the old addon build)
5. Publish anything.
=> Fix the Wrong key words for tycache workfile template settings in AYON

openpype/hosts/aftereffects/api/pipeline.py, openpype/hosts/nuke/api/pipeline.py, openpype/hosts/photoshop/api/pipeline.py, openpype/hosts/tvpaint/api/pipeline.py
The `instanceToggled` callbacks should be irrelevant for new publisher.
Similar to PR #5860 but for [other hosts than Houdini as described here](https://github.com/ynput/OpenPype/pull/5860#issuecomment-1791728692).
1. Publishing from these hosts should still work
=> Chore: Remove unused `instanceToggled` callbacks

server_addon/core/server/settings/publish_plugins.py
Follow workfile version label was marked as Collect Anatomy Instance Data label.
The location of the setting is questionable, but that is not goal of this PR.
=> AYON settings: Use correct label for follow workfile version

openpype/modules/ftrack/event_handlers_server/event_first_version_status.py, openpype/modules/ftrack/event_handlers_server/event_next_task_update.py, openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py, openpype/modules/ftrack/event_handlers_server/event_task_to_parent_status.py, openpype/modules/ftrack/event_handlers_server/event_task_to_version_status.py, openpype/modules/ftrack/event_handlers_server/event_thumbnail_updates.py, openpype/modules/ftrack/event_handlers_server/event_version_to_task_statuses.py
Events that happened on project which is not in OpenPype is not processed.
We should not run automations on ftrack projects which are not synced to OpenPype.
Ftrack project which is not synchronized to OpenPype should not trigger any event handlers.
- sync of hierarchical <> non hierarchical attributes
- task to version / version to task status propagation
- thumbnails updates
- first version status
- next task status
=> Ftrack: Events are not processed if project is not available in OpenPype

openpype/cli.py, openpype/pype_commands.py, tests/conftest.py, tests/lib/testing_classes.py
`app_group` command flag. This is for changing which flavour of the host to launch. In the case of Maya, you can launch Maya and MayaPy, but it can be used for the Nuke family as well.
Split from #5644
```
.\openpype_console.bat runtests C:\Users\tokejepsen\OpenPype\tests\integration\hosts\maya\test_publish_in_maya.py --app_group mayapy --mongo_url "mongodb://localhost:2707/"
```
This will fail the testing but should launch MayaPy. We'll resolve issues with testing with MayaPy in a different PR when we make MayaPy the default for testing in Maya.
=> Testing: app_group flag

openpype/tools/ayon_utils/widgets/utils.py
Ignore if passed icon definition is `None`.
This caused crashes if e.g. loader plugin does not have defined icon definition.
1. Loader plugins should be visible on loader tools (specifically AE and PS)
=> AYON tools: Handle empty icon definition

openpype/settings/ayon_settings.py
Convert `ValidateAttributes` settings only if are available in AYON settings.
The settings were added in one of latest PRs and the conversion is expecting the value to be there which breaks when older version of 3dsMax addon is used.
1. Use 3dsMax addon v1.0.0
2. Use this branch for openpype addon
3. Launch of AYON should not cause crashes when settings are received
=> AYON 3dsMax settings: 'ValidateAttributes' settings converte only if available

openpype/tools/publisher/window.py
Move publisher window to center of a screen on first show.
The publisher window is a little bit offset on show which cause that all actionable buttons may be out of screen. Centering the window should help to change it.
1. Open Publisher in DCCs of your choice
2. It would be goot to try this out in all Qt based DCCs to check for possible glitches > maya, nuke, houdini
=> Publisher: Center publisher window on first show

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/load/load_reference.py
Add MayaUsdReferenceLoader to reference USD as Maya native geometry using `mayaUSDImport` file translator.
This allows referencing a USD file similar to referencing Alembic files as native maya geometry.
Unlike Alembic it can actually load the loaded geometry as instances. (However not yet as Instancer, see known issues)
This uses the `mayaUsdPlugin` that comes with recent maya versions and is open-source available [here](https://github.com/Autodesk/maya-usd) where they also provide releases, e.g. 0.25 instead of 0.23.1 that comes by default with Maya 2024.1
It is possible to define Custom Python chasers that run during the file load and thus should be able to be produce nodes as if part of the reference itself. This could allow even 'referencing' custom USD data into Maya native nodes or …
=> Reference USD file as maya native geometry

openpype/tools/publisher/widgets/widgets.py
Confirmation of context changes in publisher on existing instances does not cause glitches.
The glitches are happening only if a context is changed from A to B, and back to A.
- open publisher
- select existing instance (in my case has variant: `Main` asset: `Alpaca_01` and task: `animation`)
- change asset (in my case asset: `Buddy_01`)
- hit Confirm
- change asset back to origin asset (in my case asset `Alpaca_01`)
- now, the confirm button is not visible
The same happens when variant or task is changed, or with combination of them.
1. Go throught steps to reproduce > play with it a little
2. Try to change other values and hit Confirm/Cancel
3. All changes/confirms/cancels should do what is expected to happen
=> Publisher: Instance context changes confirm works

openpype/hosts/blender/plugins/publish/extract_blend.py
Fixed a with blend extractor and packed images.
The extractor was packing all the images in the instance, but it was causing issues if the image was already packed and it wasn't in the saved location anymore, or if the image was saved with a relative path. This PR fixes it by checking if the image was already packed, and pack it only if it isn't.
1. Publish a model with a texture.
2. Delete the original texture file.
3. Load the model and create a layout with that model.
4. Try publish the layout, it should succeed.
=> Blender: Fix blend extraction and packed images

openpype/hosts/blender/plugins/publish/extract_abc.py, openpype/hosts/blender/plugins/publish/extract_abc_animation.py, openpype/hosts/blender/plugins/publish/extract_blend.py, openpype/hosts/blender/plugins/publish/extract_blend_animation.py, openpype/hosts/blender/plugins/publish/extract_camera_abc.py, openpype/hosts/blender/plugins/publish/extract_camera_fbx.py, openpype/hosts/blender/plugins/publish/extract_fbx.py, openpype/hosts/blender/plugins/publish/extract_fbx_animation.py, openpype/hosts/blender/plugins/publish/extract_layout.py, openpype/hosts/blender/plugins/publish/extract_playblast.py, openpype/hosts/blender/plugins/publish/extract_thumbnail.py
Changed how extractors name the output files to be able to use folder paths as unique identifier.
1. Follow steps in #5817 to setup project.
2. Test that creators and extractor works correctly.
=> Blender: Use folder path as unique identifier

openpype/pipeline/context_tools.py, openpype/pipeline/legacy_io.py, openpype/pipeline/mongodb.py, openpype/pipeline/schema/session-4.0.json
Added new session schema required for https://github.com/ynput/OpenPype/pull/5817.
Now `AVALON_ASSET` may contain forward slash which is requirement for folder path.
With new schema it is possible to do small cleanup.
- Environment `AVALON_PROJECTS` is not used anymore thus can be removed.
- Similar with `AVALON_INSTANCE_ID` and `AVALON_CONTAINER_ID`, I don't know if were actually used in past.
- Removed `AVALON_ASSET` from required keys, so `AVALON_PROJECT` is only requirement to create context session in `legacy_io`.
Validate the schema changes.
=> Chore: New session schema

openpype/settings/ayon_settings.py, server_addon/traypublisher/server/settings/editorial_creators.py, server_addon/traypublisher/server/version.py
Fixing Traypublisher settings for adding task in simple editorial.
- changing task settings conversion 
- changing settings value from list to string
- fixing some typos
1. Add some tasks here `ayon+settings://traypublisher/editorial_creators/editorial_simple/shot_add_tasks`
2. use Simple Editorial testing file in Tray publisher and create instances.
3. If they were created then all works as it should
=> AYON: Fix TrayPublisher editorial settings

openpype/client/__init__.py, openpype/client/server/entities.py, openpype/client/server/entity_links.py, openpype/client/server/operations.py, openpype/client/server/utils.py, openpype/lib/local_settings.py, openpype/modules/base.py, openpype/pipeline/anatomy.py, openpype/pipeline/context_tools.py, openpype/pipeline/thumbnail.py, openpype/settings/ayon_settings.py
Create global AYON api connection with all informations all the time.
Global ayon connection was initialized only in ayon-launcher process, but in DCCs missing or wrong information was used. That lead to unknown site id in DCCs or wrong settings variant being used. A function `get_ayon_server_api_connection` was implemented to be used instead of `ayon_api` directly. The function initialize the global connection with site id and ayon launcher version. Then ayon settings module in `openpype.settings` uses correct variant and also set default settings variant in global connection.
1. Settings should be taken from dev settings (or staging settings) inside DCCs and should use correct site id
2. OpenPype should not break at any point
=> AYON: Initialize connection with all information

openpype/tools/ayon_sceneinventory/models/site_sync.py
Skip 'get_site_icons' if site sync addon is disabled.
It did not validate if the addon was disabled.
=> AYON: Scene inventory tool without site sync

openpype/tools/publisher/publish_report_viewer/window.py
Use constants from classes instead of objects.
Using constances from objects is not supported in PySide6.
1. Use Publish report viewer tool with PySide6 e.g. on MacOs (run `./openpype_console publish-report-viewer`)
=> Publish report tool: Fix PySide6

.github/ISSUE_TEMPLATE/bug_report.yml, openpype/hosts/houdini/plugins/publish/validate_houdini_license_category.py
As reported in this [community comment](https://community.ynput.io/t/ayon-monthly-beginners-topic-november-23/967/9)
Houdini USD publishing is only restricted in Houdini apprentice. 
1. publish USD from an apprentice Houdini license won't work in OP or Ayon.
=> Update houdini license validator

openpype/hosts/maya/api/plugin.py, openpype/pipeline/create/creator_plugins.py
Create plugins can auto-apply settings.
I was convinced that this should be default behavior like in other plugins. It is mandatory to set `settings_category` to be able to make auto-apply to work, category is root key in project settings. There looks for `"create"` key (hardcoded) where is looking for key `settings_name`, a class name is used instead of `settings_name` is not filled. The logic implemented in maya was removed.
1. Settings of Maya create plugins should be auto-applied
=> Chore: Create plugin auto-apply settings

openpype/hosts/tvpaint/plugins/load/load_reference_image.py, openpype/modules/ftrack/event_handlers_server/action_tranfer_hierarchical_values.py, openpype/modules/ftrack/event_handlers_server/event_next_task_update.py, openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py, openpype/modules/ftrack/event_handlers_user/action_component_open.py, openpype/modules/ftrack/event_handlers_user/action_delete_asset.py, openpype/modules/ftrack/event_handlers_user/action_delivery.py, openpype/modules/ftrack/event_handlers_user/action_job_killer.py, openpype/plugins/publish/cleanup_explicit.py, openpype/plugins/publish/collect_rendered_files.py, openpype/plugins/publish/extract_burnin.py, openpype/plugins/publish/extract_color_transcode.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/integrate_thumbnail.py, openpype/plugins/publish/integrate_thumbnail_ayon.py, openpype/settings/entities/dict_conditional.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/list_entity.py, openpype/settings/entities/root_entities.py
General logging message tweaks:
- Sort some lists of folder/filenames so they appear sorted in the logs
- Fix some grammar / typos
- In some cases provide slightly more information in a log
n/a
1. Publish a few things, e.g. a few models and a deadline render
2. Test a few Ftrack actions - even though, honestly, they are just logging messages tweaks - it shouldn't break
=> Enhancement: Some publish logs cosmetics

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/lib_rendersettings.py, openpype/hosts/maya/plugins/publish/validate_rendersettings.py, openpype/modules/muster/plugins/publish/submit_maya_muster.py
Remove global `lib.RENDER_ATTRS` and implement a `RenderSettings.get_padding_attr(renderer)` method instead.
Allows more re-use of the functionality and has a simpler entry point to use it.
- Partial cleanup extracted from #3880
1. Submitting renders should still work
=> Maya: Render Settings cleanup remove global `RENDER_ATTRS`

openpype/hosts/blender/api/plugin.py, openpype/hosts/blender/plugins/create/create_action.py, openpype/hosts/blender/plugins/load/import_workfile.py, openpype/hosts/blender/plugins/load/load_abc.py, openpype/hosts/blender/plugins/load/load_action.py, openpype/hosts/blender/plugins/load/load_audio.py, openpype/hosts/blender/plugins/load/load_blend.py, openpype/hosts/blender/plugins/load/load_blendscene.py, openpype/hosts/blender/plugins/load/load_camera_abc.py, openpype/hosts/blender/plugins/load/load_camera_fbx.py, openpype/hosts/blender/plugins/load/load_fbx.py, openpype/hosts/blender/plugins/load/load_layout_json.py, openpype/hosts/blender/plugins/load/load_look.py
Renamed function `asset_name` to `prepare_scene_name`.
The name `asset_name` is not very good decision for a function name. It does not tell what the function does and the name canot be used as variable where the function is used. I've hit an issue when I wanted to use variable `asset_name`.
1. All loaders and creators should work as before this PR.
=> Blender: Better name of 'asset_name' function

openpype/tools/ayon_loader/control.py, openpype/tools/ayon_loader/models/products.py
Fix issues with invalid representation ids in loaded containers and handle missing product type in server database.
Both issues can happen only under specific conditions, e.g. imported OpenPype project or opened OpenPype scene in AYON mode.
1. Open DCC scene from OpenPype in AYON (should have loaded/referenced representations)
2. Open loader tool
3. Loader tool should work as expected
=> AYON: Loader tool bugs hunt

openpype/hosts/photoshop/plugins/publish/collect_auto_image.py, openpype/hosts/photoshop/plugins/publish/collect_auto_review.py, openpype/hosts/photoshop/plugins/publish/collect_auto_workfile.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py, openpype/modules/slack/plugins/publish/collect_slack_family.py
Use available information on context to receive context data instead of using `"anatomyData"` during publishing.
Most of the data are available on context and it is not necessary to use data dedicated for template formatting to receive them, especially host name.
Nothing should change.
=> Chore: Do not use template data as source for context

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/pipeline.py
Use QAction to change label of context label in Nuke pipeline menu.
This is preparation for https://github.com/ynput/OpenPype/pull/5817 where asset in context will contain slashes, which nuke converts into submenus when `addCommand` is used. That was modified. Returned object from `addCommand` should have `action()` method which returns `QAction` object on which is possible to call `setText` to change the label.
Added skip of change label function if in nuke assist.
Test this PR in oldest possible nuke we should support.
1. The context label should be set on launcher.
2. The context label should be changed when context changes via workfiles tool.
=> Nuke: Change context label enhancement

openpype/client/server/openpype_comp.py
AYON server does support to query 'data' field for hierarchy entities (project > ... > representation) using GraphQl since version 0.5.5. Because of [this PR in ayon-python-api](https://github.com/ynput/ayon-python-api/pull/110) it is required to modify custom graphql function in `openpype.client` to support that option.
This is a preparation/future compatibility for new ayon-python-api version. The issue with `"data"` queried via graphlql is that it returns `None` or json string and the json string must be converted.
At this moment everything should work as before.
=> AYON: Prepare for 'data' via graphql

openpype/modules/__init__.py, openpype/modules/base.py, openpype/settings/ayon_settings.py
Introduced base class for AYON addon in openpype modules discovery logic.
The reason to add this class is to be able to pass in original AYON settings instead of settings converted for OpenPype. That is hitting issues in addons that were already moved from the openpype repository which have to receive their settings in other way.
Examine the code. OpenPype modules discovery should work as always did.
=> Chore AYON: AYON addon class

openpype/hosts/traypublisher/plugins/publish/validate_frame_ranges.py
Returning variable which had been removed accidentally in previous PR.
1. in trapublisher publish `plate` family
2.  Validator for Frame ranges should not fail critically.
=> TrayPublisher: adding back `asset_doc` variable

openpype/settings/lib.py
Remove usage of kwargs to create ModulesManager.
1. System settings can be saved
=> Settings: Fix ModulesManager init args

openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
Remove duplicated attributes implementation mentioned in https://github.com/ynput/OpenPype/pull/5931#discussion_r1402175289
n/a
1.Go to Openpype Settings -> project_settings/deadline/publish/MayaSubmitDeadline/pluginInfo
2. Add {"ArnoldVerbose": 2}
3. Launch Maya via launcher with your rendering scene
4. Make sure your current renderer is Arnold
5. Publish
=> Maya: Remove duplicated attributes of MTOA verbosity level 

tests/conftest.py, tests/lib/testing_classes.py
[`is_test_failed`](https://github.com/ynput/OpenPype/blob/develop/tests/lib/testing_classes.py#L220) is used (exclusively) on module fixtures to determine whether the tests have failed or not. This determines whether to run tear down code like cleaning up the database and temporary files.
But in the module scope `request.node.rep_call` is not available, which results in `is_test_failed` always returning `True`, and no tear down code get executed.
The solution was taken from; https://github.com/pytest-dev/pytest/issues/5090
```
openpype_console runtests
```
=> Testing: Fix is_test_failed

openpype/hosts/nuke/plugins/publish/validate_write_nodes.py
Nuke: Validate Nuke Write Nodes refactor to use variable `node_value` instead of `value`
The variable `value` only exists as the last variable value in the `for value in values` loop and might not be declared if `values` is an empty iterable.
Mentioned on [discord](https://discord.com/channels/517362899170230292/517382145552154634/1162367040972128256)
1. Run Validate write node and make sure it does what it intends to do
=> Nuke: Validate Nuke Write Nodes refactor to use variable `node_value` instead of `value`

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
The creation of Ftrack components needs to allow for multiple thumbnails. This is important in situations where there could be several reviewable streams, like in the case of a nuke intermediate files preset. Customers have asked for unique thumbnails for each data stream.
For instance, one stream might contain a baked LUT file along with Display and View. Another stream might only include the baked Display and View. These variations can change the overall look. Thus, we found it necessary to depict these differences via thumbnails.
- to support required feature the plugin had to be rewritten. 
- this is only part in the puzzle which is ensembled in this PR https://github.com/ynput/OpenPype/pull/5936
1. Thumbnails in all hosts should work as before
=> Ftrack: rewriting component creation to support multiple thumbnails

openpype/hosts/maya/plugins/publish/validate_look_default_shaders_connections.py
Resolve https://github.com/ynput/OpenPype/issues/5269
Please test Maya 2024 and any version elder than Maya 2024
1. Create Look with or without tx options.
2. Publish
3. It should run smoothly
=> Maya: Small Tweaks on Validator for Look Default Shader Connection for Maya 2024

openpype/hosts/harmony/api/TB_sceneOpened.js, openpype/hosts/harmony/plugins/publish/extract_render.py
Local rendering was throwing warning about license, but didn't fail per se. It just didn't produce anything.
1. create `Render` instance to be rendered locally
2. it should finish successfully
=> Harmony: Fix local rendering

openpype/hosts/maya/plugins/load/load_reference.py
As the create placeholder dialog displays the two distinct loaders with the same name, this PR is to distinguish Maya USD Reference Loaders from the loaders of which inherited from. 
See the screenshot below:
n/a
1. Launch Maya via launcher
2. Go to Template Builder -> Create Placeholder
3. It should show loaders with different names as expected
=> Maya: Add Label to MayaUSDReferenceLoader

openpype/plugins/publish/integrate_thumbnail_ayon.py
Thumbnail integration could cause crash of server if thumbnail id was changed for the same entity id multiple times. Modified the code to avoid that issue.
This was discovered as bug on server backend and will be handled by failing the operations. So this fix is also required for future backend fix.
1. Use host of your choice.
2. Make sure you have at least 2 instances with same folder that will integrate thumbnail.
3. Publish them.
4. Integrate thumbnail should not fail.
=> AYON: Fix thumbnail integration

server_addon/photoshop/server/settings/workfile_builder.py
Path is not json serializable by default, it is not necessary, better model reused.
Was causing issues when saving profiles for Workfile builder. `"invalid input for query argument $4: {'workfile_builder': {'create_first_vers... (Type is not JSON serializable: PosixPath)`
1. run `server/create_ayon_addons.py` and re-upload `Photoshop` addon OR update `workfile_builder.py` directly in `ayon-docker/addons/photoshop...`
=> Photoshop: Fix removed unsupported Path

openpype/hosts/blender/plugins/publish/extract_thumbnail.py, openpype/plugins/publish/integrate_thumbnail_ayon.py
Use manual thumbnail added to the publisher instead of using it from published representation.
1. Add a thumbnail to any instance.
2. Add a review instance as well (just to check if it actually works. If there is a manual thumbnail, it should use that).
3. Try to publish it.
4. The thumbnail for that published instance should the the one manually added.
=> General: Use manual thumbnail if present when publishing

openpype/pype_commands.py
This is returning original behaviour of `extractenvironments` command from before #5958 so we restore functionality.
That behaviour is wrong, but currently we don't have any other solution. 
Submitted render jobs on farm should start normally (maya/houdini)
> [!WARNING]
This will break #5958 because RoyalRender has 2000 unicode char limit on environments passed to the job
=> Revert `extractenvironments` behaviour

openpype/hosts/maya/plugins/publish/validate_rendersettings.py
The following error has been encountered below: 
```
// pyblish.pyblish.plugin.Action : Finding failed instances..
// pyblish.pyblish.plugin.Action : Attempting repair for instance: renderLookdevMain ...
// Error: pyblish.plugin : Traceback (most recent call last):
//   File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.17.7-nightly.6\openpype\pipeline\publish\publish_plugins.py", line 241, in process
//     plugin.repair(instance)
//   File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.17.7-nightly.6\openpype\hosts\maya\plugins\publish\validate_rendersettings.py", line 395, in …
```
=> Maya: bug fix the repair function in validate_rendersettings

openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Without this fix the error message would report executables string with `;` between EACH character, similar to this PR: https://github.com/ynput/OpenPype/pull/5815
However that PR apparently missed also fixing it in `GlobalJobPreLoad` and only fixed it in `Ayon.py` plugin.
1. Submit to Deadline with AYON plug-in in deadline configured to an invalid executable path.
2. Reported error should be correct, informational and helpful.
=> Bugfix: Fix error message formatting if ayon executable can't be found by deadline

openpype/modules/python_console_interpreter/window/widgets.py
This changes ASCII art in the console based on the AYON/OpenPype mode
1. Run console in Openpype - you should see perfect OP art
2. Run console in AYON:
```
▄██▄
▄███▄ ▀██▄ ▀██▀ ▄██▀ ▄██▀▀▀██▄    ▀███▄      █▄
▄▄ ▀██▄  ▀██▄  ▄██▀ ██▀      ▀██▄  ▄  ▀██▄    ███
▄██▀  ██▄   ▀ ▄▄ ▀  ██         ▄██  ███  ▀██▄  ███
▄██▀    ▀██▄   ██    ▀██▄      ▄██▀  ███    ▀██ ▀█▀
▄██▀      ▀██▄  ▀█      ▀██▄▄▄▄██▀    █▀      ▀██▄
·  · - =[ by YNPUT ]:[ http://ayon.ynput.io ]= - ·  ·
```
=> Change ASCII art in the Console based on the server mode

openpype/tools/tray/pype_info_widget.py, openpype/tools/tray/pype_tray.py
This PR changes what is shown in Tray menu in AYON mode. Previously, it showed version of OpenPype that is very confusing in AYON mode. So this now shows AYON version instead. When clicked, it will opene AYON info window, where OpenPype version is now added, for debugging purposes.
=> Show slightly different info in AYON mode

openpype/hosts/traypublisher/plugins/create/create_editorial.py
Keep EDL clip name inheritance with case sensitivity. 
The code change updates the way the clip name is extracted from the OTIO file. The ".lower()" method has been removed to preserve case sensitivity.
=> Traypublisher: editorial preserve clip case sensitivity

openpype/lib/openpype_version.py, openpype/resources/__init__.py
Resources use `is_staging_enabled` function instead of `is_running_staging` to determine if should use staging icon. And fixed comparison bug in `is_running_staging`.
Function `is_staging_enabled` is not meant to be used the way it was used in resources. In resource we care if we're in staging mode, not if we're in version that should be used for staging.
1. Determination of staging mode should be much faster
=> Chore: Staging mode determination

openpype/client/server/conversion_utils.py, openpype/tools/ayon_loader/models/products.py, openpype/tools/ayon_workfiles/models/workfiles.py
Show correct create time in UIs.
Convert createdAt value to local timezone to show correct date.
1. Open Loader UI
2. Create at times should show correct time
=> AYON: Convert the createAt value to local timezone

openpype/style/style.css
Define solid color for background of branch in QTreeView.
PySide6 draws some backgroup from item's background under branch (not exactly sure why/where from), so transparent background under branch reveals the color. Only solution I found was to set solid color of background color over that part.
Left:   Before this PR.
Right: With this PR.
I'm not aware of a view where is used different background color, that could potentially cause issues.
1. Make sure you're using PySide6 (is automatically used on MacOs)
2. Try out UIs with PySide6
1. Go to `./vendor/python/`.
2. Remove `PySide2` and `shiboken2`.
3. Modify `./pyproject.toml`. Replace windows/linux qtbinding with PySide6
```
[openpype.qtbinding.windows]
package = "PySide6"
version = "6.4.3"
```
4. Run `./tools/fetch_thirdparty_libs.ps1`
=> Chore: PySide6 tree view style

openpype/plugins/publish/collect_resources_path.py
Editorial publishing is fixed and work as expected.
- checking in wrong data
=> Ayon General: traypublisher editorial check of hierarchy in wrong data 

openpype/hosts/photoshop/plugins/publish/extract_review.py, openpype/plugins/publish/integrate_thumbnail_ayon.py
Thumbnails from any products (either `review` nor separate layer instances) weren't stored in Ayon.
This resulted in not showing them in Loader and Server UI. After this PR thumbnails should be shown in the Loader and on the Server (`http://YOUR_AYON_HOSTNAME:5000/projects/YOUR_PROJECT/browser`).
Tis PR explicitly sets path to thumbnail on the instance (as there might be only one thumbnail per instance, imho) bypassing issue that representation with 'name' == 'thumbnail' is by default set to not be integrated.
1. publish workfile in PS with default `review` instance
2. publish workfile in PS with separate `image` instances which have `Review` toggle set to True 
3. Check right column in the Loader and Server UI
=> Photoshop: fix layer publish thumbnail missing in loader

openpype/hosts/fusion/plugins/publish/extract_render_local.py
Fixes publishes of single frame of `render` product type.
Files must be string not single element array.
1. set timeline to single frame
2. set `Frame range source`
=> Fusion: fix for single frame rendering

openpype/hosts/photoshop/plugins/publish/extract_review.py
Generation of .mov file with 1 frame per published layer was failing.
1. set `ayon+settings://photoshop/publish/ExtractReview?project=demo_Commercial` `Make an image sequence instead of flatten image`
2. 
3. publish workfile with multiple `image` instances
4. it shouldn't fail
=> Photoshop: fix creation of .mov

server_addon/photoshop/server/settings/publish_plugins.py, server_addon/photoshop/server/version.py
Fix for wrong default value for `Collect Color Coded Instances` Settings
1. build new Photoshop addon zip via `server_addons/create_package.py`
2. install it to Ayon server
3. try to set `ayon+settings://photoshop/publish/CollectColorCodedInstances`
=> Photoshop: fix Collect Color Coded settings

openpype/hosts/nuke/api/pipeline.py
Fixing issue where publisher parent window wasn't set because wrong use of version constant.
1. open Nuke
2. open Publisher
3. create new dialog in Nuke, like "render all write nodes..."
>[!note]
> Related issue: #6016
=> Bug: Fix Publisher parent window in Nuke

openpype/modules/ftrack/lib/custom_attributes.py, openpype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
Expect `ayon` group as one of options to get custom attributes.
This is necessary for testing AYON and OpenPype at the same time in ftrack.
=> AYON ftrack: Expect 'ayon' group in custom attributes

openpype/settings/defaults/project_settings/maya.json, server_addon/maya/server/settings/main.py
This is changing bug in default AYON setting for Maya workspace, where missing semicolumn caused workspace not being set. This is also syncing default workspace settings to OpenPype
1. start Maya on new asset
3. workspace values should be set correcty
=> Bug: fix AYON settings for Maya workspace

openpype/plugins/publish/integrate_thumbnail_ayon.py
Do not use `thumbnailSource` for thumbnail integration.
The value of `"thumbnailSource"` is what should be used as source for `"thumbnailPath"`, so it can be .exr, .mp4 etc. all of them are invalid for thumbnail. It looks like it was accidentaly used instead of thumbnailPath and nobody noticed...
I found out the logic how to determine what should be used as thumbnail is different in AYON and OpenPype integrator. Looks like the logic in OpenPype is quite old.
- Open traypublisher
- Select render
- Pass as source file mp4 and use the same mp4 for review
- Publish
- Integrate thumbnail will probably crash because mp4 is invalid file for thumbnail
1. Thumbnail publishing should work as expected
=> AYON Chore: Do not use thumbnailSource for thumbnail integration

openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
Multiple reviewable assetVersion components with better grouping to asset version name.
- Add a condition to also check if multiple_reviewable is True before updating the asset name.
1. very difficult to test but basically you need multiple reviewable representations marked as `ftrackreview`.
=> Ftrack: update asset names for multiple reviewable items

openpype/modules/python_console_interpreter/window/widgets.py
Do not save registry until there is something to save.
The addon logic tries to store last save registry even if console is not showed up at all, which may lead to confusing scenarios when `None` is stored as ideal width and height etc.
=> Python console widget: Save registry fix

openpype/scripts/ocio_wrapper.py, server_addon/openpype/client/pyproject.toml
Do not use `pathlib2` which is Python 2 backport for `pathlib` module in python 3.
Removed only usage in ocio wrapper which 100% will always run in python 3 (and contains python 3 syntax). Removed the dependency from openpype addon.
Don't know when is `ocio_warpper.py` used, but should still work with `pathlib`.
=> Editorial & chore: Stop using pathlib2

openpype/hosts/maya/api/lib.py
Unlock attributes only during the bake context, make sure attributes are relocked after to preserve the lock state of the original node being baked.
This is an implementation for https://github.com/ynput/OpenPype/pull/6073
Note that this now uses an `ExitStack` which is Python 2 incompatible, unless using a Py2 compatible ExitStack implementation. This PR implements one: https://github.com/ynput/OpenPype/pull/5942 so it might make sense to wait for that PR to merge and then use the same exit stack class.
1. See https://github.com/ynput/OpenPype/pull/6073
=> Maya: Fix bake to world space to preserve locked attributes state of original node

openpype/hosts/nuke/plugins/publish/extract_review_intermediates.py
Report in Discord https://discord.com/channels/517362899170230292/563751989075378201/1187874498234556477
n/a
1. Go to Settings, disabled both Extract Review Mov and Extract Review Intermediate in Nuke Publish
2. Launch Nuke
3. Create Render Instance
4. Publish
5. It won't show up the extract review intermediate
6. If you turn on either Extract Review Mov or Extract Review Intermediate, the extractor show up and the related setting applied to the extraction
7. If you turn on both settings, it will apply the setting from  Extract Review Mov
=> Nuke: Extract Review Intermediate disabled when both Extract Review Mov and Extract Review Intermediate disabled in setting

server_addon/openpype/client/pyproject.toml
Moved runtime dependencies from ayon-launcher to openpype addon.
This PR will be combination of PRs in multiple repositories (OpenPype, ayon-dependencies-tool, ayon-launcher).
- [ayon-launcher](https://github.com/ynput/ayon-launcher/pull/78)
- [ayon-dependencies-tool](https://github.com/ynput/ayon-dependencies-tool/pull/9)
- [OpenPype](https://github.com/ynput/OpenPype/pull/6095)
Testing notes are available in [ayon-launcher](https://github.com/ynput/ayon-launcher/pull/78).
=> AYON: OpenPype addon defines runtime dependencies

openpype/tools/sceneinventory/switch_dialog.py
When we switch only the representation type of subsets, we should not get the representation from the last version of the subset. 
1. Load a subset with several representation(any host)
2. Set version that is not the last existing version.
3. Switch the subset representation using the scene inventory.
4. Version should not change to the latest.
We could implement a version combobox selection to the switch dialog.
=> General: We should keep current subset version when we switch only the representation type

openpype/hosts/maya/plugins/load/load_redshift_proxy.py
When the published redshift proxy is being loaded, the shader of the proxy is missing. This is different from the manual load through creating redshift proxy for files. This PR is to assign the default lambert to the redshift proxy, which replicates the same approach when the user manually loads the proxy with filepath.
If there is a way of which we should get attributes of proxy materials in redshift proxy mesh, some conditions can be set up for assigning the shader if it exists in the scene. 
1. Launch Maya via launcher
2. Load redshift proxy
3. The shader of the redshift proxy is no longer in green (i.e. with no shader)
=> Maya: Apply initial viewport shader for Redshift Proxy after loading

pyproject.toml, setup.cfg
Fix [pydocstyle](https://www.pydocstyle.org/en/6.3.0/usage.html) configuration and move it to `pyproject.toml`
Run pydocstyle on any relevant python file
=> :wrench: fix and update pydocstyle configuration

openpype/pipeline/publish/lib.py, openpype/plugins/publish/integrate_hero_version.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, server_addon/core/server/settings/publish_plugins.py
Remove deprecated usage of template profiles from settings.
Removed template profiles from `IntegrateHeroVersion` plugin and stop using it. Also stop using `IntegrateAssetNew` templates (which are not available). Both settings are deprecated since 22.8.2022 (maybe even more).
=> Chore: Remove deprecated templates profiles

openpype/hosts/nuke/api/pipeline.py, openpype/tools/publisher/window.py
Don't use publisher window parent (usually main DCC window) as parent for report widget.
This caused issues with parenting. E.g. in older versions of nuke was the publisher empty on re-open.
1. Publisher should be possible to open multiple times in Nuke 13 and lower
=> Publisher: Fix issue with parenting of widgets

server_addon/openpype/client/pyproject.toml
Added `click` and `six` to requirements of openpype addon, and removed `Qt.py` requirement, which is not used anywhere.
Right now are the added requirements defined by ayon-launcher, but should be defined by openpype addon, as they are not used in ayon-launcher. The requirements must be first added to openpype before removing them from ayon launcher.
=> AYON: OpenPype addon dependencies

openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/plugins/create/create_camera.py
Creating instance fails for certain cameras, and it seems to only exist in Nuke 14. The reason of causing that contributes to the new camera node class `Camera4`  while the camera creator is working with the `Camera2` class.
n/a
1. Launch Nuke with a 3D scene where multiple cameras are created.
2. Create camera instances respectively with these cameras 
3. Publish
=> Nuke: Create camera node with the latest camera node class in Nuke 14

openpype/hosts/blender/plugins/create/create_workfile.py
Make sure workfile instance has always available 'instance_node' in transient data.
The instance node was available only if something had changed or the instance was created.
1. Launch blender
2. Open publisher tool
3. Save and Reset tool
4. There should not be any issue saving it
=> Blender: Workfile instance update fix

openpype/plugins/publish/collect_anatomy_instance_data.py, openpype/plugins/publish/collect_resources_path.py
Template data for editorial publishing are filled during `CollectInstanceAnatomyData`. The structure for editorial is determined, as it's required for ExtractHierarchy AYON/OpenPype plugins.
Right now the template data work only in TrayPublisher where context `"anatomyData"` do not contain current context, whereas in e.g. Hiero there is already filled asset so all instances will actually get filled wrong data, and files are integrated under editorial task.
This issue raised question: Should we allow to pass folder and task data from context to instances?
Do these steps in AYON/OpenPype and Hiero/TrayPublisher
1. Create new project (to have clean hierarchy in project management and files on disk).
2. Run hierarchy publishing on the project.
3. Validate that new hierarchy is created in …
=> Chore: Template data for editorial publishing

openpype/client/server/entity_links.py, openpype/tools/ayon_loader/models/site_sync.py, openpype/tools/ayon_sceneinventory/models/site_sync.py
Resolves issue:
- local and studio icons were same, they should be different
- `TypeError: string indices must be integers` error when downloading/uploading workfiles
1. enable Site Sync for your project (must be enabled in Studio settings and Project Settings too!)
2. set in Local settings `active_site` to 'local' and `remote_site` to 'studio`
3. check Availability icons in Ayon Loader
4. try do download workfile
=> Site Sync: small fixes in Loader

openpype/modules/kitsu/utils/credentials.py
Do not remove not existing keyring items.
1. Enable kitsu and setup url
2. Make sure you don't have existing kitsu login in keyring (credentials manager on windows)
3. Start tray and open kitsu login dialog
4. Uncheck `Remember` checkbox
5. Login
6. It should not crash
Resolves https://github.com/ynput/OpenPype/issues/6115
=> Kitsu: Clear credentials is safe

openpype/tools/ayon_sceneinventory/control.py, openpype/tools/ayon_sceneinventory/model.py, openpype/tools/ayon_sceneinventory/models/site_sync.py
Use 'get_qt_icon' to convert icon definitions from site sync.
1. SiteSync icons should be showed in SceneManager tool
=> SceneInventory: Fix site sync icon conversion

openpype/plugins/publish/extract_thumbnail_from_source.py
Add thumbnail output name to thumbnail representation to prevent same output filename during integration.
This is common issue when source file is `jpg` file (e.g. in traypublisher), in that case the thumbnail representation has same output file for integration which causes `Transfer to destination is already in queue:` error.
1. Drop jpg file to traypublisher (e.g. image family) and the same file use as reviewable (or thumbnail)
2. Publish.
3. It should not crash.
NOTE; I didn't try to fill both thumbnail and reviwable, not sure what will actually happen.
=> Chore: Thumbnail representation has 'outputName'

openpype/lib/transcoding.py
When transcoding image sequences, the second image onwards includes the invalid xml line of `Reading path/to/file.exr` of the oiiotool output.
This is most likely not the best solution, but it fixes the issue and illustrates the problem.
Error:
```
ERROR:pyblish.plugin:Traceback (most recent call last):
File "C:\Users\tokejepsen\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
runner(*args)
File "C:\Users\tokejepsen\OpenPype\openpype\plugins\publish\extract_color_transcode.py", line 152, in process
File "C:\Users\tokejepsen\OpenPype\openpype\lib\transcoding.py", line 1136, in convert_colorspace
input_info = get_oiio_info_for_input(input_path, logger=logger)
File …
```
=> Transcoding: Fix reading image sequences through oiiotool

openpype/tools/utils/lib.py
Minor fix in tool utils to make sure style C++ object is not garbage collected when not stored into variable.
```
File "some_test", line 1, in <module>
File "C:\OpenPype\openpype\hosts\houdini\api\lib.py", line 1056, in self_publish
publisher_show_and_publish(comment)
File "C:\OpenPype\openpype\hosts\houdini\api\lib.py", line 976, in publisher_show_and_publish
publisher_window = get_tool_by_name(
File "C:\OpenPype\openpype\tools\utils\host_tools.py", line 416, in get_tool_by_name
return _SingletonPoint.get_tool_by_name(tool_name, parent, *args, **kwargs)
File "C:\OpenPype\openpype\tools\utils\host_tools.py", line 411, in get_tool_by_name
return cls.helper.get_tool_by_name(tool_name, parent, *args, **kwargs)
File …
```
=> Chore tools: Make sure style object is not garbage collected

openpype/modules/base.py
Do not add addons directory path for addons discovery if does not exists.
The main reason is that this folder is causing warning log which is confusing for users.
```
*** WRN: >>> { ModulesLoader }: [  Could not find path when loading OpenPype modules "C:\Users\USER\AppData\Local\Ynput\AYON\addons\openpype_3.18.4-nightly.1\openpype\addons"  ]
```
1. The warning should not appear anymore
=> Chore: Add addons dir only if exists

openpype/lib/transcoding.py
Image extensions in transcoding helper was missing `.tif` extension and had `.tiff` twice.
Reorganized extensions a little to be alphabetically sorted.
=> Chore: Transcoding extensions add missing '.tif' extension

openpype/hosts/blender/plugins/load/load_blend.py
Restore the actions assigned to objects after updating assets from blend files.
1. Assign a new action to any loaded object in the scene.
2. Update that asset.
3. The objects should still have the action assigned after the update.
=> Blender: Restore actions to objects after update

openpype/hosts/blender/api/capture.py, openpype/hosts/blender/plugins/load/load_audio.py, openpype/hosts/blender/plugins/publish/extract_abc_animation.py, openpype/hosts/blender/plugins/publish/extract_camera_fbx.py, openpype/hosts/blender/plugins/publish/extract_fbx.py, openpype/hosts/blender/plugins/publish/extract_fbx_animation.py, openpype/hosts/blender/plugins/publish/extract_layout.py
Blender 4.0 disabled the old API to override context. This API updates the code to use the new API.
This change is compatible with Blender versions up to 3.2. Previous versions are not compatible with this new API.
In Blender 4.0:
1. Test FBX and Alembic extractors.
2. Test load audio.
3. Test Review extraction.
=> Blender: Use the new API for override context

openpype/plugins/publish/collect_anatomy_instance_data.py, openpype/plugins/publish/extract_hierarchy_to_ayon.py
Fixed queue loop where is used wrong variable to pop items from queue.
Also create copy of hierarchy context to be sure it is not modified during the loop in any way (just to be sure for possible future changes), and don't store 'hierarchyContext' to variable when checking if is set.
1. Anatomy data should be filled correctly during editorial publishing when new folders/assets are created.
=> Chore: Collect template data with hierarchy context

openpype/tools/publisher/control.py, openpype/tools/publisher/publish_report_viewer/model.py, openpype/tools/publisher/publish_report_viewer/window.py
Proposal of items sorting in Publish report viewer tool. Items are sorted by report creation time. Creation time is also added to publish report data when saved from publisher tool.
For older report items is used file modification time as 'created_at'. Possible issues with this approach is that new dropped report may not be as last but in the middle, which may not be ideal. ISO timestamp should be probably used instead of "current timezone" timestamp.
1. Add 'stored_at' information when report file is dropped to the UI, and use the 'stored_at' for sorting instead.
2. Completelly ignore value (column) sorting but use "custom sorting". User can manually move items around and `int` with sort value is stored for each item.
- New reports from publisher contain 'created_at'.
1. Open Publish …
=> Publish report viewer: Report items sorting

openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py, openpype/plugins/publish/extract_color_transcode.py, openpype/plugins/publish/extract_thumbnail.py
This ticket alerted to 3 different cases of integration issues;
There might be an issue with this fix, if a studio does not use the `{output}` token in their `render` anatomy template. But thinking if they have customized it, they will be responsible to maintain these edge cases.
1. Use Tray Publisher to publish `Image` with two different images of same extension.
2. Publish should succeed.
1. Setup `ayon+settings://core/publish/ExtractOIIOTranscode/profiles` with settings below.
2. Setup single frame render from Maya and publish to Deadline.
3. Publish on Deadline should succeed.
1. Setup `ayon+settings://core/publish/ExtractOIIOTranscode/profiles` with settings below (just adding `review` tag from above settings).
2. Setup single frame render from Maya and publish to Deadline.
3. …
=> OP-6382 - Thumbnail Integration Problem

openpype/hosts/maya/plugins/publish/validate_scene_set_workspace.py
Added more details to message
Previous message was "suboptimal" (as is marked to be solvable by artists):
Hopefully this one is a bit better:
1. try to publish workfile which is in incorrect folder
=> Maya: Extended error message

openpype/hosts/blender/plugins/load/load_blend.py
Fix missing animation data when updating blend assets.
There was a specific case when updating assets that were published without animation. If an animation was added after them being loaded, when updating it would throw an error.
1. Load an asset that is without any animation data (it must **not** have any animation in the outline when loaded).
2. Add an animation to that asset.
3. Try to update the asset.
=> Blender: Fix missing animation data when updating blend assets

openpype/pipeline/workfile/workfile_template_builder.py
Use correct variable where failed instances are stored for validation.
Current implementation was using `_failed_representations` which was copied from load, but should use `_failed_created_publish_instances`.
Not sure how to test. Probably cause an error of create placeholder during workfile template builder.
=> Workfile Template Builder: Use correct variable in create placeholder

openpype/hosts/traypublisher/api/plugin.py
Use `folderPath` instead of `asset` in AYON mode to calculate next available version.
1. Publish something on Traypublisher
2. Click `reload` icon
=> TrayPublisher: Pre-fill of version works in AYON

openpype/settings/ayon_settings.py
Make sure the bundle name is used in dev mode for settings variant.
Bundle name was used as variant only if was assigned to current user which broke most of automations where service users were used.
1. Use dev bundle name for automation where service API key is used (e.g. on farm).
2. It should not crash on settings call where would be variant `"dev"`.
=> AYON settings: Use bundle name as variant in dev mode

openpype/hosts/photoshop/api/lib.py
Use `get_openpype_qt_app` to create `QApplication` in Photoshop.
Function 'get_openpype_qt_app' prepares `QApplication` a little bit better for scaling.
This can be visibly tested only on windows machine with enabled scaling (e.g. 150%).
1. Launch Photoshop
2. UIs should be scaled a little bit better
=> Photoshop: High scaling in UIs

openpype/modules/ftrack/launch_hooks/post_ftrack_changes.py
Make values for project_settings/ftrack/events/status_update case insensitive.
1. `project_settings/ftrack/events/status_update` changes values to cases different to what is in Ftrack or go nuts with cases.
2. When launching a task action, the status should still update as expected.
=> Ftrack: Status update settings are not case insensitive.

openpype/lib/transcoding.py
Customer provided .exr returned width and height equal to 0 which caused error in `extract_thumbnail`. This tries to use oiiotool to get metadata about file, in our case it read it correctly.
This PR is a bit weird as it solves very specific use case, which could be reoccurring though as source `.exr` comes from Deadline render from Maya and it is not supposed to be special. This update provide just one more layer of safety.
1. test on customer site OR
2. use attached test file from Clickup issue and run this in `Tray > Console`:
```
from openpype.lib.transcoding import  get_rescaled_command_arguments
input_path = "FILE_PATH"
args = get_rescaled_command_arguments("oiiotool", input_path, 1900, 1200)
print(args )
```
=> General: added fallback for broken ffprobe return

server_addon/applications/server/applications.json
The djv does not have group defined in models so the values are not used anywhere.
Values were probably remainders after movement of the settings from OpenPype. DJV has own addon with own path settings. Version change is not necessary as this change does not affect anything in the addon.
Validate that any applications addon before this PR did not have djv in UI.
1. Create packages
2. Upload applications addon
3. Validate nothing changed
=> AYON Applications: Remove djvview group from default applications

openpype/hosts/fusion/api/menu.py, openpype/tools/utils/__init__.py, openpype/tools/utils/lib.py
Changes size (makes it smaller) of Ayon apps (Workfiles, Loader) in Fusion on high definitions displays.
Special get_qt_app is used instead of shared get_openpype_qt_app as we don't want to set application icon.
=> Fusion: Use better resolution of Ayon apps on 4k display

openpype/tools/publisher/control.py, openpype/tools/publisher/window.py
This PR adds support for the publisher to show error message from running actions.
Errors from actions will otherwise be hidden from user in various console outputs.
Also include card for when action is finished.
Not sure about a simpler test case, so this where I caught it.
1. Checkout #6137
2. Merge this PR into the checked out PR.
3. In `ayon+settings://nuke/create/CreateWriteRender/exposed_knobs` enter an invalid knob name like `create_directo`.
4. Create `render` in Nuke. Error will appear about missing knob.
5. Delete knob `create_directo` on the created instance node.
6. Validate and run repair action. Error message should appear.
=> Publisher: Show message with error on action failure

openpype/modules/timers_manager/timers_manager.py, openpype/modules/timers_manager/widget_user_idle.py
Make stop timer dialog always on top
https://app.clickup.com/t/6658547/OP-8033
1. leave system idle for a long time
2. wait for idle popup dialog
=> TimersManager: Idle dialog always on top

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/settings/defaults/project_settings/aftereffects.json, openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json, server_addon/aftereffects/server/settings/creator_plugins.py, server_addon/aftereffects/server/version.py
Previously values (resolution, duration) from Asset (eg. DB) were applied explicitly when instance of `render` product type was created. 
This PR adds toggle to Settings to disable this. (This allows artist to publish non standard length of composition, disabling of `Validate Scene Settings` is still required.)
Added only to Settings and not Publisher UI currently. I think it would add too much clutter.
This is mainly target for legacy OP per specific client request.
1. play with `project_settings/aftereffects/create/RenderCreator/force_setting_values` value
2. create instance in AE
3. check if duration got/didn't get applied to composition (RMB on comp > Composition Settings)
=> AfterEffects: added toggle for applying values from DB during creation

openpype/hosts/nuke/api/plugin.py
Fix backwards compatibility for settings `project_settings/nuke/create/CreateWriteRender/exposed_knobs`.
1. In Nuke create a write instance.
=> Nuke: expose knobs backward compatibility fix - OP-8164

openpype/plugins/publish/extract_thumbnail.py
Without thumbnail review is not clickable from main Versions list
1. render from AE locally 
2. render from AE on farm
3. both reviews on Ftrack should be clickable and playable directly from Versions list
=> AE: fix local render doesn't push thumbnail to Ftrack

openpype/hosts/nuke/plugins/publish/validate_exposed_knobs.py
Fix exposed knobs validator for backwards compatibility with missing settings.
1. Create write instance in Nuke.
3. Publish and check validator run successfully.
=> Nuke: openpype expose knobs validator - OP-8166

openpype/hosts/max/api/pipeline.py
AYON plugins are not correctly registered when switching to different workspaces.
n/a
1. launch Max via launcher
2. Open a workfile
3. Switch different workspace
4. Try to publish/load everything to see if it succeeds.
=> Bugfix: AYON menu disappeared when the workspace has been changed in 3dsMax

openpype/hosts/unreal/plugins/publish/collect_render_instances.py
Fix Render Instance Collector to use folderPath instead of just the asset name.
This was causing the `ValidateSequenceFrames` validator to fail because couldn't find the asset data in the database.
=> Unreal: Fix Render Instance Collector to use folderPath

openpype/hosts/hiero/plugins/publish/collect_clip_effects.py, openpype/settings/defaults/project_settings/hiero.json, openpype/settings/entities/schemas/projects_schema/schema_project_hiero.json
Missing settings for https://github.com/ynput/OpenPype/pull/6143.
1. Setup `Effect Categories` in Hiero addon settings (see documentation); `project_settings/hiero/publish/CollectClipEffects/effect_categories`
2. Setup a clip in Hiero with effects corresponding to the settings.
3. Publish clip and effects.
4. Load into Nuke and verify the effects are grouped correctly.
=> Hiero: Add OP settings and convert in plugin - OP-8338

openpype/hosts/nuke/plugins/publish/collect_slate_node.py, openpype/hosts/nuke/plugins/publish/collect_writes.py
Due to `frameStart` data member on representation for existing frames, the frame indexes would be re-numbered when integrating due to this; https://github.com/ynput/OpenPype/blob/develop/openpype/plugins/publish/integrate.py#L712-L726
Removing `frameStart` had no effect on publishing workflows, local or farm.
Also fixed an issues with slate collection which could misbehave if the instance node had "slate" in the name.
Resolves #5883
1. Add nuke slate to the script
2. Publish render using local machine rendering
3. Publish render with `Use existing frames` option (will reuse render from previous step)
4. Check integration logs where it copied files to publish destination, which should keep frame indexes intact. Looks like this:
```
Copying file ... …
```
=> Nuke: render use existing frames with slate offsets the published render - AY-1433

openpype/tools/ayon_workfiles/control.py
Fix copy and open published workfiles.
The button just saved as current workfile instead of using the representation path.
1. Make sure a workfile is published.
2. Launch the host/dcc.
3. Open workfiles tool.
4. Check `Published workfile` checkbox.
5. Select published workfile and click `Copy & Open` button.
6. It should copy and open the file.
=> AYON Workfiles tool: Copy and open of published workfile works

openpype/pipeline/colorspace.py, openpype/scripts/ocio_wrapper.py
Nuke 12 is now fully supported with our OCIO wrapping functionalities. 
1. Open Nuke 12 and publish render reviewable
2. nothing should stop you!
=> Chore: OCIO and python2 compatibility fixes

openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py, openpype/modules/deadline/plugins/publish/submit_publish_cache_job.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py
Use get env to get the value of `AVALON_DB`
`AVALON_DB` environment variable is not initialized when using OpenPype in Ayon mode. 
which raise an error when using `os.environ["AVALON_DB"]`
This PR changes it to `os.getenv("AVALON_DB")` 
1. Open a dcc
2. Publish a render, publisher shouldn't complain about  `AVALON_DB` being non exist.
=> Deadline: Submit Publish job error

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/plugins/create/create_arnold_scene_source.py, openpype/hosts/maya/plugins/load/load_arnold_standin.py, openpype/hosts/maya/plugins/publish/collect_arnold_scene_source.py, openpype/hosts/maya/plugins/publish/extract_arnold_scene_source.py, openpype/hosts/maya/plugins/publish/validate_arnold_scene_source.py, openpype/hosts/maya/plugins/publish/validate_arnold_scene_source_cbid.py, openpype/plugins/publish/integrate.py
This PR is to try and re-instate some flexibility to the `Arnold Scene Source` family, which got restricted by https://github.com/ynput/OpenPype/pull/4449
The proxy workflow introduced was actually broken due to https://github.com/ynput/OpenPype/pull/4460.
We can now have any nodes directly in the instance set, which should be backwards compatible of the `Arnold Scene Source` before the overhaul in https://github.com/ynput/OpenPype/pull/4449.
The `content` and `proxy` sets works as well, but not at the same time as the raw nodes directly in the instance set. There is a validator in place to prevent using a single instance for both workflows.
Now the question is whether we should have this as a single family or split somehow?
The workflow of having nodes directly in the instance set, …
=> Arnold Scene Source Raw - OP-8014

openpype/hosts/maya/plugins/publish/extract_pointcache.py
Fix for if no overrides are present in `project_settings/maya/publish/ExtractAlembic/overrides`
1. Remove all overrides from `project_settings/maya/publish/ExtractAlembic/overrides`.
2. In Maya create a model.
=> Maya: Account for no Alembic overrides.

openpype/hosts/maya/plugins/publish/extract_unreal_yeticache.py
Fix duplicate `ExtractYetiCache` plug-in name.
I mentioned [that issue on Discord a while back](https://discord.com/channels/517362899170230292/517382145552154634/1181190681490894858)
Likely also fixes this community topic: https://community.ynput.io/t/yeticache-error-in-3-18-7/1323/5
Ayon equivalent: https://github.com/ynput/ayon-core/pull/251
1. Extract Yeti cache should work.
2. Extract Yeti cache to unreal should work.
=> Maya: Ensure unique class name compared to `extract_yeti_cache.py`

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/extract_review_slate.py, openpype/plugins/publish/extract_thumbnail.py
Escape parenthesis for shell subprocess when `bash` or `sh` are set as shell applications.
Content of parenthesis is "executed" in bash so it is necessary to escape them. This was discovered when thumbnail extraction should change resolution and command contained something like `(1920-iw)`.
I don't know. It requires linux machine and specific settings and case.
=> Chore: Parenthesis in shell
