pype/nuke/lib.py, pype/plugins/nuke/publish/extract_review_data_mov.py
- controlling the output colorpace for baking mov video files used in extract review files generation by ffmpeg 
- there is 3 ways of approaching colorspace output. Default which was used before OCIODispay - defined by workfile or shot defined used OCIOColorspace or backuped fallback colorspace in case the shot definition is missing in config.ocio on a shot. 
testing this is bit difficult but I will try to explain:
1. download the pack from issue ticket:
2. set your colorspace presets this way:
```
"root": {
"colorManagement": "OCIO",
"OCIO_config": "custom",
"customOCIOConfigPath": "C:/Users/jezsc/_PYPE_testing/dazzle_custom_config_ocio/config.ocio",
"workingSpaceLUT": "ACEScg",
"defaultViewerLUT": "OCIO LUTs",
"monitorLut": "rec709/oou_neutral",
"int8Lut": "sRGB",
"int16Lut": "sRGB", …
```
=> PYPS-82 configure baked mov colorspace

pype/plugins/global/publish/submit_publish_job.py, pype/scripts/publish_filesequence.py
This PR is setting `AVALON_PROJECT` by environment rather then later reading it from json file. That was breaking publishing on linux when project was submitted on windows.
=> set avalon project on publish job by environment variable

pype/plugins/maya/publish/validate_rendersettings.py
Using `RenderPass` token with Redshift in *image prefix* is breaking render publishing.
Redshift is appending AOV name to image prefix automatically if AOVs are enabled. Explicitly stating image prefix will double it in resulting name:
```
<RenderLayer>/<RenderLayer>_<RenderPass>
```
will result in
```
Main/Main_N.N.0001.exr
```
It will also not work when multipart EXRs are enabled and in that context it doesn't even make sense.
This PR is modifying render settings validator to trigger when `<RenderPass>` token is found in image prefix for Redshift.
=> PYPE-778: [Maya][Redshift] - RenderPass token breaks render publishing

pype/plugins/maya/publish/collect_scene.py
If workfile was published Pype didn't check for its type. It forcefully published it as maya ASCII file (ma). This resulted in published file with wrong extension and maya unable to open it.
This PR is changing it so we set scene type by the current one
=> preserve mb file type during publish

pype/plugins/maya/publish/extract_playblast.py
* Changed misleading name to `extract_playblast`
* fps is taken from instance or context
* Camera options are taken now from capture preset
* rendering is forced to png instead of jpg
:warning: **requires PR**: pype-config now includes values previously hardcoded in plugin
=> PYPE-753 maya extract review refactor

pype/plugins/maya/publish/collect_scene.py
Previous PR was based on different code and is now missing maya.cmds as import. This is fixing it. Needs to be merged to develop too.
=> fixed missing import for previous PR

pype/plugins/maya/load/load_yeti_cache.py, pype/plugins/maya/publish/collect_yeti_cache.py
**Yeti Cache loader** was handling paths to _cache_ and _fursettings_ file manually, guessing location of one from other. Yeti cache files and fursettings are now two representations of one version.
This PR is taking paths from avalon now so version updates (and switching works).
=> PYPE-743: fixing yeti cache version updates

pype/plugins/global/publish/submit_publish_job.py
This is passig `PYPE_PYTHON_EXE` environment variable to farm jobs (if set). Also setting `PYPE_LOG_NO_COLORS` for farm job as output coloring doesn't make much sense in deadline/muster logs.
Depends on pypeclub/pype-setup#19
=> passing PYPE_PYTHON_EXE to farm jobs

pype/plugins/nuke/create/create_write_prerender.py, pype/plugins/nuke/create/create_write_render.py
No nodes selected case was not handled so users get a cryptic error message:
```
File "K:\pype-setup\repos\avalon-core\avalon\pipeline.py", line 994, in create
instance = plugin.process()
File "<string>", line 52, in process
IndexError: list index out of range
File "K:\pype-setup\repos\avalon-core\avalon\tools\creator\app.py", line 493, in on_create
options={"useSelection": use_selection})
File "K:\pype-setup\repos\avalon-core\avalon\pipeline.py", line 1000, in create
assert plugins, "No Creator plug-ins were run, this is a bug"
AssertionError: No Creator plug-ins were run, this is a bug
```
Now users get an error message box with:
```
No nodes selected. Please select a single node to connect to or tick off `Use …
```
=> Warn users about no nodes selected.

pype/plugins/maya/publish/collect_render.py
When objects attached to the render layers do not have family the collection would error out.
This happened for me when having a material override in a render layer.
=> Fix render collection

pype/plugins/global/publish/integrate_new.py
During copy phase we are not properly handling cases when copying fails. Thus we only get system error after unsuccessful publish fails and that doesn't include information about files.
This PR is catching **OSError** and is outputting to log more stuff.
=> Integrate: handle errors during file copy

pype/nuke/lib.py
See line 396
- also some code cosmetics.
=> Expose write node frame range and limit checkbox.

pype/plugins/maya/publish/collect_render.py
Attribute overrides for AOV only works for the legacy render layers, because the render setup do not connect to the attributes.
=> AOV toggling was not collected correctly.

pype/plugins/fusion/publish/submit_deadline.py, pype/plugins/maya/publish/submit_maya_deadline.py, pype/plugins/nuke/publish/submit_nuke_deadline.py
When working remotely the submission to Deadline is immediate but the files might not have synced between sites.
We add just the scene file for now, but later might wanna add other file dependencies.
=> Deadline wait for scene file to sync.

pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/submit_maya_deadline.py, pype/plugins/nuke/publish/submit_nuke_deadline.py
When deadline web service is not working properly, connection can take forever - deadline will not terminate connection with status code. This will block whole publishing process and freeze host completely (as requests is blocking operation)
Add `timeout` to request. Set to 10sec as this seems like reasonable value.
=> add timeout on request to deadline

pype/plugins/maya/publish/submit_maya_deadline.py, pype/plugins/nuke/publish/submit_nuke_deadline.py
This will pass PYPE_DEV to Deadline job so subsequent processes can know if we are in staging or development branch,
Relates to pypeclub/pype-setup#25
=> pass PYPE_DEV to deadline job

pype/plugins/global/publish/extract_burnin.py, pype/plugins/global/publish/extract_jpeg.py, pype/plugins/global/publish/extract_review.py
ffpmeg is not supporting multipart exrs therefor we introduced `multipartExr` property to pass that information down the line so extractor avoid running ffmpeg against those data.
Unfortunately those extractors were looking for it in wrong place - in tags on representation, but should look instead at instance data.
This bug resulted in inability to publish renders with multipart exrs as ffmpeg always crashed.
=> fixed condition for multipartExr

pype/plugins/nuke/publish/collect_writes.py
At the moment when we are publishing from render.local and render.farm the published main family is render2d but if we are rendering from already rendered frames the main published family is write. This will fix it to render2d for better consistency.
=> nuke family `render2d` if published from imgsequence

pype/plugins/harmony/load/load_template.py, pype/plugins/harmony/publish/collect_instances.py, pype/plugins/harmony/publish/extract_template.py
- other nodes within the bounding box of the backdrops are published as well, cause non-connected notes can be used to communicate to the end user.
- not publishing templates to ftrack.
resolves https://github.com/pypeclub/fourthwall-config/issues/9
=> Publish backdrops with templates.

pype/plugins/nuke/publish/validate_script.py
In a pinch users need to be able to ignore the script validation to get a shot out.
=> Optional script validation

pype/plugins/maya/publish/collect_look.py
When Arnold is not enabled in Maya, collect look will fail because of missing connection it is looking for (like `aiShader*` stuff).
This fix force collector to skip silently those invalid connections.
=> Maya - Look: Skip invalid connections

pype/plugins/blender/create/create_layout.py, pype/plugins/blender/load/load_layout.py, pype/plugins/blender/publish/extract_blend.py
This PR implements the layout asset for Blender.
=> Layout asset for Blender

pype/plugins/maya/publish/extract_animation.py
We interpret frame as *int*, but queries in Maya ofter return frames as *float*. This bug happens in `extract_animation.py` when handles are 0. Then frame range is picked from context (where it is as *int*) and `pype.hosts.maya.lib.extract_alembic()` asserts will fail as they are expecting *float* from Maya.
Fix is casting explicitly frames to float before passing them to `extract_alembic()`.
=> Maya: export alembic start/end frame type

pype/plugins/global/publish/validate_custom_ftrack_attributes.py
Because Standalone publisher does not have any Ftrack context, we ignore the host in this plugin.
=> Ignore standalone host.

pype/plugins/maya/publish/validate_transform_naming_suffix.py
Clicking on *repair action* resulted in crash - action called `get_invalid(cls, instance)` but method signature in plugin was `get_invalid(cls, instance, SUFFIX_NAMING_TABLE, ALLOW_IF_NOT_IN_SUFFIX_TABLE)`
=> Maya: validator: Suffix Name Conventions - invalid method signature

pype/hooks/premiere/prelaunch.py, pype/hosts/premiere/__init__.py, pype/hosts/premiere/extensions/com.pype/jsx/batchRenamer.jsx, pype/hosts/premiere/ppro/index.html, pype/hosts/premiere/ppro/js/pype.js
- client request for workfiles to be having own anatomy template defined per task
- change of renaming tool look and behavior
To test this PR just add:
```
work[conforming]:
folder: "{root[production]}/{project[name]}/{hierarchy}/{asset}/work/{task}"
file: "{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"
path: "{@folder}/{@file}"
```
into `pype-config/anatomy/default.yaml` (notice task name key work also root[production]).
=> premiere workfile root per task (multi-root)

pype/plugins/harmony/load/load_imagesequence.py
closes https://github.com/pypeclub/fourthwall-config/issues/21
=> Load imagesequence.

pype/plugins/photoshop/create/create_image.py, pype/plugins/photoshop/publish/validate_naming.py
When using the selection in Photoshop for instance creation, you can now use existing folders. Using the selection has the following features:
- No selection creates an empty folder.
- Single item selection
- Existing group will be used.
- Layer will be grouped.
- Multiple items selection
- User gets asked whether to create one group for all or individual groups.
- If creating individual groups, then each item in selection gets treated as "Single item selection".
closes https://github.com/pypeclub/fourthwall-config/issues/24
=> Using existing items  for instances.

pype/hosts/maya/expected_files.py, pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/submit_maya_deadline.py, pype/plugins/maya/publish/validate_rendersettings.py, pype/plugins/maya/publish/validate_vray_translator_settings.py
This PR includes various fixes for bugs preventing sucessful render of Vray scenes on Deadline.
- it is fixing output paths
- moving deadline python plugin python version to class attribute so it can be configured by preset
- removing `PYPE_PYTHON_EXE` from passed variables to job as it was braking Pype self-installing
- fixing Vray file extension detection
=> fixing vray rendering on deadline

pype/modules/ftrack/lib/ftrack_app_handler.py
Environment variables from tools are appended to existing environment. This behaviour is causing troubles for those variables that are not meant to have multiple values.
**For example:**
You have system-wide variable:
```
OCIO="/path/to/ocio.config
```
and tool environment file **foo.json**:
```javascript
{
"OCIO": "/foo/bar/ocio.config"
}
```
this will result in `OCIO="/path/to/ocio.config:/foo/bar/ocio.config"` and that is invalid.
This PR is disabling this behaviour the same way as we did it for application environments. So if we need to append some variable to another, we have to explicitly state so;
```javascript
{
"PATH": ["/some/path", "{PATH}"]
}
```
🏴 similar PR is made in pypeclub/avalon-core#161
|---|
=> stop appending of tools environment to existing env

pype/modules/ftrack/ftrack_server/socket_thread.py
I'm not sure how to tackle this. A client user was having issues with the current timeout, so just increasing it solved the issue.
Should this maybe be configurable or look at something like `AVALON_TIMEOUT`?
=> Increase socket thread timeout.

pype/plugins/maya/publish/validate_instance_in_context.py
in situations where studio is working on per-shot basis they almost exclusively publish data in the same context as scene is. This **optional** validator validates if instance belongs to scene asset to prevent for example publishing of animation to different shot.
Validator will selected all invalid instances.
=> validator for Maya: check if instances asset matches context asset

pype/plugins/celaction/publish/collect_render_path.py, pype/plugins/celaction/publish/submit_celaction_deadline.py, pype/plugins/global/publish/integrate_new.py, pype/plugins/global/publish/submit_publish_job.py
- fixing CelAction render paths to be separated for rendering and publish render (client wants to separate targets for optimalisation of rendering). This publishing path is then passed in instance.data for later Global submiter to use it in metadata json file creation
- rewriting the way metadata json file path is created in global submitter to farm
- make file paths slashes consistent
- fixing the `shutil.SameFileError` error in integrate_new which is perhaps related to Google Drive Stream storing mechanism
=> celaction deadline rendering

pype/lib.py, pype/modules/ftrack/actions/action_application_loader.py, pype/modules/ftrack/actions/action_clean_hierarchical_attributes.py, pype/modules/ftrack/actions/action_create_cust_attrs.py, pype/modules/ftrack/actions/action_delivery.py, pype/modules/ftrack/actions/action_prepare_project.py, pype/modules/ftrack/actions/action_store_thumbnails_to_avalon.py, pype/modules/ftrack/events/event_del_avalon_id_from_new.py, pype/modules/ftrack/events/event_sync_to_avalon.py, pype/modules/ftrack/events/event_user_assigment.py, pype/modules/ftrack/lib/__init__.py, pype/modules/ftrack/lib/avalon_sync.py, pype/modules/ftrack/lib/custom_attributes.json, pype/tools/pyblish_pype/model.py
- In config is possible to define applications, tools usage and intent values available for studio. (apps and tools with boolean)
- definition of custom attributes is not in pype-config anymore
- in pype-config can be set only read/write permissions and default values (OPTIONALLY!!!)
- Structure of custom attributes has changed.
- Instead of list it is a dictionary with "entity type" at first level and it's definition as value.
- Second level for "object type" is required if "entity type" is `"task"` (Not used in with current attributes).
- applications and tools attributes are registered by boolean in global apps and tools presets
- application label is used from application's toml file
- intent values are filled with global intent values (except empty value and default value)
- Ftrack …
=> simplify apps and tools configuration

pype/plugins/maya/publish/extract_camera_alembic.py, pype/plugins/maya/publish/extract_camera_mayaAscii.py
When exporting camera (either as maya scene or alembic) custom attributes can be specfied to bake into the file. It can be done using standard preset way:
**maya/publish.json:**
```javascript
{
"ExtractCameraMayaAscii": {
"bake_attributes": ["vrayCameraPhysicalFocusDistance"]
},
"ExtractCameraAlembic": {
"bake_attributes": ["vrayCameraPhysicalFocusDistance"]
}
}
```
This will add baked **vrayCameraPhysicalFocusDistance** to camera.
🌞 **Freshdesk ticker**: [#27](https://pype.freshdesk.com/a/tickets/27)
|---|
=> Maya: bake custom attributes to camera during export

pype/hosts/maya/expected_files.py
When publishing renders with camera `<camera>` token and renderable camera name containing invalid characters, Maya will render them correctly but publishing script will expect path with original (and invalid) camera name in. This is mainly case when camera has namespace prefix in its name.
This PR introduce camera name sanitizing, replacing all non-alphanumeric characters except underscore with underscore.
🎫 **Freshdesk ticket ID**:  [#61](https://pype.freshdesk.com/a/tickets/61)
|---|
=> Maya: camera names in render - invalid characters

pype/plugins/maya/load/load_rendersetup.py
Our render setup instance implementation was fast and dirty, allowing loading but nothing more. This PR adds ability to update and remove instance. It will show notification about overwriting all user modifications on render setup that are not published.
🎫 **Freshdesk ticked ID:** [#65](https://pype.freshdesk.com/a/tickets/65)
|---|
=> Maya: render setup update and removal implementation

pype/plugins/global/publish/cleanup.py
cleanup plugin was printing some non informative output to log. Also it was checking directory existence before much quicker and more frequently kicking-in filter was runned. This PR is fixing all this.
=> Publish: Cleanup plugin code optimization

pype/hosts/harmony/__init__.py
When publishing workfiles from Harmony, publishing process could be stuck for minutes (or would time out after 2 is timeout limit wasn't changed). This was because `copyPase.pasteNewNode(...)` creating tons of undo/redo points. This PR is merging whole *extract template* operation as one item for undo/redo system, dramatically reducing publishing speed to seconds.
=> Harmony: publishing performance issues

pype/modules/ftrack/actions/action_delete_old_versions.py
- option to only calculate without deletion
=> Calculate size

pype/scripts/otio_burnin.py
- output from burnin script has wrong keyframes
- add ffmpeg argument `-g 1` (replacement of deprecated `-intra`) in burnin script so output should have right keyframes
- @jezscha can you test it as you have ready testing data
- @mkolar PR is to master, is it OK?
=> change deprecated -intra parameter in ffmpeg to new `-g`

pype/plugins/global/publish/cleanup.py
This PR fixes cleanup plugin so it won't fail on instances withou staging dir set.
=> Cleanup plugin fail on instances without staging dir

pype/plugins/harmony/publish/validate_scene_settings.py
Fixing invalid variable scope in validator.
=> Harmony: invalid variable scope in validate scene settings

pype/modules/ftrack/events/event_task_to_version_status.py
- Task to version status Ftrack event handler
- By default is turned off must have set attribute value in presets
- Attribute `asset_types_of_focus` can be set in `~/presets/ftrack/plugins/server.json` with adding
```
{
...
"TaskToVersionStatus": {
"asset_types_of_focus": ["render", ...]
}
...
}
```
=> Ftrack: Option to push status from task to latest version

pype/plugins/maya/create/create_review.py, pype/plugins/maya/publish/extract_playblast.py, pype/plugins/nuke/load/load_sequence.py
- Disabled by default to maintain backwards compatibility.
- Open loading review image sequences into Nuke.
=> Option to keep the review files.

pype/plugins/global/publish/integrate_new.py, pype/plugins/global/publish/submit_publish_job.py
Stop integrating representation if they are having `delete` tags in them to lower network / internet trafic
=> add ability to skip integration of rendered frames

pype/modules/ftrack/actions/action_thumbnail_to_parent.py
Assetversion was not found when its not linked to a task. assetversion["task"] returns None instead of raising exception.
=> Thumbnail parent

pype/plugins/global/publish/integrate_new.py
Rebase https://github.com/pypeclub/pype/pull/480 onto release/2.12.0-rc
=> 2.x/bugfix/integrate new handle destination

pype/modules/ftrack/tray/ftrack_module.py, pype/modules/ftrack/tray/login_dialog.py, pype/modules/ftrack/tray/login_tools.py, pype/tools/tray/pype_tray.py
- Skipped Login/Logout actions in tray menu, replaced with `Credentials` action which shows credentials window
- Credentials action has Green icon when logged and orange when not logged
- I tried to visualize if is logged or not, maybe would be better to use 2 different icons instead of color images
- Credentials window has 2 states Simple/Advanced
- Simple has button `Ftrack login` without user and api key inputs
- Advanced has button `Login` and both user and api key inputs are visible
- When logged in, the user and api key inputs are visible and showing currently logged user (not editable)
- Not sure if API key should be visible too? It can be handy to be able the key...
=> Enhanced Ftrack credentials GUI

pype/plugins/global/publish/submit_publish_job.py
single frame renders had `.` in names of their representations.
=> Fix: strip dot from repre names in single frame renders

pype/plugins/nuke/load/load_image.py, pype/plugins/nuke/load/load_sequence.py
bugfix:
https://pype.freshdesk.com/a/tickets/166
=> feat(nuke): adding image loader 

pype/plugins/global/publish/extract_jpeg.py, pype/plugins/nuke/publish/extract_thumbnail.py
The thumbnail is being created when publishing from the baked colourspace movie.
=> Nuke: skip thumbnail creation on farm submission.

pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json
Implemented schema for  `pype-config/presets/plugins/standalonepublisher`
Requires:
pypeclub/pype/#479
=> #241 - Implementation of pype-config/presets/plugins/standalonepublisher

pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json
Added filter.json implementation for GUI settings
Not sure if there isn't better option as these check-boxes seem of two disjunctive sets (either strict OR benevolent). But current .json allowed nonsensical variants too.
=> #241 - Implemented pype-config/presets/plugins/nukestudio/filter.json

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/1_applications_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/1_tools_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/1_tray_items.json, pype/tools/settings/settings/widgets/item_types.py
- using grid layout for most of important parts so there is no need to use `dict-form` in schema
- remove `dict-form` at all when all current PRs will be merged and modified
=> Grid layout in settings

pype/tools/settings/settings/widgets/item_types.py
- there is bug for move up/down buttons in list widget
- `order_changed` is triggered after new item is added, not before
=> ListWidgetItem has fixed move buttons

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/projects_schema/0_project_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/0_system_gui_schema.json, pype/tools/settings/settings/widgets/lib.py
- current schema type definition is strange as schema names which should replace the item in schema are in list under key `children`
- with this implementation schema type represents only one schema name
```
{
...
{
"type": "schema",
"children": [
"schema_1",
"schema_2"
]
}
...
}
```
```
{
...
{
"type": "schema",
"name": "schema_1"
}, {
"type": "schema",
"name": "schema_2"
}
...
}
```
=> Schema type represents one schema

pype/tools/settings/settings/widgets/base.py
- items are expanded to all available height because of `GridLabel`
- system and project widgets add one more spacer widget so all widgets above are stretched
=> Items are stretched in settings GUI

pype/plugins/global/load/copy_file.py, pype/plugins/global/load/copy_file_path.py
- `CopyFile` and `CopyFilePath` are not working when Qt is running `QCoreApplication`
- using static methods for the same approach instead
=> Copy file and file path are working in Maya 2020

pype/tools/settings/settings/widgets/item_types.py
- project override values are not propagated in right way if `dict` is used as widget
- values are propagated in right way now
=> Dict as widget can't apply project overrides

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/1_examples.json, pype/tools/settings/settings/style/style.css, pype/tools/settings/settings/widgets/base.py, pype/tools/settings/settings/widgets/item_types.py, pype/tools/settings/settings/widgets/multiselection_combobox.py, pype/tools/settings/settings/widgets/widgets.py
- implemented `enum` item type for retrieving one value of predefined values
- enumerator is shown as combobox and allows to have multiselection, in that case list is returned instead of single value
- multiselection can be enabled with setting `"multiselection": true` in item definition
- values are defined under value of key `"enum_items"` as list
- each item in list is simple dictionary where value is label and key is value which will be stored
- should be possible to enter single dictionary if order of items doesn't matter
```javascript
{
"key": "tags",
"label": "Tags",
"type": "enum",
"multiselection": true,
"enum_items": [
{"burnin": "Add burnins"},
{"ftrackreview": "Add to Ftrack"},
{"delete": "Delete output"},
{"slate-frame": "Add slate frame"},
{"no-hnadles": "Skip handle …
```
=> Enumerator item in settings GUI

pype/tools/settings/settings/widgets/widgets.py
- label widget in `GridLabel ` is offset by 2 pixels to be more "like" in right place next to input widget
- all widgets in `GridLabel` are transparent so consistency of background is not broken when parent has different bg color
=> Grid label tweaks in settings GUI

pype/tools/settings/settings/widgets/item_types.py
- in `raw-json` remained one usage of different variable name
- fixed raw json `item_value` method
=> Fix of raw json item

pype/plugins/ftrack/publish/integrate_ftrack_api.py, pype/plugins/ftrack/publish/integrate_ftrack_note.py, pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
- when integration of ftrack component fails it is executed `session.rollback()` but in that case are lost information about Ftrack loactions in ftrack session so every next component integration will fail with error which says nothing about what happened the first time
- session trigger refresh of ftrack locations when `session.rollback()` is called
=> Refresh Ftrack locations on session rollback

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json, pype/tools/settings/settings/gui_schemas/system_schema/1_examples.json, pype/tools/settings/settings/gui_schemas/system_schema/1_modules_gui_schema.json, pype/tools/settings/settings/widgets/anatomy_types.py, pype/tools/settings/settings/widgets/item_types.py
- changed way how to define `object_type` for `list` and `dict-modifiable`
- currently `"object_type"` keep information about `"type"` and `"input_modifiers"` defined other possible modifiers like `"minimum"`, etc.
- this has been changed and `"input_modifiers"`  key is skipped
- `"object_type"` can have full definition
```javascript
{
"type": "list",
"key": "exclude_ports",
"label": "Exclude ports",
// Full definiton
"object_type": {
"type": "number",
"minimum": 1,
"maximum": 65535
}
}
```
- also if possible to enter only type if do not want to specify any modifiers
```javascript
{
"key": "families",
"label": "Families",
"type": "list",
// Only type definition
"object_type": "text"
}
```
=> List and Modifiable Dictionary items has modified object specification

pype/tools/settings/settings/widgets/base.py
- after refresh on the tool all items are moved more to center and with each refresh are getting lower
- remove all widgets in content_layout on refresh
=> Setting tool: Remove spacer after refresh

pype/hosts/harmony/__init__.py
`func` is already existing object in Harmony namespace. We use `func()` for functions we send from server to Harmony client. When they are eval()ed there, they replace Harmony object making some Hamony functions as *Create keys...*  unusable.
Added random **uuid4** prefix for all generated functions by Pype and Avalon core to minimaze possible clash.
🏴 **Relates to similar PR** pypeclub/avalon-core#199
|---|
=> Harmony: fix clashing namespace of called js functions

pype/plugins/global/publish/extract_hierarchy_avalon.py, pype/plugins/global/publish/extract_review.py, pype/plugins/standalonepublisher/publish/collect_clip_instances.py, pype/plugins/standalonepublisher/publish/collect_instance_data.py, pype/plugins/standalonepublisher/publish/extract_shot_data.py, pype/plugins/standalonepublisher/publish/extract_thumbnail.py, pype/plugins/standalonepublisher/publish/validate_editorial_resources.py, pype/scripts/otio_burnin.py, pype/tools/standalonepublish/widgets/widget_drop_frame.py
- editorial plugins were interfering with other families
- adding "clip" family to better filter editorial instances 
- render/plates workflow fixes including: 
- space in input path was crashing standalone publisher
- space in input path was crashing burning ocio script
- when input resolution was not dividable by two it was crashing ffmpeg (solution was to add pad filter to add half frame pad to both sides)
closes #579
=> Standalone publisher editorial plugins interfering

pype/plugins/maya/publish/extract_camera_mayaScene.py, pype/plugins/maya/publish/extract_maya_scene_raw.py, pype/plugins/maya/publish/extract_model.py, pype/plugins/maya/publish/extract_yeti_rig.py
We were catching wrong exception (`AttributeError` instead of `KeyError` when deciding what preset to use, so when `ext_mapping.json` was used, extractor were crashing.
=> Maya: fix maya scene type preset exception

pype/modules/__init__.py, pype/modules/base.py, pype/modules_manager.py
- currently we don't have manager for pype modules which can be used in any case and be able access modules in headless mode
- this PR does not allow that yet too, just prepare basic parts to be able to do that in future
- implemented `PypeModule` class which should be used as Base for all modules
- this is not done yet since current modules use here and there widgets and can't be used in headless at all and are created for tray module manager
- imeplemented `PypeModuleManager` which should collect all available modules, and connect them
- with this we can add modules that are not used in tray at all
- modify modules to be ready for `PypeModuleManager`
- without GUI imports and separate logic
- create wrapper for tray usage
- requires to modify all current modules as they are tray based …
=> Base of pype module manager

pype/modules/websocket_server/websocket_server.py
- websocket module raise exception because of missing variable 
```
File "C:\CODE\__PYPE\dev\pype-setup\repos\pype\pype\tools\tray\pype_tray.py", line 225, in add_module
obj = module.tray_init(self.tray_widget, self.main_window)
File "C:\CODE\__PYPE\dev\pype-setup\repos\pype\pype\modules\websocket_server\__init__.py", line 5, in tray_init
return WebSocketServer()
File "C:\CODE\__PYPE\dev\pype-setup\repos\pype\pype\modules\websocket_server\websocket_server.py", line 38, in __init__
if not port:
UnboundLocalERROR: local variable 'port' referenced before assignment
File "C:\CODE\__PYPE\dev\pype-setup\repos\pype\pype\tools\tray\pype_tray.py", line 225, in add_module
obj = module.tray_init(self.tray_widget, self.main_window) …
```
=> set port variable to None so the variable exists

pype/plugins/global/publish/collect_anatomy_instance_data.py
- plugin `Collect Anatomy Instance Data` was refactored to work faster
- changed to context plugin
- as context plugin can query all data for all instances in 3 mongo queries
- collector works event for not activated instances (which was an issue before)
- disadvantages:
- log records are not under instance directly
=> Anatomy instance data collection is substantially faster for many instances

pype/modules/avalon_apps/avalon_app.py
- preparation to convert avalon module to pype module
- Qt is not used in avalon_apps module if `tray_init` is not triggered
=> Avalon module without Qt

pype/hosts/maya/menu.py
Add **Look Assigner** to Pype/Avalon Maya menu even if [scriptsmenu](https://github.com/Colorbleed/scriptsmenu) is not available.
=> Maya: add look assigner to pype menu even if scriptsmenu is not available

pype/plugins/maya/publish/submit_maya_deadline.py
In some storage scenarios **Deadline** has problems detecting presence of file added as `AssetDependency` on job. In those cases job is submitted but hold in **Pending** state indefinetly.
This PR is adding `asset_dependencies` parameter that can be changed via presets.
=> Maya: Deadline - make use of asset dependencies optional

pype/tools/settings/settings/widgets/item_types.py
- discard changes does not work in right way
- environments are always marked as modified because compare dictionary with and without metadata
- fixed discard changes for most of items
- environments metadata are added in `config_value` not in `item_value`
=> Settings GUI environments and discard changes

pype/plugins/global/publish/extract_burnin.py, pype/tools/pyblish_pype/window.py
- intent value is not set to context until Intent combobox change index of selected item
- burnin use intent label even if intent value is not valid
- intent is set all the time on play and validate buttons click
- extract burnin checks in intent value is valid before setting intent label to burnins data
=> Intent publish setting wasn't working with default value

pype/plugins/nuke/load/load_gizmo.py, pype/plugins/nuke/publish/collect_gizmo.py, pype/plugins/nuke/publish/collect_instances.py
- fixed collection of gizmo nodes
- adding missing loader plugin
- clean empty lines
=> Nuke: gizmo publishing error

pype/plugins/global/publish/collect_current_pype_user.py, pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/submit_maya_deadline.py
- deadline publish should publish with right user on deadline
- `PYPE_USERNAME` variable is filled on deadline submit
- not tested as don't have deadline setup
=> Deadline user defaults to pype username if present

pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/publish/collect_render.py
This adds `sync_workfile_version` option to maya render collection. When set to True, the final render output will have the same version number as the source workfile in maya at the time of publish
=> Maya: allow renders to have version synced with workfile

pype/hosts/nuke/lib.py, pype/plugins/nukestudio/publish/collect_hierarchy_context.py
fix(nks):  order of plugin, 
fix(nuke): typo in namespace
=> nks: broken order on plugins

pype/modules/ftrack/__init__.py, pype/modules/ftrack/events/action_push_frame_values_to_task.py, pype/modules/ftrack/events/action_sync_to_avalon.py, pype/modules/ftrack/lib/__init__.py, pype/modules/ftrack/lib/ftrack_action_handler.py, pype/modules/ftrack/lib/ftrack_base_handler.py
- implemented `ServerAction` which more suit to be used for action on event server
- register does not filter events by username
- roles are not checked on register but on discover
=> Ftrack server action improvement

pype/modules/ftrack/events/event_sync_to_avalon.py
- sync event is processing all changes as they happened on task
- few small issues breaking event synchronization
- task changes are filtered at one place and cares only if `name` or `typeid` changed
- ftrack entities are queried by their ids not as parent ids
- added query for tasks as they need different data
- tasks of created entity is not processed on avalon document creation but are moved to "task changes" processing
- task types are queried at once
- few formatting changes
=> Task processing in event sync

pype/plugins/ftrack/publish/integrate_ftrack_instances.py
On all review instances, for example Maya reviews, the source in Ftrack was missing.
Use case was that RV could not find the local movies.
=> Add source for review instances.

pype/plugins/global/publish/submit_publish_job.py
Case was submitting compositing from Nuke did not have audio on reviews when rendering on the farm, but local rendering does.
=> Missing audio on farm submission.

pype/plugins/ftrack/publish/integrate_ftrack_instances.py, pype/plugins/global/publish/cleanup.py, pype/plugins/global/publish/extract_burnin.py, pype/plugins/global/publish/extract_review.py, pype/plugins/standalonepublisher/publish/collect_representation_names.py, pype/plugins/standalonepublisher/publish/extract_thumbnail.py
This makes it possible to name multiple representation in standalone publisher using regex and filename. This allows publishing for example multiple render AOVs from standalone publisher while keeping their correct naming.
With that it was neccessary to tweak a few other places to amke sure we dont' throw away more data than needed. Especially burning and review plugins were deleting anything with 'delete' tag, even though they were representations that should not be processed by review at all. 
To use and test this, correct preset needs to be added to `presets/plugins/standalonepublisher/publish.json`
```json
"CollecRepresentationNames": {
"families": ["render"],
"name_filter": "([^_]+_[^_]+(?=\\.))"
}
```
=> Improved publishing of multiple representation from SP

pype/plugins/nuke/load/load_sequence.py
If a render only had a single frame it couldn't be loaded with the default nuke loader. Also if importing a lot of representations, their read nodes weren't named correctly based on representation name
=> Nuke: prevent crash if we only have single frame in sequence

pype/lib.py, pype/plugins/global/publish/extract_burnin.py, pype/plugins/global/publish/extract_review.py, pype/scripts/otio_burnin.py
- Changes in `pype.lib._subprocess`
- **all changes should be backwards compatible**
- it is possible to pass logger object (handy in pyblish plugins)
- Popen subprocess `sdterr` use `subprocesss.PIPE` instead of `subprocesss.stdout` to be able separate them from `process.communication()`
- returns whole output of executed process, concatenated stdout and stderr
- raises `RunTimeError` instead of `ValueError` if subprocess ends with nonzero returncode
- is logging whole stdout at once and stderr at once, instead of line by line
- line by line spams MongoDB and it is easier to read output from single
- stdout is logged as debug level
- stderr is logged as warning level
- `ExtractReview` & `ExtractBurnin` plugins
- are using new changes in `_subprocess` and are passing logger to it so they …
=> Burnin script logs better output

pype/lib.py
- `logger` keyword argument is not in definition of `_subprocess` function but is popped from `kwarg`
=> Lib subprocess without logger

pype/tools/pyblish_pype/widgets.py
- spacer for filter buttons may not be transparent for few Qt bindings
- added transparency attribute
=> Pyblish-pype spacer in terminal wasn't transparent

pype/hosts/harmony/__init__.py, pype/lib.py, pype/plugins/nuke/publish/collect_review.py
- method do not raise `AssertionError` if any document was not found but returns `None`
- has additional `dbcon` keyword argument to have ability to use different avalon mongo connection than `avalon.io` (optional)
- it is possible to enter `project_name`
- changed way how `get_latest_version` it is used in `CollectReview` plugin in Nuke as it does not raise `AssertionErro`r now
=> Get latest version in lib

pype/hosts/harmony/__init__.py, pype/plugins/global/publish/submit_publish_job.py
Pre-calculate final publish folder to add it to right mouse click option 
for easier checking in Deadline Monitor.
Previously value for rendered files on Deadline was used.
Solves #636
Depends on #642
=> Deadline publish job shows publishing output folder

pype/settings/lib.py, pype/tools/settings/settings/widgets/base.py
- environ is get in safer way until mongo saving is implemented
- saving functions are in `pype/settings` not in settings tool and tool is using that (with this should be easier to switch to save to mongo)
=> Settings function moved out of tool

pype/lib.py, pype/modules/ftrack/actions/action_application_loader.py, pype/modules/ftrack/lib/ftrack_app_handler.py
- removed functions from `pype.lib` using and modifying `avalon.io` (functions: `get_avalon_database` and `set_io_database`)
- their usage was replaced with using `AvalonMongoDB` object
- was used in ftrack application action and on application launch from launcher tool
=> Remove avalon io from pype lib

pype/modules/websocket_server/stubs/photoshop_server_stub.py, pype/plugins/photoshop/load/load_image.py
Fixed saving namespace into Headline and to layer name
Layer name is created in format: `asset_subset`, it is extendes by numeric suffix if same subset is loaded multiple times.
Fixed switch asset and update version functionality in Scene Inventory
Switching assets now works properly
Added delete layer by id
Removal of subset in Scene Inventory fixed
Requires reinstall of extension!
Requires:
pypeclub/avalon-core#210
Closes: #654
=> Photoshop: Fix Layer name was not propagating correctly

pype/tools/launcher/delegates.py
- group identifier is in left corner of item instead of left corner of item icon
- should be at same place for each item
=> Launcher has unified group identifier

pype/plugins/nuke/publish/validate_write_legacy.py
- conditions were defined in opposite manner
=> Nuke: wrong conditions when fixing legacy write nodes

pype/lib.py, pype/plugins/global/publish/extract_jpeg.py, pype/plugins/global/publish/extract_review.py, pype/plugins/global/publish/extract_review_slate.py, pype/plugins/global/publish/validate_ffmpeg_installed.py, pype/plugins/harmony/publish/extract_render.py, pype/plugins/hiero/publish/extract_review_cutup.py, pype/plugins/photoshop/publish/extract_review.py, pype/plugins/standalonepublisher/publish/extract_shot_data.py, pype/plugins/standalonepublisher/publish/extract_thumbnail.py, pype/scripts/otio_burnin.py, pype/tools/standalonepublish/widgets/widget_drop_frame.py
- ffmpeg(and other tools) crash in subprocess if path to them contain spaces
- path to ffmpeg executables is wrapped with quotes to tell system full path to executable
- function `ffprobe_streams` can accept logger object and log also stderr from executed process, if there is any
=> Fix ffmpeg executable path with spaces

pype/plugins/global/publish/submit_publish_job.py
When publishing initial version of render there is a case when version feeded to `Anatomy` is **None**.
This happens here:
https://github.com/pypeclub/pype/blob/7c87d2c1140b09dbca3f15e4528f687623937788/pype/plugins/global/publish/submit_publish_job.py#L222-L232
in this case `instance.data.get("version")` is `1` but to `_get_publish_folder()` is passed `override_version` that is still **None**.
Inside, version determination can still result in **None**:
https://github.com/pypeclub/pype/blob/7c87d2c1140b09dbca3f15e4528f687623937788/pype/plugins/global/publish/submit_publish_job.py#L1023-L1030
If `get_latest_version` returns **None** (and it will, because nothing is published), **None** will be fed as version to Anatomy and will result in error.
=> Hotfix: Added default version number

pype/plugins/tvpaint/load/load_image.py
- TVPaint's Image loader have 3 options
- stretch to project size
- stretch to project timeline
- preload images
- defualt loader settings are all set to True for all options
=> TVPaint image loader with options

pype/plugins/global/publish/extract_burnin.py, pype/plugins/maya/publish/extract_playblast.py
- camera name in maya is collected and added to representation data
- extract burnin add camera name to burnin data
=> Camera name in burnins

pype/plugins/photoshop/publish/extract_image.py, pype/plugins/photoshop/publish/extract_review.py
Hidden layers in published group stay hidden and won't show up in a published review.
Closes: #688
=> #688 - Fix publishing hidden layers

pype/hosts/maya/expected_files.py
this adds two fixes - one for getting frame padding directly from vray settings (and not render globals) and one for filtering aovs coming from refereces (prefixed with namespaces). So AOVs named like `foo:bar` will be skipped but `baz` wil not.
=> Maya: Vray expected file fixes

pype/plugins/global/publish/extract_burnin.py, pype/plugins/global/publish/validate_ffmpeg_installed.py, pype/plugins/photoshop/publish/extract_review.py, pype/scripts/otio_burnin.py
- data for burnin script are not passed in arguments but are stored to temporary json and path to temporary file is passed as arugment
- do not put ffmpeg path to quotes for `is_tool` check
=> Fix: Burnin data pass and FFmpeg tool check

pype/plugins/maya/publish/collect_ftrack_family.py, pype/plugins/maya/publish/collect_remove_marked.py, pype/plugins/maya/publish/collect_review.py, pype/plugins/maya/publish/extract_camera_alembic.py, pype/plugins/maya/publish/extract_camera_mayaScene.py
It was not possible to publish multiple cameras if they all had a review attached to them. This PR fixes the problem and also add camera to ftrack publishable instance
=> Maya: Fix for publishing multiple cameras with review from the same scene

pype/hosts/maya/expected_files.py
Legacy overrides doesn't work with render setup and make renderable cameras not renderable. This is removing this check for overrides.
❕ **this will make it incompatible with legacy rende layers system**
=> Maya: disable legacy override check for cameras

pype/modules/ftrack/events/event_push_frame_values_to_task.py
Push attributes event handler now works slightly different. Pushing attribute values from pype's hierachical to not hierarchical for ftrack expressions has more features in.
- there is no more mapping `From attribute key` -> `To attribute key` but only defined attribute keys that will be updated
- attribute values are synchronized both ways `hierarchical` <-> `not hierarchical`
- by default it works only for keys `frameStart` and `frameEnd` and entity type `Shot` but it should work for all of them (just change attributes)
- create `frameStart` custom attribute for entity type `Shot` (must have same attributes: non-decimal number)
- run event server
- change value in hierarchical attribute on Shot entity -> check if was value was also changed in the new attribute
- change value in the new …
=> Synchronize ftrack hierarchical and shot attributes

pype/tools/pyblish_pype/model.py, pype/tools/pyblish_pype/view.py, pype/tools/pyblish_pype/window.py
- context item is not under any group item - possible since we don't have artist view anymore
- items in instance view are sorted except context item which is always at the top
- this change does not affect order of processing
Resolves https://github.com/pypeclub/pype/issues/696
=> Sort instances by label in pyblish gui 

pype/plugins/maya/load/load_vrayproxy.py
Due to a bug in outliner color assignment, the proxies wouldn't load at all. This PR fixed that to match other loaders in maya.
=> Maya: vray proxy was no loading at all

pype/lib/abstract_collect_render.py, pype/lib/abstract_expected_files.py, pype/lib/abstract_metaplugins.py, pype/lib/abstract_submit_deadline.py
This is attempt to abstract how renders are collected, submitted and published on farm. This is useful for uniting most of the code between hosts.
Idea is to inherit from those abstract plugins in host specific one, implement abstract method and/or override those that make sense for current host.
To unify data collected I used data class concept. There is support in python for data classes from 3.7 but we still need to support legacy python 2 hosts, so I opted for using [attrs](https://www.attrs.org/) module we already have in dependecies as it is pulled by something.
=> Render publish plugins abstraction

pype/tools/launcher/widgets.py, pype/tools/launcher/window.py
- project change does not affect refresh of assets in launcher because refresh first set project to previous and then to new one
- do not call refresh of projects on project change, but call model refresh if project was not found in project's combobox
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/222|
=> Asset fetch second fix

pype/modules/sync_server/providers/gdrive.py, pype/modules/sync_server/sync_server.py, pype/modules/sync_server/utils.py
Moved rest of init under try part as if no presets present, no syncing is possible.
Moved timeit decorator to utils, renamed as it was shadowing python core library.
Requires:
pypeclub/pype-config#94
=> #731 - better handling of missing presets

pype/plugins/global/publish/extract_review.py, pype/plugins/tvpaint/publish/collect_instances.py, pype/plugins/tvpaint/publish/extract_sequence.py
- not created instance in TVPaint collector is skipped
- added `review` tag to review instances instead of `ftrackreview`
- added few debug logs to extract review filtering
=> TVPaint extract review fix

pype/hosts/maya/expected_files.py
There is a bug when trying to render and publish multiple renderable cameras in one render layer. Expected files are generated only for one of those cameras. Render on farm will be ok, but publish will work for only one.
```python
['maya/render_test_v007/MainCamA/MainCamA_cam2.0991.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam2.0992.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam2.0991.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam2.0992.exr']
```
this fix will produce correct output:
```python
['maya/render_test_v007/MainCamA/MainCamA_cam2.0991.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam2.0992.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam1.0991.exr',
'maya/render_test_v007/MainCamA/MainCamA_cam1.0992.exr']
```
🏴 **freshdesk ticket**: …
=> Hotfix: Maya: multiple renderable cameras in layer

pype/plugins/ftrack/publish/collect_ftrack_api.py, pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
- integrate ftrack hiearchy is using native ftrack_api way of settings custom attribute values (`entity["custom_attributes"]["{key}"] = value`) which will not wok when custom attribute key has both hierarchical and non hiearchical version
- hieararchical attributes are prepared before import to ftrack
- removed backwards compatibility of ftrack custom attributes group (`"avalon"` -> `"pype"`)
- this should be already fixed and new import is required
- modified custom attribute value setter to use specific attribute id and entity id to set the value with ftrack operations
- test in Nukestudio/Hiero as `IntegrateHierarchyToFtrack` may not work as expected in Python 2 host
=> Ftrack integrate custom attributes fix

pype/plugins/tvpaint/load/load_reference_image.py
- update of TVPaint loader does not work because `fname` attribute cotain path to "loaded" representation, not to "loading" representation
- change `fname` attribute to "loading" representation path from "loaded" path on update
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/227|
=> TVPaint update fix

pype/tools/settings/settings/widgets/item_types.py
- Environment metadata key is part of `item_value` in `raw-json` item which will always result that item is modified not matter what happens
- metadata keys is only set in `config_value` which is not used to comparisons but only for storing
- `dict-modifiable` have to handle environment metadata by it's own in his `config_value`
=> Raw json environment discard fix

pype/plugins/global/publish/extract_review.py
- audio may not be added to output of extract review
- based on tag `"no-audio"` in output definition (extract review profiles)
=> Extract review may not add audio to output

pype/hosts/maya/expected_files.py, pype/plugins/maya/publish/extract_look.py
There was a bug when Vray default "beauty" AOV was not handle properly, resulting in invalid publishes of multiple cameras.
This PR is handling this and is adding support for more esoteric vray aovs that were crashing Pype - like `materialID`. Finally it is fixing issue determining overridden values in Render Setup.
Create few AOVs in Vray - Diffuse and Material ID. They should be collected in `Collect Render Layers`.
Resolves #755
=> Maya: Vray handling of default aov

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/system_schema/example_schema.json, pype/tools/settings/settings/widgets/item_types.py
- added new item `collapsible-wrap` which does not hold any setting value
- item is for wrapping one and more items to collapsible widget which looks like `dict` item
=> Collapsible wrapper in settings

pype/hosts/harmony/js/PypeHarmony.js, pype/plugins/harmony/publish/extract_palette.py, pype/plugins/harmony/publish/extract_template.py
There was a bug where local function argument was shadowing Harmony object name `node` in `PypeHarmony.getDependencies()` crashing template extraction process.
Creating thumbnail for Harmony palettes is failing on Mac due **PIL** inability to access fonts. This is temporary solution disabling thumbnail creation when this error happens.
=> Harmony: template extraction and palettes thumbnails on mac

pype/plugins/tvpaint/publish/collect_workfile_data.py, pype/plugins/tvpaint/publish/validate_workfile_project_name.py
It is possible to have opened multiple workfiles at the same time from different contexts. Which is not an issue for most of avalon workflow but is issue for publishing.
- each workfile contain metadata with "project", "asset" and "task" to keep context in which were workfiles created.
- these metadata are loaded in first TVPaint's collector and current context is modified by them
- if workfile does not contain these metadata current context from `api.Session` is used
- added validator for comparing project name (it is not allowed to publish in different project)
- manually copy-pasted workfile (out of workfile tool) may contain metadata from different context
- this can be fixed with resave
- workfile change is not "Super Responsive" TVPaint won't change workfile context at the moment of …
=> TVPaint store context to workfile metadata (764)

pype/plugins/tvpaint/load/load_reference_image.py
- information about reference to loaded layers is stored under key `"objectName"` which is not right
- layer ids are stored under key `"members"` as list
- pype's loader do not touch any of that key directly but is using loader's method to get layer ids
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/236|
=> TVPaint store members key

pype/tools/settings/settings/README.md, pype/tools/settings/settings/widgets/item_types.py
- item `modifiable-dict` may have defined required keys
- required keys must be defined as a list (e.g. `["key_1"]`)
- they are moved to the top
- these keys can't be removed or edited (even for developer)
- it is possible to edit label if item is collapsible
=> Settings required keys in modifiable dict

pype/plugins/global/publish/extract_review.py
- ExtractReview cut audio if input is sequence because will set `frames:v ...`
- argument `frames:v ...` for output is used only if output is sequence
- audio inputs have set duration with help of `-to` argument where duration in seconds is filled
- same is applied for input if input **is** image sequence and output **is not** image sequence
- this is to specify how many frames should be used from input
- `shortest` argument was removed (as all inputs have defined duration)
=> Extract review audio cut fix

pype/hosts/unreal/lib.py, pype/lib/hooks.py
This PR is introducing changes to support **Unreal 4.26**. This version has Python 3 by default so there's no need to manually ensure **PySide** to be installed.
🏴 **Requires:** pypeclub/pype-config#96
|---|
=> Unreal: add 4.26 support

pype/api.py, pype/lib/applications.py, pype/modules_manager.py, pype/settings/__init__.py, pype/settings/lib.py, pype/tools/settings/settings/widgets/base.py
- added verb `get` to settings getter functions
- at the same time "get overrides" functions were renamed to make more sence (these return only override data which should be applied to existing settings)
- `studio_system_settings` -> `get_studio_overrides_system_settings`
- `studio_project_settings` -> `get_studio_overrides_default_project_settings`
- `studio_project_anatomy` -> `get_studio_overrides_default_project_anatomy`
- implemented functions:
- `get_default_project_settings` - return studio's default project settings
- `get_default_project_anatomy_data` - return studio's default project anatomy data
- `get_anatomy_data` - return anatomy data(not `Anatomy` object) for specific project 
- `get_current_project_settings` - return project settings for current project set in env variable …
=> Settings get anatomy data

pype/lib/abstract_collect_render.py, pype/modules/websocket_server/stubs/aftereffects_server_stub.py, pype/plugins/aftereffects/load/load_background.py, pype/plugins/aftereffects/load/load_file.py, pype/plugins/aftereffects/publish/collect_render.py, pype/plugins/lib.py
Implemented new loader for 'background' family.
Reworked structure of json metadata to follow existing implementations more closely. (Currently contains list of container or instances. Containers have 'members' array to list all imported files from loader.)
Requires:
pypeclub/avalon-core#237
=> Feature AE load background

pype/plugins/maya/publish/extract_look.py
when extracting and applying looks Pype wasn't respecting texture color space when *make tx* function was unchecked.
🎫 **ticket:** [#442](https://pype.freshdesk.com/a/tickets/442)
|---|
=> Maya: Look - respect original texture colorspace when not using maketx

pype/tools/settings/settings/widgets/base.py, pype/tools/settings/settings/widgets/item_types.py
- seems like project overrides are not applied on save
- they are filled right but when they are applied they are overriden with default project overrides
- make sure `_update_values` won't apply default project if any project is selected in project's view
=> Project overrides fix

pype/hooks/global/pre_with_windows_shell.py
- some applications have issues when are launched directly from python process namely foundry products but may be more
- implemented prelaunch hook that add shell executable before app executable
- this will cause that application is launched the same way as from command line or .bat
- we should check if this is also issue for Linux and Mac launch
=> Foundry apps launch fix

pype.py, pype/hosts/maya/menu.py, pype/lib/user_settings.py, requirements.txt
This solves problem when `user_settings` was written with Python 3 features but was pulled into Python 2 hosts. It also changes Pype so it adds itself to Python paths.
=> Python 2: make user settings compatible with python 2 hosts

pype/lib/avalon_context.py
- `with_avalon` wrapper does not return wrapped function
- imported modules in wrapper stay in locals so can't be used inside functions
- `with_avalon` returns wrapped function
- added global variable `avalon` which is set inside the wrapper
- `io`, `api` and `pipeline` was replaced with `avalon.io/api/pipeline`
- if anybody know about better solution plese came up with it
=> Avalon context lib fix

pype/tools/launcher/models.py, pype/tools/launcher/window.py
- actions in launcher are not discovered at all if project is not set
- do not skip all actions discover if project is not available only skip applications
- trigger discover on refresh
=> Launcher actions update

dev_mongo.ps1, dev_settings.ps1, dev_tray.ps1
in 3.0 we need to activate venv and then run pype with arguments to get it running from source. I've added a few helper launchers, so we don't have to re-type it all the time.
=> add settings, tray and mongo launcher

pype/modules/ftrack/events/action_push_frame_values_to_task.py, pype/modules/ftrack/lib/ftrack_base_handler.py
- modified `PushFrameValuesToTaskAction` action to be able push hierarchical values to non hierachical custom attributes and it's tasks
- pushing these values is applied on selection and all children under selection
- configurable attributes
- `interest_attributes` - attributes that will be pushed from hierarchical custom attribute to object type(entity type) specific (Default: `["frameStart", "frameEnd"]`)
- `interest_entity_types` -  entitiy types on which this will be applied (Default: `["Shot"]`)
=> Ftrack action to push hierarchical values

pype/plugins/tvpaint/publish/collect_workfile_data.py
- invalid metadata can't be fixed in TVPaint and auto repair is not safe enough to be used in production
- implemented action that will show if workfile data collector fail
- action tries to load all metadata keys and parse it -> if parse crash metadata keys is set to default value
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/252|
=> TVPaint repair invalid metadata

pype.py, pype/lib/__init__.py, pype/lib/mongo.py, pype/settings/constants.py, pype/settings/handlers.py, pype/settings/lib.py, pype/tools/settings/settings/widgets/base.py, pype/tools/settings/settings/widgets/lib.py
- moved first loading of environments later in pype bootstrap because `PYPE_MONGO` is required to load them
- added `PypeMongoConnection` which creates and store  mongo connections by url
- this is good to use to not create multiple connections to one mongo
- has no no special logic - imeplemented 2 classmethods `create_connection` and `get_mongo_client`
- to not use multiple connections use `get_mongo_client` which create and cache the connection and checks if existing connection is alive
- settings overrides are handled by `SettingsHandler`
- logic for storing had to be separated from `settings.lib` to separate class created on first use so it was easier to create abstraction of studio overrides handler
- previous implementation of storing overrides to json files was kept in …
=> Settings store in mongo

pype/modules/base.py
- Services menu is visible on tray start because it is set visibility on menu instead of menu's action item
- Don't set visibility on service's menu but service's menu action.
=> Services menu do not popup on tray start

pype/tools/standalonepublish/app.py, pype/tools/standalonepublish/widgets/widget_asset.py, pype/tools/standalonepublish/widgets/widget_family.py
- family widget take project from environments which is not actual project
- family widget crash if project is not set because of settings
- family widget skip setting families if project is not set
- family widget is refreshed on each project change
=> Standalone publisher fix in 3.0

pype/modules/avalon_apps/avalon_app.py, pype/modules/base.py, pype/modules/clockify/clockify_module.py, pype/modules/ftrack/ftrack_module.py, pype/modules/idle_manager/idle_manager.py, pype/modules/logging/logging_module.py, pype/modules/rest_api/rest_api.py, pype/modules/standalonepublish/standalonepublish_module.py, pype/modules/timers_manager/timers_manager.py, pype/modules/user/user_module.py, pype/settings/defaults/system_settings/modules.json, pype/tools/settings/settings/gui_schemas/system_schema/module_settings/schema_ftrack.json, pype/tools/settings/settings/gui_schemas/system_schema/schema_modules.json
- module keys in settings do not use capitals and spaces
`"Avalon"` -> `"avalon"`
`"Rest Api"` -> `"rest_api"`
`"User Settings"` -> `"user"`
`"Ftrack"` -> `"ftrack"`
`"Clockify"` -> `"clockify"`
`"Logging"` -> `"log_viewer"`
`"Standalone Publish"` -> `"standalonepublish_tool"`
`"Timers Manager"` -> `"timers_manager"`
`"Idle Manager"` -> `"idle_manager"`
=> Modules keys in settings

pype/modules/ftrack/actions/action_create_cust_attrs.py, pype/modules/ftrack/lib/settings.py, pype/plugins/maya/publish/submit_maya_muster.py
- loading right keys from modules settings
- `"Ftrack"` -> `"ftrack"`
- `"Muster"` ->`"muster"`
=> Module keys fix

pype/tools/settings/settings/widgets/item_types.py
- `Reset to pype defauts` will show only on entities that are last in hierarchy or marked as groups
- fix reset to pype's default in hiearchy to show also on their parents
=> Reset to pype default action show properly

pype/tools/settings/settings/widgets/item_types.py
- items `list` and `list-strict` may not contain "label" key in schema if are not marked with `is_group` to True
- when would be marked with `is_group` visualization of overrides wouldn't work and actions may not show properly
- remove empty labels from schemas after merge of PR https://github.com/pypeclub/pype/pull/820
=> List item without label in settings gui

pype/modules/clockify/ftrack/server/action_clockify_sync_server.py, pype/modules/clockify/ftrack/user/action_clockify_sync_local.py, pype/modules/ftrack/actions/action_delivery.py, pype/modules/ftrack/actions/action_store_thumbnails_to_avalon.py, pype/modules/ftrack/events/event_sync_to_avalon.py, pype/modules/ftrack/ftrack_module.py, pype/modules/ftrack/ftrack_server/sub_event_processor.py, pype/modules/ftrack/ftrack_server/sub_legacy_server.py, pype/modules/ftrack/ftrack_server/sub_user_server.py, pype/modules/ftrack/lib/__init__.py, pype/modules/ftrack/lib/settings.py
- server and user server is not using lib functions to get paths to handlers but load Ftrack module with ModulesManager and get it from modules manager instead
- this way all registered paths to ftrack module are registered
- Clockify server sync action inherit from `ServerAction`
- few objects in Ftrack actions/events are created on object initialization instead of in class definition
=> Ftrack module use modules manager for ftrack paths

pype/hosts/maya/expected_files.py
Collecting file for render did not take into account vray switch for enabling/disabling all AOVs.
In Maya *Render Settings > Vray > Render Elements* add some AOVs. Run publish and check **Render Layer** collector for expected files - those AOVs should be listed there. Now uncheck *Render Settings > Vray > Render Elements > Enable/Disable All* and run publish again. There should now be only beauty aov.
🎫 **ticket:** [#454](https://pype.freshdesk.com/a/tickets/454)
|---|
=> Maya: Take into account vray master AOV switch

pype/plugins/global/publish/extract_scanline_exr.py, pype/plugins/maya/publish/submit_maya_deadline.py
There was data structure defined outside *Submit Maya Deadline* instance scope. It should have been read-only, but was written to, affecting all subsequent submitted instances.  It probably only affected `Frames`.
Publishing two render layers with different frame range resulted in render jobs with only one frame range (derived from first render layer submission).
This is fixing it, making data copy for each and every instance.
🎫 **Ticket ID:** [#438](https://pype.freshdesk.com/a/tickets/438)
|---|
=> Maya: Deadline submitter - shared data access violation

pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
Deadline requires integers only in frames range.
On some environments rounded floats are pushed in, this casts them to int explicitly.
=> Fix - AE - added explicit cast to int

pype/lib/terminal.py
- python module `blessed` crash on import when `sys.__stdin__` is null (Resolve)
- `Terminal` class has 2 attributes `_initialized` and `use_colors` and new static method `_initialize`
- `_initialize` should be called only once on first call of `log` method and define if colored output should be used
=> terminal.py crash on import

pype/lib/log.py, pype/pype_commands.py, pype/tools/tray/__init__.py, pype/tools/tray/__main__.py, pype/tools/tray/pype_tray.py
- tray option in pype cli won't trigger new subprocess of tray tool but execute tray's main directly
- pype logger's do not propage logs to root logger (logs are not doubled)
=> Tray without subprocess

pype/tools/settings/settings/README.md, pype/tools/settings/settings/gui_schemas/projects_schema/schema_main.json, pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json, pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_global.json, pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_anatomy_imageio.json, pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_tools.json, pype/tools/settings/settings/widgets/item_types.py
- item `list` can be wrapped in collapsible label with setting `use_label_wrap` to `True` (default is `False`)
- added few validation about set label
- item `raw-json` does not need to have filled label
- empty labels are removed from schemas
=> List item with wrapper

pype.py
- if pype.py is (accidentally) imported it will always run `boot` function which may cause infinite tray execution if it happens on tray initialization
- it may cause huge issues due to a bug on different place e.g. whensomething like this is executed `__import__(".")`
- do not run `boot` on pype.py import until it's in `__main__`
=> Pype.py do not boot on import

pype/plugins/maya/create/create_review.py, pype/plugins/maya/publish/extract_playblast.py
This adds an attribute to the review object set so users can choose to hide image planes when publishing.
Use case is that we have two reviews in our animation files; review and precomp. Precomp needs the image plane hidden.
=> Optionally hide image planes from reviews.

pype/modules/ftrack/events/event_task_to_parent_status.py, pype/modules/ftrack/events/event_task_to_version_status.py, pype/modules/ftrack/events/event_thumbnail_updates.py, pype/modules/ftrack/events/event_version_to_task_statuses.py, pype/modules/ftrack/lib/ftrack_action_handler.py, pype/modules/ftrack/lib/ftrack_base_handler.py, pype/modules/ftrack/lib/ftrack_event_handler.py
Ftrack entities are cleared from queried data on `session.rollback()`. Since rollback has stored project entity in event data all attributes and keys (mainly `full_name`) to `NOT_SET`. So each event would have to query project again or will crash if condition is not right.
- project settings are stored by `project_name` and method to get project settings from event data expect only `project_name` argument which is all it need
- project entity is not stored to event data only project name, which is string so can't be changed to `NOT_SET` so event rollback won't cause requery of project for loading settings
- all this is applied for implementations and usage in current `develop` branch
- must be pushed and modified in PR: https://github.com/pypeclub/pype/pull/847
=> Ftrack project entity is not stored to event data

pype/lib/applications.py
- on app launch was used `copy.deepcopy` to create copy of passed environment but if `os.environ` is used it will create copy of object `os._Environ` which is singleton so all modifications are also applied to current process environments
- variable `env` is always converted to a dictionary
=> Create dict copy of environments on application launch

pype/modules/ftrack/lib/avalon_sync.py
- preparation of entities info in sync to avalon action is slow due to not pre-queried data about task type id and it's name
- task type id of task entities are queried with other attributes on entities query and task type names are prepared at once
- both is done to not query them on demand one by one which is slow
=> Faster sync to avalon preparation

pype/modules/base.py, pype/tools/tray/pype_tray.py
- modules manager collect time spent on module's initialization
- tray will print it out so we can reveal modules slowing down initialization
```
-----------------------+--------------+---------+---------------+---------+-------------+-----
Module name            |Initialization|Tray init|Connect modules|Tray menu|Modules start|Total
-----------------------+--------------+---------+---------------+---------+-------------+-----
AvalonModule           |0.000         |0.195    |0.001          |0.000    |0.000        |0.196
ClockifyModule         |0.000         |N/A      |N/A            |N/A      |N/A          |0.000
FtrackModule           |0.001         |0.777    |0.000          |0.000    |0.936        |1.714
IdleManager            |0.000         |0.000    |0.000          |0.003    |0.001 …
```
=> Module manager time report

pype/modules/ftrack/actions/action_create_cust_attrs.py, pype/modules/ftrack/lib/custom_attributes.json, pype/settings/defaults/system_settings/modules.json, pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_aftereffects.json, pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_tvpaint.json, pype/tools/settings/settings/gui_schemas/system_schema/module_settings/schema_ftrack.json, pype/tools/settings/settings/gui_schemas/system_schema/module_settings/template_custom_attribute.json, pype/tools/settings/settings/widgets/item_types.py
- settings of pype's Ftrack custom attributes was limited to read/write roles and custom attributes are predefined and not set with modifiable dictionary
- fixed keys `write_security_role` and `read_security_role` to `write_security_roles` and `read_security_roles`
- removed remaining items `dict-invisible` items from schemas are removed backwards compatibility for them
Resolves: https://github.com/pypeclub/pype/issues/212
=> Ftrack custom attributes from settings

pype/lib/terminal.py
- when `blessed` module can't be imported `Terminal.echo(...)` is called which call `Terminal.log(...)` inside -> because of this the thread lock is never released and messages are not logged at all
- use `print` instead of `Terminal.echo`
=> Fix terminal inner lock

pype/modules/settings_action.py, pype/tools/settings/__init__.py, pype/tools/settings/settings/style/style.css, pype/tools/settings/settings/widgets/base.py, pype/tools/settings/settings/widgets/item_types.py, pype/tools/settings/settings/widgets/widgets.py, pype/tools/settings/settings/widgets/window.py
- settings gui sets overlay widget with text when can't response to user events (on save and load)
- it's not perfect but it is at least visible that user should wait
- settings gui is not loading settings on initialization but must be explicitelly called
- with this change is possible to have faster loading of settings action in tray and call reset on settings show
- tray initialization is faster but loading of settings gui will take a longer time on each show (settings gui is always reset when opened from tray)
- Settings gui is not using `avalon.io` but `AvalonMongoDB` which is also reset if `AVALON_MONGO` is changed in system category
=> Settings shadow widget when working

pype/plugins/global/publish/integrate_new.py, pype/plugins/global/publish/integrate_thumbnail.py, pype/plugins/houdini/publish/extract_alembic.py, pype/plugins/houdini/publish/extract_vdb_cache.py, pype/plugins/standalonepublisher/publish/collect_context.py, pype/settings/defaults/project_anatomy/templates.json
- templates use key `{ext}` instead of `{representation}` in default publish templates
- `"ext"` key is now filled with extension
- `"representation"` key is now filled with representation name
- `"output"` key was kept as it can be filled optionally but representation name is filled all the time
- don't know why it is filled optionally so was scared to go deep into the rabbit hole
- extensions collected to representation during publishing should always use extension without dot (`mov`, `exr` etc.)
- removed replacements of filled path `.replace("..", ".")` in Integrate New (as it is not "Kosher")
- extensions are checked before template filling
- if `"ext"` key on representation contain dot plugin `Integreate New` will log warning message that got extension with dot
- this should help us …
=> Extension key in templates

pype/hooks/global/pre_global_host_data.py, pype/hosts/maya/menu.py, pype/hosts/nuke/menu.py, pype/lib/__init__.py, pype/lib/avalon_context.py, pype/tools/workfiles/README.md, pype/tools/workfiles/__init__.py, pype/tools/workfiles/app.py, pype/tools/workfiles/model.py, pype/tools/workfiles/view.py, schema/workfile-1.0.json
- added workfiles tool to `pype.tools`
- workfiles tool was updated with 2.x develop features (extensions combobox)
- workfiles document is stored to mongo db on workfiles creation
- Document:
```
{
"type": "workfile",
"filename": "<workfile filename>",
"parent": <asset id>,
"task_name": <task name>,
"files": [<rootless workfile path>],
"schema": "pype:workfile-1.0",
"data": {...}
}
```
- currently is workfile tool modification used only in maya and nuke because all other hosts can't easily change menu items
- it is possible to store artist note which is stored to `data.note` key in the document
=> Store workfiles information in the db

pype/modules/ftrack/events/action_push_frame_values_to_task.py, pype/modules/ftrack/events/event_push_frame_values_to_task.py, pype/modules/ftrack/lib/ftrack_action_handler.py, pype/settings/defaults/project_settings/ftrack.json, pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
- `Sync Hierarchical and Entity Attributes` event and action are using settings
- both use same settings key
- added role list to settings and special "enable" button for action
- enable button on top control's event
- NOTE: this is not clear maybe both should be under label or split action enable (and role list) under different label
- event had to be rewritten drastically as it was based on knowing the attributes at the beginning of filtering
=> Sync hier attributes with settings

pype/hosts/maya/__init__.py, pype/hosts/nuke/lib.py
- there are still several places where `get_application` is used from `avalon.pipeline` which can't work because we don't use tomls anymore
- nuke used get_application to fill template key `"{app}"` for which can be used `"AVALON_APP"` key from `Session` or environments
- maya used Application initialization which does nothing special in pype, only set `"AVALON_WORKDIR"` which is already set through Workfiles tool
=> Remove get_application usage

vendor/README.md
Adding vendor folder. Content is ignored by git but is included during Pype build. Useful for ffmpeg/oiio/etc.
=> Pype: add vendor folder

pype/plugins/nuke/load/load_sequence.py
wrong way of replacing numbers for hashes
=> fix(nuke): improving of hashing path 

pype/plugins/hiero/publish/extract_review_cutup.py
- removing approximation to 2 decimals
- audio duration fix only if audio in families
=> Hiero: cut videos with correct secons 

pype/tools/launcher/models.py, pype/tools/launcher/widgets.py, pype/tools/launcher/window.py
- discovery of actions in launcher is broken that clicking on first project in project list won't discover actions
- launcher items do not hold session data separately but are corresponding to `dbcon.Session` which is used across all widgets
- widgets/models/views access less to children of their children
- actions are now discovered on launcher show event and on project change properly
- TODO add refresh/reset method to main launcher window to also refresh projects which is not possible right now
- actions have set tooltips to their labels so it is possible to see whole label on hover
=> Launcher fix actions discover

pype/plugins/tvpaint/load/load_sound.py
- implemented sound importer for TVpaint
- TVPaint does not have ids for loaded sound so we can reference them as we can't say which audio is related to which representation
- we may do that by filepath of an audio but that would require to allow to reference representation only once
- it is possible to load audio from video file but filtering of representations is not 100% accurate
=> TVPaint audio/sound loader

pype/modules/ftrack/actions/action_clone_review_session.py
Built-in cloning in Ftrack does not clone the children.
=> Clone review session with children.

pype/hosts/harmony/__init__.py, pype/hosts/harmony/js/PypeHarmony.js, pype/hosts/harmony/js/publish/CollectFarmRender.js, pype/plugins/global/publish/submit_publish_job.py, pype/plugins/harmony/create/create_farm_render.py, pype/plugins/harmony/create/create_render.py, pype/plugins/harmony/publish/collect_audio.py, pype/plugins/harmony/publish/collect_farm_render.py, pype/plugins/harmony/publish/collect_instances.py, pype/plugins/harmony/publish/collect_palettes.py, pype/plugins/harmony/publish/collect_scene.py, pype/plugins/harmony/publish/collect_workfile.py, pype/plugins/harmony/publish/extract_render.py, pype/plugins/harmony/publish/extract_workfile.py, pype/plugins/harmony/publish/submit_harmony_deadline..py, pype/plugins/harmony/publish/validate_scene_settings.py
Implemented Deadline rendering from Harmony.
Fixed harmony.py needs to be deployed to `DEADLINE_REPO_DIR/plugins/Harmony`
Scripts handles unwanted error code, which is probably DD issue and shouldn't happen and add possibility to create `preRenderInlineScript` argument which is needed in the case of multiple write nodes in the scene (default 'Top/Write' node is present always and shouldnt be rendered.)
Requires:
pypeclub/pype-setup#83
pypeclub/pype-config#98
|---|---|
|pype|https://github.com/pypeclub/pype/pull/911
=> Harmony deadline submission

pype/modules/websocket_server/stubs/photoshop_server_stub.py
Create called directly on layer returned list instead of single group.
|---|---|
|pype|https://github.com/pypeclub/pype/pull/921
=> Fix PS - Create from single layer

pype/hosts/maya/expected_files.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/publish/collect_render.py
Pype was expecting all enabled AOVs returned by Maya to be rendered. But Maya by default returns all AOVs, even those coming from references and they are not rendered.
Add option `use referenced aovs` on render instance that is disabled by default. If enabled Pype is expecting referenced AOVs to be rendered.
=> Maya: Handling Arnold referenced AOVs

pype/plugins/tvpaint/publish/extract_sequence.py
- sequence of single frame crash on intagration
- tvpaint extract sequence convert single frame sequence to single file
|---|---|
|pype|https://github.com/pypeclub/pype/pull/952|
=> Fix single frame Sequence in TVPaint

pype/hosts/maya/api/expected_files.py, pype/hosts/maya/plugins/create/create_render.py, pype/hosts/maya/plugins/publish/collect_render.py
Pype was expecting all enabled AOVs returned by Maya to be rendered. But Maya by default returns all AOVs, even those coming from references and they are not rendered.
Add option use referenced aovs on render instance that is disabled by default. If enabled Pype is expecting referenced AOVs to be rendered.
❕ **Pype 2 pull request:** #938
=> Maya: Handling Arnold referenced AOVs - Pype 3

pype/scripts/otio_burnin.py
- ffmpeg's output of any prores encoder (prores_ks, prores_aw, prores) is always codec name `prores` so burnin script can't 
- ffmpeg stores encoder to output metadata tags so we can read them and define which is used
- this works only if input is created by ffmpeg
- changes should affect only inputs that have codec name `prores` in metadata
|---|---|
|pype|https://github.com/pypeclub/pype/pull/959|
=> Prores ks in burnin script

pype/hooks/photoshop/prelaunch.py
Unwanted dependency, websocket server used instead.
Version for Pype3 is not needed, this hook is not there.
=> PS - remove pywin installation from hook

pype/plugins/standalonepublisher/publish/extract_bg_main_groups.py
- PSD bulk export has small modification when exports **ANIM** group in BG Layout extractor
- ANIM group is not exported as one output but similar to export to compositing where it's subgroups are exported as separated outputs and are stored the same way
|---|---|
|pype|https://github.com/pypeclub/pype/pull/966|
resolves #939
=> PSD Bulk export of ANIM group

pype/modules/ftrack/actions/action_create_project_structure.py
- ftrack action `CreateProjectFolders` is using root keys instead of root paths to create project folders
- lack of process logs
- create project folders is using root paths instead of keys
- added few logs
- action will create defined folders in each project's root
|---|---|
|pype|https://github.com/pypeclub/pype/pull/968|
=> Create project structure action fix multiroot

pype/modules/ftrack/lib/avalon_sync.py
- during sync to avalon are project's tasks compared to previous state of project and pass only changes between them to be updated but tasks must be updated as one key and is not possible to pass only changes
- due to this on each sync are task types chaning between 2 states
- modification of any task type is always resolved as all task types must be updated
|---|---|
|pype|https://github.com/pypeclub/pype/pull/973|
=> Fix update of project's tasks on Ftrack sync

pype/lib/__init__.py, pype/lib/avalon_context.py, pype/plugins/blender/load/load_layout.py, pype/plugins/maya/load/load_reference.py
- Maya's Referrence loader and Blender's Layout loader are creating instances during loading and are expecting that `avalon.api.create` can work with only family which is not possible since [PR in avalon-core](https://github.com/pypeclub/avalon-core/pull/231)
- implemented function `get_creator_by_name` that returns creator plugin but it's name
- loaders have defined creator name that will be used to create new instances and use `get_creator_by_name` to use it
The function `get_creator_by_name` returns `None` if none of registered creator plugins match to entered name and loaders will raise an error if that happens. Should the error be raised? Should be raise inside the loader or inside `get_creator_by_name`?
|---|---| …
=> Get creator by name fix

pype/modules/ftrack/events/event_sync_to_avalon.py
- object types without any specific custom attributes skip value changes of custom attributes even if happened on hierarchical custom attribute
- custom attribute update is not skipped until will check that modified values may be from hierarchical custom attribtes
- hierarchical custom attributes are not queried by configuration key but by configuration id
- configuration key may be same as there may be hierarchical and non hierarchical custom attribute with same key
|---|---|
|pype|https://github.com/pypeclub/pype/pull/983|
=> Fix Ftrack custom attribute update

pype/hosts/maya/plugin.py
When referencing a static alembic the alembic node is not created. When updating this, the code was hardcoded to set certain attributes rather than setting attributes that exists.
=> Maya: Alembic only set attributes that exists.

pype/plugins/global/publish/extract_review.py
~~- it is not handled when input and output resolution ratio is same just in different scale (INPUT: 200x320 -> OUTPUT: 100x160)~~
- it is possible that `instance.data` may contain not "ideal" pixel aspect ratio that may affect scale of an input to not allowed resolution compared to output resolution
- it is not possible to use ffmpeg padding that has resolution smaller then input's resolution
- this happens when pixel aspect number has more than 3 float points and resolution is bigger than 2K
~~- just use output resolution without calculations when input and output resolution ratios are same for scale filter~~
- handle most of edge cases when scale resolution is bigger than output's resolution by subtracting one pixel aspect ratio "point"
=> Extract review handle bizzar pixel aspect ratio

pype/plugins/maya/publish/extract_look.py
This temporarily disables creation of hardlinks in Look extractor as it is causing problems with IO blocks with maketx tool during integration. Need to investigate further.
=> Maya: Looks - disable hardlinks

pype/plugins/photoshop/publish/collect_instances.py, pype/plugins/photoshop/publish/collect_review.py
3.0 PR
https://github.com/pypeclub/pype/pull/1007
=> PS - remove obsolete functions from pywin32

pype/plugins/global/load/delete_old_versions.py
Unfortunately the nature of Loaders is that they operate on one representation at a time, so when multiple subsets are selected the settings dialog opens multiple times.
This could be solved with Loader options.
I was also thinking of splitting out the calculate to a different Loader, so better separate destructive actions.
=> Delete old versions

pype/settings/entities/exceptions.py, pype/settings/entities/lib.py
- settings entities code contained python 3 syntax which was copied from GUI (PR https://github.com/pypeclub/pype/pull/1001)
- replaced Python 3 syntax with Python 2 compatible
=> Removed Python 3 syntax from settings entities

pype/settings/defaults/project_anatomy/roots.json, pype/settings/defaults/project_anatomy/templates.json, pype/settings/lib.py, pype/tools/settings/settings/widgets/anatomy_types.py
PR resolves issue: https://github.com/pypeclub/pype/issues/1010
- removed support to set singleroot through settings tool
- default project roots have multiroot roots with single root `"work"`
- added "kind" fix of anatomy overrides
- overrides are not applied correctly on whole Project category settings (not only anatomy) because settings are stored without override metadata which define which keys are replaced
=> Unify the use of single and multi root templates

pype/modules/sync_server/tray/app.py, pype/tools/settings/__init__.py, pype/tools/settings/settings/__init__.py, pype/tools/settings/settings/widgets/__init__.py
- propagated `ProjectListWidget` in settings tool to setting `__init__.py`
- sync server is importing from settings tool not from direct submodule
=> Project list import fix

pype/lib/plugin_tools.py, pype/plugin.py
since we switched hosts to the new structure, the plugins weren't loading settings correctly. 
This also removes double logic in the settings loading
=> Plugins settings are not loaded correctly

pype/api.py, pype/hooks/global/pre_global_host_data.py, pype/lib/__init__.py, pype/lib/applications.py
- we should be able to have lib function to calculate environments for entered context like prelaunch hook `GlobalHostDataHook` does
- logic from `GlobalHostDataHook` prelaunch hook was moved to **"~/pype/lib/applications.py"**
- environments preparation has steps where are used same object and temp data so it was necessary to be able keep intermediate results in cache for this purpose was added `EnvironmentPrepData` class
- is helper dicitonary which has few required keys and few keys are added automatically if are not filled
- modified functions moved from hook to work with `EnvironmentPrepData` object
- modified hook to store intermediate results to launch context data
- implemented function `get_app_environments_for_context` which expects only **Project name**, **Asset name**, **Task …
=> Prelaunch host env preparation in lib

pype/hosts/maya/lib.py, pype/hosts/maya/render_setup_tools.py, pype/plugins/global/publish/integrate_new.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/create/create_vrayscene.py, pype/plugins/maya/load/load_vrayscene.py, pype/plugins/maya/publish/collect_render.py, pype/plugins/maya/publish/collect_renderable_camera.py, pype/plugins/maya/publish/collect_vrayscene.py, pype/plugins/maya/publish/extract_vrayscene.py, pype/plugins/maya/publish/validate_vray_translator_settings.py
This PR adds ability to work with `vrayscene` type with more control. It inherits basic principles from `rendering` family. So when you create vray scene instance, it monitors render layers and create set under instance for each of them, tracking changes. If you leave that set empty, it will export whole scene under that render layer context to *vrayscene*. However if you add objects/sets there, it will export only those under render layer context.
This is currently publishing only on local computer (not utilizing render farm) and it doesn't support multi-frame sequences of vray files.
This PR is also introducing changes in current rendering publishing system. It drops `LAYER_` prefix in names of sets created under rendering instance. Instead it prefix them with Maya namespaces. By …
=> Maya: Vray scene publishing

pype/settings/defaults/system_settings/tools.json, pype/settings/entities/root_entities.py, pype/settings/entities/schemas/system_schema/tool_settings/schema_vray.json, pype/settings/entities/schemas/system_schema/tool_settings/schema_yeti.json
- environments for vray and yeti are stored only as dictionary without metadata of env group
- default system settings are not stored where should
- added `"env_group_key"` attribute to their environments
- restored defaults to contain metadata
- changed directory of default folder for system settings
=> Tools miss env groups in schema

pype/hosts/nuke/lib.py, pype/plugins/nuke/publish/collect_instances.py, pype/plugins/nuke/publish/submit_nuke_deadline.py
- remove permissions override
- remove scene dependency on deadline
=> smaller nuke fixes from production

pype/plugins/tvpaint/publish/extract_sequence.py
Published thumbnail from TVPaint has similar filename as sequence frames which cause issues when loading to TVPaint as the sequence start a frame earlier and containt the thumbnail as first frame (even if does not contain frame number in).
- added `"outputName"` to thumbnail representation so published filename should be different than sequence frames
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1037|
=> TVPaint thumbnail extract fix

pype/modules/ftrack/events/event_sync_to_avalon.py
- event sync to avalon can't handle moved entity under project entity when calculating parent hierachy
- event check if parent is project
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1040|
=> Fix entity move under project

pype/cli.py, pype/pype_commands.py
We need to prepare environments for applications on farm which would require to import pype which is not possible at the moment and would require more changes (Issue https://github.com/pypeclub/pype/issues/1034). This is a temporary added command which can solve our current issue.
- added `extractenvironments` to pype commands
- 1 positional argument `output_json_path` where output will be stored
- 4 options **project**, **asset**, **task**, **app** they define context for which environments will be prepared
- if options are not entered then only pype's global environments are extracted
=> Environments for context command

pype/tools/settings/settings/widgets/item_widgets.py
Wrappers in settings gui break order of children in schemas. Wrappers are always added to ui layout at first place.
- wrappers are added to layout when it's first children ui is created so ordering now match schema
=> Fix order of wrappers in settings gui

pype/hosts/maya/attributes.py, pype/plugins/maya/publish/collect_renderable_camera.py
when collecting renderable cameras we queried every `renderable` attribute for every camera by switching to render layer and out of it for every query. With many cameras in scene, this becomes unusable as it was slow and took even hours just to collect this.
This is using code from @BigRoy to achieve this. We should adapt it on other places where attributes are queried by switching layers.
=> Maya: speedup renderable camera collection

pype/plugins/global/publish/collect_anatomy_instance_data.py
Subset documents query in Collect Anatomy Instance Data plugin is looking for combonations of asset ids and subset names from instances in workfile which may cause issues if wokfile contain instance with different asset.
- query is not using combinations of all asset ids and subset names but explicit combinations of asset id and subset name
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1061|
=> Explicit subset filter in anatomy instance data

pype/plugins/tvpaint/publish/extract_sequence.py
- output frame range is offset by 1 frame compared to TVPaint timeline that is probably because of TVPaint's frame indexing of bug of frame collecting
- easies fix was to modify output frameStart and frameEnd values by one (before TVPaint's extraction will do what should do)
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1060|
=> TVPaint frame offset

pype/lib/log.py, pype/modules/avalon_apps/avalon_app.py, pype/settings/defaults/system_settings/modules.json, pype/settings/entities/schemas/system_schema/schema_modules.json, start.py
- avalon module use global variables that are set with values from environments on import but avalon environments may not be set at the moment yet because they are set with Avalon Module
- the problem is avalon schema (AVALON_SCHEMA env) and avalon's mongo db (AVALON_MONGO, AVALON_TIMEOUT, AVALON_DB envs) these are problem only if `AvalonMongoDB` object is created and used before variables are set
- set the environments earlier in `start.py` before avalon is imported (before pype's module manager is used)
- moved non modifiable environments out of Pype's Avalon module to start.py this way we should be 99% sure that they are set before avalon is imported
- removed keys `AVALON_MONGO` and `AVALON_DB_DATA` from settings
Resolves: https://github.com/pypeclub/pype/issues/1069
=> Fix resolving of  schema dir

pype/plugins/global/publish/collect_anatomy_instance_data.py
- Collect Anatomy instance data will crash if there are no instances to process (with wierd error)
- do not query subset documents if subset filters are empty
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1083|
=> Collect instance data fix subset query

pype/plugins/photoshop/publish/collect_workfile.py, pype/plugins/photoshop/publish/increment_workfile.py
Allows saving workfile as .psb, publish it as psb representation
(Currently .psb could be opened, but not saved as or published.)
Requires:
pypeclub/avalon-core#290
=> PS - added support for .psb in workfiles

pype/tools/standalonepublish/widgets/widget_family.py
- fixed usage of `versions` variable in standalone publisher where were expected version documents but now it is only list of version names
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1091|
=> Fix versions variable usage in standalone publisher

pype/hosts/maya/__init__.py
Overrides of taskChanged event is not radical but explicit. All `"taskChanged"` callbacks were removed on override event in maya's implementation which is not wanted.
- `override_event` function was removed
- added `override_task_change_event` which removes task change callback from maya's implementation in avalon
- this explicit replacement give ability to register different callbacks for `"taskChanged"` event (e.g. in Loader tool)
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/298|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1107|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/299|
Resolves: https://github.com/pypeclub/pype/issues/1074
=> Reset loader's asset selection on context change

pype/settings/defaults/system_settings/general.json, start.py
- Global environments are not set on start of pype.
- removed `set_environments` from start.py as is not used
- added `set_pype_global_environments` to start.py where are set environments from `"global"` environment group and few hardcoded values
- those hardcoded environment keys were removed from defaults settings
- env variable `PYPE_PYTHON_EXE` was removed from default global environments
- this will be changed in future anyway as what is not stored under `"global"` environment group will be stored in general settings
=> Missing gobal environments

pype/hosts/tvpaint/hooks/pre_launch_args.py
- TVPaint's prelaunch hook is still using env variable `"PYPE_PYTHON_EXE"` to launch script
- changed prelaunch hook to use `get_pype_execute_args`
=> TVPaint prelaunch hook fix

pype/plugins/global/publish/integrate_new.py
- representation's extension may containt dot which will break anatomy's templates
- added autofix of extension to integrate new with warning message
=> Avoid dot in repre extension

pype/hosts/nuke/__init__.py
If `WORKFILE_OPEN_LAST_VERSION` environment variable is set to "1" callback will be added to nuke for opening last available version of workfile (.nk). In case there is none available yet it will be created as version 1.
To be able to test this feature add following code to your `pype-config\environments\nuke.json`
```json
{
"WORKFILE_OPEN_LAST_VERSION": "1"
}
=> 1070 Nuke: workfile template

pype/settings/defaults/project_settings/ftrack.json, pype/settings/entities/dict_immutable_keys_entity.py, pype/settings/entities/item_entities.py, pype/settings/entities/schemas/README.md, pype/settings/entities/schemas/projects_schema/schema_main.json, pype/settings/entities/schemas/projects_schema/schema_project_ftrack.json, pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json, pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json, pype/settings/entities/schemas/system_schema/example_schema.json, pype/settings/entities/schemas/system_schema/example_template.json, pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json, pype/settings/entities/schemas/system_schema/schema_general.json, pype/settings/entities/schemas/system_schema/schema_modules.json, pype/tools/settings/settings/widgets/item_widgets.py
Modifying schemas of settings schema usage that are not used or invalid. Most of these are discovered during preparing script of converting pype-config -> settings.
- renamed `"path-widget"` type to `"path"`
- `"path"` entity's widget have ability to have set `use_label_wrap`
- Ftrack removed items for additional paths to user/server actions/events from project settings
=> Settings schemas cleanup

pype/hosts/maya/api/__init__.py, pype/hosts/maya/hooks/pre_copy_mel.py, pype/hosts/maya/lib.py, pype/tools/workfiles/app.py
- Pype used `[copy]` key from application toml's but tomls are not used anymore
- as far as I know it was used only in Maya and in specific occations
- workfiles tool emmits signal `'before.workfile.save'` and `'after.workfile.save'`
- pype's maya host has new `lib.py` outside `/api` folder where is function `copy_workspace_mel`
- added prelaunch hook to maya which use `copy_workspace_mel` to copy workspace.mel before host start
- maya implementation capture `'before.workfile.save'` signal and use `copy_workspace_mel` to copy workspace.mel in callback
=> Maya copy mel

pype/plugins/nuke/publish/submit_nuke_deadline.py
At the moment we are not able to add any additional environment variables or override some we already have, but they need to be having different values for deadline workers. For example, if we want to have different licensing.
Add this to your `pype-config\repos\pype-config\presets\plugins\nuke\publish.json`
```json 
{
"NukeSubmitDeadline": {
"env_overrides": {
"TESTENV": "testenv value",
"FTRACK_SERVER": "overriding this key with this value"
}
}
}
=> nuke deadline submit with environ var from presets overrides

pype/plugins/hiero/publish/collect_clips.py
This allows support for track items that are shorter than the rest. For example publishing the first couple of frames for static camera shots.
=> Only extend clip range when collecting.

pype/tools/launcher/constants.py, pype/tools/launcher/delegates.py, pype/tools/launcher/models.py, pype/tools/launcher/widgets.py
- added animation to launched action in launcher tool
=> Animated launch in launcher tool

.gitignore, pype/plugins/nuke/load/load_image.py, pype/plugins/nuke/load/load_mov.py, pype/plugins/nuke/load/load_sequence.py
Some clients were demanding control over nuke node name formatting
`asset` = assert name in the context
`subset` = subset name in the context
`representation` = name of the representation in the context
`ext` = extension of the representation in the context
`id` = ID hash of the representation in the context
`class_name` = actual plugin name
Add following code to your `pype-config\presets\plugins\nuke\load.json`
```json
{
"LoadSequence": {
"name_expression": "Read_{ext}"
}
}
=> Nuke: adding preset for a Read node name to all img and mov Loaders

pype/lib/applications.py
Check of executable existence is based on function `distutils.spawn.find_executable` which does not allow .bat, .sh, etc. files. This function was used to be able determine if executable is realy executable or helps to find entered executable in `"PATH"`.
- executable path is still checked with `distutils.spawn.find_executable`. But if result of the function is None and executable path exist, it is used as it is.
=> Application executable check is less strict

setup.py
Harmony implementation is using python module `filecmp` which is not available in current build of pype (probably because cx_freeze does not resolve it as used module)
- added `filecmp` to required modules in setup.py
=> Harmony missing module

README.md, start.py, test_localsystem.txt
When running Pype from sources using manually activated venv pype root was not correctly determined. Also `README.md`  was obsolete in a way how to run Pype from sources. This PR is fixing this.
=> bug: pype root determination when running from sources

pype/hosts/maya/expected_files.py
Redshift in Maya support generated wrong named expected file lists for publishing on farm. This is fixing it.
=> Maya: fixes for Redshift support

pype/plugins/maya/create/create_camera.py
Maya `CameraRig` Creator had old superclass causing syntax error and skipping loading of whole camera creator plugin.
=> Maya: Bugfix: superclass for CreateCameraRig

pype/plugins/nuke/publish/submit_nuke_deadline.py
`NUKE_TEMP_DIR` is user dependent, so submitting to the farm generates errors because Nuke cant set the cache to this directory.
=> Ensure "NUKE_TEMP_DIR" is not part of the Deadline job environment.

pype/settings/entities/dict_mutable_keys_entity.py, pype/settings/entities/exceptions.py, pype/settings/entities/schemas/system_schema/example_schema.json, pype/tools/settings/settings/widgets/dict_mutable_widget.py
- reimplemented `"required_keys"` in settings entity type `dict-modifiable`
- it should not be possible to change key if an required key or remove required key from entity
- UI settings disable key input for required keys and their items are at the top
=> Modifiable dict with required keys

pype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py, pype/modules/ftrack/lib/avalon_sync.py
- sync to avalon does not override task types but only add new one if are not available
- applications are poped from project's data
- applications have only `"name"` key as label is not used
- fixed bug with missing old parent document
- fixed value types of synchronized items on change and sync
- fixed a lot of found bugs or slow parts
=> Sync anatomy modifications

pype/settings/entities/input_entities.py, pype/settings/entities/schemas/README.md, pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json, pype/tools/settings/settings/widgets/item_widgets.py
- settings item `raw-json` can define if value is dictionary or list
- added `"is_list"` key to schema which can be `true` or `false` by default is `false`
- raw json can have 2 value types `dict` and `list` and in most of cases is used `dict` so it seemed to me that it is better to define one of them with boolean value
- modified already existing schema using raw json as list
=> Settings raw-json value type

pype/plugins/nuke/publish/submit_nuke_deadline.py
Implementation of the Limits group attribute for submission in the JobInfo Payload attributes.
This feature will secure better handling the nuke plugin licensing when, for example, an user machines are working with Neat Video demo plugin and Render farm workers in a limited number of all workers are fully licensed.
Limit groups will be defined as pairs in Nuke deadline submitter presents where the key will be name of limit group and value will be a list of plugin's node class names. Thus, when a plugin uses more than one node, these will be captured and the triggered process will add the appropriate limit group to the payload jobinfo attributes.
1. go to Deadline Monitor and open Limit panel
2. crate testing license limit groups
3. Add following lines to your …
=> Nuke: deadline submit limiting group filter

pype/plugins/global/publish/collect_audio.py
**Motivation**
Audio is not added to our Nuke reviews.
**Implementation**
The collection will search for a subset called "audioMain" by default but this is a plugin attribute, so can be configured per studio.
On the subset a representation is hardcoded to "wav", which is more universally compliant, but we could make this a plugin attribute if a use-case is found.
If version, representation or file is not found, it'll only warn the user rather than fail.
=> Collect audio for farm reviews.

pype/plugins/global/publish/extract_jpeg.py
need to wrap all paths in jpeg extractor to make them work with spaces.
=> Fix path spaces in jpeg extractor

pype/settings/entities/__init__.py, pype/settings/entities/base_entity.py, pype/settings/entities/dict_immutable_keys_entity.py, pype/settings/entities/dict_mutable_keys_entity.py, pype/settings/entities/enum_entity.py, pype/settings/entities/exceptions.py, pype/settings/entities/input_entities.py, pype/settings/entities/item_entities.py, pype/settings/entities/list_entity.py, pype/settings/entities/root_entities.py, pype/tools/settings/settings/widgets/categories.py
- settings entities are not using `ValueError` but `EntitySchemaError` that always shows path of entity and class with reason
- added type of enum item types which must be always string (and it's validation)
- abstracted enum entity to be able differentiate schema validations for `enum`, `enum-apps` and `enum-tools`
- entity `text` can convert value from numbers to string
=> Settings exceptions

setup.py
Python's pywin32 module behavior is not the same from code as from build. In build it is not possible to import submodules of `win32com`, reason is that most of them are actually not imported from `win32com` but from `win32comext`, which is handled with python code inside which is not possible in build. Also there are few missing packages of `pywin32` module in setup.py.
- specify more packages of pywin32 module
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/305|
=> Fix TVPaints usage of pywin

pype/plugins/nuke/publish/submit_nuke_deadline.py
The for loop was testing node.Class () in presenting string and so the string would need to be precise. In the case of the plugin update and the node class version change, nothing would be found until the preset changes. But if we flip the search and look for a predefined string within a node.Class () we might make it more versatile by adding a string without version number.
=> fix(nuke): reverse search to make it more versatile

pype/settings/entities/__init__.py, pype/settings/handlers.py, pype/tools/settings/settings/widgets/categories.py
- settings handler does not create settings entity until they are needed
- settings tool can catch error and show it as message
- implementation is not "Nice" but still better to show a dialog message than shutdown whole app
- it can't catch all errors that are happening with settings before settings UI is created
- when error happens in system settings the message will show up twice as project settings are using system settings values inside
- remove one of required keys from any schema item (like "type")
=> Settings UI error catch

pype/settings/defaults/project_settings/maya.json, pype/settings/defaults/project_settings/nuke.json, pype/settings/entities/schemas/projects_schema/schemas/template_publish_plugin.json
- plugins with `optional` key also have `active` key to be able define if are turned on/off by default
=> Active key for optional plugins

pype/settings/defaults/project_settings/deadline.json, pype/settings/defaults/project_settings/maya.json, pype/settings/entities/schemas/projects_schema/schema_project_deadline.json, pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Changes following PR https://github.com/pypeclub/pype/pull/1186
- added `active` key to remaining optional plugins
=> Remaining active key for optional plugins

pype/plugins/publish/extract_review.py, pype/settings/defaults/project_settings/global.json, pype/settings/entities/input_entities.py, pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
- plugin `ExtractReview` does not have possibility to define output resolution for output definition in settings
- output definiton has `width` and `height` keys to be able specify resolution
- values are ignored if one of them is set to `0`
- `number` entity may have defined `default` value
=> Extract review with resolution

pype/__init__.py, pype/hosts/celaction/api/cli.py, pype/lib/__init__.py, pype/lib/applications.py, pype/settings/defaults/project_settings/global.json, pype/settings/defaults/system_settings/general.json, pype/settings/entities/schemas/projects_schema/schema_project_global.json, pype/settings/entities/schemas/system_schema/schema_general.json, pype/tools/standalonepublish/publish.py, pype/tools/standalonepublish/widgets/widget_components.py
- removed usage of `PYPE_PROJECT_PLUGINS` and `PYPE_STUDIO_PLUGINS` environments variable
- removed settings item of `PYPE_PROJECT_PLUGINS` from system settings
- added `project_plugins` and `project_environments` keys to project settings under global
- `project_plugins` can have multiple paths for each platform
- `project_environments` are set before application launch and before publish in standalone publisher
=> Project plugin paths and envs

pype/lib/__init__.py, pype/lib/plugin_tools.py, pype/plugin.py, pype/plugins/standalonepublisher/publish/collect_bulk_mov_instances.py, pype/plugins/standalonepublisher/publish/validate_task_existence.py, pype/tools/standalonepublish/widgets/widget_family.py
- `get_subset_name` logic moved from `PypeCreatorMixin` to pype.lib
- gives ability to use it anywhere
- separated logic of creating new instances for for batch and bulk mov publishing
- this is to not break PSD batch publishing while bulk mov must be fixed
- bulk mov was simplified and has ability to se multiple task names that are checked to be set
- Bulk mov publishing is using the moved function `get_subset_name` to create subset name of renders
- added validation of task name existence on asset document
=> Bulk mov strict task

pype/modules/ftrack/ftrack_server/lib.py
Ftrack api's Session has new attribute which is not available in our modified Session so it is not possible to start ftrack server with newer versions of ftrack api.
- new ftrack api session has new attribute `request_timeout` which is not available in modified session class
- few updates in custom session
=> Update custom ftrack session attributes

pype/modules/ftrack/actions/action_create_cust_attrs.py
Forwards compatible changes for Pype 3.
- tool names in custom attribute are stored with slash, with replacing first underscore
- this is because tools are stored with slash in Pype 3 where separate tool's group name and tool's variant name (See in [PR](https://github.com/pypeclub/pype/pull/1190) )
Running **Create/Update Custom Attributes** will cause to loose data about previous tools and applications. We should probably prepare a way how to store their values per entity and reapply after change.
|---|---|
|pype-config|https://github.com/pypeclub/pype-config/pull/105|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/307|
=> Forwards compatible config

pype/plugins/harmony/create/create_farm_render.py, pype/plugins/harmony/create/create_render.py, pype/plugins/harmony/create/create_template.py, pype/plugins/tvpaint/create/create_render_layer.py, pype/plugins/tvpaint/create/create_render_pass.py, pype/plugins/tvpaint/create/create_review.py
It was pointing to 3.0 structure ('.hosts.api') previously
No creators showed up previously
=> Fix - modified path of plugin loads for Harmony and TVPaint

pype/lib/profiles_filtering.py
- check for full match instead of simple match when checking for values in profile
- `render` regex won't match `render_bulk_mov` anymore
||Pype 3 PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1213|
Resolves: https://github.com/pypeclub/pype/issues/1211
=> Fix regex checks in profiles filtering

pype/hosts/blender/hooks/pre_pyside_install.py
- implemented prelaunch hook that will try to install PySide2 to blender
- works only on windows
- if hook won't find blender's python executable then will skip whole process 
- when executable is `.bat` or `.ps1` file or different version
- current settings does not allow to turn it off (may be annoying)
- execution of prelaunch hook is not crutial, blender is still launched if will crash
=> Blender auto PySide2 install hook

pype/plugins/nuke/publish/collect_writes.py
- collecting write node was getting `colorspace` knob with `default()` string and was causing later errors in review extracting
=> Nuke: write node colorspace ignore `default()` label

pype/plugins/nuke/publish/collect_writes.py, pype/plugins/nuke/publish/submit_nuke_deadline.py
there might be a occasions where anyone would need to search replace any environment values. This will add ability to add dictionary with pairs to presets which are then iterated on each environment value.
=> Nuke: deadline submission with search replaced env values from preset

pype/hosts/nuke/api/__init__.py, pype/hosts/nuke/api/menu.py
- reimplemented [PR](https://github.com/pypeclub/pype/pull/877) so it's possible to use pype's workfile tool in nuke
- changes were probably lost with commit `434f1615e4e379a3a7e7cff006468199eb3a2b46`
Resolves https://github.com/pypeclub/pype/issues/1216
=> Pype's workfiles tool in nuke

pype/modules/websocket_server/hosts/aftereffects.py, pype/modules/websocket_server/stubs/aftereffects_server_stub.py, pype/plugins/aftereffects/create/create_render.py, pype/plugins/aftereffects/load/load_background.py, pype/plugins/aftereffects/load/load_file.py
AfterEffects were missing SubsetManager in 2.x
Requires:
pypeclub/avalon-core#309
=> AE - added SubsetManager

pype/settings/handlers.py
- settings are stored as dictionaries instead of json string
- that is possible since [PR](https://github.com/pypeclub/pype/pull/1190)
=> Settings in mongo as dict

pype/plugins/harmony/publish/collect_farm_render.py
2.x version of pypeclub/pype#1225
Issue:
When rendered on farm files with duplicated task name were produced after change of template to explicitly contain Task name (`renderAnimationAnimationDefault`)
If Task name is explicitly set in template, it duplicated
it here. Task name might need be in template, but by default it should be in subset name.
This whole replace situation is because of avalon's Creator which modify subset name even if it shouldn't.
If Creator app is reworked (could have wide impact!), this should be cleaned up.
=> Fix - handle duplication of Task name

pype/tools/settings/settings/widgets/item_widgets.py
- hide expanding(collapse) button if content layout does not have any widget
=> Hide expand button if content does not contain any widget

pype/modules/deadline/plugins/publish/submit_nuke_deadline.py, pype/settings/defaults/project_settings/deadline.json, pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Implementation of https://github.com/pypeclub/pype/pull/1167
=> Nuke: deadline submit limit group filter

pype/settings/entities/dict_mutable_keys_entity.py, pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
- mutable dict will create new children if is accessed to a key which is not yet available with `__getitem__`
- `entity["data"]["key"]` won't crash if entity is `dict-modifiable`, it's object type is dictionary entity and `"data"` was not in settings previously
- plugin `ExtractReview` has in Pype 2 tag `sequence` which is missing in Pype 3
=> Minor settings changes

igniter/bootstrap_repos.py, igniter/tools.py, start.py, tests/igniter/test_bootstrap_repos.py, tests/igniter/test_tools.py, tools/run_mongo.ps1
This PR is unifying paths to repositories (submodules) to be the same as in live source code - *avalon-core* and others are now again in repos and module depth is same as in live code so relative paths to Pype parts are identical.
=> Pype 3: modules path unification in zips/dirs

openpype/modules/ftrack/ftrack_module.py
Ftrack url won't work is ends with slash `/` which is common mistake when copied from browser and not much issue.
- strip slash and space from ftrack url
=> Ignore Ftrack url slash

pype/modules/ftrack/actions/action_apps_tools_conversion.py
This PR is part of forwards compatibility to Pype 3 following [Forwards compatible config PR](https://github.com/pypeclub/pype/pull/1197).
We have to modify Pype 2 configs to be able use same Ftrack for Pype 2 and Pype 3. The most important differnce is in custom attributes `applications` and `tools_env` where we have to modify values.
- applications must be without dots and enum items must match variants we have in Pype 3 settings
- tools also must be without dots and must have `slash` in name which is because in pype 3 tools have group and variant, the slash is separator of (`{group}/{variant}`).
- implemented ftrack action `Pype Admin - App & Tool values` that may help us to do the conversion step without loosing data on ftrack
1. Before any changes in config run new action `Pype Admin …
=> Apps tools prep action

pype/plugins/global/publish/extract_hierarchy_avalon.py, pype/tools/assetcreator/app.py
- `avalon-core:asset-3.0` replaced with `pype:asset-3.0` in code
=> Avalon schema names

pype/modules/ftrack/lib/avalon_sync.py, pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
- ftrack attribute configuration query can expect `openpype` custom attribute
=> Forward compatible ftrack group

igniter/__init__.py
Import of igniter always trigger import of Qt in `__init__.py` file which may cause error even if Qt is not used.
- moved Qt related imports into related function (`open_dialog`)
- find out why crashes
- should be tested if crashes from code/build I think issue is that if it's launched from code venv is not added to sys.path
=> Igniter qt import

openpype/tools/settings/settings/widgets/dict_mutable_widget.py
- content of `dict-modifiable` item is always offset even if does not contain label
- Don't use `CHILD_OFFSET` if modifiable dictionary does not contain label
=> Modifiable dict offset in UI

.gitmodules
Submodules are defined with ssh access schema requiring user to have GitHub account. This PR changes this to less restricting https schema.
=> Repository: Switch from ssh to https for submodules

openpype/lib/anatomy.py
Pype 3 version of https://github.com/pypeclub/pype-setup/pull/92/files
- `root_value_for_template` crashes as found key is without formatting 
- fix `root_value_for_template` method in Anatomy
||Pype 2 PRs|
|---|---|
|pyp-setup|https://github.com/pypeclub/pype-setup/pull/92|
=> Fix root return in Anatomy

openpype/hosts/aftereffects/plugins/publish/collect_render.py
Orphaned instance points to composition that doesn't exist anymore. 
It produced error in "Collect After Effects Render Layers" (`cannot get workAreaStart from value None`)
Delete that instance, log warning
2.x version:
pypeclub/pype#1275
=> AE remove orphaned instance from workfile

pype/plugins/aftereffects/publish/collect_render.py
Version for 2x.
pypeclub/pype#1274
Orphaned instance points to composition that doesn't exist anymore.
It produced error in "Collect After Effects Render Layers" (cannot get workAreaStart from value None)
Delete that instance, log warning
=> Fix AE remove orphaned instances

openpype/hooks/pre_with_windows_shell.py, openpype/lib/applications.py
Some arguments are not correctly converted when prelaunch hook `LaunchWithWindowsShell` is used. They are mixed with command line arguments so are not parsed correctly. This is mainly issue when quotation mark `"` is part of any argument or path has spaces.
- launch arguments collected before the prelaunch hook are converted to string using `subprocess.list2cmdline`
- the prelaunch hook must be executed as last hook modifying launch arguments
- creation flags of subprocess are changed to `CREATE_NEW_CONSOLE`
- whole arguments are passed to `subprocess.Popen` as string not as list
- this is required otherwise python's `subprocess` module will try to deparse and parse arguments again
- launch context can expected launch arguments as string
Not sure why `resolve` is one of applications that …
=> Shell prelaunch hook fix

openpype/settings/lib.py
Local settings load executables still old way (with arguments) which cause crashes.
- executables from local settings are loaded as expected
=> Fix executables from local settings

openpype/modules/idle_manager/idle_module.py, openpype/modules/timers_manager/timers_manager.py, openpype/settings/defaults/system_settings/modules.json, openpype/settings/entities/schemas/system_schema/schema_modules.json
- idle manager module is always enabled but won't start it's thread if there are any registered timer callbacks
- so don't have to be in settings UI
- timer manager has `auto_stop` attribute which defines if timer will be automatically stopped sowill register it's callbacks to idle manager
=> Idle manager without settings

igniter/bootstrap_repos.py, igniter/install_dialog.py, igniter/install_thread.py, igniter/user_settings.py, openpype/lib/__init__.py, openpype/lib/local_settings.py, start.py, tests/igniter/test_bootstrap_repos.py, tests/pype/lib/test_user_settings.py
Class `PypeSettingsRegistry` in `pype.lib` was not renamed to `OpenPypeSettingsRegistry` and is using bad keys.
- fixed `"pype"` -> `"openpype"` in `pype.lib.local_settings`
- extracted secure items logic from `ASettingRegistry` to `OpenPypeSecureRegistry`
- this is because to be able access to secure items it was required to create `IniSettingRegistry` or `JSONSettingRegistry` object
- it is possible to specify name where data will be stored but to all names is added prefix `"OpenPype/"` to easily see what was created by pype
- it is also possible to specify name of registry for `OpenPypeSettingsRegistry`
- secure item of `openPypeMongo` is stored under `"OpenPype/mongodb"` key in keyring
- code of registry is same in both igniter and pype.lib it would be better if in pype is possible to …
=> OpenPype settings registry

.github/workflows/test_build.yml, start.py
When running from build, we were removing the build folder from sys.path but not adding the picked up repository version to pythonpath in turn. 
that resulted in openpyne not being importable from hosts
=> add openpype_root to pythonpath

pype/modules/ftrack/actions/action_create_cust_attrs.py
- Create/Update custom attributes action will ignore if `"pypeclub"` role is missing
=> Ftrack optional pypclub role

openpype/modules/ftrack/lib/avalon_sync.py
- on larger projects custom attributes value query may crash because of timeout (e.g. 10 custom attribute values for 20000 entities)
- custom attribute values are not queied at once by in chunks
||Pype 2 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1312|
=> Ftrack custom attributes in bulks

openpype/hosts/blender/api/__init__.py, openpype/hosts/blender/plugins/publish/validate_object_mode.py
This PR include two small improvements for Blender. 
- When opening or creating a new file, Blender will load the scene settings (start/end frame, fps and resolution) from Ftrack
- A new validator to check that all the objects that are being published are in Object Mode
=> Blender: Load Scene Settings from Ftrack and New Validator for Object Mode

openpype/hosts/tvpaint/plugins/publish/collect_instances.py, openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py, openpype/hosts/tvpaint/plugins/publish/validate_project_settings.py, openpype/settings/defaults/project_settings/tvpaint.json, openpype/settings/entities/schemas/projects_schema/schema_main.json, openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
The validator checks the asset data to the project settings on these member;
- resolution
- framerate
- pixel aspect
- frame range
The validator does not have any repair because when publishing, changing this data can result in loss of work, so it needs user care to resolve.
Had to prefix the data member, with `scene`, collected from TVP because they were otherwise being overwritten by https://github.com/pypeclub/pype/blob/2.x/main/pype/plugins/global/publish/collect_avalon_entities.py
+ added TVPaint plugin settings
||Pype 2 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1297|
=> Validate project settings

openpype/modules/ftrack/event_handlers_server/action_prepare_project.py, openpype/modules/ftrack/event_handlers_user/action_prepare_project.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
- converted Ftrack action Prepare Project to Pype 3
- action is now available from server too
- actions have separate settings
- removed option to trigger create folder structure (saves 1 click)
- can be added for local version in next PR
- prepare project is using `ProjectSettings` to define values (not using custom attribute values unless it's only in custom attributes)
- server action is under group `"OpenPype Admin"` and has `" (Server)"` suffix
- action doesn't have icon and name is too long + this way local version can be without suffix
=> Prepare project Ftrack action in Pype 3

pype/hooks/tvpaint/prelaunch.py, pype/hosts/tvpaint/__init__.py, pype/hosts/tvpaint/lib.py
This sets the TVP project settings when launching for the first time.
To figure out when the users is launching for the first time, I've added `PYPE_TVPAINT_LAUNCHED_TEMPLATE_FILE` to the environment. Only when this environment variable is present will the code modify the project settings.
||Pype 3 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1325|
=> TV Paint: Set initial project settings.

openpype/hooks/pre_python2_vendor.py, openpype/lib/__init__.py, openpype/lib/import_utils.py, openpype/lib/pype_info.py, openpype/settings/defaults/system_settings/applications.json, openpype/settings/defaults/system_settings/general.json, start.py
We currently have `OPENPYPE_ROOT` and `OPENPYPE_REPOS_ROOT` both lead to same direcotry path of used openpype version on launch but we don't have defined path to executable directory or code directory. It was discussed that `OPENPYPE_ROOT` should be used for this purpose and lead to executable directory or code directory all the time and `OPENPYPE_REPOS_ROOT` to root of used version ([Discussed here](https://github.com/pypeclub/pype/pull/1240/files))
- `OPENPYPE_ROOT` is not used to store path to directory of used openpype version but to directory of executable or code source
- `OPENPYPE_REPOS_ROOT` replaced usage of `OPENPYPE_ROOT` in settings and code
=> OpenPype root redefinition

pype/plugins/maya/create/create_look.py
`make tx` option in look creator was not set to be configurable with creator plugin presets.
=> Maya: Make tx option configurable with presets

pype/plugins/tvpaint/publish/collect_instances.py, pype/plugins/tvpaint/publish/collect_workfile_data.py, pype/plugins/tvpaint/publish/validate_marks.py, pype/plugins/tvpaint/publish/validate_project_settings.py
This validator checks whether the mark in and out are enabled, and set to the database settings.
If mark in/out are disabled, TVP will return the exposure frame range. In some cases the exposure frame range and the shots frame range can differ, so it more consistent to make sure the mark in/out are set and enabled.
When rendering the last frame gets extended to the fill the mark out range.
This has a repair action for enabling and setting the mark in/out to the database asset settings.
||Pype 3 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1334|
=> TV Paint: Validate mark in and out.

pype/plugins/tvpaint/publish/collect_workfile_data.py, pype/plugins/tvpaint/publish/validate_asset_name.py, pype/plugins/tvpaint/publish/validate_workfile_project_name.py
- implemented asset name validation on each instance for publishing
- asset name for publishing is used from collected instance from metadata which are handled only "On Create"
- workfile context is not used from "current context" (in `api.Session`) if workfile does not contain metadata
||Pype 3 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1319|
=> TVPaint asset name validation

openpype/tools/tray/pype_info_widget.py
- pype info widget is wrapped into scrollable area so not matter how much environments are set all can be visible without moving the window out of desktop
- set default size (maybe default size on open is too small)
=> Pype info window scrollable

openpype/hooks/pre_python_2_prelaunch.py
- Changes in https://github.com/pypeclub/pype/pull/1354 may break some python 2 hosts because of incompatible setuptools\s `pkg_resources`
- moved back Python 2 prelaunch hook which set's path to `pkg_resources` before launch
=> Python 2 setuptools bug fix

openpype/modules/ftrack/ftrack_module.py, openpype/modules/ftrack/lib/credentials.py, openpype/modules/ftrack/tray/ftrack_tray.py, openpype/modules/ftrack/tray/login_dialog.py
- ftrack url is filled with schema (`https`) if is not in settings and finished with `.ftrackapp.com` if is not part of url
- ftrack module won't crash if FTRACK_URL is not set
- ftrack login gui shows only ftrack url input and error message if ftrack url is not set
=> Ftrack URL cleanup

openpype/hosts/maya/plugins/publish/extract_vrayscene.py, openpype/hosts/maya/plugins/publish/validate_unreal_mesh_triangulated.py
There are some invalid imports and usage of variables in Openpype.
- fix import `openpype.hosts.maya.render_setup_tools` -> `openpype.hosts.maya.api.render_setup_tools`
- fix variable name `ValidateMeshOrder` in `ValidateUnrealMeshTriangulated`
=> Maya import bugs

pype/plugins/hiero/publish/collect_calculate_retime.py, pype/plugins/hiero/publish/collect_clips.py, pype/plugins/hiero/publish/collect_frame_ranges.py, pype/plugins/hiero/publish/collect_plates.py, pype/plugins/hiero/publish/collect_review.py, pype/plugins/hiero/publish/collect_tag_framestart.py
also review wrong sequence definition
=> Hiero: fixing source frame from correct object

pype/plugins/global/publish/integrate_new.py, pype/plugins/maya/create/create_redshift_proxy.py, pype/plugins/maya/load/load_redshift_proxy.py, pype/plugins/maya/publish/extract_redshift_proxy.py
=> Maya: Support for Redshift proxies - backport of #1358 for Pype 2

openpype/settings/defaults/system_settings/applications.json
- added `use_python_2` to unreal's defaults
=> Unreal miss default settings

pype/plugins/maya/publish/collect_look.py
This is Pype 2.x backport of #1397
=> Maya: Vray - problem getting all file nodes for look publishing

pype/hosts/maya/__init__.py
A better question might be whether this is actually needed?
This pop up is not present in any other host (as far as I know), and the only thing it does is to stop loading of the workfile and inform the user about what they have done. User cant cancel so it seems like a needless pop up.
=> Add task name to context pop up.

openpype/settings/defaults/project_settings/global.json
New ffmpeg do not allow to define `-gamma 2.2` on most of inputs (.png, .jpeg, etc.).
Found out that it is video filter configuration of an output instead of input definition. This approach was not tested properly yet. Results with this configuration should be compared to previous results and try to export both video and image sequence.
- add gamma as video filter in ffmpeg arguments
=> FFmpeg gamma argument

openpype/hosts/blender/hooks/pre_pyside_install.py
- modified pyside installation in blender's prelaunch hook to be independent on application name stored in settings
- prelaunch hook skip processing if executable does not lead to `blender.exe`
=> Blender's PySide2 installer fix

openpype/plugins/publish/extract_review.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/template_rgba_color.json
- backward compatible with single float for config.
- support for pillar boxes.
- expose thickness of boxes to config.
- expose color of boxes to config.
Config of `letterbox` on the presets can be changed to a dictionary;
```
{
"state": "pillar",
"ratio": 1.777777,
"thickness": 3,
"color": "black"
}
```
- added settings of letterbox (letterbox was not in settings at all)
- letterbox has enabled key as in settings is not possible to "not set" it
||Pype 2 PRs|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1371|
=> Enhance review letterbox feature

pype/plugins/photoshop/publish/collect_instances.py
Grouped instances will show up together in Loader.
Configurable by `pype-config/presets/plugins/photoshop/publish.json`:
```
{
"CollectInstances": {
"group_by_task_name": true
}
}
```
Closes: https://github.com/pypeclub/client/issues/56
=> PS - group all published instances

openpype/plugins/publish/extract_review.py
- in settings it is possible to store list of strings where is item with empty string which can break extract review
- extract review validate values from settings and skip empty strings
=> ExtractReview skip empty strings from settings

openpype/modules/sync_server/providers/gdrive.py, openpype/modules/sync_server/providers/lib.py, openpype/modules/sync_server/sync_server.py, openpype/modules/sync_server/sync_server_module.py, openpype/modules/sync_server/tray/app.py, openpype/modules/sync_server/tray/models.py, openpype/modules/sync_server/tray/widgets.py, openpype/modules/sync_server/utils.py
Fixed:
- random HttpError during init of GDrive provider is captured, tried next loop
- increased local default of how many files per loop processed for local_drive to 50
- Sync Queue is remembering 2 sorts
- Any user change (reset site, redownload) triggered in SQ will reset timer to next loop > synching starts immediatelly
=> Bugfix Sync server tweaks

openpype/hosts/tvpaint/api/lib.py, openpype/hosts/tvpaint/plugins/publish/collect_instance_frames.py, openpype/hosts/tvpaint/plugins/publish/collect_instances.py, openpype/hosts/tvpaint/plugins/publish/extract_sequence.py, openpype/hosts/tvpaint/plugins/publish/validate_marks.py
- TVPaint implementation does not care about Mark In/Out values but only range
- Frame index of Mark In is not modified so artist can set it to different frame than `1` but duration of Mark In/Out must match to duration of asset (shot) `({frame end} - {frame start} + 1) + {handle start} + {handle end}`
- Layers that does not have any content in Mark range are skipped during extractor
- extractor extract range from Mark in/out but then rename file sequences to right names
- e.g. if Mark In is `0` and frameStart is `1001` then output `"frame.0000.png"` is renamed to `"frame.1001.png"`
- renaming is going backwards from Mark Out/Frame End to Mark In/Frame Start to avoid clashing of filenames
||Pype 2 PRs|
|---|---|
|pype|https://github.com/pypeclub/OpenPype/pull/1424|
EDITED 29.4.2022:
- as …
=> TVPaint frame range definition

openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/list_entity.py
- skip processing of settings actions if it does not make sence to execute it on item
- e.g. item without changes will skip discard changes action
- for this logic is used same approach like for logic of showing actions in UI (`can_discard_changes`, `can_remove_from_studio_default`, `can_remove_from_project_override`)
- this is based on right implementation of the validation methods so it would be great to test as much as possible
- bigger hierarchy the better to test it
=> Faster settings actions

openpype/settings/entities/dict_mutable_keys_entity.py
Modifiable dict will remove labels from metadata on remove from studio/project overrides.
1. open settings ui
2. in system settings modify any input in tools
3. show actions for tools and use `Remove from studio default` action
4. Labels from tools should disappear
- labels from metadata for the loaded state are set in remove overrides methods
=> Keep metadata on remove overrides

website/docs/admin_hosts_blender.md, website/sidebars.js
- added **Integrations** to admin category
- added **Blender** to Integrations with brief manual how to install PySide2 in blender
=> Blender PySide2 install guide

openpype/settings/handlers.py
Global settings are saved to both system and global settings document but are loaded only from system settings document which may cause issues if we'll add versioned settings.
- only place where global settings are used from right mongo document is in Igniter so igniter may use different values than are returned from `get_system_settings` function
- global settings data are removed from system settings on save
- global settings are applied on system settings on load
- system settings document is faked if is not available at all
=> Global settings save/load out of system settings

openpype/settings/entities/dict_immutable_keys_entity.py
- action "add to studio/project overrides" in settings gui won't affect metadata which cause issues on save and load of settings
- handle metadata changes on add to studio/project overrides
=> Add to overrides actions fix

openpype/settings/entities/base_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/list_entity.py, openpype/tools/settings/settings/widgets/base.py
- settings actions on entities may not be processed on dynamic items
- currently known issues are with **strict list** item which does not process any of actions properly
- settings actions are discard changes, add to studio/project overrides and remove from studio/project overrides
- issue started with https://github.com/pypeclub/OpenPype/pull/1446 where was added validation before action process but the validation also skip all dynamic items
- action validations were split into 2 parts:
1. action can be triggered on entity - kept to check if action process can start on entity (and can show action in gui on entity)
2. action can be processed on entity - any parent triggered action and entity have to handle the changes
=> Settings actions process fix

openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/list_entity.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_publish_gui_filter.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json, openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
- dynamic items does not have validated schemas (children of `list` or `dict-modifiable` items)
- on schema validation of items with dynamic children is created one temporary item and schema is validated on it (item is removed afterwards)
- fixed invalid schema data
This may cause multiple issues one of them is duplicated key in `dict` item under `dict-modifiable`.
1. go to system settings schemas and open `schema_tools.json`
2. duplicate `"environment"` child under `tool_groups` key
3. open Settings UI
- you will see invalid value (red color) but you should see warning dialog which says that schema was validated
=> Validation of dynamic items in settings

pype/modules/ftrack/actions/action_create_cust_attrs.py, pype/modules/ftrack/lib/avalon_sync.py
- modified Pype 2 to be able to handle custom attribute changes in Ftrack from OpenPype 3
Some forward compatible changes are already available in current pype and avalon-core.
- https://github.com/pypeclub/avalon-core/pull/307
- few untracked PRs in pype...
Trigger of Create/Update attributes action may cause loose of data.
=> Forward/Backward compatible apps and tools with OpenPype 3

openpype/settings/entities/base_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/list_entity.py
- `group_item` entity returns different boolean value in Python 2 and 3
- check if `group_item` is `None` instead of expecting return right boolean from object itself
=> Fix groups check in Python 2

openpype/plugins/publish/extract_burnin.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
- it is possible to set color of text and background for burnins in burnin options
=> Extract burnins with color setting

openpype/plugins/publish/extract_burnin.py, openpype/scripts/otio_burnin.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_representation_tags.json
- added possibility to set path to font for extract burnin
- path may contain environment variables `"{MY_PATH}/path/to/my/font.tff"`
- added to settings additional filtering of output definitions
- additional filtering is defined by families and tags
- don't use `shell=True` for running subprocess which may cause issues on Mac and Linux workstations
- for windows is added `CREATE_NO_WINDOW` flag which should avoid creating new terminal window
- font is not handled in burnin script but is prepared before got into the script
- default font path should be set to `LiberationSans` font which is in OpenPype resources
- default font is also used when can't access font set in settings
- start frame on processing of sequence in burnin script is also explicitly set to be start frame of an output
- …
=> Burnin custom font filepath

openpype/modules/sync_server/sync_server_module.py
If server is globally disabled, no projects should be returned
Required by:
https://github.com/pypeclub/avalon-core/pull/326
=> Fix SyncServer get_enabled_projects should handle global state

pype/plugins/nuke/publish/collect_workfile.py
As the client was pointing recently, our deadline submissions are having a versions discrepancy.
- missing version on instance data so the version is synced with db always
=> Nuke: workfile version synced to db version always 

openpype/lib/__init__.py, openpype/lib/execute.py, openpype/plugins/publish/extract_burnin.py
- some builds of python may not have constant `CREATE_NO_WINDOW` in `subprocess` module
- defined custom constant as `subprocess` may not have defined CREATE_NO_WINDOW constant in all python builds
=> Undefined constant in subprocess module

openpype/scripts/otio_burnin.py
Determination of input codec in new FFmpeg does not work the same way as in previously used version of FFmpeg.
- added few functions using codec specific keys from input data
- these functions should be modified or added in future based on requirements of each codec
- these changes should handle current situation with decreased quality of outputs
- don't have enough testing input sources to check all possibilities and validate output
- there is a chance that I broke something which worked with previous code
- result will probably never be the same as adding video filters (drawing burnins) to output will aways cause some issues
- possible solution to keep source 1:1 is to add burnins as part of ExtractReview and force all host implementations to create review with it
=> Codec determination in extract burnin

pype/plugins/maya/publish/extract_thumbnail.py
In some cases (simulation) the timeline and instance frame start do not align.
=> Use instance frame start instead of timeline.

pype/plugins/global/load/delete_old_versions.py
- Only appears once in the right click menu.
- Size user feedback is only displayed once at the end of the operation.
I have a progress indicator printed atm, but would like to have a progress bar, but I'm shit at Qt stuff. Tried showing a progress bar but could not get it to show before the operation was completed.
Depends on https://github.com/pypeclub/avalon-core/pull/329
=> Use SubsetLoader and multiple contexts for delete_old_versions

pype/tools/standalonepublish/widgets/widget_family.py
Subset hints in Creator tool dropdown do not find out other possible user inputs if user intup has different letter case than concatenated subset name. That is because user input is replaced in concatenated subset name to get possible regex to find other possible user inputs.
```
user_input = "anim"
subset_name = "renderCompositingAnim"
expected_regex = "renderCompositing(.+)"
real_regex = "renderCompositingAnim"
```
- replacement of user input in concatenated subset name is not case sensitive
||Related Prs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/333|
||Pype 2 PRs|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1503|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/334|
=> Existing subsets hints in creator

pype/plugins/global/publish/submit_publish_job.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/publish/collect_render.py, pype/plugins/maya/publish/submit_maya_deadline.py, pype/plugins/maya/publish/validate_deadline_connection.py
This feature allows to use multiple deadline webservice instance in Maya and allow user to choose from. When preset exists in `pype-config/presets/plugins/maya/create.json`:
```javascript
{
"CreateRender": {
"deadline_servers": {
"default": "DEADLINE_REST_URL",
"aws": "http://foo:2135"
}
}
}
```
Then when **render** instance is created in Maya, it will add *Deadline Servers* combo box to its attributes:
It uses key as alias and values as its url. `DEADLINE_REST_URL` will be replaced by the one set with the same named environment variable. When user select different server, pools are queried from it.
Collector will then "bake" this value to `deadlineUrl` in published instance and rest of the plugins will use that.
**Note:** when this preset is not set, it will work as usual with …
=> Maya: Use of multiple deadline servers

openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json, openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json, openpype/tools/settings/settings/dict_mutable_widget.py
Sometimes it is required to store dictionary with invalid characters in key for mongo and only possible way how to do it is to store dictionary as list of 2 size lists.
This change does not add ability of ordered dictionary!!!
- added ability to store, load content of modifiable dict as list of lists (set key `"store_as_list"` to true in schema)
- if stored data are dictionary but output should be list entity won't tell that there is a change
- modifiable dict can't store metadata about labels and environments
- this is maybe not properly handled (it is possible to set label but won't be stored)
- as loaded may contain both dict and list of list only way how to handle this change is in code
- easiest is to always convert loaded data to dict `dict(data)`
- `dict` type can convert dict to …
=> Store data from modifiable dict as list

pype/plugins/maya/publish/extract_redshift_proxy.py
This sets proper start frame on redshift proxy representation if animation is turned on.
=> Maya: Redshift - set proper start frame on proxy

pype/plugins/global/publish/extract_review.py, pype/plugins/maya/publish/extract_playblast.py
2.x version of https://github.com/pypeclub/OpenPype/pull/1515
=>  Maya: wrong collection of playblasted frames

openpype/hosts/maya/plugins/publish/extract_playblast.py, openpype/plugins/publish/extract_review.py
Logic for collection playblasted frames was dependent pretty much on pure luck. This PR makes it explicit.
=> Maya: wrong collection of playblasted frames

openpype/__init__.py
- objects passed to pyblish loggers are kept as objects until are shown in UI so in UI are not shown data representing state at the moment of logging but at the end of plugin processing
- change pyblish `MessageHandler` emit method to convert messages to string at the moment of emmiting
=> Convert pyblish logs to string at the moment of logging

openpype/settings/entities/dict_mutable_keys_entity.py
Added feature to store modifiable dictionary as list is always resolved as modified on load. That is because on load are data autoconverted to dictionary which is not same type as output type and is not resolved in any way.
- initial value has same type as output type so settings does not recognize initial values as changed
=> Store as list dictionary check initial value with right type

igniter/bootstrap_repos.py, poetry.lock, pyproject.toml, start.py, tests/igniter/test_bootstrap_repos.py, tools/build.ps1
This PR is adding [semver module](https://pypi.org/project/semver/) and utilizing it for version resolution. `OpenPypeVersion` is extending `semver.VersionInfo`. It is adding `path` and `staging` attributes to it and slightly changing how staging is working.
```
3.0.0-rc.1+staging < 3.0.0-rc1
3.0.0+staging < 3.0.0
3.0.0-rc.1+foo-staging < 3.0.0
3.0.0 < 3.0.0 (with path set)
3.0.0 (with zip as path) < 3.0.0 (with dir as path)
```
This is also adding itself to version list detected during startup, so when we are running newer version then those already installed, current running version will be used.
resolves #1505
=> OpenPype: use `semver` module for version resolution

openpype/modules/sync_server/providers/local_drive.py, openpype/modules/sync_server/sync_server_module.py
Regular loop needs correctly named sites, Local Settings need 'local' instead of real name of local site. `(loop wouldn't work at all)`
Fix for possible race condition on slower networks `(intermittent WinError 2)`
=> Bugfix Sync server local site issues

openpype/settings/entities/base_entity.py, openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json, openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json, openpype/settings/entities/schemas/system_schema/schema_modules.json
Settings entities may be marked to store their content into file even if their parent entity is already marked to storing to file. This may cause issues in future.
- removed invalid `is_file` attributes from schema
- added validation of the attribute - entity can't have set `is_file` attribute to True if any parent already has
=> Validate is file attribute in settings schema

openpype/plugins/publish/collect_anatomy_context_data.py
IntegrateNewAsset plugin is using `instance.data["anatomyData"]["app"]` but "app" is filled only if application is one of applications defined as host integration.
- first tried value for `"app"` is taken from env variable `AVALON_APP` which is actually reserverd for host name
- if `AVALON_APP` is not defined then is tried to look for host name with `AVALON_APP_NAME` and `ApplicationManager`
- when host name is found out it is set back to `AVALON_APP`
- that is because `AVALON_APP` is used for filtering on some places
=> Host name collecting fix

openpype/hosts/photoshop/plugins/create/create_image.py, openpype/hosts/photoshop/plugins/publish/extract_image.py, openpype/hosts/photoshop/plugins/publish/extract_review.py, openpype/settings/defaults/project_settings/photoshop.json, openpype/settings/entities/schemas/projects_schema/schema_main.json, openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Closes: https://github.com/pypeclub/client/issues/72
PS was hardcoding 'image' into subset name ignoring possible different value expected for Subset configured in `Settings > Project > Global > Tools > Creator`
PS is creating quick review with all visible layers if no 'image' instances are created (`previously blank picture`)
=> Bugfix  PS subset and quick review

openpype/settings/defaults/project_settings/tvpaint.json, openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
TVPaint loaders don't have schemas for their settings.
- added settings for `LoadImage` and `ImportImage` loaders both have same settings
- both have ability to modify families because a client have modified them, but we should maybe go through them and look if we can keep families out of settings?
- maybe we could get rid of `ImpotImage` loader not sure if would anybody use it anymore?
=> TVPaint loader settings

openpype/tools/project_manager/project_manager/model.py
Duplicated tasks are not handled properly on delete task in worst cases it will crash project manager.
- removed task tells to it's asset that was removed and should not care about it's name duplicity
- task name operations are ignored on asset item level if task is marked as removed
=> Handle duplicated task names in project manager

openpype/hosts/blender/__init__.py, openpype/hosts/blender/api/__init__.py, openpype/hosts/blender/api/lib.py
Blender can have set only one `BLENDER_USER_SCRIPTS` which is already occupied by OpenPype implementation.
- blender install method also register plugins/scripts/addons from `OPENPYPE_BLENDER_USER_SCRIPTS`
- advantage is that it should be possible to register multiple paths
- this implementation is using "copy" of inner blender python module function so it may change over time
- tested only on Windows with my custom plugin (didn't find other plugin that would use BLENDER_USER_PATH)
- implemented only OpenPype 3 variant
- `OPENPYPE_BLENDER_USER_SCRIPTS` was added with [PR](https://github.com/pypeclub/OpenPype/pull/1522)
Closes: https://github.com/pypeclub/OpenPype/issues/1050
=> Blender can initialize differente user script paths

pype/plugins/global/load/delete_old_versions.py
- Ensure `file_path_base` item are in list before removing.
- Ensure there is `data` to process.
=> More failsafes prevent errored runs.

pype/modules/ftrack/actions/action_delete_asset.py
- ftrack delete action may cause circular error
- ftrack entities are deleted by their link length (link contain all hierarchy of entity)
- higher link entities are removed as first to avoid removing of already deleted entity
- `AvalonMongoDB` is created on action initialization
- run action on multiple entities with children having published content and asset versions on tasks
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1579|
=> Ftrack delete action cause circular error

pype/lib/delivery.py, pype/plugins/global/load/delivery.py
Only single file was being created and overwritten in case of sequence
=> Delivery in LibraryLoader - fixed sequence issue

openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py, openpype/modules/ftrack/lib/avalon_sync.py
- sync to avalon store `"hierarchy"` key in asset document which is not used in code (`"parents"` key is used instead)
- sync to avalon action and event are not storing `"hierarchy"` key on asset document
Closes https://github.com/pypeclub/OpenPype/issues/432
=> Sync to avalon do not store hierarchy key

tools/build.ps1, tools/build.sh, tools/create_env.ps1, tools/create_env.sh, tools/create_zip.ps1, tools/create_zip.sh, tools/run_tests.ps1, tools/run_tests.sh
running `/tools/create_env.ps1` cleaned python cache files (pyc/pyo/__pycache__) in whole openpype directory, including **build** directory. When something was there, it deleted cache file from there too even from necessary python system files. This broke the build with error like "invalid fs encoding".
This fix is directly excluding `build` directory from cleanup.
It is also specifying on Windows that OpenPype requires Python 3.7. It is prohibiting to run it with older versions and write warning if running with newer.
=> Build: stop cleaning of pyc files in build directory

openpype/settings/entities/dict_mutable_keys_entity.py
Dict mutable dict has bug in logic when loading data stored as list. It's appending `key: value` into list but not as list.
- fix list appending, values are stored as 2 items in single list
=> List append fix in mutable dict settings

pype/hosts/maya/expected_files.py, pype/plugins/maya/create/create_render.py, pype/plugins/maya/publish/collect_render.py, pype/plugins/maya/publish/validate_render_single_camera.py, pype/plugins/maya/publish/validate_rendersettings.py
- adds Maya Hardware support to the rendering pipeline. Normally render farms might not support this but because we use the Maya Sequence rendering (https://github.com/tokejepsen/MayaSequence) we can use Maya Hardware to render playblasts on the farm.
- Ensures the renderer is queried on all render layers.
=> Maya Hardware support

pype/plugins/global/publish/extract_review.py
Bash on linux may have issue with few symbols (e.g. `(` ) in arguments if are not in quotation marks (`"`).
- add video and audio filters into quotation marks
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1589|
=> FFmpeg filters in quote marks

openpype/hosts/maya/plugins/publish/validate_rendersettings.py, openpype/modules/deadline/plugins/publish/submit_publish_job.py
- validation: in validate render settings comparison of values failed because different possible types, they are now compared as strings.
- wrong regex in submit_publish job was missing `beauty` aov name so it was not marked for preview.
🔙 **pype 2 backport:** #1609
=> Maya: Render workflow fixes

pype/plugins/global/publish/submit_publish_job.py
this is fixing regex to detect beauty pass for review. It did match `foo_beauty.1001.exr` but not just `beauty`.
🧛🏻 **this is backport of**: #1607
=> Maya: Render workflow fixes - 2.0 backport

openpype/modules/standalonepublish_action.py
- standalone publisher can't be launched in OpenPype on MacOs
- standalone publisher is launched as new process and `DETACHED_PROCESS` is not used if not available
=> MacOs Fix launch of standalone publisher

pype/modules/ftrack/actions/action_delivery.py
Fixed errors:
- Delivery action 'launch':
- Result from 'real_launch' was not caught (report_items)
- Invalid return types were used in case of skipped or empty data
- 'real_launch':
- When 'anatomy' path is not solved, only 1 error message is kept (second one replaces first one in case both errors occur)
- Small typo corrections
=> 'Delivery action' report fix +typos

openpype/settings/entities/lib.py
- UI wrappers break current implementation of `"skip_paths"` concept
- wrapper items are handler properly so they should pass skip path to their children and skip themselves if all children are skipped
=> Settings template skip paths support wrappers

start.py
We were initializing terminal even in gui mode on windows (where there is no stdout) - leading to crash during start.
=> Bug: Initialize blessed term only in console mode

openpype/modules/sync_server/tray/app.py, openpype/modules/sync_server/tray/widgets.py
- sync server gui is setting layout specifically to wrong widgets even if are already set to right widget
- removed "setLayout" methods as layouts are already set to right parents
=> Sync server Qt layout fix

openpype/modules/webserver/host_console_listener.py, openpype/modules/webserver/webserver_module.py
`HostListener` in webserver module may break Python 2 hosts as have Python 3 specific imports in global scope.
- move import of HostListener from global scope to method where is used
=> Console Listener on Python 2 fix

openpype/style/style.css, openpype/tools/tray/pype_info_widget.py, openpype/tools/tray/pype_tray.py
- use OpenPype style in tray widgets
- tray menu
- OpenPype info widget
=> Tray style

openpype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py
- don't query all entities from project but only entities related to selection
- this may be faster for smaller selection in hierarchy but slower on top
- added more safe change commits and data queries (in chunks)
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1626|
=> Faster hierarchical values push

openpype/cli.py, openpype/modules/settings_action.py, openpype/pype_commands.py, openpype/tools/settings/__init__.py, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/window.py
- settings UI in tray will always use `manager` role
- settings UI cli handle `--dev` argument properly
- missing defaults should not add widgets to window
- fixed double reset of settings ui in tray
=> Settings permissions

openpype/modules/base.py, openpype/modules/launcher_action.py, openpype/tools/tray/pype_tray.py
- modules can define doubleclick callbacks
- not implemented way how to define which is used (not topic of this PR as Launcher is only registered callback)
- launcher register it's callback
- changed how click on icon works (to be able catch double click)
- this does not work on Mac as it's menu is displayed in a different way
=> Tray doubleclick

.gitignore, pyproject.toml, setup.py, tools/build_dependencies.py
This adds ability to use poetry to build / publish OpenPype wheels.
```shell
poetry build
```
will creates OpenPype wheel unde `/dist` directory
```shell
poetry publish
```
will then publish just built wheel to [pypi](https://pypi.org/). You can add `--username` and `--password` to specify credentials for **pypi**. `--dry-run` will simulate process without publishing anything. For use with **pypi** [API tokens](https://pypi.org/help/#apitoken) should be used instead:
```shell
poetry config pypi-token.pypi pypi-api-token
```
------
OpenPype can be run after `poetry install` with `poetry run openpype`. Installing wheel will create executable script in target python `openpype`.
=> Use poetry to build / publish OpenPype wheel

openpype/tools/project_manager/project_manager/model.py
- click on `Add Asset` button in project manager with selected Task will cause crash on project manager
- add asset on task item won't crash but create asset on it's parent
=> Add asset on task item

openpype/tools/project_manager/project_manager/model.py
In hierarchy model is used Queue which may cause issues in Qt to not properly trigger callbacks and save does not reset attributes properly.
- replaced Queue with dequeue
- reset attributes storing asset names and ids
- resetting attributes fixed a lot of issues with duplicated names and not updated data in view
=> Project manager save and queue

openpype/lib/avalon_context.py, openpype/settings/handlers.py
New project won't have set applications and tools on creation.
~- remove project overrides from project settings on new project creation~
~- this is cheat fix but work~
- anatomy overrides wont return attributes with filled applications if `"apps"` key is not in project config
=> New project anatomy values

openpype/style/style.css
- mac shows selection color (different than openpype's) on branches too
- selection color is set to transparent
- also set transparent background for branches (alternate color is expanded to full width of view)
=> Transparent branches in view on Mac

openpype/hooks/pre_mac_launch.py, openpype/modules/standalonepublish_action.py
We're modifying launch arguments for MacOS to launch new process using `open` command. At the time we've added this ability it didn't work with `-n` argument (create new independent process) so was skipped. Now the reason is known that `open` arguments must be in single dash and in specific order.
- add argument to launch subprocess as new process to launch in mac arguments
=> Mac launch arguments fix

pype/plugins/standalonepublisher/publish/collect_instance_resources.py
Client requested jpeg sequence `plateOffline` not to be deleted - originally meant only to be converted to mp4 and then deleted. But they wish to load it to nuke instead of mp4. This way it is preserved and yes it is hotfix but enhancement at the same time.
Closes https://github.com/pypeclub/client/issues/82
=> StandalonePublisher: adding  exception for adding `delete` tag to repre

openpype/settings/entities/dict_mutable_keys_entity.py, openpype/tools/settings/settings/list_item_widget.py
1. `add_row` may cause that settings ui will crash because of recursion error because it's children value change may trigger adding infinite children with same value
2. store as list in `DictMutableKeysDict` is still broken because of missing conversion to list in `value` property
- trigger `set_entity_value` on ListWidget's `add_row` after new item is part of `input_fields`
- property `value` in `DictMutableKeysDict` is append list of key, value
=> Settings list race condifiton and mutable dict list conversion

openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py, openpype/settings/defaults/project_settings/standalonepublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json
2.x version: https://github.com/pypeclub/OpenPype/pull/1680
Closes https://github.com/pypeclub/client/issues/89
Calculates duration from Asset from DB, compares with number of published files.
Skips movie-like extensions (configurable).
Run Standalone publisher with 'Render' family, try to publish sequence of files
=> #683 - Validate Frame Range in Standalone Publisher

openpype/tools/project_manager/project_manager/view.py
- define `"name"` column width and use interactive stretch to be able resize it and avoid strange behavior
- it's not perfect but better then current situation
=> Project Manger: Default name column width

openpype/style/style.css
- aesthetic small change change to remove outline which is in most of cases has wrong borders
=> Remove outline in stylesheet

pype/plugins/standalonepublisher/publish/collect_instance_resources.py
reversing pr #1650
As previouse PR was breaking reviewable workflow so the representation with jpg sequence was identified as ftrack reviewable and was published as video instead of mp4 with burnins. We have to add `delete`. Instead of removing `delete` tag we have to duplicate the representation and mark only one  as reviewable with `delete` and second is plate representation. 
- `keepSequence` will duplicate any image sequence representation 
- one repre is for conversion to mp4 as reviewable
- second is published as plates
=> StandalonePublisher:  instance data attribute `keepSequence`

openpype/settings/entities/enum_entity.py
- sort applications and tools in comboboxes inside settings ui by their label
- open system settings go to project attributes and open applications and tools comboboxes and see if are sorted
- should I do the same for task types before we'll have proper ordering of them?
=> Sort applications and tools alphabetically in Settings UI

openpype/modules/ftrack/ftrack_server/socket_thread.py
Ftrack user event server is running as subprocess which cause issues with logging because all python subprocess.Popen objects have stdout and stderr which are inherited from source process, but if `openpype_gui` executable is used then sys.stdout and sys.stderr are set to None so new created processes get strange PIPE objects that can't work with `PypeStreamHandler` properly and may crash at any time because `flush` of the stream cause OSError.
- redirect stdout of ftrack process to devnull if sys.stdout is None to prevent issues described above
Any processed action can crash during logging (most visible when launchin application).
Hard to say. I launched Nuke 5-10 timer in row from ftrack. One of launches should crash if `openpype_gui` executable is used.
Closes: …
=> Ftrack subprocess handle of stdout/stderr

openpype/modules/clockify/clockify_api.py, openpype/modules/clockify/widgets.py, openpype/modules/ftrack/tray/login_dialog.py, openpype/modules/muster/widget_login.py, openpype/modules/timers_manager/widget_user_idle.py
- Ftrack module
- login widget is using openpype style
- ftrack url is label instead of input (as user can't change the url)
- Clockify module
- credentials widget use openpype style
- fixed bug in clockify api
- simplified a little bit code of widgets
- ok and cancel buttons have same width
- Muster module
- credentials widget use openpype style
- ok and cancel buttons have same width
- Timers manager module
- message box (about stopping timers) is using openpype style
=> OpenPype style in modules

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py, openpype/settings/defaults/project_settings/standalonepublisher.json
- ffmepg arguments in extraction of thumbnail from standalone publisher did not expect some bad cases
- fixed ffmpeg arguments in standalone publisher extract thumbnail
- path with spaces or backslashes can be used now (for ffmpeg executable, input and ouput path)
- changed default input argument from `- gamma 2.2` to `-apply_trc gamma22`
Closes: https://github.com/pypeclub/OpenPype/issues/1700
=> Standalone publisher Thumbnail export args

openpype/hosts/maya/plugins/publish/extract_playblast.py, openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Extract playblast had wrong condition causing it to trigger *isolate* mode even when it was not requested, causing gray screen renders.
- run Maya
- create simple scene + camera
- select camera -> Pype / Create / Review
- make sure "isolate" is not enabled on instance
- publish
It should produce completely gray render. After this fix, playblast render should be as expected.
- run Maya
- create simple scene + camera
- select camera -> Pype / Create / Review
- make sure "isolate" **is enabled on instance**
- add one of the objects to Review instance
- publish
This should output only object added to review.
🔙  **Pype 2 backport PR:** #1713 
|---|
=> Maya: Extract review hotfix

pype/plugins/maya/publish/extract_playblast.py, pype/plugins/maya/publish/extract_thumbnail.py
Extract playblast had wrong condition causing it to trigger *isolate* mode even when it was not requested, causing gray screen renders.
- run Maya
- create simple scene + camera
- select camera -> Pype / Create / Review
- make sure "isolate" is not enabled on instance
- publish
It should produce completely gray render. After this fix, playblast render should be as expected.
- run Maya
- create simple scene + camera
- select camera -> Pype / Create / Review
- make sure "isolate" **is enabled on instance**
- add one of the objects to Review instance
- publish
This should output only object added to review.
🗻 **OpenPype 3 PR:** #1714
|---|
=> Maya: Extract review hotfix - 2.x backport

pype/plugins/maya/publish/validate_model_content.py, pype/plugins/maya/publish/validate_model_top_group.py
With client request do disable validation of top level group when publishing model, this splits it into two files. The one validating top level group then can be disabled with presets/project overrides.
For **OpenPype 3** this should be solved by different approach. Check should be marked by enum flags and its combination should be settable in Settings to control validator behavior in more precise way.
=> Maya: Split model content validator

openpype/settings/defaults/project_settings/global.json
By default settings tvpaint review and workfile families are using subset template `{family}{Variant}` but as both are created dynamically during collection `"variant"` is never available. We lack default subset template for this purposes.
- set default subset template for review and workfile family in tvpaint with `{family}{Task}` template
=> Default subset template for TVPaint review and workfile families

openpype/hosts/tvpaint/plugins/create/create_render_layer.py
- it is requested to use layer name instead of group name for default `renderLayer` family variant
- use layer name instead of group name for default render layer variant
=> TVPaint use layer name for default variant

openpype/tools/launcher/models.py, openpype/tools/launcher/widgets.py, openpype/tools/launcher/window.py
- project names are refreshed each 10 seconds
- refreshing of projects won't reset whole model but removes not found projects and adds new projects
- actions are refreshed each 10 seconds
- refreshing happens only if launcher is active window to avoid repetitive calls to mongo if window is not active
- open launcher
- create project (through project manager of ftrack project sync)
- set launcher as active window
- wait 10 seconds if project will appear in launcher
- open launcher
- click of project -> asset -> task
- remove/add applications for the project in settings (or through ftrack)
- set launcher as active window
- wait 10 seconds if application will show up
Would be great to test if it works on linux and mac as I'm not sure how "active window" is handled on them.
=> Autoupdate launcher

pype/lib/applications.py
- tool names in application preparation do not expect slash in tool name from OpenPype3
- replace slash on tool name with underscore
=> Tools names forwards compatibility

openpype/modules/ftrack/event_handlers_server/event_version_to_task_statuses.py
Ftrack version to task status mapping won't map statuses if mapping is not defined in settings which is not right and should contiue using default way (which is exact status mapping).
- don't skip processing if mapping is not set and use default mapping
Closes: https://github.com/pypeclub/OpenPype/issues/1670
=> Ftrack sync status

openpype/tools/launcher/lib.py, openpype/tools/launcher/widgets.py, openpype/tools/launcher/window.py
Project changes may not be propagated in right way. So project clicked on first launcher page may be propagated to project combobox on page 2 but is not propagated to assets widget which is confusing and may cause crash of OpenPype Tray.
This happens since https://github.com/pypeclub/OpenPype/pull/1725 .
- implemented `ProjectHandler` which handles project changes and refreshing of projects
- all callbacks related to project changes does not care about anything else that value passed with project change signal
- ProjectHandler object always make all necessary steps before callbacks are triggered
- this simplified a lot of code as propagation of project change was sequence based and race coditions were not always right
=> Launcher project changes

openpype/modules/ftrack/lib/avalon_sync.py
Missing `avalon_mongo_id` or lack of permissions to the custom attribute will cause that popup message will show up but won't show much usefull information as `<` and `>` will cause that custom attribute name is not visible in ftrack and username is not shown at all.
- custom attribute name is not wrapped with `<` and `>` but `"`
- details will show both username and api key
=> Ftrack missing custom attribute message

openpype/modules/settings_action.py, openpype/tools/settings/local_settings/window.py
Local settings UI crashes OpenPype tray if there are missing default values for studio settings. This issue will never happen to user(99.99%).
- local settings ui won't load any settings until is called `reset`
- local settings ui catch errors happened on `reset` and show them in dialog
- hide widgets and disable save button
- reset button is kept there to be able reset local settings when defaults are set
- local settings action in tray won't trigger `reset` on first show as that is handled by local settings ui itself
Easiest is to rename `~/openpype/settings/defaults/system_settings/tools.json` to different name. That should cause missing defaults error but tray should be possible to start.
Closes: https://github.com/pypeclub/OpenPype/issues/1712
=> Local settings UI crash on missing defaults

openpype/settings/defaults/project_settings/harmony.json, openpype/settings/defaults/project_settings/houdini.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/defaults/project_settings/photoshop.json, openpype/settings/entities/schemas/projects_schema/schema_main.json, openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json, openpype/settings/entities/schemas/projects_schema/schema_project_houdini.json, openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
We lack settings for `ValidateContainers` validator which is global validator but for multiple hosts.
- added `ValidateContainers` settings into all hosts (that can use the plugin) so it's possible to modify it's behavior per host
- created houdini settings with only this plugin
Part of https://github.com/pypeclub/OpenPype/issues/1661 Issue (not closing).
=> Validate containers settings

openpype/lib/applications.py, openpype/settings/defaults/system_settings/applications.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json, openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json, openpype/settings/lib.py, openpype/tools/settings/local_settings/apps_widget.py
- some applications can't have set executables because it's executable is calculated on the fly (namely Unreal)
- application without `"executables"` key in variant will always have successfull validation of global executables existence
- default launch arguments are in that case empty so they must be filled in hooks
- these applications are not visible in local settings and local settings should skip their overriding
- Prelaunch hook should raise `ApplicationNotFound` exception if won't find proper executable
- removed `"executables"` and `"arguments"` from Unreal application
closes: https://github.com/pypeclub/OpenPype/issues/1674
=> Application without executables

openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py, openpype/hosts/tvpaint/plugins/publish/extract_sequence.py, openpype/settings/defaults/project_settings/tvpaint.json, openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Background of thumbnail has not set default background color so transparency is filled with black which is in most of cases unwanted behavior.
- add white background for thumbnail image
- make sure bg compositing is happening only if alpha is available
closes https://github.com/pypeclub/client/issues/107
=> TVPaint white background on thumbnail

openpype/hosts/photoshop/plugins/lib.py, openpype/hosts/photoshop/plugins/load/load_image.py, openpype/hosts/photoshop/plugins/load/load_image_from_sequence.py
Closes https://github.com/pypeclub/client/issues/46
Loader allows user to select specific frame from sequence of files.
This loader is a bit specific as it doesn't produce container in the scene. Currently there is no container with frame field to store.
Customer is fine with it for now, might be necessary to be added in the future, but currently not extra limiting.
Still uses qargparse approach, no special nice dialog (that would need much more rework).
**How to test it:**
- open Photoshop
- click on Launch
- locate 'render' subset with multiple frames
- open context menu with rmb
- click on small rectangle at the end of line with ImageFromSequenceLoader
- select specific file
- please try some other existing loaders, dont need to be from PS
=> PS - added loader from sequence

openpype/settings/entities/__init__.py, openpype/settings/entities/enum_entity.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/projects_schema/schema_project_slack.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json, openpype/settings/entities/schemas/system_schema/host_settings/template_host_unchangables.json
We use host names in filtering a lot but we don't have enumeration of available hosts in settings.
- added `hosts-enum` entity type which is enumerator with all possible host names
- has single selection and multiselection option
- it is possible to have empty value with custom label which is stored as empty string `""`
- to have this set `use_empty_value` to true/false
- entity can have defined `custom_labels` as dictionary where key is host name and valid is label
- replaced list of strings in hosts usage with new enum item
=> Settings Hosts enum

openpype/hosts/nuke/plugins/create/create_write_prerender.py, openpype/hosts/nuke/plugins/create/create_write_render.py
When `use selection` was ticked off the creator was failing as we could not retrieve format width and height from selected nodes. 
Getting width and height was added to tray and if fails it will get format from root actual format
1. open nuke and in workfile create version (if you are in untitled script) 
2. open Creator and chose Create Render Write
3. tick off `use selected`
4. hit create and write node should be created without troubles. 
5. Look inside of the created node (ctrl+enter) and look into properties of Crop node
6. width and height should be the same as it is set on script's actual format (with mouse over node graph window hit `s` and look down to format)
=> Nuke: fixing render creator for no selection format failing

openpype/lib/applications.py
With this change it is possible to define executable path of application containing environments.
Environments must be avaialble in global environments of currently running process! It is not possible to set the environment e.g. in application group/variant environments.
- try to format executable path with environments
- failed formattings is ignored
=> Application executables with environment variables

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
- full input path has double quotations once on top of iteration and second when passed to ffmpeg args which breaks the path if has spaces or other breaking characters
- removed qutation adding on top of iteration as it's confusing
- open standalone publisher
- add there video file with spaces in path
- check thumbnail and preview
- publish it as e.g. plate
- `Extract thumbnail SP` should not crash
=> Standalone publisher thumbnail extractor fix

openpype/tools/workfiles/app.py
- widths of Workfile tools widgets have better sizes to display it's content
- workfile tool window is wider now
closes: https://github.com/pypeclub/OpenPype/issues/1633
=> Workfile tool widths

openpype/lib/applications.py
Applying of project specific environments was broken as it didn't update environments but set it again which was unexpected for launching from launcher and ftrack.
Current state of project specific environments is that it will break all environments if it's not empty.
- fix project specific environment variables to work as expected with updating the value instead of setting the value back
- I did it with adding custom environment in application envirtonments (`"MY_TEST_ENV": "VALUE_1"`)
- In project settings I've added `"MY_TEST_ENV": "{MY_TEST_ENV} - VALUE_2"`
- On application launch checked if OpenPype loaded and if value of env `"MY_TEST_ENV"` is `"VALUE_1 - VALUE_2"`
=> Project specific environments

openpype/settings/entities/base_entity.py, openpype/settings/entities/root_entities.py, openpype/tools/settings/settings/base.py
- adding possibility to copy and paste values in settings ui
- added `Copy`, `Paste` and `Paste to same entity` action
- `Copy` - copy the value of right clicked entity
- `Paste` - tries to paste copied value to right clicked entity (shows dialog on crash)
- `Paste to same place` - paste the value to same hierarchi entity (shows dialog on crash)
- I don't like the label, any suggestion are welcomed
- all paste actions are available only for values copied using `Copy` action
Paste can be slow now connected to "on change" callbacks slowing down whole UI but that is not part of this PR.
=> Settings UI copy/paste

openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py, openpype/modules/ftrack/lib/__init__.py, openpype/modules/ftrack/lib/custom_attributes.py
- task parent changes are not handled with event handling with hierarchical value pushing from parent to task on attribute value change
- it is confusing for users that value set on (e.g.) Shot is not propagated to value on created task which is annoyng especially if task attribute is used in expression
- event handler also cares about change of task parent
- in that case is pushing of values more robust and a little bit slower as have to query hierarchical attribute values all the time
1. Run event server with this branch
2. Make sure you have custom attribute available for `Shot` and `Task` and is hierarchical at the same time (`frameStart` or `frameEnd`)
3. Make sure settings for this event have proper values (`ProjectSettings/Ftrack/Server Actions/Events/Sync Hierarchical and Entity …
=> Push hierarchical attributes care about task parent changes

openpype/lib/anatomy.py
- template key "others" is processed with expected keys which is unexpected and cause crashes
- pop others before expected keys are processed
=> Anatomy others templates don't cause crash

openpype/lib/applications.py, openpype/settings/defaults/system_settings/applications.json, openpype/settings/entities/lib.py, openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_photoshop.json, openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json, openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
Setting of `Use python 2` is now on all applications but on few of them it doesn't make sence at all because will always use Python 3.
- key `use_python_2` is not required key in application variant and is set to `False` by default
- fixed replacing of curly brackets when replacing template value
- removed `use_python_2` from applications where will be always Python 3
- Blender
- Harmony
- Photoshop
- Aftereffect
- TVPaint
=> Settings application use python 2 only where needed

openpype/lib/vendor_bin_utils.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/extract_review_slate.py
Streams read from input file using ffprobe are not always in order we're using it now. We always expect that first stream is video or image stream but in some cases there can be an audio at first place. That is currently breaking all ffprobe usages.
- instead of blindly using first stream from ffprobe is used first most matching the expectations
- check if stream has width and height
- ignore audio codec type if we expect video or image
- modified ffprobe reading in `ExtractReview` and `ExtractReviewSlate`
- ffprobe stdout, stderr is decoded to utf-8 before logging
=> FFprobe streams order

openpype/settings/entities/base_entity.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/lib.py, openpype/settings/entities/root_entities.py
- loading of settings schema is handled using SchemaHub
- schemas are not resolved before are passed to root entity
- schemas must be resolved in entities that can possibly have 'schema' or 'template' type as children
- json files that can't be parsed won't cause error if are not used
- this is required step as now filling of entity children had to be handled in single function which had to know all entities structure but with this change it is entity based so entity and it's schema data can have different definitions of children data (required for [this issue](https://github.com/pypeclub/OpenPype/issues/1749))
It's tricky as everything should work almost the same way.
=> Settings schema without prefill

openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py
Validate Frames didn't count single file properly. Old implementation expected [], string is provided for single frame.
----------------
- try to publish single image file
- see error mesage of Validate Frames
=> Fix - single file files are str only, cast it to list to count properly

openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py, openpype/settings/defaults/project_settings/deadline.json, openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
- allowed environment keys filter
- search & replace in environment values
=> Deadline: Nuke submission additional attributes

openpype/lib/editorial.py
Opentimeline import inside openpype lib crashes in most of the time when is not build properly for openpype venv but the error raised during import in openpype process does not make sence as it's crashing because of missing env key `AVALON_APP` which can't be set in most of cases in openpype process (and wouldn't fix the error).
- reraise exception if `AVALON_APP` is not set
- solution is not perfect but much better then current state
=> Otio unrelated error on import

openpype/modules/ftrack/event_handlers_server/action_clone_review_session.py
Ftrack action `Clone Review Session` can crash if email on user entity is set to `None`.
- make sure email is not None but string
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1785|
=> Invitee email can be None which break the Ftrack commit.

igniter/bootstrap_repos.py, openpype/cli.py, start.py, tests/igniter/test_bootstrap_repos.py, tools/build.ps1, website/docs/admin_openpype_commands.md, website/docs/admin_use.md
This is fixing issue #1719 and is adding some additional clarifications.
1) if invalid version format is requested with `--use-version`, error is displayed and execution is stopped.
2) `--list-versions [--use-staging]` option was added - this will list all available (detected) versions on all places OpenPype is looking. Without `--use-staging` only production  versions are displayed.
3) if `--use-version` is used with *staging* variant, `--use-staging` is implied.
Close #1719
=> Fix: staging and `--use-version` option

pype/modules/ftrack/events/action_multiple_notes.py
- created server version of multiple notes action
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1795|
=> Ftrack Multiple notes as server action

openpype/tools/standalonepublish/app.py, openpype/tools/standalonepublish/widgets/widget_asset.py
- it is handy that standalone publisher would remember last selected project instead of using first available
- standalone publisher remembers 5 last selected projects and tries to set them on initialization
- last selection is stored using QSettings
- project names in combobox are sorted
1. open standalone publisher
2. change project (and remember selected project)
3. close standalone publisher
4. open standalone publisher
5. check if project is set to project from step 2
closes: https://github.com/pypeclub/client/issues/49
=> Standalone publisher last project

openpype/hosts/nuke/plugins/publish/precollect_instances.py
This is recurring issue and had been fixed many times. At the moment this is fixing the issue again. 
1. create nuke write render node on any input
2. render images without publishing `render local` button
3. set render node into `use existing images` 
4. publish 
5. correct result is that new version is created into folder `.../publish/render/...` and not `.../publish/write/...`
=> nuke: fixing wrong name of family folder when `used existing frames`

openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py, openpype/settings/defaults/project_settings/ftrack.json
- `CollectFtrackFamily` is looking for `"additional_filters"` key in settings but there is only `"advanced_filtering"`
- `review` instance is never added to ftrack by default which is confusing for most of cases
- `CollectFtrackFamily` is looking for `"advanced_filtering"`
- `review` instances have ftrack family added
=> Collect ftrack family bugs

openpype/hosts/nuke/plugins/publish/precollect_instances.py, openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py, openpype/settings/defaults/project_settings/ftrack.json
We have changed the way we are attaching `ftrack` family to any instance based on presets in settings. Nuke were missing this transition.
1. open settings and save (to write defaults to your db)
2. make sure project overrides are not changing those new settings > look to Project settings / ftrack / Collect Ftrack Family / at bottom is nuke host preset
3. publish some render node and toggle review off 
4. notice that `Integrate Ftrack API` plugin is not present (that is correct)
5. toggle review on on the render node and refresh
6. check integrators and `Integrate Ftrack API` should be back again
this PR has already merged https://github.com/pypeclub/OpenPype/pull/1801
=> Nuke: ftrack family plugin settings preset

openpype/lib/applications.py
- filling of executable paths happens after mac os specific modification of path so they may not work as expected
- move environment filling before mac specific check
=> Environments in app executable for MacOS

openpype/settings/entities/__init__.py, openpype/settings/entities/base_entity.py, openpype/settings/entities/dict_conditional.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/lib.py, openpype/settings/entities/list_entity.py, openpype/settings/entities/root_entities.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/system_schema/example_schema.json, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/dict_conditional.py, openpype/tools/settings/settings/item_widgets.py
Implementing concept of one entity value modifying children entities of dictionary. Added `dict-conditional` entity type which always have one entity with enumerator where value of enumerator change other children of dictionary.
- added the `dict-conditional` entity type for settings
- parent can tell if missing defaults can be skipped or not
```
{
"type": "dict-conditional",
"key": "my_key",
"label": "My Key",
"enum_key": "type",
"enum_label": "label",
"enum_children": [
{
"key": "action",
"label": "Action",
"children": [
{
"type": "text",
"key": "key",
"label": "Key"
},
{
"type": "text",
"key": "label",
"label": "Label"
},
{
"type": "text",
"key": "command",
"label": "Comand"
}
]
},
{
"key": "menu",
"label": "Menu",
"children": [
{
"key": "children",
"label": "Children",
"type": "list", …
```
=> Settings conditional dict

tools/build.ps1, tools/build.sh, tools/build_win_installer.ps1, tools/create_env.ps1, tools/create_env.sh, tools/create_zip.ps1, tools/create_zip.sh, tools/fetch_thirdparty_libs.ps1, tools/fetch_thirdparty_libs.sh, tools/make_docs.ps1, tools/make_docs.sh, tools/run_project_manager.ps1, tools/run_projectmanager.sh, tools/run_settings.ps1, tools/run_settings.sh, tools/run_tests.ps1, tools/run_tests.sh, tools/run_tray.ps1, tools/run_tray.sh
This PR is updating deprecated **Poetry** installer. Scripts will no longer add Poetry to `PATH`. They will check for `POETRY_HOME` and use Poetry from there (this allows to use system-wide Poetry installation). If `POETRY_HOME` is not set, it will be for the current session and will point to OpenPype local Poetry installation.
**To test:** remove poetry from `PATH`, make sure that if you run `poetry` command from terminal, you'll get `command not found` error. Then run all relevant scripts in **tools** folder.
=> Build: don't add Poetry to `PATH`

openpype/hosts/standalonepublisher/plugins/publish/collect_editorial.py, openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py, openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_resources.py, openpype/hosts/standalonepublisher/plugins/publish/collect_hierarchy.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/defaults/project_settings/standalonepublisher.json, openpype/settings/entities/enum_entity.py, openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Missing settings for some important standalone plugins and others. 
Modifications:
=> Settings: settings for plugins

openpype/hosts/maya/plugins/publish/extract_yeti_rig.py
Invalid variable pointing to file was set in representation in Yeti rig extractor in Maya.
=> Maya: fix yeti settings path in extractor

openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/input_entities.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/projects_schema/schema_project_global.json
- it is not possible to have setting overrides on project settings because current schema of project structure allows to have dots in dicitonary keys which is not allowd in settings
- RawJson entity can store value as string
- this value is not auto converted to python objects on load so it must be manually converted back using json module
- project folder strucuture is stored as string
- action using project folder structure settings expects string
closes: https://github.com/pypeclub/OpenPype/issues/1793
=> Project folder structure overrides

openpype/hosts/aftereffects/plugins/publish/validate_instance_asset.py
Better validation for case of switching between workfiles and obsolete context.
Requires:
https://github.com/pypeclub/avalon-core/pull/335
=> PS, AE - send actual context when another webserver is running

pype/hosts/nuke/lib.py
If a container from another project is in the script, the `check_inventory_versions` method errors. This method is run when saving the script which prevents the user from saving the work.
Reduced the error to a log warning about which nodes are the issue.
Error:
```
File "C:/Program Files/Nuke11.0v4/plugins\nuke\callbacks.py", line 92, in onScriptSave
_doCallbacks(onScriptSaves)
File "C:/Program Files/Nuke11.0v4/plugins\nuke\callbacks.py", line 46, in _doCallbacks
f[0](*f[1],**f[2])
File "C:\Users\tokejepsen\bumpybox_development\pype-setup\repos\pype\pype\hosts\nuke\lib.py", line 68, in check_inventory_versions
"_id": representation["parent"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
|---|---| …
=> Failsafe for cross project containers.

openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
Current implementation of PrepareProject action does not work if project does not exists yet.
- project is created if is not available
- added order of attributes shown in widget
1. create new Ftrack project
2. run PrepareProject without syncing the project
3. confirm values
4. see if it crashes or not
*. check order of attributes in the action interface
=> Prepare project action enhance

openpype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py, openpype/modules/ftrack/lib/ftrack_base_handler.py
Action to push attribute values may crash without description what happened.
- added methods to ftrack base handler which saves traceback to a textfile and add the file to a job
- use the methods in push hierarchical values to load traceback to the job on crash
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1842|
=> Ftrack push attributes action adds traceback to job

tools/build.ps1, tools/create_env.ps1, tools/run_mongo.ps1
this is slightly changing how Python is detected and Poetry is installed. It is first testing for existance of [pyenv-win](https://github.com/pyenv-win/pyenv-win) and it it exists, it will take Python path from it, because powershell `Get-Command` will ignore its shims and it will still use whats in the `PATH`. This allows to use `pyenv` the same way as it is used on linux/darwin.
now with bonus feature - ability to select preferred mongodb version on windows when multiple versions are installed.
=> Add support for pyenv-win on windows

openpype/hosts/nuke/plugins/load/load_effects.py, openpype/hosts/nuke/plugins/load/load_effects_ip.py
Updating was not working and backdrop was created multiply
Follow this video, all is explained there https://www.loom.com/share/5318b671759e47e29828f98d3ec844d1
=> Nuke: updating effects subset fail

openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
closes https://github.com/pypeclub/client/issues/124
1. open publisher form tray
2. set context to any task
3. set family to Editorial
4. point to any of your editorial testing edl file
5. hit publish
Result: clips should be collected without any error commint from `Collect Editorial Instances`
=> publisher: missing version in subset prop

pype/plugins/standalonepublisher/publish/validate_texture_versions.py
Validator fails on multiple batch textures of same version, it shouldnt.
How to test
-------------
- Unpack 
[versions_bug.zip](https://github.com/pypeclub/OpenPype/files/6870008/versions_bug.zip)
- D&D all present files
- Publish (previous version without fix should fail on ValidateTextureBatchVersions)
=> Bugfix textures validator versions

openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Function `get_hierarchical_attributes_values` expect as value custom attribute types in list but sync event is passing dictionary mapped by id.
- pass right type to `get_hierarchical_attributes_values`
=> Ftrack type error fix in sync to avalon event handler

openpype/settings/lib.py, start.py
First step to be able think about implementation of OpenPype Addons with their settings. Load general environments from settings without using api functions which should load settings also from addons. This must be done separatelly as this part must be done before Addons are loaded.
- added function `get_general_environments` which return environments from general settings which is used in start.py
General environments must load
- if build was created with this PR without any zip
- if build was created with this PR and zip is from older OpenPype
- if build was created before this PR and this PR is used as zip
- to apply this change new build must be distributted
- modifications are forwards and backwards compatible
- new build is not required until addons are really implemented and used
=> Independent general environments

openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Image Io section in project anatomy settings was not defined as group, instead children were using those in misunderstanding of the concept. 
Removing all children `is_group` attributes and placing one at root  of the imageio section.
=> imageio: fix grouping 

pype/plugins/tvpaint/publish/collect_workfile_data.py, pype/plugins/tvpaint/publish/extract_sequence.py, pype/plugins/tvpaint/publish/validate_start_frame.py
- offset expected renders by start frame
- optional validator to sync start frame and mark in.
@jezscha was this the correct way of naming the branch?
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1844|
=> TVPaint Start Frame

openpype/modules/ftrack/event_handlers_server/action_prepare_project.py, openpype/modules/ftrack/event_handlers_user/action_prepare_project.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Enhance of https://github.com/pypeclub/OpenPype/pull/1838
There are differences in local and server prepare project. Server does not have ordered keys. Custom attribute changes are not commited. Local action does not have create project structure.
- commit changes of custom attribute values
- update Server action with changes from Local action
- added "Create folder structure" to local action
- local action have in settings default checked value of "Create folder structure"
Closes https://github.com/pypeclub/client/issues/95
=> Ftrack prepare project structure

openpype/settings/entities/anatomy_entities.py, openpype/settings/entities/schemas/README.md
Settings entity `anatomy` should have all children as groups to avoid unresolved overrides.
- `anatomy` entity is validating that all it's children are groups otherwise it can break project data
1. try to set `is_group` to `True` on entity which is deeper in anatomy settings hierarchy
2. error should appear on settings ui open
=> Anatomy schema validation

openpype/settings/entities/enum_entity.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
Host enumerator should be used in most of cases when host names should be filled but sometimes it is required to limit host names to only few of them.
- `hosts-enum` entity has new attribute `hosts_filter` where can be defined host names which will be available in enum
- hosts filter is validated
- at least one host must remain from all hosts
- if host from filter is not available then warning is logged (Should raise and exception?)
- added hosts filter for "workfiles on startup" where `standalonepublisher` is skipped
=> Filter hosts in settings host-enum

openpype/modules/log_viewer/tray/app.py, openpype/modules/log_viewer/tray/widgets.py, openpype/style/style.css, openpype/tools/settings/settings/window.py, openpype/tools/standalonepublish/widgets/widget_component_item.py
Changes required to use PySide2 and keep same (or similar) results as with PyQt5.
- stylesheet changes or definitions
- use direct parenting to propagate style as expected
- Qt signals have different receivers access
- everything should look and behave the same way
=> Prepare for pyside2

openpype/hosts/nuke/api/lib.py, openpype/lib/applications.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
In pype2 used to be an option to add env var to launch workfile tool at a host launch. It was missing in openpype.
- adding global workfile project settings with an filter on host and task name ([this should be changed to task type in future](https://github.com/pypeclub/OpenPype/pull/1866))
- adding default settings not to open the workfile tool at launch
- adding functionality for filtering by host and task name and adding result to environment variable `WORKFILE_STARTUP`  as it used to be
- refactory nuke's lib function to support this back again
1. open settings and go to `project/global/tools/workfile/Open workfile tool at launch`
2. create new filter and set host to `nuke` and Enabled to True
3. launch nuke from any of your task
4. workfile tool should be opening
closes …
=> Workfile tool start at host launch support

openpype/tools/workfiles/app.py
Avalon event emit expect that second argument is list or tuple of arguments but workfiles tool is sending string which is not expected.
- emit workfile arguments as list instead of path
I found it out in maya. When I saved workfile there is an error in scriptsmenu telling that callback did expect only one argument.
=> Workfiles tool event arguments fix

openpype/modules/timers_manager/rest_api.py
This exposes the `stop_timers` method of the timers manager through the rest api.
Went with `stop_timer` instead of `stop_timers` to align with `start_timer`.
=> Expose stop timer through rest api.

openpype/settings/entities/dict_conditional.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/system_schema/example_schema.json, openpype/tools/settings/settings/dict_conditional.py
Sometimes it is better to have combobox of conditional dictionary next to children instead of on top of them.
- added attributes to conditional dict item `enum_is_horizontal` which moves combobox next to children instead on top of them
- also added optional attribute `enum_on_right` which will move the combobox after children on right side (can be enabled only if `enum_is_horizontal` is enabled)
- modified UI to handle that situations
=> Settings: Conditional dict enum positioning

openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py, openpype/hosts/standalonepublisher/plugins/publish/collect_hierarchy.py, openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py, openpype/settings/defaults/project_settings/standalonepublisher.json, openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json
- version detection for locked version on subset properties
- settings with wrong key
- ffmpeg path needed to add quotations around
- open standalone publisher
- set to context on any task in a project
- set to editorial family
- add any of yours testing edl file to instances area
- publish
=> publisher: editorial plugins fixes

openpype/plugins/publish/validate_editorial_asset_name.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
- options for Validate Versions
- options for Valildate Editorial Asset Name
- improving label for Valildate Editorial Asset Name
=> Settings: global validators with options

tools/build.ps1, tools/create_env.ps1
fixed python command detection. Python from **pyenv-win** will be used only if installed and is set explicitly, `python3` is not used on windows by default.
=> Bug: fixed python detection

openpype/hosts/maya/plugins/publish/collect_look.py, openpype/hosts/maya/plugins/publish/extract_look.py
Adding support for `RedshiftNormalMap` node in looks workflow. This file node is now collected and processed as other file nodes in look publishing.
When `make tx` option is on, preserve its linear colorspace.
=> Maya: add support for `RedshiftNormalMap` node, fix `tx` linear space 🚀

openpype/__init__.py
This PR unpacks any environment variables in the studio plugin paths before testing for existence.
=> Support nested studio plugins paths.

openpype/scripts/otio_burnin.py
Burnins are not using input bitrate when h264 codec is used so output can be much lower quality than input.
- use input's bitrate for output for h264 codec
=> Burnins: Use input's bitrate in h624

openpype/tools/pyblish_pype/control.py, openpype/tools/pyblish_pype/model.py
- deactivated instances may not trigger to process plugins in collecting stage which requires to reset collecting after checking them
- all instances behave "like activated" during collecting stage
=> Pyblish UI: Fix collecting stage processing

openpype/tools/settings/settings/list_item_widget.py
Moving row up/down and add/remove may not be propagated in right way which is a lot confusing as values before save may not be same as after save. Issue is only on UI side.
- row order changes are propagated right way with right buttons
- all items are checked on each entity change (which may be time consuming but safer)
- find in settings any list (text object is best to find out changes)
- fill it with idenficable values
- save changes
- combine up/down/add/remove buttons and see if changes are propagated as expected
=> Settings UI: List order works as expected

openpype/lib/applications.py, poetry.lock, start.py
Environments defined in same environments dictionary may not fill all keys defined in the dictionary. Most visible in general environments where it is not possible to use key from general environments inside it's values.
- modification in `acre.merge` - ~~TODO Change acre commit when approved ([PR](https://github.com/pypeclub/acre/pull/3))~~
- compute environments after merging them
Depends on https://github.com/pypeclub/acre/pull/3
=> Global: Use environment computation after environments merge

openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py, openpype/hosts/standalonepublisher/plugins/publish/validate_texture_batch.py, openpype/hosts/standalonepublisher/plugins/publish/validate_texture_name.py, openpype/hosts/standalonepublisher/plugins/publish/validate_texture_workfiles.py
OP version of https://github.com/pypeclub/OpenPype/pull/1913
Texture validators for workfiles (Validate Texture Presence, Validate Texture Batch Naming) triggered for even different families.
How to test is:
Use same workfile as for Texture testing
Select different family in middle column of SP (lets say Background Batch)
Check that Texture validators won't appear anymore (before they would show up and fail)
=> Fix - texture validators for workfiles triggers only for textures workfiles

pype/plugins/standalonepublisher/publish/collect_texture.py, pype/plugins/standalonepublisher/publish/validate_texture_batch.py, pype/plugins/standalonepublisher/publish/validate_texture_name.py, pype/plugins/standalonepublisher/publish/validate_texture_workfiles.py
Texture validators for workfiles (`Validate Texture Presence`,  `Validate Texture Batch Naming`) triggered for even different families.
How to test is:
- Use same workfile as for Texture testing
- Select different family in middle column of SP (lets say Background Batch)
- Check that Texture validators won't appear anymore (before they would show up and fail)
=> Fix - validators for textures workfiles trigger only for textures workfiles

openpype/hosts/nuke/plugins/load/load_mov.py
- open Nuke in some workfile at a task
- open loader and find a subset with mov or mp4
- once you see it is having muiltiple versions reduce the version with enumerator list to lowest version 
- load video file into the nuke script
- open menu/Openpype/Manage
- update to latest version
- all should work as expected and loader should turn to green and latest version should be loaded
=> Nuke: update video file crassing

openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
repre["files"] might be list or str, loop for string wasn't working
=> Fix - validate takes repre["files"] as list all the time

pype/plugins/photoshop/create/create_image.py
Subset name comes out as "imageImage[name]"
=> Duplicate family name.

openpype/tools/settings/settings/dict_mutable_widget.py
- swapped label and key in label when not edited
- added confirmation button when key/label is edited
- fixed removing of duplicated keys
- the remaining keys which were marked as duplicated does not remain as duplicated
- added tooltip to key input
=> Settings UI: Modifiable dict view enhance

openpype/settings/entities/dict_conditional.py, openpype/settings/entities/enum_entity.py, openpype/settings/entities/schemas/README.md
- Entity `dict-conditional` may need to have set default enum value.
- `enum` entity may have defined default value (even in mutiselection)
- this is usable only for dynamic items that may not have set default values (like `dict-conditional`)
- `dict-conditional` may have defined default enum
- set `"default"` attribute on any `enum` in `list` or `dict-modifiable`
- the default should be selected on adding new item
```
{
"type": "list",
"key": "test",
"label": "Test",
"object_type": {
"type": "enum",
"default": "ftrackreview",
"enum_items": [
{"burnin": "Add burnins"},
{"ftrackreview": "Add to Ftrack"}
]
}
}
```
=> Settings: Default values for enum

openpype/hosts/aftereffects/plugins/publish/collect_workfile.py, openpype/settings/defaults/project_settings/ftrack.json
By default workfile is sent to Ftrack, could be disabled by Settings
=> Fix - make AE workfile publish to Ftrack configurable

openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
AVALON_APP_NAME now contains / as separator between name and version, but existing code normalized it to \\.
This skip normalization for key AVALON_APP_NAME
=> Bugfix nuke deadline app name

openpype/hosts/maya/api/menu.py
- there is not used OpenPype workfiles in Maya
- maya menu has unusable project manager action
- replaced avalon workfiles with openpype workfiles
- removed project manager action
- `_get_menu` does not care about scripts menu settings
- do not run `uninstall` on `install`
Resolves https://github.com/pypeclub/OpenPype/issues/1944
=> Maya: Menu actions fix

openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
Frame indexes are handled in different version of TVPaint in a different way. Mark In 5 may have frame index 5 in rendering in one version but index 10 in another - that is cause by changing `Start Frame` in TVPaint.
- Start Frame in TVPaint is set to `0` before rendering and then back to previous value when rendering is done
- this way should work any version of TVPaint the same way
=> TVPaint: Fixed rendered frame indexes

openpype/hosts/maya/plugins/create/create_xgen.py, openpype/hosts/maya/plugins/load/load_reference.py, openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py, openpype/hosts/maya/plugins/publish/extract_pointcache.py, openpype/hosts/maya/plugins/publish/extract_xgen_cache.py, openpype/plugins/publish/integrate_new.py, website/docs/artist_hosts_maya.md
This PR adds basic support for publishing and loading Xgen in Maya. It only works with interactive grooms, which get published as maya ascii with any attached scalps and at the same time as baked alembic curves.
To test this you need to create a mesh with xgen interactive groom. Then you can create new xgen family with the xgen node selected. When you publish you should end up with .ma and .abc representations. 
At the moment there are no settings, but will need to probably add at least enable/optional settings for the plugins
=> Maya: Add Xgen family support

openpype/hosts/maya/plugins/create/create_animation.py, openpype/hosts/maya/plugins/create/create_model.py, openpype/hosts/maya/plugins/create/create_pointcache.py, openpype/hosts/maya/plugins/publish/extract_animation.py, openpype/hosts/maya/plugins/publish/extract_model.py, openpype/hosts/maya/plugins/publish/extract_pointcache.py
Add possibility to keep facesets in the alembic exports. This technically allows to keep material assignments (not the materials) on the alembic when it gets imported to a different host than maya.
=> Add face sets to exported alembics

igniter/bootstrap_repos.py
When adding files to the zip, the file path is not "resolved", resulting in errors in some cases (eg: when using UNC paths).
For example in Windows if OpenPype is installed on a mapped network drive:
- Let's consider the directory "\\\\192.168.1.1\dev" mapped to drive "W" (containing the OpenPype cloned repository).
- In a PowerShell session, if the current directory is "W:\OpenPype", and the script ".\tools\create_zip.ps1" is executed, the following error occurs:
```
ValueError: 'W:\\OpenPype\\igniter\\...\\openpype\\action.py' does not start with '\\\\192.168.1.1\\dev\\OpenPype'
```
and the zip creation is cancelled.
If executing the script in "\\\\192.168.1.1\dev\OpenPype", the error doesn't occur.
By resolving the path, we avoid the issue.
=> Resolve path when adding to zip

openpype/plugins/publish/collect_scene_version.py
- `CollectSceneVersion` plugin has defined hosts for which should be processed instead of excluding them in process method
[cuID:yjx9fq]
=> Global: Define hosts in CollectSceneVersion

openpype/plugins/publish/integrate_new.py, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Closes #1894 
How to test;
-------------
- configure selection with selected application of specific template in `Setting > Project > Global > Publish plugins > IntegrateAssetNew > Template name profiles` (for example you can set 'workfile' family to 'work' template instead standard 'publish' for Standalone Publisher)
[cuID:yjx9d9]
=> #1894 - adds host to template_name_profiles for filtering

openpype/plugins/publish/start_timer.py, openpype/plugins/publish/stop_timer.py, openpype/settings/defaults/system_settings/modules.json, openpype/settings/entities/schemas/system_schema/schema_modules.json
This feature will stop the timer when publishing and start it again at the end of publishing.
This feature is an optional setting which is disabled by default.
Technically I'm on stopping the timer when reaching the extraction stage of the publishing, which is usually time consuming part. The reason for doing this was because users can often stop the publishing process at the collection stage, so stopping the timer at the collection stage would need complex logic to start the timer again.
Due to the above it might be worth exploring other names for the setting since we technically only disregard the extraction and integration.
Our use case for this, is that we need to measure work hours and not machine hours. Machines can have different specs, so measuring time spent while the machine is …
=> Disregard publishing time.

tools/build_dependencies.py
The file `python3.dll` from the build needs to be copied over to the `dependencies/PyQt5` folder for the build to work on other machines.
Fixes this error:
```
*** No DB connection string specified.
--- launching setup UI ...
Qt.py [warning]: ImportError(QtCore): DLL load failed: The specified module could not be found.
Qt.py [warning]: ImportError(QtGui): DLL load failed: The specified module could not be found.
Qt.py [warning]: ImportError(QtHelp): DLL load failed: The specified module could not be found.
Qt.py [warning]: ImportError(QtMultimedia): DLL load failed: The specified module could not be found.
Qt.py [warning]: ImportError(QtNetwork): DLL load failed: The specified module could not be found.
Qt.py [warning]: ImportError(QtOpenGL): DLL load failed: The specified module could …
```
=> Fix PyQt5 on Windows build.

.github/workflows/prerelease.yml, tools/ci_tools.py
Right now we are automatically rising minor version every time an `enhancement` is merged into the develop. Due to the speed that we are adding things, that are technically enhancement, but they are very small, it effectivelly means, that `patch` versioning never kicks in. We practically never have only a bugfix release. 
This PR proposes a shift in this strategy. We'll divide all PRs into `Features`, `Enhancements` and `Bugs`
`Feature` - adds new functionality that specifically affects user.
`Enhancement` - improves on existing functionality, adds new things that don't directly affects what user sees (most of the backend changes)
`Bug` - Fixing an issue with existing functionality. 
Separation between these is of course somewhat arbitrary and if you're unclear if what you are submitting …
=> CI: change release numbering triggers

pype/plugins/maya/publish/submit_maya_deadline.py
This PR adds ability to customize Deadlines `Job_Info` and `Plugin_Info` from presets.
It will update existing data prior to submission, useful for adding / overriding
⏩ **OpenPype 3 version: #1797
|---|
=> Maya: Deadline custom settings - Pype 2 backport

openpype/hosts/tvpaint/plugins/publish/collect_instances.py, openpype/hosts/tvpaint/plugins/publish/collect_workfile.py, openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py, openpype/plugins/publish/collect_host_name.py
Some collectors have order below `-0.5` which is out of range of Collectors order so headless publishing would not process them before collectors.
- changed orders to valid orders for `CollectHostName` and TVPaint collectors
=> Collectors order

openpype/lib/applications.py, openpype/tools/workfiles/app.py
Function looking for last workfile is always using `"work"` template key.
- during start of application may not find last workfile if `"work"` template key is not used
- template key is passed to function which handles that
=> Last workfile with multiple work templates

openpype/hosts/standalonepublisher/plugins/publish/extract_harmony_zip.py
- `ExtractHarmonyZip` plugin is using `"work"` template name all the time which has changed with https://github.com/pypeclub/OpenPype/pull/1966
- `ExtractHarmonyZip` uses `get_workfile_template_key_from_context` to get right template name
=> Standalone Publisher: Extract harmony zip handle workfile template

openpype/settings/entities/input_entities.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/system_schema/example_schema.json, openpype/tools/settings/settings/item_widgets.py, openpype/tools/settings/settings/style/style.css, openpype/widgets/sliders.py
Number inputs may have slider in UI that can be helpfull in few cases.
- added attribute `show_slider` to `number` type which will cause that slider will show in UI
=> Settings UI: Number sliders

openpype/plugins/publish/stop_timer.py
This causes the timer to stop on validation instead of extraction.
=> Stop timer was within validator order range.

openpype/settings/entities/input_entities.py, openpype/settings/entities/schemas/README.md, openpype/settings/entities/schemas/system_schema/schema_modules.json, openpype/tools/settings/settings/item_widgets.py, openpype/tools/settings/settings/widgets.py
- number entity can have defined `"steps"` which define single step of number input (when using arrows of scroll wheel)
Resolves: https://github.com/pypeclub/OpenPype/issues/1999
=> Settings UI: Number with configurable steps

openpype/hosts/hiero/plugins/publish/precollect_clip_effects.py, openpype/hosts/hiero/plugins/publish/precollect_instances.py, openpype/hosts/hiero/plugins/publish/precollect_workfile.py, openpype/hosts/nuke/plugins/publish/precollect_instances.py, openpype/hosts/nuke/plugins/publish/precollect_workfile.py, openpype/hosts/nuke/plugins/publish/precollect_writes.py, openpype/hosts/resolve/plugins/publish/precollect_instances.py, openpype/hosts/resolve/plugins/publish/precollect_workfile.py
=> nuke, resolve, hiero: precollector order lest then 0.5

openpype/lib/__init__.py, openpype/lib/pype_info.py, openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py, openpype/modules/default_modules/ftrack/scripts/sub_event_processor.py, openpype/modules/default_modules/ftrack/scripts/sub_event_status.py, openpype/modules/default_modules/ftrack/scripts/sub_event_storer.py
Show OpenPype versions in event server status action for both zip and build. Also show executable path (or path to start.py when running from code).
- renamed `get_pype_version` to `get_openpype_version` (`get_pype_version` kept for backwards compatibility of opened PRs)
- added `is_running_from_build` function to be able know it openpype is running from code or build
- added `get_build_version` which should return version of build even if is not currently running version
- use new functions to pass information about processes to statuser
- information about processes are passed as list of lists to keep order
- statuser was modified to be able handle that situations (require restart of whole event server)
- run ftrack event server
- run `OpenPype Admin - Event server Status (...)` action …
=> Ftrack: Show OpenPype versions in event server status

openpype/lib/path_tools.py
- have expanding object `my_list = [1, *args]` where `args` is epxanded does not work in python 2 syntax which is used in openpype.lib right now and is breaking host implementations
- modified the line to work in python 2
=> General: Fix Python 2 breaking line

website/docs/admin_openpype_commands.md, website/docs/module_ftrack.md
- update which arguments can be used for launching of ftrack event server
- removed `no-credentials`, `store-credentials` and `ftrack-events-path` which are not used anymore
- modified example shell scripts for event server
- added `OPENPYPE_MONGO` as environment
- modified value of `OPENPYPE_DEBUG` to `1`
- `pushd` path is not explicit
- linux execute command starts with `./openpype_console`
=> Documentation: Ftrack launch argsuments update

openpype/modules/default_modules/ftrack/event_handlers_server/action_sync_to_avalon.py, openpype/modules/default_modules/ftrack/event_handlers_user/action_sync_to_avalon.py, openpype/modules/default_modules/ftrack/lib/ftrack_base_handler.py
- sync to avalon actions (local and server) create job on start
- job has uploaded file with traceback if job crashes
- removed traceback message from report to user
- methos `show_interface` have ability to modify submit button label
One possible way is to raise exception before `self.synchronize(...)` in `openpype/modules/default_modules/ftrack/event_handlers_user/action_sync_to_avalon.py` (line 78).
```
try:
raise ValueError("Test")
result = self.synchronization(event, project_name)
except Exception:
...
```
Closes https://github.com/pypeclub/OpenPype/issues/1310
=> Ftrack: Sync to avalon actions have jobs

openpype/modules/default_modules/python_console_interpreter/window/widgets.py
Console tool may be hidden on show because of previous invalid size stored in workstation registers.
- resize console window only once and make sure it has minimum size
- I've changed size of console tool on HD resolution to minimum and closed
- restarted tray and showed console tool on 4K monitor
- window was visible in task manager but was not visually visible
=> Console interpreter: Handle invalid sizes on initialization

openpype/modules/base.py, openpype/modules/default_modules/avalon_apps/avalon_app.py, openpype/modules/default_modules/clockify/clockify_module.py, openpype/modules/default_modules/deadline/deadline_module.py, openpype/modules/default_modules/log_viewer/log_view_module.py, openpype/modules/default_modules/muster/muster.py, openpype/modules/default_modules/project_manager_action.py, openpype/modules/default_modules/python_console_interpreter/module.py, openpype/modules/default_modules/settings_module/settings_action.py, openpype/modules/default_modules/slack/slack_module.py, openpype/modules/default_modules/sync_server/sync_server_module.py
- `connect_with_modules` method on modules is not abstract
- method make sense only for modules that have defined interface which is not true in most of cases
=> Modules: Connect method is not required

openpype/lib/pype_info.py, openpype/tools/workfiles/app.py
Auto task selection is not working because for selecting is used index from source model instead of proxy model which is invalid in selection model.
- use source model of task view to select task so indexes are valid
- open workfiles tool in any host and current task should be preselected when tool is opened
=> Workfiles tool: Task selection

openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_old_versions.py
Ftrack action that use `valid_roles` method must have set attribute `settings_key` which is missing on `DeleteOldVersions` action.
- added missing `settings_key` attribute for delete old versions action
=> Ftrack: Delete old versions missing settings key

openpype/hosts/nuke/api/lib.py
=> PYPE-1835_Create-Read-From-Rendered---Typo

openpype/lib/__init__.py, openpype/lib/applications.py, openpype/lib/avalon_context.py, openpype/lib/plugin_tools.py, openpype/lib/profiles_filtering.py, openpype/plugins/publish/integrate_new.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/defaults/project_settings/global.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/defaults/project_settings/slack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_slack.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_workfile_build.json, openpype/settings/entities/schemas/projects_schema/schemas/template_workfile_options.json
Use rather task types in settings than task names (mainly in profiles).
- replaced custom functions handling profiles with function from `openpype.lib.profiles_filtering`
- all settings profiles where was possible to have task name filtering also have task type filter
- modified code where modified settings are used - Affected:
- `IntegrateNew`
- `get_subset_name`
- open last workfile on start
- workfile tool on startup
This has few disadvantages:
- changing of task types in project anatomy is not automatically propagated to enums (comboboxes) storing task type value
- it is possible to remove task type and store the task type in profiles at the same time
- it is possible (in theory) to have task with type that is not in project config
I've kept task name profiling to not break backwards …
=> General: Task types in profiles

openpype/hosts/harmony/plugins/publish/extract_render.py, openpype/hosts/photoshop/plugins/publish/extract_review.py, openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py, openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py, openpype/lib/__init__.py, openpype/lib/execute.py, openpype/plugins/publish/extract_jpeg_exr.py, openpype/plugins/publish/extract_otio_audio_tracks.py, openpype/plugins/publish/extract_otio_review.py, openpype/plugins/publish/extract_otio_trimming_video.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/extract_review_slate.py
Some versions of python (on unix) may not be able to parse subprocess arguments so they can know which part is executable and which parts are arguments. This is mainly issue of ffmpeg arguments where in most of cases use string as full command.
Pass arguments to `subprocess.Popen` as list instead of string.
- list of arguments is used directly everywhere where we know all arguments of the subprocess command
- added function `split_command_to_list` which should be able return list of arguments created from passed subprocess command
- added function `path_to_subprocess_arg` which decides if path should be wrapped in quotes in subprocess arguments
- using always quotes may break `split_command_to_list` which can't know if quotes are intended or not
- use `split_command_to_list` where …
=> FFmpeg: Subprocess arguments as list

openpype/tools/settings/settings/base.py, openpype/tools/settings/settings/dict_mutable_widget.py, openpype/tools/settings/settings/item_widgets.py, openpype/tools/settings/settings/lib.py
Make UI more responsive when modifying values.
- value changes of few inputs are deffered and emitted to entity once per 300ms after last change
- changes in UI (specially text changes) are more responsive
- styles and validations are applied with 300ms offset after last change
=> Settings UI: Deffered set value on entity

openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py, openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py, openpype/plugins/publish/extract_jpeg_exr.py, openpype/plugins/publish/extract_review.py, openpype/plugins/publish/extract_review_slate.py
Shell flag causes issue when ffmpeg is called with a list of arguments
=> Removed shell flag in subprocess call

openpype/hosts/nuke/plugins/publish/validate_proxy_mode.py
Adding Proxy mode validator for Nuke host
1. Open your testing scene.
2. Toggle Proxy button on (CTRL+P). 
3. Then open publisher and validate. 
4. It should fail. 
5. Then use repair action to fix it. 
6. Proxy should switch off.
=> Nuke: proxy mode validator

openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json, openpype/settings/entities/schemas/projects_schema/schemas/template_publish_families.json, openpype/tools/libraryloader/app.py, openpype/tools/loader/__init__.py, openpype/tools/loader/app.py, openpype/tools/loader/model.py, openpype/tools/loader/widgets.py, openpype/tools/utils/lib.py
- be able to modify families filtering in loader based on profiles
- added Loader section in settings with families filter profiles
- added multiselection enum with (probably) all possible families that can be in loader visible
- any modifications of the list are welcomed
- maybe we could add there a list of string and let it change manually?
- family config simplified as most of it is not available in OpenPype
- states of families are defined by profiles from settings
Depends on https://github.com/pypeclub/OpenPype/pull/2038
=> Loader: Families filtering

openpype/hosts/nuke/plugins/load/load_sequence.py, openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
- When subsets are created by standalone publisher and they are `jpg` sequence, `jpg` as thumbnail was created and the name was also `JPG`, so build workflow was chosen randomly. 
- Nuke is reading a single JPG image  a sequence.
=> Differentiate jpg sequences from thumbnail

openpype/hosts/hiero/otio/hiero_export.py, openpype/hosts/hiero/plugins/publish/precollect_instances.py, openpype/hosts/hiero/plugins/publish/precollect_workfile.py, openpype/plugins/publish/collect_hierarchy.py, openpype/plugins/publish/collect_otio_frame_ranges.py, openpype/plugins/publish/collect_otio_review.py, openpype/plugins/publish/collect_otio_subset_resources.py
- otio ignoring disabled and offline clilps
1. open your testing timeline
2. make first clip offlined or disabled
3. publish
4. all should work as expected
=> Hiero: Editorial fixes

openpype/hosts/nuke/plugins/publish/increment_script_version.py, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Plugin for increasing workfile version is now configurable, optional and families could be selected. (Default setting as per current configuration in the plugin.)
Closes https://app.clickup.com/t/6658547/PYPE-1839
On client side Setting must be set as they request!
=> Settings for Nuke IncrementScriptVersion

openpype/modules/default_modules/timers_manager/timers_manager.py
- fixed typo in timers manager `timer_stopper` -> `timer_stopped`
=> Timers manger: Typo fix

tools/build_win_installer.ps1
This PR is adding support for **pyenv** on Windows to `build_win_installer` script.
=> Tools: add support for pyenv on windows

openpype/hosts/maya/plugins/create/create_setdress.py, openpype/hosts/maya/plugins/publish/validate_setdress_root.py
When publishing setdress in Maya, top group node will be checked if it's part of publishing content.
What does that mean ?
Say you have these in Maya outliner, 4 loaded models all parented under one top group node:
```
forestSet_GRP
+ Foo_01:modelMain
+ Foo_02:modelMain
+ Bar_01:modelMain
+ Bar_02:modelMain
```
And you created two `setdress` instances for publish :
```
setdressFoo
+ Foo_01:modelMain
+ Foo_02:modelMain
setdressBar
+ Bar_01:modelMain
+ Bar_02:modelMain
```
Without this new feature, the top group node and all it's child nodes will be published together. Which means all those 4 models will be in both `setdressFoo` and `setdressBar` subsets.
Now with this PR, the unexpected result in above example will not happen.
---
Resolves client ticket …
=> Maya: Validate setdress top group

openpype/hosts/maya/api/__init__.py, openpype/hosts/maya/plugins/inventory/import_modelrender.py, openpype/hosts/maya/plugins/load/load_reference.py, openpype/hosts/maya/plugins/publish/collect_look.py, openpype/hosts/maya/plugins/publish/extract_look.py
This close pypeclub/client#137.
Enable extracting render attribute sets (e.g. V-Ray Displacement) while publishing model, as model representation's metadata. So optionally, lookdev artist could use them while working on the model as for a suggestion (or bootstrap) from modeler.
1. Say a modeler have this scene ready to publish a model. There are some simple shading and displacement sets applied to those meshes.
2. Modeler published the model, lookdev artist takeover and start to work. Model has been referenced from Loader.
3. Lookdev artist go to the Scene Inventory tool, trying to apply render attribute sets which has been published with current loaded model, to see if they could help.
4. Render attribute sets has been imported, now the lookdev artist can play with them however he/she …
=> Maya: Enable publishing render attrib sets (e.g. V-Ray Displacement) with model

openpype/tools/project_manager/project_manager/__init__.py, openpype/tools/project_manager/project_manager/constants.py, openpype/tools/project_manager/project_manager/model.py, openpype/tools/project_manager/project_manager/window.py
- current project is not defined by variable but by combobox selection
- refreshing of projects won't clear whole model but only remove not available and add new
- added sort/filter proxy model for projects to filter `< Select project >` item when any project is selected and to sort projects by name
- disable create folders button when invalid project is selected
=> Project manager: Filter first item after selection of project

openpype/hosts/nuke/__init__.py, openpype/lib/applications.py
UI scaling in Nuke does not work because `QT_AUTO_SCREEN_SCALE_FACTOR` env is set on nuke start.
- environments that are removed during env preparation are also popped from result
- `QT_AUTO_SCREEN_SCALE_FACTOR` is popped from nuke environments
=> Nuke UI scaling

openpype/hosts/blender/plugins/publish/extract_blend.py
Blender uses relative paths to track images. So, when publishing assets, the textures are missing. 
To fix the problem, this PR packs images used by the published assets in the blend files.
=> Blender: fix texture missing when publishing blend files

openpype/hosts/blender/plugins/load/load_rig.py
When loading rigs in Blender, modifiers in curves lost the connections to the armature. This PR fixes this bug by retargeting the object of the modifier during the loading.
=> Blender: fixed Curves with modifiers in Rigs

start.py
Fix issue caused by https://github.com/pypeclub/OpenPype/pull/2054
- oiio tool path hierarchy is different on linux than on windows
- fixed oiio tool path for linux machines
=> General: Startup validations oiio tool path fix on linux

openpype/settings/__init__.py, openpype/tools/tray/pype_tray.py
- tray will show a message saying that default settings are not set
- remove any key from default settings and run tray
Feel free to modify title and message.
Resolves https://github.com/pypeclub/OpenPype/issues/1385
=> Tray UI: Message box about missing settings defaults

openpype/hosts/maya/api/__init__.py, openpype/modules/default_modules/sync_server/sync_server_module.py
Currently this checks if Site Sync is enabled (globally and for project) and if User has set `active_site` to `local` (eg. User is synching files locally). If so, it puts into `dirmap` root(s) from `remote_site` as a source and `local` site as a destination.
It completely ignores configuration in Settings, if anyone could produce use case when this would be needed, please go ahead and share.
(I am not super happy about mixing Site Sync logic with host implementation, but couldn't figure out better option.)
=> Added choosing different dirmap mapping if workfile synched locally

openpype/tools/tray/pype_tray.py
Tray menu show is offset by few milliseconds because of double-click callback which can cause that menu is not shown at position where mouse clicked. This PR should change that first mouse click position is stored and used to show menu.
- show menu at position where first click happened
=> Tray UI: Show menu where first click happened

pype/plugins/global/publish/extract_burnin.py, pype/plugins/global/publish/extract_review.py, pype/scripts/otio_burnin.py
Further to conversations on Discord the burnin script uses bitrate which greatly reduces the visual quality of video when applying burnin effects. Instead the Constant Rate Factor (crf) is a better measure of visual quality.
crf cant be queried by `ffprobe` so its better to use metadata instead. I've opted for getting this metadata through pyblish rather than encoding the metadata onto the video, because metadata for different video formats can get tricky.
Since Openpype ships with `-crf 18` by default, all burnins should get this data.
=> Use crf for quality in burnin

openpype/hosts/maya/plugins/publish/validate_instance_in_context.py, openpype/hosts/nuke/plugins/publish/validate_instance_in_context.py, openpype/plugins/publish/collect_avalon_entities.py, openpype/plugins/publish/start_timer.py, openpype/plugins/publish/stop_timer.py, openpype/plugins/publish/validate_containers.py, openpype/plugins/publish/validate_intent.py, openpype/plugins/publish/validate_version.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/defaults/project_settings/maya.json, openpype/settings/defaults/project_settings/nuke.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
- `ValidateInstanceInContext` split into maya and nuke plugin
- added settings for each of them
- context anatomy collector also stores task type of  context
- start/stop timer plugins are using settings stored in context instead of loading them again
- `ValidateIntent` is for all hosts by default and added profiles to filter validations (by default is plugin disabled)
- `ValidateVersion` added `active` attribute to be able define if is activated by default
- `ValidateContainers` - currently has settings in each host settings and not sure if should be added to global publish plugins settings and if yes than it will probably need profiles but at the same time should have `optional` (maybe) does it make sense to have both `optional` + `active` and `profiles` under that?
- …
=> Global: add global validators to settings

igniter/tools.py, openpype/lib/mongo.py, openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py, start.py
Since 30.9.2021 does not work cloud mongo connection correctly because of invalid ssl certificates on most of machines. It is issue mainly on Windows machines.
- add certifi certificate to creation of mongo connection if `mongodb+srv` scheme is used or when `ssl=true` or `tls=true` is in mongo url query
- add session creation to validation of mongo connection
- server info does not trigger any mongo server queries which are important to validate
- removed decompose/compose function for mongo parsing from igniter (which removes possibly important attributes)
- fixed import order bug caused by https://github.com/pypeclub/OpenPype/pull/2091#event-5387393877
- validation and mongo connection inside openpype happens on single place through `OpenPypeMongoConnection` class
- avalon started to …
=> General: Cloud mongo ca certificate issue

openpype/hosts/tvpaint/api/plugin.py
Creators are using context from `avalon.api.Session` which may not be the same as context of current workfile.
TVPaint creators set `asset` and `task` keys using dynamic data loaded from currently opened workfile.
=> TVPaint: Creator use context from workfile

openpype/modules/default_modules/ftrack/event_handlers_user/action_create_cust_attrs.py, openpype/modules/default_modules/ftrack/ftrack_module.py, openpype/modules/default_modules/ftrack/lib/__init__.py, openpype/modules/default_modules/ftrack/lib/constants.py
Ftrack cause warning message on save of project settings becaue `active` custom attribute was not found.
- ftrack check only known attributes on save all others are skipped
- intent custom attribute key has constant
- enable ftrack module and login
- go to project settings in setting UI
- go to any project that exists on ftrack
- change anything in attributes and save settings
- warning message about `active` custom attribute should not appear
=> Ftrack: Project settings save custom attributes skip unknown attributes

openpype/tools/settings/settings/constants.py, openpype/tools/settings/settings/widgets.py
Project list in settings may not sort them properly because sorting is based on alphabetical order.
- project proxy model have custom sorting method to put default project at first place than active projects and inactive projects as last
- project model cares about it's refreshing instead of refreshing out of model
- refresh of model is real refreshing (does not clear all projects on refresh but only removes not existing and adds new projects)
- roles are constants
- create project starting with number
- list should show them under `< Default >` item
=> Settings UI: Project model refreshing and sorting

openpype/modules/default_modules/sync_server/providers/sftp.py
Bug is manifesting in Maya SceneInventory
During testing another issue was found in Blender 2.93 (only), where Blender's own libraries conflict with a provider. (Issue occured in Loader and Manage.. in OP menu).
=> Fix broken import in sftp provider

openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
- seems like TVPaint changed how "loop" behavior is called in newer versions which has changed to "repeat"
- added second variant of "loop" behavior - "repeat"
=> TVPaint: Behavior name of loop also accept repeat

openpype/hosts/houdini/startup/scripts/houdinicore.py
Adding an equivalent to 123.py for Houdini Core.
123.py is only read by Houdini FX, whereas Houdini Core expects a `houdinicore.py` file. 
See docs here: https://www.sidefx.com/docs/houdini/hom/locations.html#startup
=> Add startup script for Houdini Core. 

openpype/tools/project_manager/project_manager/model.py
PySide2 returns `QByteArray` from mime data which is not the same as in PyQt5. That causes error:
```
File "C:\Users\iLLiCiT\PycharmProjects\pype3\openpype\tools\project_manager\project_manager\view.py", line 338, in keyPressEvent
self._paste_items()
File "C:\Users\iLLiCiT\PycharmProjects\pype3\openpype\tools\project_manager\project_manager\view.py", line 381, in _paste_items
self._source_model.paste_mime_data(index, mime_data)
File "C:\Users\iLLiCiT\PycharmProjects\pype3\openpype\tools\project_manager\project_manager\model.py", line 1463, in paste_mime_data
encoded_data = QtCore.QByteArray.fromRawData(raw_data)
TypeError: 'PySide2.QtCore.QByteArray.fromRawData' called with wrong argument types:
PySide2.QtCore.QByteArray.fromRawData(QByteArray)
Supported …
```
=> Project Manager: Fix copying of tasks

openpype/settings/entities/__init__.py, openpype/settings/entities/base_entity.py, openpype/settings/entities/color_entity.py, openpype/settings/entities/dict_conditional.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/enum_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/list_entity.py, openpype/settings/entities/root_entities.py, openpype/settings/entities/schemas/README.md
Have entity that will use roots of current project as keys and be able define type of a value.
- fixed typo `_item_initalization` -> `_item_initialization` 
- adde new settings entity `dict-roots`
- uses root keys as keys and value type can be defined similar way like in dict-modifiable` or in `list` by defying `object_type`
- entity is always marked as overriden (similar to anatomy)
Entity is not in examples because (like anatomy) is project specific and changes it's structure based on current project.
This example can be added anywhere in project settings and should work:
```
{
"key": "test_roots",
"type": "dict-roots",
"label": "Test roots",
"object_type": {
"type": "path",
"multiplatform": true,
"multipath": false
}
}
```
Planned for project settings of providers in sync server.
=> Settings: Dictionary based on project roots

openpype/hosts/standalonepublisher/plugins/publish/collect_bulk_mov_instances.py, openpype/hosts/tvpaint/plugins/publish/collect_instances.py, openpype/hosts/tvpaint/plugins/publish/collect_workfile.py, openpype/lib/__init__.py, openpype/lib/plugin_tools.py
Right now there is requirement to pass asset id into `get_subset_name` which is used to query asset document and get it's tasks but in most of cases we already have access to asset document which can be passed there.
Issue was created to modify behavior in Creator tool. Since new publisher requires new creators and logic for them this is preparation PR for new publisher.
- added new function `get_subset_name_with_asset_doc` which does not require to query asset anymore
- merged logic of both `get_subset_name` and `get_subset_name_with_asset_doc` into `_get_subset_name`
- use function in collectors where can be used
=> Subset name: Be able to pass asset document to get subset name

openpype/lib/delivery.py
Delivery of sequence require `frame` key in template and delivery function crashes on invalid bug when the key is not available.
- added checks of template existence
- added check of having `frame` formatting key in template for sequence delivery
=> Delivery: Check 'frame' key in template for sequence delivery

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/menu.py, openpype/settings/defaults/project_anatomy/imageio.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Set Colorspace in Maya color management preference from project setting for new scenes and also add menu item for change open scenes .
1. Go to ( studio setting >> project >> anatomy >> color management >> Maya ) .
2. Set the OCIO config path in your system. . like `/aces_1.0.2/config.ocio`.
3. Set the Rendering Space .. like `ACES - ACEScg`.
4. Set the Viewer Transform .. like `Raw (ACES)`.
5. Create new Maya scene or open existing Maya scene then from OpenPype menu press `Set Colorspace`.
6.check color management tab from Maya preferences.
=> Maya : Colorspace configuration 

openpype/hosts/maya/api/lib.py, openpype/hosts/maya/api/menu.py
Set the device aspect ratio and pixel aspect ratio from asset setting in Maya .
1. Set resolution and pixel aspect ratio in project manager for asset  .
5. Create new Maya scene or open existing Maya scene then from OpenPype menu press `Reset Resolution`.
6. Check resolution and pixel aspect ratio from Maya render setting.
=> Maya: Aspect ratio

openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py, openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_asset.py, openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Object of `Queue` can easily became a thread killer as is using thread locks which may stop whole process without visible reason. There is no reason to use `Queue` in those cases so for a "better sleep" were replaced with `deque` which does the job.
- replaced `queue.Queue` with `collections.deque` in cases where is not needed thread safe queue
- everything should work the same way
- change affect:
- event sync to avalon
- action sync to avalon
- action delete assets/subsets
=> Ftrack: Replace Queue with deque in event handlers logic

openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
It seems that it is possible to have missing `ftrackId` on project document but sync to avalon event always expect that the key is filled.
- if the `ftrackId` key is missing on project document then is updated directly with current ftrack project
=> Ftrack: Fill missing ftrack id on mongo project

openpype/tools/mayalookassigner/app.py, openpype/tools/utils/lib.py, openpype/tools/workfiles/app.py
Workfiles tool still use removed files from avalon tools.
- use functions/classes already moved to openpype in workfiles tool (and one in look assigner)
=> Tools: Workfiles tool don't use avalon widgets

openpype/hosts/blender/plugins/publish/extract_blend.py
There might be cases where a texture node in the shader has no image. If this happens, an error is thrown because the image in the node should be packed. This PR checks if the image exists, before packing it.
=> Blender: Fix trying to pack an image when the shader node has no texture

openpype/modules/default_modules/sync_server/providers/dropbox.py, openpype/modules/default_modules/sync_server/providers/gdrive.py, openpype/modules/default_modules/sync_server/providers/local_drive.py, openpype/modules/default_modules/sync_server/providers/sftp.py, openpype/settings/entities/__init__.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
Reduce settings of sites for sync server in project settings. Now it shows settings for all providers for each site name and site names must be manually added.
- added new settings entity `sync-server-sites`
- entity works as dictionary children based on sync server system settings
- all site names are always available in project settings
- each site have `enabled` boolean to know if should be enabled for the project
- other schemas  for value are get from providers using `get_project_settings_schema`
Use this entity and replace current `site` item in settings. That require to modify how sync server module uses settings and probably will have to keep backwards compatibility. So it should be done in different PR.
Change sites in project settings schemas to this:
```
{
"type": …
```
=> Settings: Site sync project settings improvement

openpype/plugins/publish/validate_unique_names.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Hello,
A maya validator checking that each transform has a unique name (ie: assuring cmds never raise the error "More than one object matches name: pCube1")
=> Maya : validate unique names

openpype/tools/libraryloader/app.py, openpype/tools/loader/app.py, openpype/tools/utils/lib.py
- center window function makes sure that `y` is in screen
- center loader and library loader tools on first show
=> Tools: Center loader and library loader on show

openpype/tools/pyblish_pype/control.py
When there are registered targets `"default"` target is not added to list so all plugins without changed targets are skipped.
- make sure targets contain default target
=> Pyblish Tool: Fix targets handling

openpype/modules/base.py
OpenPype addon/module can't be used if does not have `__init__.py` file because in that is not possible to find class inheriting `OpenPypeModule`. At the same time it is possible to filter empty folders without any content or just `.pyc` files which remained after deleted module.
- skip module directories without `__init__.py` file when loading modules
=> General: Skip module directories without init file

openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Some keys are really weird in PS (grain instead of green etc)
Created explicit enum. Setting needs to be resaved for it to work!
=> Fix - enum for color coding in PS

openpype/lib/python_module_tools.py
ModuleType expect string type in initialization but in Python 2 is used default passed type `unicode` which breaks the creation.
- fix Python 2 unicode with conversion to `str`
Run Houdini with Python 2 which should raidse unicode error with current develop and work fine with this PR.
=> Python 2: Unicode to string conversion

openpype/cli.py, openpype/modules/README.md, openpype/modules/base.py, openpype/modules/default_modules/ftrack/ftrack_module.py, openpype/modules/example_addons/example_addon/addon.py, openpype/pype_commands.py
Modules should be able to define their cli commands which could help to reduce commands in general openpype commands.
- added cli group `module` into general cli commands
- each module has `cli` method which is called on start of openpype and gives ability to add commands to `module` click group
- method by default does nothing
- example addon has example cli commands
- ftrack adds `eventserver` command (did not remove the old)
- we can replace `./openpype_console eventserver *arg` with `./openpype_console module ftrack eventserver *args`
- calling the module commands has this order
- `<op executable> module <module name> <command> *args`
- `<module name>` is recommendation but can't be forced
- each of the step can have help
=> Modules: Module can add cli commands

openpype/hosts/webpublisher/webserver_service/webpublish_routes.py, openpype/hosts/webpublisher/webserver_service/webserver_cli.py, openpype/settings/defaults/project_settings/photoshop.json
Fixes problem with multiple batches in row.
=> Added queue for studio processing in PS

openpype/plugins/publish/collect_anatomy_instance_data.py, openpype/plugins/publish/validate_version.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Feature which allow to configure Openpype publish to always use the workfile version
Having the same version number for the workfile, his produced files (review, publish, render, ...) and the tracked version (within Shotgrid, ftrack, ...) can be more simpler to manipulate files and versions
You can activate this option in the global project settings, in the Collect Anatomy Instance Data plugin
The downside of this feature is that you lose the ability to publish multiple times from the same workfile, which is prevented by the plugin ValidateVersion
=> Add a "following workfile versioning" option on publish

openpype/modules/default_modules/ftrack/lib/ftrack_base_handler.py
Method `get_project_from_entity` on base ftrack event handler does not expect cases that parent of `AssetVersion` is project.
- fix cases when parent of asset version is project
=> Ftrack: Base event fix of 'get_project_from_entity' method

openpype/lib/path_tools.py, openpype/modules/default_modules/sync_server/providers/dropbox.py, openpype/modules/default_modules/sync_server/providers/gdrive.py, openpype/modules/default_modules/sync_server/providers/local_drive.py, openpype/modules/default_modules/sync_server/providers/sftp.py
It was using 'roots' which resulted in Nuke and Maya chocking on it because dirmap functionality (which looks at Site Sync  Local Settings).
Previously `root` key was used, this PR returns to it as a safer option. (And it follows Anatomy etc.)
=> Site Sync settings should contain 'root' key

openpype/modules/default_modules/ftrack/ftrack_module.py
Ftrack session creation always looks into keyring credentials which crashes ftrack event server running on linux and ftrack cares only about changes in anatomy values but changes in settings may not reflect required changes in Ftrack.
- ftrack session creation first look for credentials into environments (fixes ftrack event server)
- ftrack callback on anatomy setting changes will check all values stored in attributes and push changes into ftrack
=> Ftrack: Session creation and Prepare project

openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
PR https://github.com/pypeclub/OpenPype/pull/2203/files was fixing not existing `ftrackId` on project document but the already cached project document was not updated so for rest of work of event is still unset.
- store new ftrack id to cached project document
=> Ftrack: Sync project ftrack id cache issue

openpype/scripts/otio_burnin.py
- mxf has not stored metadata on "streams" but under "format" key when loaded using ffprobe
- store whole result of ffprobe to burnins
- use source timecode from `"format"` key if is available
=> Burnins: Support mxf metadata

openpype/tools/context_dialog/window.py, openpype/tools/workfiles/app.py
- There was accidentally kept `selectionChanged` attribute access which breaks current context select dialog
- fix attribute acces in signal registration
=> Tools: Select Context dialog attribute fix

openpype/hosts/maya/plugins/publish/collect_render.py
when sending render job from maya on linux, the metadata json path is missing lead / from the path, hence crashing the publish.
This is quite dirty quick fix, we need to find something cleaner
=> Maya: Render publishing fails on linux

openpype/hosts/maya/api/lib_renderproducts.py, openpype/hosts/maya/plugins/create/create_render.py, openpype/hosts/maya/plugins/publish/collect_render.py, openpype/hosts/maya/plugins/publish/validate_rendersettings.py, openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json, tools/run_mongo.ps1
Fixing issue with data setting during Render Instance creation.
Support for configurable AOV separator characters. Those can be configured in Settings `project_settings/maya/create/CreateRender/aov_separator`. It can be `_` (underscore) - default, `-` (dash), `.` (dot).
Set your AOV separator characted is Settings and create new render instance in Maya - image prefix should match the selected character and render settings validator should pass too.
⚠️ this is using tag 3.5.0 as a base and needs to be merged there _and_ to develop to act as a hotfix
|---|
=> Maya: Support for configurable AOV separator characters

openpype/tools/context_dialog/window.py, openpype/tools/launcher/window.py, openpype/tools/libraryloader/app.py, openpype/tools/loader/app.py, openpype/tools/loader/widgets.py, openpype/tools/utils/assets_widget.py, openpype/tools/utils/host_tools.py, openpype/tools/utils/lib.py, openpype/tools/utils/tasks_widget.py, openpype/tools/utils/widgets.py, openpype/tools/workfiles/app.py
- separate asset specific logic into one segment and prepare few widgets with public methods ready to use without knowing inner logic
- get rid of accessing inner attributes of asset widget
- created `assets_widget.py` file in `openpype.tools.utils` containing all basics related to assets logic
- important objects are `SingleSelectAssetsWidget` and `MultiSelectAssetsWidget`
- asset widget does not work with asset documents but can return asset names or asset ids
- use new widgets in tools: loader, library loader, workfiles, context dialog and launcher
- reduced double refreshes in few of them (e.g. workfiles and launcher refreshed assets twice on show)
- implemented `PlaceholderLineEdit` which should fix issue with placeholders in Qt 5.12 and higher
- previous AssetWidget kept because is …
=> Tools: Assets widget

openpype/style/style.css, openpype/tools/sceneinventory/switch_dialog.py, openpype/tools/sceneinventory/widgets.py
Add option to choose from different loaders in switch dialog. Move feature from avalon-core into OpenPype's scene inventory.
- new method to get representation ids for currently context (selected containers and combobox values)
- have option to show menu popup if there are multiple loaders that can be used for loading
- loaders must match for all representations retrieved from currentl context of dialog
- loaders must have `switch` method available
- loaders with attribute `is_utility` set to True are skipped
- accept button has arrow which will show intersection of possible loaders for selected context so it is possible to use different loader
- that doesn't mean loading will work as expected
Depends on: https://github.com/pypeclub/avalon-core/pull/385
=> SceneInventory: Choose loader in asset switcher

openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_resources.py
Problem was, that if they were using their own .mp4 (accompanied to exr sequences) then it was not creating thumbnails.
=> Standalone: editorial not publishing thumbnails on all subsets

openpype/hosts/hiero/api/lib.py, openpype/hosts/hiero/api/menu.py, openpype/hosts/hiero/api/pipeline.py, openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/menu.py
- bad parenting of tools in nuke and hiero may break modality of tools for them
- pass right pointer to parent window into tools on callbacks
- open e.g. workfiles tool
- call `nuke.message("test")` from script editor
- message should popup in front of opened tool
- other tools in Nuke may depend on this PR in avalon-core https://github.com/pypeclub/avalon-core/pull/390
=> Tools: Parenting of tools in Nuke and Hiero

openpype/tools/workfiles/app.py
Fix wrong variable name _asse_id
=> Bug: fix variable name _asset_id in workfiles application

openpype/modules/default_modules/sync_server/providers/sftp.py
All root keys must be 'root', missed one for sftp provider :/.
=> Fix - missed wrong key for sftp provider

openpype/api.py, openpype/hosts/nuke/api/lib.py, openpype/lib/avalon_context.py
Since PR https://github.com/pypeclub/OpenPype/pull/2157 tasks are used as dictionary which was not modified in nuke's lib function `format_anatomy`.
- use `get_workdir_data` in `format_anatomy` function to get context data for filling template
=> Nuke: Anatomy fill data use task as dictionary

openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
Target "filesequence" is not registered with latest change of `publish` command.
- add "filesequence" target when submitting job to deadline
=> Deadline: Fix publish targets

openpype/modules/default_modules/royal_render/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
This quick PR is adding support for publishing channels in their respective subfolders:
For example you have file template like this `<Root>/<Scene>/<Layer>/<Aov>/<Scene>_<Layer>_<Aov>` and you have 3 AOVs like ID/Z/P.
Royal Render register them as *channels* and will now correctly pass them to publisher.
=> Royal Render: Support for rr channels in separate dirs

openpype/lib/vendor_bin_utils.py
- ffprobe is executed as string which may cause issues on linux machines and older python versions
- use list of arguments for ffprobe instead of command as string 
- removed `shell=True` which is not needed when list of arguments is passed
=> FFmpeg: Execute ffprobe using list of arguments instead of string command

openpype/tools/publisher/widgets/list_view_widgets.py
Publisher widget is calling not existing method which should be called on proxy model.
- fix method called on mapping of indexes
=> New Publisher: Fix mapping of indexes

openpype/lib/avalon_context.py, openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py, openpype/modules/default_modules/ftrack/lib/avalon_sync.py
OpenPype 3 variant of https://github.com/pypeclub/OpenPype/pull/2071 PR. Goal is to synchronize input links from ftrack to avalon database.
- avalon sync also synchronize input links to avalon entities
- added new event handler which is executed after sync event and modifies avalon entities based on changes of dependencies in ftrack
Both do the input links synchronization in a way that was designed for links. Data stored in asset document are sotred in `data` under `inputLinks` which is a list. Each item is dictionary(object) which contains `_id`, `type` and `source`. Asset links from ftrack have type of `breakdown` and source is `ftrack`.
=> Ftrack: Synchronize input links

openpype/modules/default_modules/sync_server/providers/sftp.py, openpype/modules/default_modules/sync_server/sync_server_module.py
----------------
- open Sync Queue
- try to do Re-sync active site on representation with a multiple files
- all files should be redownloaded (reuploaded)
Closes https://github.com/pypeclub/OpenPype/issues/2283
=> Alternate site for site sync doesnt work for sequences

openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/load/load_clip.py, openpype/hosts/nuke/plugins/load/load_image.py, openpype/hosts/nuke/plugins/load/load_script_precomp.py
adding to nuke loader plugin abstract class method for securing uniqueness of cotainer id for each loaded container node members
=> Nuke: inventory update removes all loaded read nodes

openpype/modules/default_modules/deadline/plugins/publish/submit_maya_deadline.py
Submitting job from Maya to Deadline was ignoring Limits and Groups set in Settings.
Close #2172
=> Maya: Deadline - fix limit groups

openpype/plugins/publish/integrate_new.py
If Site Sync was enabled, but both sites were same it failed with NPE.
Now it also checks if remote_site wasn't added yet
=> Validate remote_site for Site Sync

openpype/tools/workfiles/app.py
- workfiles tool can't find latest version because does not expect that templates from anatomy may contain `{task}` but should expect `{task[name]}`
- replace `{task}` with `{task[name]}` in loaded template
- open workfiles tool
- select context where already are some workfiles
- click of "Save as"
- write any comment to input and the version should be right (before created version 1)
=> Workfiles tool: Fix task formatting

openpype/hosts/nuke/api/plugin.py
- fixing multiplication of representations if run multiply on one nuke session. Problem was in having class method not to be restored on each instance initialization
=> nuke: do not multiply representation on class method

openpype/lib/execute.py
Function `run_subprocess` logs stderr as warning level of log which affect ffmpeg execution and since it is not really important to have warning level there it can be modified to less "violence" variant.
- log stderr as info log level instead of warning
Resolves https://github.com/pypeclub/OpenPype/issues/2308
=> General: Run process log stderr as info log level

igniter/tools.py, vendor/deadline/custom/plugins/GlobalJobPreLoad.py
When Deadline nodes are located in the cloud and spun up dynamically it sometimes produces issue of OP not connecting to Mongo resulting in weird failures.
Added more logging to GlobalJobPreload for better debugging, added possibility to drive timeout by AVALON_TIMEOUT, added explicit high timeout to GlobalJobPrelod.
---------------
This is difficult, only just by introducing connection lag to DB which would be noticeable when DL job is triggered.
=> Deadline timeout and logging

openpype/lib/avalon_context.py
There is a typo in `get_linked_asset_ids` from `openpype.lib`. Key `"inputsLinks"` should be `"inputLinks"`.
- fixed the key
=> InputLinks: Typo in "inputLinks" key

openpype/lib/delivery.py
Representations created on windows may have hierarchy with backslashes which is not handled in delivery.
- make sure paths are available at any platform
- replace backslashes with slashes and then normalize the path
=> Delivery: Fix delivery paths created on windows

openpype/lib/avalon_context.py, openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py, openpype/modules/default_modules/ftrack/lib/avalon_sync.py, openpype/plugins/publish/integrate_inputlinks.py, openpype/tools/assetlinks/widgets.py
- we have more variants of "id key" in item of `inpuLinks`
- plugin `IntegrateInputLinks` crashes if workfile is not published (there is a lot of cases when workfile is not published)
- plugin `IntegrateInputLinks` skips workfile related linking if is not found
- unified id key to `id` (kept backwards compatibility)
- should I add "auto-fix" of id keys
- we should be able to find link even without workfile instance in future
=> Input links: Cleanup and unification of differences

start.py
Vendorized binaries existence is validated by executing their executables which is slow and triggering console windows from openpype gui.
- validation happens by checking existence of executables
=> General: Don't validate vendor bin with executing them

openpype/hosts/nuke/api/plugin.py, openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
- do not add outputName into representation with baked mov if there is only one baking preset. This will not add it to final published name suffix.
- also bring consistency to quotations
=> nuke: bake preset single input exception 

openpype/plugins/publish/extract_review.py
We just tell that ffprobe couldn't read file but sometimes error may happen because of different reason like hardware limitations etc. which is hard to determine without knowing original message.
- add message of raised exception to new exception
=> General: FFprobe error exception contain original error message

openpype/modules/default_modules/timers_manager/timers_manager.py
Threads listening for mouse and keyboard events may cause thread lock on linux platform which cause that main process won't exit. It can cause that next process of OpenPype tray won't be initialized properly.
- disable auto stop timer for linux platform
Python module `pynput` is not written in a way we need to use it so we should check for different solution of this feature.
=> Timers Manager: Disable auto stop timer on linux platform

openpype/lib/anatomy.py, openpype/tools/workfiles/app.py
Anatomy should replace `{task}` with `{task[name]}` in templates on loading of settings because sometimes are templates from anatomy used without using it's formatting but only for getting the template. Auto repair of task type should be fixed before filling optional keys. 
- moved fix of task type before filling optional keys
- `{task}` is replaced with `{task[name]}` when anatomy loads data from settings
- removed replacement of `{task}` with `{task[name]}` in workfiles tool
1. Fix of task type for optional keys
- add `<{task}>` to any template and try to fill the template with data
```
{
"task": {
"name": "ANY_NAME"
}
<all other keys>...
}
```
2. Replacement of task with task[name]
- workfiles tool should find last workfile even with comment
=> Anatomy: Replaces task in templates on load

pype/plugins/tvpaint/publish/collect_deadline_submission.py, pype/plugins/tvpaint/publish/collect_instances.py, pype/plugins/tvpaint/publish/collect_json_data.py, pype/plugins/tvpaint/publish/collect_layer_behaviors.py, pype/plugins/tvpaint/publish/collect_tvpaint_info.py, pype/plugins/tvpaint/publish/collect_workfile.py, pype/plugins/tvpaint/publish/collect_workfile_data.py, pype/plugins/tvpaint/publish/extract_deadline_submission.py, pype/plugins/tvpaint/publish/extract_layer_exposure_frames.py, pype/plugins/tvpaint/publish/extract_sequence.py, pype/plugins/tvpaint/publish/submit_tvpaint_deadline.py
**Goal**
To submit TVPaint to Deadline.
**Motivation**
TVPaint licenses cant run multiple session on the same machine. This means artists have to wait on publishing/rendering, while not being able to work. Submitting to Deadline can offset the publishing to a dedicated machine or just queue up job for later.
**Implementation**
Depends on:
- https://github.com/pypeclub/pype-setup/pull/102
- https://github.com/pypeclub/avalon-core/pull/372
- need to use the OpenPype Deadline plugin; https://github.com/pypeclub/OpenPype/tree/develop/vendor/deadline
- to progress any errors to the OpenPype Deadline plugin, we need to make a TVPaint application that is attached. See below toml and bat files:
***toml***
```toml
executable = "tvpaint_11.5pro_attached"
schema = "avalon-core:application-1.0" …
```
=> Tvpaint: Deadline

openpype/hosts/maya/plugins/publish/collect_look.py, openpype/hosts/maya/plugins/publish/validate_model_content.py, openpype/settings/defaults/project_settings/maya.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Provide configurable top level group model validation.
Same as hotfix PR #2320
=> Maya: configurable model top level validation

openpype/tools/utils/assets_widget.py
Assets widget has few issues on refresh when partially transparent items are still in view which is confusing for user.
- asset model can be cleared before refresh thread starts
- clear asset model if project change
- always check existing items if it's children are same as children loaded from db
1. Make sure you have 1 project with assets hierarchy and 1 project without any assets
2. Open launcher
3. Go to project with hierarchy
4. Switch to project without hierarchy
5. Hover over view
- you should not be able to replicate the bug :)
=> Assets Widget: Clear model on project change

openpype/tools/mayalookassigner/models.py
There is one loop over dictionary where `iteritems` is called which is not Python 3 compatible.
- iterate over sorted keys and then get value from dictionary
=> Maya Look Assigner: Fix Python 3 compatibility

openpype/tools/tray/pype_tray.py
Sometimes may happen that splash is not painted properly because it's painting is interrupted with triggered logic and don't have process time to do so.
- make sure splash and tray icon are painted before triggering initialization logic
- run tray on any device
- most visible change is on linux machine Centos 7 GNOME
=> Tray: Paint splash and tray before initialization logic

openpype/tools/utils/host_tools.py
Some hosts don't have Qt Application initialized on start and triggering show of tool cause crash. Currently it broke Unreal integration.
- us Qt Application context when showing qt tools
=> Tools: Use Qt context on tools show

openpype/style/style.css, openpype/tools/settings/local_settings/apps_widget.py
- it is possible to select and copy studio path of  executable in local settings
Resolves https://github.com/pypeclub/OpenPype/issues/2310
=> Local settings: Copyable studio paths

openpype/tools/launcher/window.py
Launcher does not have enabled minimize icon on MacOs.
- set explicit window hints in launcher
=> Launcher: Minimize button on MacOs

openpype/hosts/flame/api/lib.py
Pop method in custom dictionary has default value `object()` which is called at runtime and then is checked if `default is object()` which will never be true because those are 2 different object pointers (Bug disceverd during PR https://github.com/pypeclub/OpenPype/pull/2186).
- just use passed args and kwargs to master's pop
=> Flame: Fix default argument value in custom dictionary

openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_instances.py
All TVPaint render instances have family `renderPass` but should have `render` and render layers should have `renderLayer`.
- render instances has `render` family and render layer has `renderLayer` in families
=> Webpublisher: Fix assignment of families of TVpaint instances

openpype/hosts/nuke/api/__init__.py, openpype/hosts/nuke/api/menu.py
When change of context on running Nuke session is done, the Openpype menu content is rolled back to the original avalon menu content.
Suggested team solution is to completely override avalon menu by openpype menu at start of nuke. 
1. open nuke in context and open workfile, but do not change anything in the script
2. notice the context label in Openpype menu on top
3. open workfile and open other workfile from different task or asset
4. notice the context label in openpype menu has changed according to the context
=> Nuke: fixing menu re-drawing during context change 

openpype/hosts/nuke/plugins/load/load_clip.py
- also improving code
- go to settings to your project overides `project_settings/nuke/load/LoadClip/node_name_template` and add following value "Read_{asset}_{subset}_{class_name}_{ext}", and save.
- load a subset X into nuke test scene
- open Manager and right button click at the loaded subset and go to Switch asset. 
- find another subset Y and hit confirm. 
- loader should change to other subset Y and also the name of node should change.
=> Nuke: fixing node name based on switched asset name

tools/build.sh
This is flipping logic on `--no-submodule-update` as it was wrong in linux build script. It should be same as on windows.
=> Linux : flip updating submodules logic

openpype/style/style.css
Label color of group or in-group settings entity does not change by real state.
- add the color changes tp styleshet for the label of wrapper
1. open settings ui
2. change something in group or add something to overrides
3. the wrapper label should change color based on the state of entity
=> Settings: Fix state change of wrapper label

openpype/lib/avalon_context.py, openpype/plugins/publish/collect_anatomy_context_data.py, openpype/plugins/publish/collect_anatomy_instance_data.py, openpype/tools/workfiles/app.py, website/docs/admin_settings_project_anatomy.md
A simple proposal to add the parent in the  path templating construction.
=> OpenPypeV3: Add key parent asset to path templating construction

Dockerfile.centos7
Add xcb libs directly to OpenPype during docker build.
Centos 7 might miss some libraries needed for Qt to work. They would need to be installed on every machine OpenPype runs on. This is copying these libraries directly to bundled PySide2 so it can find them and work with them without installing them separately.
This is quite hackich approach but since we are doing it anyway with other libs, lets close both eyes and keep it that way. At least until someone finds better solution.
=> Centos 7 dependency compatibility

openpype/hosts/maya/plugins/publish/collect_look.py
CollectLook throw an error when running on a scene using "Message" Attribute
```
File "C:\Users\jlorrain\PycharmProjects\OpenPype_build\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
runner(*args)
File "C:\Users\jlorrain\PycharmProjects\OpenPype_build\openpype\hosts\maya\plugins\publish\collect_look.py", line 228, in process
File "C:\Users\jlorrain\PycharmProjects\OpenPype_build\openpype\hosts\maya\plugins\publish\collect_look.py", line 313, in collect
File "C:\Users\jlorrain\PycharmProjects\OpenPype_build\openpype\hosts\maya\plugins\publish\collect_look.py", line 493, in collect_attributes_changed
RuntimeError: Message attributes have no data values.
```
Here is a fix
=> [Fix][MAYA] Handle message type attribute within CollectLook

openpype/hosts/maya/plugins/load/load_image_plane.py
I need to import images published of design in maya on the front and side view to serve as blueprint for the modeling. We add the optional possibility of having fixed and visible plane images in all windows.
=> Maya: Add is_static_image_plane and is_in_all_views option in imagePlaneLoader

openpype/settings/lib.py
Function `get_general_environments` does not use sytem settings but all default settings which cause crash if overrides do not have set environments.
- use system setttings as base for finding environments instead of all default values
=> General: Fix access to environments from default settings

openpype/tools/settings/settings/base.py, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/widgets.py
Add ability to use values from different project in setting UI.
Add new action to project settings that will allow on right click use values for the entity from different project. This won't use only overriden values but all values. The menu is available only if entity is not "dynamic entity" and there are projects which ca be used as source. Modifying default values won't show any action items.
- Settings UI will show `Apply values from` menu with list of project names from which values can be applied
- a dialog with message is shown if something goes wrong
- all actions will show `Working...` overlay when are triggered
- What should error dialog tell to user? Now tells that something went wrong and traceback is in detail.
- Is `Apply values from` understandable?
=> Enhancement: Settings: Use project settings values from another project

openpype/hosts/blender/hooks/pre_pyside_install.py
Prelaunch hook installing PySide2 into Blender does not work with new 3.0 version and placeholder color set after showing may not be propagated in some cases.
- regex searching for versioned subfolder of Blender has been modified to also expect `3.x` version
=> Blender 3: Support auto install for new blender version

openpype/tools/utils/widgets.py
Change of placeholder color may not be propagated when done after showing for some PySide2 versions. Happened to me in Blender 3.0.
- set placeholder font color on initialization instead of after show
- placeholder color should be white-ish where `PlaceholderLineEdit` is used
=> Fix: Placeholder Input color set fix

openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Sync to avalon does not check object type on recreation which can cause crash because of missing object type on ftrack server.
This is edge case issue which can happen when object type was removed or renamed in ftrack and entity with published stuff was removed. On recreation it tries to use entity type which was stored to avalon at the moment of last sync but it is not available anymore.
- check existence of entity type before recreation and use default `"Folder"` object type if the stored one is not available
1. Create new ObjectType in ftrack for testing purposes
2. Create ftrack entity that has the new ObjectType
3. Run sync to avalon
4. Publish something in the entity
5. Delete the entity and the OPbjectType from ftrack
6. Run sync to avalon which should recreate the entity as …
=> Ftrack: Check existence of object type on recreation

openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
AfterEffects variant 2022 has default values in settings but there are not schemas that would add them or give ability to modify them.
- added 2022 variant to schemas
=> AfterEffects: Variant 2022 is in defaults but missing in schemas

openpype/settings/entities/base_entity.py, openpype/settings/entities/dict_conditional.py, openpype/settings/entities/dict_immutable_keys_entity.py, openpype/settings/entities/dict_mutable_keys_entity.py, openpype/settings/entities/input_entities.py, openpype/settings/entities/item_entities.py, openpype/settings/entities/list_entity.py, openpype/settings/entities/root_entities.py, openpype/tools/settings/settings/breadcrumbs_widget.py
Passing path to breadcrumbs path can create new entities which is unwanted in most of cases.
Path that lead to dynamic entities may create new entities if do not exists. E.g. can create new children in modifiable dictionary or in list. This is not an issue in most of cases but it is possible to have set path to dynamic item which was removed before hitting save. On reloading after save the new entity is created which may be confusing for user.
- added new abstract method for settings entities `has_child_with_key` which will check if entity has passed key as child
- breadcrumbs path is not brute forced but is using new method `has_child_with_key` to find out if the path is valid
=> Settings UI: Breadcrumbs path does not create new entities

openpype/hosts/photoshop/plugins/publish/validate_naming.py, openpype/settings/defaults/project_settings/photoshop.json, openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Repair Action of ValidateNaming pluging was modifying subset name incorrectly.
If published layer name contained invalid value (whitespace) Repair action mangled subset name (subset didnt contain variant).
This add possibility to configure invalid characters by regular expression and cleaned up replacements
Closes #2275
- create layer with invalid name ( "05 walls light" )
- create layer with valid name ("06_walls_light")
- Publish
- ValidateNaming plugin should complain that first subset contains invalid charactes, press `Repair` on them
- run Publish again, this time validate shouldn't trigger
- compare both created subset in `Subset Manager`, focus on presence of family (`image`), variant ('Main`) and format of both subset names
=> PS: Introduced settings for invalid characters to use in ValidateNaming plugin

openpype/settings/entities/dict_mutable_keys_entity.py
Entity type ~`modifiable-dict`~`dict-modifiable` does not recognize that value has change if does not have overrides and one of keys was removed.
- set override state on calling `pop` method.
1. Find entity in settings that is modifiable dictionary e.g. `project_anatomy/tasks`
2. Open settings UI
3. Make sure the entity does not have overrides (is using default values)
4. Remove one key from the entity - the UI should change color to blue
5. Save - the reloaded values should be without the key
Resolves https://github.com/pypeclub/OpenPype/issues/2035
=> Settings UI: Modifiable dictionary can't recognize change on removing key

openpype/tools/settings/settings/base.py, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/window.py
Settings entity type `label` can contain url which lead to settings entity.
Entity type label may contain link that lead to `settings://some/settings/path`. On click the path should be changed to the entity or category may change (e.g. from Project settings -> System settings). The first item in path must start with one of categories `system-settings`, `project_settings` or `project_anatomy`.
```
{
"type": "label",
"label": "Check your system settings <a href=\"settings://system_settings/modules/deadline/deadline_urls\">here</a>"
}
```
1. Add any label to schemas
2. Click on the url in settings UI
- url links can't be styled with Qt stylesheets so only way is to set style in the `<a style=\"color:red\">` tag (or using `<span>`)
Resolves: https://github.com/pypeclub/OpenPype/issues/2303
=> Settings UI: Hyperlinks to settings

openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
Baking representation was not added additive 
This issue was blocking the plugin to add representations for all baking outputs in case there were multiple.
1. open your testing workfile in nuke
2. make sure you have multiple outputs in settings on `project_setings/nuke/publish/ExtractReviewDataMov`
3. publish
4. all outputs should be published
=> Nuke: baking representations was not additive

openpype/scripts/otio_burnin.py
Currently the option the "current_frame" option for burnins is not padded
This cause the text box to move with the current frame length increasing
=> Add zero padding to otio burnins for "current_frame"

openpype/hooks/post_start_timer.py, openpype/lib/applications.py, openpype/lib/avalon_context.py, openpype/modules/default_modules/ftrack/launch_hooks/post_ftrack_changes.py, openpype/modules/default_modules/timers_manager/exceptions.py, openpype/modules/default_modules/timers_manager/launch_hooks/post_start_timer.py, openpype/modules/default_modules/timers_manager/rest_api.py, openpype/modules/default_modules/timers_manager/timers_manager.py
Currently only post launch hook starting timer is in Ftrack but it can be triggered using TimersManager.
- added new post launch hook using webserver to start timer for passed context
- ftrack post launch hook does not start timer
- removed need of `"hierarchy"` in rest api call to start timer
- replaced not used `change_timer_from_host` with static method `start_timer_with_webserver`
Resolves https://github.com/pypeclub/OpenPype/issues/1656
=> TimersManager: Start timer post launch hook

openpype/cli.py, openpype/hooks/pre_global_host_data.py, openpype/lib/applications.py, openpype/pype_commands.py, vendor/deadline/custom/plugins/GlobalJobPreLoad.py
Give ability to set different environment variables when are prepared on artist machine and on farm.
Added one more dictionary level to environment variables dictionary which is called environment group. Default group is "standard" but is not used until environment data values use it. This gives ability to not change current settings but just extend their usage.
The environment variable group level does **NOT** apply on general environment variables. General environments are set in `start.py` before openpype cli is used. 
The new dictionary level can be used before platform specific level. Example:
```
{
"ENV_KEY": {
"farm": {
"windows": "WINDOWS",
"linux": "LINUX",
"darwin": "MACOS"
}
}
}
```
It won't work if the order is swapped. This will **NOT** work and the key will be skipped:
```
{ …
```
=> General: Environment variables groups

openpype/api.py, openpype/lib/__init__.py, openpype/lib/log.py, openpype/lib/mongo.py, start.py
Replica sets may require to pass mutliple urls into mongo url (e.g.: `mongodb://localhost:27017,localhost:27018/?replicaSet=foo`).
That is not now possible because we're parsing mongo url into components for `MongoHandler`. As nothing from the decomposed url parts is at the end used we don't really need "real" connection data. This should give ability to enter any valid mongo url and not crash on logging creation.
- removed `decompose_url` and `compose_url` from openpype `lib` and `api`
- removed `compose_url` completelly
- log use default url components
- changed `decompose_url` to `_decompose_url` and use it only in `get_default_components`
- have replica set mongo
- pass mongo ulr with replica set group into igniter
- everything should work
Resolves …
=> General: MongoDB ability to specify replica set groups

openpype/hosts/photoshop/plugins/publish/help/validate_instance_asset.xml, openpype/hosts/photoshop/plugins/publish/help/validate_naming.xml, openpype/hosts/photoshop/plugins/publish/help/validate_unique_subsets.xml, openpype/hosts/photoshop/plugins/publish/validate_instance_asset.py, openpype/hosts/photoshop/plugins/publish/validate_naming.py, openpype/hosts/photoshop/plugins/publish/validate_unique_subsets.py, openpype/pipeline/__init__.py, openpype/pipeline/publish/__init__.py, openpype/pipeline/publish/lib.py, openpype/pipeline/publish/publish_plugins.py
`New Publisher` expects a bit different styles of validators. (Using our own validator exception instead of asserts.)
This PR modifies validators for Photoshop
1. Enable availability of `New Publisher` in your Local Settings
2. Try New Publisher in Photoshop, try to mess with scene to trigger validations.
=> Photoshop: New style validations for New publisher

setup.py
Pytest run as a module requires `sqlite3`. `cx_freeze` didn't copy it into build.
Added `sqlite3` into setup to force `cx_freeze` to copy it.
`openpype_console runtests` before would fail because missing module `sqlite3`.
1. create new build
2. run `openpype_console runtests ABS_PATH/tests/integration/hosts/nuke`
=> Forced cx_freeze to include sqlite3 into build 

openpype/lib/plugin_tools.py
Bug fix when using a short path for Pyblish plugins.
When filtering the Pyblish plugins, if the config data for the current host is not found, the host will be extracted from the plugin's path.
If the path is composed of less than 4 elements (including the file name), it will crash.
Even more, the crash also occurs when the config data is found, as the code extracting the host name from the path is executed regardless its need.
The error occurs in the 'filter_pyblish_plugins' function, when trying to access the components of the path up to index -4.
Additionally, the code is executed even when not needed, as it is located before testing for the defined host.
The produced exception message:
```
```
1. Define a plugin path in the settings UI ('Additional Project Plugin Paths' in the project …
=> Short Pyblish plugin path

tools/create_zip.ps1
The regex to ignore "build" folder for the cache cleaning process of the create_zip was too wide and would completely ignore the openpype folder if it was in a hierarchy containing build anywhere (e.g. C:\Users\\**build**erman\OpenPype)
Also optimized the process to clean __pycache__ first since pycache contains .pyc and .pyo
And added ".venv" to the ignored folder since openpype and repos folder are not supposed to contain any virtual env
=> Fix and improve create_zip cache cleaning filters

openpype/plugins/publish/cleanup.py, openpype/plugins/publish/cleanup_explicit.py
We need cleanup plugin that does not guess what should be removed but context already know it.
Created new cleanup plugin that will do nothing if context does not contain paths that should be removed. This approach is backwards compatible and should not affect current implementation.
Plugin is looking for 2 keys in publish `context,data`. First is `cleanupFullPaths` all paths in this list will be deleted not matter if it's file or folder path. Second is `cleanupEmptyDirs` which will remove directories if do not contain any files.
Goal is to convert each plugin that creates a files to start using this ability. This should give us ability to do it step by step, host by host.
This is first PR just adding new cleanup plugin and adding hosts filter into old one.
- added new cleanup plugin …
=> Enhancement: Global cleanup plugin that explicitly remove paths from context

openpype/hosts/unreal/api/tools_ui.py
Menu items are not defined by unreal plugin which may be complicated as plugin is compiled on project reation and then is not updated.
It is better to create menu dynamically in python and menu in Unreal will have only 2 action callbacks.
- one will show tools in a dialog which will stay until user close it
- second will show tools in popup which will close on loose of focus
- implemented the dialog and popup in openpype unreal implementation
**Menu**
**Popup**
**Dialog**
||Depends on|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/401|
|unreal-plugin|https://github.com/pypeclub/avalon-unreal-integration/pull/3|
Resolves https://github.com/pypeclub/OpenPype/issues/2370
=> Unreal: Dynamic menu created in Python

openpype/hosts/maya/plugins/publish/extract_look.py
Now it uses path to vendorized OIIO utilities.
Previously it expected `maketx` utility installed on PATH even we vendor OIIO utilities ourselves. This PR standardizes approach a bit
Closes #2386
Run publish in Maya in any of the look workfiles, it shouldn't fail in ExtractReview phase
=> Maya: Replaced PATH usage with vendored oiio path for maketx utility

openpype/hosts/harmony/plugins/publish/help/validate_audio.xml, openpype/hosts/harmony/plugins/publish/help/validate_instances.xml, openpype/hosts/harmony/plugins/publish/help/validate_scene_settings.xml, openpype/hosts/harmony/plugins/publish/validate_audio.py, openpype/hosts/harmony/plugins/publish/validate_instances.py, openpype/hosts/harmony/plugins/publish/validate_scene_settings.py
`New Publisher` expects a bit different styles of validators. (Using our own validator exception instead of asserts.)
This PR modifies validators for Harmony
1. Enable availability of `New Publisher` in your Local Settings
2. Try New Publisher in Harmony, try to mess with scene to trigger validations.
=> Harmony: Added new style validations for New Publisher

openpype/tools/loader/app.py
- Fixes an error that is produced when in the Loader selecting a Subset and then clicking in the empty area below subsets (basically deselecting a subset). Previously it would error:
```python
```
- This also reorders some of the code so variables are closer to where they are used to avoid confusion. Now it's clearer `version_docs` isn't actually used up to where it's now defined.
=> Fix error when clicking on empty Subset area in Loader after having a Subset active

openpype/hooks/pre_create_extra_workdir_folders.py, openpype/lib/__init__.py, openpype/lib/path_tools.py, openpype/modules/default_modules/ftrack/event_handlers_user/action_create_folders.py, openpype/settings/defaults/project_settings/global.json, openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json, openpype/tools/workfiles/app.py
In some cases workflow requires folders next to workfile and it would be handy to create them automatically based on task context.
Added settings nad function to create extra folders in workdir based on context. Settings are profile based on host name, task name and task type and each profile may define list of folders that will be created. List of folders may contain nested folder structure when string contain `/` in string.
- remove `sw_folders` from settings and it's usage from Create Folders action
- not sure if this feature is used so it is a question if it make sense to keep it?
- replaced `sw_folders` with `extra_folders` settings
- implemented function `create_workdir_extra_folders` which is using `extra_folders` settings
- run `create_workdir_extra_folders` on application launch …
=> General: Workdir extra folders

openpype/hosts/tvpaint/plugins/create/create_render_layer.py
First sentence is brief description.
- make dialog shown in create render layer always on top
- run TVPaint
- select layer with group (e.g. Red color) and create Render Layer with name 'Test'
- select layer with a different group (e.g. Blue color) and create Render Layer with name 'Test'
- a dialog should show up with message which should be visible on top of Creator tool
=> TVPaint: Create render layer dialog is in front

openpype/tools/utils/assets_widget.py, openpype/tools/utils/tasks_widget.py
Be able to create different source model for assets widget and tasks widget.
In some cases it is better to use different model for assets and tasks widget which is based on different source of data. For example when a tool is querying asset documents for it's purposes then triggers refresh of assets widget. In that case the same data are queried twice which makes loading of tool slower. At the same time a tool may require custom filtering of assets or tasks which is not possible right now. Both use cases would require to create whole new asset or task widget for the tool which is duplication of code.
- tasks and asset widget have methods to create model and proxy model
- this way it is easy to inherit from the class and override those methods to define different source of data
- clearing …
=> Tools: Be able to change models of tasks and assets widgets

openpype/tools/publisher/control.py, openpype/tools/pyblish_pype/control.py, openpype/tools/pyblish_pype/window.py
Defered execution in publish pype makes processing much slower because of deffering.
Reduced defering of execution to minimum using main thread process helper. Which tries to execute methods each 10 ms (if there are any). This approach makes publishing faster and should also allow repaint of UI.
- copied main thread processor from new publisher (and slightly modified) to publish pype
- converted current methods to use new processor to reduce waiting time
- didn't test actions
- didn't test long time plugins properly but collect ftrack api (takes 1s +/-) stopped and UI was painted
1. Run publish
2. Check speed
*3. Try to run any action (repair etc.)
=> Publish pype: Reduce publish process defering

openpype/hosts/maya/plugins/publish/collect_history.py
Also felt like this Collector was running a bit slower than I liked.
Optimizations:
- `maya.cmds.listHistory` returns duplicates if multiple nodes have the same node in history, thus making them unique with `set` reduces tons of items continuing through all the commands (biggest speed improvement here)
- `cmds.ls(type="renderLayer")` now without input nodes. History tends to be so big that calling the command with those nodes as arguments produces a big overhead, simultaneously amount of renderlayers usually tend to be relatively small. So we just get all renderlayers and filter ourselves.
- use `fastIteration` flag in Maya 2020+ (about 10-20% speed difference in my tests)
=> Maya: Improve speed of Collect History logic

openpype/hosts/maya/plugins/publish/validate_rig_controllers.py
The code implemented with [this commit](https://github.com/pypeclub/OpenPype/commit/127a167224c10dac532dccf805204db67f46e7e1) by @tokejepsen prints "error" messages in my script editor in both Maya 2020 and 2022.
For example:
```
```
_For sake of example I just quickly added a cube as "controller"_
The script continues fine but it's a confusing/annoying side effect and because it prints so many in the Script Editor it also slows down the validation.
This code change avoids the error and still correctly skips the usedAsProxy attributes as intended originally.
Note that it's using [`maya.cmds.addAttr` flag `exists=True`](https://help.autodesk.com/cloudhelp/2017/ENU/Maya-Tech-Docs/CommandsPython/addAttr.html#flagexists) instead of checking whether the attribute itself exists with …
=> Maya: Validate Rig Controllers - fix Error: in script editor

openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/plugins/load/load_reference.py
Options added :
- attach_to_root : wether or not a group should contain reference
---
name: Feature request
about: Suggest an idea for this project
title: Add options to ReferenceLoader
labels: enhancement
assignees: ''
---
**Is your feature request related to a problem? Please describe.**
When an asset is referenced, a group  `subset`_`asset`_:_GRP is created
For our workflow already using a root node with a special name this group is
redundant and even an annoyance.
**Describe the solution you'd like**
Loaders have the possibility to receive options yet none were developped for ReferenceLoader.
So the pull request is about adding "attach_to_root" as an option.
Option is set by default as True to keep legacy loader behaviour
**Describe alternatives you've considered**
Huu ... Making …
=> Maya : add option to not group reference in ReferenceLoader

openpype/modules/avalon_apps/avalon_app.py, openpype/plugins/load/delivery.py
Library loader used in host without parent widget should be always on top but that is not true for tray.
Remove always on top flag from loader window in tray so it is possible to move it to back and front.
- removed unused attribute `avalon_mongo_url` from avalon module
- library loader in tray does not have always on top flag
- delivery loader will show dialog always on top and uses openpype style
Resolves https://github.com/pypeclub/OpenPype/issues/2479
=> Loader: Remove always on top flag in tray

openpype/hosts/maya/plugins/publish/validate_mesh_normals_unlocked.py
Implement a faster check for this Validate Locked Normals validator.
A quick test here on a very large asset we had laying around the speed difference is 9.5s before and 1.0s after. It's much faster.
=> Maya: Optimize Validate Locked Normals speed for dense polymeshes

openpype/lib/avalon_context.py
Custom template filter key `task_type` does not match data in profiles where is `task_types`.
- fix filter key from `task_type` to `task_types`
=> General: Custom template paths filter fix

openpype/hosts/maya/plugins/publish/validate_mesh_ngons.py
Re-use the code that is already in `openpype.host.maya.api.lib` to maintain less code.
But more importantly with https://github.com/pypeclub/OpenPype/pull/2447 merged this also means this validation will be much faster on dense meshes.
=> Maya: Validate NGONs re-use polyConstraint code from openpype.host.maya.api.lib

openpype/tools/workfiles/app.py
Files view in Workfiles tool is disabled and without files on first show.
- trigger on task changed in set context method to trigger update of files view
=> Workfiles tool: Files widget show files on first show

openpype/lib/anatomy.py
It seems that anatomy sets environments in `os.environ` as unicode type in Python 2 host which cause issues in subprocess.Popen.
- make sure anatomy does not return unicode strings
=> General: Anatomy does not return root envs as unicode

openpype/style/__init__.py, openpype/tools/creator/widgets.py, openpype/tools/creator/window.py, openpype/tools/loader/widgets.py, openpype/tools/utils/__init__.py, openpype/tools/utils/error_dialog.py, openpype/tools/utils/widgets.py
Error dialog in loader miss styles and is under Loader window if Loader tool has flag `AlwaysOnTop`. Also traceback could be collapsible.
The error dialog does not have parent which would fix the modality and style issue. The traceback can extend the dialog to infinite size so it would be nice to have it collapsible and if the contet would be in `QTextEdit` which has scrollbars so the text size of traceback won't matter.
- crated base for error dialogs for both creating and loading
- added them to utils, they are not much generic but it can be easily changed now
- have ability to copy report data with button if the method for returning the report data returns any data
- `LoadErrorMessageBox` and `CreateErrorMessageBox` inherit from base `ErrorMessageBox`
- parent is passed to …
=> Tools: Fix style and modality of errors in loader and creator

openpype/lib/python_module_tools.py
Lib function `modules_from_path` does not have unified output type.
- unified output of `modules_from_path` function
=> General: Modules import function output fix

openpype/settings/entities/op_version_entity.py
Settings crash if OpenPypeVersion from igniter is not available.
Missing OpenPypeVersion can happen when build is older than 3.8.0 or when settings entities are loaded in non-OpenPype process.
- validate if `get_remote_versions` returns `None` when getting hints for versions
=> General: Settings work if OpenPypeVersion is available

openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/hosts/aftereffects/plugins/load/load_background.py
Creator error was handled but non standard custom widget. This replaces it.
The error window should be always put on top, it contains collapsible 
1. Create subset with Creator
2. Try to create it again, it should throw error
=> AE: fix hiding of alert window below Publish

openpype/modules/default_modules/ftrack/ftrack_module.py, openpype/modules/default_modules/ftrack/ftrack_server/ftrack_server.py, openpype/settings/defaults/system_settings/modules.json, openpype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
Ftrack event handler settings can't define multiplatform paths.
- added option to define platform specific paths to ftrack event handlers
- changed labels in settings
- ftrack event server will try format paths with environments so it is possible enter environmets into user/server paths in settings
=> Ftrack: Event handlers settings

openpype/hosts/tvpaint/plugins/publish/help/validate_asset_name.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_duplicated_layer_names.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_layers_visibility.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_marks.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_missing_layer_names.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_render_pass_group.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_scene_settings.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_start_frame.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_workfile_metadata.xml, openpype/hosts/tvpaint/plugins/publish/help/validate_workfile_project_name.xml, openpype/hosts/tvpaint/plugins/publish/validate_asset_name.py, openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py, openpype/hosts/tvpaint/plugins/publish/validate_layers_visibility.py, openpype/hosts/tvpaint/plugins/publish/validate_marks.py, openpype/hosts/tvpaint/plugins/publish/validate_missing_layer_names.py, openpype/hosts/tvpaint/plugins/publish/validate_render_pass_group.py, openpype/hosts/tvpaint/plugins/publish/validate_scene_settings.py, openpype/hosts/tvpaint/plugins/publish/validate_start_frame.py, openpype/hosts/tvpaint/plugins/publish/validate_workfile_metadata.py, openpype/hosts/tvpaint/plugins/publish/validate_workfile_project_name.py
Use new Exception for validation errors inside TVPaint validators.
1. Check the xml and their texts
2. OPTIONAL: Enable new publisher
3. OPTIONAL: Start publishing of TVPaint file and go through each validator
=> TVPaint: Use new publisher exceptions in validators
